<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 4. Madurez y capacidad de proceso: SPICE y CMMI – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-95bfa606010d176c52cfb6b551730f65.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/index.html">Unidad 3. Estándares de calidad aplicados al software</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html">Tema 4. Madurez de procesos: SPICE y CMMI</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Calidad del software y estándares de calidad</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-01-que-es-calidad-quien-la-define/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es la calidad y quién la define</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Calidad de proceso y de producto: ISO/IEC 25010:2023</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Importancia, costo y calidad en un mundo globalizado</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Procesos de calidad del software. Modelos y métricas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-01-sqa-relacion-ingenieria/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es el SQA y su relación con la ingeniería de software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La calidad en cada fase del ciclo de vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-03-roles-habilidades/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Roles, responsabilidades y habilidades del personal de SQA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-04-actividades-sqa/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Actividades del SQA: revisiones, auditorías y gestión de configuración</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-05-modelos-metricas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Modelos y métricas de calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-06-herramientas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 6. Herramientas de SQA en la industria</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 3. Estándares de calidad aplicados al software</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Estándares IEEE para la calidad del software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Marcos para evaluar la usabilidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 4. Madurez de procesos: SPICE y CMMI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 4. Validación y verificación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Métodos, metodologías y estándares de verificación y validación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Validación y verificación de requisitos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-03-control-costo-calidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Control de la calidad y costo de la calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Nomenclatura y certificación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-05-factores-atam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Factores que determinan la calidad y el método ATAM</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#objetivo-y-resultado-de-aprendizaje" id="toc-objetivo-y-resultado-de-aprendizaje" class="nav-link active" data-scroll-target="#objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</a></li>
  <li><a href="#ruta-de-estudio" id="toc-ruta-de-estudio" class="nav-link" data-scroll-target="#ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</a></li>
  <li><a href="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" id="toc-el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="nav-link" data-scroll-target="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</a></li>
  <li><a href="#parte-1.-la-pregunta-común" id="toc-parte-1.-la-pregunta-común" class="nav-link" data-scroll-target="#parte-1.-la-pregunta-común"><span class="header-section-number">4</span> Parte 1. La pregunta común</a></li>
  <li><a href="#parte-2.-isoiec-33000-y-la-retirada-de-la-15504" id="toc-parte-2.-isoiec-33000-y-la-retirada-de-la-15504" class="nav-link" data-scroll-target="#parte-2.-isoiec-33000-y-la-retirada-de-la-15504"><span class="header-section-number">5</span> Parte 2. ISO/IEC 33000 y la retirada de la 15504</a>
  <ul class="collapse">
  <li><a href="#los-documentos-de-la-serie-que-importan-aquí" id="toc-los-documentos-de-la-serie-que-importan-aquí" class="nav-link" data-scroll-target="#los-documentos-de-la-serie-que-importan-aquí">Los documentos de la serie que importan aquí</a></li>
  <li><a href="#dos-modelos-que-se-combinan" id="toc-dos-modelos-que-se-combinan" class="nav-link" data-scroll-target="#dos-modelos-que-se-combinan">Dos modelos que se combinan</a></li>
  </ul></li>
  <li><a href="#parte-3.-la-escala-de-calificación-n-p-l-y-f" id="toc-parte-3.-la-escala-de-calificación-n-p-l-y-f" class="nav-link" data-scroll-target="#parte-3.-la-escala-de-calificación-n-p-l-y-f"><span class="header-section-number">6</span> Parte 3. La escala de calificación N, P, L y F</a>
  <ul class="collapse">
  <li><a href="#el-refinamiento-de-p-y-l" id="toc-el-refinamiento-de-p-y-l" class="nav-link" data-scroll-target="#el-refinamiento-de-p-y-l">El refinamiento de P y L</a></li>
  <li><a href="#quién-pone-el-porcentaje" id="toc-quién-pone-el-porcentaje" class="nav-link" data-scroll-target="#quién-pone-el-porcentaje">Quién pone el porcentaje</a></li>
  </ul></li>
  <li><a href="#parte-4.-niveles-de-capacidad-0-a-5-y-los-nueve-atributos-de-proceso" id="toc-parte-4.-niveles-de-capacidad-0-a-5-y-los-nueve-atributos-de-proceso" class="nav-link" data-scroll-target="#parte-4.-niveles-de-capacidad-0-a-5-y-los-nueve-atributos-de-proceso"><span class="header-section-number">7</span> Parte 4. Niveles de capacidad 0 a 5 y los nueve atributos de proceso</a>
  <ul class="collapse">
  <li><a href="#los-nueve-atributos-con-sus-nombres-vigentes" id="toc-los-nueve-atributos-con-sus-nombres-vigentes" class="nav-link" data-scroll-target="#los-nueve-atributos-con-sus-nombres-vigentes">Los nueve atributos con sus nombres vigentes</a></li>
  <li><a href="#cómo-se-deriva-el-nivel-a-partir-de-las-letras" id="toc-cómo-se-deriva-el-nivel-a-partir-de-las-letras" class="nav-link" data-scroll-target="#cómo-se-deriva-el-nivel-a-partir-de-las-letras">Cómo se deriva el nivel a partir de las letras</a></li>
  </ul></li>
  <li><a href="#parte-5.-automotive-spice-4.0-y-los-procesos-swe" id="toc-parte-5.-automotive-spice-4.0-y-los-procesos-swe" class="nav-link" data-scroll-target="#parte-5.-automotive-spice-4.0-y-los-procesos-swe"><span class="header-section-number">8</span> Parte 5. Automotive SPICE 4.0 y los procesos SWE</a>
  <ul class="collapse">
  <li><a href="#los-procesos-de-ingeniería-de-software" id="toc-los-procesos-de-ingeniería-de-software" class="nav-link" data-scroll-target="#los-procesos-de-ingeniería-de-software">Los procesos de ingeniería de software</a></li>
  <li><a href="#qué-evidencia-pide-un-proceso-prácticas-base-y-prácticas-genéricas" id="toc-qué-evidencia-pide-un-proceso-prácticas-base-y-prácticas-genéricas" class="nav-link" data-scroll-target="#qué-evidencia-pide-un-proceso-prácticas-base-y-prácticas-genéricas">Qué evidencia pide un proceso: prácticas base y prácticas genéricas</a></li>
  <li><a href="#quién-evalúa" id="toc-quién-evalúa" class="nav-link" data-scroll-target="#quién-evalúa">Quién evalúa</a></li>
  </ul></li>
  <li><a href="#parte-6.-ejemplo-resuelto-calificar-swe.1-en-la-app-de-turnos" id="toc-parte-6.-ejemplo-resuelto-calificar-swe.1-en-la-app-de-turnos" class="nav-link" data-scroll-target="#parte-6.-ejemplo-resuelto-calificar-swe.1-en-la-app-de-turnos"><span class="header-section-number">9</span> Parte 6. Ejemplo resuelto: calificar SWE.1 en la app de turnos</a>
  <ul class="collapse">
  <li><a href="#paso-1.-definir-el-alcance" id="toc-paso-1.-definir-el-alcance" class="nav-link" data-scroll-target="#paso-1.-definir-el-alcance">Paso 1. Definir el alcance</a></li>
  <li><a href="#paso-2.-nivel-1-el-proceso-logra-su-propósito-pa-1.1" id="toc-paso-2.-nivel-1-el-proceso-logra-su-propósito-pa-1.1" class="nav-link" data-scroll-target="#paso-2.-nivel-1-el-proceso-logra-su-propósito-pa-1.1">Paso 2. Nivel 1: ¿el proceso logra su propósito? (PA 1.1)</a></li>
  <li><a href="#paso-3.-nivel-2-se-gestiona-el-proceso-pa-2.1-y-pa-2.2" id="toc-paso-3.-nivel-2-se-gestiona-el-proceso-pa-2.1-y-pa-2.2" class="nav-link" data-scroll-target="#paso-3.-nivel-2-se-gestiona-el-proceso-pa-2.1-y-pa-2.2">Paso 3. Nivel 2: ¿se gestiona el proceso? (PA 2.1 y PA 2.2)</a></li>
  <li><a href="#paso-4.-derivar-el-nivel" id="toc-paso-4.-derivar-el-nivel" class="nav-link" data-scroll-target="#paso-4.-derivar-el-nivel">Paso 4. Derivar el nivel</a></li>
  <li><a href="#paso-5.-qué-mejorar-y-re-evaluar" id="toc-paso-5.-qué-mejorar-y-re-evaluar" class="nav-link" data-scroll-target="#paso-5.-qué-mejorar-y-re-evaluar">Paso 5. Qué mejorar y re-evaluar</a></li>
  </ul></li>
  <li><a href="#parte-7.-cmmi-v3.0" id="toc-parte-7.-cmmi-v3.0" class="nav-link" data-scroll-target="#parte-7.-cmmi-v3.0"><span class="header-section-number">10</span> Parte 7. CMMI v3.0</a>
  <ul class="collapse">
  <li><a href="#los-ocho-dominios" id="toc-los-ocho-dominios" class="nav-link" data-scroll-target="#los-ocho-dominios">Los ocho dominios</a></li>
  <li><a href="#áreas-de-práctica-grupos-de-práctica-y-niveles" id="toc-áreas-de-práctica-grupos-de-práctica-y-niveles" class="nav-link" data-scroll-target="#áreas-de-práctica-grupos-de-práctica-y-niveles">Áreas de práctica, grupos de práctica y niveles</a></li>
  <li><a href="#qué-no-se-pudo-verificar" id="toc-qué-no-se-pudo-verificar" class="nav-link" data-scroll-target="#qué-no-se-pudo-verificar">Qué no se pudo verificar</a></li>
  </ul></li>
  <li><a href="#parte-8.-niveles-de-madurez-y-apreciaciones" id="toc-parte-8.-niveles-de-madurez-y-apreciaciones" class="nav-link" data-scroll-target="#parte-8.-niveles-de-madurez-y-apreciaciones"><span class="header-section-number">11</span> Parte 8. Niveles de madurez y apreciaciones</a>
  <ul class="collapse">
  <li><a href="#niveles-de-capacidad-de-cmmi-por-área-de-práctica" id="toc-niveles-de-capacidad-de-cmmi-por-área-de-práctica" class="nav-link" data-scroll-target="#niveles-de-capacidad-de-cmmi-por-área-de-práctica">Niveles de capacidad de CMMI (por área de práctica)</a></li>
  <li><a href="#tabla-de-niveles-de-madurez-por-unidad-de-la-organización" id="toc-tabla-de-niveles-de-madurez-por-unidad-de-la-organización" class="nav-link" data-scroll-target="#tabla-de-niveles-de-madurez-por-unidad-de-la-organización">Tabla de niveles de madurez (por unidad de la organización)</a></li>
  <li><a href="#los-cuatro-tipos-de-apreciación" id="toc-los-cuatro-tipos-de-apreciación" class="nav-link" data-scroll-target="#los-cuatro-tipos-de-apreciación">Los cuatro tipos de apreciación</a></li>
  </ul></li>
  <li><a href="#parte-9.-subir-de-nivel-qué-significa-y-cuánto-cuesta" id="toc-parte-9.-subir-de-nivel-qué-significa-y-cuánto-cuesta" class="nav-link" data-scroll-target="#parte-9.-subir-de-nivel-qué-significa-y-cuánto-cuesta"><span class="header-section-number">12</span> Parte 9. Subir de nivel: qué significa y cuánto cuesta</a>
  <ul class="collapse">
  <li><a href="#qué-cambia-al-subir" id="toc-qué-cambia-al-subir" class="nav-link" data-scroll-target="#qué-cambia-al-subir">Qué cambia al subir</a></li>
  <li><a href="#qué-dice-la-evidencia-sobre-el-costo" id="toc-qué-dice-la-evidencia-sobre-el-costo" class="nav-link" data-scroll-target="#qué-dice-la-evidencia-sobre-el-costo">Qué dice la evidencia sobre el costo</a></li>
  <li><a href="#lo-que-sí-se-sabe-de-precios-hoy" id="toc-lo-que-sí-se-sabe-de-precios-hoy" class="nav-link" data-scroll-target="#lo-que-sí-se-sabe-de-precios-hoy">Lo que sí se sabe de precios hoy</a></li>
  </ul></li>
  <li><a href="#parte-10.-spice-contra-cmmi" id="toc-parte-10.-spice-contra-cmmi" class="nav-link" data-scroll-target="#parte-10.-spice-contra-cmmi"><span class="header-section-number">13</span> Parte 10. SPICE contra CMMI</a>
  <ul class="collapse">
  <li><a href="#los-nombres-se-parecen-los-niveles-no-son-equivalentes" id="toc-los-nombres-se-parecen-los-niveles-no-son-equivalentes" class="nav-link" data-scroll-target="#los-nombres-se-parecen-los-niveles-no-son-equivalentes">Los nombres se parecen, los niveles no son equivalentes</a></li>
  <li><a href="#cuándo-conviene-cada-uno" id="toc-cuándo-conviene-cada-uno" class="nav-link" data-scroll-target="#cuándo-conviene-cada-uno">Cuándo conviene cada uno</a></li>
  </ul></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes"><span class="header-section-number">14</span> Errores frecuentes</a></li>
  <li><a href="#autoevaluación" id="toc-autoevaluación" class="nav-link" data-scroll-target="#autoevaluación"><span class="header-section-number">15</span> Autoevaluación</a></li>
  <li><a href="#lo-que-te-llevas" id="toc-lo-que-te-llevas" class="nav-link" data-scroll-target="#lo-que-te-llevas"><span class="header-section-number">16</span> Lo que te llevas</a></li>
  <li><a href="#glosario" id="toc-glosario" class="nav-link" data-scroll-target="#glosario"><span class="header-section-number">17</span> Glosario</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">18</span> Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/index.html">Unidad 3. Estándares de calidad aplicados al software</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html">Tema 4. Madurez de procesos: SPICE y CMMI</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 4. Madurez y capacidad de proceso: SPICE y CMMI</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">3 de octubre de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 3. Estándares de calidad aplicados al software</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 4. Madurez y capacidad de proceso: SPICE y CMMI</td>
</tr>
</tbody>
</table>
</div>
<p><a href="../presentacion-interactiva.html" class="btn-curso">Presentación interactiva de la unidad</a></p>
<p>Tema anterior: <a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html">Tema 3. Usabilidad</a>. Tema siguiente: <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html">Unidad 4, Tema 1. Métodos y estándares de validación y verificación</a>.</p>
<section id="objetivo-y-resultado-de-aprendizaje" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</h2>
<p>Este tema cierra la Unidad 3. Los tres anteriores trataron de estándares que miran el documento, el producto o la organización completa. Este mira el proceso con el que se construye el software y responde una pregunta que interesa a cualquier cliente serio: qué tan fiable es la manera de trabajar de un equipo, más allá de un proyecto con suerte.</p>
<p>Dos marcos responden esa pregunta. SPICE, que hoy se apoya en la familia ISO/IEC 33000, califica cada proceso con una escala de capacidad. CMMI, mantenido por ISACA, califica la capacidad de áreas de práctica y también la madurez de una unidad de la organización. Aquí aprendes los dos, los comparas y descubres cuánto cuesta subir de nivel.</p>
<p>Al terminar puedes:</p>
<ul>
<li>Explicar por qué la norma ISO/IEC 15504 está retirada y qué la reemplazó, con fechas.</li>
<li>Aplicar la escala de calificación N, P, L y F y derivar el nivel de capacidad de un proceso a partir de sus atributos.</li>
<li>Nombrar los nueve atributos de proceso con los nombres de la norma vigente ISO/IEC 33020 y señalar qué cambió respecto de la 15504.</li>
<li>Describir los procesos de ingeniería de software (SWE) de Automotive SPICE 4.0 y qué evidencia pide cada uno.</li>
<li>Calificar un proceso de la app de turnos con un ejemplo resuelto paso a paso.</li>
<li>Explicar la estructura de CMMI v3.0 (dominios, áreas de práctica, niveles de capacidad y de madurez) y sus cuatro tipos de apreciación.</li>
<li>Interpretar con criterio lo que se sabe y lo que no se sabe sobre el tiempo y el dinero que cuesta subir de nivel.</li>
<li>Elegir entre SPICE y CMMI según la pregunta que se quiere responder.</li>
</ul>
<p>Prerrequisitos: el Tema 2 de esta unidad (familias ISO) y los temas 2 y 4 de la Unidad 2 (calidad en el ciclo de vida, actividades de aseguramiento de la calidad). Necesitas distinguir <em>proceso</em> de <em>producto</em> y saber qué es una evidencia objetiva.</p>
</section>
<section id="ruta-de-estudio" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</h2>
<p>Son unas 7 horas de trabajo independiente. Puedes partirlas en cuatro sesiones. La presentación interactiva de la unidad sigue estas mismas partes, así que sirve como primera mirada o como repaso.</p>
<div class="calendario">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parte</th>
<th>Qué haces</th>
<th>Tiempo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. La pregunta común</td>
<td>Distingues capacidad de proceso y madurez de organización</td>
<td>25 min</td>
</tr>
<tr class="even">
<td>2. ISO/IEC 33000 y la retirada de la 15504</td>
<td>Lees las fechas y la estructura de la familia</td>
<td>30 min</td>
</tr>
<tr class="odd">
<td>3. La escala N, P, L y F</td>
<td>Aprendes los porcentajes y resuelves el Reto 1</td>
<td>35 min</td>
</tr>
<tr class="even">
<td>4. Niveles de capacidad 0 a 5</td>
<td>Estudias los nueve atributos y resuelves el Reto 2</td>
<td>45 min</td>
</tr>
<tr class="odd">
<td>5. Automotive SPICE 4.0</td>
<td>Lees los procesos SWE y cómo se aplican</td>
<td>40 min</td>
</tr>
<tr class="even">
<td>6. Ejemplo resuelto: calificar SWE.1</td>
<td>Sigues el cálculo completo y resuelves el Reto 3</td>
<td>55 min</td>
</tr>
<tr class="odd">
<td>7. CMMI v3.0</td>
<td>Lees la estructura del modelo y lo que no se pudo verificar</td>
<td>50 min</td>
</tr>
<tr class="even">
<td>8. Niveles de madurez y apreciaciones</td>
<td>Estudias la tabla de niveles y resuelves el Reto 4</td>
<td>45 min</td>
</tr>
<tr class="odd">
<td>9. Subir de nivel: qué significa y cuánto cuesta</td>
<td>Lees la evidencia disponible y resuelves el Reto 5</td>
<td>40 min</td>
</tr>
<tr class="even">
<td>10. SPICE contra CMMI</td>
<td>Comparas los dos marcos y resuelves el Reto 6</td>
<td>30 min</td>
</tr>
<tr class="odd">
<td>Cierre</td>
<td>Autoevaluación y glosario</td>
<td>30 min</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</h2>
<p>Todo el curso usa un producto ficticio, una app que asigna turnos médicos. Su requisito de partida es “la app asigna hasta 20 turnos por día a cada especialidad”. En este tema la clínica contrata a un equipo de desarrollo y el equipo se pregunta qué tan sólido es su proceso. Con ese equipo calificas un proceso real de la norma (análisis de requisitos de software) y estimas el costo de mejorar. Ninguna cifra de la clínica es real. Cada vez que aparece un número propio, el texto lo marca como ilustrativo.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Cómo se verificó esta guía
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los datos de esta guía se contrastaron en octubre de 2026 con fuentes primarias: los catálogos de ISO, el modelo de evaluación Automotive SPICE 4.0 publicado por la VDA, los materiales de ISACA y del CMMI Institute, y un informe técnico del Software Engineering Institute (SEI). La norma ISO/IEC 33020 es de pago y no se pudo leer completa. Sus nombres y reglas se tomaron del texto que el modelo Automotive SPICE reproduce con licencia de ISO, y se parafrasean aquí. Lo que no se pudo confirmar en fuente primaria queda señalado como tal en cada parte.</p>
</div>
</div>
</section>
<section id="parte-1.-la-pregunta-común" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="parte-1.-la-pregunta-común"><span class="header-section-number">4</span> Parte 1. La pregunta común</h2>
<p>Un equipo que entregó bien un proyecto no demuestra que sabe entregar bien. Puede haber sido talento individual, un cliente fácil o suerte. Los modelos de proceso intentan separar el resultado de una vez de la capacidad repetible, bajo la idea de que un proceso bien gestionado produce resultados más predecibles que uno improvisado.</p>
<p>SPICE y CMMI comparten esa idea y la miden de forma distinta. Para no confundirlos desde el principio, fíjate en dos palabras que aparecen todo el tiempo.</p>
<ul>
<li><strong>Capacidad.</strong> Qué tan bien funciona un proceso concreto, por ejemplo el análisis de requisitos. Se mide con una escala por proceso.</li>
<li><strong>Madurez.</strong> Qué tan consolidada está la forma de trabajar de una unidad de la organización, medida sobre un conjunto de áreas a la vez.</li>
</ul>
<p>SPICE califica capacidad de procesos, uno por uno. CMMI califica capacidad por área de práctica y, además, madurez de una unidad organizacional. El título del tema nombra ambas porque cada marco usa las dos palabras con su propio significado, y la Parte 10 las compara con detalle.</p>
<div class="diagrama">
<svg viewbox="0 0 760 270" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Dos unidades de análisis. En SPICE cada proceso de un proyecto recibe su propio nivel de capacidad, por ejemplo requisitos nivel 2, diseño nivel 1 y pruebas nivel 3, sin un nivel consolidado. En CMMI un conjunto predefinido de áreas de práctica da un nivel de madurez para una unidad de la organización, y cada área puede además tener su nivel de capacidad" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t4a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs><text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Qué se califica en cada marco</text><rect x="20" y="34" width="350" height="216" rx="12" fill="#f5f7fa" stroke="#cfd8e3"></rect><text x="195" y="58" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">SPICE: cada proceso aparte</text><g fill="#eef4fa" stroke="#c7d6e6"><rect x="44" y="76" width="140" height="34" rx="8"></rect><rect x="44" y="120" width="140" height="34" rx="8"></rect><rect x="44" y="164" width="140" height="34" rx="8"></rect></g><g font-size="11.5" fill="#12324f"><text x="56" y="98">Requisitos (SWE.1)</text><text x="56" y="142">Diseño (SWE.3)</text><text x="56" y="186">Pruebas (SWE.4)</text></g><g fill="#e4f2f1" stroke="#8fc9c5"><rect x="230" y="76" width="110" height="34" rx="8"></rect><rect x="230" y="120" width="110" height="34" rx="8"></rect><rect x="230" y="164" width="110" height="34" rx="8"></rect></g><g font-size="11.5" font-weight="600" fill="#0e6f6c" text-anchor="middle"><text x="285" y="98">nivel 2</text><text x="285" y="142">nivel 1</text><text x="285" y="186">nivel 3</text></g><g fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#u3t4a)"><path d="M184,93 L228,93"></path><path d="M184,137 L228,137"></path><path d="M184,181 L228,181"></path></g><text x="195" y="228" font-size="11" fill="#5b6876" text-anchor="middle">No existe un nivel consolidado del proyecto</text><rect x="390" y="34" width="350" height="216" rx="12" fill="#f5f7fa" stroke="#cfd8e3"></rect><text x="565" y="58" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">CMMI: dos lecturas del mismo modelo</text><rect x="410" y="76" width="310" height="52" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect><text x="565" y="98" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">Un área de práctica</text><text x="565" y="116" font-size="11" fill="#0e6f6c" text-anchor="middle">nivel de capacidad, de 0 a 3</text><rect x="410" y="142" width="310" height="52" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect><text x="565" y="164" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">Conjunto predefinido de áreas de práctica</text><text x="565" y="182" font-size="11" fill="#0e6f6c" text-anchor="middle">nivel de madurez de la unidad, de 0 a 5</text><text x="565" y="222" font-size="11" fill="#5b6876" text-anchor="middle">La unidad evaluada es la que define el alcance</text>
</svg>
</div>
</section>
<section id="parte-2.-isoiec-33000-y-la-retirada-de-la-15504" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="parte-2.-isoiec-33000-y-la-retirada-de-la-15504"><span class="header-section-number">5</span> Parte 2. ISO/IEC 33000 y la retirada de la 15504</h2>
<p><em>SPICE</em> es la sigla de <em>Software Process Improvement and Capability dEtermination</em>. Nació como un proyecto internacional que produjo la norma ISO/IEC 15504, y la industria conservó el nombre aunque la norma cambió. Hoy conviene decir “SPICE” para el enfoque y citar la familia ISO/IEC 33000 para el documento vigente.</p>
<p>Según el catálogo de ISO, la parte 1 de la norma 15504 (conceptos y vocabulario, edición de 2004) se retiró el 27 de febrero de 2015, y la parte 2 (realización de una evaluación, edición de 2003) se retiró el 3 de marzo de 2015. Ambas fueron reemplazadas por documentos de la serie 33000 publicados en marzo de 2015. En el catálogo de ISO, esos documentos figuran como publicados y confirmados.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>ISO/IEC 15504 está retirada
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una oferta de trabajo, un contrato o una herramienta que mencione “ISO/IEC 15504” usa una referencia obsoleta. El documento vigente es de la serie 33000. Todo lo que ves en esta guía sobre atributos de proceso y escala de calificación sale de la 33020:2019 y no de la 15504, y más abajo se señala dónde cambian los nombres.</p>
</div>
</div>
<section id="los-documentos-de-la-serie-que-importan-aquí" class="level3">
<h3 class="anchored" data-anchor-id="los-documentos-de-la-serie-que-importan-aquí">Los documentos de la serie que importan aquí</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Documento</th>
<th>Edición y estado en el catálogo de ISO</th>
<th>Qué define</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ISO/IEC 33001</td>
<td>2015, vigente</td>
<td>Conceptos y terminología de la evaluación de procesos</td>
</tr>
<tr class="even">
<td>ISO/IEC 33002</td>
<td>2015, vigente</td>
<td>Requisitos para realizar una evaluación de procesos</td>
</tr>
<tr class="odd">
<td>ISO/IEC 33003</td>
<td>2015, vigente</td>
<td>Requisitos para los marcos de medición de procesos</td>
</tr>
<tr class="even">
<td>ISO/IEC 33004</td>
<td>2015, con versión corregida de 2017, vigente</td>
<td>Requisitos para modelos de referencia de procesos, modelos de evaluación y modelos de madurez</td>
</tr>
<tr class="odd">
<td>ISO/IEC 33020</td>
<td>2019 (edición 2), vigente</td>
<td>Marco de medición para evaluar la capacidad de un proceso</td>
</tr>
<tr class="even">
<td>ISO/IEC 33020</td>
<td>2015 (edición 1), retirada el 21 de noviembre de 2019</td>
<td>Reemplazada por la edición de 2019</td>
</tr>
</tbody>
</table>
<p>La serie 33000 tiene más documentos, entre ellos modelos de evaluación para procesos concretos. Esta guía usa solo los cinco de la tabla, que son los que fijan la escala y las reglas de evaluación.</p>
</section>
<section id="dos-modelos-que-se-combinan" class="level3">
<h3 class="anchored" data-anchor-id="dos-modelos-que-se-combinan">Dos modelos que se combinan</h3>
<p>En SPICE, describir un proceso y medir qué tan bien se ejecuta son dos trabajos distintos.</p>
<ul>
<li><strong>Modelo de referencia de procesos</strong> (<em>Process Reference Model</em>, PRM). Lista los procesos de un dominio y dice el propósito y los resultados de cada uno.</li>
<li><strong>Modelo de evaluación de procesos</strong> (<em>Process Assessment Model</em>, PAM). Toma esos procesos y añade los indicadores con los que un evaluador reúne evidencia y juzga.</li>
</ul>
<p>La norma 33004 fija cómo se construyen ambos. Automotive SPICE define su propio PRM y su propio PAM y los publica juntos en un documento, lo que verás en la Parte 5. En CMMI, en cambio, el modelo de buenas prácticas y la forma de calificarlo viven en un mismo marco, de modo que no hay dos documentos con esos nombres.</p>
<div class="diagrama">
<svg viewbox="0 0 760 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Línea de tiempo con fechas verificadas. 1991 primera versión del Software CMM. 2015 marzo publicación de las normas ISO/IEC 33001 a 33004 y retiro de partes de la 15504. 2019 noviembre edición de 2019 de la 33020. Abril de 2023 anuncio de CMMI v3.0 por ISACA. 29 de noviembre de 2023 fecha del modelo Automotive SPICE 4.0" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t4b" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs><text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Hitos con fecha confirmada en fuente primaria</text><path d="M40,100 L720,100" stroke="#c7d6e6" stroke-width="2.5" fill="none"></path><g fill="#0e6f6c"><circle cx="90" cy="100" r="7"></circle><circle cx="235" cy="100" r="7"></circle><circle cx="380" cy="100" r="7"></circle><circle cx="525" cy="100" r="7"></circle><circle cx="670" cy="100" r="7"></circle></g><g fill="none" stroke="#8fb3d1" stroke-width="1.5"><path d="M90,107 L90,132"></path><path d="M235,107 L235,132"></path><path d="M380,107 L380,132"></path><path d="M525,107 L525,132"></path><path d="M670,107 L670,132"></path></g><g fill="#eef4fa" stroke="#c7d6e6"><rect x="20" y="134" width="140" height="94" rx="10"></rect><rect x="165" y="134" width="140" height="94" rx="10"></rect><rect x="310" y="134" width="140" height="94" rx="10"></rect><rect x="455" y="134" width="140" height="94" rx="10"></rect><rect x="600" y="134" width="140" height="94" rx="10"></rect></g><g text-anchor="middle" font-size="12" font-weight="700" fill="#12324f"><text x="90" y="78">1991</text><text x="235" y="78">Marzo de 2015</text><text x="380" y="78">Noviembre de 2019</text><text x="525" y="78">Abril de 2023</text><text x="670" y="78">29 nov. 2023</text></g><g text-anchor="middle" font-size="11" font-weight="600" fill="#12324f"><text x="90" y="156">Software CMM</text><text x="235" y="156">Serie 33000</text><text x="380" y="156">ISO/IEC 33020</text><text x="525" y="156">CMMI v3.0</text><text x="670" y="156">ASPICE PAM 4.0</text></g><g text-anchor="middle" font-size="10" fill="#5b6876"><text x="90" y="176">primera versión, raíz</text><text x="90" y="190">de CMMI según ISACA</text><text x="235" y="176">33001 a 33004 salen y</text><text x="235" y="190">se retira la 15504</text><text x="380" y="176">edición 2, reemplaza</text><text x="380" y="190">a la de 2015</text><text x="525" y="176">ISACA anuncia la</text><text x="525" y="190">versión el 10 de abril</text><text x="670" y="176">fecha del documento</text><text x="670" y="190">publicado por la VDA</text></g>
</svg>
</div>
</section>
</section>
<section id="parte-3.-la-escala-de-calificación-n-p-l-y-f" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="parte-3.-la-escala-de-calificación-n-p-l-y-f"><span class="header-section-number">6</span> Parte 3. La escala de calificación N, P, L y F</h2>
<p>En SPICE no se califica un proceso con un solo número de entrada. Primero se califica cada <em>atributo de proceso</em> (una propiedad medible de la capacidad) y después se deriva el nivel. Cada atributo recibe una de cuatro letras según qué parte de él se logró.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Letra</th>
<th>Nombre</th>
<th>Porcentaje de logro</th>
<th>Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>N</td>
<td>No logrado</td>
<td>de 0 a 15</td>
<td>Hay poca o ninguna evidencia de que el atributo se logre</td>
</tr>
<tr class="even">
<td>P</td>
<td>Parcialmente logrado</td>
<td>más de 15 hasta 50</td>
<td>Hay un enfoque y algo de logro, y algunos aspectos pueden ser impredecibles</td>
</tr>
<tr class="odd">
<td>L</td>
<td>Ampliamente logrado</td>
<td>más de 50 hasta 85</td>
<td>Hay un enfoque sistemático y un logro significativo, con algunas debilidades</td>
</tr>
<tr class="even">
<td>F</td>
<td>Plenamente logrado</td>
<td>más de 85 hasta 100</td>
<td>Hay un enfoque completo y sistemático, sin debilidades significativas</td>
</tr>
</tbody>
</table>
<p>La escala es ordinal: una letra describe un tramo del porcentaje, no un valor exacto. Los porcentajes y las descripciones son los de ISO/IEC 33020:2019, tal como los reproduce el modelo Automotive SPICE 4.0.</p>
<section id="el-refinamiento-de-p-y-l" class="level3">
<h3 class="anchored" data-anchor-id="el-refinamiento-de-p-y-l">El refinamiento de P y L</h3>
<p>La norma permite dividir P y L en dos mitades, útil cuando el equipo evaluador debe distinguir mejor. Según un artículo de ISACA sobre la adaptación de COBIT a la serie 33000, los tramos son estos.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Refinamiento</th>
<th>Porcentaje de logro</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P-</td>
<td>más de 15 hasta 32,5</td>
</tr>
<tr class="even">
<td>P+</td>
<td>más de 32,5 hasta 50</td>
</tr>
<tr class="odd">
<td>L-</td>
<td>más de 50 hasta 67,5</td>
</tr>
<tr class="even">
<td>L+</td>
<td>más de 67,5 hasta 85</td>
</tr>
</tbody>
</table>
<p>N y F no se dividen. El refinamiento no cambia cómo se deriva el nivel, que depende de las letras N, P, L y F.</p>
</section>
<section id="quién-pone-el-porcentaje" class="level3">
<h3 class="anchored" data-anchor-id="quién-pone-el-porcentaje">Quién pone el porcentaje</h3>
<p>El porcentaje es un juicio del equipo evaluador sobre la evidencia que reunió, no una fórmula. La norma 33020 admite tres métodos de calificación (R1, R2 y R3) que se diferencian en cómo se agregan los resultados de varias instancias del proceso, y el evaluador líder decide cuál usar y lo declara en el informe. El detalle de cada método está en la norma de pago y esta guía no lo reproduce.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Pon la letra
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un equipo evaluador estima el logro de cuatro atributos de proceso: 12 por ciento, 48 por ciento, 67 por ciento y 86 por ciento. Escribe la letra de la escala básica de cada uno y su refinamiento cuando corresponda.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>12 por ciento: N, porque está entre 0 y 15.</li>
<li>48 por ciento: P, y con refinamiento P+, porque está sobre 32,5 y no pasa de 50.</li>
<li>67 por ciento: L, y con refinamiento L-, porque está sobre 50 y no pasa de 67,5.</li>
<li>86 por ciento: F, porque pasa de 85. F no tiene refinamiento.</li>
</ul>
<p>Un 85 por ciento exacto sería L+, no F. El límite de F es “más de 85”.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-4.-niveles-de-capacidad-0-a-5-y-los-nueve-atributos-de-proceso" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="parte-4.-niveles-de-capacidad-0-a-5-y-los-nueve-atributos-de-proceso"><span class="header-section-number">7</span> Parte 4. Niveles de capacidad 0 a 5 y los nueve atributos de proceso</h2>
<p>El nivel de capacidad de un proceso va de 0 a 5. Cada nivel se define con uno o dos atributos, y la suma da nueve atributos desde el nivel 1 en adelante. Los nombres vigentes son los de ISO/IEC 33020:2019.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Nivel</th>
<th>Nombre</th>
<th>Qué se espera del proceso</th>
<th>Atributos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>Incompleto</td>
<td>El proceso no está implementado o no logra su propósito</td>
<td>ninguno</td>
</tr>
<tr class="even">
<td>1</td>
<td>Ejecutado (<em>Performed</em>)</td>
<td>El proceso implementado logra su propósito</td>
<td>PA 1.1</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Gestionado (<em>Managed</em>)</td>
<td>Se planifica, monitorea y ajusta, y sus productos de trabajo se establecen, controlan y mantienen</td>
<td>PA 2.1, PA 2.2</td>
</tr>
<tr class="even">
<td>3</td>
<td>Establecido (<em>Established</em>)</td>
<td>Se implementa con un proceso definido capaz de lograr sus resultados</td>
<td>PA 3.1, PA 3.2</td>
</tr>
<tr class="odd">
<td>4</td>
<td>Predecible (<em>Predictable</em>)</td>
<td>Opera de forma predecible dentro de límites definidos, con datos para hallar las causas de variación</td>
<td>PA 4.1, PA 4.2</td>
</tr>
<tr class="even">
<td>5</td>
<td>Innovador (<em>Innovating</em>)</td>
<td>Se mejora de forma continua para responder a cambios de la organización</td>
<td>PA 5.1, PA 5.2</td>
</tr>
</tbody>
</table>
<div class="diagrama">
<svg viewbox="0 0 760 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Escalera de los seis niveles de capacidad de ISO/IEC 33020. Nivel 0 Incompleto sin atributos. Nivel 1 Ejecutado con el atributo desempeño del proceso. Nivel 2 Gestionado con gestión del desempeño y gestión de productos de trabajo. Nivel 3 Establecido con definición y despliegue del proceso. Nivel 4 Predecible con análisis cuantitativo y control cuantitativo. Nivel 5 Innovador con innovación del proceso e implementación de la innovación" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t4c" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs><text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Seis niveles de capacidad y sus atributos</text><rect x="14" y="250" width="112" height="60" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect><rect x="134" y="220" width="112" height="90" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="254" y="190" width="112" height="120" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="374" y="160" width="112" height="150" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="494" y="130" width="112" height="180" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="614" y="100" width="112" height="210" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect><g text-anchor="middle" font-size="11" font-weight="700" fill="#12324f"><text x="70" y="272">Nivel 0</text><text x="190" y="242">Nivel 1</text><text x="310" y="212">Nivel 2</text><text x="430" y="182">Nivel 3</text><text x="550" y="152">Nivel 4</text><text x="670" y="122">Nivel 5</text></g><g text-anchor="middle" font-size="10.5" font-weight="600" fill="#0e6f6c"><text x="70" y="288">Incompleto</text><text x="190" y="258">Ejecutado</text><text x="310" y="228">Gestionado</text><text x="430" y="198">Establecido</text><text x="550" y="168">Predecible</text><text x="670" y="138">Innovador</text></g><g text-anchor="middle" font-size="9.5" fill="#5b6876"><text x="70" y="302">sin atributos</text><text x="190" y="276">PA 1.1</text><text x="310" y="246">PA 2.1 y 2.2</text><text x="430" y="216">PA 3.1 y 3.2</text><text x="550" y="186">PA 4.1 y 4.2</text><text x="670" y="156">PA 5.1 y 5.2</text></g><text x="670" y="180" font-size="10" fill="#3c7d7a" text-anchor="middle">cada nivel suma</text><text x="670" y="194" font-size="10" fill="#3c7d7a" text-anchor="middle">atributos a los</text><text x="670" y="208" font-size="10" fill="#3c7d7a" text-anchor="middle">de los niveles</text><text x="670" y="222" font-size="10" fill="#3c7d7a" text-anchor="middle">anteriores</text><text x="380" y="60" font-size="11" fill="#5b6876" text-anchor="middle">La escalera exige que los niveles de abajo estén plenamente cubiertos</text>
</svg>
</div>
<section id="los-nueve-atributos-con-sus-nombres-vigentes" class="level3">
<h3 class="anchored" data-anchor-id="los-nueve-atributos-con-sus-nombres-vigentes">Los nueve atributos con sus nombres vigentes</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Nivel</th>
<th>Atributo (33020:2019)</th>
<th>Qué mide</th>
<th>Nombre en la 15504, si cambió</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>PA 1.1 Desempeño del proceso (<em>Process performance</em>)</td>
<td>Hasta dónde se logra el propósito del proceso</td>
<td>igual</td>
</tr>
<tr class="even">
<td>2</td>
<td>PA 2.1 Gestión del desempeño del proceso (<em>Performance management</em>)</td>
<td>Que el desempeño se gestione con objetivos, plan, recursos, seguimiento e interfaces</td>
<td>igual</td>
</tr>
<tr class="odd">
<td>2</td>
<td>PA 2.2 Gestión de productos de trabajo (<em>Work product management</em>)</td>
<td>Que los productos del proceso estén definidos, controlados y revisados</td>
<td>igual</td>
</tr>
<tr class="even">
<td>3</td>
<td>PA 3.1 Definición del proceso (<em>Process definition</em>)</td>
<td>Que exista un proceso estándar mantenido</td>
<td>igual</td>
</tr>
<tr class="odd">
<td>3</td>
<td>PA 3.2 Despliegue del proceso (<em>Process deployment</em>)</td>
<td>Que ese proceso estándar se adapte y se use en los proyectos</td>
<td>igual</td>
</tr>
<tr class="even">
<td>4</td>
<td>PA 4.1 Análisis cuantitativo (<em>Quantitative analysis</em>)</td>
<td>Que se definan necesidades de información, relaciones entre elementos y datos a recoger</td>
<td>Medición del proceso</td>
</tr>
<tr class="odd">
<td>4</td>
<td>PA 4.2 Control cuantitativo (<em>Quantitative control</em>)</td>
<td>Que los datos objetivos se usen para controlar un desempeño predecible</td>
<td>Control del proceso</td>
</tr>
<tr class="even">
<td>5</td>
<td>PA 5.1 Innovación del proceso (<em>Process innovation</em>)</td>
<td>Que se identifiquen oportunidades de mejora a partir de los objetivos de negocio</td>
<td>igual</td>
</tr>
<tr class="odd">
<td>5</td>
<td>PA 5.2 Implementación de la innovación del proceso (<em>Process innovation implementation</em>)</td>
<td>Que las mejoras aprobadas se pongan en práctica de forma efectiva</td>
<td>Optimización del proceso</td>
</tr>
</tbody>
</table>
<p>El nombre del nivel 5 también cambió, de <em>Optimizing</em> en la 15504 a <em>Innovating</em> en la 33020. Las guías antiguas (incluida la versión previa de este tema) usan los nombres de la 15504 para los atributos 4.1, 4.2 y 5.2 y para el nivel 5. Quien encuentre “Medición del proceso” o “Nivel 5, optimización” está leyendo la terminología retirada. La fuente de los cambios es el modelo Automotive SPICE 4.0, que reproduce los nombres de la 33020:2019, y el artículo de ISACA que marca esos tres atributos como renombrados.</p>
</section>
<section id="cómo-se-deriva-el-nivel-a-partir-de-las-letras" class="level3">
<h3 class="anchored" data-anchor-id="cómo-se-deriva-el-nivel-a-partir-de-las-letras">Cómo se deriva el nivel a partir de las letras</h3>
<p>La regla general que fija la norma es esta: para alcanzar un nivel, sus atributos deben estar ampliamente o plenamente logrados, y todos los atributos de los niveles inferiores deben estar plenamente logrados.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Para alcanzar el nivel</th>
<th>PA 1.1</th>
<th>PA 2.1 y 2.2</th>
<th>PA 3.1 y 3.2</th>
<th>PA 4.1 y 4.2</th>
<th>PA 5.1 y 5.2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>L o F</td>
<td>no se exigen</td>
<td>no se exigen</td>
<td>no se exigen</td>
<td>no se exigen</td>
</tr>
<tr class="even">
<td>2</td>
<td>F</td>
<td>L o F</td>
<td>no se exigen</td>
<td>no se exigen</td>
<td>no se exigen</td>
</tr>
<tr class="odd">
<td>3</td>
<td>F</td>
<td>F</td>
<td>L o F</td>
<td>no se exigen</td>
<td>no se exigen</td>
</tr>
<tr class="even">
<td>4</td>
<td>F</td>
<td>F</td>
<td>F</td>
<td>L o F</td>
<td>no se exigen</td>
</tr>
<tr class="odd">
<td>5</td>
<td>F</td>
<td>F</td>
<td>F</td>
<td>F</td>
<td>L o F</td>
</tr>
</tbody>
</table>
<p>La consecuencia práctica es que un solo atributo bajo bloquea el nivel aunque los de arriba estén muy bien. Un equipo con gestión del desempeño plenamente lograda y productos de trabajo en P se queda en el nivel 1, por buena que sea su planificación. El Reto 2 y el ejemplo de la Parte 6 trabajan justo esa regla.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Deriva el nivel
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un proceso recibe estas letras: PA 1.1 en F, PA 2.1 en F, PA 2.2 en L, PA 3.1 en L y PA 3.2 en P. ¿Qué nivel de capacidad alcanza? Justifica con la tabla de derivación, y di qué atributo habría que subir para llegar al nivel 3.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>El proceso alcanza el nivel 2. Para el nivel 2 se pide PA 1.1 en F, que se cumple, y PA 2.1 y PA 2.2 en L o F, que también se cumple porque están en F y L.</p>
<p>No llega al nivel 3 por dos razones. PA 3.2 está en P y se pide L o F. Además, para el nivel 3 también se exige PA 2.2 plenamente logrado (F), y está en L.</p>
<p>Hay que subir dos atributos, PA 3.2 hasta L o F y PA 2.2 hasta F. Subir solo uno no alcanza.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-5.-automotive-spice-4.0-y-los-procesos-swe" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="parte-5.-automotive-spice-4.0-y-los-procesos-swe"><span class="header-section-number">8</span> Parte 5. Automotive SPICE 4.0 y los procesos SWE</h2>
<p><em>Automotive SPICE</em> es la aplicación de SPICE a los sistemas basados en software de los vehículos. Según la VDA, la asociación alemana de la industria automotriz, el estándar se publicó por primera vez en 2005 y su versión vigente es la 4.0. La elaboró el grupo de trabajo 13 del centro de calidad de la VDA (VDA QMC). El documento con los modelos de referencia y de evaluación lleva fecha del 29 de noviembre de 2023 y es una revisión de la versión 3.1.</p>
<p>La VDA lo describe como un modelo de dos dimensiones. La dimensión de proceso contiene los 32 procesos del modelo, en 3 categorías y 11 grupos. La dimensión de capacidad contiene los seis niveles de capacidad de la serie 33000. Cada proceso incluido en el alcance recibe su propio nivel, y la VDA aclara que no existe un nivel consolidado para un proyecto ni para una empresa.</p>
<section id="los-procesos-de-ingeniería-de-software" class="level3">
<h3 class="anchored" data-anchor-id="los-procesos-de-ingeniería-de-software">Los procesos de ingeniería de software</h3>
<p>El grupo SWE reúne los seis procesos con los que se construye y verifica el software. Todos conservan el patrón de la V: lo que se especifica a la izquierda se verifica a la derecha.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Proceso</th>
<th>Nombre en el PAM 4.0</th>
<th>Propósito, resumido</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SWE.1</td>
<td>Análisis de requisitos de software (<em>Software Requirements Analysis</em>)</td>
<td>Establecer requisitos de software estructurados y analizados, consistentes con los requisitos y la arquitectura del sistema</td>
</tr>
<tr class="even">
<td>SWE.2</td>
<td>Diseño arquitectónico de software (<em>Software Architectural Design</em>)</td>
<td>Establecer una arquitectura analizada, con aspectos estáticos y dinámicos, consistente con los requisitos</td>
</tr>
<tr class="odd">
<td>SWE.3</td>
<td>Diseño detallado y construcción de unidades (<em>Software Detailed Design and Unit Construction</em>)</td>
<td>Establecer el diseño detallado y construir las unidades de software coherentes con él</td>
</tr>
<tr class="even">
<td>SWE.4</td>
<td>Verificación de unidades de software (<em>Software Unit Verification</em>)</td>
<td>Verificar que las unidades de software son consistentes con el diseño detallado</td>
</tr>
<tr class="odd">
<td>SWE.5</td>
<td>Verificación de componentes y de integración (<em>Software Component Verification and Integration Verification</em>)</td>
<td>Verificar los componentes contra la arquitectura e integrar y verificar los elementos integrados</td>
</tr>
<tr class="even">
<td>SWE.6</td>
<td>Verificación de software (<em>Software Verification</em>)</td>
<td>Verificar que el software integrado es consistente con los requisitos de software</td>
</tr>
</tbody>
</table>
<p>La validación (<em>Validation</em>) pasó a tener su propio grupo, con el proceso VAL.1. El PAM 4.0 también trae grupos de ingeniería de aprendizaje automático (MLE) y de ingeniería de hardware (HWE), además de los de sistema (SYS), adquisición (ACQ), suministro (SPL), apoyo (SUP), gestión (MAN), mejora de procesos (PIM) y reutilización (REU).</p>
<p>La comparación detallada con la versión 3.1, por ejemplo cómo se llamaban antes SWE.5 y SWE.6, no se verificó contra el documento de la 3.1. Quien la necesite debe leer ambos PAM.</p>
</section>
<section id="qué-evidencia-pide-un-proceso-prácticas-base-y-prácticas-genéricas" class="level3">
<h3 class="anchored" data-anchor-id="qué-evidencia-pide-un-proceso-prácticas-base-y-prácticas-genéricas">Qué evidencia pide un proceso: prácticas base y prácticas genéricas</h3>
<p>Cada proceso del grupo trae <em>prácticas base</em> (<em>base practices</em>, BP), que son actividades que indican si el proceso logra su propósito. Sirven de evidencia para el nivel 1. Para los niveles 2 en adelante, el PAM usa <em>prácticas genéricas</em> (<em>generic practices</em>, GP), que valen para cualquier proceso porque miden cómo se gestiona, no qué hace.</p>
<p>Como ejemplo, SWE.1 en la versión 4.0 define siete resultados esperados y seis prácticas base.</p>
<ul>
<li>BP1. Especificar los requisitos de software.</li>
<li>BP2. Estructurar y priorizar los requisitos.</li>
<li>BP3. Analizar los requisitos (corrección y factibilidad técnica).</li>
<li>BP4. Analizar el impacto sobre el entorno de operación.</li>
<li>BP5. Asegurar consistencia y establecer trazabilidad bidireccional.</li>
<li>BP6. Comunicar los requisitos acordados y su impacto.</li>
</ul>
<p>El atributo PA 2.1 se apoya en seis prácticas genéricas, de GP 2.1.1 a GP 2.1.6: definir objetivos y estrategia, planificar, determinar necesidades de recursos, hacer disponibles los recursos, monitorear y ajustar, y gestionar las interfaces entre las partes. PA 2.2 usa cuatro: definir los requisitos de los productos de trabajo, definir los de almacenamiento y control, identificar y controlar los productos, y revisarlos y ajustarlos.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Lo que la VDA no publica en abierto
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los contratos de la industria suelen fijar un nivel de capacidad mínimo y un alcance de procesos. El nivel que cada fabricante exige y el alcance exacto no están en los documentos públicos consultados y no se afirman aquí.</p>
</div>
</div>
</section>
<section id="quién-evalúa" class="level3">
<h3 class="anchored" data-anchor-id="quién-evalúa">Quién evalúa</h3>
<p>La VDA QMC es el único organismo de certificación de personas para Automotive SPICE. Certifica a los evaluadores según el esquema internacional intacs (<em>International Assessor Certification Scheme</em>). La licencia de evaluador dura tres años y se renueva. Al consultar la página de la VDA en octubre de 2026, el registro mostraba 7619 evaluadores de Automotive SPICE en 51 países. Para un proveedor, eso significa que una evaluación con valor para un cliente automotriz la hace un evaluador certificado, no el propio equipo.</p>
</section>
</section>
<section id="parte-6.-ejemplo-resuelto-calificar-swe.1-en-la-app-de-turnos" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="parte-6.-ejemplo-resuelto-calificar-swe.1-en-la-app-de-turnos"><span class="header-section-number">9</span> Parte 6. Ejemplo resuelto: calificar SWE.1 en la app de turnos</h2>
<p>La Clínica Aurora quiere saber cómo está el proceso de análisis de requisitos de software de su app. El equipo usa un evaluador externo ficticio que aplica el PAM 4.0. Todos los porcentajes de este ejemplo son juicios ilustrativos de ese evaluador, no datos reales.</p>
<section id="paso-1.-definir-el-alcance" class="level3">
<h3 class="anchored" data-anchor-id="paso-1.-definir-el-alcance">Paso 1. Definir el alcance</h3>
<p>El proceso es SWE.1. Se evalúa el proyecto “módulo de asignación de turnos”, cuyo requisito de partida es “la app asigna hasta 20 turnos por día a cada especialidad”. Se revisan el repositorio de requisitos, las actas de revisión y se entrevista a la analista y al líder técnico.</p>
</section>
<section id="paso-2.-nivel-1-el-proceso-logra-su-propósito-pa-1.1" class="level3">
<h3 class="anchored" data-anchor-id="paso-2.-nivel-1-el-proceso-logra-su-propósito-pa-1.1">Paso 2. Nivel 1: ¿el proceso logra su propósito? (PA 1.1)</h3>
<p>El evaluador contrasta las seis prácticas base de SWE.1 con lo que halló.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Práctica base</th>
<th>Evidencia hallada</th>
<th>Juicio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BP1 Especificar</td>
<td>46 requisitos escritos en el gestor de tareas, con criterio de verificación en 41</td>
<td>Casi completa</td>
</tr>
<tr class="even">
<td>BP2 Estructurar y priorizar</td>
<td>Agrupados por especialidad y con prioridad en todos</td>
<td>Completa</td>
</tr>
<tr class="odd">
<td>BP3 Analizar</td>
<td>Se analizó la factibilidad del límite de 20 turnos, falta el análisis de correctitud de los requisitos de cancelación</td>
<td>Parcial</td>
</tr>
<tr class="even">
<td>BP4 Impacto en el entorno</td>
<td>Se analizó el impacto sobre el envío de mensajes de texto, no sobre el sistema de historias clínicas de la clínica</td>
<td>Parcial</td>
</tr>
<tr class="odd">
<td>BP5 Trazabilidad</td>
<td>Trazas hacia los requisitos del sistema en 44 de 46</td>
<td>Casi completa</td>
</tr>
<tr class="even">
<td>BP6 Comunicar</td>
<td>Acta de la reunión de aprobación con el personal médico</td>
<td>Completa</td>
</tr>
</tbody>
</table>
<p>Con ese balance, el evaluador estima el logro de PA 1.1 en 88 por ciento, que es F.</p>
</section>
<section id="paso-3.-nivel-2-se-gestiona-el-proceso-pa-2.1-y-pa-2.2" class="level3">
<h3 class="anchored" data-anchor-id="paso-3.-nivel-2-se-gestiona-el-proceso-pa-2.1-y-pa-2.2">Paso 3. Nivel 2: ¿se gestiona el proceso? (PA 2.1 y PA 2.2)</h3>
<p>PA 2.1 tiene ocho logros esperados. El equipo tiene un plan de iteraciones, recursos asignados y seguimiento semanal. Le falta definir con claridad las responsabilidades y preparar a dos personas nuevas, y la interfaz con el equipo de la clínica se gestiona de manera informal. El evaluador estima 70 por ciento, que es L+.</p>
<p>PA 2.2 tiene cuatro logros esperados. Los requisitos viven en un gestor de tareas con control de cambios básico, pero no hay criterios definidos de contenido ni de revisión para los documentos de requisitos, no se hacen línea base y la revisión es ocasional. El evaluador estima 40 por ciento, que es P+.</p>
</section>
<section id="paso-4.-derivar-el-nivel" class="level3">
<h3 class="anchored" data-anchor-id="paso-4.-derivar-el-nivel">Paso 4. Derivar el nivel</h3>
<div class="diagrama">
<svg viewbox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Barras de logro de los tres atributos del proceso SWE.1 de la app de turnos sobre una escala de 0 a 100 por ciento con zonas N, P, L y F. PA 1.1 llega a 88 por ciento y es F. PA 2.1 llega a 70 por ciento y es L. PA 2.2 llega a 40 por ciento y es P. Como PA 2.2 no llega a L, el proceso queda en el nivel 1" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t4d" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs><text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">SWE.1 de la app de turnos, antes de mejorar</text><g fill="#f5f7fa" stroke="#cfd8e3"><rect x="160" y="50" width="75" height="150"></rect><rect x="235" y="50" width="175" height="150"></rect><rect x="410" y="50" width="175" height="150"></rect><rect x="585" y="50" width="75" height="150"></rect></g><g font-size="12" font-weight="700" fill="#5b6876" text-anchor="middle"><text x="197" y="44">N</text><text x="322" y="44">P</text><text x="497" y="44">L</text><text x="622" y="44">F</text></g><g fill="#e4f2f1" stroke="#8fc9c5"><rect x="160" y="64" width="440" height="30" rx="4"></rect></g><g fill="#eef4fa" stroke="#c7d6e6"><rect x="160" y="110" width="350" height="30" rx="4"></rect><rect x="160" y="156" width="200" height="30" rx="4"></rect></g><g font-size="11.5" fill="#12324f" text-anchor="end"><text x="150" y="84">PA 1.1</text><text x="150" y="130">PA 2.1</text><text x="150" y="176">PA 2.2</text></g><g font-size="11" font-weight="600" fill="#0e6f6c"><text x="608" y="84">88 F</text><text x="518" y="130">70 L+</text><text x="368" y="176">40 P+</text></g><g font-size="10.5" fill="#5b6876" text-anchor="middle"><text x="160" y="216">0</text><text x="235" y="216">15</text><text x="410" y="216">50</text><text x="585" y="216">85</text><text x="660" y="216">100 por ciento</text></g><rect x="130" y="238" width="500" height="46" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect><text x="380" y="258" font-size="12" font-weight="700" fill="#0e6f6c" text-anchor="middle">Resultado: nivel 1</text><text x="380" y="275" font-size="11" fill="#3c7d7a" text-anchor="middle">PA 2.2 queda en P y el nivel 2 exige L o F</text>
</svg>
</div>
<p>Se aplica la tabla de derivación de la Parte 4.</p>
<ol type="1">
<li>Nivel 1 pide PA 1.1 en L o F. Hay F. Se cumple.</li>
<li>Nivel 2 pide PA 1.1 en F, PA 2.1 en L o F y PA 2.2 en L o F. PA 1.1 está en F y PA 2.1 en L, pero PA 2.2 está en P. No se cumple.</li>
</ol>
<p>El proceso SWE.1 del proyecto queda en nivel 1. No se evalúan los niveles superiores.</p>
</section>
<section id="paso-5.-qué-mejorar-y-re-evaluar" class="level3">
<h3 class="anchored" data-anchor-id="paso-5.-qué-mejorar-y-re-evaluar">Paso 5. Qué mejorar y re-evaluar</h3>
<p>El hallazgo útil no es “nivel 1” sino “PA 2.2 es el atributo que bloquea”. El equipo ataca justo eso: define una plantilla con criterios de contenido y de revisión para el documento de requisitos, marca línea base antes de cada iteración y programa una revisión entre pares por cada versión.</p>
<p>Seis meses después, el evaluador califica de nuevo y estima PA 2.2 en 75 por ciento (L+). PA 1.1 se mantiene en 88 y PA 2.1 en 70. El proceso cumple los criterios del nivel 2. Para el nivel 3 haría falta PA 2.1 y PA 2.2 en F y que la organización tenga un proceso estándar definido (PA 3.1) y desplegado (PA 3.2) en L o F, lo que todavía no existe.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. El caso de SWE.4
</div>
</div>
<div class="callout-body-container callout-body">
<p>Otro evaluador califica SWE.4 (verificación de unidades) del mismo proyecto con estas letras: PA 1.1 en L, PA 2.1 en F y PA 2.2 en F. ¿Qué nivel alcanza el proceso y qué atributo habría que subir para llegar al nivel 2?</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Alcanza el nivel 1. Nivel 1 pide PA 1.1 en L o F y se cumple con L. Nivel 2 pide PA 1.1 en F, y ahí falla, aunque PA 2.1 y PA 2.2 estén plenamente logrados.</p>
<p>Hay que subir PA 1.1 de L a F: el proceso tiene que lograr su propósito sin debilidades significativas. Una buena gestión no compensa un proceso que todavía no logra plenamente lo que debe lograr.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-7.-cmmi-v3.0" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="parte-7.-cmmi-v3.0"><span class="header-section-number">10</span> Parte 7. CMMI v3.0</h2>
<p><em>CMMI</em> (<em>Capability Maturity Model Integration</em>) es un modelo de buenas prácticas de ISACA, que lo publica por medio del CMMI Institute. Una fuente primaria, un artículo de ISACA del 10 de abril de 2023, ubica sus raíces en el Software CMM, publicado por primera vez en 1991, y anuncia la versión 3.0 como la nueva iteración del modelo.</p>
<p>Según ISACA, la versión 2.0 de 2018 pasó a llamarse CMMI Performance Solutions, y la versión 3.0 amplía el modelo más allá del desarrollo de productos, la operación de servicios y la gestión de proveedores, hacia seguridad, seguridad funcional, gestión de datos, gestión de personas y trabajo virtual. En entrevista de marzo de 2024, un evaluador líder certificado por ISACA dice que, para quien usa CMMI en desarrollo, servicios o proveedores, el cambio será mínimo o transparente.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Recuadro. CMMI v1.3, solo como historia
</div>
</div>
<div class="callout-body-container callout-body">
<p>La versión 1.3 se publicó en 2010 por el SEI. Ofrecía dos representaciones: por etapas, con niveles de madurez 1 a 5, y continua, con niveles de capacidad por proceso. Tenía tres constelaciones separadas (desarrollo, servicios y adquisición) y el método de apreciación se llamaba SCAMPI, con las clases A, B y C. La versión 2.0 fundió las constelaciones en un modelo y reemplazó SCAMPI por el método de apreciación de CMMI.</p>
<p>Estos datos vienen de fuentes secundarias. Los documentos del SEI sobre la versión 1.3 no se pudieron consultar en esta revisión. Si encuentras “representación por etapas” o “SCAMPI clase A” en un contrato nuevo, se trata de vocabulario de la versión 1.3 y conviene preguntar a qué versión del modelo se refiere.</p>
</div>
</div>
<section id="los-ocho-dominios" class="level3">
<h3 class="anchored" data-anchor-id="los-ocho-dominios">Los ocho dominios</h3>
<p>ISACA describe la versión 3.0 como un solo modelo con ocho dominios: desarrollo, servicios, gestión de proveedores, datos, personas, seguridad funcional (<em>safety</em>), seguridad de la información (<em>security</em>) y trabajo virtual. Cada organización escoge los dominios que le sirven. La página del visor del modelo del CMMI Institute enumera siete nombres (sin proveedores como dominio aparte), de modo que la lista de ocho es la de los blogs de ISACA.</p>
<p>Para un equipo como el de la clínica, el dominio de desarrollo es el que corresponde. El de seguridad podría sumarse si la clínica exigiera protección de datos de salud.</p>
</section>
<section id="áreas-de-práctica-grupos-de-práctica-y-niveles" class="level3">
<h3 class="anchored" data-anchor-id="áreas-de-práctica-grupos-de-práctica-y-niveles">Áreas de práctica, grupos de práctica y niveles</h3>
<p>En CMMI v3.0, cada dominio se organiza en <em>áreas de práctica</em> (<em>practice areas</em>). Un artículo de ISACA de 2025 cita entre las áreas existentes Solución técnica (<em>Technical Solution</em>, TS), Verificación (<em>Verification</em>, VER) y Revisiones entre pares (<em>Peer Reviews</em>, PR), y entre las nuevas de la versión 3.0 Gestión de datos (DM), Calidad de datos (DQ) y Empoderamiento de la fuerza laboral (WE). El número total de áreas de práctica de la versión 3.0 y la lista completa no se pudieron verificar en fuente primaria accesible, porque el contenido del modelo está en un visor de suscripción.</p>
<p>Dentro de cada área, las prácticas se agrupan en <em>grupos de práctica</em> etiquetados de nivel 0 a nivel 3. Cada nivel se apoya en el anterior. Esos grupos son el origen de los niveles de capacidad que verás en la Parte 8.</p>
<div class="diagrama">
<svg viewbox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Estructura de CMMI v3.0. Un dominio contiene áreas de práctica. Cada área de práctica contiene grupos de práctica de nivel 0 a 3 que dan su nivel de capacidad. Un conjunto predefinido de áreas de práctica da el nivel de madurez de una unidad, de 0 a 5" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t4e" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs><text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Cómo se organiza el modelo CMMI v3.0</text><rect x="20" y="40" width="200" height="60" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect><text x="120" y="64" font-size="12.5" font-weight="600" fill="#12324f" text-anchor="middle">Dominio</text><text x="120" y="82" font-size="10.5" fill="#5b6876" text-anchor="middle">uno de los ocho, por ejemplo desarrollo</text><rect x="280" y="40" width="200" height="60" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect><text x="380" y="64" font-size="12.5" font-weight="600" fill="#12324f" text-anchor="middle">Áreas de práctica</text><text x="380" y="82" font-size="10.5" fill="#5b6876" text-anchor="middle">por ejemplo TS, VER y PR</text><rect x="540" y="40" width="200" height="60" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect><text x="640" y="64" font-size="12.5" font-weight="600" fill="#12324f" text-anchor="middle">Grupos de práctica</text><text x="640" y="82" font-size="10.5" fill="#5b6876" text-anchor="middle">niveles 0, 1, 2 y 3</text><g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u3t4e)"><path d="M220,70 L278,70"></path><path d="M480,70 L538,70"></path></g><rect x="540" y="140" width="200" height="60" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect><text x="640" y="164" font-size="12.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Nivel de capacidad</text><text x="640" y="182" font-size="10.5" fill="#3c7d7a" text-anchor="middle">de un área, de 0 a 3</text><path d="M640,100 L640,138" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u3t4e)"></path><rect x="280" y="140" width="200" height="60" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect><text x="380" y="164" font-size="12.5" font-weight="600" fill="#12324f" text-anchor="middle">Conjunto predefinido</text><text x="380" y="182" font-size="10.5" fill="#5b6876" text-anchor="middle">de áreas de práctica</text><path d="M380,100 L380,138" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u3t4e)"></path><rect x="280" y="236" width="200" height="50" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect><text x="380" y="258" font-size="12.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Nivel de madurez</text><text x="380" y="275" font-size="10.5" fill="#3c7d7a" text-anchor="middle">de la unidad, de 0 a 5</text><path d="M380,200 L380,234" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u3t4e)"></path>
</svg>
</div>
</section>
<section id="qué-no-se-pudo-verificar" class="level3">
<h3 class="anchored" data-anchor-id="qué-no-se-pudo-verificar">Qué no se pudo verificar</h3>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Datos de CMMI sin confirmar en fuente primaria
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>La fecha exacta de lanzamiento de la versión 3.0: ISACA anunció la versión el 10 de abril de 2023, y materiales de terceros dan el 6 de abril. La guía usa “abril de 2023”.</li>
<li>El número total de áreas de práctica de la versión 3.0 y su lista oficial.</li>
<li>Hasta cuándo se aceptaron apreciaciones de las versiones 2.0 y 2.2, y cuándo se retiró cada una. Las páginas del CMMI Institute consultadas en octubre de 2026 todavía mencionan la versión 2.0 en materiales de adopción, y el PDF de cambios de contenido de la versión 3.0 que citan buscadores ya no está disponible.</li>
<li>Si una organización puede apreciarse hoy con la versión 2.2.</li>
</ul>
<p>Antes de contratar una apreciación, pregunta al evaluador líder qué versión del modelo y del método de apreciación se aplica y qué fecha rige.</p>
</div>
</div>
</section>
</section>
<section id="parte-8.-niveles-de-madurez-y-apreciaciones" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="parte-8.-niveles-de-madurez-y-apreciaciones"><span class="header-section-number">11</span> Parte 8. Niveles de madurez y apreciaciones</h2>
<section id="niveles-de-capacidad-de-cmmi-por-área-de-práctica" class="level3">
<h3 class="anchored" data-anchor-id="niveles-de-capacidad-de-cmmi-por-área-de-práctica">Niveles de capacidad de CMMI (por área de práctica)</h3>
<p>Según el CMMI Institute, los niveles de capacidad aplican al desempeño y la mejora de una organización en áreas de práctica individuales.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Nivel</th>
<th>Nombre</th>
<th>Qué significa para el área de práctica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>Incompleto</td>
<td>Enfoque incompleto, que puede o no cumplir la intención de alguna práctica, con desempeño inconsistente</td>
</tr>
<tr class="even">
<td>1</td>
<td>Inicial</td>
<td>Enfoque inicial, con un conjunto incompleto de prácticas, que atiende problemas de desempeño</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Gestionado</td>
<td>Conjunto simple pero completo de prácticas que cubre la intención del área, sin exigir activos de la organización, y vigila el avance hacia los objetivos del proyecto</td>
</tr>
<tr class="even">
<td>3</td>
<td>Definido</td>
<td>Usa estándares de la organización y su adaptación, y busca cumplir objetivos del proyecto y de la organización</td>
</tr>
</tbody>
</table>
</section>
<section id="tabla-de-niveles-de-madurez-por-unidad-de-la-organización" class="level3">
<h3 class="anchored" data-anchor-id="tabla-de-niveles-de-madurez-por-unidad-de-la-organización">Tabla de niveles de madurez (por unidad de la organización)</h3>
<p>Los niveles de madurez representan un camino por etapas, basado en conjuntos predefinidos de áreas de práctica. Cada nivel se apoya en los anteriores.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Nivel</th>
<th>Nombre</th>
<th>Cómo describe el CMMI Institute a la organización</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>Incompleto</td>
<td>Ad hoc y desconocido. El trabajo puede o no terminarse</td>
</tr>
<tr class="even">
<td>1</td>
<td>Inicial</td>
<td>Impredecible y reactiva. El trabajo se completa pero suele retrasarse y exceder el presupuesto</td>
</tr>
<tr class="odd">
<td>2</td>
<td>Gestionado</td>
<td>Gestionada a nivel de proyecto. Los proyectos se planifican, ejecutan, miden y controlan</td>
</tr>
<tr class="even">
<td>3</td>
<td>Definido</td>
<td>Proactiva, no reactiva. Los estándares de la organización guían proyectos, programas y portafolios</td>
</tr>
<tr class="odd">
<td>4</td>
<td>Gestionado cuantitativamente</td>
<td>Medida y controlada. Se guía por datos, con objetivos cuantitativos de mejora que son predecibles y atienden las necesidades de las partes interesadas</td>
</tr>
<tr class="even">
<td>5</td>
<td>En optimización</td>
<td>Estable y flexible. Enfocada en la mejora continua y preparada para responder a oportunidades y cambios</td>
</tr>
</tbody>
</table>
<p>Los nombres de los niveles son los publicados por el CMMI Institute y se traducen aquí. Los conjuntos exactos de áreas de práctica que cada nivel de madurez exige no se pudieron verificar en fuente primaria accesible.</p>
</section>
<section id="los-cuatro-tipos-de-apreciación" class="level3">
<h3 class="anchored" data-anchor-id="los-cuatro-tipos-de-apreciación">Los cuatro tipos de apreciación</h3>
<p>Una <em>apreciación</em> es la actividad que identifica fortalezas y debilidades de los procesos de una organización y mide qué tan cerca están de las buenas prácticas de CMMI. El CMMI Institute describe cuatro tipos en su documento de definición del método.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Tipo</th>
<th>Para qué sirve</th>
<th>Calificaciones</th>
<th>Validez</th>
<th>Tamaño mínimo del equipo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Benchmark</td>
<td>Evaluación rigurosa y completa para obtener un nivel con valor ante terceros</td>
<td>Sí</td>
<td>3 años</td>
<td>4 o más, con un evaluador líder certificado</td>
</tr>
<tr class="even">
<td>Sustainment</td>
<td>Chequeo posterior a un benchmark para confirmar que se mantiene el nivel</td>
<td>Sí</td>
<td>2 años</td>
<td>2 o más, incluido el evaluador líder</td>
</tr>
<tr class="odd">
<td>Evaluation</td>
<td>Enfoque flexible y menos formal para prepararse y hallar oportunidades de mejora</td>
<td>No</td>
<td>No aplica</td>
<td>1 o más, incluido el evaluador líder</td>
</tr>
<tr class="even">
<td>Action Plan Reappraisal</td>
<td>Segunda oportunidad para quien no alcanzó por poco el nivel objetivo</td>
<td>Igual que la apreciación previa</td>
<td>Igual que la previa</td>
<td>Igual que la previa</td>
</tr>
</tbody>
</table>
<p>Reglas que el CMMI Institute precisa para estos tipos.</p>
<ul>
<li>No se pueden hacer más de tres apreciaciones sustainment seguidas antes de volver a un benchmark.</li>
<li>Para mantener la validez de la calificación previa, un sustainment debe completarse y ser aceptado por ISACA antes de que venza esa validez.</li>
<li>Una action plan reappraisal se hace dentro de los 4 meses posteriores al cierre de la apreciación previa, y solo si se falló por poco el nivel de madurez o el perfil de capacidad objetivo.</li>
<li>Los resultados publicados se registran en el sitio de resultados de apreciación (PARS) de ISACA.</li>
</ul>
<p>Una versión anterior de esta guía decía que un sustainment extiende un rating “hasta por seis años en tramos de dos”. Esa cifra no aparece en la fuente primaria. Lo que sí está confirmado es la validez de 3 años del benchmark y de 2 del sustainment, con el tope de tres sustainment seguidos.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 4. Escoge el tipo de apreciación
</div>
</div>
<div class="callout-body-container callout-body">
<p>Resuelve dos situaciones.</p>
<p>A. Una empresa obtuvo un benchmark con madurez nivel 3 hace 34 meses. Su cliente exige mantener el nivel vigente y no quiere repetir todo el proceso. B. Otra empresa se apreció hace dos meses, apuntaba al nivel 3 y quedó a muy poco. Quiere confirmar solo los puntos pendientes.</p>
<p>¿Qué tipo de apreciación encaja en cada una y qué plazo debe vigilar?</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A. Sustainment. La validez del benchmark es de 3 años, o sea 36 meses, y a los 34 faltan 2. El sustainment debe completarse y ser aceptado por ISACA antes de que venza esa validez, y no pueden hacerse más de tres seguidos antes de volver a un benchmark. Con dos meses de margen, el plazo es muy ajustado y conviene empezar ya.</p>
<p>B. Action plan reappraisal. Es el tipo para quien falló por poco el nivel objetivo. Debe completarse dentro de los 4 meses siguientes al cierre de la apreciación previa, así que quedan unos dos meses.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-9.-subir-de-nivel-qué-significa-y-cuánto-cuesta" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="parte-9.-subir-de-nivel-qué-significa-y-cuánto-cuesta"><span class="header-section-number">12</span> Parte 9. Subir de nivel: qué significa y cuánto cuesta</h2>
<section id="qué-cambia-al-subir" class="level3">
<h3 class="anchored" data-anchor-id="qué-cambia-al-subir">Qué cambia al subir</h3>
<p>Subir de nivel no es sumar documentos. Cambia quién controla el trabajo.</p>
<ul>
<li>De nivel 1 a nivel 2 (en CMMI, madurez 2 y capacidad 2; en SPICE, capacidad 2). Un proyecto planifica, mide y controla su trabajo, y gestiona sus productos de trabajo. La mejora la sostienen las personas del proyecto.</li>
<li>De nivel 2 a nivel 3. La organización define estándares y los proyectos los adaptan y los usan. Ya hay activos compartidos, como procedimientos y plantillas, que mantiene alguien además de los equipos.</li>
<li>Niveles 4 y 5. La mejora pasa a depender de datos cuantitativos y de causas de variación identificadas, con una organización preparada para cambiar de rumbo.</li>
</ul>
</section>
<section id="qué-dice-la-evidencia-sobre-el-costo" class="level3">
<h3 class="anchored" data-anchor-id="qué-dice-la-evidencia-sobre-el-costo">Qué dice la evidencia sobre el costo</h3>
<p>Hay muy pocos datos públicos de costo con método. Los que se pudieron verificar son estos, y no son del modelo vigente.</p>
<p>Un informe técnico del SEI de 1994 (Herbsleb y colaboradores, CMU/SEI-94-TR-013) recogió datos de 13 organizaciones que mejoraban procesos con el Software CMM, el modelo anterior a CMMI. Los datos los aportaron las propias organizaciones, y los autores señalan que los resultados muestran lo posible “en un entorno favorable”. Las cifras están en dólares de la época.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Medida</th>
<th>Rango</th>
<th>Mediana</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Costo anual total de las actividades de mejora</td>
<td>US$ 49.000 a US$ 1.202.000</td>
<td>US$ 245.000</td>
</tr>
<tr class="even">
<td>Años dedicados a la mejora</td>
<td>1 a 9</td>
<td>3,5</td>
</tr>
<tr class="odd">
<td>Costo de la mejora por ingeniero de software al año</td>
<td>US$ 490 a US$ 2.004</td>
<td>US$ 1.375</td>
</tr>
<tr class="even">
<td>Ganancia anual de productividad</td>
<td>9 a 67 por ciento</td>
<td>35 por ciento</td>
</tr>
<tr class="odd">
<td>Reducción anual de los reportes de defectos posteriores a la entrega</td>
<td>10 a 94 por ciento</td>
<td>39 por ciento</td>
</tr>
<tr class="even">
<td>Valor del retorno por cada dólar invertido</td>
<td>4,0 a 8,8</td>
<td>5,0</td>
</tr>
</tbody>
</table>
<p>El propio informe advierte que los valores absolutos de organizaciones distintas no son comparables, porque cada una definió defecto y línea de código a su manera, y que el retorno es de las cifras más difíciles de interpretar por cómo se asignaron costos y beneficios.</p>
<p>El mismo informe describe un caso, la División de Ingeniería de Software de Hughes Aircraft. Una primera evaluación asistida por el SEI en 1987 la halló en nivel 2, y una segunda en 1990 la halló en un nivel 3 sólido. Ir de un nivel 2 sólido a un nivel 3 sólido en dos años costó 75 personas-mes más 45.000 dólares de la evaluación asistida por el SEI, en una unidad de unos 500 profesionales.</p>
</section>
<section id="lo-que-sí-se-sabe-de-precios-hoy" class="level3">
<h3 class="anchored" data-anchor-id="lo-que-sí-se-sabe-de-precios-hoy">Lo que sí se sabe de precios hoy</h3>
<ul>
<li>El CMMI Institute describe el benchmark como el tipo con la mayor dedicación de personas, tiempo y costo, y el sustainment como de dedicación reducida. No publica un precio.</li>
<li>La suscripción de un año al visor del modelo cuesta US$ 150, y US$ 225 con contenido de madurez en inteligencia artificial, en la página consultada en octubre de 2026.</li>
<li>No se encontró en fuente primaria el costo en dinero ni en horas de una apreciación benchmark actual. Esa cifra depende del alcance y de la unidad evaluada, y se cotiza con el evaluador líder.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Cifras de beneficios que circulan
</div>
</div>
<div class="callout-body-container callout-body">
<p>La página de producto del CMMI Institute muestra cifras como 30 por ciento menos defectos, 15 por ciento más de productividad y 47 por ciento menos variación de costos. La página no indica comparación base, muestra ni periodo, así que sirven como mercadeo y no como dato para decidir. ISACA también informa, en un artículo de 2023, que de 33.272 objetivos de desempeño revisados en 8.866 apreciaciones, 84,4 por ciento se lograron o se superaron. Es un dato de organizaciones que decidieron apreciarse, con objetivos que ellas mismas fijaron, y no una comparación con organizaciones sin apreciación.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 5. Estima y limita
</div>
</div>
<div class="callout-body-container callout-body">
<p>El equipo de la clínica tiene 8 ingenieros. Con las medianas y los extremos de la tabla del SEI, calcula el costo anual de mejora y el costo en 3,5 años con la mediana, y el rango anual. Después escribe dos razones para no usar ese número como presupuesto.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Con la mediana de US$ 1.375 por ingeniero al año, 8 ingenieros cuestan 8 por 1.375 = US$ 11.000 al año. En 3,5 años son 11.000 por 3,5 = US$ 38.500. El rango anual va de 8 por 490 = US$ 3.920 a 8 por 2.004 = US$ 16.032.</p>
<p>Dos razones para no usarlo como presupuesto: son dólares de 1994 y de otro modelo (el Software CMM), y las organizaciones que aportaron los datos lo hicieron de forma voluntaria y en un entorno favorable, que no representa a cualquier equipo. Además, la cifra no incluye la apreciación formal actual, cuyo costo no se encontró en fuente primaria.</p>
<p>El resultado es un orden de magnitud para conversar, no una cotización.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-10.-spice-contra-cmmi" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="parte-10.-spice-contra-cmmi"><span class="header-section-number">13</span> Parte 10. SPICE contra CMMI</h2>
<p>Las dos familias preguntan qué tan fiable es la manera de trabajar. Se diferencian en lo que califican, en quién lo califica y en cómo se organiza el documento.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Aspecto</th>
<th>SPICE (ISO/IEC 33000 y Automotive SPICE)</th>
<th>CMMI v3.0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Quién lo mantiene</td>
<td>ISO e IEC para la serie 33000. La VDA para Automotive SPICE</td>
<td>ISACA, por medio del CMMI Institute</td>
</tr>
<tr class="even">
<td>Qué califica</td>
<td>Cada proceso del alcance, uno por uno</td>
<td>Cada área de práctica (capacidad) y un conjunto predefinido de áreas (madurez de la unidad)</td>
</tr>
<tr class="odd">
<td>Escala</td>
<td>Capacidad de 0 a 5 con nueve atributos</td>
<td>Capacidad de 0 a 3 por área de práctica y madurez de 0 a 5 por unidad</td>
</tr>
<tr class="even">
<td>Escala de logro por atributo</td>
<td>N, P, L, F con porcentajes</td>
<td>Grupos de práctica por nivel, con otro método de calificación</td>
</tr>
<tr class="odd">
<td>Nivel consolidado</td>
<td>La VDA aclara que no existe para un proyecto ni una empresa</td>
<td>Sí: el nivel de madurez de la unidad evaluada</td>
</tr>
<tr class="even">
<td>Organización del documento</td>
<td>Modelo de referencia y modelo de evaluación definidos con la norma 33004</td>
<td>Un solo modelo con dominios, áreas y grupos de práctica</td>
</tr>
<tr class="odd">
<td>Quién evalúa</td>
<td>Evaluadores certificados por el esquema intacs, en el caso automotriz</td>
<td>Evaluador líder certificado de CMMI, en la apreciación formal</td>
</tr>
<tr class="even">
<td>Dominio habitual</td>
<td>Automotriz, con dominios afines</td>
<td>Desarrollo, servicios, proveedores, datos, personas, seguridad y trabajo virtual</td>
</tr>
</tbody>
</table>
<p>Un punto merece cuidado. La guía anterior contrastaba a SPICE como “un proceso a la vez” con CMMI como “un nivel para toda la organización”. La segunda mitad era incompleta, porque CMMI también califica la capacidad de áreas de práctica individuales. La diferencia fiel es esta: SPICE no define un nivel consolidado y CMMI sí lo ofrece como una de sus lecturas.</p>
<section id="los-nombres-se-parecen-los-niveles-no-son-equivalentes" class="level3">
<h3 class="anchored" data-anchor-id="los-nombres-se-parecen-los-niveles-no-son-equivalentes">Los nombres se parecen, los niveles no son equivalentes</h3>
<p>Los niveles 2 y 3 de ambos marcos usan palabras cercanas (gestionado, establecido o definido), pero cada uno se define con sus propios criterios. En el material consultado no se encontró una correspondencia oficial entre los niveles de SPICE y los de CMMI. Un cliente que pide “nivel 3” debe aclarar a qué marco, a qué escala (capacidad o madurez) y a qué alcance se refiere.</p>
</section>
<section id="cuándo-conviene-cada-uno" class="level3">
<h3 class="anchored" data-anchor-id="cuándo-conviene-cada-uno">Cuándo conviene cada uno</h3>
<ul>
<li>Un cliente automotriz exige evaluar procesos de ingeniería de un producto con software embebido: Automotive SPICE, con evaluadores intacs.</li>
<li>Una organización de servicios o de desarrollo quiere mejorar y mostrar madurez ante clientes de distintos sectores: CMMI.</li>
<li>Un equipo solo quiere ordenar su trabajo, sin certificado: cualquiera de los dos modelos como guía, sin pagar apreciación formal.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 6. Qué marco aplica
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para cada caso, elige SPICE, CMMI o ninguno de los dos como primera opción y explica en una frase por qué.</p>
<ol type="1">
<li>El taller que construye la app de la clínica quiere vender un módulo a un fabricante de vehículos que le pide evaluar sus procesos de software.</li>
<li>El equipo de la clínica solo quiere reducir los errores de sus entregas y no tiene ningún cliente que exija un certificado.</li>
<li>Una consultora de software con proyectos para gobierno, servicios y datos quiere un nivel reconocido en varios sectores.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>SPICE, en concreto Automotive SPICE. Es el marco del sector, con su modelo y su esquema de evaluadores.</li>
<li>Ninguno de los dos como apreciación formal. Pueden servir como guía interna y un equipo con ese objetivo puede avanzar sin pagar una apreciación, con prácticas de revisión y verificación. La apreciación formal solo se justifica si alguien va a pedir su resultado.</li>
<li>CMMI. Cubre varios dominios y produce un nivel de madurez comunicable a clientes de sectores distintos.</li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="errores-frecuentes" class="level2" data-number="14">
<h2 data-number="14" class="anchored" data-anchor-id="errores-frecuentes"><span class="header-section-number">14</span> Errores frecuentes</h2>
<ul>
<li>Citar ISO/IEC 15504 como norma vigente cuando la serie 33000 la reemplazó en 2015.</li>
<li>Usar “Medición del proceso”, “Control del proceso” y “Optimización” como nombres de los atributos 4.1, 4.2 y 5.2, que son los de la 15504.</li>
<li>Llamar “Optimizing” al nivel 5 de SPICE en documentos nuevos, cuando el nombre vigente es <em>Innovating</em>.</li>
<li>Creer que el nivel de un proceso se promedia: el nivel exige todos los atributos de los niveles inferiores en F.</li>
<li>Pensar que SPICE da un nivel a toda la organización. En Automotive SPICE no existe nivel consolidado.</li>
<li>Decir que CMMI es “solo un nivel para toda la organización” y olvidar que también califica la capacidad por área de práctica.</li>
<li>Mezclar vocabulario de la versión 1.3 (SCAMPI, representaciones por etapas y continua) con el de las versiones 2.0 y 3.0.</li>
<li>Afirmar que una apreciación es un certificado de producto. Mide la capacidad de los procesos evaluados en una unidad y un alcance.</li>
<li>Usar cifras de mercadeo (porcentajes de mejora) o de 1994 como presupuesto.</li>
<li>Dar por vigente un dato de apreciación sin preguntar qué versión del modelo y del método rige.</li>
</ul>
</section>
<section id="autoevaluación" class="level2" data-number="15">
<h2 data-number="15" class="anchored" data-anchor-id="autoevaluación"><span class="header-section-number">15</span> Autoevaluación</h2>
<p>Responde sin mirar la guía. Marca tu opción y abre la clave para comprobarla. Es una práctica formativa y no tiene nota.</p>
<p><strong>1.</strong> Según el catálogo de ISO, ¿qué ocurrió con ISO/IEC 15504?</p>
<p><label><input type="checkbox"> Sigue vigente y es la norma de SPICE</label><br> <label><input type="checkbox"> Sus partes 1 y 2 se retiraron en 2015 y las reemplazaron documentos de la serie 33000</label><br> <label><input type="checkbox"> Se convirtió en CMMI v3.0</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. La parte 1 se retiró el 27 de febrero de 2015 y la parte 2 el 3 de marzo de 2015, y las reemplazaron los documentos 33001 a 33004, publicados en marzo de 2015.</p>
</div>
</div>
</div>
<p><strong>2.</strong> Un atributo de proceso se estima en 62 por ciento de logro. ¿Qué letra recibe con el refinamiento?</p>
<p><label><input type="checkbox"> P+</label><br> <label><input type="checkbox"> L-</label><br> <label><input type="checkbox"> L+</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. L cubre más de 50 hasta 85, y L- cubre más de 50 hasta 67,5. P+ llega solo hasta 50 y L+ empieza sobre 67,5.</p>
</div>
</div>
</div>
<p><strong>3.</strong> Para alcanzar el nivel 2 de capacidad, ¿qué se exige?</p>
<p><label><input type="checkbox"> PA 1.1 en L o F, y PA 2.1 y 2.2 en F</label><br> <label><input type="checkbox"> PA 1.1 en F, y PA 2.1 y 2.2 en L o F</label><br> <label><input type="checkbox"> Que la organización tenga un proceso estándar definido</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Los atributos del nivel que se busca pueden estar en L o F, y los de los niveles inferiores deben estar plenamente logrados (F). El proceso estándar de la organización es del nivel 3.</p>
</div>
</div>
</div>
<p><strong>4.</strong> ¿Cómo se llama el atributo PA 4.1 en ISO/IEC 33020:2019?</p>
<p><label><input type="checkbox"> Medición del proceso</label><br> <label><input type="checkbox"> Análisis cuantitativo</label><br> <label><input type="checkbox"> Control cuantitativo</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. “Medición del proceso” es el nombre de la 15504, y “Control cuantitativo” es PA 4.2.</p>
</div>
</div>
</div>
<p><strong>5.</strong> ¿Cómo se llama hoy el nivel 5 de capacidad?</p>
<p><label><input type="checkbox"> Optimizing, como en la 15504</label><br> <label><input type="checkbox"> Innovating, como en la 33020</label><br> <label><input type="checkbox"> Defined</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Innovating (innovador) es el nombre del nivel 5 en la 33020 y en el PAM de Automotive SPICE 4.0. Optimizing era el nombre en la 15504.</p>
</div>
</div>
</div>
<p><strong>6.</strong> ¿Qué afirma la VDA sobre el resultado de una evaluación Automotive SPICE?</p>
<p><label><input type="checkbox"> Entrega un nivel consolidado para toda la empresa</label><br> <label><input type="checkbox"> Cada proceso del alcance recibe su nivel y no existe nivel consolidado para un proyecto ni una empresa</label><br> <label><input type="checkbox"> Solo se califican los procesos del nivel 1</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. La VDA lo dice en la descripción de la dimensión de capacidad del modelo.</p>
</div>
</div>
</div>
<p><strong>7.</strong> ¿Cuál es el propósito de SWE.4 en el PAM 4.0?</p>
<p><label><input type="checkbox"> Verificar que las unidades de software son consistentes con el diseño detallado</label><br> <label><input type="checkbox"> Verificar que el software integrado cumple los requisitos de software</label><br> <label><input type="checkbox"> Establecer la arquitectura del software</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. La opción 2 es SWE.6 y la opción 3 es SWE.2.</p>
</div>
</div>
</div>
<p><strong>8.</strong> ¿Cuántos dominios tiene CMMI v3.0 según ISACA y quién lo publica?</p>
<p><label><input type="checkbox"> Tres dominios, publicado por el SEI</label><br> <label><input type="checkbox"> Ocho dominios, publicado por ISACA</label><br> <label><input type="checkbox"> Un solo dominio, publicado por ISO</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Los tres dominios originales (desarrollo, servicios y proveedores) se ampliaron con datos, personas, seguridad funcional, seguridad de la información y trabajo virtual.</p>
</div>
</div>
</div>
<p><strong>9.</strong> ¿Qué tipo de apreciación CMMI produce calificaciones con validez de 3 años?</p>
<p><label><input type="checkbox"> Evaluation</label><br> <label><input type="checkbox"> Benchmark</label><br> <label><input type="checkbox"> Sustainment</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Sustainment da calificaciones con validez de 2 años y evaluation no produce calificaciones.</p>
</div>
</div>
</div>
<p><strong>10.</strong> ¿Qué conclusión es correcta sobre el costo de subir de nivel?</p>
<p><label><input type="checkbox"> Cuesta siempre US$ 1.375 por ingeniero al año</label><br> <label><input type="checkbox"> Los datos verificados son del Software CMM, de 1994 y de 13 organizaciones voluntarias, y sirven solo como orden de magnitud</label><br> <label><input type="checkbox"> El CMMI Institute publica el precio de un benchmark</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 10
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. US$ 1.375 es una mediana de ese estudio, no una tarifa, y el CMMI Institute no publica el precio de una apreciación.</p>
</div>
</div>
</div>
</section>
<section id="lo-que-te-llevas" class="level2" data-number="16">
<h2 data-number="16" class="anchored" data-anchor-id="lo-que-te-llevas"><span class="header-section-number">16</span> Lo que te llevas</h2>
<div class="checklist">
<p><strong>Al salir de este tema deberías poder explicar, sin mirar la guía</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Por qué ISO/IEC 15504 está retirada y qué la reemplazó, con las fechas de ISO</label></li>
<li><label><input type="checkbox">La escala N, P, L y F con sus porcentajes y el refinamiento de P y L</label></li>
<li><label><input type="checkbox">Los seis niveles de capacidad y los nueve atributos con los nombres de la 33020:2019</label></li>
<li><label><input type="checkbox">Cómo se deriva el nivel de un proceso a partir de las letras, y por qué un atributo bajo lo bloquea</label></li>
<li><label><input type="checkbox">Qué son los procesos SWE.1 a SWE.6 de Automotive SPICE 4.0 y qué diferencia hay entre prácticas base y genéricas</label></li>
<li><label><input type="checkbox">Cómo se califica un proceso con un ejemplo, de la evidencia al nivel</label></li>
<li><label><input type="checkbox">La estructura de CMMI v3.0, los niveles de capacidad (0 a 3) y de madurez (0 a 5)</label></li>
<li><label><input type="checkbox">Los cuatro tipos de apreciación, qué produce cada uno y cuánto dura su validez</label></li>
<li><label><input type="checkbox">Qué se sabe y qué no se sabe del costo de subir de nivel</label></li>
<li><label><input type="checkbox">En qué se parecen y en qué se diferencian SPICE y CMMI</label></li>
</ul>
</div>
</section>
<section id="glosario" class="level2" data-number="17">
<h2 data-number="17" class="anchored" data-anchor-id="glosario"><span class="header-section-number">17</span> Glosario</h2>
<ul>
<li><strong>SPICE.</strong> Sigla de <em>Software Process Improvement and Capability dEtermination</em>. Nombre del enfoque de evaluación de procesos, hoy apoyado en la serie ISO/IEC 33000.</li>
<li><strong>ISO/IEC 15504.</strong> Norma original de SPICE, con sus partes 1 y 2 retiradas en 2015.</li>
<li><strong>ISO/IEC 33000.</strong> Serie de normas de evaluación de procesos que reemplazó a la 15504.</li>
<li><strong>ISO/IEC 33020.</strong> Norma que define el marco de medición de la capacidad de un proceso. La edición vigente es la de 2019.</li>
<li><strong>Modelo de referencia de procesos (PRM).</strong> Catálogo de procesos de un dominio, con su propósito y sus resultados.</li>
<li><strong>Modelo de evaluación de procesos (PAM).</strong> Modelo con los indicadores para evaluar la capacidad de los procesos de un PRM.</li>
<li><strong>Atributo de proceso (PA).</strong> Propiedad medible de la capacidad de un proceso. Hay nueve, de PA 1.1 a PA 5.2.</li>
<li><strong>Nivel de capacidad.</strong> Valor de 0 a 5 que se deriva de las calificaciones de los atributos de un proceso.</li>
<li><strong>Escala N, P, L y F.</strong> Calificación de un atributo: no logrado, parcialmente, ampliamente o plenamente logrado.</li>
<li><strong>Práctica base (BP).</strong> Actividad de un proceso que indica si logra su propósito. Evidencia del nivel 1.</li>
<li><strong>Práctica genérica (GP).</strong> Actividad aplicable a cualquier proceso, que indica cómo se gestiona. Evidencia de los niveles 2 a 5.</li>
<li><strong>Automotive SPICE.</strong> Aplicación de SPICE al software y los sistemas de los vehículos, mantenida por la VDA.</li>
<li><strong>VDA.</strong> Asociación alemana de la industria automotriz. Su centro de calidad es el VDA QMC.</li>
<li><strong>intacs.</strong> Esquema internacional de certificación de evaluadores de SPICE.</li>
<li><strong>SWE.</strong> Grupo de procesos de ingeniería de software de Automotive SPICE, de SWE.1 a SWE.6.</li>
<li><strong>CMMI.</strong> <em>Capability Maturity Model Integration</em>. Modelo de buenas prácticas de ISACA, por medio del CMMI Institute.</li>
<li><strong>ISACA.</strong> Asociación que publica y mantiene CMMI.</li>
<li><strong>Dominio (CMMI).</strong> Conjunto de áreas de práctica para un tipo de trabajo. La versión 3.0 tiene ocho.</li>
<li><strong>Área de práctica (CMMI).</strong> Unidad temática del modelo, por ejemplo Verificación (VER).</li>
<li><strong>Grupo de práctica (CMMI).</strong> Conjunto de prácticas de un área, etiquetado de nivel 0 a 3.</li>
<li><strong>Nivel de capacidad (CMMI).</strong> Valor de 0 a 3 del desempeño de una organización en un área de práctica.</li>
<li><strong>Nivel de madurez (CMMI).</strong> Valor de 0 a 5 de una unidad de la organización, sobre un conjunto predefinido de áreas.</li>
<li><strong>Apreciación.</strong> Actividad que identifica fortalezas y debilidades de los procesos de una organización frente a CMMI.</li>
<li><strong>Benchmark, sustainment, evaluation y action plan reappraisal.</strong> Los cuatro tipos de apreciación de CMMI.</li>
<li><strong>Evaluador líder.</strong> Persona certificada que conduce una apreciación formal de CMMI.</li>
<li><strong>Software CMM.</strong> Modelo anterior a CMMI, publicado por primera vez en 1991.</li>
<li><strong>Calificación ordinal.</strong> Escala cuyos valores indican orden y tramo, no una medida exacta.</li>
</ul>
</section>
<section id="bibliografía" class="level2" data-number="18">
<h2 data-number="18" class="anchored" data-anchor-id="bibliografía"><span class="header-section-number">18</span> Bibliografía</h2>
<p>Sobre la serie ISO/IEC 33000 y la retirada de la 15504 (consultados el 3 de octubre de 2026):</p>
<ul>
<li>ISO/IEC 33001:2015. <em>Information technology. Process assessment. Concepts and terminology.</em> <a href="https://www.iso.org/standard/54175.html">Catálogo de ISO</a>.</li>
<li>ISO/IEC 33002:2015. <em>Requirements for performing process assessment.</em> <a href="https://www.iso.org/standard/54176.html">Catálogo de ISO</a>.</li>
<li>ISO/IEC 33003:2015. <em>Requirements for process measurement frameworks.</em> <a href="https://www.iso.org/standard/54177.html">Catálogo de ISO</a>.</li>
<li>ISO/IEC 33004:2015. <em>Requirements for process reference, process assessment and maturity models.</em> <a href="https://www.iso.org/standard/54178.html">Catálogo de ISO</a>.</li>
<li>ISO/IEC 33020:2019 (edición 2). <em>Process measurement framework for assessment of process capability.</em> <a href="https://www.iso.org/standard/78526.html">Catálogo de ISO</a>. La edición de 2015 consta <a href="https://www.iso.org/standard/54195.html">retirada</a>.</li>
<li>ISO/IEC 15504-1:2004. <em>Concepts and vocabulary.</em> <a href="https://www.iso.org/standard/38932.html">Retirada el 27 de febrero de 2015</a>.</li>
<li>ISO/IEC 15504-2:2003. <em>Performing an assessment.</em> <a href="https://www.iso.org/standard/37458.html">Retirada el 3 de marzo de 2015</a>.</li>
<li>Souza Neto, J., Almeida, R., Linares Pinto, P. y Mira da Silva, M. (2018). A COBIT 5 PAM Update Compliant With ISO/IEC 330xx Family. <em>ISACA Journal</em>, vol.&nbsp;1. <a href="https://www.isaca.org/resources/isaca-journal/issues/2018/volume-1/a-cobit-5-pam-update-compliant-with-isoiec-330xx-family">Artículo</a>. Refinamiento de la escala y atributos renombrados.</li>
</ul>
<p>Sobre Automotive SPICE:</p>
<ul>
<li>VDA Working Group 13 (2023). <em>Automotive SPICE Process Reference Model, Process Assessment Model, versión 4.0</em>, 29 de noviembre de 2023. VDA QMC. <a href="https://vda-qmc.de/wp-content/uploads/2023/12/Automotive-SPICE-PAM-v40.pdf">PDF</a>. Reproduce, con licencia de ISO, los nombres y reglas de la 33020:2019.</li>
<li>VDA QMC. <a href="https://vda-qmc.de/en/automotive-spice/">Automotive SPICE</a> y <a href="https://vda-qmc.de/en/automotive-spice/automotive-spice-zertifizierung/">certificación de evaluadores</a>. Consultados el 3 de octubre de 2026.</li>
</ul>
<p>Sobre CMMI (consultados el 3 de octubre de 2026):</p>
<ul>
<li>Lear, R. (2023). CMMI Updates Take Performance Improvements to the Next Level. <em>ISACA Now Blog</em>, 10 de abril de 2023. <a href="https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2023/cmmi-updates-take-performance-improvements-to-the-next-level">Artículo</a>.</li>
<li>ISACA Now (2024). Shaping the Future with CMMI, 28 de marzo de 2024. <a href="https://www.isaca.org/resources/news-and-trends/isaca-now-blog/2024/shaping-the-future-with-cmmi">Entrevista</a>.</li>
<li>Sundaram, J. (2025). CMMI in the AI Age: Driving Efficiency, Innovation, and Governance. <em>ISACA Journal</em>, vol.&nbsp;3, 1 de mayo de 2025. <a href="https://www.isaca.org/resources/isaca-journal/issues/2025/volume-3/cmmi-in-the-ai-age">Artículo</a>.</li>
<li>CMMI Institute. <a href="https://cmmiinstitute.com/learning/appraisals/types">Tipos de apreciación de CMMI</a>, <a href="https://cmmiinstitute.com/learning/appraisals/levels">niveles de capacidad y de madurez</a>, <a href="https://cmmiinstitute.com/learning/appraisals">qué es una apreciación</a>, <a href="https://cmmiinstitute.com/products/cmmi/cmmi-model-viewer">visor del modelo</a> y <a href="https://cmmiinstitute.com/products/cmmi">página de producto</a>.</li>
<li>Wikipedia. <a href="https://en.wikipedia.org/wiki/Capability_Maturity_Model_Integration">Capability Maturity Model Integration</a>. Fuente secundaria, usada solo para el recuadro histórico de la versión 1.3.</li>
</ul>
<p>Sobre costos de la mejora de procesos:</p>
<ul>
<li>Herbsleb, J., Carleton, A., Rozum, J., Siegel, J. y Zubrow, D. (1994). <em>Benefits of CMM-Based Software Process Improvement: Initial Results.</em> CMU/SEI-94-TR-013. Software Engineering Institute. <a href="https://www.sei.cmu.edu/library/benefits-of-cmm-based-software-process-improvement-initial-results/">Ficha y PDF</a>.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fuentes de pago
</div>
</div>
<div class="callout-body-container callout-body">
<p>Las normas ISO/IEC 33001 a 33004 y 33020 son de pago y no se leyeron completas. Esta guía se apoya en los catálogos de ISO (títulos, ediciones, fechas y estado) y en el modelo Automotive SPICE 4.0, que reproduce con licencia partes de la 33020:2019. El modelo CMMI v3.0 está en un visor por suscripción y no se leyó. Lo que se afirma de su contenido sale de materiales públicos de ISACA y del CMMI Institute.</p>
</div>
</div>
<div class="pie-doc">
<p>Calidad del software (CDS01). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>