<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e inteligencia artificial – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-95bfa606010d176c52cfb6b551730f65.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/index.html">Unidad 3. Estándares de calidad aplicados al software</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Calidad del software y estándares de calidad</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-01-que-es-calidad-quien-la-define/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es la calidad y quién la define</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Calidad de proceso y de producto: ISO/IEC 25010:2023</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Importancia, costo y calidad en un mundo globalizado</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Procesos de calidad del software. Modelos y métricas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-01-sqa-relacion-ingenieria/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es el SQA y su relación con la ingeniería de software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La calidad en cada fase del ciclo de vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-03-roles-habilidades/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Roles, responsabilidades y habilidades del personal de SQA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-04-actividades-sqa/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Actividades del SQA: revisiones, auditorías y gestión de configuración</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-05-modelos-metricas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Modelos y métricas de calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-06-herramientas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 6. Herramientas de SQA en la industria</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 3. Estándares de calidad aplicados al software</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Estándares IEEE para la calidad del software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Marcos para evaluar la usabilidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Madurez de procesos: SPICE y CMMI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 4. Validación y verificación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Métodos, metodologías y estándares de verificación y validación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Validación y verificación de requisitos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-03-control-costo-calidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Control de la calidad y costo de la calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Nomenclatura y certificación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-05-factores-atam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Factores que determinan la calidad y el método ATAM</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#objetivo-y-resultado-de-aprendizaje" id="toc-objetivo-y-resultado-de-aprendizaje" class="nav-link active" data-scroll-target="#objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</a></li>
  <li><a href="#ruta-de-estudio" id="toc-ruta-de-estudio" class="nav-link" data-scroll-target="#ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</a></li>
  <li><a href="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" id="toc-el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="nav-link" data-scroll-target="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</a></li>
  <li><a href="#parte-1.-panorama-de-la-familia-iso-para-software" id="toc-parte-1.-panorama-de-la-familia-iso-para-software" class="nav-link" data-scroll-target="#parte-1.-panorama-de-la-familia-iso-para-software"><span class="header-section-number">4</span> Parte 1. Panorama de la familia ISO para software</a>
  <ul class="collapse">
  <li><a href="#recuadro-de-vigencia-y-de-fuentes" id="toc-recuadro-de-vigencia-y-de-fuentes" class="nav-link" data-scroll-target="#recuadro-de-vigencia-y-de-fuentes">Recuadro de vigencia y de fuentes</a></li>
  </ul></li>
  <li><a href="#parte-2.-la-serie-square-por-divisiones" id="toc-parte-2.-la-serie-square-por-divisiones" class="nav-link" data-scroll-target="#parte-2.-la-serie-square-por-divisiones"><span class="header-section-number">5</span> Parte 2. La serie SQuaRE por divisiones</a>
  <ul class="collapse">
  <li><a href="#las-divisiones-una-por-una" id="toc-las-divisiones-una-por-una" class="nav-link" data-scroll-target="#las-divisiones-una-por-una">Las divisiones, una por una</a></li>
  <li><a href="#qué-normas-están-vigentes-a-octubre-de-2026" id="toc-qué-normas-están-vigentes-a-octubre-de-2026" class="nav-link" data-scroll-target="#qué-normas-están-vigentes-a-octubre-de-2026">Qué normas están vigentes a octubre de 2026</a></li>
  <li><a href="#una-numeración-nueva-que-se-está-estrenando" id="toc-una-numeración-nueva-que-se-está-estrenando" class="nav-link" data-scroll-target="#una-numeración-nueva-que-se-está-estrenando">Una numeración nueva que se está estrenando</a></li>
  <li><a href="#las-nueve-características-solo-una-referencia" id="toc-las-nueve-características-solo-una-referencia" class="nav-link" data-scroll-target="#las-nueve-características-solo-una-referencia">Las nueve características, solo una referencia</a></li>
  </ul></li>
  <li><a href="#parte-3.-calidad-de-los-datos" id="toc-parte-3.-calidad-de-los-datos" class="nav-link" data-scroll-target="#parte-3.-calidad-de-los-datos"><span class="header-section-number">6</span> Parte 3. Calidad de los datos</a>
  <ul class="collapse">
  <li><a href="#dos-miradas-y-quince-características" id="toc-dos-miradas-y-quince-características" class="nav-link" data-scroll-target="#dos-miradas-y-quince-características">Dos miradas y quince características</a></li>
  <li><a href="#las-quince-características-con-la-app-de-turnos" id="toc-las-quince-características-con-la-app-de-turnos" class="nav-link" data-scroll-target="#las-quince-características-con-la-app-de-turnos">Las quince características, con la app de turnos</a></li>
  <li><a href="#un-caso-para-analizar" id="toc-un-caso-para-analizar" class="nav-link" data-scroll-target="#un-caso-para-analizar">Un caso para analizar</a></li>
  <li><a href="#medir-los-datos-y-la-serie-isoiec-5259-para-aprendizaje-automático" id="toc-medir-los-datos-y-la-serie-isoiec-5259-para-aprendizaje-automático" class="nav-link" data-scroll-target="#medir-los-datos-y-la-serie-isoiec-5259-para-aprendizaje-automático">Medir los datos, y la serie ISO/IEC 5259 para aprendizaje automático</a></li>
  </ul></li>
  <li><a href="#parte-4.-medir-la-calidad-el-patrón-de-la-serie-2502n" id="toc-parte-4.-medir-la-calidad-el-patrón-de-la-serie-2502n" class="nav-link" data-scroll-target="#parte-4.-medir-la-calidad-el-patrón-de-la-serie-2502n"><span class="header-section-number">7</span> Parte 4. Medir la calidad: el patrón de la serie 2502n</a>
  <ul class="collapse">
  <li><a href="#las-normas-de-base-y-las-de-aplicación" id="toc-las-normas-de-base-y-las-de-aplicación" class="nav-link" data-scroll-target="#las-normas-de-base-y-las-de-aplicación">Las normas de base y las de aplicación</a></li>
  <li><a href="#lo-que-las-tres-normas-dicen-y-lo-que-no-dicen" id="toc-lo-que-las-tres-normas-dicen-y-lo-que-no-dicen" class="nav-link" data-scroll-target="#lo-que-las-tres-normas-dicen-y-lo-que-no-dicen">Lo que las tres normas dicen y lo que no dicen</a></li>
  <li><a href="#ejemplo-resuelto-medir-tres-capas-de-la-app-de-turnos" id="toc-ejemplo-resuelto-medir-tres-capas-de-la-app-de-turnos" class="nav-link" data-scroll-target="#ejemplo-resuelto-medir-tres-capas-de-la-app-de-turnos">Ejemplo resuelto: medir tres capas de la app de turnos</a></li>
  </ul></li>
  <li><a href="#parte-5.-requisitos-y-evaluación-de-la-calidad" id="toc-parte-5.-requisitos-y-evaluación-de-la-calidad" class="nav-link" data-scroll-target="#parte-5.-requisitos-y-evaluación-de-la-calidad"><span class="header-section-number">8</span> Parte 5. Requisitos y evaluación de la calidad</a>
  <ul class="collapse">
  <li><a href="#isoiec-25030-el-marco-de-requisitos-de-calidad" id="toc-isoiec-25030-el-marco-de-requisitos-de-calidad" class="nav-link" data-scroll-target="#isoiec-25030-el-marco-de-requisitos-de-calidad">ISO/IEC 25030: el marco de requisitos de calidad</a></li>
  <li><a href="#isoiec-25040-el-marco-de-evaluación" id="toc-isoiec-25040-el-marco-de-evaluación" class="nav-link" data-scroll-target="#isoiec-25040-el-marco-de-evaluación">ISO/IEC 25040: el marco de evaluación</a></li>
  </ul></li>
  <li><a href="#parte-6.-iso-9001-a-fondo" id="toc-parte-6.-iso-9001-a-fondo" class="nav-link" data-scroll-target="#parte-6.-iso-9001-a-fondo"><span class="header-section-number">9</span> Parte 6. ISO 9001 a fondo</a>
  <ul class="collapse">
  <li><a href="#qué-es-y-qué-no-es" id="toc-qué-es-y-qué-no-es" class="nav-link" data-scroll-target="#qué-es-y-qué-no-es">Qué es y qué no es</a></li>
  <li><a href="#la-edición-vigente-iso-90012026" id="toc-la-edición-vigente-iso-90012026" class="nav-link" data-scroll-target="#la-edición-vigente-iso-90012026">La edición vigente: ISO 9001:2026</a></li>
  <li><a href="#qué-cambió-según-iso-y-qué-sigue-igual" id="toc-qué-cambió-según-iso-y-qué-sigue-igual" class="nav-link" data-scroll-target="#qué-cambió-según-iso-y-qué-sigue-igual">Qué cambió, según ISO, y qué sigue igual</a></li>
  <li><a href="#la-enmienda-12024-un-puente-que-quedó-atrás" id="toc-la-enmienda-12024-un-puente-que-quedó-atrás" class="nav-link" data-scroll-target="#la-enmienda-12024-un-puente-que-quedó-atrás">La Enmienda 1:2024, un puente que quedó atrás</a></li>
  <li><a href="#las-siete-cláusulas-auditables" id="toc-las-siete-cláusulas-auditables" class="nav-link" data-scroll-target="#las-siete-cláusulas-auditables">Las siete cláusulas auditables</a></li>
  <li><a href="#la-cláusula-8-en-una-empresa-de-software" id="toc-la-cláusula-8-en-una-empresa-de-software" class="nav-link" data-scroll-target="#la-cláusula-8-en-una-empresa-de-software">La cláusula 8 en una empresa de software</a></li>
  <li><a href="#el-enfoque-de-riesgos-y-oportunidades" id="toc-el-enfoque-de-riesgos-y-oportunidades" class="nav-link" data-scroll-target="#el-enfoque-de-riesgos-y-oportunidades">El enfoque de riesgos y oportunidades</a></li>
  <li><a href="#el-ciclo-phva" id="toc-el-ciclo-phva" class="nav-link" data-scroll-target="#el-ciclo-phva">El ciclo PHVA</a></li>
  <li><a href="#la-auditoría-interna-y-la-revisión-por-la-dirección" id="toc-la-auditoría-interna-y-la-revisión-por-la-dirección" class="nav-link" data-scroll-target="#la-auditoría-interna-y-la-revisión-por-la-dirección">La auditoría interna y la revisión por la dirección</a></li>
  <li><a href="#la-auditoría-de-certificación" id="toc-la-auditoría-de-certificación" class="nav-link" data-scroll-target="#la-auditoría-de-certificación">La auditoría de certificación</a></li>
  <li><a href="#qué-demuestra-una-certificación-y-qué-no" id="toc-qué-demuestra-una-certificación-y-qué-no" class="nav-link" data-scroll-target="#qué-demuestra-una-certificación-y-qué-no">Qué demuestra una certificación y qué no</a></li>
  </ul></li>
  <li><a href="#parte-7.-isoiecieee-90003-la-iso-9001-aplicada-al-software" id="toc-parte-7.-isoiecieee-90003-la-iso-9001-aplicada-al-software" class="nav-link" data-scroll-target="#parte-7.-isoiecieee-90003-la-iso-9001-aplicada-al-software"><span class="header-section-number">10</span> Parte 7. ISO/IEC/IEEE 90003: la ISO 9001 aplicada al software</a></li>
  <li><a href="#parte-8.-inteligencia-artificial-isoiec-25059-e-isoiec-42001" id="toc-parte-8.-inteligencia-artificial-isoiec-25059-e-isoiec-42001" class="nav-link" data-scroll-target="#parte-8.-inteligencia-artificial-isoiec-25059-e-isoiec-42001"><span class="header-section-number">11</span> Parte 8. Inteligencia artificial: ISO/IEC 25059 e ISO/IEC 42001</a>
  <ul class="collapse">
  <li><a href="#isoiec-25059-un-modelo-de-calidad-para-sistemas-de-ia" id="toc-isoiec-25059-un-modelo-de-calidad-para-sistemas-de-ia" class="nav-link" data-scroll-target="#isoiec-25059-un-modelo-de-calidad-para-sistemas-de-ia">ISO/IEC 25059: un modelo de calidad para sistemas de IA</a></li>
  <li><a href="#isoiec-42001-un-sistema-de-gestión-para-ia" id="toc-isoiec-42001-un-sistema-de-gestión-para-ia" class="nav-link" data-scroll-target="#isoiec-42001-un-sistema-de-gestión-para-ia">ISO/IEC 42001: un sistema de gestión para IA</a></li>
  <li><a href="#cómo-se-combinan-en-la-clínica" id="toc-cómo-se-combinan-en-la-clínica" class="nav-link" data-scroll-target="#cómo-se-combinan-en-la-clínica">Cómo se combinan en la clínica</a></li>
  </ul></li>
  <li><a href="#parte-9.-cómo-se-combinan-tabla-de-decisión" id="toc-parte-9.-cómo-se-combinan-tabla-de-decisión" class="nav-link" data-scroll-target="#parte-9.-cómo-se-combinan-tabla-de-decisión"><span class="header-section-number">12</span> Parte 9. Cómo se combinan: tabla de decisión</a></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes"><span class="header-section-number">13</span> Errores frecuentes</a></li>
  <li><a href="#autoevaluación" id="toc-autoevaluación" class="nav-link" data-scroll-target="#autoevaluación"><span class="header-section-number">14</span> Autoevaluación</a></li>
  <li><a href="#lo-que-te-llevas" id="toc-lo-que-te-llevas" class="nav-link" data-scroll-target="#lo-que-te-llevas"><span class="header-section-number">15</span> Lo que te llevas</a></li>
  <li><a href="#glosario" id="toc-glosario" class="nav-link" data-scroll-target="#glosario"><span class="header-section-number">16</span> Glosario</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">17</span> Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/index.html">Unidad 3. Estándares de calidad aplicados al software</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e inteligencia artificial</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">3 de octubre de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 3. Estándares de calidad aplicados al software</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 2. La familia ISO para software: SQuaRE, datos, gestión e IA</td>
</tr>
</tbody>
</table>
</div>
<p><a href="../presentacion-interactiva.html" class="btn-curso">Presentación interactiva de la unidad</a></p>
<p>Tema anterior: <a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html">Tema 1. Estándares IEEE para la calidad del software</a>. Tema siguiente: <a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html">Tema 3. Usabilidad</a>.</p>
<section id="objetivo-y-resultado-de-aprendizaje" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</h2>
<p>El Tema 1 de esta unidad mostró cómo el IEEE ordena la documentación de un proyecto. Este tema cambia de ángulo. Estudia qué normas usa alguien de afuera, un comprador, un auditor o un regulador, para decidir si un producto de software, los datos que procesa y la organización que lo construye merecen confianza. La palabra ISO no nombra una sola norma. Nombra una familia con cuatro frentes: el producto, los datos, el sistema de gestión y, desde hace pocos años, la inteligencia artificial.</p>
<p>Al terminar puedes:</p>
<ul>
<li>Ubicar cada norma de la serie SQuaRE (ISO/IEC 25000) en su división y decir qué pregunta responde.</li>
<li>Distinguir las quince características de calidad de datos de la ISO/IEC 25012 y clasificarlas en inherentes, de sistema o de ambos tipos.</li>
<li>Leer y calcular una medida de calidad de producto, de datos y de uso con el patrón de la serie 2502n.</li>
<li>Explicar qué exige la ISO 9001, qué cambió con la edición de 2026 y cómo se recorre una auditoría de certificación.</li>
<li>Aplicar el ciclo PHVA y el enfoque de riesgos y oportunidades a un problema de calidad de software.</li>
<li>Decir para qué sirve la ISO/IEC/IEEE 90003 y por qué no se certifica.</li>
<li>Diferenciar la ISO/IEC 25059 (calidad de un sistema de IA) de la ISO/IEC 42001 (sistema de gestión de IA).</li>
</ul>
<p>Prerrequisitos: el Tema 2 de la Unidad 1, que desarrolla las nueve características de la ISO/IEC 25010:2023, y el Tema 1 de esta unidad. Esta guía no repite esas nueve características. Solo las cita cuando hace falta.</p>
</section>
<section id="ruta-de-estudio" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</h2>
<p>Son unas 8 horas de trabajo independiente. Puedes partirlas en cuatro sesiones. La presentación interactiva de la unidad sigue las mismas partes y en el mismo orden, así que sirve como repaso o como primera mirada.</p>
<div class="calendario">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parte</th>
<th>Qué haces</th>
<th>Tiempo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Panorama de la familia</td>
<td>Lees el mapa de las cuatro familias y el recuadro de vigencia</td>
<td>25 min</td>
</tr>
<tr class="even">
<td>2. SQuaRE por divisiones</td>
<td>Estudias las divisiones, las ediciones vigentes y la nueva numeración</td>
<td>50 min</td>
</tr>
<tr class="odd">
<td>3. Calidad de datos</td>
<td>Aprendes las quince características de la 25012 y resuelves el Reto 1</td>
<td>55 min</td>
</tr>
<tr class="even">
<td>4. Medición de la calidad</td>
<td>Sigues el ejemplo resuelto en la app de turnos y resuelves el Reto 2</td>
<td>75 min</td>
</tr>
<tr class="odd">
<td>5. Requisitos y evaluación</td>
<td>Lees las normas 25030 y 25040 y resuelves el Reto 3</td>
<td>30 min</td>
</tr>
<tr class="even">
<td>6. ISO 9001 a fondo</td>
<td>Cláusulas, riesgos, PHVA, auditoría y edición 2026; resuelves los Retos 4 y 5</td>
<td>120 min</td>
</tr>
<tr class="odd">
<td>7. ISO/IEC/IEEE 90003</td>
<td>Lees la guía de aplicación al software</td>
<td>20 min</td>
</tr>
<tr class="even">
<td>8. Inteligencia artificial</td>
<td>Estudias la 25059 y la 42001 y resuelves el Reto 6</td>
<td>45 min</td>
</tr>
<tr class="odd">
<td>9. Cómo se combinan</td>
<td>Usas la tabla de decisión</td>
<td>15 min</td>
</tr>
<tr class="even">
<td>Cierre</td>
<td>Errores frecuentes, autoevaluación y glosario</td>
<td>45 min</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</h2>
<p>El curso usa un producto ficticio, una app que asigna turnos médicos. Su requisito de partida es “la app asigna hasta 20 turnos por día a cada especialidad” (RF-01). Aquí la usas como laboratorio para medir su calidad con la serie 2502n, revisar sus datos con la 25012, someterla a un ciclo PHVA y pensar qué normas aplicarían si le agregaran un asistente de inteligencia artificial. Todos los números de la clínica son inventados para razonar. Ninguno es una medición real.</p>
</section>
<section id="parte-1.-panorama-de-la-familia-iso-para-software" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="parte-1.-panorama-de-la-familia-iso-para-software"><span class="header-section-number">4</span> Parte 1. Panorama de la familia ISO para software</h2>
<p>Cuando una clínica compra una app de turnos, hace cuatro preguntas distintas, y cada una la contesta un grupo diferente de normas. Primero pregunta si el producto es bueno, y para eso existe la serie SQuaRE. Después pregunta si los datos que guarda son confiables, que es terreno de la ISO/IEC 25012 y sus medidas. Luego pregunta si la empresa que la construye gestiona bien su calidad, y ahí entran la ISO 9001 y su guía para software, la ISO/IEC/IEEE 90003. Por último, si la app incluye inteligencia artificial, pregunta cómo se gobierna esa parte, y para eso hay una norma de producto (25059) y una de gestión (42001).</p>
<div class="diagrama">
<svg viewbox="0 0 760 310" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cuatro preguntas que hace un comprador sobre la app de turnos y la familia de normas ISO que responde cada una: producto con SQuaRE, datos con 25012, gestion con ISO 9001 y 90003, e inteligencia artificial con 25059 y 42001" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t2a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Cuatro preguntas, cuatro frentes de la familia ISO</text> <rect x="230" y="30" width="300" height="52" rx="12" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="52" font-size="14" font-weight="700" fill="#0e6f6c" text-anchor="middle">Comprador de la app de turnos</text> <text x="380" y="70" font-size="11" fill="#3c7d7a" text-anchor="middle">decide si confía en producto, datos y empresa</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="15" y="150" width="170" height="140" rx="10"></rect><rect x="205" y="150" width="170" height="140" rx="10"></rect><rect x="395" y="150" width="170" height="140" rx="10"></rect><rect x="585" y="150" width="160" height="140" rx="10"></rect></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u3t2a)"><path d="M300,82 L110,148"></path><path d="M345,82 L290,148"></path><path d="M415,82 L470,148"></path><path d="M460,82 L650,148"></path></g> <g text-anchor="middle"> <g font-size="12.5" font-weight="700" fill="#12324f"><text x="100" y="174">El producto</text><text x="290" y="174">Los datos</text><text x="480" y="174">La gestión</text><text x="665" y="174">La IA</text></g> <g font-size="10.8" fill="#5b6876"> <text x="100" y="196">Serie SQuaRE</text><text x="100" y="212">ISO/IEC 25000 a 25099</text><text x="100" y="236">25010 modelo</text><text x="100" y="252">25023 medición</text><text x="100" y="268">25040 evaluación</text> <text x="290" y="196">ISO/IEC 25012</text><text x="290" y="212">modelo de datos</text><text x="290" y="236">25024 medición</text><text x="290" y="252">5259 datos para</text><text x="290" y="268">aprendizaje automático</text> <text x="480" y="196">ISO 9001:2026</text><text x="480" y="212">sistema de gestión</text><text x="480" y="236">ISO/IEC/IEEE 90003</text><text x="480" y="252">guía para software</text><text x="480" y="268">ISO 19011 auditorías</text> <text x="665" y="196">ISO/IEC 25059</text><text x="665" y="212">calidad del sistema</text><text x="665" y="236">ISO/IEC 42001</text><text x="665" y="252">sistema de gestión</text><text x="665" y="268">de IA</text> </g> </g>
</svg>
</div>
<p>Una norma de producto describe cómo debe ser el software. Una norma de gestión describe cómo debe trabajar la organización. Esa diferencia es la más importante del tema. Una empresa con un sistema de gestión certificado puede entregar un producto malo, y un producto excelente puede salir de una empresa sin ninguna certificación. Por eso el comprador maduro pide evidencia de los dos lados.</p>
<section id="recuadro-de-vigencia-y-de-fuentes" class="level3">
<h3 class="anchored" data-anchor-id="recuadro-de-vigencia-y-de-fuentes">Recuadro de vigencia y de fuentes</h3>
<p>Esta guía se verificó el 3 de octubre de 2026 contra las fichas del catálogo de ISO (iso.org) y contra el comunicado de prensa de ISO del 16 de septiembre de 2026. Los textos completos de las normas son de pago y no se reproducen aquí. Lo que la guía afirma sobre el contenido de una norma proviene de su resumen oficial, de su prólogo o introducción cuando estuvo disponible, y de fuentes secundarias que se señalan como tales.</p>
<p>Cuando un dato solo aparece en sitios de certificadoras o consultoras, la guía lo marca como no verificado en fuente primaria. Antes de citar un número de cláusula o una fecha en un informe formal, confírmalo en el texto de la norma o con tu organismo de certificación.</p>
</section>
</section>
<section id="parte-2.-la-serie-square-por-divisiones" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="parte-2.-la-serie-square-por-divisiones"><span class="header-section-number">5</span> Parte 2. La serie SQuaRE por divisiones</h2>
<p>SQuaRE son las siglas en inglés de <em>Systems and software Quality Requirements and Evaluation</em>, requisitos y evaluación de la calidad de sistemas y software. Es la serie ISO/IEC 25000 a 25099, que mantiene el comité ISO/IEC JTC 1/SC 7. En el Tema 2 de la Unidad 1 viste su mapa en una tabla. Aquí lo recorres norma por norma.</p>
<p>La introducción de la propia ISO/IEC 25010:2023 describe la serie en divisiones, y cada división agrupa normas con una misma función. Dos ideas ordenan todo. La primera es la cadena que va del modelo a la medida, al requisito y a la evaluación. La segunda es que ninguna división sirve sola.</p>
<div class="diagrama">
<svg viewbox="0 0 760 340" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Divisiones de la serie SQuaRE: 2500n gestion arriba, 2501n modelos, 2502n medicion y 2503n requisitos en el medio, 2504n evaluacion abajo y una division de extensiones de 25050 a 25099 con la 25059 para inteligencia artificial" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t2b" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Divisiones de SQuaRE y sus normas principales</text> <rect x="210" y="28" width="340" height="58" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="50" font-size="12.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">2500n. Gestión de la calidad</text> <text x="380" y="70" font-size="10.5" fill="#3c7d7a" text-anchor="middle">25000 guía, 25001 planificación, 25002 uso de los modelos</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="20" y="118" width="220" height="92" rx="9"></rect><rect x="270" y="118" width="220" height="92" rx="9"></rect><rect x="520" y="118" width="220" height="92" rx="9"></rect></g> <g text-anchor="middle" font-size="12" font-weight="700" fill="#12324f"><text x="130" y="142">2501n. Modelos</text><text x="380" y="142">2502n. Medición</text><text x="630" y="142">2503n. Requisitos</text></g> <g text-anchor="middle" font-size="10.3" fill="#5b6876"> <text x="130" y="162">25010 producto, 25012 datos</text><text x="130" y="178">25019 calidad en uso</text><text x="130" y="194">TS 25011 servicios de TI</text> <text x="380" y="162">25020 marco, 25021 elementos</text><text x="380" y="178">25022 uso, 25023 producto</text><text x="380" y="194">25024 datos</text> <text x="630" y="162">25030 marco de requisitos</text><text x="630" y="178">usa los modelos 25010 y 25012</text><text x="630" y="194">y las medidas de la 2502n</text> </g> <rect x="20" y="246" width="220" height="70" rx="9" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="130" y="270" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">25050 a 25099. Extensiones</text> <text x="130" y="290" font-size="10.3" fill="#5b6876" text-anchor="middle">25059 modelo de calidad</text> <text x="130" y="305" font-size="10.3" fill="#5b6876" text-anchor="middle">para sistemas de IA</text> <rect x="270" y="246" width="220" height="70" rx="9" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="270" font-size="12.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">2504n. Evaluación</text> <text x="380" y="290" font-size="10.3" fill="#3c7d7a" text-anchor="middle">25040 marco de evaluación</text> <text x="380" y="305" font-size="10.3" fill="#3c7d7a" text-anchor="middle">usa modelo, medidas y requisitos</text> <g fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#u3t2b)"><path d="M300,86 L150,116"></path><path d="M380,86 L380,116"></path><path d="M460,86 L610,116"></path><path d="M240,200 L270,262"></path><path d="M380,210 L380,244"></path><path d="M520,200 L490,262"></path></g>
</svg>
</div>
<section id="las-divisiones-una-por-una" class="level3">
<h3 class="anchored" data-anchor-id="las-divisiones-una-por-una">Las divisiones, una por una</h3>
<ul>
<li><strong>2500n, gestión de la calidad.</strong> Define los modelos, términos y definiciones que usan todas las demás normas de la serie, y da requisitos para la función que gestiona los requisitos, la especificación y la evaluación de la calidad. Incluye la ISO/IEC 25000 (guía de la serie), la 25001 (planificación y gestión) y la ISO/IEC 25002:2024 (resumen y uso de los modelos de calidad).</li>
<li><strong>2501n, modelos de calidad.</strong> Presenta modelos detallados para sistemas y productos de software, datos, servicios de TI y calidad en uso. Aquí viven la ISO/IEC 25010 (producto), la 25012 (datos), la 25019 (calidad en uso) y la especificación técnica 25011 (servicios).</li>
<li><strong>2502n, medición de la calidad.</strong> Reúne el marco de medición, las definiciones matemáticas de las medidas y la guía práctica para aplicarlas. Define también los elementos de medida de calidad, la base sobre la que se construyen las medidas.</li>
<li><strong>2503n, requisitos de calidad.</strong> Ayuda a especificar requisitos de calidad a partir de los modelos y de las medidas, tanto para elicitar requisitos como para dárselos de entrada a una evaluación.</li>
<li><strong>2504n, evaluación de la calidad.</strong> Da requisitos, recomendaciones y guías para evaluar un producto, ya sea que lo evalúen evaluadores independientes, compradores o desarrolladores.</li>
<li><strong>25050 a 25099, extensiones.</strong> Cubren, entre otras cosas, el software listo para usar y los modelos y medidas para tecnologías nuevas, como los servicios en la nube y la inteligencia artificial.</li>
</ul>
<p>Las seis descripciones salen de la introducción de la ISO/IEC 25010:2023. La misma introducción dice que la serie puede usarse junto con las normas de procesos del ciclo de vida (ISO/IEC/IEEE 12207 y 15288), con la familia ISO/IEC 33000 de evaluación de procesos (Tema 4 de esta unidad) y con la ISO 9001 para apoyar la fijación de objetivos de calidad y la revisión del diseño, la verificación y la validación.</p>
</section>
<section id="qué-normas-están-vigentes-a-octubre-de-2026" class="level3">
<h3 class="anchored" data-anchor-id="qué-normas-están-vigentes-a-octubre-de-2026">Qué normas están vigentes a octubre de 2026</h3>
<p>La serie no se renueva toda al mismo tiempo. La tabla recoge el estado que muestran las fichas de ISO el 3 de octubre de 2026.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Norma</th>
<th>Edición vigente</th>
<th>Estado en el catálogo de ISO</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ISO/IEC 25000 (guía de SQuaRE)</td>
<td>2014, edición 2</td>
<td>Publicada y confirmada</td>
</tr>
<tr class="even">
<td>ISO/IEC 25002 (uso de los modelos)</td>
<td>2024, edición 1</td>
<td>Publicada. Junto con la 25010:2023 y la 25019 reemplaza a la 25010:2011</td>
</tr>
<tr class="odd">
<td>ISO/IEC 25010 (modelo de producto)</td>
<td>2023, edición 2</td>
<td>Publicada. La edición de 2011 está retirada</td>
</tr>
<tr class="even">
<td>ISO/IEC 25012 (modelo de datos)</td>
<td>2008, edición 1</td>
<td>Publicada y confirmada</td>
</tr>
<tr class="odd">
<td>ISO/IEC 25019 (calidad en uso)</td>
<td>2023, edición 1</td>
<td>Publicada</td>
</tr>
<tr class="even">
<td>ISO/IEC 25020 (marco de medición)</td>
<td>2019, edición 2</td>
<td>Publicada y confirmada</td>
</tr>
<tr class="odd">
<td>ISO/IEC 25021 (elementos de medida)</td>
<td>2012, edición 1</td>
<td>Publicada y confirmada</td>
</tr>
<tr class="even">
<td>ISO/IEC 25022 (medición de calidad en uso)</td>
<td>2016, edición 1</td>
<td>Publicada, con revisión en curso</td>
</tr>
<tr class="odd">
<td>ISO/IEC 25023 (medición de calidad de producto)</td>
<td>2016, edición 1</td>
<td>Publicada, con revisión en curso</td>
</tr>
<tr class="even">
<td>ISO/IEC 25024 (medición de calidad de datos)</td>
<td>2015, edición 1</td>
<td>Publicada y confirmada</td>
</tr>
<tr class="odd">
<td>ISO/IEC 25030 (marco de requisitos)</td>
<td>2019, edición 2</td>
<td>Publicada y confirmada</td>
</tr>
<tr class="even">
<td>ISO/IEC 25040 (marco de evaluación)</td>
<td>2024, edición 2</td>
<td>Publicada. La edición de 2011 está retirada</td>
</tr>
<tr class="odd">
<td>ISO/IEC 25059 (calidad de sistemas de IA)</td>
<td>2023, edición 1</td>
<td>Publicada, con revisión en curso</td>
</tr>
</tbody>
</table>
<p>Fíjate en una consecuencia práctica. Un texto que cite la “ISO/IEC 25010:2011” cita una edición retirada. El modelo de calidad en uso de cinco características que traía esa edición se reemplazó por el modelo de tres características de la 25019:2023, que ya viste en la Unidad 1.</p>
</section>
<section id="una-numeración-nueva-que-se-está-estrenando" class="level3">
<h3 class="anchored" data-anchor-id="una-numeración-nueva-que-se-está-estrenando">Una numeración nueva que se está estrenando</h3>
<p>Las fichas de ISO de las normas 25022 y 25023 muestran que sus reemplazos están en elaboración con un número distinto. La 25023 será sustituida por el borrador ISO/IEC DIS 25000-23, “Parte 23: medición de calidad de producto”, y la 25022 por el borrador ISO/IEC CD 25000-22. La ficha de la 25023 anuncia que se espera que la sustituya “en los próximos meses”.</p>
<p>El patrón es nuevo. La serie parece migrar de números sueltos (25022, 25023) a partes numeradas dentro de la ISO/IEC 25000. Mientras esos borradores no se publiquen, las ediciones de 2016 siguen siendo las vigentes. No se afirma aquí el contenido de los borradores, porque no son públicos.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Qué cambia cuando una norma está “en revisión”
</div>
</div>
<div class="callout-body-container callout-body">
<p>El estado de revisión sistemática de ISO ocurre cada cinco años. Una norma “por revisar” sigue vigente. Se cita con su edición publicada, y conviene mirar su ficha antes de entregar un informe, porque la nueva edición puede salir sin aviso previo.</p>
</div>
</div>
</section>
<section id="las-nueve-características-solo-una-referencia" class="level3">
<h3 class="anchored" data-anchor-id="las-nueve-características-solo-una-referencia">Las nueve características, solo una referencia</h3>
<p>La ISO/IEC 25010:2023 define el modelo de producto con nueve características. Su prólogo explica los cambios principales respecto de 2011. Se agregó la seguridad frente a daños (<em>safety</em>), usabilidad pasó a capacidad de interacción y portabilidad pasó a flexibilidad. La clasificación completa de las nueve, con ejemplos en la app de turnos, está en el <a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html">Tema 2 de la Unidad 1</a>. Esta guía no la repite.</p>
</section>
</section>
<section id="parte-3.-calidad-de-los-datos" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="parte-3.-calidad-de-los-datos"><span class="header-section-number">6</span> Parte 3. Calidad de los datos</h2>
<p>La ISO/IEC 25010 mide el producto. Un sistema puede tener un código impecable y fallarle al usuario porque sus datos están incompletos, desactualizados o contradictorios. La ISO/IEC 25012, publicada en 2008 y confirmada desde entonces, define un modelo de calidad para datos guardados en formato estructurado dentro de un sistema, como las tablas de una base de datos relacional. Su resumen oficial dice que sirve para establecer requisitos de calidad de datos, definir medidas y planificar evaluaciones, por ejemplo en procesos de adquisición e integración de datos o para evaluar el cumplimiento de la legislación.</p>
<section id="dos-miradas-y-quince-características" class="level3">
<h3 class="anchored" data-anchor-id="dos-miradas-y-quince-características">Dos miradas y quince características</h3>
<p>El modelo organiza quince características desde dos puntos de vista. La calidad inherente se refiere al dato en sí mismo, a sus valores y restricciones, a las relaciones entre valores y a los metadatos. La calidad dependiente del sistema se refiere a lo que logran o conservan los componentes de la plataforma, como el hardware, el software de respaldo o las herramientas de migración. Algunas características pertenecen a las dos miradas.</p>
<div class="diagrama">
<svg viewbox="0 0 760 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Las quince caracteristicas de la ISO IEC 25012 en tres grupos: cinco inherentes, siete que son de ambos tipos y tres dependientes del sistema" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">ISO/IEC 25012. Quince características en tres grupos</text> <rect x="14" y="32" width="226" height="258" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="254" y="32" width="256" height="258" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <rect x="524" y="32" width="222" height="258" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="127" y="58" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Solo inherentes (5)</text> <text x="382" y="58" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Inherentes y de sistema (7)</text> <text x="635" y="58" font-size="13" font-weight="700" fill="#0e6f6c" text-anchor="middle">Solo de sistema (3)</text> <g font-size="12" fill="#12324f"> <text x="40" y="94">Exactitud</text><text x="40" y="124">Completitud</text><text x="40" y="154">Consistencia</text><text x="40" y="184">Credibilidad</text><text x="40" y="214">Vigencia (currentness)</text> <text x="282" y="90">Accesibilidad</text><text x="282" y="115">Cumplimiento</text><text x="282" y="140">Confidencialidad</text><text x="282" y="165">Eficiencia</text><text x="282" y="190">Precisión</text><text x="282" y="215">Trazabilidad</text><text x="282" y="240">Comprensibilidad</text> <text x="550" y="94">Disponibilidad</text><text x="550" y="124">Portabilidad</text><text x="550" y="154">Recuperabilidad</text> </g> <text x="127" y="262" font-size="10.3" fill="#5b6876" text-anchor="middle">propias del contenido del dato</text> <text x="382" y="270" font-size="10.3" fill="#5b6876" text-anchor="middle">dependen del dato y del sistema</text> <text x="635" y="262" font-size="10.3" fill="#3c7d7a" text-anchor="middle">las logra la plataforma</text> <text x="380" y="314" font-size="10.8" fill="#5b6876" text-anchor="middle">Agrupación según el modelo de la norma, tal como la reproduce la literatura académica</text>
</svg>
</div>
<p>La agrupación en tres bloques sale de la tabla de definiciones que reproduce un estudio académico de 2025 sobre herramientas de calidad de datos (Papastergios, Ehrlinger y Gounaris), que a su vez cita la norma. El resumen oficial de ISO solo dice “quince características desde dos puntos de vista”, así que la clasificación por bloques se atribuye a esa fuente secundaria.</p>
</section>
<section id="las-quince-características-con-la-app-de-turnos" class="level3">
<h3 class="anchored" data-anchor-id="las-quince-características-con-la-app-de-turnos">Las quince características, con la app de turnos</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Característica</th>
<th>Qué pregunta responde</th>
<th>Ejemplo en la clínica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exactitud</td>
<td>¿El valor representa la realidad? Tiene un aspecto sintáctico (formato válido) y uno semántico (valor correcto)</td>
<td>Documento con 9 dígitos y formato válido, pero que pertenece a otro paciente</td>
</tr>
<tr class="even">
<td>Completitud</td>
<td>¿Están todos los valores esperados?</td>
<td>Turnos sin teléfono de contacto</td>
</tr>
<tr class="odd">
<td>Consistencia</td>
<td>¿Está libre de contradicción respecto de otros datos?</td>
<td>El turno aparece “confirmado” en la agenda y “cancelado” en el historial</td>
</tr>
<tr class="even">
<td>Credibilidad</td>
<td>¿Los usuarios lo consideran verdadero y creíble? Incluye autenticidad del origen</td>
<td>Un turno cargado por una hoja de cálculo que nadie reconoce como fuente oficial</td>
</tr>
<tr class="odd">
<td>Vigencia</td>
<td>¿Tiene la edad adecuada para el uso?</td>
<td>La agenda de un médico que se actualizó hace tres días</td>
</tr>
<tr class="even">
<td>Accesibilidad</td>
<td>¿Se puede acceder a él, incluso con tecnología de apoyo?</td>
<td>Datos del turno que un lector de pantalla no puede leer</td>
</tr>
<tr class="odd">
<td>Cumplimiento</td>
<td>¿Cumple normas, convenciones o reglamentos sobre calidad de datos?</td>
<td>Campos de salud que no siguen el estándar exigido por una entidad</td>
</tr>
<tr class="even">
<td>Confidencialidad</td>
<td>¿Solo lo ve quien debe?</td>
<td>Un recepcionista que ve diagnósticos que no necesita</td>
</tr>
<tr class="odd">
<td>Eficiencia</td>
<td>¿Se procesa con rendimiento esperado y recursos adecuados?</td>
<td>Consultar la agenda del mes tarda 30 segundos</td>
</tr>
<tr class="even">
<td>Precisión</td>
<td>¿Es exacto o permite discriminar?</td>
<td>La hora del turno guardada solo como “mañana” o “tarde”</td>
</tr>
<tr class="odd">
<td>Trazabilidad</td>
<td>¿Hay rastro de accesos y cambios?</td>
<td>Nadie sabe quién cambió la fecha de un turno</td>
</tr>
<tr class="even">
<td>Comprensibilidad</td>
<td>¿Se lee e interpreta sin ambigüedad, con idioma, símbolos y unidades adecuados?</td>
<td>Estados con códigos como “E3” sin tabla de significados</td>
</tr>
<tr class="odd">
<td>Disponibilidad</td>
<td>¿Los usuarios autorizados pueden recuperarlo cuando lo necesitan?</td>
<td>La base de datos cae a las 7 de la mañana, hora de mayor demanda</td>
</tr>
<tr class="even">
<td>Portabilidad</td>
<td>¿Se puede mover entre sistemas conservando su calidad?</td>
<td>Migrar agendas a otro proveedor y perder el historial</td>
</tr>
<tr class="odd">
<td>Recuperabilidad</td>
<td>¿Mantiene su calidad aun ante una falla?</td>
<td>Tras una caída, los turnos de la tarde no se restauran</td>
</tr>
</tbody>
</table>
</section>
<section id="un-caso-para-analizar" class="level3">
<h3 class="anchored" data-anchor-id="un-caso-para-analizar">Un caso para analizar</h3>
<p>Situación. El área de registro de una universidad ve que dos reportes dan un número distinto de matriculados en el mismo curso. El código de cada reporte funciona correctamente. La tabla de matrículas y la tabla histórica de inscripciones dejaron de coincidir en algún punto.</p>
<p>Pregunta de análisis. ¿Hay que buscar un defecto en el código o un defecto en el dato?</p>
<p>Respuesta. Es un defecto de dato, una falla de consistencia en el vocabulario de la 25012. Separar los dos modelos evita perseguir un defecto de programa donde hay un defecto de datos, y también el error contrario, que es culpar a los datos de un problema que está en la lógica del programa.</p>
</section>
<section id="medir-los-datos-y-la-serie-isoiec-5259-para-aprendizaje-automático" class="level3">
<h3 class="anchored" data-anchor-id="medir-los-datos-y-la-serie-isoiec-5259-para-aprendizaje-automático">Medir los datos, y la serie ISO/IEC 5259 para aprendizaje automático</h3>
<p>La ISO/IEC 25024:2015 define las medidas de calidad de datos para las características de la 25012. Según su resumen, incluye un conjunto básico de medidas por característica, las entidades a las que se aplican durante el ciclo de vida del dato, una explicación de cómo aplicarlas y una guía para que cada organización defina sus propias medidas. No fija rangos de valores aceptables, porque esos valores dependen de cada sistema y de lo que necesitan sus usuarios.</p>
<p>Para los datos que alimentan sistemas de aprendizaje automático existe otra familia, la serie ISO/IEC 5259, <em>Artificial intelligence, Data quality for analytics and machine learning</em>. Las fichas de ISO muestran cuatro partes publicadas en 2024. La parte 1 da visión general y terminología, la parte 2 las medidas de calidad de datos, la parte 3 los requisitos y guías de gestión de calidad de datos, y la parte 4 el marco de procesos de calidad de datos. Esta guía las nombra para que ubiques el terreno. No desarrolla su contenido.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Clasifica cuatro problemas de datos de la clínica
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para cada situación, escribe la característica de la ISO/IEC 25012 que más claramente falla y si es inherente, de sistema o de ambos tipos.</p>
<ol type="1">
<li>Las agendas de tres médicos muestran los turnos de la semana pasada, aunque ya hubo cambios.</li>
<li>Después de un corte de energía, 85 turnos ya confirmados desaparecen y no se pueden reconstruir.</li>
<li>Un paciente cambió su fecha de nacimiento y no queda registro de quién lo hizo ni cuándo.</li>
<li>El campo “documento” de 12 pacientes contiene letras y símbolos, como “C.C.#12a45”.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Vigencia (<em>currentness</em>). Es una característica inherente: el dato no tiene la edad adecuada para el uso.</li>
<li>Recuperabilidad. Es una característica dependiente del sistema, porque la logran las copias de respaldo y la plataforma. Aquí fallaron.</li>
<li>Trazabilidad. Pertenece al grupo de las que son inherentes y dependientes del sistema, porque exige tanto atributos del dato como un registro de auditoría de la plataforma.</li>
<li>Exactitud sintáctica. Es inherente: el valor no respeta el formato del dominio válido, que es solo de dígitos.</li>
</ol>
<p>Si dudaste entre exactitud y consistencia en el caso 3 o 4, recuerda que consistencia compara un dato con otro, y exactitud compara un dato con la realidad o con su dominio válido.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-4.-medir-la-calidad-el-patrón-de-la-serie-2502n" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="parte-4.-medir-la-calidad-el-patrón-de-la-serie-2502n"><span class="header-section-number">7</span> Parte 4. Medir la calidad: el patrón de la serie 2502n</h2>
<p>Un modelo de calidad dice qué mirar. Una medida dice cuánto. La división 2502n existe para pasar de lo primero a lo segundo, y se apoya en tres normas de base y en tres normas de aplicación.</p>
<section id="las-normas-de-base-y-las-de-aplicación" class="level3">
<h3 class="anchored" data-anchor-id="las-normas-de-base-y-las-de-aplicación">Las normas de base y las de aplicación</h3>
<p>La ISO/IEC 25020:2019 es el marco de medición. Contiene el modelo de referencia de la medición de calidad, las relaciones entre los tipos de medidas, guías para seleccionar y construir medidas, y guías para planificar y ejecutar mediciones. Sus anexos tratan la fiabilidad de la medición y la validez de las medidas, los elementos para documentar una medida y la función de medición normalizada.</p>
<p>La ISO/IEC 25021:2012 define los elementos de medida de calidad. Según su resumen, un elemento de medida es una medida definida por una propiedad y el método de medición que la cuantifica, con una transformación matemática opcional. Son los ladrillos con los que se arman las medidas.</p>
<p>Las tres normas de aplicación, cada una para un objeto distinto, son estas.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Norma</th>
<th>Objeto que mide</th>
<th>Referencia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ISO/IEC 25023:2016</td>
<td>Calidad de sistema y de producto de software</td>
<td>Características y subcaracterísticas de la ISO/IEC 25010</td>
</tr>
<tr class="even">
<td>ISO/IEC 25022:2016</td>
<td>Calidad en uso</td>
<td>Características del modelo de calidad en uso (ver nota)</td>
</tr>
<tr class="odd">
<td>ISO/IEC 25024:2015</td>
<td>Calidad de los datos</td>
<td>Características de la ISO/IEC 25012</td>
</tr>
</tbody>
</table>
<p>Nota. La 25022 y la 25023 son de 2016 y se escribieron para el modelo de 2011. La ISO/IEC 25010:2023 es posterior, y la ficha de la 25023 ya anuncia su reemplazo. No se afirma aquí cómo se alinean exactamente con el modelo de 2023. Si necesitas esa correspondencia, consulta el texto de las normas o los borradores cuando se publiquen.</p>
</section>
<section id="lo-que-las-tres-normas-dicen-y-lo-que-no-dicen" class="level3">
<h3 class="anchored" data-anchor-id="lo-que-las-tres-normas-dicen-y-lo-que-no-dicen">Lo que las tres normas dicen y lo que no dicen</h3>
<p>Los resúmenes oficiales de la 25022, la 25023 y la 25024 coinciden en dos puntos que conviene aprender.</p>
<p>Primero, ninguna fija rangos de valores aceptables. Dicen que esos valores se definen para cada sistema según su naturaleza, la categoría del software, el nivel de integridad y las necesidades de los usuarios. En otras palabras, la norma te da la forma de la medida y la organización decide el umbral. Segundo, el conjunto de medidas que traen es básico y sugerido. No es una lista exhaustiva ni obligatoria.</p>
</section>
<section id="ejemplo-resuelto-medir-tres-capas-de-la-app-de-turnos" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-medir-tres-capas-de-la-app-de-turnos">Ejemplo resuelto: medir tres capas de la app de turnos</h3>
<p>Un aviso antes de empezar. Las medidas que siguen están construidas con el patrón de la serie, que es una razón entre dos elementos de medida, X = A / B. Sus nombres y redacción son del docente. No son copia literal del catálogo de medidas de la 25023, la 25022 o la 25024, cuyo texto es de pago. Los números de la clínica son inventados.</p>
<p>Situación. El equipo de la Clínica Aurora quiere saber cómo está la versión 1.2 de la app antes de abrirla a todas las especialidades. Decide medir tres capas: el producto (¿asigna bien los turnos?), los datos (¿están buenos los turnos de la semana?) y el uso (¿los pacientes logran sacar su turno?).</p>
<p><strong>Paso 1. Medida de producto: corrección funcional de RF-01.</strong></p>
<p>El requisito RF-01 dice que la app asigna hasta 20 turnos por día a cada especialidad. El equipo diseña 60 casos de prueba sobre esa regla, con 20, 21 y 0 turnos, cambio de día y varias especialidades a la vez.</p>
<ul>
<li>Elemento A: casos de prueba cuyo resultado es el esperado. Se ejecutan y resultan 57.</li>
<li>Elemento B: casos de prueba ejecutados. Son 60.</li>
<li>Medida: X = A / B = 57 / 60 = 0,95.</li>
</ul>
<p><strong>Paso 2. Medidas de datos: tres medidas sobre 500 turnos de Cardiología de la semana.</strong></p>
<p>El equipo exporta los 500 turnos de la semana y calcula tres medidas, una por característica de la ISO/IEC 25012.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Característica</th>
<th>Elemento A</th>
<th>Elemento B</th>
<th>X = A / B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Completitud del teléfono</td>
<td>460 turnos con teléfono</td>
<td>500 turnos</td>
<td>0,92</td>
</tr>
<tr class="even">
<td>Exactitud sintáctica del documento</td>
<td>485 documentos con formato válido</td>
<td>500 turnos</td>
<td>0,97</td>
</tr>
<tr class="odd">
<td>Consistencia del estado</td>
<td>491 turnos con el mismo estado en la agenda y en el historial</td>
<td>500 turnos</td>
<td>0,982</td>
</tr>
</tbody>
</table>
<p>Una cuarta medida mide vigencia. De las 20 agendas de especialistas, 18 se actualizaron en las últimas 24 horas, así que X = 18 / 20 = 0,90.</p>
<p><strong>Paso 3. Medida de uso: tarea completada, con diez pacientes.</strong></p>
<p>En el piloto con diez pacientes mayores de 65 años, el equipo mide cuántos sacan su turno sin ayuda. Resultan 3.</p>
<ul>
<li>Elemento A: pacientes que completan la tarea. Son 3.</li>
<li>Elemento B: pacientes que lo intentan. Son 10.</li>
<li>Medida: X = A / B = 3 / 10 = 0,30.</li>
</ul>
<p><strong>Paso 4. Poner el umbral, que es una decisión de la clínica y no de la norma.</strong></p>
<p>Como las normas no fijan rangos, el equipo fija los suyos con sus datos y sus riesgos. La tabla muestra el resultado de comparar.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Medida</th>
<th>Valor</th>
<th>Umbral que fija la clínica</th>
<th>Resultado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Corrección funcional de RF-01</td>
<td>0,95</td>
<td>0,98 o más</td>
<td>No cumple</td>
</tr>
<tr class="even">
<td>Completitud del teléfono</td>
<td>0,92</td>
<td>0,98 o más</td>
<td>No cumple</td>
</tr>
<tr class="odd">
<td>Exactitud sintáctica del documento</td>
<td>0,97</td>
<td>0,99 o más</td>
<td>No cumple</td>
</tr>
<tr class="even">
<td>Consistencia del estado</td>
<td>0,982</td>
<td>0,99 o más</td>
<td>No cumple</td>
</tr>
<tr class="odd">
<td>Vigencia de las agendas</td>
<td>0,90</td>
<td>0,95 o más</td>
<td>No cumple</td>
</tr>
<tr class="even">
<td>Tarea completada por pacientes mayores</td>
<td>0,30</td>
<td>0,80 o más</td>
<td>No cumple</td>
</tr>
</tbody>
</table>
<p><strong>Paso 5. Leer los resultados.</strong></p>
<p>Las seis medidas quedan por debajo del umbral, pero no pesan igual. Tres lecturas ordenan la decisión.</p>
<ul>
<li>Los 3 casos de prueba que fallan en RF-01 son tres defectos candidatos que hay que reproducir y corregir. Es un asunto de producto.</li>
<li>Los 40 turnos sin teléfono (500 menos 460) son pacientes que no recibirán recordatorio por mensaje. Es un asunto de datos que se corrige en el formulario de captura, no en el algoritmo de asignación.</li>
<li>La medida de 0,30 en pacientes mayores es la más baja y la que más afecta el resultado para las personas. Es un asunto de calidad en uso, y su causa probable está en capacidad de interacción, como se vio en la Unidad 1.</li>
</ul>
<p><strong>Paso 6. Dos precauciones que cualquiera debe tomar.</strong></p>
<p>Una razón sobre muestras pequeñas es frágil. Diez pacientes alcanzan para detectar un problema grave de uso, pero no para estimar con precisión el porcentaje real. Además, una medida donde “menos es mejor”, como las fallas por cada mil usos, se normaliza como 1 menos la razón para que todas las medidas de la tabla se lean en la misma dirección. El marco de medición (25020) trae en uno de sus anexos una función de normalización con ese fin.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Calcula y decide
</div>
</div>
<div class="callout-body-container callout-body">
<p>Con otra semana de datos de la clínica, el equipo obtiene lo siguiente sobre 400 turnos de Pediatría.</p>
<ul>
<li>372 turnos tienen teléfono de contacto.</li>
<li>396 turnos tienen el mismo estado en la agenda y en el historial.</li>
<li>De 15 agendas de especialistas, 12 se actualizaron en las últimas 24 horas.</li>
<li>De 80 casos de prueba de RF-01, 78 dan el resultado esperado.</li>
</ul>
<p>Calcula las cuatro medidas con tres decimales, compáralas con los umbrales del ejemplo (0,98 para teléfono y corrección funcional, 0,99 para consistencia, 0,95 para vigencia) y di cuál es la más urgente de atender.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Completitud del teléfono: 372 / 400 = 0,930. Umbral 0,98. No cumple. Faltan 28 teléfonos.</li>
<li>Consistencia del estado: 396 / 400 = 0,990. Umbral 0,99. Cumple, justo en el límite.</li>
<li>Vigencia de las agendas: 12 / 15 = 0,800. Umbral 0,95. No cumple. Fallan 3 agendas.</li>
<li>Corrección funcional de RF-01: 78 / 80 = 0,975. Umbral 0,98. No cumple por muy poco, con 2 casos fallidos.</li>
</ul>
<p>La más urgente depende de la consecuencia y no del tamaño de la brecha. La vigencia tiene la brecha mayor (0,15 bajo el umbral), y una agenda desactualizada manda al paciente a una cita que ya no existe, así que es razonable atenderla primero. Los 2 casos fallidos de RF-01 se reproducen y se corrigen en paralelo, porque son pocos y concretos. Cualquier respuesta se acepta si justifica la prioridad con una consecuencia para el paciente.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-5.-requisitos-y-evaluación-de-la-calidad" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="parte-5.-requisitos-y-evaluación-de-la-calidad"><span class="header-section-number">8</span> Parte 5. Requisitos y evaluación de la calidad</h2>
<section id="isoiec-25030-el-marco-de-requisitos-de-calidad" class="level3">
<h3 class="anchored" data-anchor-id="isoiec-25030-el-marco-de-requisitos-de-calidad">ISO/IEC 25030: el marco de requisitos de calidad</h3>
<p>La ISO/IEC 25030:2019 da el marco para los requisitos de calidad de sistemas, productos de software y datos. Incluye el concepto de requisito de calidad y los requisitos y recomendaciones para los procesos y métodos con que se elicitan, definen, usan y gobiernan. Su resumen aclara dos cosas. Cumple los procesos técnicos de la ISO/IEC/IEEE 15288. Y usa los modelos de la 25010 y de la 25012 para categorizar los requisitos y las medidas de la serie 2502n para cuantificarlos.</p>
<p>En la práctica, es el origen del requisito medible que viste en el Tema 2 de la Unidad 1 con sus cinco piezas. La 25030 no cubre los otros requisitos, como los funcionales o los de proceso.</p>
</section>
<section id="isoiec-25040-el-marco-de-evaluación" class="level3">
<h3 class="anchored" data-anchor-id="isoiec-25040-el-marco-de-evaluación">ISO/IEC 25040: el marco de evaluación</h3>
<p>La ISO/IEC 25040:2024, edición 2, reemplazó a la de 2011, que fue retirada. Su resumen la presenta como el marco para evaluar la calidad de productos de TIC (incluido el software), datos y servicios de TI. Se dirige a quienes necesitan evaluar una entidad: organizaciones de desarrollo, compradores, proveedores de servicios de TI y evaluadores independientes. Aclara que no da métodos de prueba específicos ni guía para usar los resultados.</p>
<p>Dos detalles conviene retener. El alcance se amplió de “producto de software” a producto, datos y servicios. Y la norma da un marco, no un procedimiento de pruebas. La edición de 2011, según descripciones secundarias, organizaba el proceso en cinco actividades (establecer requisitos, especificar, diseñar, ejecutar y concluir la evaluación). El texto de la edición de 2024 es de pago y no se consultó, así que no se afirma si conserva esa secuencia.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. Ubica seis actividades en la serie SQuaRE
</div>
</div>
<div class="callout-body-container callout-body">
<p>Escribe, para cada actividad, la división (2500n, 2501n, 2502n, 2503n o 2504n) que la sustenta.</p>
<ol type="1">
<li>Decidir que la app de turnos se evaluará con las características de calidad de producto.</li>
<li>Escribir que el tiempo de respuesta debe ser de 2 segundos o menos en el 95 por ciento de las solicitudes.</li>
<li>Calcular la razón entre casos de prueba correctos y casos ejecutados.</li>
<li>Un evaluador independiente aplica modelo, medidas y requisitos a la app y emite un veredicto.</li>
<li>Consultar cuántas características tiene el modelo de datos de la clínica.</li>
<li>Buscar el vocabulario común que usan todas las normas de la serie.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Modelo de calidad (2501n), porque se elige el modelo de referencia.</li>
<li>Requisitos de calidad (2503n), por tratarse de especificar un requisito medible.</li>
<li>Medición de la calidad (2502n), porque es una razón entre dos elementos de medida.</li>
<li>Evaluación de la calidad (2504n), porque se aplican los otros tres elementos a un producto real.</li>
<li>Modelo de calidad (2501n), pues el modelo de datos es la ISO/IEC 25012.</li>
<li>Gestión de la calidad (2500n), que reúne los términos y modelos comunes.</li>
</ol>
<p>La cadena completa, modelo, medida, requisito y evaluación, explica por qué ninguna división sirve sola.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-6.-iso-9001-a-fondo" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="parte-6.-iso-9001-a-fondo"><span class="header-section-number">9</span> Parte 6. ISO 9001 a fondo</h2>
<section id="qué-es-y-qué-no-es" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-y-qué-no-es">Qué es y qué no es</h3>
<p>La ISO 9001 especifica los requisitos de un sistema de gestión de la calidad. Sirve a cualquier organización, de cualquier tamaño y sector, sin importar si fabrica autopartes, atiende pacientes o desarrolla software. De toda la familia ISO 9000 es la única norma contra la que se puede certificar, aunque la certificación no es obligatoria. Según la página oficial de ISO hay más de un millón de certificados emitidos en 189 países, lo que la hace la norma de gestión de la calidad más usada del mundo.</p>
<p>Una distinción previa, que se retoma en la Unidad 4, Tema 4. La ISO 9001 certifica que el sistema de gestión funciona, no que cada producto sea bueno. Un sistema de gestión maduro mejora la probabilidad de entregar buenos productos, pero no la garantiza.</p>
</section>
<section id="la-edición-vigente-iso-90012026" class="level3">
<h3 class="anchored" data-anchor-id="la-edición-vigente-iso-90012026">La edición vigente: ISO 9001:2026</h3>
<p>Esta guía se escribe después de un cambio importante. El 16 de septiembre de 2026, ISO anunció la publicación de la ISO 9001:2026, <em>Quality management systems, Requirements</em>. Es la sexta edición, tiene 36 páginas según su ficha, y su estado en el catálogo es “publicada”. La ficha de la ISO 9001:2015 y la de su Enmienda 1:2024 figuran ahora como retiradas.</p>
<p>Tres hechos de esa publicación conviene tenerlos claros.</p>
<ul>
<li>La ISO 9001:2026 reemplaza a la ISO 9001:2015. Las organizaciones certificadas en la edición de 2015 tienen tres años para pasar a la de 2026, y no necesitan empezar el proceso de certificación desde cero. Su organismo de certificación les indica los plazos.</li>
<li>La fecha exacta del fin del periodo de transición no se verificó en fuente primaria. Varias certificadoras la ubican a fines de septiembre de 2029, tres años después de la publicación. Confírmala con tu organismo de certificación.</li>
<li>Las ediciones de ISO 9000 y de ISO 19011, normas de apoyo, también se renovaron en mayo de 2026. La ISO 9000:2026 (edición 5, fundamentos y vocabulario) reemplaza a la de 2015, y la ISO 19011:2026 (edición 4, directrices para auditar sistemas de gestión) reemplaza a la de 2018.</li>
</ul>
</section>
<section id="qué-cambió-según-iso-y-qué-sigue-igual" class="level3">
<h3 class="anchored" data-anchor-id="qué-cambió-según-iso-y-qué-sigue-igual">Qué cambió, según ISO, y qué sigue igual</h3>
<p>La página oficial de ISO resume los cambios de la ISO 9001:2026 como refinamientos, no como un enfoque nuevo. Estos son los cinco que ISO destaca, con la cláusula que menciona.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Cambio</th>
<th>Cláusula</th>
<th>Qué significa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Liderazgo más explícito</td>
<td>5.1</td>
<td>Se refuerza la cultura de calidad y el comportamiento ético, y crear un ambiente donde todos contribuyen al sistema</td>
</tr>
<tr class="even">
<td>Política de calidad alineada con la estrategia</td>
<td>5.2</td>
<td>La política se vincula más claramente con el contexto y la dirección estratégica</td>
</tr>
<tr class="odd">
<td>Riesgos y oportunidades por separado</td>
<td>6.1</td>
<td>Se distingue mejor gestionar los riesgos de perseguir las oportunidades</td>
</tr>
<tr class="even">
<td>Énfasis en las personas</td>
<td>7.3</td>
<td>Nuevos requisitos de toma de conciencia sobre la cultura de calidad y el comportamiento ético</td>
</tr>
<tr class="odd">
<td>Anexo A nuevo</td>
<td>Anexo A</td>
<td>Aclara conceptos, terminología y la intención de los requisitos, para aplicarlos de forma consistente</td>
</tr>
</tbody>
</table>
<p>Lo que sigue igual también importa. ISO afirma que la estructura de cláusulas no cambió, porque conserva la Estructura de Alto Nivel (<em>Harmonized Structure</em>) que comparten las normas de sistemas de gestión. Se mantienen el enfoque al cliente, el enfoque de procesos, el pensamiento basado en riesgos y la mejora continua. La edición de 2026 además conserva la consideración del cambio climático que la Enmienda 1:2024 había añadido a la edición de 2015.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Lo que no se verificó en fuente primaria sobre la edición 2026
</div>
</div>
<div class="callout-body-container callout-body">
<p>Varias certificadoras y consultoras describen cambios más finos. Mencionan, por ejemplo, que la cláusula 6.1 se parte en una subcláusula de riesgos y otra de oportunidades, que la gestión del cambio (6.3) pasa de cuatro a siete consideraciones, y que cambian partes de 8.4 (proveedores externos) y 9.2 (auditoría interna). Estas afirmaciones provienen de sitios de certificadoras y no se confirmaron en el texto de la norma, que es de pago. Antes de usarlas en un informe, consulta el texto de la norma.</p>
</div>
</div>
</section>
<section id="la-enmienda-12024-un-puente-que-quedó-atrás" class="level3">
<h3 class="anchored" data-anchor-id="la-enmienda-12024-un-puente-que-quedó-atrás">La Enmienda 1:2024, un puente que quedó atrás</h3>
<p>La ISO 9001:2015/Amd 1:2024 se publicó en febrero de 2024 y añadió el cambio climático a las cláusulas 4.1 y 4.2: la organización determina si es una cuestión pertinente y reconoce que las partes interesadas pueden tener requisitos sobre él. Esa información proviene de listados de organismos de normalización y no de la ficha de ISO. Hoy la Enmienda figura como retirada, porque la edición de 2026 incorpora su contenido.</p>
</section>
<section id="las-siete-cláusulas-auditables" class="level3">
<h3 class="anchored" data-anchor-id="las-siete-cláusulas-auditables">Las siete cláusulas auditables</h3>
<p>La ISO 9001 tiene diez cláusulas. Las tres primeras (alcance, referencias normativas y términos) no se auditan. Las siete siguientes contienen los requisitos, y la página de ISO las presenta en este orden.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Cláusula</th>
<th>Tema</th>
<th>Qué pregunta un auditor</th>
<th>Evidencia posible en la clínica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4</td>
<td>Contexto de la organización</td>
<td>¿Conoce la organización los factores internos y externos que afectan su sistema?</td>
<td>Análisis de contexto con regulación de datos de salud, competencia y cambio de normas</td>
</tr>
<tr class="even">
<td>5</td>
<td>Liderazgo</td>
<td>¿La dirección asume la calidad como responsabilidad propia?</td>
<td>Política de calidad firmada, objetivos revisados por la gerencia</td>
</tr>
<tr class="odd">
<td>6</td>
<td>Planificación</td>
<td>¿Se planifican las acciones para riesgos, oportunidades y objetivos?</td>
<td>Matriz de riesgos de la app y plan para lograr los objetivos</td>
</tr>
<tr class="even">
<td>7</td>
<td>Apoyo</td>
<td>¿Hay recursos, competencia, toma de conciencia, comunicación y documentación?</td>
<td>Registros de capacitación, procedimientos controlados, herramientas licenciadas</td>
</tr>
<tr class="odd">
<td>8</td>
<td>Operación</td>
<td>¿Se planifican y controlan los procesos que entregan el producto?</td>
<td>Registros de diseño, revisiones, pruebas, control de cambios, gestión de proveedores</td>
</tr>
<tr class="even">
<td>9</td>
<td>Evaluación del desempeño</td>
<td>¿Se mide, se audita y se revisa?</td>
<td>Indicadores, informes de auditoría interna, actas de revisión por la dirección</td>
</tr>
<tr class="odd">
<td>10</td>
<td>Mejora</td>
<td>¿Se corrigen las desviaciones y se mejora de forma continua?</td>
<td>Registro de no conformidades y acciones correctivas</td>
</tr>
</tbody>
</table>
<p>El contenido de cada una proviene de la descripción oficial de ISO. La evidencia de la última columna es un ejemplo del docente, no una lista de la norma.</p>
</section>
<section id="la-cláusula-8-en-una-empresa-de-software" class="level3">
<h3 class="anchored" data-anchor-id="la-cláusula-8-en-una-empresa-de-software">La cláusula 8 en una empresa de software</h3>
<p>La cláusula 8 es donde el software aparece de forma más visible. En la edición de 2015, su numeración distinguía requisitos para el diseño y desarrollo (8.3), proveedores externos (8.4), la producción y la provisión del servicio (8.5), la liberación (8.6) y las salidas no conformes (8.7). Esa numeración es de la edición de 2015. Como ISO afirma que la estructura no cambió en 2026, la lógica se mantiene, pero los números de subcláusula de 2026 no se verificaron.</p>
<p>Para la app de turnos, esto se traduce en preguntas concretas. ¿Hay revisiones del diseño antes de programar? ¿Cada versión se verifica y se valida antes de liberarla? ¿Cómo se controlan los cambios en los requisitos? ¿Se evalúan los proveedores, como el servicio de mensajería que envía los recordatorios, y las bibliotecas que la app incorpora? ¿Qué se hace con el defecto que llega a producción? Un sistema de gestión bien armado responde cada una con un procedimiento, un registro y un responsable.</p>
</section>
<section id="el-enfoque-de-riesgos-y-oportunidades" class="level3">
<h3 class="anchored" data-anchor-id="el-enfoque-de-riesgos-y-oportunidades">El enfoque de riesgos y oportunidades</h3>
<p>Desde la edición de 2015, la norma exige pensamiento basado en riesgos. En esa edición reemplazó la acción preventiva como requisito separado, según el Anexo A de la ISO 9001:2015 (texto de pago, no consultado). La edición de 2026 refuerza la idea y, según ISO, distingue más claramente los riesgos de las oportunidades.</p>
<p>Un riesgo es un efecto de la incertidumbre que puede alejar el resultado de lo esperado. Una oportunidad es lo contrario, una incertidumbre que puede mejorar el resultado. Se gestionan por separado porque sus respuestas son distintas. Los riesgos se evitan, se reducen, se comparten o se aceptan. Las oportunidades se buscan y se aprovechan.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Tipo</th>
<th>Ejemplo en la app de turnos</th>
<th>Respuesta posible</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Riesgo</td>
<td>Dos pacientes reciben el mismo turno cuando hay solicitudes simultáneas</td>
<td>Restricción única en la base de datos, prueba de concurrencia en cada versión</td>
</tr>
<tr class="even">
<td>Riesgo</td>
<td>El proveedor de mensajería deja de operar</td>
<td>Contrato con segundo proveedor y registro de recordatorios pendientes</td>
</tr>
<tr class="odd">
<td>Oportunidad</td>
<td>Un recordatorio automático puede reducir las inasistencias</td>
<td>Piloto en una especialidad y medición antes y después</td>
</tr>
<tr class="even">
<td>Oportunidad</td>
<td>La clínica abre otra sede y la app puede escalar</td>
<td>Diseñar la agenda por sede desde ahora</td>
</tr>
</tbody>
</table>
</section>
<section id="el-ciclo-phva" class="level3">
<h3 class="anchored" data-anchor-id="el-ciclo-phva">El ciclo PHVA</h3>
<p>PHVA son las siglas de planificar, hacer, verificar y actuar, en inglés PDCA. Es un ciclo de mejora que se asocia con el trabajo de Shewhart y de Deming. La ISO 9001:2015 lo explicaba en su introducción como el método que sostiene el enfoque de procesos. No se verificó si el texto de 2026 conserva esa explicación con las mismas palabras, aunque ISO confirma que el enfoque de procesos y la mejora continua siguen en el centro.</p>
<div class="diagrama">
<svg viewbox="0 0 760 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Ciclo PHVA aplicado al problema de turnos duplicados: planificar la meta de 40 a 10 reclamos por mes, hacer el cambio en una especialidad, verificar con los reclamos de cada mes y actuar extendiendo el cambio" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t2c" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Ciclo PHVA aplicado a los turnos duplicados de la app</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="30" y="40" width="250" height="84" rx="10"></rect><rect x="480" y="40" width="250" height="84" rx="10"></rect><rect x="480" y="206" width="250" height="84" rx="10"></rect><rect x="30" y="206" width="250" height="84" rx="10"></rect></g> <g text-anchor="middle" font-size="13" font-weight="700" fill="#12324f"><text x="155" y="64">1. Planificar</text><text x="605" y="64">2. Hacer</text><text x="605" y="230">3. Verificar</text><text x="155" y="230">4. Actuar</text></g> <g text-anchor="middle" font-size="10.8" fill="#5b6876"> <text x="155" y="84">Meta: bajar de 40 a 10 reclamos</text><text x="155" y="100">por mes en dos meses</text><text x="155" y="116">Causa: solicitudes simultáneas</text> <text x="605" y="84">Restricción única y prueba de</text><text x="605" y="100">concurrencia, solo en</text><text x="605" y="116">Cardiología</text> <text x="605" y="250">Mes 1: 22 reclamos</text><text x="605" y="266">Mes 2: 9 reclamos</text><text x="605" y="282">Meta cumplida</text> <text x="155" y="250">Extender a todas las especialidades</text><text x="155" y="266">y escribir el procedimiento</text><text x="155" y="282">de cambios de agenda</text> </g> <rect x="285" y="125" width="190" height="80" rx="12" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="158" font-size="13" font-weight="700" fill="#0e6f6c" text-anchor="middle">Mejora continua</text> <text x="380" y="178" font-size="10.5" fill="#3c7d7a" text-anchor="middle">el ciclo se repite con</text> <text x="380" y="192" font-size="10.5" fill="#3c7d7a" text-anchor="middle">una meta nueva</text> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u3t2c)"><path d="M280,82 L478,82"></path><path d="M605,124 L605,204"></path><path d="M480,248 L282,248"></path><path d="M155,206 L155,126"></path></g>
</svg>
</div>
<section id="ejemplo-resuelto-phva-sobre-los-turnos-duplicados" class="level4">
<h4 class="anchored" data-anchor-id="ejemplo-resuelto-phva-sobre-los-turnos-duplicados">Ejemplo resuelto: PHVA sobre los turnos duplicados</h4>
<p>Situación. La clínica recibe unos 40 reclamos al mes por turnos duplicados. Los números son ilustrativos.</p>
<p><strong>Planificar.</strong> El equipo revisa los reclamos y encuentra un patrón: ocurren cuando dos pacientes piden el mismo cupo con segundos de diferencia. Fija una meta (no más de 10 reclamos por mes en dos meses), un indicador (reclamos mensuales por turnos duplicados) y un responsable.</p>
<p><strong>Hacer.</strong> Implementa una restricción única en la base de datos y una prueba de concurrencia, y las libera solo en Cardiología para reducir el riesgo de equivocarse en todas a la vez.</p>
<p><strong>Verificar.</strong> Mide los reclamos. El primer mes hay 22 y el segundo 9. Compara contra la meta, no contra impresiones: 9 es menor que 10, se cumple.</p>
<p><strong>Actuar.</strong> Como el cambio funcionó, lo extiende a todas las especialidades, escribe el procedimiento de cambios de agenda para que no dependa de una persona, y deja el registro como evidencia. Luego fija una nueva meta y el ciclo vuelve a empezar.</p>
<p>Observa que cada paso deja un registro. Esos registros son lo que un auditor pide, porque dan evidencia de que el sistema funciona y de que no depende de la memoria de alguien.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 4. Riesgo, oportunidad y ciclo PHVA
</div>
</div>
<div class="callout-body-container callout-body">
<p>La clínica agrega a la app un módulo de pago anticipado del copago.</p>
<ol type="1">
<li>Escribe un riesgo y una oportunidad que ese módulo introduzca, cada uno con una respuesta.</li>
<li>Propón una meta medible para el primer mes y un indicador.</li>
<li>Completa un ciclo PHVA de una línea por paso, con números ilustrativos.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Riesgo: un cobro duplicado cuando el paciente pulsa dos veces. Respuesta: clave de idempotencia por operación y prueba de doble envío. Oportunidad: el pago anticipado reduce las inasistencias porque el paciente ya comprometió dinero. Respuesta: medir inasistencias antes y después en una especialidad piloto.</li>
<li>Meta: cero cobros duplicados en el primer mes. Indicador: número de cobros duplicados reportados por mes.</li>
<li>Planificar: meta de cero duplicados y prueba de doble envío. Hacer: liberar el módulo en una sede. Verificar: el primer mes hay 2 duplicados, que no cumplen la meta. Actuar: corregir la causa, que era el reintento automático del proveedor de pagos, repetir la prueba y recién entonces extender a otras sedes.</li>
</ol>
<p>Tu respuesta puede variar mientras la meta sea medible y cada paso deje un registro.</p>
</div>
</div>
</div>
</section>
</section>
<section id="la-auditoría-interna-y-la-revisión-por-la-dirección" class="level3">
<h3 class="anchored" data-anchor-id="la-auditoría-interna-y-la-revisión-por-la-dirección">La auditoría interna y la revisión por la dirección</h3>
<p>Antes de que llegue el auditor de certificación, la organización se audita a sí misma. La ISO 9001 exige auditorías internas y revisión por la dirección dentro de la evaluación del desempeño (cláusula 9, cuya estructura conserva la edición de 2026). Cada una cumple un papel distinto.</p>
<ul>
<li><strong>Auditoría interna.</strong> Personas de la propia organización, independientes del proceso que auditan, comprueban si el sistema cumple los requisitos de la norma y los propios de la organización.</li>
<li><strong>Revisión por la dirección.</strong> La alta dirección examina los resultados, las auditorías, los indicadores y los riesgos, y decide acciones.</li>
</ul>
<p>La guía para auditar sistemas de gestión es la ISO 19011. Su edición vigente es la ISO 19011:2026, publicada en mayo de 2026 como cuarta edición, que reemplaza a la de 2018.</p>
</section>
<section id="la-auditoría-de-certificación" class="level3">
<h3 class="anchored" data-anchor-id="la-auditoría-de-certificación">La auditoría de certificación</h3>
<p>La ISO no certifica a nadie. Lo dice su propia página: la certificación la hacen organismos externos, y una empresa no puede estar certificada por ISO. Un organismo acreditado es aquel al que un organismo de acreditación reconoce como competente. La acreditación no es obligatoria, y un organismo sin acreditar no es por eso poco serio, pero la acreditación da una confirmación independiente de su competencia.</p>
<p>Dos hechos sobre el sistema internacional de acreditación. La página de ISO indica que la cooperación mundial de acreditación (Global ACI) asumió las funciones que tenían antes el Foro Internacional de Acreditación (IAF) y la ILAC. Y las certificaciones acreditadas pueden verificarse en una base de datos global, IAF CertSearch.</p>
<p>Los organismos de certificación se rigen por la ISO/IEC 17021-1:2015, que según su resumen contiene principios y requisitos de competencia, coherencia e imparcialidad para organismos que auditan y certifican sistemas de gestión. La ficha de esa norma indica que está en revisión.</p>
<p>El recorrido típico se describe así. Es una descripción general basada en las prácticas habituales de los organismos de certificación y en la ISO/IEC 17021-1, cuyo texto es de pago y no se consultó. Los plazos y nombres exactos varían según el organismo.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Fase</th>
<th>Qué ocurre</th>
<th>Resultado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Solicitud y alcance</td>
<td>La organización define el alcance del sistema, por ejemplo “desarrollo y mantenimiento de la app de turnos”</td>
<td>Contrato y programa de auditoría</td>
</tr>
<tr class="even">
<td>Auditoría etapa 1</td>
<td>Revisión de la documentación y de la preparación de la organización</td>
<td>Hallazgos y plan para la etapa 2</td>
</tr>
<tr class="odd">
<td>Auditoría etapa 2</td>
<td>Visita para comprobar que el sistema se aplica: entrevistas, registros, observación</td>
<td>Informe con conformidades y no conformidades</td>
</tr>
<tr class="even">
<td>Tratamiento de hallazgos</td>
<td>La organización corrige y demuestra las correcciones. Las no conformidades se clasifican como mayores o menores</td>
<td>Cierre de hallazgos</td>
</tr>
<tr class="odd">
<td>Decisión</td>
<td>El organismo decide si emite el certificado</td>
<td>Certificado con su alcance</td>
</tr>
<tr class="even">
<td>Seguimiento y renovación</td>
<td>Auditorías de seguimiento durante la vigencia y renovación al cabo de unos tres años</td>
<td>Certificado vigente</td>
</tr>
</tbody>
</table>
<p>Un dato sobre los hallazgos. Una no conformidad es el incumplimiento de un requisito. La diferencia entre mayor y menor la fija cada organismo con criterios propios, de modo que el mismo hallazgo puede clasificarse distinto en dos organismos. La literatura secundaria describe además observaciones y oportunidades de mejora como hallazgos sin incumplimiento.</p>
<p>La ISO 9001:2026 también obliga a pensar cómo se auditan las exigencias nuevas. Una certificadora señala, por ejemplo, que la toma de conciencia de la cultura de calidad (7.3) se prueba entrevistando a las personas y no solo revisando una lista de asistencia. Esa observación proviene de una fuente secundaria. Muestra un criterio general que vale con cualquier edición: el auditor busca evidencia de que algo ocurre, no solo de que se escribió.</p>
</section>
<section id="qué-demuestra-una-certificación-y-qué-no" class="level3">
<h3 class="anchored" data-anchor-id="qué-demuestra-una-certificación-y-qué-no">Qué demuestra una certificación y qué no</h3>
<p>Una certificación ISO 9001 demuestra que un organismo independiente encontró evidencia de que el sistema de gestión de la organización cumple la norma dentro de su alcance. No demuestra que cada producto sea bueno, que el código esté libre de defectos, ni que la organización sea honesta en todas sus decisiones.</p>
<p>Un auditor revisa procedimientos, registros y evidencia por muestreo. No lee línea por línea el código de un producto. Por eso la certificación, aunque útil, no reemplaza las pruebas técnicas, las revisiones de código ni la responsabilidad ética del equipo. Un caso real donde esa diferencia fue decisiva se estudia en la <a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html">Unidad 4, Tema 4</a>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 5. Qué evidencia pedirías y qué concluirías
</div>
</div>
<div class="callout-body-container callout-body">
<p>Eres auditor interno de la clínica.</p>
<ol type="1">
<li>Para la cláusula 7 (apoyo), escribe tres evidencias que pedirías sobre la competencia del equipo de desarrollo.</li>
<li>Para la cláusula 8 (operación), escribe tres evidencias sobre cómo se controla un cambio al algoritmo de asignación.</li>
<li>La clínica muestra su certificado ISO 9001 como prueba de que “la app no tiene errores”. Redacta una frase que corrija esa afirmación.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Registros de formación o certificaciones del equipo, descripciones de cargo con las competencias requeridas, y evaluaciones de desempeño o evidencia de acompañamiento de personal nuevo.</li>
<li>La solicitud de cambio aprobada, el registro de revisión del diseño y de las pruebas ejecutadas (incluida la prueba de RF-01), y la aprobación de liberación con el registro de la versión desplegada.</li>
<li>“El certificado muestra que un organismo independiente comprobó que la clínica gestiona su calidad con un sistema que cumple la norma. No dice que la app esté libre de errores, que se demuestra con pruebas, medidas y revisiones del producto.”</li>
</ol>
<p>Cualquier lista razonable que conecte evidencia con requisito es válida.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-7.-isoiecieee-90003-la-iso-9001-aplicada-al-software" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="parte-7.-isoiecieee-90003-la-iso-9001-aplicada-al-software"><span class="header-section-number">10</span> Parte 7. ISO/IEC/IEEE 90003: la ISO 9001 aplicada al software</h2>
<p>La ISO 9001 es genérica a propósito. Para que una empresa de software la entienda sin traducir cada cláusula por su cuenta, existe la ISO/IEC/IEEE 90003:2018, <em>Software engineering, Guidelines for the application of ISO 9001:2015 to computer software</em>.</p>
<p>Según su resumen oficial, la norma da guías para aplicar la ISO 9001:2015 a la adquisición, el suministro, el desarrollo, la operación y el mantenimiento de software y de los servicios de apoyo relacionados. Cuatro rasgos la definen.</p>
<ul>
<li>No añade requisitos ni cambia los de la ISO 9001. Solo orienta cómo interpretarlos para el software.</li>
<li>No está pensada como criterio de evaluación para certificar un sistema de gestión. Se certifica contra la ISO 9001, no contra la 90003.</li>
<li>Una organización que quiera saber si su sistema también sigue esta guía puede usar las dos normas como criterios de evaluación en el dominio del software.</li>
<li>Su Anexo A es una tabla que remite a guía adicional en normas de ISO/IEC JTC 1/SC 7, ISO/IEC JTC 1/SC 27 e ISO/TC 176.</li>
</ul>
<p>Es la edición de 2018, primera con ese número, confirmada en el catálogo de ISO. Se escribió para la ISO 9001:2015. A octubre de 2026 su ficha no muestra una edición posterior alineada con la ISO 9001:2026. Lo prudente es leerla como guía de la edición de 2015 mientras no se publique otra, y contrastarla con el texto de 2026 cuando se use en un proyecto real.</p>
<p>La ISO 9001 y la 90003 se complementan con los estándares del Tema 1: la IEEE 730 (plan de aseguramiento de la calidad) o la familia 12207 (procesos del ciclo de vida) aportan el detalle técnico que la ISO 9001 deja abierto.</p>
</section>
<section id="parte-8.-inteligencia-artificial-isoiec-25059-e-isoiec-42001" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="parte-8.-inteligencia-artificial-isoiec-25059-e-isoiec-42001"><span class="header-section-number">11</span> Parte 8. Inteligencia artificial: ISO/IEC 25059 e ISO/IEC 42001</h2>
<p>Cuando un producto incluye inteligencia artificial, sus riesgos cambian. Un modelo puede dar respuestas distintas ante entradas casi iguales, aprender de datos sesgados o degradarse con el tiempo. La familia ISO respondió con dos normas que no se deben confundir.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>ISO/IEC 25059:2023</th>
<th>ISO/IEC 42001:2023</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pregunta</td>
<td>¿Qué calidad tiene este sistema de IA?</td>
<td>¿Cómo gestiona esta organización la IA?</td>
</tr>
<tr class="even">
<td>Tipo</td>
<td>Modelo de calidad de producto (extensión de SQuaRE)</td>
<td>Sistema de gestión (como la ISO 9001)</td>
</tr>
<tr class="odd">
<td>Se aplica a</td>
<td>Un sistema de IA concreto</td>
<td>Toda la organización que desarrolla, provee o usa IA</td>
</tr>
<tr class="even">
<td>Se certifica</td>
<td>Es un modelo de referencia, no un sistema de gestión certificable</td>
<td>Sí, la certificación es voluntaria</td>
</tr>
<tr class="odd">
<td>Comité</td>
<td>ISO/IEC JTC 1/SC 42</td>
<td>ISO/IEC JTC 1/SC 42</td>
</tr>
</tbody>
</table>
<section id="isoiec-25059-un-modelo-de-calidad-para-sistemas-de-ia" class="level3">
<h3 class="anchored" data-anchor-id="isoiec-25059-un-modelo-de-calidad-para-sistemas-de-ia">ISO/IEC 25059: un modelo de calidad para sistemas de IA</h3>
<p>La ISO/IEC 25059:2023, edición 1, tiene 15 páginas. Su resumen la describe como una extensión de SQuaRE específica para sistemas de IA, con características y subcaracterísticas que dan terminología consistente para especificar, medir y evaluar su calidad, y un conjunto contra el cual comparar si los requisitos están completos.</p>
<p>Según el portal iso25000.com, una fuente secundaria mantenida por una red académica, el modelo agrega subcaracterísticas a las del modelo base. Agrega adaptabilidad funcional (usar lo aprendido en predicciones futuras) a la adecuación funcional, controlabilidad por el usuario y transparencia a la interacción, robustez a la fiabilidad e intervenibilidad a la seguridad. Advierte además que los métodos de aprendizaje automático muchas veces no dan corrección funcional en todas las circunstancias observadas, así que hay que medir con cuidado la corrección y la incorrección.</p>
<p>Dos advertencias de vigencia. La ficha de ISO muestra que la norma está “por revisar” y que se espera que la reemplace en los próximos meses un texto en etapa de proyecto final (FDIS). Y la edición de 2023 se publicó antes que la ISO/IEC 25010:2023, de modo que la alineación exacta entre ambas, y los nombres de las subcaracterísticas en la nueva edición, no se verificaron en fuente primaria.</p>
</section>
<section id="isoiec-42001-un-sistema-de-gestión-para-ia" class="level3">
<h3 class="anchored" data-anchor-id="isoiec-42001-un-sistema-de-gestión-para-ia">ISO/IEC 42001: un sistema de gestión para IA</h3>
<p>La ISO/IEC 42001:2023, <em>Information technology, Artificial intelligence, Management system</em>, es la primera norma internacional de sistemas de gestión de IA. Edición 1, publicada en diciembre de 2023, tiene 51 páginas. Especifica requisitos para establecer, implantar, mantener y mejorar de forma continua un sistema de gestión de IA, para organizaciones que desarrollan, proveen o usan productos o servicios basados en IA.</p>
<p>La página de ISO sobre la norma resume sus requisitos en siete temas.</p>
<ul>
<li>Liderazgo y contexto de la organización.</li>
<li>Política y objetivos de IA.</li>
<li>Gestión de riesgos de los sistemas de IA.</li>
<li>Gobierno de datos y controles del ciclo de vida del sistema.</li>
<li>Transparencia e información a las partes interesadas.</li>
<li>Evaluación del desempeño y seguimiento.</li>
<li>Mejora continua.</li>
</ul>
<p>Tres aclaraciones que ISO hace explícitas. La certificación es voluntaria. La hacen organismos independientes y no ISO. Y la norma no sustituye leyes ni reglamentos, sino que da un marco de gestión que ayuda a cumplir las obligaciones. Si una organización ya conoce la ISO 9001, reconocerá la lógica (contexto, liderazgo, planificación, apoyo, operación, evaluación, mejora). La 42001 agrega los temas propios de la IA.</p>
</section>
<section id="cómo-se-combinan-en-la-clínica" class="level3">
<h3 class="anchored" data-anchor-id="cómo-se-combinan-en-la-clínica">Cómo se combinan en la clínica</h3>
<p>Si la clínica agrega a su app un asistente que sugiere la especialidad según los síntomas del paciente, cada norma aporta algo distinto. El Reto 6 lo trabaja.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 6. Un asistente de IA en la app de turnos
</div>
</div>
<div class="callout-body-container callout-body">
<p>El asistente sugiere la especialidad según el texto que escribe el paciente. Para cada afirmación, escribe la norma que mejor la atiende (25010, 25012, 25059, 42001 o 9001) y por qué.</p>
<ol type="1">
<li>Medir qué proporción de sugerencias es correcta en 200 casos de prueba, incluidos textos con errores de digitación.</li>
<li>Decidir quién en la clínica responde por los riesgos del asistente y cómo se revisan.</li>
<li>Comprobar que los textos con los que se entrenó el asistente están completos y no se contradicen.</li>
<li>Mostrar a un cliente corporativo evidencia de que la clínica gestiona su calidad de forma sistemática.</li>
<li>Definir que el paciente pueda corregir o ignorar fácilmente una sugerencia.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>ISO/IEC 25059. La proporción de sugerencias correctas es una medida de corrección funcional, y los textos con errores de digitación prueban la robustez, ambas características que la extensión de IA destaca.</li>
<li>ISO/IEC 42001. Define liderazgo, responsabilidades, gestión de riesgos y evaluación periódica del uso de IA en la organización.</li>
<li>ISO/IEC 25012 (y las medidas de la 25024), porque se trata de completitud y consistencia de datos. Si los datos son para entrenar un modelo, la serie 5259 es el terreno específico.</li>
<li>ISO 9001, porque el certificado de un sistema de gestión de calidad es la evidencia que piden los clientes. Si la IA es parte relevante, la 42001 la complementa.</li>
<li>ISO/IEC 25059 (controlabilidad por el usuario) y, como atributo del producto, la capacidad de interacción de la ISO/IEC 25010:2023.</li>
</ol>
<p>Varias normas pueden aplicarse a la misma situación. Lo importante es distinguir si se evalúa el producto, los datos o la organización.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-9.-cómo-se-combinan-tabla-de-decisión" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="parte-9.-cómo-se-combinan-tabla-de-decisión"><span class="header-section-number">12</span> Parte 9. Cómo se combinan: tabla de decisión</h2>
<p>Antes de abrir una norma conviene saber qué pregunta se está haciendo. La tabla ayuda a elegir.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Si la pregunta es…</th>
<th>Mira primero</th>
<th>Y complementa con</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>¿Qué características debe tener el producto?</td>
<td>ISO/IEC 25010:2023</td>
<td>25030 para escribir requisitos</td>
</tr>
<tr class="even">
<td>¿Cómo mido una característica?</td>
<td>Serie 2502n (25020, 25023)</td>
<td>25021 para los elementos de medida</td>
</tr>
<tr class="odd">
<td>¿Cómo midió el usuario su experiencia?</td>
<td>ISO/IEC 25019 y 25022</td>
<td>Ver Tema 3 de esta unidad</td>
</tr>
<tr class="even">
<td>¿Están bien los datos?</td>
<td>ISO/IEC 25012 y 25024</td>
<td>Serie 5259 si son para aprendizaje automático</td>
</tr>
<tr class="odd">
<td>¿Cómo evalúo el producto de forma formal?</td>
<td>ISO/IEC 25040:2024</td>
<td>25010, 25023 y 25030</td>
</tr>
<tr class="even">
<td>¿La empresa gestiona bien su calidad?</td>
<td>ISO 9001:2026</td>
<td>ISO/IEC/IEEE 90003 como guía para software</td>
</tr>
<tr class="odd">
<td>¿Cómo audito el sistema de gestión?</td>
<td>ISO 19011:2026</td>
<td>ISO/IEC 17021-1 si se certifica</td>
</tr>
<tr class="even">
<td>¿Cómo evalúo la madurez de los procesos?</td>
<td>ISO/IEC 33000, CMMI</td>
<td>Tema 4 de esta unidad</td>
</tr>
<tr class="odd">
<td>¿Cómo se gobierna la IA en la organización?</td>
<td>ISO/IEC 42001</td>
<td>ISO/IEC 25059 para el sistema</td>
</tr>
</tbody>
</table>
</section>
<section id="errores-frecuentes" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="errores-frecuentes"><span class="header-section-number">13</span> Errores frecuentes</h2>
<ul>
<li><strong>Citar la ISO/IEC 25010:2011 como vigente.</strong> Está retirada. La vigente es la de 2023. Si un texto habla de cinco características de calidad en uso, es de la edición anterior.</li>
<li><strong>Pensar que SQuaRE es una sola norma.</strong> Es una serie de normas agrupadas en divisiones. Citar “la 25000” para hablar del modelo de producto es confundir la guía con el modelo.</li>
<li><strong>Esperar que la norma fije el umbral.</strong> Las normas de medición dan la forma de la medida y no el valor aceptable. Ese valor lo fija la organización con sus datos y riesgos.</li>
<li><strong>Confundir calidad de datos con calidad de producto.</strong> Un reporte con cifras distintas puede ser un defecto de datos (25012) y no de programa (25010). Diagnosticar mal manda al equipo a buscar en el lugar equivocado.</li>
<li><strong>Decir que la ISO 9001 certifica el producto.</strong> Certifica el sistema de gestión dentro de su alcance. Un producto concreto se evalúa con pruebas y con las normas de producto.</li>
<li><strong>Citar la ISO 9001:2015 como la edición vigente sin mencionar la transición.</strong> La edición vigente desde el 16 de septiembre de 2026 es la de 2026. Los certificados de 2015 siguen válidos durante el periodo de transición, que ISO fija en tres años.</li>
<li><strong>Creer que la ISO/IEC/IEEE 90003 se certifica.</strong> Es una guía de aplicación que no añade requisitos y no se usa como criterio de certificación por sí sola.</li>
<li><strong>Mezclar la 25059 con la 42001.</strong> Una es un modelo de calidad del producto de IA y la otra un sistema de gestión. Se complementan, pero no se reemplazan.</li>
<li><strong>Hacer del ciclo PHVA un trámite.</strong> Un PHVA sin meta medible ni registro de la verificación es un papel y no una mejora.</li>
</ul>
</section>
<section id="autoevaluación" class="level2" data-number="14">
<h2 data-number="14" class="anchored" data-anchor-id="autoevaluación"><span class="header-section-number">14</span> Autoevaluación</h2>
<p>Responde sin mirar la guía. Marca tu opción y abre la clave para comprobarla. Es una práctica formativa y no tiene nota.</p>
<p><strong>1.</strong> ¿En qué división de SQuaRE está la ISO/IEC 25040:2024?</p>
<p><label><input type="checkbox"> 2501n, modelos de calidad</label><br> <label><input type="checkbox"> 2504n, evaluación de la calidad</label><br> <label><input type="checkbox"> 2502n, medición de la calidad</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. La 25040 es el marco de evaluación, y la división 2504n agrupa las normas de evaluación. La 2501n es de modelos y la 2502n de medición.</p>
</div>
</div>
</div>
<p><strong>2.</strong> ¿Cuál de estas características de la ISO/IEC 25012 pertenece solo al grupo de las dependientes del sistema?</p>
<p><label><input type="checkbox"> Completitud</label><br> <label><input type="checkbox"> Trazabilidad</label><br> <label><input type="checkbox"> Recuperabilidad</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 3. Disponibilidad, portabilidad y recuperabilidad son las tres que solo dependen del sistema. La completitud es inherente y la trazabilidad es de ambos tipos.</p>
</div>
</div>
</div>
<p><strong>3.</strong> En 400 registros, 380 tienen correo electrónico. ¿Cuánto vale la medida de completitud con el patrón X = A / B?</p>
<p><label><input type="checkbox"> 0,05</label><br> <label><input type="checkbox"> 0,95</label><br> <label><input type="checkbox"> 1,05</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. 380 / 400 = 0,95. Una razón entre un subconjunto y el total no puede pasar de 1, así que 1,05 no es posible, y 0,05 es la proporción que falta.</p>
</div>
</div>
</div>
<p><strong>4.</strong> ¿Qué dicen las normas 25022, 25023 y 25024 sobre los valores aceptables de sus medidas?</p>
<p><label><input type="checkbox"> Fijan un umbral obligatorio para cada medida</label><br> <label><input type="checkbox"> No fijan rangos, porque dependen del sistema y de las necesidades de los usuarios</label><br> <label><input type="checkbox"> Los fija el organismo de certificación</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Los resúmenes oficiales dicen que los valores se definen para cada sistema según su naturaleza, su contexto y sus usuarios. La organización pone el umbral.</p>
</div>
</div>
</div>
<p><strong>5.</strong> A octubre de 2026, ¿cuál es la edición vigente de la ISO 9001 y qué ocurre con los certificados de 2015?</p>
<p><label><input type="checkbox"> La de 2015, y los certificados no cambian</label><br> <label><input type="checkbox"> La de 2026 (sexta edición), y los certificados de 2015 tienen tres años para pasar a ella</label><br> <label><input type="checkbox"> La de 2026, y los certificados de 2015 caducan de inmediato</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. ISO publicó la ISO 9001:2026 el 16 de septiembre de 2026 y dio tres años de transición a las organizaciones certificadas en 2015, sin tener que empezar de nuevo.</p>
</div>
</div>
</div>
<p><strong>6.</strong> ¿Cuál de estos es un cambio de la ISO 9001:2026 que ISO destaca en su página oficial?</p>
<p><label><input type="checkbox"> Cambió el número de cláusulas auditables de siete a diez</label><br> <label><input type="checkbox"> Distingue con más claridad los riesgos de las oportunidades</label><br> <label><input type="checkbox"> Eliminó el enfoque de procesos</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. ISO resalta además la cultura de calidad y el comportamiento ético y un Anexo A nuevo. La estructura de cláusulas no cambió, y el enfoque de procesos se mantiene.</p>
</div>
</div>
</div>
<p><strong>7.</strong> En el ciclo PHVA, comparar los reclamos del mes con la meta fijada corresponde a:</p>
<p><label><input type="checkbox"> Planificar</label><br> <label><input type="checkbox"> Verificar</label><br> <label><input type="checkbox"> Actuar</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Verificar mide y compara lo ocurrido contra lo planificado. Actuar es lo que se decide después, como extender el cambio o corregir.</p>
</div>
</div>
</div>
<p><strong>8.</strong> Una clínica con certificado ISO 9001 afirma que su app no tiene errores. ¿Qué se le responde?</p>
<p><label><input type="checkbox"> Tiene razón: el certificado garantiza la ausencia de errores</label><br> <label><input type="checkbox"> El certificado acredita que su sistema de gestión cumple la norma, no que cada producto esté libre de errores</label><br> <label><input type="checkbox"> El certificado solo prueba que pagó la auditoría</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. La certificación recae sobre el sistema de gestión y su alcance. La ausencia de errores se evalúa con pruebas y medidas del producto.</p>
</div>
</div>
</div>
<p><strong>9.</strong> ¿Cuál afirmación sobre la ISO/IEC/IEEE 90003:2018 es correcta?</p>
<p><label><input type="checkbox"> Añade requisitos a la ISO 9001 para el software y se certifica por separado</label><br> <label><input type="checkbox"> Da guías para aplicar la ISO 9001:2015 al software, sin añadir requisitos</label><br> <label><input type="checkbox"> Reemplaza a la ISO 9001 en las empresas de software</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Su resumen oficial dice que no añade ni cambia los requisitos de la ISO 9001 y que no está pensada como criterio de certificación.</p>
</div>
</div>
</div>
<p><strong>10.</strong> ¿Cuál es la diferencia principal entre la ISO/IEC 25059 y la ISO/IEC 42001?</p>
<p><label><input type="checkbox"> La 25059 es un modelo de calidad de un sistema de IA y la 42001 un sistema de gestión de IA para la organización</label><br> <label><input type="checkbox"> La 25059 es para empresas grandes y la 42001 para pequeñas</label><br> <label><input type="checkbox"> Son la misma norma publicada por dos comités</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 10
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. La 25059 extiende SQuaRE al producto de IA, y la 42001 especifica requisitos de un sistema de gestión, de la misma familia de la ISO 9001. Ambas las publica el comité ISO/IEC JTC 1/SC 42 y se complementan.</p>
</div>
</div>
</div>
</section>
<section id="lo-que-te-llevas" class="level2" data-number="15">
<h2 data-number="15" class="anchored" data-anchor-id="lo-que-te-llevas"><span class="header-section-number">15</span> Lo que te llevas</h2>
<div class="checklist">
<p>Al salir de este tema deberías poder explicar, sin mirar la guía</p>
<ul class="task-list">
<li><label><input type="checkbox">Las divisiones de la serie SQuaRE, qué pregunta responde cada una y cuál es la edición vigente de sus normas principales</label></li>
<li><label><input type="checkbox">Las quince características de la ISO/IEC 25012, su agrupación en tres bloques y por qué los datos se evalúan aparte del producto</label></li>
<li><label><input type="checkbox">Cómo se construye y se lee una medida con el patrón X = A / B y por qué el umbral lo fija la organización</label></li>
<li><label><input type="checkbox">Qué exige la ISO 9001, qué cambió con la edición de 2026, cuándo vence la transición y qué dice cada fuente</label></li>
<li><label><input type="checkbox">El ciclo PHVA y la gestión de riesgos y oportunidades con un ejemplo propio</label></li>
<li><label><input type="checkbox">El recorrido de una auditoría de certificación y qué demuestra y qué no demuestra el certificado</label></li>
<li><label><input type="checkbox">Para qué sirve la ISO/IEC/IEEE 90003 y por qué no se certifica</label></li>
<li><label><input type="checkbox">La diferencia entre la ISO/IEC 25059 y la ISO/IEC 42001</label></li>
</ul>
</div>
</section>
<section id="glosario" class="level2" data-number="16">
<h2 data-number="16" class="anchored" data-anchor-id="glosario"><span class="header-section-number">16</span> Glosario</h2>
<ul>
<li><strong>ISO.</strong> Organización Internacional de Normalización, que publica normas por consenso entre organismos nacionales.</li>
<li><strong>IEC.</strong> Comisión Electrotécnica Internacional, que publica junto con ISO las normas ISO/IEC.</li>
<li><strong>SQuaRE.</strong> <em>Systems and software Quality Requirements and Evaluation</em>, la serie ISO/IEC 25000 a 25099 sobre requisitos y evaluación de la calidad.</li>
<li><strong>División (de SQuaRE).</strong> Grupo de normas con una misma función: gestión (2500n), modelos (2501n), medición (2502n), requisitos (2503n), evaluación (2504n) y extensiones (25050 a 25099).</li>
<li><strong>Modelo de calidad.</strong> Conjunto de características y subcaracterísticas que sirve de referencia para especificar, medir y evaluar la calidad.</li>
<li><strong>Calidad en uso.</strong> Efecto del uso del sistema sobre quienes lo usan en un contexto de uso específico, que describe la ISO/IEC 25019.</li>
<li><strong>Elemento de medida de calidad (QME).</strong> Medida definida por una propiedad y su método de medición, que sirve de base para construir medidas de calidad.</li>
<li><strong>Medida de calidad.</strong> Función matemática de uno o más elementos de medida que cuantifica una característica, como X = A / B.</li>
<li><strong>Umbral.</strong> Valor que fija la organización para decidir si una medida es aceptable. Las normas de medición no lo fijan.</li>
<li><strong>Dato inherente.</strong> Característica de calidad que se refiere al dato mismo, a sus valores, relaciones y metadatos.</li>
<li><strong>Dato dependiente del sistema.</strong> Característica de calidad que logran o conservan los componentes de la plataforma, como respaldos o migración.</li>
<li><strong>Exactitud sintáctica y semántica.</strong> Cercanía de los valores a un dominio formalmente válido y a un dominio con significado correcto, respectivamente.</li>
<li><strong>Vigencia (<em>currentness</em>).</strong> Grado en que el dato tiene la edad adecuada para el uso.</li>
<li><strong>Sistema de gestión de la calidad (SGC).</strong> Conjunto de políticas, procesos y recursos con que una organización gestiona la calidad.</li>
<li><strong>ISO 9001.</strong> Norma con los requisitos de un SGC, la única de la familia ISO 9000 contra la que se certifica.</li>
<li><strong>Estructura de Alto Nivel.</strong> Esquema común de cláusulas que comparten las normas ISO de sistemas de gestión, también llamada <em>Harmonized Structure</em>.</li>
<li><strong>Pensamiento basado en riesgos.</strong> Planificar y decidir considerando los riesgos y, desde la edición de 2026, las oportunidades por separado.</li>
<li><strong>PHVA (PDCA).</strong> Ciclo de planificar, hacer, verificar y actuar para la mejora continua.</li>
<li><strong>No conformidad.</strong> Incumplimiento de un requisito, detectado en una auditoría.</li>
<li><strong>Auditoría interna.</strong> Revisión del sistema por personas de la propia organización, independientes del proceso auditado.</li>
<li><strong>Revisión por la dirección.</strong> Examen periódico del sistema que hace la alta dirección para decidir acciones.</li>
<li><strong>Organismo de certificación.</strong> Entidad independiente que audita y emite el certificado de un sistema de gestión.</li>
<li><strong>Acreditación.</strong> Reconocimiento de que un organismo de certificación es competente. Lo da un organismo de acreditación.</li>
<li><strong>Global ACI.</strong> Cooperación mundial de acreditación que asumió las funciones del IAF y de ILAC.</li>
<li><strong>Transición.</strong> Periodo en que las organizaciones certificadas con una edición pasan a la nueva. Para la ISO 9001:2026 ISO lo fija en tres años.</li>
<li><strong>ISO/IEC/IEEE 90003.</strong> Guía para aplicar la ISO 9001 al software. No añade requisitos y no se certifica por sí sola.</li>
<li><strong>ISO 19011.</strong> Directrices para auditar sistemas de gestión, con edición 2026.</li>
<li><strong>ISO/IEC 25059.</strong> Modelo de calidad para sistemas de inteligencia artificial, extensión de SQuaRE.</li>
<li><strong>ISO/IEC 42001.</strong> Norma de sistemas de gestión de inteligencia artificial, que se puede certificar de forma voluntaria.</li>
<li><strong>ISO/IEC 5259.</strong> Serie sobre calidad de datos para analítica y aprendizaje automático.</li>
<li><strong>Robustez.</strong> Capacidad de un sistema de IA de mantener su nivel de desempeño en distintas circunstancias.</li>
</ul>
</section>
<section id="bibliografía" class="level2" data-number="17">
<h2 data-number="17" class="anchored" data-anchor-id="bibliografía"><span class="header-section-number">17</span> Bibliografía</h2>
<p>Familia SQuaRE y calidad de datos. Todas las fichas son del catálogo de ISO, consultadas el 3 de octubre de 2026.</p>
<ul>
<li>ISO/IEC (2014). <em>ISO/IEC 25000:2014, Systems and software engineering, SQuaRE, Guide to SQuaRE.</em> Edición 2. <a href="https://www.iso.org/standard/64764.html">Ficha</a>.</li>
<li>ISO/IEC (2023). <em>ISO/IEC 25010:2023, Product quality model.</em> Edición 2. <a href="https://www.iso.org/standard/78176.html">Ficha</a>. Se consultó además la vista previa pública con el prólogo y la introducción.</li>
<li>ISO/IEC (2024). <em>ISO/IEC 25002:2024, Quality model overview and usage.</em> <a href="https://www.iso.org/standard/78175.html">Ficha</a>.</li>
<li>ISO/IEC (2023). <em>ISO/IEC 25019:2023, Quality-in-use model.</em> <a href="https://www.iso.org/standard/78177.html">Ficha</a>.</li>
<li>ISO/IEC (2008). <em>ISO/IEC 25012:2008, Data quality model.</em> <a href="https://www.iso.org/standard/35736.html">Ficha</a>.</li>
<li>ISO/IEC (2019). <em>ISO/IEC 25020:2019, Quality measurement framework.</em> <a href="https://www.iso.org/standard/72117.html">Ficha</a>.</li>
<li>ISO/IEC (2012). <em>ISO/IEC 25021:2012, Quality measure elements.</em> <a href="https://www.iso.org/standard/55477.html">Ficha</a>.</li>
<li>ISO/IEC (2016). <em>ISO/IEC 25022:2016, Measurement of quality in use.</em> <a href="https://www.iso.org/standard/35746.html">Ficha</a>.</li>
<li>ISO/IEC (2016). <em>ISO/IEC 25023:2016, Measurement of system and software product quality.</em> <a href="https://www.iso.org/standard/35747.html">Ficha</a>.</li>
<li>ISO/IEC (2015). <em>ISO/IEC 25024:2015, Measurement of data quality.</em> <a href="https://www.iso.org/standard/35749.html">Ficha</a>.</li>
<li>ISO/IEC (2019). <em>ISO/IEC 25030:2019, Quality requirements framework.</em> <a href="https://www.iso.org/standard/72116.html">Ficha</a>.</li>
<li>ISO/IEC (2024). <em>ISO/IEC 25040:2024, Quality evaluation framework.</em> Edición 2. <a href="https://www.iso.org/standard/83467.html">Ficha</a>.</li>
<li>ISO/IEC (2024). <em>ISO/IEC 5259-1 a 5259-4, Artificial intelligence, Data quality for analytics and machine learning.</em> <a href="https://www.iso.org/standard/81088.html">Parte 1</a>, <a href="https://www.iso.org/standard/81860.html">parte 2</a>, <a href="https://www.iso.org/standard/81092.html">parte 3</a>, <a href="https://www.iso.org/standard/81093.html">parte 4</a>.</li>
<li>Papastergios, V., Ehrlinger, L. y Gounaris, A. (2025). <em>Unfolding Data Quality Dimensions in Practice: A Survey.</em> <a href="https://arxiv.org/abs/2507.17507">arXiv:2507.17507</a>. Fuente secundaria de la tabla de definiciones de la ISO/IEC 25012.</li>
</ul>
<p>Gestión de la calidad y auditoría.</p>
<ul>
<li>ISO (16 de septiembre de 2026). <em>ISO launches update to world’s most widely used quality management standard for a new era of business.</em> Comunicado de prensa. <a href="https://www.iso.org/news/2026/09/ISO9001-2026">Enlace</a>.</li>
<li>ISO (2026). <em>ISO 9001:2026, Quality management systems, Requirements.</em> Edición 6. <a href="https://www.iso.org/standard/9001">Ficha</a>.</li>
<li>ISO (2026). <em>ISO 9001:2026, What businesses need to know.</em> <a href="https://www.iso.org/quality-management/iso-9001-2026">Página</a>.</li>
<li>ISO (2015). <em>ISO 9001:2015</em> y su <em>Enmienda 1:2024.</em> Fichas con estado retirado. <a href="https://www.iso.org/standard/62085.html">Ficha</a>.</li>
<li>ISO (2026). <em>ISO 9000:2026, Quality management, Fundamentals and vocabulary.</em> Edición 5. <a href="https://www.iso.org/standard/9000">Ficha</a>.</li>
<li>ISO (2026). <em>ISO 19011:2026, Guidelines for auditing management systems.</em> Edición 4. <a href="https://www.iso.org/standard/19011">Ficha</a>.</li>
<li>ISO/IEC (2015). <em>ISO/IEC 17021-1:2015, Requirements for bodies providing audit and certification of management systems.</em> <a href="https://www.iso.org/standard/61651.html">Ficha</a>.</li>
<li>ISO. <em>Certification.</em> Página sobre certificación y acreditación. <a href="https://www.iso.org/certification.html">Enlace</a>.</li>
<li>ISO/IEC/IEEE (2018). <em>ISO/IEC/IEEE 90003:2018, Guidelines for the application of ISO 9001:2015 to computer software.</em> <a href="https://www.iso.org/standard/74348.html">Ficha</a>.</li>
</ul>
<p>Inteligencia artificial.</p>
<ul>
<li>ISO/IEC (2023). <em>ISO/IEC 25059:2023, Quality model for AI systems.</em> <a href="https://www.iso.org/standard/80655.html">Ficha</a>. Descripción de las subcaracterísticas: <a href="https://iso25000.com/index.php/en/iso-25000-standards/iso-25059">iso25000.com</a>, fuente secundaria.</li>
<li>ISO/IEC (2023). <em>ISO/IEC 42001:2023, Artificial intelligence, Management system.</em> <a href="https://www.iso.org/standard/81230.html">Ficha</a>. Guía de ISO: <a href="https://www.iso.org/insights/iso-42001-explained">ISO/IEC 42001 explained</a>.</li>
</ul>
<p>Fuentes secundarias consultadas para el proceso de certificación y los cambios de detalle. No son fuente primaria.</p>
<ul>
<li>Wikipedia. <em>ISO 9001.</em> Resumen general del proceso de certificación. <a href="https://en.wikipedia.org/wiki/ISO_9001">Artículo</a>.</li>
<li>Certificadoras y consultoras (DQS, SGS, DNV, LRQA y otras) que describen cambios de cláusulas más finos y la fecha de septiembre de 2029. Sus datos se marcan en el texto como no verificados en fuente primaria.</li>
</ul>
<div class="pie-doc">
<p>Calidad del software (CDS01). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>