<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 2. El teléfono de Ana, resuelto en cuatro pasos – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-9d905b06f1e8b96cef5de7dac512495c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-03/index.html">Unidad 3. Modelo relacional</a></li><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-03/tema-02-formas-normalizacion/index.html">Tema 2. El teléfono de Ana, resuelto en cuatro pasos</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Introducción a los sistemas de bases de datos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-01/tema-01-datos-informacion-conocimiento/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Datos, información y el archivo que se queda corto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-01/tema-02-integracion-organizacional/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Una base de datos, toda la empresa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/actividad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Actividad 1. Profundicen la Unidad 1</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Modelo entidad relación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-02/tema-01-componentes-mer/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Las piezas con las que se dibuja la realidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-02/tema-02-representacion-cardinalidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. El dibujo que decide la llave foránea</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 3. Modelo relacional</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-03/tema-01-de-er-a-relacional/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Seis reglas para convertir el diagrama en tablas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-03/tema-02-formas-normalizacion/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 2. El teléfono de Ana, resuelto en cuatro pasos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-03/tema-03-diseno-tablas-integridad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. La tabla que vigila sus propias reglas, y las que se le escapan</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#la-jerarquía-que-vas-a-recorrer" id="toc-la-jerarquía-que-vas-a-recorrer" class="nav-link active" data-scroll-target="#la-jerarquía-que-vas-a-recorrer"><span class="header-section-number">1</span> La jerarquía que vas a recorrer</a></li>
  <li><a href="#las-tres-anomalías-otra-vez-con-la-tabla-completa-delante" id="toc-las-tres-anomalías-otra-vez-con-la-tabla-completa-delante" class="nav-link" data-scroll-target="#las-tres-anomalías-otra-vez-con-la-tabla-completa-delante"><span class="header-section-number">2</span> Las tres anomalías, otra vez, con la tabla completa delante</a></li>
  <li><a href="#qué-es-una-dependencia-funcional" id="toc-qué-es-una-dependencia-funcional" class="nav-link" data-scroll-target="#qué-es-una-dependencia-funcional"><span class="header-section-number">3</span> Qué es una dependencia funcional</a></li>
  <li><a href="#primera-forma-normal-valores-atómicos-y-una-llave-que-sea-de-verdad" id="toc-primera-forma-normal-valores-atómicos-y-una-llave-que-sea-de-verdad" class="nav-link" data-scroll-target="#primera-forma-normal-valores-atómicos-y-una-llave-que-sea-de-verdad"><span class="header-section-number">4</span> Primera forma normal: valores atómicos y una llave que sea de verdad</a></li>
  <li><a href="#segunda-forma-normal-nada-depende-de-una-parte-de-la-llave" id="toc-segunda-forma-normal-nada-depende-de-una-parte-de-la-llave" class="nav-link" data-scroll-target="#segunda-forma-normal-nada-depende-de-una-parte-de-la-llave"><span class="header-section-number">5</span> Segunda forma normal: nada depende de una parte de la llave</a></li>
  <li><a href="#tercera-forma-normal-nada-depende-de-un-atributo-que-no-es-la-llave" id="toc-tercera-forma-normal-nada-depende-de-un-atributo-que-no-es-la-llave" class="nav-link" data-scroll-target="#tercera-forma-normal-nada-depende-de-un-atributo-que-no-es-la-llave"><span class="header-section-number">6</span> Tercera forma normal: nada depende de un atributo que no es la llave</a></li>
  <li><a href="#cuarta-forma-normal-dos-hechos-independientes-no-comparten-tabla" id="toc-cuarta-forma-normal-dos-hechos-independientes-no-comparten-tabla" class="nav-link" data-scroll-target="#cuarta-forma-normal-dos-hechos-independientes-no-comparten-tabla"><span class="header-section-number">7</span> Cuarta forma normal: dos hechos independientes no comparten tabla</a></li>
  <li><a href="#qué-anomalía-corrige-cada-forma-normal" id="toc-qué-anomalía-corrige-cada-forma-normal" class="nav-link" data-scroll-target="#qué-anomalía-corrige-cada-forma-normal"><span class="header-section-number">8</span> Qué anomalía corrige cada forma normal</a></li>
  <li><a href="#lo-que-te-llevas-de-hoy" id="toc-lo-que-te-llevas-de-hoy" class="nav-link" data-scroll-target="#lo-que-te-llevas-de-hoy"><span class="header-section-number">9</span> Lo que te llevas de hoy</a></li>
  <li><a href="#lo-que-sigue" id="toc-lo-que-sigue" class="nav-link" data-scroll-target="#lo-que-sigue"><span class="header-section-number">10</span> Lo que sigue</a></li>
  <li><a href="#recursos" id="toc-recursos" class="nav-link" data-scroll-target="#recursos"><span class="header-section-number">11</span> Recursos</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-03/index.html">Unidad 3. Modelo relacional</a></li><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-03/tema-02-formas-normalizacion/index.html">Tema 2. El teléfono de Ana, resuelto en cuatro pasos</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 2. El teléfono de Ana, resuelto en cuatro pasos</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">21 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 3. Modelo relacional</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 2. Formas de normalización, de la primera a la cuarta</td>
</tr>
</tbody>
</table>
</div>
<p><a href="../../../base-de-datos/unidad-03/tema-02-formas-normalizacion/presentacion.html">Diapositivas de la sesión</a></p>
<p>El Tema 1 de esta unidad tomó el diagrama entidad-relación de la cafetería que armaste en la Unidad 2, ya bien pensado, con sus entidades separadas y su cardinalidad marcada, y lo tradujo al vocabulario de tablas del modelo relacional aplicando reglas de mapeo concretas, cada entidad se convierte en una tabla, cada relación se resuelve con una llave foránea o con una tabla propia. Ese procedimiento parte de un diagrama que ya está bien diseñado, así que el resultado hereda automáticamente esa calidad. Hoy el punto de partida es distinto y, en la práctica profesional, más frecuente, porque casi nunca vas a heredar un diagrama entidad-relación limpio recién dibujado, vas a heredar una tabla que alguien más ya construyó, con datos ya cargados adentro, la misma tabla plana de pedidos de la cafetería que abrió la Unidad 1, con el teléfono del cliente repetido en cada fila. Tu trabajo hoy es auditar esa tabla con un procedimiento formal en vez de con un diagrama, y ese procedimiento se llama normalización.</p>
<p>Mapear bien un modelo entidad-relación y normalizar una tabla plana pueden terminar en una estructura de tablas parecida, pero no son el mismo ejercicio. Mapear bien no garantiza por sí solo que el resultado cumpla las formas normales que vas a estudiar hoy, porque las reglas de mapeo resuelven cardinalidad y participación, no dependencias funcionales entre atributos. Y normalizar una tabla plana no exige haber dibujado antes ningún diagrama, porque el procedimiento trabaja directo sobre las columnas y las filas que ya existen. Las dos rutas conviven en este curso porque en la vida profesional te vas a encontrar con las dos situaciones, un negocio nuevo que se puede modelar desde cero y un negocio con años de datos sueltos que hay que ordenar.</p>
<p>El tema cierra con la cuarta forma normal, que corrige un tipo de redundancia distinto al que arreglan las tres primeras, y con un mapa completo de qué anomalía corrige cada forma. El Tema 3, el último de esta unidad, toma las tablas que vas a terminar de construir hoy y les asigna tipos de dato, llaves y restricciones concretas.</p>
<section id="la-jerarquía-que-vas-a-recorrer" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="la-jerarquía-que-vas-a-recorrer"><span class="header-section-number">1</span> La jerarquía que vas a recorrer</h2>
<p>Cada forma normal que viene a continuación es más exigente que la anterior, y cumplir la más exigente obliga a cumplir todas las que están debajo. La 2FN exige primero cumplir la 1FN, la 3FN exige primero cumplir la 2FN, y así sucesivamente, lo que convierte la normalización en un procedimiento de pasos acumulados, no en cuatro reglas sueltas que se puedan aplicar en cualquier orden.</p>
<div class="diagrama">
<svg viewbox="0 0 760 320" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cuatro rectángulos anidados que representan la jerarquía de las formas normales, el más grande es primera forma normal y contiene a segunda forma normal, que contiene a tercera forma normal, que contiene a cuarta forma normal en el centro, cada anillo visible lleva la etiqueta de la forma normal correspondiente y la anomalía que corrige" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Cada forma normal exige cumplir primero todas las anteriores</text> <rect x="20" y="34" width="720" height="266" rx="14" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="380" y="56" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">1FN. valores atómicos y una llave real</text> <text x="380" y="72" font-size="10.5" fill="#5b6876" text-anchor="middle">evita que varios hechos se compriman en una sola fila o una sola columna</text> <rect x="60" y="86" width="640" height="200" rx="12" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="380" y="108" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">2FN. nada depende de una parte de la llave</text> <text x="380" y="124" font-size="10.5" fill="#5b6876" text-anchor="middle">corrige la redundancia de un atributo que solo depende de una parte de una llave compuesta</text> <rect x="100" y="138" width="560" height="132" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="160" font-size="13" font-weight="700" fill="#0e6f6c" text-anchor="middle">3FN. nada depende de un atributo que no es la llave</text> <text x="380" y="176" font-size="10.5" fill="#3c7d7a" text-anchor="middle">corrige las tres anomalías clásicas: inserción, actualización y borrado</text> <rect x="150" y="192" width="460" height="60" rx="9" fill="#cfe6e3" stroke="#6bb0ab"></rect> <text x="380" y="216" font-size="12.5" font-weight="700" fill="#0e4a48" text-anchor="middle">4FN. hechos independientes en tablas separadas</text> <text x="380" y="234" font-size="10.5" fill="#0e4a48" text-anchor="middle">corrige la redundancia de mezclar dos dependencias multivaluadas</text>
</svg>
</div>
<p>Con ese mapa en mente, el resto del tema recorre las cuatro formas en orden, y para las tres primeras el hilo conductor es siempre la misma tabla, la de los pedidos de la cafetería.</p>
</section>
<section id="las-tres-anomalías-otra-vez-con-la-tabla-completa-delante" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="las-tres-anomalías-otra-vez-con-la-tabla-completa-delante"><span class="header-section-number">2</span> Las tres anomalías, otra vez, con la tabla completa delante</h2>
<p>Esta es la misma tabla que abrió la Unidad 1, la que un empleado de la cafetería armó juntando pedido, cliente, teléfono, producto y valor en una sola fila por línea de venta.</p>
<div class="tabla-ancha">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Pedido</th>
<th>Cliente</th>
<th>Teléfono</th>
<th>Producto</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1001</td>
<td>Ana Ruiz</td>
<td>300 111 2233</td>
<td>Café</td>
<td>4500</td>
</tr>
<tr class="even">
<td>1002</td>
<td>Ana Ruiz</td>
<td>300 111 2233</td>
<td>Torta</td>
<td>23400</td>
</tr>
<tr class="odd">
<td>1003</td>
<td>Luis Pena</td>
<td>301 444 5566</td>
<td>Café</td>
<td>4500</td>
</tr>
<tr class="even">
<td>1004</td>
<td>Ana Ruiz</td>
<td>300 111 2233</td>
<td>Jugo</td>
<td>6800</td>
</tr>
</tbody>
</table>
</div>
<p>Ya viste en la Unidad 1 que esta tabla falla de tres formas concretas, y hoy conviene repasarlas con la vista puesta en la causa, no solo en el síntoma, porque esa causa es la que las formas normales van a corregir una por una a lo largo del tema.</p>
<p>La primera falla aparece si Ana cambia de teléfono. Su número actual, 300 111 2233, está escrito tres veces, en las filas 1001, 1002 y 1004, porque Ana hizo tres pedidos distintos. Corregir el número exige tocar las tres filas, y si alguien corrige dos y olvida la tercera, la tabla termina con dos números de teléfono distintos para la misma persona, sin que ninguna regla dentro de la tabla avise de esa contradicción. Ese es el nombre técnico completo de lo que en la Unidad 1 se presentó de forma intuitiva, la <em>anomalía de actualización</em>, y ocurre porque el mismo dato, el teléfono de Ana, vive repetido en varias filas en vez de vivir una sola vez en un solo lugar.</p>
<p>La segunda falla aparece si la cafetería quiere registrar a un cliente nuevo que todavía no ha hecho ningún pedido, alguien que se acaba de inscribir al programa de fidelización, por ejemplo. La tabla no tiene ninguna fila donde quepa solo un nombre y un teléfono, porque cada fila exige también un número de pedido, un producto y un valor. Ese cliente se queda sin registrar hasta que compre algo, aunque ya sea un cliente real desde el momento en que se inscribió. Esa es la <em>anomalía de inserción</em>, y ocurre porque la tabla obliga a que dos hechos independientes, que exista un cliente y que exista un pedido, aparezcan siempre juntos en la misma fila.</p>
<p>La tercera falla aparece si se anula el pedido 1003 y se borra esa fila. Luis Pena solo aparece ahí, así que borrar su único pedido borra también el único registro de que Luis Pena es cliente de la cafetería, con todo y su teléfono, aunque el pedido y el cliente sean conceptualmente dos cosas distintas. Esa es la <em>anomalía de borrado</em>, y ocurre por la misma razón que la de inserción, dos hechos independientes atados a la misma fila, de modo que borrar uno arrastra al otro.</p>
<p>Las tres anomalías comparten una causa común, que un solo atributo, el teléfono de Ana o los datos de contacto de Luis, termina mezclado en una fila que en realidad debería contener otra cosa, un pedido. El resto del tema formaliza esa intuición con un concepto preciso, el de dependencia funcional, y usa ese concepto para decidir, paso a paso, qué atributo pertenece a qué tabla.</p>
</section>
<section id="qué-es-una-dependencia-funcional" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="qué-es-una-dependencia-funcional"><span class="header-section-number">3</span> Qué es una dependencia funcional</h2>
<p>Una <em>dependencia funcional</em> es una regla de negocio que dice que el valor de un atributo, o de un conjunto de atributos, determina de forma única el valor de otro. Silberschatz, Korth y Sudarshan lo formalizan así en <em>Database System Concepts</em>, dado un esquema de relación con atributos X y Y, se dice que X determina funcionalmente a Y, o que Y depende funcionalmente de X, si para dos filas cualesquiera de la tabla que tengan el mismo valor de X, esas dos filas también tienen que tener el mismo valor de Y. Elmasri y Navathe llegan a la misma idea con otra frase en <em>Fundamentals of Database Systems</em>, la dependencia funcional es una restricción entre dos conjuntos de atributos que se deriva del significado y de la interrelación real de los datos, no de la casualidad con que esos datos aparecen en un momento dado.</p>
<p>Esa última precisión importa porque separa dos cosas que se confunden con facilidad, una regla de negocio verdadera y una coincidencia que solo se cumple en los datos que tienes delante en este momento. Antes de listar las dependencias de la tabla de pedidos conviene verlas dibujadas, porque el mapa completo deja claro de un vistazo cuáles atributos dependen de cuáles.</p>
<div class="diagrama">
<svg viewbox="0 0 760 320" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Mapa de dependencias funcionales de la tabla de pedidos: la llave primaria compuesta por Pedido y Producto determina a Cliente y a Valor respectivamente, y Cliente determina además a Teléfono, lo que crea una dependencia transitiva de Pedido hacia Teléfono" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="dba3t2a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Cada atributo depende de una parte distinta de la llave compuesta</text> <rect x="50" y="30" width="650" height="86" rx="10" fill="none" stroke="#cfd8e3" stroke-dasharray="4 4"></rect> <text x="375" y="46" font-size="12" font-weight="600" fill="#5b6876" text-anchor="middle">llave primaria: (Pedido, Producto)</text> <rect x="70" y="54" width="160" height="50" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="150" y="84" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Pedido</text> <rect x="500" y="54" width="160" height="50" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="580" y="84" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Producto</text> <path d="M150,104 L150,160" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#dba3t2a)"></path> <path d="M580,104 L580,160" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#dba3t2a)"></path> <rect x="70" y="162" width="160" height="50" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="150" y="192" font-size="13.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Cliente</text> <rect x="500" y="162" width="160" height="50" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="580" y="192" font-size="13.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Valor</text> <text x="260" y="140" font-size="11" fill="#5b6876" text-anchor="middle">Pedido determina Cliente</text> <text x="660" y="140" font-size="11" fill="#5b6876" text-anchor="middle">Producto determina Valor</text> <path d="M150,212 L150,258" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#dba3t2a)"></path> <rect x="60" y="260" width="180" height="50" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="150" y="290" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Teléfono</text> <text x="380" y="300" font-size="11" fill="#5b6876" text-anchor="middle">Cliente determina Teléfono; por transitividad, Pedido también lo determina</text>
</svg>
</div>
<p>Escritas en prosa, las dependencias funcionales de la tabla de pedidos son estas cuatro. Un <code>Pedido</code> determina a <code>Cliente</code>, porque cada pedido pertenece a un único cliente, nunca a dos a la vez. Un <code>Cliente</code> determina a <code>Teléfono</code>, porque la cafetería guarda un solo número de contacto por cliente. Un <code>Producto</code> determina a <code>Valor</code>, porque el precio de un producto en el catálogo no cambia de un pedido a otro. Y por una propiedad de las dependencias funcionales llamada transitividad, si <code>Pedido</code> determina a <code>Cliente</code> y <code>Cliente</code> determina a <code>Teléfono</code>, entonces <code>Pedido</code> también determina a <code>Teléfono</code>, aunque esa dependencia sea indirecta y pase por <code>Cliente</code> en el camino. Esa última dependencia, indirecta, es justo la que va a resolver la tercera forma normal más adelante.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Regla de negocio o coincidencia
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para cada afirmación, marca si te parece una dependencia funcional real, una regla que la cafetería sostendría siempre, o si te parece que solo coincide con los cuatro pedidos de la tabla de arriba, sin que sea una regla garantizada.</p>
<p><label><input type="checkbox"> <code>Pedido</code> determina a <code>Cliente</code></label><br> <label><input type="checkbox"> <code>Cliente</code> determina a <code>Teléfono</code></label><br> <label><input type="checkbox"> <code>Teléfono</code> determina a <code>Cliente</code></label><br> <label><input type="checkbox"> <code>Producto</code> determina a <code>Valor</code></label><br> <label><input type="checkbox"> <code>Valor</code> determina a <code>Producto</code></label><br> <label><input type="checkbox"> <code>Cliente</code> determina a <code>Pedido</code></label></p>
<p>Para las que consideres coincidencia, describe en una frase una situación futura, sin cambiar la tabla de columnas, en la que esa afirmación dejaría de cumplirse.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>Pedido</code> determina a <code>Cliente</code> es una dependencia funcional real, porque un pedido siempre pertenece a un único cliente, esa es una regla del negocio y no una coincidencia de esta muestra de datos.</p>
<p><code>Cliente</code> determina a <code>Teléfono</code> también es real, en la medida en que la cafetería decide guardar un solo número de contacto por cliente, así que mientras esa política se mantenga, esta dependencia se sostiene.</p>
<p><code>Teléfono</code> determina a <code>Cliente</code> es una coincidencia, no una regla. En esta muestra cada número de teléfono aparece asociado a un único cliente, pero nada impide que dos clientes distintos compartan un mismo número, por ejemplo una pareja que registra el teléfono de la casa para los dos, así que esta dependencia se rompería el día que eso ocurra.</p>
<p><code>Producto</code> determina a <code>Valor</code> es real si se asume que el precio del producto viene de un catálogo fijo y no cambia de un pedido a otro, que es la lectura más razonable de esta tabla.</p>
<p><code>Valor</code> determina a <code>Producto</code> es una coincidencia. En esta muestra cada valor corresponde a un producto distinto, café y torta y jugo cuestan cifras distintas, pero nada impide que dos productos distintos cuesten lo mismo, por ejemplo si la cafetería agrega una galleta que también cueste 4500, el mismo valor del café.</p>
<p><code>Cliente</code> determina a <code>Pedido</code> es falso incluso dentro de esta misma muestra, porque Ana Ruiz ya aparece asociada a tres pedidos distintos, el 1001, el 1002 y el 1004, así que un mismo valor de <code>Cliente</code> no determina un único valor de <code>Pedido</code>.</p>
</div>
</div>
</div>
</section>
<section id="primera-forma-normal-valores-atómicos-y-una-llave-que-sea-de-verdad" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="primera-forma-normal-valores-atómicos-y-una-llave-que-sea-de-verdad"><span class="header-section-number">4</span> Primera forma normal: valores atómicos y una llave que sea de verdad</h2>
<p>La <em>primera forma normal</em>, o 1FN, exige dos cosas a la vez, según la formalización de Codd retomada por Elmasri y Navathe, que cada atributo contenga solo valores atómicos, es decir un único dato por celda y no una lista ni un grupo repetido, y que la tabla tenga definida una llave primaria capaz de identificar cada fila sin ambigüedad. La tabla de pedidos cumple la primera condición sin ningún cambio, cada celda guarda un único valor, ningún cliente aparece con dos teléfonos en la misma celda ni ningún pedido aparece con una lista de productos separados por comas. El trabajo real de esta sección está en la segunda condición, encontrar la llave primaria correcta.</p>
<p>A primera vista, el atributo <code>Pedido</code> parece suficiente como llave, porque en esta muestra de cuatro filas cada número de pedido aparece una sola vez. Pero nada en el diseño de la tabla garantiza eso. Ya viste en la Unidad 2, en el Reto 2 de aquel tema, qué pasaría si el pedido 1002 de Ana hubiera incluido a la vez una torta y un jugo, con una tabla como esta, sin una columna que solo admita un producto por fila, la única forma de registrar los dos productos es repetir la fila completa del pedido 1002 dos veces, una por cada producto, cambiando solo <code>Producto</code> y <code>Valor</code>. Ese mismo caso hipotético revela algo sobre la llave de esta tabla, si dos filas pueden compartir el mismo número de pedido, <code>Pedido</code> por sí solo no alcanza para identificar una fila sin ambigüedad.</p>
<div class="diagrama">
<svg viewbox="0 0 760 280" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Dos filas hipotéticas con el mismo número de pedido, 1002, pero productos distintos, torta y jugo, el pedido se repite idéntico en las dos filas mientras que el producto cambia, lo que muestra que Pedido por sí solo no es una llave candidata y hace falta agregar Producto" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Nada impide que un mismo pedido incluya más de un producto</text> <rect x="200" y="40" width="360" height="52" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="380" y="62" font-size="13" font-weight="700" fill="#0e6f6c" text-anchor="middle">Pedido = 1002</text> <text x="380" y="80" font-size="12" fill="#5b6876" text-anchor="middle">Producto = Torta</text> <rect x="200" y="102" width="360" height="52" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="380" y="124" font-size="13" font-weight="700" fill="#0e6f6c" text-anchor="middle">Pedido = 1002</text> <text x="380" y="142" font-size="12" fill="#5b6876" text-anchor="middle">Producto = Jugo</text> <text x="380" y="180" font-size="11.5" fill="#5b6876" text-anchor="middle">Dos filas con el mismo Pedido, pero un Producto distinto: Pedido por sí solo no es candidata a llave</text> <rect x="220" y="200" width="320" height="46" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="228" font-size="13" font-weight="700" fill="#0e6f6c" text-anchor="middle">llave candidata real: (Pedido, Producto)</text>
</svg>
</div>
<p>La llave primaria correcta de la tabla plana, entonces, es la combinación de <code>Pedido</code> y <code>Producto</code>, no <code>Pedido</code> solo. Con esa combinación como llave, la tabla ya cumple la 1FN completa, valores atómicos y una llave que identifica cada fila sin ambigüedad, aunque en la muestra concreta de cuatro filas cada pedido siga apareciendo una sola vez. La llave compuesta es la que hace posible, en las dos secciones siguientes, hablar con precisión de qué atributo depende de qué parte de esa llave.</p>
</section>
<section id="segunda-forma-normal-nada-depende-de-una-parte-de-la-llave" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="segunda-forma-normal-nada-depende-de-una-parte-de-la-llave"><span class="header-section-number">5</span> Segunda forma normal: nada depende de una parte de la llave</h2>
<p>La <em>segunda forma normal</em>, o 2FN, exige que la tabla ya esté en 1FN y que, además, ningún atributo que no forme parte de la llave dependa de solo una parte de una llave compuesta, tiene que depender de la llave completa. Codd definió esta forma en 1971, en el artículo <em>Further Normalization of the Data Base Relational Model</em>, con el objetivo explícito de que la colección de tablas resultante fuera más fácil de entender y de mantener. Cuando un atributo depende de una parte de la llave nada más, se dice que tiene una <em>dependencia parcial</em>, y esa dependencia parcial es justo el problema que la 2FN corrige.</p>
<p>Con la llave <code>(Pedido, Producto)</code> ya establecida, toca revisar cada atributo que no es llave, que son <code>Cliente</code>, <code>Teléfono</code> y <code>Valor</code>, y preguntar de qué parte de la llave depende cada uno. <code>Cliente</code> depende solo de <code>Pedido</code>, no de <code>Producto</code>, porque el cliente de un pedido no cambia según qué producto se esté mirando. <code>Teléfono</code> depende también solo de <code>Pedido</code>, por la misma razón, y de forma transitiva por <code>Cliente</code>, como ya viste en el mapa de dependencias. <code>Valor</code> depende solo de <code>Producto</code>, no de <code>Pedido</code>, porque el precio de un producto es el mismo sin importar en cuál pedido aparezca, el café cuesta 4500 tanto en el pedido 1001 como en el 1003. Ningún atributo de la tabla depende de la llave completa <code>(Pedido, Producto)</code> a la vez, así que los tres violan la 2FN.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Encuentra la dependencia parcial
</div>
</div>
<div class="callout-body-container callout-body">
<p>Antes de seguir leyendo, revisa la tabla de pedidos ya con la llave <code>(Pedido, Producto)</code> en mente y responde en un párrafo corto. De los tres atributos que no son llave, <code>Cliente</code>, <code>Teléfono</code> y <code>Valor</code>, cuáles dependen de todo <code>Pedido</code> junto con todo <code>Producto</code> a la vez, y cuáles dependen de uno solo de los dos. Si el pedido 1002 de Ana incluyera también un jugo, además de la torta, qué valor tendría que repetirse en la nueva fila, y por qué eso es justo la definición de una dependencia parcial.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Ninguno de los tres atributos depende de <code>Pedido</code> y <code>Producto</code> juntos, los tres dependen de uno solo de los dos. <code>Cliente</code> y <code>Teléfono</code> dependen únicamente de <code>Pedido</code>, mientras que <code>Valor</code> depende únicamente de <code>Producto</code>.</p>
<p>Si el pedido 1002 de Ana incluyera también un jugo, la nueva fila repetiría el nombre de Ana y su teléfono, exactamente igual que en la fila de la torta, porque esos dos datos no tienen nada que ver con qué producto se está registrando en esa fila puntual, dependen solo del pedido. Esa repetición del mismo valor cada vez que cambia la parte de la llave que no lo determina es exactamente la dependencia parcial que corrige la 2FN, el atributo no necesita las dos partes de la llave para quedar determinado, le sobra una.</p>
</div>
</div>
</div>
<p>Corregir la dependencia parcial exige separar la tabla en tres, agrupando cada atributo con la parte de la llave de la que depende.</p>
<div class="diagrama">
<svg viewbox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="La tabla plana en primera forma normal se descompone en tres tablas: Pedido con Cliente y Teléfono porque dependen solo de Pedido, Pedido_Producto como tabla de unión sin atributos propios, y Producto con Valor porque depende solo de Producto" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="dba3t2c" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Cada atributo se agrupa con la parte de la llave de la que depende</text> <rect x="220" y="30" width="320" height="56" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="380" y="52" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Pedidos, tras la 1FN</text> <text x="380" y="70" font-size="11" fill="#5b6876" text-anchor="middle">llave: (Pedido, Producto)</text> <path d="M340,86 C280,110 200,130 150,166" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#dba3t2c)"></path> <path d="M380,86 L380,166" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#dba3t2c)"></path> <path d="M420,86 C480,110 560,130 610,166" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#dba3t2c)"></path> <text x="220" y="132" font-size="10.5" fill="#5b6876" text-anchor="middle">Cliente y Teléfono</text> <text x="220" y="145" font-size="10.5" fill="#5b6876" text-anchor="middle">dependen solo de Pedido</text> <text x="545" y="132" font-size="10.5" fill="#5b6876" text-anchor="middle">Valor depende</text> <text x="545" y="145" font-size="10.5" fill="#5b6876" text-anchor="middle">solo de Producto</text> <rect x="30" y="168" width="230" height="66" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="145" y="190" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Pedido</text> <text x="145" y="207" font-size="11" fill="#5b6876" text-anchor="middle">Cliente, Teléfono</text> <text x="145" y="222" font-size="10" fill="#5b6876" text-anchor="middle">llave: Pedido</text> <rect x="290" y="168" width="200" height="66" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="390" y="190" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Pedido_Producto</text> <text x="390" y="207" font-size="11" fill="#5b6876" text-anchor="middle">sin atributos propios</text> <text x="390" y="222" font-size="10" fill="#5b6876" text-anchor="middle">llave: (Pedido, Producto)</text> <rect x="520" y="168" width="210" height="66" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="625" y="190" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Producto</text> <text x="625" y="207" font-size="11" fill="#5b6876" text-anchor="middle">Valor</text> <text x="625" y="222" font-size="10" fill="#5b6876" text-anchor="middle">llave: Producto</text> <text x="380" y="268" font-size="11.5" fill="#5b6876" text-anchor="middle">El café ya no repite su precio en cada pedido que lo incluye: vive una sola vez en la tabla Producto</text>
</svg>
</div>
<p>La tabla <code>Pedido_Producto</code> queda sin ningún atributo propio, solo con la pareja de llaves foráneas que la forman, porque en esta tabla plana no hay ningún dato adicional, como una cantidad, que dependa de la combinación completa de pedido y producto. Si la cafetería quisiera registrar cuántas unidades de un producto lleva cada pedido, ese dato de cantidad sí dependería de las dos partes de la llave a la vez, y por eso se quedaría precisamente en esta tabla, no en ninguna de las otras dos, tal como ya viste con el atributo <code>cantidad</code> de <code>Detalle_Pedido</code> en el caso de la cafetería de la Unidad 2.</p>
</section>
<section id="tercera-forma-normal-nada-depende-de-un-atributo-que-no-es-la-llave" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="tercera-forma-normal-nada-depende-de-un-atributo-que-no-es-la-llave"><span class="header-section-number">6</span> Tercera forma normal: nada depende de un atributo que no es la llave</h2>
<p>La <em>tercera forma normal</em>, o 3FN, exige que la tabla ya esté en 2FN y que, además, ningún atributo que no es llave dependa de otro atributo que tampoco es llave. Cuando eso ocurre, se dice que hay una <em>dependencia transitiva</em>, un atributo A determina a un atributo B, que a su vez determina a un atributo C, así que C termina dependiendo de A de forma indirecta, pasando por B en el camino. Codd definió también esta forma en el mismo artículo de 1971, con la conjetura de que una tabla en 3FN extiende la vida útil de los programas que la usan, porque cambiar un atributo transitivo ya no obliga a tocar filas que en realidad hablan de otra cosa.</p>
<p>La tabla <code>Pedido</code> que quedó tras la 2FN, con los atributos <code>Pedido</code>, <code>Cliente</code> y <code>Teléfono</code>, todavía tiene ese problema. <code>Pedido</code> determina a <code>Cliente</code>, eso es correcto y esperado, un pedido pertenece a un cliente. Pero <code>Cliente</code> determina a su vez a <code>Teléfono</code>, y ese <code>Teléfono</code> no depende directamente de <code>Pedido</code>, depende de <code>Cliente</code>, que tampoco es la llave de esta tabla. <code>Teléfono</code> termina dependiendo de <code>Pedido</code> solo de forma transitiva, pasando por <code>Cliente</code>, y esa es exactamente la dependencia transitiva que la 3FN prohíbe.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. Cuenta las repeticiones
</div>
</div>
<div class="callout-body-container callout-body">
<p>Con la tabla <code>Pedido(Pedido, Cliente, Teléfono)</code> que quedó tras la 2FN, todavía con una fila por cada uno de los cuatro pedidos originales, responde antes de seguir leyendo. Cuántas veces aparece el número de teléfono de Ana Ruiz en esta tabla, y si Ana cambia de número, cuántas filas hay que corregir con esta estructura. Explica con tus palabras por qué la 2FN, por sí sola, no alcanzó a resolver esa repetición.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>El teléfono de Ana Ruiz aparece tres veces en la tabla <code>Pedido</code>, una por cada uno de sus tres pedidos, el 1001, el 1002 y el 1004, exactamente la misma cantidad de veces que en la tabla plana original. Si Ana cambia de número, hay que corregir las tres filas.</p>
<p>La 2FN no resolvió esta repetición porque su regla solo mira la relación entre los atributos y la llave de la tabla, que en <code>Pedido(Pedido, Cliente, Teléfono)</code> es <code>Pedido</code> solamente. Tanto <code>Cliente</code> como <code>Teléfono</code> dependen de esa llave completa, así que ninguno de los dos viola la 2FN dentro de esta tabla. El problema real no está entre estos atributos y la llave, está entre dos atributos que no son llave, <code>Cliente</code> determina a <code>Teléfono</code>, y ese tipo de dependencia solo lo detecta la 3FN.</p>
</div>
</div>
</div>
<p>La corrección separa <code>Cliente</code> y <code>Teléfono</code> en su propia tabla, dejando en <code>Pedido</code> solo una llave foránea hacia <code>Cliente</code>.</p>
<div class="diagrama">
<svg viewbox="0 0 760 260" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="La tabla Pedido con Cliente y Teléfono, tras la segunda forma normal, tiene una dependencia transitiva porque Teléfono depende de Cliente y no directamente de Pedido, se descompone en una tabla Pedido con Cliente como llave foránea y una tabla Cliente con Teléfono, unidas por esa llave foránea" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="dba3t2d" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Teléfono depende de Cliente, no directamente de Pedido</text> <rect x="30" y="40" width="260" height="150" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="160" y="62" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Pedido, tras la 2FN</text> <rect x="60" y="76" width="200" height="34" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="160" y="98" font-size="11.5" fill="#12324f" text-anchor="middle">Pedido (llave)</text> <path d="M160,110 L160,124" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#dba3t2d)"></path> <rect x="60" y="126" width="200" height="34" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="160" y="148" font-size="11.5" fill="#12324f" text-anchor="middle">Cliente</text> <path d="M160,160 L160,174" fill="none" stroke="#0e6f6c" stroke-width="1.6" stroke-dasharray="3 3" marker-end="url(#dba3t2d)"></path> <text x="270" y="170" font-size="10" fill="#0e6f6c" text-anchor="start">transitiva</text> <rect x="330" y="90" width="110" height="30" rx="6" fill="none" stroke="none"></rect> <text x="385" y="108" font-size="11.5" font-weight="700" fill="#5b6876" text-anchor="middle">3FN separa</text> <path d="M300,120 L440,120" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#dba3t2d)"></path> <rect x="470" y="40" width="170" height="60" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="555" y="62" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Pedido</text> <text x="555" y="80" font-size="11" fill="#5b6876" text-anchor="middle">Cliente (llave foránea)</text> <rect x="560" y="140" width="170" height="60" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="645" y="162" font-size="12.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Cliente</text> <text x="645" y="180" font-size="11" fill="#3c7d7a" text-anchor="middle">Teléfono</text> <path d="M580,100 C590,120 610,130 620,138" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#dba3t2d)"></path> <text x="380" y="232" font-size="11.5" fill="#5b6876" text-anchor="middle">El teléfono de Ana ya vive una sola vez, en su fila de la tabla Cliente</text>
</svg>
</div>
<p>Con esta última separación, la tabla de pedidos originales queda convertida en cuatro tablas, <code>Cliente</code> con <code>Teléfono</code>, <code>Pedido</code> con una llave foránea hacia <code>Cliente</code>, <code>Producto</code> con <code>Valor</code>, y <code>Pedido_Producto</code> como tabla de unión entre <code>Pedido</code> y <code>Producto</code>. Este resultado es equivalente en espíritu al diagrama entidad-relación completo que armaste en la Unidad 2 para el mismo negocio, tres entidades, <code>Cliente</code>, <code>Pedido</code> y <code>Producto</code>, conectadas por una relación uno a muchos y una relación muchos a muchos resuelta con tabla propia. Hay dos diferencias honestas que vale la pena marcar. La primera es que esta tabla plana nunca tuvo una columna de fecha, así que el <code>Pedido</code> que resulta de la normalización no la incluye, aunque el modelo entidad-relación de la Unidad 2 sí la tenía. La segunda es que, sin una columna de cantidad en los datos originales, <code>Pedido_Producto</code> queda sin atributos propios, mientras que <code>Detalle_Pedido</code> en la Unidad 2 sí llevaba <code>cantidad</code>. Ninguna de las dos diferencias es un error, son la consecuencia lógica de partir de datos distintos, un diagrama diseñado desde cero contra una tabla que ya existía con las columnas que alguien decidió guardarle en su momento. También queda pendiente, a propósito, decidir si <code>Cliente</code> debería identificarse por su nombre o por un identificador propio como el <code>id_cliente</code> de la Unidad 2, una decisión de llave que el Tema 3 va a formalizar junto con los tipos de dato y las restricciones de cada tabla.</p>
<p>Con esta última tabla, ya puedes volver a las tres anomalías de la apertura del tema y confirmar que las tres desaparecieron. Cambiar el teléfono de Ana corrige una sola fila, la de <code>Cliente</code>, y sus tres pedidos siguen apuntando a ese mismo cliente sin que el teléfono se repita en ningún lado. Registrar un cliente nuevo del programa de fidelización ya no exige que tenga un pedido, porque <code>Cliente</code> es su propia tabla, independiente de <code>Pedido</code>. Y borrar el pedido 1003 ya no borra el teléfono de Luis Pena, porque ese dato vive en la tabla <code>Cliente</code>, no en la fila del pedido que se elimina.</p>
</section>
<section id="cuarta-forma-normal-dos-hechos-independientes-no-comparten-tabla" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="cuarta-forma-normal-dos-hechos-independientes-no-comparten-tabla"><span class="header-section-number">7</span> Cuarta forma normal: dos hechos independientes no comparten tabla</h2>
<p>Las tres formas anteriores corrigen problemas causados por dependencias funcionales, un atributo determina a otro con un único valor posible. La <em>cuarta forma normal</em>, o 4FN, corrige un problema distinto, causado por una <em>dependencia multivaluada</em>, cuando un atributo determina, no un único valor de otro atributo, sino un conjunto entero de valores, y ese conjunto no depende de un tercer atributo que también esté en la misma tabla. Ronald Fagin definió este concepto y esta forma normal en 1977, en el artículo <em>Multivalued Dependencies and a New Normal Form for Relational Databases</em>, publicado en ACM Transactions on Database Systems. Una tabla está en 4FN cuando, para toda dependencia multivaluada no trivial que contenga, el atributo que determina es, por sí solo, una llave capaz de identificar cada fila.</p>
<p>La tabla de pedidos de la cafetería no tiene, con las columnas que trae, ningún caso de dependencia multivaluada, así que conviene un ejemplo aparte, simple y distinto, para ver el problema con claridad. Imagina que la cafetería registra, para cada empleado de cocina, las habilidades que domina y los idiomas que habla, sin relación alguna entre unas y otros, un empleado puede saber preparar postres y hablar inglés, sin que eso tenga nada que ver con si también habla francés.</p>
<div class="diagrama">
<svg viewbox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Marta domina dos habilidades, análisis de datos y diseño UX, y habla dos idiomas, inglés y francés, de forma independiente entre sí; una sola tabla que junte las tres columnas necesita las cuatro combinaciones posibles, mientras que separar habilidad e idioma en dos tablas evita esa multiplicación" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="dba3t2e" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Dos hechos independientes sobre Marta, multiplicados en una sola tabla</text> <rect x="140" y="32" width="480" height="100" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="380" y="50" font-size="11.5" font-weight="700" fill="#12324f" text-anchor="middle">Empleado_Habilidad_Idioma (Empleado, Habilidad, Idioma)</text> <text x="380" y="68" font-size="11" fill="#5b6876" text-anchor="middle">Marta, Análisis de datos, Inglés</text> <text x="380" y="84" font-size="11" fill="#5b6876" text-anchor="middle">Marta, Análisis de datos, Francés</text> <text x="380" y="100" font-size="11" fill="#5b6876" text-anchor="middle">Marta, Diseño UX, Inglés</text> <text x="380" y="116" font-size="11" fill="#5b6876" text-anchor="middle">Marta, Diseño UX, Francés</text> <path d="M380,132 L380,164" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#dba3t2e)"></path> <text x="470" y="152" font-size="10.5" fill="#5b6876" text-anchor="start">4FN separa las dos dependencias multivaluadas</text> <rect x="110" y="170" width="260" height="70" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="240" y="192" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Empleado_Habilidad</text> <text x="240" y="210" font-size="11" fill="#5b6876" text-anchor="middle">Marta, Análisis de datos</text> <text x="240" y="226" font-size="11" fill="#5b6876" text-anchor="middle">Marta, Diseño UX</text> <rect x="390" y="170" width="260" height="70" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="520" y="192" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Empleado_Idioma</text> <text x="520" y="210" font-size="11" fill="#5b6876" text-anchor="middle">Marta, Inglés</text> <text x="520" y="226" font-size="11" fill="#5b6876" text-anchor="middle">Marta, Francés</text> <text x="380" y="270" font-size="11.5" fill="#5b6876" text-anchor="middle">Agregar un tercer idioma ahora agrega una sola fila, no una por cada habilidad</text>
</svg>
</div>
<p>Guardar las dos cosas en una sola tabla <code>Empleado_Habilidad_Idioma</code>, con las tres columnas juntas, obliga a escribir una fila por cada combinación posible entre las habilidades y los idiomas de un mismo empleado, aunque las dos cosas no tengan relación entre sí. Marta domina dos habilidades y habla dos idiomas, así que su información ocupa cuatro filas, dos por cada habilidad multiplicadas por los dos idiomas. Si Marta aprende un tercer idioma, portugués por ejemplo, hay que agregar dos filas nuevas, una por cada habilidad que ya tenía, para mantener el registro de todas las combinaciones, aunque el hecho nuevo, que habla portugués, no tenga nada que ver con sus habilidades. Esa es la redundancia que corrige la 4FN, separar <code>Habilidad</code> e <code>Idioma</code> en dos tablas propias, cada una con <code>Empleado</code> como parte de su llave, deja que agregar un idioma nuevo agregue exactamente una fila, sin tocar las habilidades para nada.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 4. Otro caso de hechos independientes
</div>
</div>
<div class="callout-body-container callout-body">
<p>La cafetería también registra, para cada cliente frecuente, las formas de pago que suele usar (efectivo, tarjeta, aplicación del celular) y los apodos con los que el personal lo reconoce (su nombre, un apodo cariñoso, una seña particular), sin que unas cosas tengan relación con las otras.</p>
<p>Si alguien propone guardar las tres columnas, <code>Cliente</code>, <code>FormaPago</code> y <code>Apodo</code>, en una sola tabla, explica en un párrafo qué le pasaría a esa tabla si un cliente tiene dos formas de pago registradas y dos apodos con los que lo conocen, y cómo la separarías en dos tablas siguiendo el mismo patrón del ejemplo de Marta.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Con las tres columnas juntas, un cliente con dos formas de pago y dos apodos necesitaría cuatro filas, una por cada combinación entre una forma de pago y un apodo, exactamente igual que Marta con sus habilidades e idiomas, aunque la forma en que paga ese cliente no tenga ninguna relación con el apodo que usa el personal para reconocerlo. Agregar una tercera forma de pago, por ejemplo si empieza a pagar con una billetera digital nueva, obligaría a agregar una fila por cada apodo que ya tuviera registrado, una redundancia idéntica a la del ejemplo de Marta.</p>
<p>La corrección separa las dos dependencias multivaluadas en dos tablas propias, <code>Cliente_FormaPago</code> con <code>Cliente</code> y <code>FormaPago</code>, y <code>Cliente_Apodo</code> con <code>Cliente</code> y <code>Apodo</code>, cada una con su propia llave compuesta por esos dos atributos. Agregar una forma de pago nueva entonces agrega una sola fila en <code>Cliente_FormaPago</code>, sin tocar <code>Cliente_Apodo</code> para nada.</p>
</div>
</div>
</div>
</section>
<section id="qué-anomalía-corrige-cada-forma-normal" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="qué-anomalía-corrige-cada-forma-normal"><span class="header-section-number">8</span> Qué anomalía corrige cada forma normal</h2>
<p>Con las cuatro formas ya recorridas, conviene cerrar con el mapa completo, qué elimina cada una y qué anomalía concreta corrige en el caso de la cafetería.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Forma normal</th>
<th>Qué elimina</th>
<th>Anomalía que corrige en el caso de la cafetería</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1FN</td>
<td>Valores no atómicos y la falta de una llave que identifique cada fila sin ambigüedad</td>
<td>Evita que un pedido con varios productos se comprima en una fila con una lista de productos, lo que impediría agregar un producto sin reescribir la fila entera</td>
</tr>
<tr class="even">
<td>2FN</td>
<td>Dependencia parcial de un atributo no clave sobre una parte de una llave compuesta</td>
<td>El precio de un producto deja de repetirse cada vez que ese producto aparece en un pedido distinto, como el café en los pedidos 1001 y 1003</td>
</tr>
<tr class="odd">
<td>3FN</td>
<td>Dependencia transitiva de un atributo no clave sobre otro atributo no clave</td>
<td>Las tres anomalías clásicas sobre el teléfono de Ana, ya no hay que corregirlo en varias filas, ya se puede registrar un cliente sin pedidos, y borrar un pedido ya no borra el teléfono de nadie</td>
</tr>
<tr class="even">
<td>4FN</td>
<td>Dependencias multivaluadas independientes mezcladas en la misma tabla</td>
<td>En el ejemplo de Marta, agregar un idioma nuevo ya no obliga a repetir una fila por cada habilidad que domina</td>
</tr>
</tbody>
</table>
<p>Fíjate en un patrón dentro de esta tabla, la 2FN corrigió una redundancia real pero silenciosa, la del precio del producto, que ni siquiera estaba entre las tres anomalías con las que abrió el tema. Las tres anomalías clásicas de la Unidad 1, las que sí estaban ahí desde el principio, resultaron depender de una dependencia transitiva, así que hizo falta llegar hasta la 3FN para resolverlas del todo. Ese es justamente el motivo por el que la normalización se recorre en orden y no se detiene en la primera forma que parece razonable, un diseño puede parecer correcto y seguir escondiendo una anomalía que solo aparece al aplicar la siguiente regla.</p>
</section>
<section id="lo-que-te-llevas-de-hoy" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="lo-que-te-llevas-de-hoy"><span class="header-section-number">9</span> Lo que te llevas de hoy</h2>
<div class="checklist">
<p>Al salir de este tema deberías poder explicar, sin mirar la guía, los siguientes puntos:</p>
<ul class="task-list">
<li><label><input type="checkbox">Las tres anomalías clásicas, inserción, actualización y borrado, señaladas sobre filas y columnas concretas de la tabla de pedidos</label></li>
<li><label><input type="checkbox">Qué es una dependencia funcional y la diferencia entre una regla de negocio real y una coincidencia de los datos que tienes delante</label></li>
<li><label><input type="checkbox">Por qué <code>Pedido</code> por sí solo no es una llave candidata válida para la tabla plana, y por qué <code>(Pedido, Producto)</code> sí lo es</label></li>
<li><label><input type="checkbox">La primera forma normal, valores atómicos más una llave que identifique cada fila sin ambigüedad</label></li>
<li><label><input type="checkbox">La segunda forma normal, sin dependencia parcial de una llave compuesta, y por qué el precio del producto violaba esa regla</label></li>
<li><label><input type="checkbox">La tercera forma normal, sin dependencia transitiva, y por qué resolvió las tres anomalías clásicas que la 2FN dejó intactas</label></li>
<li><label><input type="checkbox">La cuarta forma normal, sin dependencias multivaluadas independientes mezcladas en la misma tabla, con el ejemplo de las habilidades y los idiomas</label></li>
<li><label><input type="checkbox">La jerarquía completa de las cuatro formas normales y qué anomalía corrige cada una</label></li>
</ul>
</div>
</section>
<section id="lo-que-sigue" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="lo-que-sigue"><span class="header-section-number">10</span> Lo que sigue</h2>
<p>Hoy terminaste de construir cuatro tablas, <code>Cliente</code>, <code>Pedido</code>, <code>Producto</code> y <code>Pedido_Producto</code>, partiendo de una sola tabla plana con anomalías y aplicando un procedimiento formal en vez de un diagrama. El resultado es equivalente en espíritu al modelo entidad-relación que armaste en la Unidad 2 para el mismo negocio, y coherente con el mapeo que el Tema 1 de esta unidad aplicó sobre ese mismo diagrama, dos caminos distintos que llegan a una estructura de tablas parecida.</p>
<p>Lo que todavía falta es precisar cada tabla al nivel de detalle con el que de verdad se construye una base de datos, qué tipo de dato guarda cada columna, cuál es la llave primaria exacta de cada tabla, cuáles son las llaves foráneas y qué restricciones garantizan que los datos se mantengan correctos. Ese es el trabajo del Tema 3, el último de esta unidad, que toma exactamente las tablas normalizadas de hoy como punto de partida.</p>
</section>
<section id="recursos" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="recursos"><span class="header-section-number">11</span> Recursos</h2>
<ul>
<li>Codd, E. F. (1970). <em>A Relational Model of Data for Large Shared Data Banks.</em> Communications of the ACM, 13(6). <a href="https://www.engineering.upenn.edu/~zives/03f/cis550/codd.pdf">Copia en la Universidad de Pensilvania</a>.</li>
<li>Codd, E. F. (1971). <em>Further Normalization of the Data Base Relational Model.</em> IBM Research Report RJ909, San Jose, California. Artículo donde se definen formalmente la segunda y la tercera forma normal. <a href="http://www.sigmod.org/publications/dblp/db/labs/ibm/RJ909.html">Ficha bibliográfica en sigmod.org</a>.</li>
<li>Fagin, R. (1977). <em>Multivalued Dependencies and a New Normal Form for Relational Databases.</em> ACM Transactions on Database Systems, 2(3), 262 a 278. DOI: <a href="https://doi.org/10.1145/320557.320571">10.1145/320557.320571</a>.</li>
<li>Silberschatz, A., Korth, H. F. y Sudarshan, S. <em>Database System Concepts</em> (7.a ed.). Capítulo sobre diseño de bases de datos relacionales, dependencias funcionales y formas normales. Material de apoyo oficial de los autores en <a href="https://www.db-book.com">db-book.com</a>.</li>
<li>Elmasri, R. y Navathe, S. B. <em>Fundamentals of Database Systems.</em> Capítulo sobre fundamentos de dependencias funcionales y normalización, y capítulo sobre algoritmos de diseño relacional y formas normales adicionales.</li>
<li>Connolly, T. M. y Begg, C. E. <em>Database Systems: A Practical Approach to Design, Implementation, and Management.</em> Capítulo sobre normalización, dependencias funcionales y anomalías de actualización.</li>
</ul>
<div class="pie-doc">
<p>Base de datos (DBA03). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>