<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 1. Estándares IEEE para la calidad del software – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-95bfa606010d176c52cfb6b551730f65.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/index.html">Unidad 3. Estándares de calidad aplicados al software</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html">Tema 1. Estándares IEEE para la calidad del software</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Calidad del software y estándares de calidad</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-01-que-es-calidad-quien-la-define/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es la calidad y quién la define</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Calidad de proceso y de producto: ISO/IEC 25010:2023</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Importancia, costo y calidad en un mundo globalizado</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Procesos de calidad del software. Modelos y métricas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-01-sqa-relacion-ingenieria/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es el SQA y su relación con la ingeniería de software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La calidad en cada fase del ciclo de vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-03-roles-habilidades/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Roles, responsabilidades y habilidades del personal de SQA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-04-actividades-sqa/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Actividades del SQA: revisiones, auditorías y gestión de configuración</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-05-modelos-metricas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Modelos y métricas de calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-06-herramientas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 6. Herramientas de SQA en la industria</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 3. Estándares de calidad aplicados al software</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 1. Estándares IEEE para la calidad del software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Marcos para evaluar la usabilidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Madurez de procesos: SPICE y CMMI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 4. Validación y verificación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Métodos, metodologías y estándares de verificación y validación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Validación y verificación de requisitos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-03-control-costo-calidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Control de la calidad y costo de la calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Nomenclatura y certificación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-05-factores-atam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Factores que determinan la calidad y el método ATAM</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#objetivo-y-resultado-de-aprendizaje" id="toc-objetivo-y-resultado-de-aprendizaje" class="nav-link active" data-scroll-target="#objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</a></li>
  <li><a href="#ruta-de-estudio" id="toc-ruta-de-estudio" class="nav-link" data-scroll-target="#ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</a></li>
  <li><a href="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" id="toc-el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="nav-link" data-scroll-target="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</a></li>
  <li><a href="#parte-1.-quién-escribe-las-normas" id="toc-parte-1.-quién-escribe-las-normas" class="nav-link" data-scroll-target="#parte-1.-quién-escribe-las-normas"><span class="header-section-number">4</span> Parte 1. Quién escribe las normas</a>
  <ul class="collapse">
  <li><a href="#cómo-leer-el-estado-de-una-norma" id="toc-cómo-leer-el-estado-de-una-norma" class="nav-link" data-scroll-target="#cómo-leer-el-estado-de-una-norma">Cómo leer el estado de una norma</a></li>
  </ul></li>
  <li><a href="#parte-2.-el-mapa-de-la-familia" id="toc-parte-2.-el-mapa-de-la-familia" class="nav-link" data-scroll-target="#parte-2.-el-mapa-de-la-familia"><span class="header-section-number">5</span> Parte 2. El mapa de la familia</a></li>
  <li><a href="#parte-3.-ieee-730-aseguramiento-de-calidad-del-software" id="toc-parte-3.-ieee-730-aseguramiento-de-calidad-del-software" class="nav-link" data-scroll-target="#parte-3.-ieee-730-aseguramiento-de-calidad-del-software"><span class="header-section-number">6</span> Parte 3. IEEE 730: aseguramiento de calidad del software</a>
  <ul class="collapse">
  <li><a href="#historia-en-pocas-líneas" id="toc-historia-en-pocas-líneas" class="nav-link" data-scroll-target="#historia-en-pocas-líneas">Historia en pocas líneas</a></li>
  <li><a href="#a-quién-aplica" id="toc-a-quién-aplica" class="nav-link" data-scroll-target="#a-quién-aplica">A quién aplica</a></li>
  <li><a href="#tres-áreas-y-16-actividades" id="toc-tres-áreas-y-16-actividades" class="nav-link" data-scroll-target="#tres-áreas-y-16-actividades">Tres áreas y 16 actividades</a></li>
  <li><a href="#independencia-tres-parámetros" id="toc-independencia-tres-parámetros" class="nav-link" data-scroll-target="#independencia-tres-parámetros">Independencia: tres parámetros</a></li>
  <li><a href="#conformidad-completa-o-ajustada" id="toc-conformidad-completa-o-ajustada" class="nav-link" data-scroll-target="#conformidad-completa-o-ajustada">Conformidad completa o ajustada</a></li>
  <li><a href="#qué-lleva-el-plan-sqap" id="toc-qué-lleva-el-plan-sqap" class="nav-link" data-scroll-target="#qué-lleva-el-plan-sqap">Qué lleva el plan (SQAP)</a></li>
  </ul></li>
  <li><a href="#parte-4.-ejemplo-resuelto-el-sqap-de-la-clínica" id="toc-parte-4.-ejemplo-resuelto-el-sqap-de-la-clínica" class="nav-link" data-scroll-target="#parte-4.-ejemplo-resuelto-el-sqap-de-la-clínica"><span class="header-section-number">7</span> Parte 4. Ejemplo resuelto: el SQAP de la clínica</a>
  <ul class="collapse">
  <li><a href="#paso-1.-alcance-y-riesgo-del-producto" id="toc-paso-1.-alcance-y-riesgo-del-producto" class="nav-link" data-scroll-target="#paso-1.-alcance-y-riesgo-del-producto">Paso 1. Alcance y riesgo del producto</a></li>
  <li><a href="#paso-2.-esfuerzo" id="toc-paso-2.-esfuerzo" class="nav-link" data-scroll-target="#paso-2.-esfuerzo">Paso 2. Esfuerzo</a></li>
  <li><a href="#paso-3.-independencia" id="toc-paso-3.-independencia" class="nav-link" data-scroll-target="#paso-3.-independencia">Paso 3. Independencia</a></li>
  <li><a href="#paso-4.-el-plan-sección-por-sección" id="toc-paso-4.-el-plan-sección-por-sección" class="nav-link" data-scroll-target="#paso-4.-el-plan-sección-por-sección">Paso 4. El plan, sección por sección</a></li>
  <li><a href="#paso-5.-una-medición-de-ejemplo" id="toc-paso-5.-una-medición-de-ejemplo" class="nav-link" data-scroll-target="#paso-5.-una-medición-de-ejemplo">Paso 5. Una medición de ejemplo</a></li>
  </ul></li>
  <li><a href="#parte-5.-documentar-las-pruebas-de-ieee-829-a-isoiecieee-29119" id="toc-parte-5.-documentar-las-pruebas-de-ieee-829-a-isoiecieee-29119" class="nav-link" data-scroll-target="#parte-5.-documentar-las-pruebas-de-ieee-829-a-isoiecieee-29119"><span class="header-section-number">8</span> Parte 5. Documentar las pruebas: de IEEE 829 a ISO/IEC/IEEE 29119</a>
  <ul class="collapse">
  <li><a href="#qué-fue-ieee-829-y-qué-le-pasó" id="toc-qué-fue-ieee-829-y-qué-le-pasó" class="nav-link" data-scroll-target="#qué-fue-ieee-829-y-qué-le-pasó">Qué fue IEEE 829 y qué le pasó</a></li>
  <li><a href="#las-partes-de-isoiecieee-29119" id="toc-las-partes-de-isoiecieee-29119" class="nav-link" data-scroll-target="#las-partes-de-isoiecieee-29119">Las partes de ISO/IEC/IEEE 29119</a></li>
  <li><a href="#los-documentos-de-la-parte-3" id="toc-los-documentos-de-la-parte-3" class="nav-link" data-scroll-target="#los-documentos-de-la-parte-3">Los documentos de la parte 3</a></li>
  <li><a href="#ejemplo-resuelto-documentos-de-prueba-para-el-límite-de-20-turnos" id="toc-ejemplo-resuelto-documentos-de-prueba-para-el-límite-de-20-turnos" class="nav-link" data-scroll-target="#ejemplo-resuelto-documentos-de-prueba-para-el-límite-de-20-turnos">Ejemplo resuelto: documentos de prueba para el límite de 20 turnos</a></li>
  <li><a href="#una-discusión-sobre-29119" id="toc-una-discusión-sobre-29119" class="nav-link" data-scroll-target="#una-discusión-sobre-29119">Una discusión sobre 29119</a></li>
  </ul></li>
  <li><a href="#parte-6.-isoiecieee-12207-el-mapa-del-ciclo-de-vida" id="toc-parte-6.-isoiecieee-12207-el-mapa-del-ciclo-de-vida" class="nav-link" data-scroll-target="#parte-6.-isoiecieee-12207-el-mapa-del-ciclo-de-vida"><span class="header-section-number">9</span> Parte 6. ISO/IEC/IEEE 12207: el mapa del ciclo de vida</a>
  <ul class="collapse">
  <li><a href="#historia-en-pocas-líneas-1" id="toc-historia-en-pocas-líneas-1" class="nav-link" data-scroll-target="#historia-en-pocas-líneas-1">Historia en pocas líneas</a></li>
  <li><a href="#qué-hace-y-qué-no-hace" id="toc-qué-hace-y-qué-no-hace" class="nav-link" data-scroll-target="#qué-hace-y-qué-no-hace">Qué hace y qué no hace</a></li>
  <li><a href="#los-cuatro-grupos-de-procesos" id="toc-los-cuatro-grupos-de-procesos" class="nav-link" data-scroll-target="#los-cuatro-grupos-de-procesos">Los cuatro grupos de procesos</a></li>
  <li><a href="#cómo-usar-el-mapa" id="toc-cómo-usar-el-mapa" class="nav-link" data-scroll-target="#cómo-usar-el-mapa">Cómo usar el mapa</a></li>
  </ul></li>
  <li><a href="#parte-7.-requisitos-y-vocabulario-29148-y-24765" id="toc-parte-7.-requisitos-y-vocabulario-29148-y-24765" class="nav-link" data-scroll-target="#parte-7.-requisitos-y-vocabulario-29148-y-24765"><span class="header-section-number">10</span> Parte 7. Requisitos y vocabulario: 29148 y 24765</a>
  <ul class="collapse">
  <li><a href="#isoiecieee-29148-ingeniería-de-requisitos" id="toc-isoiecieee-29148-ingeniería-de-requisitos" class="nav-link" data-scroll-target="#isoiecieee-29148-ingeniería-de-requisitos">ISO/IEC/IEEE 29148: ingeniería de requisitos</a></li>
  <li><a href="#ejemplo-resuelto-mejorar-un-requisito-de-la-clínica" id="toc-ejemplo-resuelto-mejorar-un-requisito-de-la-clínica" class="nav-link" data-scroll-target="#ejemplo-resuelto-mejorar-un-requisito-de-la-clínica">Ejemplo resuelto: mejorar un requisito de la clínica</a></li>
  <li><a href="#isoiecieee-24765-vocabulario" id="toc-isoiecieee-24765-vocabulario" class="nav-link" data-scroll-target="#isoiecieee-24765-vocabulario">ISO/IEC/IEEE 24765: vocabulario</a></li>
  <li><a href="#cómo-se-conectan-las-cinco-normas" id="toc-cómo-se-conectan-las-cinco-normas" class="nav-link" data-scroll-target="#cómo-se-conectan-las-cinco-normas">Cómo se conectan las cinco normas</a></li>
  </ul></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes"><span class="header-section-number">11</span> Errores frecuentes</a></li>
  <li><a href="#autoevaluación" id="toc-autoevaluación" class="nav-link" data-scroll-target="#autoevaluación"><span class="header-section-number">12</span> Autoevaluación</a></li>
  <li><a href="#lo-que-te-llevas" id="toc-lo-que-te-llevas" class="nav-link" data-scroll-target="#lo-que-te-llevas"><span class="header-section-number">13</span> Lo que te llevas</a></li>
  <li><a href="#glosario" id="toc-glosario" class="nav-link" data-scroll-target="#glosario"><span class="header-section-number">14</span> Glosario</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">15</span> Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/index.html">Unidad 3. Estándares de calidad aplicados al software</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html">Tema 1. Estándares IEEE para la calidad del software</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 1. Estándares IEEE para la calidad del software</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">3 de octubre de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 88%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 3. Estándares de calidad aplicados al software</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 1. Estándares IEEE para la calidad del software</td>
</tr>
</tbody>
</table>
</div>
<p><a href="../presentacion-interactiva.html" class="btn-curso">Presentación interactiva de la unidad</a></p>
<p>Introducción de la unidad: <a href="../../../calidad-del-software/unidad-03/index.html">Unidad 3. Estándares de calidad aplicados al software</a>. Tema anterior: <a href="../../../calidad-del-software/unidad-02/tema-06-herramientas/index.html">Unidad 2, Tema 6. Herramientas</a>. Tema siguiente: <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html">Tema 2. Normas ISO</a>.</p>
<section id="objetivo-y-resultado-de-aprendizaje" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</h2>
<p>La Unidad 2 te enseñó qué hace el SQA. Esta unidad te enseña contra qué marcos externos se compara el trabajo. Este primer tema recorre los estándares que publica el IEEE, la mayoría en conjunto con ISO e IEC, y los que más se citan cuando una organización documenta su calidad de software: el plan de aseguramiento (IEEE 730), la documentación de pruebas (de IEEE 829 a ISO/IEC/IEEE 29119), el mapa del ciclo de vida (ISO/IEC/IEEE 12207), los requisitos (29148) y el vocabulario (24765).</p>
<p>Al terminar puedes:</p>
<ul>
<li>Distinguir una norma IEEE pura de una norma conjunta ISO/IEC/IEEE, y leer el estado de una norma (vigente, sustituida, inactiva) en la ficha del editor.</li>
<li>Explicar qué exige IEEE 730 y enumerar sus tres áreas y sus 16 actividades.</li>
<li>Redactar un plan de aseguramiento de calidad (SQAP) para un proyecto pequeño, con riesgos, esfuerzo, actividades y registros.</li>
<li>Decir qué documentos de prueba define ISO/IEC/IEEE 29119-3 y producirlos para un requisito concreto.</li>
<li>Ubicar un trabajo de calidad dentro de los cuatro grupos de procesos de ISO/IEC/IEEE 12207.</li>
<li>Usar 29148 para mejorar un requisito y 24765 para fijar el vocabulario de un equipo.</li>
<li>Citar con fecha de consulta qué edición de cada norma está vigente, sin repetir de memoria datos que cambian.</li>
</ul>
<p>Prerrequisitos: los temas de la Unidad 2, en especial actividades de SQA, revisiones y auditorías. Necesitas saber qué es un requisito, un caso de prueba y un defecto.</p>
</section>
<section id="ruta-de-estudio" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</h2>
<p>Son unas 5 horas de trabajo independiente. Puedes partirlas en dos o tres sesiones. La presentación interactiva de la unidad sigue las mismas partes y sirve como repaso.</p>
<div class="calendario">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parte</th>
<th>Qué haces</th>
<th>Tiempo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Quién escribe las normas</td>
<td>Lees la diferencia entre norma pura y conjunta, y aprendes a leer el estado de una norma</td>
<td>25 min</td>
</tr>
<tr class="even">
<td>2. El mapa de la familia</td>
<td>Lees la tabla de normas con su estado a octubre de 2026 y resuelves el Reto 1</td>
<td>30 min</td>
</tr>
<tr class="odd">
<td>3. IEEE 730</td>
<td>Lees las tres áreas, las 16 actividades y la historia de sus ediciones</td>
<td>50 min</td>
</tr>
<tr class="even">
<td>4. Ejemplo resuelto: el SQAP de la clínica</td>
<td>Sigues el plan completo con números y resuelves los Retos 2 y 3</td>
<td>55 min</td>
</tr>
<tr class="odd">
<td>5. Documentar las pruebas</td>
<td>Lees de IEEE 829 a 29119, sigues el ejemplo resuelto y resuelves el Reto 4</td>
<td>50 min</td>
</tr>
<tr class="even">
<td>6. ISO/IEC/IEEE 12207</td>
<td>Lees los cuatro grupos de procesos y resuelves el Reto 5</td>
<td>35 min</td>
</tr>
<tr class="odd">
<td>7. Requisitos y vocabulario</td>
<td>Lees 29148 y 24765 y resuelves el Reto 6</td>
<td>30 min</td>
</tr>
<tr class="even">
<td>Cierre</td>
<td>Errores frecuentes, autoevaluación y glosario</td>
<td>30 min</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</h2>
<p>El curso usa un producto ficticio, una app que asigna turnos médicos. Su requisito de partida es “la app asigna hasta 20 turnos por día a cada especialidad”. En este tema la clínica contrata a un equipo para construir la versión 1.0 y el equipo debe decidir qué normas aplicar y cómo documentarlo. Ninguna cifra de la clínica es real. Cada número propio se marca como ilustrativo.</p>
</section>
<section id="parte-1.-quién-escribe-las-normas" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="parte-1.-quién-escribe-las-normas"><span class="header-section-number">4</span> Parte 1. Quién escribe las normas</h2>
<p>El IEEE (Institute of Electrical and Electronics Engineers) es una asociación profesional internacional. Dentro de su Computer Society trabaja el comité C/S2ESC (Software &amp; Systems Engineering Standards Committee), que según su propia página está encargado de convertir en normas las prácticas profesionales de la ingeniería de software y de sistemas, y de armonizar las normas nacionales e internacionales.</p>
<p>Ese comité mantiene dos tipos de documento. La diferencia importa porque cambia el nombre, quién revisa el texto y dónde se consulta.</p>
<ul>
<li><strong>Norma IEEE pura.</strong> La desarrolla y publica solo el IEEE. Lleva el prefijo IEEE y el año, como IEEE 730-2026.</li>
<li><strong>Norma conjunta ISO/IEC/IEEE.</strong> La desarrollan y publican el IEEE y ISO/IEC. Lleva las tres siglas, como ISO/IEC/IEEE 12207:2026. El IEEE la lista como IEEE/ISO/IEC 12207-2026 y ISO como ISO/IEC/IEEE 12207:2026. Es el mismo documento con el orden de siglas según el editor.</li>
</ul>
<p>Una norma conjunta tiene reconocimiento internacional más amplio y puede citarse en contratos entre países. Una norma pura sigue siendo válida, pero su alcance de adopción depende solo del IEEE. Algunas normas nacieron puras y después una conjunta las reemplazó, como le pasó a IEEE 829.</p>
<div class="diagrama">
<svg viewbox="0 0 760 270" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="El comité C/S2ESC del IEEE produce normas IEEE puras, como IEEE 730-2026, y normas conjuntas ISO IEC IEEE, como 12207, 29119, 29148 y 24765" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t1a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Dos tipos de norma que produce el comité de software del IEEE</text> <rect x="240" y="32" width="280" height="56" rx="12" fill="#eee8f7" stroke="#b9a6d6"></rect> <text x="380" y="56" font-size="13" font-weight="700" fill="#4a2f7a" text-anchor="middle">C/S2ESC, IEEE Computer Society</text> <text x="380" y="75" font-size="11" fill="#5b6876" text-anchor="middle">comité de normas de software y sistemas</text> <rect x="30" y="160" width="320" height="92" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="190" y="184" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Norma IEEE pura</text> <text x="190" y="204" font-size="11" fill="#5b6876" text-anchor="middle">IEEE 730-2026 (plan de SQA)</text> <text x="190" y="221" font-size="11" fill="#5b6876" text-anchor="middle">IEEE 829-2008 (sustituida)</text> <text x="190" y="238" font-size="11" fill="#5b6876" text-anchor="middle">solo la publica el IEEE</text> <rect x="410" y="160" width="320" height="92" rx="10" fill="#eee8f7" stroke="#b9a6d6"></rect> <text x="570" y="184" font-size="12.5" font-weight="700" fill="#4a2f7a" text-anchor="middle">Norma conjunta ISO/IEC/IEEE</text> <text x="570" y="204" font-size="11" fill="#5b6876" text-anchor="middle">12207, 29119, 29148, 24765</text> <text x="570" y="221" font-size="11" fill="#5b6876" text-anchor="middle">IEEE e ISO/IEC la publican juntos</text> <text x="570" y="238" font-size="11" fill="#5b6876" text-anchor="middle">el IEEE la lista como IEEE/ISO/IEC</text> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u3t1a)"><path d="M320,88 C270,115 230,138 205,158"></path><path d="M440,88 C490,115 530,138 555,158"></path></g>
</svg>
</div>
<section id="cómo-leer-el-estado-de-una-norma" class="level3">
<h3 class="anchored" data-anchor-id="cómo-leer-el-estado-de-una-norma">Cómo leer el estado de una norma</h3>
<p>Una norma tiene edición y estado, y los dos cambian con los años. Antes de citarla, mira su ficha en el sitio del editor. El IEEE usa cuatro datos que debes saber leer.</p>
<ul>
<li><strong>Estado.</strong> <em>Active</em> (vigente), <em>Superseded</em> (sustituida por otra), <em>Inactive-Reserved</em> (inactiva, el IEEE ya no la mantiene al día).</li>
<li><strong>Fecha de aprobación y de publicación.</strong> Pueden diferir meses.</li>
<li><strong>Supersedes y Superseded by.</strong> Qué edición reemplaza y por cuál fue reemplazada.</li>
<li><strong>Armonizada con.</strong> A qué otras normas se alinea su texto.</li>
</ul>
<p>El texto completo de casi todas estas normas es de pago. Esta guía se apoya en las fichas públicas del IEEE y de catálogos de normas, y en el texto de la edición 2014 de IEEE 730. Cuando algo no se pudo leer en fuente primaria, el texto lo dice.</p>
</section>
</section>
<section id="parte-2.-el-mapa-de-la-familia" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="parte-2.-el-mapa-de-la-familia"><span class="header-section-number">5</span> Parte 2. El mapa de la familia</h2>
<p>Antes de entrar a cada norma, esta tabla da el panorama. Los estados corresponden a la consulta de octubre de 2026 en las fichas del IEEE y en catálogos de ISO.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Norma</th>
<th>Para qué sirve</th>
<th>Edición vigente</th>
<th>Qué pasó con las anteriores</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>IEEE 730</td>
<td>Procesos de aseguramiento de calidad del software (SQA) y su plan</td>
<td>IEEE 730-2026, publicada el 21 de agosto de 2026</td>
<td>Sustituye a IEEE 730-2014, que el IEEE marcó inactiva el 27 de marzo de 2025</td>
</tr>
<tr class="even">
<td>ISO/IEC/IEEE 29119 (partes 1 a 5)</td>
<td>Pruebas de software: conceptos, procesos, documentación, técnicas, pruebas por palabras clave</td>
<td>Parte 1: 2022. Partes 2, 3 y 4: 2021. Parte 5: 2024</td>
<td>IEEE 829-2008 quedó sustituida por la familia 29119</td>
</tr>
<tr class="odd">
<td>ISO/IEC/IEEE 12207</td>
<td>Procesos del ciclo de vida del software</td>
<td>ISO/IEC/IEEE 12207:2026, publicada el 15 de abril de 2026</td>
<td>Sustituye a la edición de 2017</td>
</tr>
<tr class="even">
<td>ISO/IEC/IEEE 29148</td>
<td>Ingeniería de requisitos</td>
<td>Edición de 2018, publicada el 30 de noviembre de 2018</td>
<td>Sustituyó a la edición de 2011</td>
</tr>
<tr class="odd">
<td>ISO/IEC/IEEE 24765</td>
<td>Vocabulario de ingeniería de sistemas y software</td>
<td>Edición de 2017, publicada el 28 de agosto de 2017</td>
<td>Sustituyó a la edición de 2010</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Una edición vigente hoy puede no serlo mañana
</div>
</div>
<div class="callout-body-container callout-body">
<p>La guía anterior de este tema daba por buena la edición 2014 de IEEE 730 y no mencionaba la 2026. Dos normas de esta tabla cambiaron de edición en 2026, y otra, la 29148, aparece en un catálogo comercial como pendiente de revisión. En las fuentes consultadas no consta una edición posterior de 29148, pero la ausencia de ese dato no prueba que no exista. Revisa la ficha del editor cada vez que cites una edición en un documento formal.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Lee el estado de una norma
</div>
</div>
<div class="callout-body-container callout-body">
<p>El equipo de la clínica propone tres frases para su documento de calidad. Decide si son correctas a octubre de 2026.</p>
<ol type="1">
<li>“El plan de calidad sigue IEEE 730-2014, que está vigente.”</li>
<li>“La documentación de pruebas sigue IEEE 829-2008, que es el estándar actual.”</li>
<li>“El ciclo de vida se describe con ISO/IEC/IEEE 12207:2017, la edición más reciente.”</li>
</ol>
<p><label><input type="checkbox"> Las tres son correctas</label> <label><input type="checkbox"> Solo la 1 es correcta</label> <label><input type="checkbox"> Las tres son incorrectas</label></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Las tres son incorrectas. La 1: IEEE 730-2014 pasó a inactiva el 27 de marzo de 2025 y la sustituye IEEE 730-2026, publicada el 21 de agosto de 2026. La 2: IEEE 829-2008 figura como sustituida por la familia ISO/IEC/IEEE 29119, y la parte de documentación es 29119-3:2021. La 3: la edición más reciente es ISO/IEC/IEEE 12207:2026, publicada el 15 de abril de 2026.</p>
<p>Las ediciones anteriores no se vuelven falsas, pero un documento nuevo no debería citarlas como la referencia actual sin explicar por qué.</p>
</div>
</div>
</div>
</section>
<section id="parte-3.-ieee-730-aseguramiento-de-calidad-del-software" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="parte-3.-ieee-730-aseguramiento-de-calidad-del-software"><span class="header-section-number">6</span> Parte 3. IEEE 730: aseguramiento de calidad del software</h2>
<p>La Unidad 2 definió el SQA como el conjunto de actividades que da confianza en que el software cumple sus requisitos. IEEE 730 es la norma que dice qué procesos de SQA debe tener un proyecto de desarrollo o de mantenimiento y qué debe contener el plan que los organiza. El propósito declarado en la edición 2014 es producir y reunir la evidencia que sustenta una declaración justificada de confianza en que el producto cumple sus requisitos.</p>
<section id="historia-en-pocas-líneas" class="level3">
<h3 class="anchored" data-anchor-id="historia-en-pocas-líneas">Historia en pocas líneas</h3>
<ul>
<li><strong>Hasta 2002.</strong> La norma se centraba en el formato del documento del plan.</li>
<li><strong>IEEE 730-2002.</strong> Edición que la de 2014 sustituyó.</li>
<li><strong>IEEE 730-2014.</strong> Cambia el título a “Software Quality Assurance Processes” y pasa de describir un documento a exigir procesos. Aprobada el 27 de marzo de 2014 y publicada el 13 de junio de 2014.</li>
<li><strong>IEEE 730-2026.</strong> Aprobada por la junta del IEEE el 12 de febrero de 2026 y publicada el 21 de agosto de 2026. Su ficha indica que sustituye a la de 2014 y que se armoniza con ISO/IEC/IEEE 12207:2017, IEEE 2675-2021 e ISO/IEC/IEEE 15289:2019.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Lo que no se pudo verificar de la edición 2026
</div>
</div>
<div class="callout-body-container callout-body">
<p>El texto de IEEE 730-2026 es de pago y no se pudo leer. La ficha pública confirma su vigencia, sus fechas y su armonización, pero no su lista de actividades. Todo el detalle de las partes siguientes (áreas, 16 actividades, esquema del plan) corresponde a la edición 2014. Antes de afirmar conformidad con la edición 2026, contrasta cada punto con el texto de esa edición.</p>
</div>
</div>
</section>
<section id="a-quién-aplica" class="level3">
<h3 class="anchored" data-anchor-id="a-quién-aplica">A quién aplica</h3>
<p>La edición 2014 declara que no se restringe por tamaño, complejidad, criticidad ni aplicación del software. Se aplica a productos nuevos, a mantenimiento y a integración, y a software que forma parte de un sistema o que se vende solo. Quien dice que “IEEE 730 es solo para software crítico” repite una idea que el texto de 2014 no sostiene. Lo que sí hace la norma es pedir que el esfuerzo de SQA sea proporcional al riesgo del producto.</p>
</section>
<section id="tres-áreas-y-16-actividades" class="level3">
<h3 class="anchored" data-anchor-id="tres-áreas-y-16-actividades">Tres áreas y 16 actividades</h3>
<p>La norma organiza el trabajo en tres áreas. Las actividades de cada área llevan un propósito, resultados esperados y tareas.</p>
<div class="diagrama">
<svg viewbox="0 0 760 280" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="IEEE 730-2014 organiza el SQA en tres areas: implementacion del proceso con seis actividades, aseguramiento de producto con cinco y aseguramiento de proceso con cinco. Las tres producen evidencia en los registros de SQA" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t1b" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Las tres areas de IEEE 730-2014: 6 + 5 + 5 = 16 actividades</text> <rect x="20" y="40" width="220" height="100" rx="10" fill="#fdf3d0" stroke="#e3c768"></rect> <text x="130" y="64" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Implementacion del proceso</text> <text x="130" y="84" font-size="11" fill="#5b6876" text-anchor="middle">6 actividades</text> <text x="130" y="102" font-size="11" fill="#5b6876" text-anchor="middle">organizar el SQA, planificar,</text> <text x="130" y="118" font-size="11" fill="#5b6876" text-anchor="middle">ejecutar, guardar registros</text> <rect x="270" y="40" width="220" height="100" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="380" y="64" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Aseguramiento de producto</text> <text x="380" y="84" font-size="11" fill="#5b6876" text-anchor="middle">5 actividades</text> <text x="380" y="102" font-size="11" fill="#5b6876" text-anchor="middle">evalua si el producto y su</text> <text x="380" y="118" font-size="11" fill="#5b6876" text-anchor="middle">documentacion cumplen</text> <rect x="520" y="40" width="220" height="100" rx="10" fill="#fdf3d0" stroke="#e3c768"></rect> <text x="630" y="64" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Aseguramiento de proceso</text> <text x="630" y="84" font-size="11" fill="#5b6876" text-anchor="middle">5 actividades</text> <text x="630" y="102" font-size="11" fill="#5b6876" text-anchor="middle">evalua si el proceso, el entorno,</text> <text x="630" y="118" font-size="11" fill="#5b6876" text-anchor="middle">el proveedor y el personal cumplen</text> <rect x="250" y="196" width="260" height="62" rx="12" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="222" font-size="12.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Evidencia: plan y registros de SQA</text> <text x="380" y="241" font-size="11" fill="#3c7d7a" text-anchor="middle">base de la confianza en la conformidad</text> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u3t1b)"><path d="M130,140 C190,168 290,184 330,194"></path><path d="M380,140 L380,194"></path><path d="M630,140 C570,168 470,184 430,194"></path></g>
</svg>
</div>
<p>La tabla siguiente lista las 16 actividades de la edición 2014 con el propósito de cada una, resumido con palabras propias.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Cláusula</th>
<th>Actividad</th>
<th>Para qué sirve</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5.3.1</td>
<td>Establecer los procesos de SQA</td>
<td>La organización define, antes del proyecto, el papel del SQA y una política de calidad que lo gobierna</td>
</tr>
<tr class="even">
<td>5.3.2</td>
<td>Coordinar con procesos relacionados</td>
<td>El SQA acuerda con la gerencia cuáles procesos del ciclo de vida (verificación, validación, revisión, auditoría) se coordinan con él</td>
</tr>
<tr class="odd">
<td>5.3.3</td>
<td>Documentar la planificación del SQA</td>
<td>Se escribe el plan (SQAP) adaptado al riesgo del producto</td>
</tr>
<tr class="even">
<td>5.3.4</td>
<td>Ejecutar el plan de SQA</td>
<td>Se hace lo planificado, se levantan no conformidades y se revisa el plan cuando el proyecto cambia</td>
</tr>
<tr class="odd">
<td>5.3.5</td>
<td>Gestionar los registros de SQA</td>
<td>Se crean, protegen y entregan los registros que prueban que el SQA se hizo</td>
</tr>
<tr class="even">
<td>5.3.6</td>
<td>Evaluar independencia y objetividad</td>
<td>Se confirma que quien hace SQA tiene libertad y autoridad para evaluar sin presiones</td>
</tr>
<tr class="odd">
<td>5.4.2</td>
<td>Evaluar planes frente a contratos, normas y regulaciones</td>
<td>Los planes existen, cumplen el contrato y las leyes, y son coherentes entre sí</td>
</tr>
<tr class="even">
<td>5.4.3</td>
<td>Evaluar el producto frente a los requisitos</td>
<td>Se mide cuánto cumplen el software y su documentación los requisitos establecidos</td>
</tr>
<tr class="odd">
<td>5.4.4</td>
<td>Evaluar la aceptabilidad del producto</td>
<td>Antes de entregar, se mide la confianza del proveedor en que el cliente lo aceptará</td>
</tr>
<tr class="even">
<td>5.4.5</td>
<td>Evaluar el soporte del ciclo de vida del producto</td>
<td>El soporte prometido coincide con el contrato y fija responsabilidades</td>
</tr>
<tr class="odd">
<td>5.4.6</td>
<td>Medir los productos</td>
<td>Las mediciones del producto demuestran su calidad y siguen los procedimientos del proyecto</td>
</tr>
<tr class="even">
<td>5.5.2</td>
<td>Evaluar procesos y planes del ciclo de vida</td>
<td>El trabajo real sigue el proceso y los planes definidos</td>
</tr>
<tr class="odd">
<td>5.5.3</td>
<td>Evaluar los entornos</td>
<td>Los entornos de ingeniería y de prueba son los que el plan indica</td>
</tr>
<tr class="even">
<td>5.5.4</td>
<td>Evaluar los procesos de subcontratistas</td>
<td>Los proveedores cumplen los requisitos de proceso que se les trasladaron</td>
</tr>
<tr class="odd">
<td>5.5.5</td>
<td>Medir los procesos</td>
<td>Las mediciones de proceso apoyan una gestión efectiva</td>
</tr>
<tr class="even">
<td>5.5.6</td>
<td>Evaluar habilidades y conocimientos del personal</td>
<td>Se detectan brechas de formación frente a lo que cada rol necesita</td>
</tr>
</tbody>
</table>
</section>
<section id="independencia-tres-parámetros" class="level3">
<h3 class="anchored" data-anchor-id="independencia-tres-parámetros">Independencia: tres parámetros</h3>
<p>La actividad 5.3.6 define la independencia del SQA con tres parámetros. La independencia técnica pide personas que no participaron en el desarrollo. La independencia gerencial pide que el SQA pertenezca a una organización distinta de la que desarrolla y de la dirección del programa. La independencia financiera pide que el presupuesto del SQA lo controle una organización ajena al desarrollo. En un equipo pequeño es difícil cumplir los tres, y por eso la norma permite declarar con claridad lo que no se cumple, como verás en la Parte 4.</p>
</section>
<section id="conformidad-completa-o-ajustada" class="level3">
<h3 class="anchored" data-anchor-id="conformidad-completa-o-ajustada">Conformidad completa o ajustada</h3>
<p>La norma admite dos formas de declarar conformidad. La completa exige demostrar todos los requisitos del capítulo 5 con sus resultados como evidencia. La ajustada permite limitar el alcance de las actividades de producto y de proceso a lo que el proyecto hace. En ese caso, cada actividad que no se ejecuta se registra en el plan como “no aplica” con su justificación. Callar una actividad no cuenta como ajuste.</p>
</section>
<section id="qué-lleva-el-plan-sqap" class="level3">
<h3 class="anchored" data-anchor-id="qué-lleva-el-plan-sqap">Qué lleva el plan (SQAP)</h3>
<p>La edición 2014 pide que el plan cubra todos los temas de un esquema, pero deja el nombre y el orden de las secciones como informativos. El esquema tiene siete bloques.</p>
<ol type="1">
<li>Propósito y alcance.</li>
<li>Definiciones y siglas.</li>
<li>Documentos de referencia.</li>
<li>Visión general del plan: organización e independencia, riesgo del producto, herramientas, normas, prácticas y convenciones, y esfuerzo, recursos y cronograma.</li>
<li>Actividades, resultados y tareas: aseguramiento de producto y aseguramiento de proceso.</li>
<li>Consideraciones adicionales: revisión de contratos, medición de calidad, excepciones y desviaciones, repetición de tareas, riesgo de ejecutar el SQA, estrategia de comunicación y proceso de no conformidades.</li>
<li>Registros de SQA: cómo se recogen, guardan y se ponen a disposición.</li>
</ol>
<p>Si una sección no aplica, el plan incluye un marcador con la justificación.</p>
</section>
</section>
<section id="parte-4.-ejemplo-resuelto-el-sqap-de-la-clínica" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="parte-4.-ejemplo-resuelto-el-sqap-de-la-clínica"><span class="header-section-number">7</span> Parte 4. Ejemplo resuelto: el SQAP de la clínica</h2>
<p>El equipo de la clínica tiene cinco desarrolladores y 12 semanas para entregar la versión 1.0. El plan siguiente es una muestra didáctica, escrita con el esquema de la edición 2014. Todos los números son ilustrativos y la norma no fija porcentajes de esfuerzo.</p>
<section id="paso-1.-alcance-y-riesgo-del-producto" class="level3">
<h3 class="anchored" data-anchor-id="paso-1.-alcance-y-riesgo-del-producto">Paso 1. Alcance y riesgo del producto</h3>
<p>Primero se decide qué cubre el plan y cuánto riesgo tiene cada módulo, porque la norma pide que el esfuerzo de SQA sea proporcional al riesgo.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Módulo</th>
<th>Qué pasa si falla</th>
<th>Riesgo</th>
<th>Esfuerzo de SQA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Asignación de turnos</td>
<td>Turnos duplicados o sobrecupo, pacientes sin atención</td>
<td>Alto</td>
<td>Evaluación en cada entrega</td>
</tr>
<tr class="even">
<td>Historia y datos del paciente</td>
<td>Fuga de datos de salud, que la Ley 1581 de 2012 trata como sensibles</td>
<td>Alto</td>
<td>Evaluación en cada entrega</td>
</tr>
<tr class="odd">
<td>Recordatorios por mensaje</td>
<td>Paciente no se entera de su cita</td>
<td>Medio</td>
<td>Evaluación quincenal</td>
</tr>
<tr class="even">
<td>Reportes administrativos</td>
<td>Cifras equivocadas para la gerencia</td>
<td>Bajo</td>
<td>Evaluación al cierre</td>
</tr>
</tbody>
</table>
</section>
<section id="paso-2.-esfuerzo" class="level3">
<h3 class="anchored" data-anchor-id="paso-2.-esfuerzo">Paso 2. Esfuerzo</h3>
<p>El proyecto suma 5 personas x 12 semanas x 40 horas = 2.400 horas. El equipo decide reservar el 8 % para SQA: 2.400 x 0,08 = 192 horas. Reparte esas horas por áreas de la norma.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Área</th>
<th>Horas</th>
<th>Qué cubre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Implementación del proceso</td>
<td>48</td>
<td>Plan, coordinación, registros, informe semanal</td>
</tr>
<tr class="even">
<td>Aseguramiento de producto</td>
<td>80</td>
<td>Revisión de requisitos, de casos de prueba y del producto antes de cada entrega</td>
</tr>
<tr class="odd">
<td>Aseguramiento de proceso</td>
<td>64</td>
<td>Auditorías de proceso, del entorno de pruebas y del proveedor de mensajería</td>
</tr>
<tr class="even">
<td>Total</td>
<td>192</td>
<td>48 + 80 + 64 = 192</td>
</tr>
</tbody>
</table>
</section>
<section id="paso-3.-independencia" class="level3">
<h3 class="anchored" data-anchor-id="paso-3.-independencia">Paso 3. Independencia</h3>
<p>Con cinco desarrolladores no hay un área de SQA propia. El plan asigna el rol a una persona de otro equipo de la clínica (independencia técnica), que informa a la Dirección de Calidad y no al líder del proyecto (independencia gerencial). El presupuesto de esas horas lo maneja la Dirección de Calidad (independencia financiera). Si la clínica no pudiera dar esa persona, el plan debería escribir qué parámetro queda sin cumplir y qué riesgo trae.</p>
</section>
<section id="paso-4.-el-plan-sección-por-sección" class="level3">
<h3 class="anchored" data-anchor-id="paso-4.-el-plan-sección-por-sección">Paso 4. El plan, sección por sección</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Plan de aseguramiento de calidad del software, Turnos Aurora v1.0
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>1. Propósito y alcance.</strong> Este plan organiza el SQA de la versión 1.0 de la app de turnos: aplicación web, servicio de asignación y módulo de recordatorios. Queda fuera la integración con el sistema hospitalario, prevista para la versión 2.0.</p>
<p><strong>2. Definiciones y siglas.</strong> SQA, SQAP, no conformidad (NC) y criticidad A, B y C se definen en el glosario del proyecto.</p>
<p><strong>3. Documentos de referencia.</strong> IEEE 730 (guía del plan), ISO/IEC/IEEE 12207 (mapa de procesos), ISO/IEC/IEEE 29148 (formato de requisitos), ISO/IEC/IEEE 29119-3 (documentos de prueba), Ley 1581 de 2012 y el contrato con el proveedor de mensajería.</p>
<p><strong>4. Visión general.</strong></p>
<ul>
<li>Organización e independencia: la responsable de SQA es una analista de la Dirección de Calidad, ajena al equipo. Informa semanalmente a la gerencia de la clínica.</li>
<li>Riesgo del producto: tabla del Paso 1.</li>
<li>Herramientas: gestor de incidencias, repositorio con revisión de cambios y servidor de integración continua.</li>
<li>Normas y convenciones: requisitos en la forma de 29148, documentos de prueba con las plantillas de 29119-3 y lista de chequeo de revisión de código de la clínica.</li>
<li>Esfuerzo y cronograma: 192 horas, repartidas según el Paso 2. Hitos de evaluación al final de las semanas 4, 8 y 12.</li>
</ul>
<p><strong>5. Actividades, resultados y tareas.</strong></p>
<ul>
<li>Aseguramiento de producto: revisar los 34 requisitos con el formato de 29148 antes de la semana 2. Verificar que cada requisito de criticidad A tenga al menos un caso de prueba. Evaluar el producto contra los requisitos antes de cada entrega.</li>
<li>Aseguramiento de proceso: auditar una vez por hito que las revisiones de código ocurran, que el entorno de pruebas coincida con el plan y que el proveedor de mensajería cumpla lo pactado.</li>
</ul>
<p><strong>6. Consideraciones adicionales.</strong></p>
<ul>
<li>Revisión de contratos: el SQA lee el contrato del proveedor de mensajería antes de integrarlo.</li>
<li>Medición de calidad: porcentaje de requisitos con caso de prueba (meta 100 % en criticidad A) e incidencias críticas abiertas (meta 0 para entregar).</li>
<li>Excepciones: se aceptan solo por escrito, con firma de la gerencia y fecha de cierre.</li>
<li>Riesgo de ejecutar el SQA: si la analista se ausenta más de una semana, la Dirección de Calidad nombra reemplazo en 2 días hábiles.</li>
<li>Comunicación: informe semanal de una página a la gerencia y al líder del proyecto.</li>
<li>No conformidades: se registran en el gestor con criticidad. Las críticas se atienden antes de la siguiente entrega.</li>
</ul>
<p><strong>7. Registros de SQA.</strong> Informes semanales, listas de chequeo diligenciadas, actas de auditoría y reportes de no conformidad se guardan en la carpeta del proyecto de la Dirección de Calidad, de solo lectura para el equipo, durante 2 años después de la entrega.</p>
</div>
</div>
</section>
<section id="paso-5.-una-medición-de-ejemplo" class="level3">
<h3 class="anchored" data-anchor-id="paso-5.-una-medición-de-ejemplo">Paso 5. Una medición de ejemplo</h3>
<p>A la semana 4 el SQA cuenta 34 requisitos, de los cuales 31 tienen al menos un caso de prueba. La cobertura es 31 / 34 = 0,912, es decir 91,2 %. Para los de criticidad A, 12 en total, hay 11 con caso de prueba, 11 / 12 = 91,7 %. La meta de la sección 6 es 100 % en criticidad A, así que el SQA levanta una no conformidad por el requisito sin caso y la registra con fecha de cierre.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Ajusta el plan a un proyecto más pequeño
</div>
</div>
<div class="callout-body-container callout-body">
<p>La clínica pide un módulo adicional: un tablero de reportes. Lo construyen 3 personas durante 8 semanas de 40 horas. Reservan el 10 % para SQA. Calcula el total de horas de SQA y reparte esas horas así: 25 % en implementación del proceso, 40 % en producto y el resto en proceso. Después decide qué parámetros de independencia puede cumplir si solo hay una analista de calidad que trabaja en otro proyecto de la clínica.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Horas del proyecto: 3 x 8 x 40 = 960. Horas de SQA: 960 x 0,10 = 96.</p>
<p>Reparto: implementación 96 x 0,25 = 24 horas, producto 96 x 0,40 = 38,4 horas, y proceso el 35 % restante, 96 x 0,35 = 33,6 horas. La suma es 24 + 38,4 + 33,6 = 96 horas. Si prefieres números enteros, redondea a 24, 38 y 34.</p>
<p>Independencia: la analista pertenece a otro proyecto, así que cumple la técnica. Si informa a la Dirección de Calidad cumple la gerencial. Si la Dirección de Calidad maneja su presupuesto cumple la financiera. Si el presupuesto lo controla el líder del tablero, no se cumple la financiera y el plan debe declararlo, con el riesgo que implica.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. Detecta lo que falta en un fragmento de plan
</div>
</div>
<div class="callout-body-container callout-body">
<p>Este es el borrador del plan de otro equipo de la clínica: “El plan se aplicará al sistema de laboratorio. La calidad la revisa el líder del proyecto cuando termina. Si algo falla, se corrige.” Escribe, usando las siete secciones de la norma, tres secciones que faltan y qué contendría cada una.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Respuestas posibles, mientras conecten la sección con su contenido:</p>
<ul>
<li>Organización e independencia: el líder del proyecto no puede ser quien evalúa su propio trabajo. Falta nombrar a una persona o un área independiente.</li>
<li>Riesgo del producto: falta identificar qué módulos del laboratorio pueden dañar al paciente si fallan y proporcionar el esfuerzo de SQA a ese riesgo.</li>
<li>Proceso de no conformidades y registros: “se corrige” no deja evidencia. Falta definir cómo se registra, quién la cierra y cuánto tiempo se guarda el registro.</li>
</ul>
<p>También faltan las actividades de producto y de proceso con su frecuencia y las mediciones que demuestren calidad.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-5.-documentar-las-pruebas-de-ieee-829-a-isoiecieee-29119" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="parte-5.-documentar-las-pruebas-de-ieee-829-a-isoiecieee-29119"><span class="header-section-number">8</span> Parte 5. Documentar las pruebas: de IEEE 829 a ISO/IEC/IEEE 29119</h2>
<p>Probar y documentar la prueba son dos tareas distintas. Sin un registro de qué se probó, con qué datos y con qué resultado, nadie más que quien ejecutó la prueba puede confiar en ella, ni repetirla cuando un defecto se corrige.</p>
<section id="qué-fue-ieee-829-y-qué-le-pasó" class="level3">
<h3 class="anchored" data-anchor-id="qué-fue-ieee-829-y-qué-le-pasó">Qué fue IEEE 829 y qué le pasó</h3>
<p>IEEE 829 fue la norma de documentación de pruebas. La ficha del IEEE muestra que la edición 2008 se aprobó el 27 de marzo de 2008 y sustituyó a la de 1998. Hoy figura como <em>Superseded</em> (sustituida) por las partes 1, 2 y 3 de ISO/IEC/IEEE 29119 en su edición de 2013 y por la parte 4 de 2015. Esas ediciones fueron a su vez reemplazadas por las de 2021 y 2022 que muestra la Parte 2.</p>
<p>La familia 29119 empezó a desarrollarse en 2007 a partir de IEEE 829, de IEEE 1008 (pruebas unitarias) y de las normas británicas BS 7925-1 y BS 7925-2, según la referencia consultada. La primera edición se publicó en 2013.</p>
</section>
<section id="las-partes-de-isoiecieee-29119" class="level3">
<h3 class="anchored" data-anchor-id="las-partes-de-isoiecieee-29119">Las partes de ISO/IEC/IEEE 29119</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Parte</th>
<th>Tema</th>
<th>Edición</th>
<th>Nota</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>29119-1</td>
<td>Conceptos y definiciones</td>
<td>2022</td>
<td>Vocabulario base</td>
</tr>
<tr class="even">
<td>29119-2</td>
<td>Procesos de prueba</td>
<td>2021</td>
<td>Procesos organizacionales y de gestión de pruebas</td>
</tr>
<tr class="odd">
<td>29119-3</td>
<td>Documentación de pruebas</td>
<td>2021</td>
<td>Reemplaza a 29119-3:2013 y hereda el papel de IEEE 829</td>
</tr>
<tr class="even">
<td>29119-4</td>
<td>Técnicas de prueba</td>
<td>2021</td>
<td>De especificación, de estructura y de experiencia</td>
</tr>
<tr class="odd">
<td>29119-5</td>
<td>Pruebas por palabras clave</td>
<td>2024</td>
<td>Segunda edición, diciembre de 2024. La edición de 2016 se retiró</td>
</tr>
<tr class="even">
<td>29119-6</td>
<td>Uso de la norma en contextos ágiles</td>
<td>2021</td>
<td>Informe técnico, según un sitio secundario</td>
</tr>
<tr class="odd">
<td>29119-11</td>
<td>Pruebas de sistemas basados en IA</td>
<td>2020</td>
<td>Informe técnico, según un sitio secundario</td>
</tr>
</tbody>
</table>
<p>Las filas de las partes 6 y 11 se apoyan en un sitio de referencia secundario, no en una ficha de ISO. Verifica en iso.org antes de citarlas. Las demás filas se apoyan en catálogos nacionales de normas y en la ficha del IEEE.</p>
</section>
<section id="los-documentos-de-la-parte-3" class="level3">
<h3 class="anchored" data-anchor-id="los-documentos-de-la-parte-3">Los documentos de la parte 3</h3>
<p>29119-3 define plantillas para tres niveles. El texto de pago no se pudo leer, así que la lista siguiente se basa en la estructura conocida de la parte 3 y debe contrastarse con la edición 2021.</p>
<div class="diagrama">
<svg viewbox="0 0 760 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Los documentos de prueba de ISO IEC IEEE 29119-3 en tres niveles: organizacional con politica y estrategia, gestion de pruebas con plan, informe de estado e informe de cierre, y pruebas dinamicas con diseno, casos, procedimiento, datos, ambiente, resultados, registro e incidencias" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t1c" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Tres niveles de documentos de prueba en 29119-3</text> <rect x="40" y="34" width="680" height="62" rx="10" fill="#eee8f7" stroke="#b9a6d6"></rect> <text x="380" y="58" font-size="12.5" font-weight="700" fill="#4a2f7a" text-anchor="middle">Nivel organizacional</text> <text x="380" y="78" font-size="11.5" fill="#5b6876" text-anchor="middle">politica de pruebas y estrategia de pruebas de la organizacion</text> <rect x="40" y="120" width="680" height="62" rx="10" fill="#fdf3d0" stroke="#e3c768"></rect> <text x="380" y="144" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Gestion de pruebas del proyecto</text> <text x="380" y="164" font-size="11.5" fill="#5b6876" text-anchor="middle">plan de pruebas, informe de estado, informe de cierre</text> <rect x="40" y="206" width="680" height="96" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="380" y="230" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Pruebas dinamicas</text> <text x="380" y="252" font-size="11.5" fill="#5b6876" text-anchor="middle">diseno de pruebas, casos, procedimiento, requisitos y estado de datos y de ambiente</text> <text x="380" y="272" font-size="11.5" fill="#5b6876" text-anchor="middle">resultado real, registro de ejecucion, informe de incidencia</text> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u3t1c)"><path d="M380,96 L380,118"></path><path d="M380,182 L380,204"></path></g> <text x="380" y="322" font-size="11" fill="#5b6876" text-anchor="middle">de lo general a lo concreto: cada nivel se apoya en el de arriba</text>
</svg>
</div>
<p>Cada documento responde una pregunta.</p>
<ul>
<li><strong>Política y estrategia de pruebas.</strong> Cómo prueba la organización en general.</li>
<li><strong>Plan de pruebas.</strong> Qué, cuándo, quién y con qué criterios se prueba en este proyecto.</li>
<li><strong>Informe de estado.</strong> Cómo va la prueba en una fecha.</li>
<li><strong>Informe de cierre.</strong> Qué se logró y qué quedó pendiente al terminar.</li>
<li><strong>Diseño y casos de prueba.</strong> Qué se prueba y con qué entradas y resultados esperados.</li>
<li><strong>Procedimiento de prueba.</strong> Pasos para ejecutarlos.</li>
<li><strong>Datos y ambiente.</strong> Qué necesita la prueba y si está listo.</li>
<li><strong>Resultado real y registro de ejecución.</strong> Lo que ocurrió.</li>
<li><strong>Informe de incidencia.</strong> Un resultado inesperado que hay que investigar.</li>
</ul>
</section>
<section id="ejemplo-resuelto-documentos-de-prueba-para-el-límite-de-20-turnos" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-documentos-de-prueba-para-el-límite-de-20-turnos">Ejemplo resuelto: documentos de prueba para el límite de 20 turnos</h3>
<p>El requisito de la clínica es “la app asigna hasta 20 turnos por día a cada especialidad”. Un requisito con un límite numérico pide probar los valores del borde.</p>
<p><strong>Diseño.</strong> Técnica de análisis de valores límite, del grupo de técnicas de especificación de la parte 4. Valores: 0 turnos, 19 turnos y 20 turnos ya asignados, más un caso de concurrencia.</p>
<p><strong>Casos de prueba.</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Caso</th>
<th>Estado de partida</th>
<th>Acción</th>
<th>Resultado esperado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TC-01</td>
<td>Cardiología con 0 turnos</td>
<td>Una paciente pide turno</td>
<td>Se asigna, total 1</td>
</tr>
<tr class="even">
<td>TC-02</td>
<td>Cardiología con 19 turnos</td>
<td>Una paciente pide turno</td>
<td>Se asigna, total 20</td>
</tr>
<tr class="odd">
<td>TC-03</td>
<td>Cardiología con 20 turnos</td>
<td>Una paciente pide turno</td>
<td>Se rechaza con mensaje de cupo agotado, total 20</td>
</tr>
<tr class="even">
<td>TC-04</td>
<td>Cardiología con 19 turnos</td>
<td>Dos pacientes piden turno al mismo tiempo</td>
<td>Se asigna exactamente uno, total 20</td>
</tr>
</tbody>
</table>
<p><strong>Ejecución y resultado real.</strong> TC-01, TC-02 y TC-03 pasan. En TC-04 las dos solicitudes quedan asignadas y el total llega a 21. El probador abre la incidencia INC-014, de severidad alta, con los pasos y el resultado real.</p>
<p><strong>Informe de cierre del nivel.</strong> Se planearon y ejecutaron 4 casos. Pasaron 3 y falló 1, con 1 incidencia abierta de severidad alta. El criterio de salida decía “ninguna incidencia alta abierta”, así que el informe concluye que el módulo todavía no está listo.</p>
<p>Fíjate en lo que aportan los documentos. El informe de incidencia permite reproducir el defecto, y el informe de cierre conecta ese defecto con la decisión de no entregar.</p>
</section>
<section id="una-discusión-sobre-29119" class="level3">
<h3 class="anchored" data-anchor-id="una-discusión-sobre-29119">Una discusión sobre 29119</h3>
<p>Desde 2014, parte de la comunidad de pruebas, agrupada en torno a la Association for Software Testing y la International Society for Software Testing, impulsó una petición contra 29119. Alegaban que no reflejaba un consenso real de quienes prueban software y que su peso en la documentación restaría tiempo a probar. La discusión sirve para recordar que un documento vale por lo que ayuda a encontrar y corregir defectos, no por haberse llenado.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 4. Qué documento falta
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un equipo ejecuta sus pruebas y al final del nivel solo conserva un informe que dice “todo bien”. Nadie sabe qué datos se usaron, qué entorno se probó ni qué pasó con un fallo intermitente que alguien mencionó en el chat. Nombra tres documentos de 29119-3 que habrían evitado el problema y di qué pregunta contesta cada uno.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Registro de ejecución y resultado real: dice qué se ejecutó, en qué orden y qué ocurrió, y evita que “todo bien” sea la única evidencia.</li>
<li>Informe de incidencia: el fallo intermitente debió quedar registrado con sus pasos y su frecuencia, y no solo mencionado en un chat.</li>
<li>Requisitos y estado del ambiente de prueba, y de los datos: responden con qué entorno y con qué datos se probó, para repetir la prueba.</li>
</ul>
<p>También sirve el informe de cierre, que obliga a declarar lo pendiente y no solo lo aprobado.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-6.-isoiecieee-12207-el-mapa-del-ciclo-de-vida" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="parte-6.-isoiecieee-12207-el-mapa-del-ciclo-de-vida"><span class="header-section-number">9</span> Parte 6. ISO/IEC/IEEE 12207: el mapa del ciclo de vida</h2>
<p>IEEE 730, la documentación de pruebas y la gestión de configuración son piezas concretas. Ninguna dice por sí sola cuándo ocurre cada una dentro de un proyecto. Ese mapa lo da ISO/IEC/IEEE 12207, la norma de procesos del ciclo de vida del software.</p>
<section id="historia-en-pocas-líneas-1" class="level3">
<h3 class="anchored" data-anchor-id="historia-en-pocas-líneas-1">Historia en pocas líneas</h3>
<ul>
<li><strong>1995.</strong> Primera edición como norma ISO/IEC.</li>
<li><strong>2008.</strong> Edición armonizada con el IEEE, ya como norma conjunta.</li>
<li><strong>2017.</strong> Edición alineada con la norma de sistemas ISO/IEC/IEEE 15288.</li>
<li><strong>2026.</strong> ISO/IEC/IEEE 12207:2026, publicada el 15 de abril de 2026 según la ficha del IEEE, que indica que sustituye a la de 2017 y que se alinea con ISO/IEC/IEEE 15288:2023.</li>
</ul>
<p>La ficha del IEEE indica que el marco soporta la aplicación concurrente, iterativa y recursiva de los procesos. Un resumen de un distribuidor de normas señala como cambios la descripción más precisa de iteración y recursión, contenido nuevo sobre definición del concepto y del sistema, y más contenido sobre métodos ágiles. Ese resumen no es fuente primaria, así que el detalle debe confirmarse en la norma.</p>
</section>
<section id="qué-hace-y-qué-no-hace" class="level3">
<h3 class="anchored" data-anchor-id="qué-hace-y-qué-no-hace">Qué hace y qué no hace</h3>
<p>12207 define procesos, actividades y tareas que se aplican al adquirir, suministrar, desarrollar, operar, mantener y retirar software. No impone un modelo de ciclo de vida. Una organización puede usar cascada, iterativo o ágil y seguir aplicando los mismos procesos. Su propósito es dar un vocabulario y un marco común, no prescribir cómo se organiza el trabajo en el tiempo.</p>
</section>
<section id="los-cuatro-grupos-de-procesos" class="level3">
<h3 class="anchored" data-anchor-id="los-cuatro-grupos-de-procesos">Los cuatro grupos de procesos</h3>
<div class="diagrama">
<svg viewbox="0 0 760 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="12207 organiza los procesos del ciclo de vida en cuatro grupos: acuerdo, habilitadores de proyecto de la organizacion, gestion tecnica y tecnicos. Se ubican IEEE 730 en gestion tecnica, 29119 en verificacion y validacion y 29148 en requisitos" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t1d" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Los cuatro grupos de procesos de 12207 y las normas que los detallan</text> <rect x="290" y="130" width="180" height="62" rx="12" fill="#eee8f7" stroke="#b9a6d6"></rect> <text x="380" y="158" font-size="13" font-weight="700" fill="#4a2f7a" text-anchor="middle">ISO/IEC/IEEE</text> <text x="380" y="176" font-size="13" font-weight="700" fill="#4a2f7a" text-anchor="middle">12207:2026</text> <rect x="14" y="40" width="250" height="80" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="139" y="64" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Procesos de acuerdo</text> <text x="139" y="84" font-size="11" fill="#5b6876" text-anchor="middle">adquisicion y suministro</text> <text x="139" y="101" font-size="11" fill="#5b6876" text-anchor="middle">entre quien pide y quien construye</text> <rect x="496" y="40" width="250" height="80" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="621" y="64" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Habilitadores de la organizacion</text> <text x="621" y="84" font-size="11" fill="#5b6876" text-anchor="middle">calidad, personas, infraestructura</text> <text x="621" y="101" font-size="11" fill="#5b6876" text-anchor="middle">y conocimiento para todos los proyectos</text> <rect x="14" y="214" width="250" height="100" rx="10" fill="#fdf3d0" stroke="#e3c768"></rect> <text x="139" y="238" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Gestion tecnica</text> <text x="139" y="258" font-size="11" fill="#5b6876" text-anchor="middle">planificacion, riesgos, configuracion,</text> <text x="139" y="275" font-size="11" fill="#5b6876" text-anchor="middle">medicion y aseguramiento de calidad</text> <text x="139" y="296" font-size="11" font-weight="600" fill="#4a2f7a" text-anchor="middle">aqui encaja IEEE 730</text> <rect x="496" y="214" width="250" height="100" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="621" y="238" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Procesos tecnicos</text> <text x="621" y="258" font-size="11" fill="#5b6876" text-anchor="middle">requisitos, arquitectura, diseno, construccion,</text> <text x="621" y="275" font-size="11" fill="#5b6876" text-anchor="middle">verificacion, validacion, operacion, retiro</text> <text x="621" y="296" font-size="11" font-weight="600" fill="#4a2f7a" text-anchor="middle">aqui 29148 y 29119</text> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u3t1d)"><path d="M310,132 C270,112 230,100 200,96"></path><path d="M450,132 C490,112 530,100 560,96"></path><path d="M310,190 C270,206 235,218 205,222"></path><path d="M450,190 C490,206 525,218 555,222"></path></g>
</svg>
</div>
<ul>
<li><strong>Procesos de acuerdo.</strong> Formalizan la relación entre quien adquiere el software y quien lo suministra: contratos, entregas y aceptación.</li>
<li><strong>Procesos habilitadores de la organización.</strong> Aplican a toda la organización y no a un proyecto: política de calidad, gestión de personas, infraestructura y conocimiento.</li>
<li><strong>Procesos de gestión técnica.</strong> Dirigen y controlan un proyecto concreto: planificación, evaluación y control, riesgos, configuración, información, medición y aseguramiento de calidad.</li>
<li><strong>Procesos técnicos.</strong> Construyen el producto: definir necesidades y requisitos, arquitectura, diseño, implementación, integración, verificación, transición, validación, operación, mantenimiento y disposición final.</li>
</ul>
<p>El detalle de los nombres de procesos por grupo corresponde a la estructura de 12207 y 15288, que es texto de pago. La edición 2014 de IEEE 730 se armonizaba con la edición 2008 de 12207, y la 2026 declara armonía con la de 2017. Esa diferencia muestra que dos normas pueden estar un paso fuera de fase y conviene mirar la edición de cada una.</p>
</section>
<section id="cómo-usar-el-mapa" class="level3">
<h3 class="anchored" data-anchor-id="cómo-usar-el-mapa">Cómo usar el mapa</h3>
<p>Cuando alguien propone una práctica de calidad, 12207 permite preguntar en qué grupo vive. Si es una auditoría del proceso, vive en gestión técnica y la detalla IEEE 730. Si es probar, vive en procesos técnicos (verificación y validación) y la documenta 29119. Si es escribir requisitos, vive en procesos técnicos y la detalla 29148.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 5. Ubica cada actividad en su grupo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una empresa que desarrolla para la clínica firma un contrato de outsourcing con otra para construir el módulo de recordatorios. Define una política de calidad para todos sus proyectos. Una analista prepara el plan de SQA de este proyecto. El equipo levanta los requisitos del módulo, lo diseña, lo construye y lo verifica. Asigna cada actividad a uno de los cuatro grupos de 12207.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>El contrato de outsourcing es un proceso de acuerdo, porque formaliza la relación entre quien adquiere y quien suministra.</li>
<li>La política de calidad para todos los proyectos es un proceso habilitador de la organización, porque no pertenece a un proyecto concreto.</li>
<li>El plan de SQA del proyecto es gestión técnica, porque dirige y controla ese proyecto, igual que la gestión de configuración.</li>
<li>Levantar requisitos, diseñar, construir y verificar son procesos técnicos, porque construyen el producto que se entrega.</li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="parte-7.-requisitos-y-vocabulario-29148-y-24765" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="parte-7.-requisitos-y-vocabulario-29148-y-24765"><span class="header-section-number">10</span> Parte 7. Requisitos y vocabulario: 29148 y 24765</h2>
<section id="isoiecieee-29148-ingeniería-de-requisitos" class="level3">
<h3 class="anchored" data-anchor-id="isoiecieee-29148-ingeniería-de-requisitos">ISO/IEC/IEEE 29148: ingeniería de requisitos</h3>
<p>La ficha del IEEE describe 29148 como la norma con las disposiciones para los procesos y productos de la ingeniería de requisitos de sistemas y software durante el ciclo de vida. Define las características de calidad de un requisito y sus atributos, y muestra cómo aplicar el proceso de requisitos de forma iterativa. Puede incorporarse a un marco de ciclo de vida de 12207 y 15288 o usarse por separado.</p>
<p>Fue publicada el 30 de noviembre de 2018 y sustituyó a la edición de 2011. Aparece como vigente en el IEEE. Un catálogo comercial la marca como pendiente de revisión, y en las fuentes consultadas no consta una edición posterior.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Lista de características de un buen requisito
</div>
</div>
<div class="callout-body-container callout-body">
<p>La lista siguiente es la que se enseña habitualmente de 29148:2018: necesario, independiente de la implementación, no ambiguo, completo, singular, factible, verificable, correcto y conforme. El texto de la norma es de pago y no se pudo contrastar en esta consulta. Verifica la lista y sus definiciones en el texto de 2018 antes de citarla como literal.</p>
</div>
</div>
</section>
<section id="ejemplo-resuelto-mejorar-un-requisito-de-la-clínica" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-mejorar-un-requisito-de-la-clínica">Ejemplo resuelto: mejorar un requisito de la clínica</h3>
<p>Requisito original: “La app permite sacar turnos de forma rápida y sin problemas.”</p>
<p>Se revisa contra las características.</p>
<ol type="1">
<li>No ambiguo: “rápida” y “sin problemas” no tienen medida. Falla.</li>
<li>Verificable: no se puede diseñar una prueba para “sin problemas”. Falla.</li>
<li>Singular: mezcla velocidad y ausencia de errores. Falla.</li>
</ol>
<p>Se divide y se concreta.</p>
<ul>
<li>“Cuando una paciente autenticada solicita un turno y la especialidad tiene menos de 20 turnos asignados ese día, el sistema debe asignarlo y mostrar la confirmación en un máximo de 3 segundos.”</li>
<li>“Cuando una paciente autenticada solicita un turno y la especialidad ya tiene 20 turnos asignados ese día, el sistema debe rechazar la solicitud y mostrar el mensaje de cupo agotado.”</li>
</ul>
<p>Cada versión nueva dice una sola cosa, se puede probar y no depende de cómo se construya. El límite de 3 segundos es ilustrativo, y la clínica debe fijarlo con sus usuarios.</p>
</section>
<section id="isoiecieee-24765-vocabulario" class="level3">
<h3 class="anchored" data-anchor-id="isoiecieee-24765-vocabulario">ISO/IEC/IEEE 24765: vocabulario</h3>
<p>24765 reúne el vocabulario común de la ingeniería de sistemas y de software. La ficha del IEEE dice que busca terminología común para los profesionales y fomentar la adopción de las normas del IEEE Computer Society, ISO y el PMI. Se publicó el 28 de agosto de 2017 y sustituyó a la de 2010. Figura como vigente.</p>
<p>Sirve de árbitro cuando dos personas usan una palabra con sentidos distintos, como “falla”, “defecto” o “verificación”. Un equipo puede acordar al inicio que, ante una duda de significado, manda el vocabulario de 24765, y escribirlo en la sección de definiciones del plan de SQA.</p>
</section>
<section id="cómo-se-conectan-las-cinco-normas" class="level3">
<h3 class="anchored" data-anchor-id="cómo-se-conectan-las-cinco-normas">Cómo se conectan las cinco normas</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Norma</th>
<th>Pregunta que responde</th>
<th>Grupo de 12207</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>IEEE 730</td>
<td>Cómo se organiza y se planifica el SQA</td>
<td>Gestión técnica</td>
</tr>
<tr class="even">
<td>29119</td>
<td>Cómo se prueba y se documenta la prueba</td>
<td>Procesos técnicos (verificación y validación)</td>
</tr>
<tr class="odd">
<td>29148</td>
<td>Cómo se escribe y gestiona un requisito</td>
<td>Procesos técnicos (requisitos)</td>
</tr>
<tr class="even">
<td>24765</td>
<td>Qué significa cada término</td>
<td>Transversal</td>
</tr>
<tr class="odd">
<td>12207</td>
<td>Qué procesos existen y cómo se agrupan</td>
<td>Marco general</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 6. Reescribe y ubica
</div>
</div>
<div class="callout-body-container callout-body">
<p>Reescribe el siguiente requisito de la clínica para que cumpla las características de 29148, y di en qué norma de la tabla anterior buscarías cómo documentar su prueba: “El sistema debe enviar recordatorios a tiempo y no fallar”.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Una versión posible: “Cuando falten 24 horas para un turno confirmado, el sistema debe enviar un recordatorio por mensaje al número registrado de la paciente.” Y otra: “Si el envío del recordatorio falla, el sistema debe reintentarlo una vez y registrar el fallo.” Cada una es singular, medible y verificable. El valor de 24 horas es ilustrativo y lo fija la clínica.</p>
<p>La prueba se documenta con 29119-3: caso de prueba, resultado real e informe de incidencia si el mensaje no sale. Los términos “falla” y “reintento” se definen con 24765.</p>
</div>
</div>
</div>
</section>
</section>
<section id="errores-frecuentes" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="errores-frecuentes"><span class="header-section-number">11</span> Errores frecuentes</h2>
<ul>
<li>Citar IEEE 730-2014 como la edición vigente, cuando la 2026 la sustituyó y la de 2014 está inactiva.</li>
<li>Dar por buena una “edición 2026” de una norma sin verificarla en la ficha del editor. La de 12207 sí existe, publicada el 15 de abril de 2026, pero no se aplica a otras normas por analogía.</li>
<li>Afirmar que IEEE 730 es solo para software crítico, cuando el texto de 2014 declara que no se restringe por tamaño, complejidad ni criticidad.</li>
<li>Seguir usando IEEE 829 como estándar actual de documentación de pruebas.</li>
<li>Confundir la lista de partes de 29119: la parte 3 es la de documentación, la 4 la de técnicas.</li>
<li>Llenar los documentos de prueba para tener una carpeta y no para encontrar defectos.</li>
<li>Escribir un plan de SQA que omite en silencio las actividades que no hace, en lugar de declararlas “no aplica” con justificación.</li>
<li>Asignar el SQA al líder del proyecto, que evaluaría su propio trabajo.</li>
<li>Creer que una norma conjunta y una pura se citan igual. La conjunta lleva ISO/IEC/IEEE y su edición puede diferir de la pura equivalente.</li>
<li>Citar de memoria listas o nombres de procesos de normas de pago sin contrastarlos con el texto.</li>
</ul>
</section>
<section id="autoevaluación" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="autoevaluación"><span class="header-section-number">12</span> Autoevaluación</h2>
<p>Responde sin mirar la guía. Marca tu opción y abre la clave para comprobarla. Es una práctica formativa y no tiene nota.</p>
<p><strong>1.</strong> ¿Qué distingue a una norma conjunta ISO/IEC/IEEE de una norma IEEE pura?</p>
<p><label><input type="checkbox"> La conjunta la publican el IEEE e ISO/IEC, y la pura solo el IEEE</label> <label><input type="checkbox"> La pura es más reciente que la conjunta</label> <label><input type="checkbox"> La conjunta solo aplica a software crítico</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Lo que cambia es quién publica la norma y su alcance de adopción. La antigüedad y la criticidad no definen el tipo.</p>
</div>
</div>
</div>
<p><strong>2.</strong> En la ficha del IEEE de IEEE 730-2014, el estado que aparece es:</p>
<p><label><input type="checkbox"> Active, sin cambios</label> <label><input type="checkbox"> Inactive-Reserved, sustituida por IEEE 730-2026</label> <label><input type="checkbox"> Superseded por ISO/IEC/IEEE 29119</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. La ficha indica que se inactivó el 27 de marzo de 2025 y que la sustituye IEEE 730-2026.</p>
</div>
</div>
</div>
<p><strong>3.</strong> ¿Cuántas actividades específicas organiza IEEE 730-2014 y en cuántas áreas?</p>
<p><label><input type="checkbox"> 16 actividades en tres áreas</label> <label><input type="checkbox"> 12 actividades en dos áreas</label> <label><input type="checkbox"> 9 actividades en cuatro áreas</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Son seis de implementación del proceso, cinco de aseguramiento de producto y cinco de aseguramiento de proceso, que suman 16.</p>
</div>
</div>
</div>
<p><strong>4.</strong> Un proyecto no hace auditoría de proveedores porque no tiene subcontratistas. Según la conformidad ajustada de 730, ¿qué debe hacer el plan?</p>
<p><label><input type="checkbox"> Omitir la actividad sin decir nada</label> <label><input type="checkbox"> Declararla “no aplica” con su justificación</label> <label><input type="checkbox"> Cumplirla de todas formas con un proveedor ficticio</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. La norma exige identificar en el plan toda actividad no realizada y justificar por qué.</p>
</div>
</div>
</div>
<p><strong>5.</strong> ¿Qué parámetro de independencia se cumple si el presupuesto de SQA lo controla una organización ajena al desarrollo?</p>
<p><label><input type="checkbox"> Técnica</label> <label><input type="checkbox"> Gerencial</label> <label><input type="checkbox"> Financiera</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 3. La técnica se refiere a las personas, la gerencial a la organización a la que pertenece el SQA, y la financiera al control del presupuesto.</p>
</div>
</div>
</div>
<p><strong>6.</strong> ¿Qué norma reemplazó a IEEE 829 para la documentación de pruebas?</p>
<p><label><input type="checkbox"> ISO/IEC/IEEE 29119, con la parte 3 como la de documentación</label> <label><input type="checkbox"> ISO 9001</label> <label><input type="checkbox"> IEEE 730</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. La ficha del IEEE muestra 829-2008 como sustituida por la familia 29119, y la edición vigente de la parte 3 es la de 2021.</p>
</div>
</div>
</div>
<p><strong>7.</strong> En el ejemplo de la clínica, con 19 turnos asignados, dos pacientes piden el último turno al mismo tiempo y ambos reciben turno. ¿Qué documento de 29119-3 registra el hallazgo apenas ocurre?</p>
<p><label><input type="checkbox"> El informe de incidencia</label> <label><input type="checkbox"> La política de pruebas</label> <label><input type="checkbox"> El plan de pruebas</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. La política y el plan se escriben antes de ejecutar, y el informe de incidencia captura el resultado inesperado en el momento.</p>
</div>
</div>
</div>
<p><strong>8.</strong> ¿Qué dice 12207 sobre el modelo de ciclo de vida que debe usar un proyecto?</p>
<p><label><input type="checkbox"> Obliga a la cascada</label> <label><input type="checkbox"> No impone ninguno, define procesos aplicables a cualquier modelo</label> <label><input type="checkbox"> Obliga a un modelo ágil</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. La norma define procesos, actividades y tareas, y deja al proyecto la elección del modelo y del orden en el tiempo.</p>
</div>
</div>
</div>
<p><strong>9.</strong> El plan de SQA de un proyecto pertenece a qué grupo de procesos de 12207:</p>
<p><label><input type="checkbox"> Procesos de acuerdo</label> <label><input type="checkbox"> Procesos de gestión técnica</label> <label><input type="checkbox"> Procesos técnicos</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Dirige y controla un proyecto concreto, igual que la planificación y la gestión de configuración.</p>
</div>
</div>
</div>
<p><strong>10.</strong> Del requisito “el sistema debe ser rápido”, ¿qué falla según los criterios de 29148?</p>
<p><label><input type="checkbox"> Es ambiguo y no verificable, porque no tiene una medida</label> <label><input type="checkbox"> Es singular y verificable</label> <label><input type="checkbox"> Solo falla porque está en español</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 10
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Sin una medida (“en menos de 3 segundos”) no se puede diseñar una prueba.</p>
</div>
</div>
</div>
</section>
<section id="lo-que-te-llevas" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="lo-que-te-llevas"><span class="header-section-number">13</span> Lo que te llevas</h2>
<div class="checklist">
<p><strong>Al salir de este tema deberías poder explicar, sin mirar la guía</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">La diferencia entre norma IEEE pura y conjunta ISO/IEC/IEEE, y cómo leer el estado de una norma</label></li>
<li><label><input type="checkbox">Qué ediciones están vigentes a octubre de 2026 de 730, 12207, 29119, 29148 y 24765</label></li>
<li><label><input type="checkbox">Las tres áreas y las 16 actividades de IEEE 730, y qué cambió entre 2014 y 2026</label></li>
<li><label><input type="checkbox">Cómo se escribe un SQAP con riesgo, esfuerzo, independencia, actividades y registros</label></li>
<li><label><input type="checkbox">Qué reemplazó a IEEE 829 y qué documentos define 29119-3</label></li>
<li><label><input type="checkbox">Los cuatro grupos de procesos de 12207 y dónde cae cada norma</label></li>
<li><label><input type="checkbox">Cómo se mejora un requisito con 29148 y para qué sirve 24765</label></li>
</ul>
</div>
</section>
<section id="glosario" class="level2" data-number="14">
<h2 data-number="14" class="anchored" data-anchor-id="glosario"><span class="header-section-number">14</span> Glosario</h2>
<ul>
<li><strong>IEEE.</strong> Instituto de Ingenieros Eléctricos y Electrónicos, asociación profesional internacional.</li>
<li><strong>C/S2ESC.</strong> Comité de normas de ingeniería de software y de sistemas de la IEEE Computer Society.</li>
<li><strong>Norma IEEE pura.</strong> Norma que desarrolla y publica solo el IEEE.</li>
<li><strong>Norma conjunta ISO/IEC/IEEE.</strong> Norma que desarrollan y publican el IEEE e ISO/IEC.</li>
<li><strong>Active.</strong> Estado de una norma vigente en el IEEE.</li>
<li><strong>Superseded.</strong> Estado de una norma sustituida por otra.</li>
<li><strong>Inactive-Reserved.</strong> Estado de una norma que el IEEE ya no mantiene al día.</li>
<li><strong>SQA.</strong> Aseguramiento de calidad del software: actividades que dan confianza en que el producto cumple sus requisitos.</li>
<li><strong>SQAP.</strong> Plan de aseguramiento de calidad del software.</li>
<li><strong>Aseguramiento de producto.</strong> Actividades que evalúan si el producto y su documentación cumplen los requisitos.</li>
<li><strong>Aseguramiento de proceso.</strong> Actividades que evalúan si el proceso, el entorno, los proveedores y el personal cumplen lo planificado.</li>
<li><strong>Conformidad completa y ajustada.</strong> Dos formas de declarar que se cumple IEEE 730: todas las actividades, o un subconjunto con justificación.</li>
<li><strong>Independencia del SQA.</strong> Técnica, gerencial y financiera: separación del equipo que desarrolla.</li>
<li><strong>No conformidad.</strong> Resultado que no coincide con lo esperado según el plan o el requisito.</li>
<li><strong>IEEE 829.</strong> Norma de documentación de pruebas, sustituida por la familia 29119.</li>
<li><strong>ISO/IEC/IEEE 29119.</strong> Familia de normas de pruebas de software.</li>
<li><strong>Informe de incidencia.</strong> Documento que registra un resultado inesperado en una prueba.</li>
<li><strong>Criterio de salida.</strong> Condición que debe cumplirse para dar por terminado un nivel de prueba.</li>
<li><strong>Análisis de valores límite.</strong> Técnica que prueba los valores en el borde de un rango.</li>
<li><strong>ISO/IEC/IEEE 12207.</strong> Norma de procesos del ciclo de vida del software.</li>
<li><strong>Proceso de acuerdo.</strong> Proceso que regula la relación entre quien adquiere y quien suministra.</li>
<li><strong>Proceso habilitador de la organización.</strong> Proceso que aplica a toda la organización.</li>
<li><strong>Proceso de gestión técnica.</strong> Proceso que dirige y controla un proyecto.</li>
<li><strong>Proceso técnico.</strong> Proceso que construye el producto.</li>
<li><strong>ISO/IEC/IEEE 29148.</strong> Norma de ingeniería de requisitos.</li>
<li><strong>Requisito singular.</strong> Requisito que dice una sola cosa.</li>
<li><strong>ISO/IEC/IEEE 24765.</strong> Vocabulario de ingeniería de sistemas y de software.</li>
<li><strong>Armonización.</strong> Alineación del texto de una norma con otra para que no se contradigan.</li>
</ul>
</section>
<section id="bibliografía" class="level2" data-number="15">
<h2 data-number="15" class="anchored" data-anchor-id="bibliografía"><span class="header-section-number">15</span> Bibliografía</h2>
<p>Normas del IEEE (fichas públicas, consultadas en octubre de 2026):</p>
<ul>
<li>IEEE (2026). <em>IEEE Standard for Software Quality Assurance Processes</em>, IEEE Std 730-2026. <a href="https://standards.ieee.org/ieee/730/10854/">Ficha</a>.</li>
<li>IEEE (2014). <em>IEEE Standard for Software Quality Assurance Processes</em>, IEEE Std 730-2014. <a href="https://standards.ieee.org/ieee/730/5284/">Ficha</a>.</li>
<li>IEEE (2008). <em>IEEE Standard for Software and System Test Documentation</em>, IEEE Std 829-2008, sustituida. <a href="https://standards.ieee.org/ieee/829/3787/">Ficha</a>.</li>
<li>ISO/IEC/IEEE (2026). <em>Systems and software engineering, Software life cycle processes</em>, 12207:2026. <a href="https://standards.ieee.org/ieee/12207/11416/">Ficha del IEEE</a>.</li>
<li>ISO/IEC/IEEE (2018). <em>Systems and software engineering, Life cycle processes, Requirements engineering</em>, 29148:2018. <a href="https://standards.ieee.org/ieee/29148/6937/">Ficha</a>.</li>
<li>ISO/IEC/IEEE (2017). <em>Systems and software engineering, Vocabulary</em>, 24765:2017. <a href="https://standards.ieee.org/ieee/24765/6800/">Ficha</a>.</li>
<li>ISO/IEC/IEEE (2021 a 2024). <em>Software and systems engineering, Software testing</em>, 29119, partes 1 a 5. Ediciones: parte 1, 2022; partes 2, 3 y 4, 2021; parte 5, 2024. Texto de pago, consultado en catálogos de normas. Referencia secundaria: <a href="https://quality.arc42.org/standards/iso-iec-ieee-29119">arc42 Quality</a>.</li>
</ul>
<p>Otras fuentes:</p>
<ul>
<li>IEEE Computer Society. <a href="https://www.computer.org/volunteering/boards-and-committees/standards-activities/committees/s2esc">Software and Systems Engineering Standards Committee (S2ESC)</a>.</li>
<li>Wikipedia. <a href="https://en.wikipedia.org/wiki/ISO/IEC_29119">ISO/IEC 29119</a>. Fuente secundaria sobre la historia de la familia y la petición de 2014.</li>
<li>Wikipedia. <a href="https://en.wikipedia.org/wiki/ISO/IEC_12207">ISO/IEC 12207</a>. Fuente secundaria sobre las ediciones históricas.</li>
</ul>
<p>Parte del contenido de IEEE 730-2026, de 29119-3, de 29148 y de 12207 es de pago y no se pudo leer. Los puntos que dependen de esos textos están marcados en cada parte.</p>
<div class="pie-doc">
<p>Calidad del software (CDS01). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>