<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 2. La calidad en cada fase del ciclo de vida – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-95bfa606010d176c52cfb6b551730f65.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-02/index.html">Unidad 2. Procesos de calidad del software. Modelos y métricas</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html">Tema 2. La calidad en cada fase del ciclo de vida</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Calidad del software y estándares de calidad</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-01-que-es-calidad-quien-la-define/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es la calidad y quién la define</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Calidad de proceso y de producto: ISO/IEC 25010:2023</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Importancia, costo y calidad en un mundo globalizado</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Procesos de calidad del software. Modelos y métricas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-01-sqa-relacion-ingenieria/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es el SQA y su relación con la ingeniería de software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 2. La calidad en cada fase del ciclo de vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-03-roles-habilidades/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Roles, responsabilidades y habilidades del personal de SQA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-04-actividades-sqa/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Actividades del SQA: revisiones, auditorías y gestión de configuración</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-05-modelos-metricas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Modelos y métricas de calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-06-herramientas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 6. Herramientas de SQA en la industria</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 3. Estándares de calidad aplicados al software</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Estándares IEEE para la calidad del software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Marcos para evaluar la usabilidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Madurez de procesos: SPICE y CMMI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 4. Validación y verificación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Métodos, metodologías y estándares de verificación y validación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Validación y verificación de requisitos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-03-control-costo-calidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Control de la calidad y costo de la calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Nomenclatura y certificación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-05-factores-atam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Factores que determinan la calidad y el método ATAM</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#objetivo-y-resultado-de-aprendizaje" id="toc-objetivo-y-resultado-de-aprendizaje" class="nav-link active" data-scroll-target="#objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</a></li>
  <li><a href="#ruta-de-estudio" id="toc-ruta-de-estudio" class="nav-link" data-scroll-target="#ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</a></li>
  <li><a href="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" id="toc-el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="nav-link" data-scroll-target="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</a></li>
  <li><a href="#parte-1.-la-calidad-por-fase-y-la-norma-isoiecieee-12207" id="toc-parte-1.-la-calidad-por-fase-y-la-norma-isoiecieee-12207" class="nav-link" data-scroll-target="#parte-1.-la-calidad-por-fase-y-la-norma-isoiecieee-12207"><span class="header-section-number">4</span> Parte 1. La calidad por fase y la norma ISO/IEC/IEEE 12207</a>
  <ul class="collapse">
  <li><a href="#qué-es-una-actividad-de-calidad-por-fase" id="toc-qué-es-una-actividad-de-calidad-por-fase" class="nav-link" data-scroll-target="#qué-es-una-actividad-de-calidad-por-fase">Qué es una actividad de calidad por fase</a></li>
  <li><a href="#verificación-y-validación" id="toc-verificación-y-validación" class="nav-link" data-scroll-target="#verificación-y-validación">Verificación y validación</a></li>
  <li><a href="#la-norma-isoiecieee-12207" id="toc-la-norma-isoiecieee-12207" class="nav-link" data-scroll-target="#la-norma-isoiecieee-12207">La norma ISO/IEC/IEEE 12207</a></li>
  <li><a href="#los-procesos-que-importan-para-la-calidad" id="toc-los-procesos-que-importan-para-la-calidad" class="nav-link" data-scroll-target="#los-procesos-que-importan-para-la-calidad">Los procesos que importan para la calidad</a></li>
  <li><a href="#la-norma-de-sqa-que-la-acompaña" id="toc-la-norma-de-sqa-que-la-acompaña" class="nav-link" data-scroll-target="#la-norma-de-sqa-que-la-acompaña">La norma de SQA que la acompaña</a></li>
  <li><a href="#la-calidad-de-producto-en-una-referencia-breve" id="toc-la-calidad-de-producto-en-una-referencia-breve" class="nav-link" data-scroll-target="#la-calidad-de-producto-en-una-referencia-breve">La calidad de producto en una referencia breve</a></li>
  </ul></li>
  <li><a href="#parte-2.-cuatro-formas-de-organizar-el-ciclo-de-vida" id="toc-parte-2.-cuatro-formas-de-organizar-el-ciclo-de-vida" class="nav-link" data-scroll-target="#parte-2.-cuatro-formas-de-organizar-el-ciclo-de-vida"><span class="header-section-number">5</span> Parte 2. Cuatro formas de organizar el ciclo de vida</a>
  <ul class="collapse">
  <li><a href="#cascada" id="toc-cascada" class="nav-link" data-scroll-target="#cascada">Cascada</a></li>
  <li><a href="#modelo-en-v" id="toc-modelo-en-v" class="nav-link" data-scroll-target="#modelo-en-v">Modelo en V</a></li>
  <li><a href="#iterativo-e-incremental" id="toc-iterativo-e-incremental" class="nav-link" data-scroll-target="#iterativo-e-incremental">Iterativo e incremental</a></li>
  <li><a href="#ágil-scrum-y-kanban" id="toc-ágil-scrum-y-kanban" class="nav-link" data-scroll-target="#ágil-scrum-y-kanban">Ágil: Scrum y Kanban</a></li>
  <li><a href="#comparación" id="toc-comparación" class="nav-link" data-scroll-target="#comparación">Comparación</a></li>
  <li><a href="#ejemplo-resuelto-la-misma-función-en-dos-modelos" id="toc-ejemplo-resuelto-la-misma-función-en-dos-modelos" class="nav-link" data-scroll-target="#ejemplo-resuelto-la-misma-función-en-dos-modelos">Ejemplo resuelto: la misma función en dos modelos</a></li>
  </ul></li>
  <li><a href="#parte-3.-cicd-y-devops" id="toc-parte-3.-cicd-y-devops" class="nav-link" data-scroll-target="#parte-3.-cicd-y-devops"><span class="header-section-number">6</span> Parte 3. CI/CD y DevOps</a>
  <ul class="collapse">
  <li><a href="#qué-cambia-con-la-entrega-continua" id="toc-qué-cambia-con-la-entrega-continua" class="nav-link" data-scroll-target="#qué-cambia-con-la-entrega-continua">Qué cambia con la entrega continua</a></li>
  <li><a href="#un-pipeline-con-puertas-de-calidad" id="toc-un-pipeline-con-puertas-de-calidad" class="nav-link" data-scroll-target="#un-pipeline-con-puertas-de-calidad">Un pipeline con puertas de calidad</a></li>
  <li><a href="#ejemplo-resuelto-por-qué-el-pipeline-se-parte-en-niveles" id="toc-ejemplo-resuelto-por-qué-el-pipeline-se-parte-en-niveles" class="nav-link" data-scroll-target="#ejemplo-resuelto-por-qué-el-pipeline-se-parte-en-niveles">Ejemplo resuelto: por qué el pipeline se parte en niveles</a></li>
  <li><a href="#las-métricas-dora" id="toc-las-métricas-dora" class="nav-link" data-scroll-target="#las-métricas-dora">Las métricas DORA</a></li>
  <li><a href="#ejemplo-resuelto-las-métricas-de-la-clínica-en-un-mes" id="toc-ejemplo-resuelto-las-métricas-de-la-clínica-en-un-mes" class="nav-link" data-scroll-target="#ejemplo-resuelto-las-métricas-de-la-clínica-en-un-mes">Ejemplo resuelto: las métricas de la clínica en un mes</a></li>
  </ul></li>
  <li><a href="#parte-4.-shift-left-shift-right-y-quality-engineering" id="toc-parte-4.-shift-left-shift-right-y-quality-engineering" class="nav-link" data-scroll-target="#parte-4.-shift-left-shift-right-y-quality-engineering"><span class="header-section-number">7</span> Parte 4. Shift-left, shift-right y quality engineering</a>
  <ul class="collapse">
  <li><a href="#shift-left" id="toc-shift-left" class="nav-link" data-scroll-target="#shift-left">Shift-left</a></li>
  <li><a href="#shift-right" id="toc-shift-right" class="nav-link" data-scroll-target="#shift-right">Shift-right</a></li>
  <li><a href="#quality-engineering" id="toc-quality-engineering" class="nav-link" data-scroll-target="#quality-engineering">Quality engineering</a></li>
  </ul></li>
  <li><a href="#parte-5.-la-matriz-de-actividades-de-calidad-por-fase" id="toc-parte-5.-la-matriz-de-actividades-de-calidad-por-fase" class="nav-link" data-scroll-target="#parte-5.-la-matriz-de-actividades-de-calidad-por-fase"><span class="header-section-number">8</span> Parte 5. La matriz de actividades de calidad por fase</a></li>
  <li><a href="#parte-6.-ejemplo-resuelto-efectividad-de-remoción-por-fase" id="toc-parte-6.-ejemplo-resuelto-efectividad-de-remoción-por-fase" class="nav-link" data-scroll-target="#parte-6.-ejemplo-resuelto-efectividad-de-remoción-por-fase"><span class="header-section-number">9</span> Parte 6. Ejemplo resuelto: efectividad de remoción por fase</a>
  <ul class="collapse">
  <li><a href="#el-concepto" id="toc-el-concepto" class="nav-link" data-scroll-target="#el-concepto">El concepto</a></li>
  <li><a href="#datos-de-la-función-cancelar-y-reprogramar-un-turno" id="toc-datos-de-la-función-cancelar-y-reprogramar-un-turno" class="nav-link" data-scroll-target="#datos-de-la-función-cancelar-y-reprogramar-un-turno">Datos de la función “cancelar y reprogramar un turno”</a></li>
  <li><a href="#paso-a-paso" id="toc-paso-a-paso" class="nav-link" data-scroll-target="#paso-a-paso">Paso a paso</a></li>
  <li><a href="#el-costo-del-hallazgo" id="toc-el-costo-del-hallazgo" class="nav-link" data-scroll-target="#el-costo-del-hallazgo">El costo del hallazgo</a></li>
  <li><a href="#escenario-mejorar-la-revisión-de-requisitos" id="toc-escenario-mejorar-la-revisión-de-requisitos" class="nav-link" data-scroll-target="#escenario-mejorar-la-revisión-de-requisitos">Escenario: mejorar la revisión de requisitos</a></li>
  </ul></li>
  <li><a href="#parte-7.-ejemplo-resuelto-plan-de-calidad-por-fase-de-la-app" id="toc-parte-7.-ejemplo-resuelto-plan-de-calidad-por-fase-de-la-app" class="nav-link" data-scroll-target="#parte-7.-ejemplo-resuelto-plan-de-calidad-por-fase-de-la-app"><span class="header-section-number">10</span> Parte 7. Ejemplo resuelto: plan de calidad por fase de la app</a>
  <ul class="collapse">
  <li><a href="#qué-es-un-plan-de-calidad-por-fase" id="toc-qué-es-un-plan-de-calidad-por-fase" class="nav-link" data-scroll-target="#qué-es-un-plan-de-calidad-por-fase">Qué es un plan de calidad por fase</a></li>
  <li><a href="#el-plan" id="toc-el-plan" class="nav-link" data-scroll-target="#el-plan">El plan</a></li>
  <li><a href="#cómo-leer-el-plan" id="toc-cómo-leer-el-plan" class="nav-link" data-scroll-target="#cómo-leer-el-plan">Cómo leer el plan</a></li>
  <li><a href="#ejemplo-resuelto-aplicar-el-criterio-de-salida" id="toc-ejemplo-resuelto-aplicar-el-criterio-de-salida" class="nav-link" data-scroll-target="#ejemplo-resuelto-aplicar-el-criterio-de-salida">Ejemplo resuelto: aplicar el criterio de salida</a></li>
  </ul></li>
  <li><a href="#parte-8.-caso-real-el-boeing-737-max-y-el-sistema-mcas" id="toc-parte-8.-caso-real-el-boeing-737-max-y-el-sistema-mcas" class="nav-link" data-scroll-target="#parte-8.-caso-real-el-boeing-737-max-y-el-sistema-mcas"><span class="header-section-number">11</span> Parte 8. Caso real: el Boeing 737 MAX y el sistema MCAS</a>
  <ul class="collapse">
  <li><a href="#por-qué-este-caso" id="toc-por-qué-este-caso" class="nav-link" data-scroll-target="#por-qué-este-caso">Por qué este caso</a></li>
  <li><a href="#los-hechos" id="toc-los-hechos" class="nav-link" data-scroll-target="#los-hechos">Los hechos</a></li>
  <li><a href="#dónde-faltó-cada-control" id="toc-dónde-faltó-cada-control" class="nav-link" data-scroll-target="#dónde-faltó-cada-control">Dónde faltó cada control</a></li>
  <li><a href="#la-auditoría-de-la-faa-de-2024" id="toc-la-auditoría-de-la-faa-de-2024" class="nav-link" data-scroll-target="#la-auditoría-de-la-faa-de-2024">La auditoría de la FAA de 2024</a></li>
  </ul></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes"><span class="header-section-number">12</span> Errores frecuentes</a></li>
  <li><a href="#autoevaluación" id="toc-autoevaluación" class="nav-link" data-scroll-target="#autoevaluación"><span class="header-section-number">13</span> Autoevaluación</a></li>
  <li><a href="#lo-que-te-llevas" id="toc-lo-que-te-llevas" class="nav-link" data-scroll-target="#lo-que-te-llevas"><span class="header-section-number">14</span> Lo que te llevas</a></li>
  <li><a href="#glosario" id="toc-glosario" class="nav-link" data-scroll-target="#glosario"><span class="header-section-number">15</span> Glosario</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">16</span> Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-02/index.html">Unidad 2. Procesos de calidad del software. Modelos y métricas</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html">Tema 2. La calidad en cada fase del ciclo de vida</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 2. La calidad en cada fase del ciclo de vida</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">3 de octubre de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 89%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 2. Procesos de calidad del software. Modelos y métricas</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 2. La calidad en cada fase del ciclo de vida</td>
</tr>
</tbody>
</table>
</div>
<p><a href="../presentacion-interactiva.html" class="btn-curso">Presentación interactiva de la unidad</a></p>
<p>Tema anterior: <a href="../../../calidad-del-software/unidad-02/tema-01-sqa-relacion-ingenieria/index.html">Tema 1. El SQA y su relación con la ingeniería de software</a>. Tema siguiente: <a href="../../../calidad-del-software/unidad-02/tema-03-roles-habilidades/index.html">Tema 3. Roles y habilidades del personal de SQA</a>.</p>
<section id="objetivo-y-resultado-de-aprendizaje" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</h2>
<p>El Tema 1 explicó qué es el aseguramiento de la calidad del software (SQA) y cómo se relaciona con la ingeniería de software. Este tema responde una pregunta más concreta: en qué momento del desarrollo entra cada actividad de calidad, qué necesita para empezar, qué entrega al terminar y quién responde por ella. Los roles y las habilidades de esas personas se estudian en el Tema 3.</p>
<p>Al terminar puedes:</p>
<ul>
<li>Explicar qué hace ISO/IEC/IEEE 12207 con el ciclo de vida y por qué habla de procesos y no de fases fijas.</li>
<li>Ubicar la calidad en la cascada, el modelo en V, el desarrollo iterativo y el ágil (Scrum y Kanban).</li>
<li>Describir un pipeline de CI/CD y las métricas DORA que miden su salud.</li>
<li>Distinguir <em>shift-left</em>, <em>shift-right</em> y <em>quality engineering</em>, y decidir qué control va en cada lado.</li>
<li>Leer y construir una matriz de actividades de calidad por fase, con entradas, salidas y responsable.</li>
<li>Calcular la efectividad de remoción de defectos de cada fase y el costo que produce el reparto de hallazgos.</li>
<li>Armar un plan de calidad por fase para una función de la app de turnos de la clínica.</li>
<li>Analizar el caso del Boeing 737 MAX (MCAS) y nombrar en qué fase faltó cada control.</li>
</ul>
<p>Prerrequisitos: el Tema 1 de esta unidad y los Temas 1 a 3 de la Unidad 1. Necesitas distinguir <em>requisito</em>, <em>defecto</em> y <em>falla</em>, y saber qué es una norma.</p>
</section>
<section id="ruta-de-estudio" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</h2>
<p>Son unas 6 horas de trabajo independiente, que puedes partir en tres sesiones. La presentación interactiva de la unidad sigue estas mismas partes y en el mismo orden.</p>
<div class="calendario">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parte</th>
<th>Qué haces</th>
<th>Tiempo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. La calidad por fase y la norma 12207</td>
<td>Lees qué es una fase de calidad y qué dice la norma vigente</td>
<td>35 min</td>
</tr>
<tr class="even">
<td>2. Cuatro formas de organizar el ciclo de vida</td>
<td>Comparas cascada, V, iterativo y ágil, y resuelves el Reto 1</td>
<td>50 min</td>
</tr>
<tr class="odd">
<td>3. CI/CD y DevOps</td>
<td>Lees el pipeline y las métricas DORA, y resuelves el Reto 2</td>
<td>45 min</td>
</tr>
<tr class="even">
<td>4. Shift-left, shift-right y quality engineering</td>
<td>Lees los tres enfoques y resuelves el Reto 3</td>
<td>35 min</td>
</tr>
<tr class="odd">
<td>5. La matriz de actividades por fase</td>
<td>Lees la matriz completa y resuelves el Reto 4</td>
<td>40 min</td>
</tr>
<tr class="even">
<td>6. Ejemplo resuelto: efectividad por fase</td>
<td>Sigues el cálculo de defectos y de costo, y resuelves el Reto 5</td>
<td>55 min</td>
</tr>
<tr class="odd">
<td>7. Ejemplo resuelto: plan de calidad de la app</td>
<td>Lees el plan de una función y resuelves el Reto 6</td>
<td>45 min</td>
</tr>
<tr class="even">
<td>8. Caso: Boeing 737 MAX y MCAS</td>
<td>Analizas el caso fase por fase y resuelves el Reto 7</td>
<td>45 min</td>
</tr>
<tr class="odd">
<td>Cierre</td>
<td>Errores frecuentes, autoevaluación y glosario</td>
<td>30 min</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</h2>
<p>La app de la Clínica Aurora asigna turnos médicos, con su requisito de partida “la app asigna hasta 20 turnos por día a cada especialidad”. En este tema el equipo de la clínica prepara una función nueva, cancelar y reprogramar un turno, y tú le armas el plan de calidad de principio a fin.</p>
<p>Todas las cifras de la clínica son ilustrativas. Se inventaron para practicar el cálculo y no vienen de ninguna clínica real. Las cifras de normas, informes y casos sí vienen de fuentes que se citan en la bibliografía.</p>
</section>
<section id="parte-1.-la-calidad-por-fase-y-la-norma-isoiecieee-12207" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="parte-1.-la-calidad-por-fase-y-la-norma-isoiecieee-12207"><span class="header-section-number">4</span> Parte 1. La calidad por fase y la norma ISO/IEC/IEEE 12207</h2>
<section id="qué-es-una-actividad-de-calidad-por-fase" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-una-actividad-de-calidad-por-fase">Qué es una actividad de calidad por fase</h3>
<p>El Tema 1 distinguió dos ideas. El aseguramiento de la calidad (SQA) vigila que el proceso de construcción sea adecuado y trabaja de forma preventiva. El control de calidad revisa el producto ya construido y detecta defectos. Una guía de calidad por fase pone esas dos ideas en el calendario del proyecto.</p>
<p>Para ubicar una actividad de calidad dentro del ciclo de vida, hazle cinco preguntas.</p>
<ol type="1">
<li>Qué fase la contiene, por ejemplo requisitos, diseño o construcción.</li>
<li>Qué entrada necesita, es decir qué documento o producto debe existir antes.</li>
<li>Qué salida produce, es decir qué evidencia queda cuando termina.</li>
<li>Quién responde por ella, un rol y no una persona con nombre.</li>
<li>Qué criterio decide que la fase puede cerrarse, y por tanto qué defecto la detendría.</li>
</ol>
<p>Con esas cinco respuestas, “hacer pruebas” deja de ser una sola caja al final y pasa a ser un conjunto de controles repartidos. La matriz de la Parte 5 reúne las respuestas para todas las fases.</p>
</section>
<section id="verificación-y-validación" class="level3">
<h3 class="anchored" data-anchor-id="verificación-y-validación">Verificación y validación</h3>
<p>Toda actividad de calidad por fase se apoya en dos preguntas distintas, que los Temas 1 y 2 de la Unidad 4 desarrollan a fondo. Aquí basta la idea central.</p>
<ul>
<li>Verificación: ¿se construyó bien el producto frente a lo que se especificó? Compara un resultado contra su especificación.</li>
<li>Validación: ¿se construyó el producto correcto para quien lo va a usar? Compara el producto contra la necesidad real.</li>
</ul>
<p>Una revisión de requisitos que busca contradicciones es verificación. Un piloto con pacientes reales que prueban la app es validación. El equipo necesita las dos, porque un producto puede cumplir su especificación y aun así no servir para lo que el usuario necesitaba.</p>
</section>
<section id="la-norma-isoiecieee-12207" class="level3">
<h3 class="anchored" data-anchor-id="la-norma-isoiecieee-12207">La norma ISO/IEC/IEEE 12207</h3>
<p>La norma ISO/IEC/IEEE 12207, <em>Systems and software engineering, Software life cycle processes</em>, la publican de forma conjunta ISO, IEC e IEEE. Establece un marco común de procesos para describir el ciclo de vida completo de un sistema de software, desde la concepción hasta el retiro. Sirve tanto para quien adquiere software como para quien lo suministra, lo desarrolla, lo opera y lo mantiene.</p>
<p>Su idea más útil para este tema es que define procesos, no una secuencia obligatoria de fases. La propia norma indica que esos procesos se pueden aplicar de forma concurrente, iterativa y recursiva. La organización elige su modelo de ciclo de vida (cascada, iterativo, ágil) y usa los procesos de la norma como catálogo de lo que debe cubrir, sin importar el orden.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Edición vigente en octubre de 2026
</div>
</div>
<div class="callout-body-container callout-body">
<p>La edición vigente es ISO/IEC/IEEE 12207:2026, segunda edición, publicada en abril de 2026. Según la ficha de IEEE, su fecha de publicación es el 15 de abril de 2026, y sustituye a la edición de 2017.</p>
<p>Según el resumen del catálogo de ISO, el cambio es una revisión técnica. Actualiza procesos técnicos como análisis de negocio o misión, definición de arquitectura, implementación, integración, operación y mantenimiento. Mejora procesos de gestión técnica como riesgos y gestión de configuración. Amplía el contenido sobre métodos ágiles y revisa el anexo sobre ingeniería de sistemas y software basada en modelos. La ficha de IEEE añade que se alinea con ISO/IEC/IEEE 15288:2023, la norma de procesos de ciclo de vida de sistemas.</p>
<p>El texto completo de la norma es de pago y no se pudo leer en fuente primaria. Por eso esta guía no cita números de cláusula de la edición 2026 y describe los procesos con los nombres de la edición 2017, que tampoco se pudieron contrastar con el texto completo. Antes de usar la norma como referencia contractual, confirma el texto en iso.org o en standards.ieee.org.</p>
</div>
</div>
</section>
<section id="los-procesos-que-importan-para-la-calidad" class="level3">
<h3 class="anchored" data-anchor-id="los-procesos-que-importan-para-la-calidad">Los procesos que importan para la calidad</h3>
<p>En la edición 2017 los procesos se agrupan en cuatro familias principales y un grupo propio del software. Para este tema interesan tres de ellas.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Grupo de la edición 2017</th>
<th>Procesos relevantes para la calidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gestión técnica</td>
<td>Planificación, evaluación y control del proyecto, gestión del riesgo, gestión de configuración, medición y aseguramiento de la calidad</td>
</tr>
<tr class="even">
<td>Técnicos</td>
<td>Definición de requisitos, definición de arquitectura y de diseño, implementación, integración, verificación, transición, validación, operación y mantenimiento</td>
</tr>
<tr class="odd">
<td>Habilitación organizacional</td>
<td>Gestión del modelo de ciclo de vida, gestión de la calidad de la organización</td>
</tr>
</tbody>
</table>
<p>Dos cosas se desprenden de la tabla. Primera, el aseguramiento de la calidad es un proceso de gestión técnica que acompaña a todos los demás, y no una fase que ocurre al final. Segunda, la verificación y la validación son procesos técnicos con nombre propio, que se ejecutan sobre cada producto intermedio y no solo sobre el programa terminado.</p>
</section>
<section id="la-norma-de-sqa-que-la-acompaña" class="level3">
<h3 class="anchored" data-anchor-id="la-norma-de-sqa-que-la-acompaña">La norma de SQA que la acompaña</h3>
<p>La norma específica de procesos de SQA es la IEEE 730. Su edición de 2014 quedó inactiva-reservada el 27 de marzo de 2025. La edición vigente es IEEE 730-2026, publicada el 21 de agosto de 2026, que sustituye a la de 2014. Establece los requisitos para iniciar, planificar, controlar y ejecutar los procesos de SQA en proyectos de desarrollo o de mantenimiento de software. Según su ficha, se armoniza con la edición 2017 de ISO/IEC/IEEE 12207 y con ISO/IEC/IEEE 15289:2019, que trata el contenido de la información de ciclo de vida. La Unidad 3 estudia las normas IEEE con detalle.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Una advertencia sobre las fuentes antiguas
</div>
</div>
<div class="callout-body-container callout-body">
<p>Muchas guías, apuntes y presentaciones todavía citan IEEE 730-2014 como la norma vigente y ISO/IEC/IEEE 12207:2017 como la última edición. Al revisar una fuente, mira el año. Si es anterior a 2026, su afirmación sobre la edición vigente puede haber cambiado. La ficha del catálogo, no el apunte de otra persona, es la que dice qué edición rige.</p>
</div>
</div>
</section>
<section id="la-calidad-de-producto-en-una-referencia-breve" class="level3">
<h3 class="anchored" data-anchor-id="la-calidad-de-producto-en-una-referencia-breve">La calidad de producto en una referencia breve</h3>
<p>La calidad del producto se evalúa contra el modelo ISO/IEC 25010:2023, con nueve características, que el Tema 2 de la Unidad 1 desarrolla. Cada actividad de este tema puede entenderse como una forma de proteger una o varias de esas características en un momento concreto del ciclo de vida.</p>
</section>
</section>
<section id="parte-2.-cuatro-formas-de-organizar-el-ciclo-de-vida" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="parte-2.-cuatro-formas-de-organizar-el-ciclo-de-vida"><span class="header-section-number">5</span> Parte 2. Cuatro formas de organizar el ciclo de vida</h2>
<p>Un modelo de ciclo de vida decide el orden y el tamaño de los pasos. La calidad no cambia de objetivo, pero sí cambia el momento en que llega la primera señal de que algo está mal. Esta parte compara cuatro modelos con la misma pregunta: cuándo se entera el equipo de un defecto.</p>
<section id="cascada" class="level3">
<h3 class="anchored" data-anchor-id="cascada">Cascada</h3>
<p>En el modelo en cascada las fases ocurren una tras otra: requisitos, diseño, construcción, pruebas y mantenimiento. Cada fase termina antes de que empiece la siguiente, y un documento aprobado marca la salida. La calidad se apoya en revisiones formales de cada documento y en un conjunto grande de pruebas al final.</p>
<p>Winston Royce describió esta secuencia en 1970 en su artículo <em>Managing the Development of Large Software Systems</em>. Lo que muchas veces se omite es que el propio Royce la presentó como un esquema arriesgado en su forma pura, y recomendó iterar, involucrar al cliente y planificar las pruebas con anticipación. El nombre “cascada” vino después y la imagen se popularizó sin esas advertencias.</p>
<p>La señal de calidad llega tarde. Un defecto de requisitos puede viajar hasta las pruebas finales sin que nadie lo vea, y entonces corregirlo obliga a rehacer fases ya cerradas. Funciona bien cuando los requisitos son estables y bien conocidos, y mal cuando el usuario descubre lo que necesita mientras ve el producto.</p>
</section>
<section id="modelo-en-v" class="level3">
<h3 class="anchored" data-anchor-id="modelo-en-v">Modelo en V</h3>
<p>El modelo en V conserva la secuencia de la cascada y le agrega una idea. Cada fase de especificación o de diseño tiene una fase de verificación o validación que se planifica al mismo tiempo que ella. Cuando el equipo escribe los requisitos, escribe también los criterios de la prueba de aceptación. Cuando define la arquitectura, define también las pruebas de integración.</p>
<div class="diagrama">
<svg viewbox="0 0 760 340" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Modelo en V: a la izquierda bajan requisitos, diseño del sistema, diseño de arquitectura y diseño detallado; en el vértice está la construcción; a la derecha suben pruebas unitarias, de integración, de sistema y de aceptación. Líneas punteadas unen cada fase con la prueba que se planifica junto a ella." font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u2t2a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">El modelo en V: cada prueba se planifica junto a su fase</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="10" y="38" width="190" height="42" rx="8"></rect><rect x="60" y="108" width="190" height="42" rx="8"></rect><rect x="110" y="178" width="190" height="42" rx="8"></rect><rect x="160" y="248" width="190" height="42" rx="8"></rect></g> <rect x="285" y="296" width="190" height="38" rx="8" fill="#fff6dc" stroke="#e6cf8a"></rect> <g fill="#e4f2f1" stroke="#8fc9c5"><rect x="410" y="248" width="190" height="42" rx="8"></rect><rect x="460" y="178" width="190" height="42" rx="8"></rect><rect x="510" y="108" width="190" height="42" rx="8"></rect><rect x="560" y="38" width="190" height="42" rx="8"></rect></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8"><path d="M105,80 L155,108"></path><path d="M155,150 L205,178"></path><path d="M205,220 L255,248"></path><path d="M255,290 L320,296"></path></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u2t2a)"><path d="M440,296 L505,290"></path><path d="M505,248 L555,220"></path><path d="M555,178 L605,150"></path><path d="M605,108 L655,80"></path></g> <g stroke="#cfd8e3" stroke-width="1.2" stroke-dasharray="4 4"><line x1="200" y1="59" x2="560" y2="59"></line><line x1="250" y1="129" x2="510" y2="129"></line><line x1="300" y1="199" x2="460" y2="199"></line><line x1="350" y1="269" x2="410" y2="269"></line></g> <g text-anchor="middle" font-size="12" fill="#12324f"><text x="105" y="63">Requisitos</text><text x="155" y="133">Diseño del sistema</text><text x="205" y="203">Diseño de arquitectura</text><text x="255" y="273">Diseño detallado</text></g> <text x="380" y="320" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Construcción</text> <g text-anchor="middle" font-size="12" fill="#12324f"><text x="505" y="273">Pruebas unitarias</text><text x="555" y="203">Pruebas de integración</text><text x="605" y="133">Pruebas de sistema</text><text x="655" y="63">Pruebas de aceptación</text></g> <g font-size="11" fill="#5b6876"><text x="380" y="46" text-anchor="middle">validación</text><text x="380" y="116" text-anchor="middle">verificación contra el diseño</text><text x="380" y="186" text-anchor="middle">verificación de interfaces</text><text x="380" y="256" text-anchor="middle">verificación del módulo</text></g>
</svg>
</div>
<p>El modelo en V no deja la validación para el final. Por eso se dice que lleva la prueba hacia la izquierda: se escribe el criterio de aceptación antes de que exista el código. Su punto débil es que sigue siendo secuencial. Si el análisis y el diseño se atrasan, la presión de la fecha comprime las pruebas del lado derecho, y la cobertura real termina siendo menor que la planificada.</p>
</section>
<section id="iterativo-e-incremental" class="level3">
<h3 class="anchored" data-anchor-id="iterativo-e-incremental">Iterativo e incremental</h3>
<p>En el desarrollo iterativo el equipo repite ciclos cortos de análisis, diseño, construcción y prueba, y en cada ciclo entrega una parte del producto. Barry Boehm propuso en 1988 el modelo en espiral, que añade el análisis explícito de riesgos al comienzo de cada vuelta. La idea de fondo es que una señal de calidad llega en semanas y no en meses, porque cada incremento se prueba y se enseña a un usuario.</p>
<p>Esto cambia la manera de verificar. Las pruebas de regresión se vuelven imprescindibles, porque cada ciclo toca código que ya funcionaba. Y las revisiones se hacen sobre piezas pequeñas, que son más fáciles de revisar a fondo.</p>
</section>
<section id="ágil-scrum-y-kanban" class="level3">
<h3 class="anchored" data-anchor-id="ágil-scrum-y-kanban">Ágil: Scrum y Kanban</h3>
<p>Los métodos ágiles llevan la iteración al extremo, con ciclos de una a cuatro semanas y entregas frecuentes. Dos marcos son muy usados, y cada uno pone la calidad en un lugar distinto.</p>
<p>La Guía de Scrum (Schwaber y Sutherland, edición de noviembre de 2020) organiza el trabajo en sprints. La calidad vive en la <em>Definición de Terminado</em> (<em>Definition of Done</em>), que la guía describe como una descripción formal del estado del incremento cuando cumple las medidas de calidad que el producto exige. Un elemento del trabajo no está terminado hasta que cumple esa definición. La guía agrega que la calidad es responsabilidad del equipo completo y no de una función separada, y que el Sprint Review y la Retrospectiva sirven para inspeccionar y mejorar.</p>
<p>Kanban no tiene sprints. El trabajo fluye por un tablero, y la calidad se apoya en cuatro prácticas que describe David Anderson: visualizar el flujo, limitar el trabajo en curso, gestionar el flujo y hacer explícitas las políticas. Limitar el trabajo en curso reduce las tareas a medias y acorta el tiempo en que un defecto espera a ser visto. Las políticas explícitas, como “una tarjeta no pasa a Listo sin revisión de pares”, son el equivalente de una definición de terminado.</p>
</section>
<section id="comparación" class="level3">
<h3 class="anchored" data-anchor-id="comparación">Comparación</h3>
<div class="tabla-ancha">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Modelo</th>
<th>Cuándo llega la primera señal de calidad</th>
<th>Control principal</th>
<th>Riesgo típico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cascada</td>
<td>Al final de cada fase, o en las pruebas finales</td>
<td>Revisión formal de cada documento</td>
<td>Defectos de requisitos que se descubren tarde</td>
</tr>
<tr class="even">
<td>Modelo en V</td>
<td>En la fase, con las pruebas ya planificadas</td>
<td>Pares de fase y prueba</td>
<td>Pruebas comprimidas por el cronograma</td>
</tr>
<tr class="odd">
<td>Iterativo e incremental</td>
<td>Al final de cada iteración</td>
<td>Prueba de regresión y revisión de riesgos</td>
<td>Incrementos que acumulan deuda técnica</td>
</tr>
<tr class="even">
<td>Ágil (Scrum)</td>
<td>Dentro del sprint</td>
<td>Definición de Terminado</td>
<td>Una definición débil que deja pasar defectos</td>
</tr>
<tr class="odd">
<td>Ágil (Kanban)</td>
<td>Cuando la tarjeta cambia de columna</td>
<td>Límite de trabajo en curso y políticas explícitas</td>
<td>Políticas que nadie hace cumplir</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="ejemplo-resuelto-la-misma-función-en-dos-modelos" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-la-misma-función-en-dos-modelos">Ejemplo resuelto: la misma función en dos modelos</h3>
<p>El equipo de la clínica debe entregar “cancelar y reprogramar un turno”. Mira cuándo se descubre un defecto de requisitos, por ejemplo olvidar que un turno ya atendido no se puede cancelar.</p>
<ol type="1">
<li>En cascada, el defecto sale cuando el equipo de pruebas ejecuta los casos de cancelación, en la semana 9 de un proyecto de 10.</li>
<li>En el modelo en V, sale en la revisión de requisitos de la semana 1, porque los criterios de la prueba de aceptación se escriben ahí y el caso “cancelar un turno atendido” lo exige.</li>
<li>En Scrum, sale en la planificación del sprint, cuando el equipo escribe los criterios de aceptación de la historia y alguien pregunta por ese caso.</li>
<li>En Kanban, sale cuando la tarjeta pasa a revisión de pares y la política exige criterios de aceptación escritos.</li>
</ol>
<p>El defecto es el mismo, y el modelo solo cambia cuándo y a qué costo se descubre. Ningún modelo garantiza que el control funcione. Cada uno necesita que alguien escriba el criterio y alguien lo haga cumplir.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Ubica el control en cada modelo
</div>
</div>
<div class="callout-body-container callout-body">
<p>La clínica quiere asegurar que “el cupo liberado por una cancelación pueda ser tomado por otro paciente en menos de 60 segundos”. Escribe, para el modelo en V y para Scrum, en qué momento escribirías el criterio de esa prueba y quién lo aprobaría. Después explica por qué la cascada pura lo haría tarde.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Modelo en V: el criterio nace con los requisitos, junto con la prueba de aceptación “cancelar y reservar el cupo en menos de 60 segundos”. Lo aprueba quien representa a la clínica, como el dueño del requisito.</li>
<li>Scrum: el criterio se escribe al refinar la historia, antes del sprint, y entra en la Definición de Terminado de esa historia. Lo acuerdan el dueño del producto y el equipo.</li>
<li>Cascada pura: el tiempo de liberación se mediría en las pruebas finales, y un valor de 5 minutos obligaría a rehacer diseño y código ya cerrados.</li>
</ul>
<p>Tu respuesta puede variar en los roles mientras ubique el criterio antes de construir.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-3.-cicd-y-devops" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="parte-3.-cicd-y-devops"><span class="header-section-number">6</span> Parte 3. CI/CD y DevOps</h2>
<section id="qué-cambia-con-la-entrega-continua" class="level3">
<h3 class="anchored" data-anchor-id="qué-cambia-con-la-entrega-continua">Qué cambia con la entrega continua</h3>
<p>En los modelos anteriores la calidad se inspecciona en puntos del calendario. La integración continua (CI) y la entrega continua (CD) la inspeccionan en cada cambio. Cada vez que un desarrollador envía código al repositorio, una serie de controles automáticos lo construye, lo prueba y decide si puede avanzar. A ese recorrido se le llama <em>pipeline</em> de entrega, o línea de despliegue.</p>
<p>DevOps es la cultura y el conjunto de prácticas que acercan desarrollo y operaciones, con el fin de entregar cambios pequeños y frecuentes con menos riesgo. Para la calidad significa tres cosas. Los cambios son pequeños, así que un defecto es más fácil de localizar. El pipeline automatiza las verificaciones repetibles. Y la operación en producción devuelve datos al equipo, que usa para corregir el rumbo.</p>
</section>
<section id="un-pipeline-con-puertas-de-calidad" class="level3">
<h3 class="anchored" data-anchor-id="un-pipeline-con-puertas-de-calidad">Un pipeline con puertas de calidad</h3>
<p>Un pipeline se organiza en etapas. Al final de cada etapa hay una puerta de calidad, un criterio que debe cumplirse para que el cambio avance. Si no se cumple, el cambio se detiene y el autor recibe aviso.</p>
<div class="diagrama">
<svg viewbox="0 0 760 270" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Pipeline de CI/CD con cinco etapas: confirmación del cambio con revisión de pares, construcción y pruebas rápidas, pruebas de integración, despliegue por anillos y observación en producción. Entre etapas hay puertas de calidad. Una flecha de retorno lleva los datos de producción de vuelta al inicio." font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u2t2b" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Un pipeline de entrega con puertas de calidad</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="12" y="40" width="130" height="86" rx="10"></rect><rect x="162" y="40" width="130" height="86" rx="10"></rect><rect x="312" y="40" width="130" height="86" rx="10"></rect><rect x="462" y="40" width="130" height="86" rx="10"></rect></g> <rect x="612" y="40" width="136" height="86" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u2t2b)"><path d="M142,83 L162,83"></path><path d="M292,83 L312,83"></path><path d="M442,83 L462,83"></path><path d="M592,83 L612,83"></path></g> <g fill="#fff6dc" stroke="#e6cf8a"><rect x="146" y="136" width="8" height="8"></rect><rect x="296" y="136" width="8" height="8"></rect><rect x="446" y="136" width="8" height="8"></rect><rect x="596" y="136" width="8" height="8"></rect></g> <g text-anchor="middle" font-size="12" font-weight="600" fill="#12324f"><text x="77" y="66">1. Cambio</text><text x="227" y="66">2. Construcción</text><text x="377" y="66">3. Integración</text><text x="527" y="66">4. Despliegue</text><text x="680" y="66" fill="#0e6f6c">5. Producción</text></g> <g text-anchor="middle" font-size="11" fill="#5b6876"><text x="77" y="86">revisión de pares</text><text x="77" y="100">análisis estático</text><text x="227" y="86">compila y corre</text><text x="227" y="100">pruebas unitarias</text><text x="377" y="86">pruebas de API</text><text x="377" y="100">y de seguridad</text><text x="527" y="86">por anillos con</text><text x="527" y="100">interruptores</text><text x="680" y="86">métricas, alertas</text><text x="680" y="100">y quejas</text></g> <g font-size="11" fill="#5b6876" text-anchor="middle"><text x="150" y="162">puerta</text><text x="300" y="162">puerta</text><text x="450" y="162">puerta</text><text x="600" y="162">puerta</text></g> <path d="M680,126 C680,200 400,230 77,230 C60,230 60,200 77,128" fill="none" stroke="#8fb3d1" stroke-width="1.8" stroke-dasharray="5 4" marker-end="url(#u2t2b)"></path> <text x="380" y="252" font-size="11" fill="#5b6876" text-anchor="middle">lo que se observa en producción vuelve al equipo y alimenta el siguiente cambio</text>
</svg>
</div>
<p>Cada etapa filtra defectos distintos. La revisión de pares y el análisis estático atrapan errores de escritura y de diseño local. Las pruebas unitarias atrapan fallas de lógica. Las pruebas de integración atrapan interfaces rotas. El despliegue por anillos, que libera el cambio a grupos crecientes de usuarios con observación entre grupos, limita el daño de lo que ninguna prueba vio. El Tema 3 de la Unidad 1 mostró lo que pasa cuando esa última defensa falta.</p>
</section>
<section id="ejemplo-resuelto-por-qué-el-pipeline-se-parte-en-niveles" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-por-qué-el-pipeline-se-parte-en-niveles">Ejemplo resuelto: por qué el pipeline se parte en niveles</h3>
<p>El equipo de la clínica integra unos 20 cambios por día. Su suite completa de pruebas tarda 50 minutos, y la puede ejecutar de dos maneras.</p>
<ol type="1">
<li>Todo en cada cambio. 20 cambios x 50 minutos = 1.000 minutos de ejecución al día, y cada desarrollador espera 50 minutos para saber si rompió algo.</li>
<li>Por niveles. Una etapa rápida de 5 minutos (compilación, pruebas unitarias, análisis estático) corre en cada cambio: 20 x 5 = 100 minutos. Una etapa de integración de 15 minutos corre solo al fusionar con la rama principal, unas 6 veces al día: 6 x 15 = 90 minutos. Las pruebas de extremo a extremo, de 30 minutos, corren una vez cada noche: 30 minutos.</li>
<li>Suma el segundo esquema. 100 + 90 + 30 = 220 minutos al día, contra 1.000. Ahorra 780 minutos, unas 13 horas de ejecución.</li>
<li>Lee el efecto en la calidad. El aviso de la mayoría de los defectos llega en 5 minutos y no en 50, y eso hace probable que el autor lo corrija mientras todavía recuerda el cambio.</li>
</ol>
<p>Los tiempos y el número de cambios son ilustrativos. Lo que se aprende es el razonamiento, es decir llevar los controles rápidos al lugar más frecuente y los lentos al menos frecuente, sin quitar ninguno.</p>
</section>
<section id="las-métricas-dora" class="level3">
<h3 class="anchored" data-anchor-id="las-métricas-dora">Las métricas DORA</h3>
<p>El programa de investigación DORA (<em>DevOps Research and Assessment</em>), de Google, mide el desempeño de la entrega de software con cinco métricas. DORA las lista en su guía vigente de la siguiente manera.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Métrica</th>
<th>Qué mide</th>
<th>Tipo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tiempo de entrega de un cambio (<em>change lead time</em>)</td>
<td>Tiempo que pasa desde que un cambio se confirma en el control de versiones hasta que está en producción</td>
<td>Rendimiento</td>
</tr>
<tr class="even">
<td>Frecuencia de despliegue (<em>deployment frequency</em>)</td>
<td>Número de despliegues en un periodo, o tiempo entre despliegues</td>
<td>Rendimiento</td>
</tr>
<tr class="odd">
<td>Tiempo de recuperación de un despliegue fallido (<em>failed deployment recovery time</em>)</td>
<td>Tiempo para restablecer el servicio tras un despliegue que requirió atención urgente</td>
<td>Rendimiento</td>
</tr>
<tr class="even">
<td>Tasa de fallo de cambios (<em>change fail rate</em>)</td>
<td>Proporción de despliegues que requieren intervención inmediata</td>
<td>Inestabilidad</td>
</tr>
<tr class="odd">
<td>Tasa de retrabajo (<em>deployment rework rate</em>)</td>
<td>Proporción de despliegues no planificados que ocurren como resultado de un incidente en producción</td>
<td>Inestabilidad</td>
</tr>
</tbody>
</table>
<p>Las tres primeras miden qué tan rápido se entrega. Las dos últimas miden qué tan estable es lo que se entrega. La lectura correcta mira las dos familias juntas, porque ir rápido a costa de la estabilidad no es mejora. El informe <em>Accelerate State of DevOps 2024</em> de DORA encontró que la adopción de inteligencia artificial aumenta la productividad individual pero afecta de forma negativa la estabilidad y el rendimiento de la entrega, y recomienda mantener lotes pequeños y pruebas sólidas para compensarlo.</p>
</section>
<section id="ejemplo-resuelto-las-métricas-de-la-clínica-en-un-mes" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-las-métricas-de-la-clínica-en-un-mes">Ejemplo resuelto: las métricas de la clínica en un mes</h3>
<p>En un mes, el equipo de la clínica registra lo siguiente.</p>
<ul>
<li>22 despliegues.</li>
<li>3 de esos despliegues requirieron intervención inmediata, con recuperaciones de 40, 90 y 20 minutos.</li>
<li>2 despliegues no planificados ocurrieron como resultado de un incidente en producción.</li>
<li>5 cambios medidos tardaron 1, 2, 2, 3 y 7 días entre la confirmación y la producción.</li>
</ul>
<p>Los cálculos son estos.</p>
<ol type="1">
<li>Frecuencia de despliegue: 22 en el mes, con unos 22 días hábiles, cerca de uno por día hábil.</li>
<li>Tasa de fallo de cambios: 3 / 22 = 13,6 %.</li>
<li>Tiempo de recuperación: promedio (40 + 90 + 20) / 3 = 50 minutos. La mediana es 40 minutos, y es la cifra menos sensible al caso de 90 minutos.</li>
<li>Tasa de retrabajo: 2 / 22 = 9,1 %.</li>
<li>Tiempo de entrega: la mediana de 1, 2, 2, 3 y 7 días es 2 días. El promedio sería 3, y el 7 lo infla.</li>
</ol>
<p>Con una muestra tan pequeña, las cifras sirven para empezar la conversación y no para comparar con otros equipos. DORA no fija un valor universal “bueno”. Cada equipo compara su propia tendencia mes a mes.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Lee las métricas
</div>
</div>
<div class="callout-body-container callout-body">
<p>El mes siguiente la clínica hace 30 despliegues. De ellos, 6 requieren intervención inmediata, con recuperaciones de 15, 20, 25, 30, 30 y 60 minutos. Calcula la tasa de fallo de cambios y la mediana del tiempo de recuperación. Después di si el equipo mejoró o empeoró frente al mes anterior y qué dos números usarías para sostener tu respuesta.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Tasa de fallo de cambios: 6 / 30 = 20 %.</li>
<li>Mediana de recuperación: ordenados son 15, 20, 25, 30, 30 y 60. Con seis datos, la mediana es el promedio de los dos centrales, (25 + 30) / 2 = 27,5 minutos.</li>
<li>Frente al mes anterior (13,6 % de fallos y mediana de 40 minutos), el equipo desplegó más (30 contra 22) y recuperó más rápido (27,5 contra 40 minutos), pero falló más veces en proporción (20 % contra 13,6 %).</li>
</ul>
<p>La respuesta honesta es que el resultado es mixto. Entrega más rápido y se recupera mejor, pero la estabilidad bajó. Los dos números que lo sostienen son la tasa de fallo de cambios, que empeoró, y el tiempo de recuperación, que mejoró. Faltaría saber por qué subieron los fallos antes de decidir qué controlar.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-4.-shift-left-shift-right-y-quality-engineering" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="parte-4.-shift-left-shift-right-y-quality-engineering"><span class="header-section-number">7</span> Parte 4. Shift-left, shift-right y quality engineering</h2>
<section id="shift-left" class="level3">
<h3 class="anchored" data-anchor-id="shift-left">Shift-left</h3>
<p>El principio <em>shift-left</em> (mover a la izquierda) consiste en llevar las actividades de calidad lo más temprano posible en la línea de tiempo del proyecto. El Tema 3 de la Unidad 1 lo presentó junto con la discusión sobre la curva de costo del defecto. Aquí interesa su aplicación fase por fase.</p>
<p>Algunas prácticas concretas de <em>shift-left</em> son revisar los requisitos antes de diseñar, escribir los criterios de aceptación antes de programar, hacer análisis de amenazas durante el diseño, ejecutar análisis estático al guardar el código, y escribir la prueba antes que el código, como en el desarrollo guiado por pruebas (TDD). El currículo de ISTQB para el nivel básico, en su versión 4.0, incluye un capítulo propio sobre las pruebas a lo largo del ciclo de vida y otro sobre pruebas estáticas, y declara que sus conceptos aplican por igual a cascada, ágil, DevOps y entrega continua.</p>
<p>El marco SSDF (<em>Secure Software Development Framework</em>), del NIST de Estados Unidos, lleva la misma idea a la seguridad. Su versión 1.1, de febrero de 2022 (NIST SP 800-218), organiza las prácticas en cuatro grupos: preparar la organización, proteger el software, producir software bien asegurado y responder a las vulnerabilidades. Los tres primeros caen casi por completo antes de la entrega. No se verificó en este tema si existe una versión posterior.</p>
</section>
<section id="shift-right" class="level3">
<h3 class="anchored" data-anchor-id="shift-right">Shift-right</h3>
<p>El principio <em>shift-right</em> (mover a la derecha) reconoce que ninguna prueba previa cubre todo lo que pasa con usuarios y datos reales. Lleva actividades de calidad al entorno de producción, con mecanismos para observar y limitar el daño. Algunas prácticas son monitorear métricas y alertas, activar funciones con interruptores (<em>feature flags</em>) para poder apagarlas, liberar a un grupo pequeño de usuarios antes que al resto (<em>canary release</em>), y estudiar los incidentes sin buscar culpables.</p>
<p>Mover a la derecha no sustituye a mover a la izquierda. El primero controla lo que no se pudo prever, y el segundo evita lo que sí se pudo. Un equipo que solo hace <em>shift-left</em> queda ciego ante lo que ocurre en producción, y uno que solo hace <em>shift-right</em> usa a sus usuarios como pruebas.</p>
<div class="diagrama">
<svg viewbox="0 0 760 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Línea de tiempo del ciclo de vida de izquierda a derecha, con cinco momentos: requisitos, diseño, construcción, pruebas y producción. Arriba, una flecha hacia la izquierda agrupa los controles tempranos. Abajo, una flecha hacia la derecha agrupa los controles en producción." font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u2t2c" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Dónde van los controles: a la izquierda y a la derecha</text> <line x1="40" y1="120" x2="720" y2="120" stroke="#8fb3d1" stroke-width="2"></line> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="30" y="100" width="110" height="40" rx="8"></rect><rect x="170" y="100" width="110" height="40" rx="8"></rect><rect x="310" y="100" width="110" height="40" rx="8"></rect><rect x="450" y="100" width="110" height="40" rx="8"></rect></g> <rect x="590" y="100" width="130" height="40" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g text-anchor="middle" font-size="12" font-weight="600" fill="#12324f"><text x="85" y="125">Requisitos</text><text x="225" y="125">Diseño</text><text x="365" y="125">Construcción</text><text x="505" y="125">Pruebas</text><text x="655" y="125">Producción</text></g> <rect x="30" y="38" width="390" height="40" rx="8" fill="#fff6dc" stroke="#e6cf8a"></rect> <path d="M410,58 L40,58" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u2t2c)"></path> <text x="225" y="53" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Shift-left</text> <text x="225" y="70" font-size="11" fill="#5b6876" text-anchor="middle">revisar, criterios de aceptación, TDD, análisis estático</text> <rect x="450" y="162" width="270" height="40" rx="8" fill="#fff6dc" stroke="#e6cf8a"></rect> <path d="M460,182 L710,182" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u2t2c)"></path> <text x="585" y="177" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Shift-right</text> <text x="585" y="194" font-size="11" fill="#5b6876" text-anchor="middle">monitoreo, interruptores, canary, postmortem</text> <text x="380" y="232" font-size="11" fill="#5b6876" text-anchor="middle">Los dos lados se complementan: uno evita lo previsible y el otro limita lo imprevisto</text>
</svg>
</div>
</section>
<section id="quality-engineering" class="level3">
<h3 class="anchored" data-anchor-id="quality-engineering">Quality engineering</h3>
<p><em>Quality engineering</em> (ingeniería de calidad) es el nombre que muchas organizaciones dan a un cambio de enfoque. En vez de tener un equipo de pruebas que revisa al final, la calidad se trata como una capacidad de ingeniería que se diseña, automatiza y mide a lo largo de todo el ciclo. Quien hace esto construye herramientas, pipelines y estrategias de prueba, y ayuda a los equipos a prevenir defectos y no solo a encontrarlos.</p>
<p>No existe una definición única y normativa del término, y el nombre del puesto varía mucho entre empresas. Lo que sí es estable es el contenido, que combina cuatro tareas.</p>
<ul>
<li>Definir qué significa calidad para el producto y cómo se mide.</li>
<li>Automatizar las verificaciones repetibles dentro del pipeline.</li>
<li>Acompañar al equipo para que la calidad esté en cada fase y no al final.</li>
<li>Usar los datos de producción para decidir dónde invertir.</li>
</ul>
<p>El Tema 3 describe los roles y las habilidades que sostienen esas tareas.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. Izquierda o derecha
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para cada control de la clínica, escribe si es <em>shift-left</em> o <em>shift-right</em>, y en qué fase vive.</p>
<ol type="1">
<li>Revisar con la recepcionista que el requisito de cancelación cubre los turnos ya atendidos.</li>
<li>Activar la cancelación con un interruptor para el 5 % de los pacientes durante la primera semana.</li>
<li>Una alerta cuando la cancelación falla más de 2 veces por cada 100 intentos.</li>
<li>Escribir la prueba “cancelar un turno atendido devuelve un error claro” antes de programar.</li>
<li>Un análisis posterior de por qué 14 pacientes recibieron un mensaje de cancelación equivocado.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><em>Shift-left</em>, en requisitos. Es una revisión que evita un defecto antes de diseñar.</li>
<li><em>Shift-right</em>, en liberación y operación. Limita el daño de lo que no se pudo prever a un grupo pequeño.</li>
<li><em>Shift-right</em>, en operación. Observa el comportamiento real con datos de producción.</li>
<li><em>Shift-left</em>, en construcción. La prueba va antes que el código, como en TDD.</li>
<li><em>Shift-right</em>, en operación y mantenimiento. Aprende de un incidente real sin buscar culpables.</li>
</ol>
<p>Observa que tres de los cinco son de la derecha. Un equipo maduro necesita controles en los dos lados.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-5.-la-matriz-de-actividades-de-calidad-por-fase" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="parte-5.-la-matriz-de-actividades-de-calidad-por-fase"><span class="header-section-number">8</span> Parte 5. La matriz de actividades de calidad por fase</h2>
<p>La matriz reúne lo que las partes anteriores explicaron. Las filas son las fases de un ciclo de vida genérico y las columnas son las cinco preguntas de la Parte 1. El modelo que uses cambia el orden y el tamaño, pero las actividades siguen siendo estas. Las que se describen con más detalle (revisiones técnicas, auditorías, gestión de configuración) se estudian en el Tema 4, y los roles en el Tema 3.</p>
<div class="tabla-ancha">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Fase</th>
<th>Actividad de calidad</th>
<th>Entradas</th>
<th>Salidas</th>
<th>Responsable</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Requisitos</td>
<td>Revisión de requisitos: completitud, consistencia, verificabilidad. Criterios de aceptación</td>
<td>Necesidades del usuario, reglas del negocio</td>
<td>Requisitos aprobados y criterios de aceptación escritos</td>
<td>Analista de requisitos, dueño del producto, SQA</td>
</tr>
<tr class="even">
<td>Requisitos</td>
<td>Análisis de riesgos del producto</td>
<td>Requisitos, contexto de uso</td>
<td>Lista de riesgos con prioridad y controles previstos</td>
<td>Dueño del producto, líder técnico</td>
</tr>
<tr class="odd">
<td>Diseño</td>
<td>Revisión técnica de la arquitectura y análisis de amenazas</td>
<td>Requisitos aprobados, riesgos</td>
<td>Decisiones de diseño revisadas, hallazgos cerrados</td>
<td>Arquitecto, revisores, SQA</td>
</tr>
<tr class="even">
<td>Diseño</td>
<td>Planificación de pruebas (estrategia y casos)</td>
<td>Requisitos, diseño</td>
<td>Plan de pruebas, casos diseñados, datos de prueba definidos</td>
<td>Ingeniero de pruebas</td>
</tr>
<tr class="odd">
<td>Construcción</td>
<td>Estándares de código, revisión de pares, análisis estático</td>
<td>Diseño, estándares del equipo</td>
<td>Código revisado, reporte del análisis, deuda técnica visible</td>
<td>Desarrolladores, revisor de pares</td>
</tr>
<tr class="even">
<td>Construcción</td>
<td>Pruebas unitarias y gestión de configuración</td>
<td>Código, casos unitarios</td>
<td>Pruebas pasando, versiones controladas</td>
<td>Desarrolladores</td>
</tr>
<tr class="odd">
<td>Verificación</td>
<td>Pruebas de integración, de sistema, de seguridad y de desempeño</td>
<td>Plan de pruebas, build candidato</td>
<td>Informe de pruebas, defectos registrados y priorizados</td>
<td>Ingeniero de pruebas, equipo</td>
</tr>
<tr class="even">
<td>Validación</td>
<td>Pruebas de aceptación y piloto con usuarios</td>
<td>Criterios de aceptación, build candidato</td>
<td>Acta de aceptación, observaciones del usuario</td>
<td>Dueño del producto, usuarios</td>
</tr>
<tr class="odd">
<td>Liberación</td>
<td>Revisión de criterios de salida y plan de despliegue y de reversión</td>
<td>Informe de pruebas, defectos abiertos</td>
<td>Decisión de liberar, plan de reversión probado</td>
<td>Líder de calidad, líder técnico</td>
</tr>
<tr class="even">
<td>Operación</td>
<td>Monitoreo, alertas, gestión de incidentes y soporte</td>
<td>Métricas de producción, reportes de usuarios</td>
<td>Incidentes registrados, métricas, solicitudes de cambio</td>
<td>Operaciones, soporte</td>
</tr>
<tr class="odd">
<td>Mantenimiento</td>
<td>Control de cambios, análisis de impacto y pruebas de regresión</td>
<td>Solicitud de cambio, código existente</td>
<td>Cambio aprobado, regresión ejecutada</td>
<td>Comité de cambios, desarrolladores</td>
</tr>
<tr class="even">
<td>Retiro</td>
<td>Plan de migración y retiro de datos</td>
<td>Decisión de retirar</td>
<td>Datos migrados o eliminados, cierre documentado</td>
<td>Líder del proyecto, operaciones</td>
</tr>
</tbody>
</table>
</div>
<p>Cuatro observaciones ayudan a leer la matriz.</p>
<ul>
<li>Cada fase tiene una salida que es la entrada de la siguiente. Una revisión de requisitos mal hecha contamina todo lo que sigue.</li>
<li>La verificación y la validación son filas separadas porque responden preguntas distintas.</li>
<li>El responsable es un rol, no una persona. En un equipo pequeño, una persona puede cubrir varios.</li>
<li>La matriz es una plantilla. Una organización la ajusta a su modelo, a su tamaño y al riesgo de su producto.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 4. Completa una fila
</div>
</div>
<div class="callout-body-container callout-body">
<p>La clínica añade un pago en línea de la consulta. Escribe, para la fase de diseño, una actividad de calidad específica de ese riesgo, su entrada, su salida y quién la ejecutaría. Después indica qué pasaría con los datos de tarjeta si esa actividad se omitiera.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Actividad: análisis de amenazas del flujo de pago, que revisa por dónde viajan y dónde se guardan los datos de tarjeta.</li>
<li>Entrada: el requisito de pago aprobado y el diagrama de la arquitectura.</li>
<li>Salida: lista de amenazas con su control, por ejemplo delegar el cobro a un proveedor certificado para no almacenar el número de la tarjeta.</li>
<li>Responsable: arquitecto, con apoyo de quien lidere la seguridad.</li>
</ul>
<p>Si se omite, el equipo podría diseñar un almacenamiento propio de números de tarjeta sin cifrar. Corregirlo después implicaría rediseñar y migrar datos ya guardados, lo que cuesta mucho más que decidirlo en el diseño.</p>
</div>
</div>
</div>
</section>
<section id="parte-6.-ejemplo-resuelto-efectividad-de-remoción-por-fase" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="parte-6.-ejemplo-resuelto-efectividad-de-remoción-por-fase"><span class="header-section-number">9</span> Parte 6. Ejemplo resuelto: efectividad de remoción por fase</h2>
<section id="el-concepto" class="level3">
<h3 class="anchored" data-anchor-id="el-concepto">El concepto</h3>
<p>Cada actividad de la matriz funciona como un filtro. Entran defectos, el filtro encuentra una parte y deja pasar el resto. La <em>efectividad de remoción de defectos</em> (DRE, de <em>defect removal effectiveness</em>) de una fase es la proporción de los defectos presentes en ella que esa fase encontró.</p>
<p>DRE de una fase = defectos encontrados en la fase / defectos presentes al entrar a la fase, incluidos los que la propia fase introdujo.</p>
<p>Stephen Kan formaliza esta métrica y su uso en <em>Metrics and Models in Software Quality Engineering</em>. El Tema 5 de esta unidad la retoma entre los modelos y las métricas.</p>
</section>
<section id="datos-de-la-función-cancelar-y-reprogramar-un-turno" class="level3">
<h3 class="anchored" data-anchor-id="datos-de-la-función-cancelar-y-reprogramar-un-turno">Datos de la función “cancelar y reprogramar un turno”</h3>
<p>El equipo de la clínica llevó la cuenta de los defectos de esta función, desde el origen hasta el primer mes de producción. Introdujo 30 defectos en requisitos, 22 en diseño y 48 en código, 100 en total. Las columnas son las siguientes.</p>
<div class="tabla-ancha">
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Filtro</th>
<th style="text-align: center;">Defectos que entran</th>
<th style="text-align: center;">Defectos hallados</th>
<th style="text-align: center;">DRE</th>
<th style="text-align: center;">Defectos que pasan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Revisión de requisitos</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">40 %</td>
<td style="text-align: center;">18</td>
</tr>
<tr class="even">
<td>Revisión de diseño</td>
<td style="text-align: center;">18 + 22 = 40</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">40 %</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="odd">
<td>Revisión de pares y pruebas unitarias</td>
<td style="text-align: center;">24 + 48 = 72</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">50 %</td>
<td style="text-align: center;">36</td>
</tr>
<tr class="even">
<td>Pruebas de integración y de sistema</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">66,7 %</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="odd">
<td>Aceptación y piloto</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">50 %</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td>Producción (primer mes)</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">100 %</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
</div>
<div class="diagrama">
<svg viewbox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Seis grupos de barras, una por filtro. Defectos que entran y defectos hallados: requisitos 30 y 12, diseño 40 y 16, código 72 y 36, integración y sistema 36 y 24, aceptación 12 y 6, producción 6 y 6." font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Defectos que entran y defectos hallados en cada filtro (cifras ilustrativas)</text> <line x1="50" y1="230" x2="730" y2="230" stroke="#cfd8e3" stroke-width="1.4"></line> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="62" y="160" width="36" height="70"></rect><rect x="176" y="136" width="36" height="94"></rect><rect x="290" y="62" width="36" height="168"></rect><rect x="404" y="146" width="36" height="84"></rect><rect x="518" y="202" width="36" height="28"></rect><rect x="632" y="216" width="36" height="14"></rect></g> <g fill="#e4f2f1" stroke="#8fc9c5"><rect x="102" y="202" width="36" height="28"></rect><rect x="216" y="192" width="36" height="38"></rect><rect x="330" y="146" width="36" height="84"></rect><rect x="444" y="174" width="36" height="56"></rect><rect x="558" y="216" width="36" height="14"></rect><rect x="672" y="216" width="36" height="14"></rect></g> <g font-size="11" font-weight="600" fill="#12324f" text-anchor="middle"><text x="80" y="154">30</text><text x="120" y="196">12</text><text x="194" y="130">40</text><text x="234" y="186">16</text><text x="308" y="56">72</text><text x="348" y="140">36</text><text x="422" y="140">36</text><text x="462" y="168">24</text><text x="536" y="196">12</text><text x="576" y="210">6</text><text x="650" y="210">6</text><text x="690" y="210">6</text></g> <g font-size="11" fill="#12324f" text-anchor="middle"><text x="100" y="250">Requisitos</text><text x="214" y="250">Diseño</text><text x="328" y="250">Código y</text><text x="328" y="264">unitarias</text><text x="442" y="250">Integración</text><text x="442" y="264">y sistema</text><text x="556" y="250">Aceptación</text><text x="670" y="250">Producción</text></g> <rect x="540" y="30" width="12" height="12" fill="#eef4fa" stroke="#c7d6e6"></rect><text x="558" y="40" font-size="11" fill="#5b6876">entran</text> <rect x="620" y="30" width="12" height="12" fill="#e4f2f1" stroke="#8fc9c5"></rect><text x="638" y="40" font-size="11" fill="#5b6876">hallados</text> <text x="380" y="288" font-size="11" fill="#5b6876" text-anchor="middle">Los 6 defectos que llegan a producción son los que ningún filtro anterior encontró</text>
</svg>
</div>
</section>
<section id="paso-a-paso" class="level3">
<h3 class="anchored" data-anchor-id="paso-a-paso">Paso a paso</h3>
<ol type="1">
<li>Calcula cada DRE. Requisitos 12 / 30 = 40 %. Diseño 16 / 40 = 40 %. Código 36 / 72 = 50 %. Integración y sistema 24 / 36 = 66,7 %. Aceptación 6 / 12 = 50 %.</li>
<li>Calcula la remoción antes de entregar. Los defectos hallados antes de producción son 12 + 16 + 36 + 24 + 6 = 94 de 100. La DRE global antes de entregar es 94 %.</li>
<li>Cuenta lo que escapó. Los 6 restantes llegaron a los pacientes.</li>
<li>Mira cuál filtro es el más débil. Los de requisitos y de diseño encuentran 40 %, es decir que dejan pasar 6 de cada 10 defectos presentes. Para esa etapa temprana, la revisión puede mejorar.</li>
</ol>
</section>
<section id="el-costo-del-hallazgo" class="level3">
<h3 class="anchored" data-anchor-id="el-costo-del-hallazgo">El costo del hallazgo</h3>
<p>El costo de corregir depende de la fase en que se halla el defecto. Supón estas horas por defecto, que son un ejemplo y no un dato de ninguna clínica: 1 hora en requisitos, 2 en diseño, 3 en código, 6 en integración y sistema, 8 en aceptación y 20 en producción (arreglo, soporte y citas perdidas). Una hora del equipo cuesta 60.000 pesos, como en el Tema 3 de la Unidad 1.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Filtro</th>
<th style="text-align: center;">Defectos</th>
<th style="text-align: center;">Horas por defecto</th>
<th style="text-align: center;">Horas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Requisitos</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="even">
<td>Diseño</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">32</td>
</tr>
<tr class="odd">
<td>Código y unitarias</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">108</td>
</tr>
<tr class="even">
<td>Integración y sistema</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">144</td>
</tr>
<tr class="odd">
<td>Aceptación</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">48</td>
</tr>
<tr class="even">
<td>Producción</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">120</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">464</td>
</tr>
</tbody>
</table>
<p>El total es 464 horas, es decir 464 x 60.000 = 27.840.000 pesos. Cuatro cosas salen de la tabla.</p>
<ol type="1">
<li>Los 94 defectos hallados antes de entregar cuestan 344 horas. Los 6 que llegaron a producción cuestan 120.</li>
<li>El 6 % de los defectos produce el 25,9 % del costo (120 / 464).</li>
<li>El promedio es 4,64 horas por defecto.</li>
<li>Integración, sistema y aceptación suman 192 de las 464 horas (41,4 %), porque hallan lo que los filtros tempranos dejaron pasar.</li>
</ol>
</section>
<section id="escenario-mejorar-la-revisión-de-requisitos" class="level3">
<h3 class="anchored" data-anchor-id="escenario-mejorar-la-revisión-de-requisitos">Escenario: mejorar la revisión de requisitos</h3>
<p>Supón que el equipo no hiciera la revisión de requisitos, cuyo esfuerzo fue de 16 horas, y que esos 12 defectos se hallaran después en las pruebas de sistema, a 6 horas cada uno.</p>
<ol type="1">
<li>Costo sin revisión: 12 x 6 = 72 horas de corrección. Costo con revisión: 12 x 1 = 12 horas de corrección más 16 de revisión = 28 horas.</li>
<li>Diferencia: 72 menos 28 son 44 horas a favor de la revisión.</li>
<li>Condición: el resultado supone que los defectos se habrían hallado en pruebas de sistema, y que la revisión de 16 horas no halló más que esos 12.</li>
</ol>
<p>Este tipo de cálculo no demuestra que revisar siempre se pague. Como se vio en el Tema 3 de la Unidad 1, los estudios empíricos discuten cuánto cuesta de verdad un defecto tardío, y por eso conviene medir las horas reales del propio equipo.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 5. Mejora la revisión de diseño
</div>
</div>
<div class="callout-body-container callout-body">
<p>El equipo propone una revisión de diseño más profunda, que cuesta 20 horas más. Con ella la DRE de diseño sube de 40 % a 60 %. Supón que los defectos extra que ahora se hallan en diseño se habrían hallado antes en integración y sistema. Calcula cuántos defectos extra se hallan, cuántas horas se ahorran con los costos de la tabla, y si la inversión se paga.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Defectos hallados con 60 %: 0,60 x 40 = 24. Con 40 % eran 16, así que se hallan 8 defectos extra.</li>
<li>Cada uno cuesta 2 horas en diseño y habría costado 6 en integración y sistema. Se ahorran 6 menos 2 = 4 horas por defecto, y 8 x 4 = 32 horas.</li>
<li>La inversión es de 20 horas. La ganancia neta es 32 menos 20 = 12 horas, así que se paga, aunque con un margen modesto.</li>
</ul>
<p>El margen es modesto y depende de los supuestos de costo. Si los defectos extra se hubieran hallado en código a 3 horas, el ahorro sería 8 x 1 = 8 horas y la inversión no se pagaría. Por eso el cálculo exige conocer en qué fase se habrían hallado.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-7.-ejemplo-resuelto-plan-de-calidad-por-fase-de-la-app" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="parte-7.-ejemplo-resuelto-plan-de-calidad-por-fase-de-la-app"><span class="header-section-number">10</span> Parte 7. Ejemplo resuelto: plan de calidad por fase de la app</h2>
<section id="qué-es-un-plan-de-calidad-por-fase" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-un-plan-de-calidad-por-fase">Qué es un plan de calidad por fase</h3>
<p>Un plan de calidad por fase fija, para cada fase de una función, cuál es el objetivo medible, qué actividades se ejecutan, cuál es el criterio de salida y qué evidencia queda. Es el resultado de aplicar la matriz de la Parte 5 a un producto concreto. Se escribe al comienzo, con la información que existe, y se ajusta mientras avanza el proyecto.</p>
<p>La función es “cancelar y reprogramar un turno”. Su requisito, escrito para que se pueda verificar, es “un paciente puede cancelar un turno hasta 2 horas antes de la cita, el cupo queda disponible para otro paciente en menos de 60 segundos, y la app envía un mensaje de confirmación”.</p>
</section>
<section id="el-plan" class="level3">
<h3 class="anchored" data-anchor-id="el-plan">El plan</h3>
<div class="tabla-ancha">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Fase</th>
<th>Objetivo medible</th>
<th>Actividades</th>
<th>Criterio de salida</th>
<th>Evidencia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Requisitos</td>
<td>0 requisitos ambiguos o sin criterio de aceptación</td>
<td>Revisión con recepción y con un paciente, lista de casos límite (turno atendido, turno de otro paciente, cita a menos de 2 horas)</td>
<td>Cada requisito con al menos un criterio de aceptación escrito</td>
<td>Acta de revisión, matriz de requisitos y criterios</td>
</tr>
<tr class="even">
<td>Diseño</td>
<td>Ningún dato de salud viaja sin cifrar. El cupo se libera de forma atómica</td>
<td>Revisión técnica de la arquitectura, análisis de amenazas, diseño de la concurrencia del cupo</td>
<td>Hallazgos de la revisión cerrados</td>
<td>Diagrama revisado, lista de amenazas con control</td>
</tr>
<tr class="odd">
<td>Construcción</td>
<td>Código revisado por un par antes de fusionar. Cobertura de pruebas unitarias mínima de 80 % en el módulo nuevo (valor ilustrativo)</td>
<td>Revisión de pares, análisis estático, pruebas unitarias, TDD en las reglas de cancelación</td>
<td>Pipeline en verde y 0 hallazgos críticos del análisis estático</td>
<td>Reporte del pipeline, reporte de cobertura</td>
</tr>
<tr class="even">
<td>Verificación</td>
<td>0 defectos críticos abiertos. Liberación de cupo en menos de 60 segundos en el percentil 95</td>
<td>Pruebas de integración, de sistema, de seguridad y de carga con 200 usuarios simultáneos (valor ilustrativo)</td>
<td>Casos de prueba ejecutados y defectos críticos cerrados</td>
<td>Informe de pruebas, resultados de la carga</td>
</tr>
<tr class="odd">
<td>Validación</td>
<td>8 de 10 pacientes de un piloto completan la cancelación sin ayuda (valor ilustrativo)</td>
<td>Piloto con pacientes reales en una sede, observación del uso</td>
<td>Acta de aceptación del dueño del producto</td>
<td>Registro del piloto, observaciones</td>
</tr>
<tr class="even">
<td>Liberación</td>
<td>Reversión probada en menos de 10 minutos</td>
<td>Revisión de criterios de salida, ensayo de reversión, despliegue por anillos con interruptor</td>
<td>Lista de salida firmada y reversión ensayada</td>
<td>Lista de salida, registro del ensayo</td>
</tr>
<tr class="odd">
<td>Operación</td>
<td>Detectar una falla de cancelación en menos de 15 minutos</td>
<td>Alerta sobre la tasa de error, tablero de métricas, revisión semanal de reclamos</td>
<td>Alertas activas y tablero publicado</td>
<td>Configuración de alertas, reporte semanal</td>
</tr>
<tr class="even">
<td>Mantenimiento</td>
<td>Todo cambio con regresión ejecutada</td>
<td>Control de cambios, análisis de impacto, regresión automática</td>
<td>Regresión en verde antes de cada liberación</td>
<td>Registro de cambios, reporte de regresión</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="cómo-leer-el-plan" class="level3">
<h3 class="anchored" data-anchor-id="cómo-leer-el-plan">Cómo leer el plan</h3>
<p>Tres detalles distinguen un plan útil de una lista de buenas intenciones.</p>
<ol type="1">
<li>Cada objetivo se puede medir. “Buena calidad” no sirve. “Liberación de cupo en menos de 60 segundos en el percentil 95” sí, porque alguien puede comprobarlo.</li>
<li>Cada fase tiene criterio de salida. Sin criterio, la fase se cierra por fecha y no por evidencia.</li>
<li>La evidencia existe y queda guardada. Si no hay evidencia, la actividad no se puede auditar.</li>
</ol>
<p>Los valores marcados como ilustrativos (80 % de cobertura, 200 usuarios simultáneos, 8 de 10 pacientes) son decisiones que cada equipo toma según su riesgo. Subirlos tiene costo, y por eso se fijan al comienzo y se justifican.</p>
</section>
<section id="ejemplo-resuelto-aplicar-el-criterio-de-salida" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-aplicar-el-criterio-de-salida">Ejemplo resuelto: aplicar el criterio de salida</h3>
<p>Al final de la fase de verificación, el informe de la clínica muestra lo siguiente.</p>
<ul>
<li>4 defectos críticos abiertos, 2 de ellos en la liberación del cupo.</li>
<li>Liberación de cupo: 38 segundos en el percentil 95.</li>
<li>Carga de 200 usuarios simultáneos sin errores.</li>
</ul>
<p>Decide si la función puede pasar a validación.</p>
<ol type="1">
<li>Revisa los criterios. Se exigía 0 defectos críticos abiertos y la liberación del cupo menor a 60 segundos en el percentil 95.</li>
<li>Compara. La liberación (38 segundos) cumple. La carga cumple. Los defectos críticos (4) no cumplen.</li>
<li>Decide. La función no pasa a validación. Se cierran los 4 defectos críticos y se vuelve a ejecutar lo afectado.</li>
<li>Registra. El acta dice que se detuvo la fase y por qué, y eso es evidencia del proceso.</li>
</ol>
<p>Un cumplimiento parcial no basta. Si un criterio falla, la fase no se cierra, aunque los demás se cumplan.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 6. Escribe una fila
</div>
</div>
<div class="callout-body-container callout-body">
<p>Añade al plan una fila de la fase de liberación para una regla nueva: “la cancelación debe seguir funcionando si el proveedor de mensajes está caído”. Define un objetivo medible, dos actividades, un criterio de salida y la evidencia. Indica además qué defecto o falla impediría cerrar la fase.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Objetivo medible: con el proveedor de mensajes apagado, el 100 % de las cancelaciones se registra, y los mensajes se reintentan al volver el servicio.</li>
<li>Actividades: una prueba de caos dirigida que apaga el proveedor en el entorno de pruebas, y un ensayo de reversión del despliegue.</li>
<li>Criterio de salida: ninguna cancelación perdida en la prueba, y mensajes enviados en un máximo de 30 minutos tras la recuperación.</li>
<li>Evidencia: informe de la prueba con el número de cancelaciones y mensajes, y el registro del ensayo de reversión.</li>
<li>Falla que impediría cerrar: que una cancelación se pierda o que el cupo no se libere cuando el mensaje falla.</li>
</ul>
<p>Tu respuesta puede variar en los valores mientras sean medibles y tengan evidencia.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-8.-caso-real-el-boeing-737-max-y-el-sistema-mcas" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="parte-8.-caso-real-el-boeing-737-max-y-el-sistema-mcas"><span class="header-section-number">11</span> Parte 8. Caso real: el Boeing 737 MAX y el sistema MCAS</h2>
<section id="por-qué-este-caso" class="level3">
<h3 class="anchored" data-anchor-id="por-qué-este-caso">Por qué este caso</h3>
<p>El caso del 737 MAX no sirve para aprender de aviación sino para ver, en un producto real y con documentos oficiales, qué ocurre cuando varias actividades de calidad fallan en fases distintas. Cada control que se estudió en este tema tiene aquí un ejemplo de su ausencia. Antes de leerlo, piensa qué fase de la matriz de la Parte 5 crees que falló más.</p>
</section>
<section id="los-hechos" class="level3">
<h3 class="anchored" data-anchor-id="los-hechos">Los hechos</h3>
<p>El 29 de octubre de 2018 se estrelló el vuelo 610 de Lion Air, con 189 muertos. El 10 de marzo de 2019 se estrelló el vuelo 302 de Ethiopian Airlines, con 157 muertos. Los dos accidentes suman 346 víctimas. La FAA ordenó mantener los aviones en tierra el 13 de marzo de 2019. El Boeing 737 MAX volvió a servicio el 18 de noviembre de 2020, tras 619 días.</p>
<p>El sistema MCAS (<em>Maneuvering Characteristics Augmentation System</em>) está en el centro de los dos accidentes. Es un software diseñado para ayudar a controlar la tendencia del avión a levantar el morro en ciertas condiciones, causada por motores más grandes y colocados en otra posición. En su diseño original dependía de la lectura de un solo sensor de ángulo de ataque. Si ese sensor entregaba un valor erróneo, MCAS podía empujar el morro hacia abajo de forma repetida.</p>
<p>Estos son los hechos que respaldan los informes y las fuentes oficiales consultadas.</p>
<ul>
<li>La investigación indonesia del accidente de Lion Air (informe final de octubre de 2019) identificó nueve factores que contribuyeron. El software MCAS se activó con datos de un sensor de ángulo de ataque mal instalado, y el informe criticó los análisis de seguridad del diseño y la falta de información de MCAS en el manual y en el entrenamiento.</li>
<li>La investigación etíope del accidente de Ethiopian (informe final del 23 de diciembre de 2022) señaló como causa más probable las entradas repetidas y no ordenadas de MCAS por un valor erróneo de ese sensor, con una activación que la tripulación no pudo recuperar. La NTSB de Estados Unidos y el BEA francés publicaron comentarios propios sobre ese informe.</li>
<li>El informe final del Comité de Transporte e Infraestructura de la Cámara de Representantes (septiembre de 2020) concluyó que el diseño y desarrollo del MAX estuvo marcado por fallas técnicas, falta de transparencia con reguladores y clientes, y esfuerzos para ocultar información sobre la operación del avión.</li>
<li>Ese mismo informe documentó que MCAS no se mencionaba en el manual de los pilotos, y que ingenieros de Boeing plantearon preocupaciones sobre el uso de un solo sensor durante el desarrollo.</li>
<li>Según el informe del comité, ciertos modos de falla que podían activar MCAS sin orden, como un valor alto erróneo de ángulo de ataque, no se simularon en la validación del análisis de riesgos funcionales, y por eso otros efectos de la misma falla no se documentaron.</li>
<li>Según la cobertura del informe, Boeing supuso que las tripulaciones reaccionarían a una activación errónea de MCAS en unos cuatro segundos, mientras que en una prueba de 2012 un piloto de Boeing tardó más de diez segundos.</li>
<li>Un análisis de la FAA de diciembre de 2018, hecho poco después del primer accidente, estimó que, sin cambios en MCAS, el MAX tendría unos 15,4 accidentes fatales a lo largo de la vida de una flota de 4.800 aviones.</li>
<li>El Departamento de Justicia de Estados Unidos y Boeing llegaron en enero de 2021 a un acuerdo por 2.500 millones de dólares por cargos de fraude relacionados con el 737 MAX.</li>
<li>Para volver al servicio, la FAA exigió que MCAS use datos de dos sensores de ángulo de ataque y un nuevo entrenamiento en simulador.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Sobre las fuentes de este caso
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los documentos oficiales completos (el informe de la Cámara, los informes de las investigaciones de Indonesia y de Etiopía, y los comunicados de la FAA) están citados en la bibliografía. Varios hechos de esta parte se confirmaron por medio de resúmenes y cobertura de esos documentos y no por una lectura directa del texto completo, porque los sitios de las agencias no estaban accesibles en la consulta. Los números de página y las citas literales de los informes no se reproducen.</p>
</div>
</div>
</section>
<section id="dónde-faltó-cada-control" class="level3">
<h3 class="anchored" data-anchor-id="dónde-faltó-cada-control">Dónde faltó cada control</h3>
<p>El caso se entiende mejor al mapearlo a las fases de la matriz. La tabla propone una lectura. Es un análisis docente con base en los hechos anteriores, y no una conclusión de los informes.</p>
<div class="diagrama">
<svg viewbox="0 0 760 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cinco fases con el control que faltó en cada una en el caso del Boeing 737 MAX: en requisitos y diseño, un solo sensor de ángulo de ataque; en diseño, supuestos sobre la reacción de los pilotos; en verificación, modos de falla no simulados; en liberación, MCAS ausente del manual y el entrenamiento; en operación, el riesgo estimado tras el primer accidente sin que se detuviera la flota." font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u2t2d" markerwidth="9" markerheight="9" refx="7" refy="2.8" orient="auto"><path d="M0,0 L7,2.8 L0,5.6 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">737 MAX: el control que faltó en cada fase</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="10" y="36" width="140" height="44" rx="8"></rect><rect x="162" y="36" width="140" height="44" rx="8"></rect><rect x="314" y="36" width="140" height="44" rx="8"></rect><rect x="466" y="36" width="140" height="44" rx="8"></rect><rect x="618" y="36" width="132" height="44" rx="8"></rect></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#u2t2d)"><path d="M150,58 L162,58"></path><path d="M302,58 L314,58"></path><path d="M454,58 L466,58"></path><path d="M606,58 L618,58"></path></g> <g text-anchor="middle" font-size="12" font-weight="600" fill="#12324f"><text x="80" y="63">Requisitos</text><text x="232" y="63">Diseño</text><text x="384" y="63">Verificación</text><text x="536" y="63">Liberación</text><text x="684" y="63">Operación</text></g> <g fill="#fbeae5" stroke="#e0a595"><rect x="10" y="100" width="140" height="150" rx="8"></rect><rect x="162" y="100" width="140" height="150" rx="8"></rect><rect x="314" y="100" width="140" height="150" rx="8"></rect><rect x="466" y="100" width="140" height="150" rx="8"></rect><rect x="618" y="100" width="132" height="150" rx="8"></rect></g> <g text-anchor="middle" font-size="11" fill="#12324f"><text x="80" y="124">Un solo sensor</text><text x="80" y="139">de ángulo de</text><text x="80" y="154">ataque como</text><text x="80" y="169">entrada de un</text><text x="80" y="184">sistema con</text><text x="80" y="199">autoridad sobre</text><text x="80" y="214">el estabilizador</text><text x="232" y="124">Se supuso que</text><text x="232" y="139">la tripulación</text><text x="232" y="154">reaccionaría en</text><text x="232" y="169">unos cuatro</text><text x="232" y="184">segundos. Un</text><text x="232" y="199">piloto tardó</text><text x="232" y="214">más de diez</text><text x="384" y="124">Fallas que</text><text x="384" y="139">activaban MCAS</text><text x="384" y="154">sin orden no</text><text x="384" y="169">se simularon</text><text x="384" y="184">en la validación</text><text x="384" y="199">del análisis de</text><text x="384" y="214">riesgos</text><text x="536" y="124">MCAS no figuraba</text><text x="536" y="139">en el manual de</text><text x="536" y="154">los pilotos, y</text><text x="536" y="169">hubo presión para</text><text x="536" y="184">evitar simulador</text><text x="536" y="199">en el entrenamiento</text><text x="684" y="124">La FAA estimó en</text><text x="684" y="139">dic. de 2018 unos</text><text x="684" y="154">15,4 accidentes</text><text x="684" y="169">fatales sin cambio.</text><text x="684" y="184">La flota siguió</text><text x="684" y="199">volando hasta el</text><text x="684" y="214">segundo accidente</text></g> <text x="380" y="276" font-size="11" fill="#5b6876" text-anchor="middle">Cada caja roja es un control que la matriz de la Parte 5 prevé en esa fase</text> <text x="380" y="296" font-size="11" fill="#5b6876" text-anchor="middle">El sistema falló por la suma de varias ausencias y no por un solo defecto de código</text>
</svg>
</div>
<div class="tabla-ancha">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Fase</th>
<th>Control que la matriz prevé</th>
<th>Qué muestran los hechos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Requisitos</td>
<td>Análisis de riesgos del producto</td>
<td>Un sistema con autoridad sobre el estabilizador se apoyó en un solo sensor, y ingenieros de Boeing lo cuestionaron durante el desarrollo</td>
</tr>
<tr class="even">
<td>Diseño</td>
<td>Revisión técnica y análisis de amenazas</td>
<td>Supuestos de reacción de la tripulación que una prueba de 2012 contradecía</td>
</tr>
<tr class="odd">
<td>Verificación</td>
<td>Pruebas de integración y de sistema</td>
<td>Modos de falla que activaban MCAS sin orden no se simularon</td>
</tr>
<tr class="even">
<td>Liberación</td>
<td>Revisión de criterios de salida y documentación</td>
<td>MCAS no se mencionaba en el manual de los pilotos</td>
</tr>
<tr class="odd">
<td>Operación</td>
<td>Monitoreo y gestión de incidentes</td>
<td>El riesgo estimado tras el primer accidente no detuvo la operación de la flota</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="la-auditoría-de-la-faa-de-2024" class="level3">
<h3 class="anchored" data-anchor-id="la-auditoría-de-la-faa-de-2024">La auditoría de la FAA de 2024</h3>
<p>En enero de 2024 hubo un incidente con un 737 MAX 9 de Alaska Airlines en pleno vuelo, con la pérdida de un tapón de puerta. A raíz de eso, la FAA realizó una auditoría especial de seis semanas a la producción del 737. Según la cobertura de prensa del resumen de la FAA, Boeing superó 56 de las 89 auditorías de producto que se le hicieron y no superó 33, con 97 casos de incumplimiento. En las 13 auditorías a Spirit AeroSystems, proveedor del fuselaje, 6 se aprobaron y 7 no. Muchos de los problemas se relacionaban con no seguir los procesos de manufactura aprobados y con no mantener la documentación de control de calidad.</p>
<p>El 28 de febrero de 2024, el administrador de la FAA, Michael Whitaker, comunicó a Boeing que debía presentar un plan de acción integral en 90 días que incorporara los resultados de la auditoría y los hallazgos del panel de expertos que la ley de 2020 había exigido. La FAA señaló incumplimientos en el control de procesos de manufactura, el manejo y almacenamiento de piezas y el control del producto. El panel de expertos encontró, entre otras cosas, que los estándares de seguridad de Boeing podían ser demasiado complejos y confundir a los empleados.</p>
<p>Esta auditoría corresponde a otro momento y a otro problema, la calidad de la producción del 737 MAX 9, y no al diseño de MCAS. Sirve para completar la lectura. Una organización que falla en el diseño puede fallar también en el proceso de fabricación, y los dos casos muestran que la calidad es una propiedad de todo el ciclo de vida y no de una fase.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Sobre estas cifras de 2024
</div>
</div>
<div class="callout-body-container callout-body">
<p>Las cifras de la auditoría (89, 56, 33, 97, 13, 6 y 7) provienen de la cobertura de prensa del resumen de la FAA. No se pudo leer el documento original de la agencia en la consulta. Antes de citarlas en un trabajo, confirma cada una en el sitio de la FAA.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 7. Mapa del caso
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un compañero afirma que el desastre del 737 MAX fue “un bug de software”. Escribe tres razones por las que esa frase es incompleta, cada una con una fase del ciclo de vida. Después propón un control concreto de la matriz que habría reducido el riesgo en una de esas fases.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Requisitos y diseño: el diseño dependía de un solo sensor para una función con alta autoridad. Eso es una decisión de arquitectura y de análisis de riesgos, y no un error de una línea de código.</li>
<li>Verificación: ciertos modos de falla que activaban MCAS sin orden no se simularon. Una verificación más amplia habría expuesto la dependencia del sensor.</li>
<li>Liberación y documentación: MCAS no se mencionaba en el manual de los pilotos, de modo que quien lo operaba no sabía que existía.</li>
<li>Control propuesto, por ejemplo: una revisión técnica del diseño con revisores independientes del equipo, que cuestionara por escrito el uso de un solo sensor y exigiera la redundancia antes de pasar a verificación.</li>
</ul>
<p>Tu respuesta puede variar mientras cada razón tenga una fase y un hecho.</p>
</div>
</div>
</div>
</section>
</section>
<section id="errores-frecuentes" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="errores-frecuentes"><span class="header-section-number">12</span> Errores frecuentes</h2>
<ul>
<li>Creer que la calidad es una fase. La norma 12207 la trata como un proceso que acompaña a todos los demás.</li>
<li>Confundir verificación con validación. Una cumple la especificación, y la otra sirve a la necesidad.</li>
<li>Citar IEEE 730-2014 o ISO/IEC/IEEE 12207:2017 como vigentes en 2026 sin revisar la edición.</li>
<li>Usar el modelo en V sin respetar el cronograma de las pruebas. Si se comprimen al final, se pierde la ventaja.</li>
<li>Escribir una Definición de Terminado de una línea, como “funciona”, que no detiene nada.</li>
<li>Medir solo la velocidad de entrega. Las métricas DORA se leen en pares, rendimiento e inestabilidad.</li>
<li>Hacer solo shift-left o solo shift-right. Cada lado cubre lo que el otro no ve.</li>
<li>Cerrar una fase por fecha y no por criterio de salida.</li>
<li>Reducir el caso del 737 MAX a un bug de software, y olvidar el análisis de riesgos, la verificación y la documentación.</li>
<li>Dar cifras de casos o de normas sin fuente. En esta guía, cada cifra indica de dónde sale.</li>
</ul>
</section>
<section id="autoevaluación" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="autoevaluación"><span class="header-section-number">13</span> Autoevaluación</h2>
<p>Responde cada pregunta sin mirar la guía y después abre la clave.</p>
<p><strong>1.</strong> ¿Qué idea distingue al modelo en V de la cascada pura?</p>
<p><label><input type="checkbox"> Cada fase de especificación o diseño tiene su prueba planificada al mismo tiempo</label> <label><input type="checkbox"> No tiene pruebas, solo revisiones</label> <label><input type="checkbox"> Cada fase dura exactamente la misma cantidad de tiempo</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Los criterios de aceptación se escriben con los requisitos, y las pruebas de integración se definen con la arquitectura.</p>
</div>
</div>
</div>
<p><strong>2.</strong> Una revisión de requisitos que busca contradicciones entre ellos es:</p>
<p><label><input type="checkbox"> Verificación</label> <label><input type="checkbox"> Validación</label> <label><input type="checkbox"> Control de configuración</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Compara los requisitos entre sí contra una regla de consistencia. La validación compara el producto contra la necesidad real.</p>
</div>
</div>
</div>
<p><strong>3.</strong> ¿Cuál es la edición vigente de ISO/IEC/IEEE 12207 en octubre de 2026?</p>
<p><label><input type="checkbox"> La de 2017</label> <label><input type="checkbox"> La de 2026, publicada en abril</label> <label><input type="checkbox"> La de 2008</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Es la segunda edición y sustituye a la de 2017, según el catálogo de ISO y la ficha de IEEE.</p>
</div>
</div>
</div>
<p><strong>4.</strong> ¿Qué edición de IEEE 730 sustituyó a la de 2014?</p>
<p><label><input type="checkbox"> IEEE 730-2026, publicada en agosto de 2026</label> <label><input type="checkbox"> IEEE 730-2002</label> <label><input type="checkbox"> Ninguna, la de 2014 sigue activa</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. La de 2014 quedó inactiva-reservada en marzo de 2025.</p>
</div>
</div>
</div>
<p><strong>5.</strong> En Scrum, ¿qué es la Definición de Terminado?</p>
<p><label><input type="checkbox"> Una descripción formal del estado del incremento cuando cumple las medidas de calidad exigidas</label> <label><input type="checkbox"> La fecha de entrega del proyecto</label> <label><input type="checkbox"> El informe final del auditor</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1, según la Guía de Scrum 2020. Un elemento no está terminado hasta que cumple esa definición.</p>
</div>
</div>
</div>
<p><strong>6.</strong> ¿Cuál de estas prácticas es <em>shift-right</em>?</p>
<p><label><input type="checkbox"> Escribir criterios de aceptación antes de programar</label> <label><input type="checkbox"> Liberar a un grupo pequeño de usuarios con un interruptor y observar</label> <label><input type="checkbox"> Revisar los requisitos antes del diseño</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Lleva el control a producción para limitar el daño de lo que no se previó.</p>
</div>
</div>
</div>
<p><strong>7.</strong> Un filtro tiene 50 defectos presentes y halla 35. ¿Cuál es su DRE?</p>
<p><label><input type="checkbox"> 30 %</label> <label><input type="checkbox"> 70 %</label> <label><input type="checkbox"> 85 %</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. 35 / 50 = 0,70, es decir 70 %. Quedan 15 defectos que pasan al siguiente filtro.</p>
</div>
</div>
</div>
<p><strong>8.</strong> Un equipo hace 25 despliegues y 4 requieren intervención inmediata. ¿Cuál es su tasa de fallo de cambios?</p>
<p><label><input type="checkbox"> 4 %</label> <label><input type="checkbox"> 16 %</label> <label><input type="checkbox"> 25 %</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. 4 / 25 = 0,16, es decir 16 %. Es una métrica de inestabilidad en la lista de DORA.</p>
</div>
</div>
</div>
<p><strong>9.</strong> ¿Qué hecho del diseño original de MCAS es central en los dos accidentes del 737 MAX?</p>
<p><label><input type="checkbox"> Dependía de un solo sensor de ángulo de ataque</label> <label><input type="checkbox"> Funcionaba sin software</label> <label><input type="checkbox"> Usaba tres sensores en paralelo</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Un valor erróneo de ese sensor podía empujar el morro hacia abajo de forma repetida. Para volver al servicio, la FAA exigió datos de dos sensores.</p>
</div>
</div>
</div>
<p><strong>10.</strong> ¿Por qué un pipeline se parte en etapas de distinta duración?</p>
<p><label><input type="checkbox"> Para que los controles rápidos corran en cada cambio y los lentos con menos frecuencia, sin quitar ninguno</label> <label><input type="checkbox"> Para reducir el número de pruebas que existen</label> <label><input type="checkbox"> Para que el equipo no vea los resultados</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 10
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Una etapa rápida en cada cambio da aviso en minutos, y las etapas lentas corren menos veces, por ejemplo al fusionar o cada noche. En el ejemplo de la clínica se pasó de 1.000 a 220 minutos de ejecución al día.</p>
</div>
</div>
</div>
</section>
<section id="lo-que-te-llevas" class="level2" data-number="14">
<h2 data-number="14" class="anchored" data-anchor-id="lo-que-te-llevas"><span class="header-section-number">14</span> Lo que te llevas</h2>
<div class="checklist">
<p><strong>Al salir de este tema deberías poder explicar, sin mirar la guía</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Las cinco preguntas que ubican una actividad de calidad en una fase, y la diferencia entre verificar y validar</label></li>
<li><label><input type="checkbox">Qué hace ISO/IEC/IEEE 12207 y cuál es su edición vigente, y cuál es la edición vigente de IEEE 730</label></li>
<li><label><input type="checkbox">Dónde llega la primera señal de calidad en cascada, modelo en V, iterativo, Scrum y Kanban</label></li>
<li><label><input type="checkbox">Qué es un pipeline con puertas de calidad y cómo se leen las cinco métricas DORA</label></li>
<li><label><input type="checkbox">La diferencia entre shift-left, shift-right y quality engineering, con un ejemplo de cada uno</label></li>
<li><label><input type="checkbox">Cómo se lee la matriz de actividades por fase, con entradas, salidas y responsable</label></li>
<li><label><input type="checkbox">Cómo se calcula la DRE de un filtro y el costo de los hallazgos por fase</label></li>
<li><label><input type="checkbox">Qué contiene un plan de calidad por fase y cómo se aplica un criterio de salida</label></li>
<li><label><input type="checkbox">Qué fallas de fase muestra el caso del Boeing 737 MAX y por qué no fue solo un bug</label></li>
</ul>
</div>
</section>
<section id="glosario" class="level2" data-number="15">
<h2 data-number="15" class="anchored" data-anchor-id="glosario"><span class="header-section-number">15</span> Glosario</h2>
<ul>
<li><strong>Actividad de calidad.</strong> Control que se ejecuta en una fase del ciclo de vida para prevenir o detectar defectos.</li>
<li><strong>Aseguramiento de la calidad (SQA).</strong> Conjunto de actividades preventivas que vigilan que el proceso de construcción sea adecuado.</li>
<li><strong>Cascada.</strong> Modelo de ciclo de vida en el que las fases ocurren una tras otra y cada una cierra antes de la siguiente.</li>
<li><strong>Modelo en V.</strong> Variante de la secuencia en la que cada fase de especificación o diseño tiene su prueba planificada al mismo tiempo.</li>
<li><strong>Iterativo e incremental.</strong> Modelo que repite ciclos cortos y entrega una parte del producto en cada uno.</li>
<li><strong>Modelo en espiral.</strong> Modelo propuesto por Boehm en 1988 que añade el análisis de riesgos al comienzo de cada vuelta.</li>
<li><strong>Scrum.</strong> Marco ágil que organiza el trabajo en sprints, con roles, eventos y artefactos definidos en la Guía de Scrum.</li>
<li><strong>Definición de Terminado.</strong> Descripción formal del estado del incremento cuando cumple las medidas de calidad que el producto exige.</li>
<li><strong>Kanban.</strong> Método ágil que gestiona el flujo de trabajo en un tablero, con límite de trabajo en curso y políticas explícitas.</li>
<li><strong>Verificación.</strong> Confirmación de que el producto cumple lo especificado.</li>
<li><strong>Validación.</strong> Confirmación de que el producto sirve para la necesidad real del usuario.</li>
<li><strong>Proceso de ciclo de vida.</strong> Conjunto de actividades y tareas que la norma 12207 describe, sin imponer un orden de fases.</li>
<li><strong>ISO/IEC/IEEE 12207.</strong> Norma de procesos del ciclo de vida del software. Edición vigente: 2026.</li>
<li><strong>IEEE 730.</strong> Norma de procesos de aseguramiento de la calidad del software. Edición vigente: 2026.</li>
<li><strong>Integración continua (CI).</strong> Práctica de integrar y probar el código de forma automática en cada cambio.</li>
<li><strong>Entrega continua (CD).</strong> Práctica de mantener el software siempre listo para liberarse mediante un pipeline automatizado.</li>
<li><strong>DevOps.</strong> Cultura y prácticas que acercan desarrollo y operaciones para entregar cambios pequeños y frecuentes con menos riesgo.</li>
<li><strong>Pipeline.</strong> Recorrido automatizado que construye, prueba y despliega un cambio, con puertas de calidad entre etapas.</li>
<li><strong>Puerta de calidad.</strong> Criterio que debe cumplirse para que un cambio avance a la siguiente etapa.</li>
<li><strong>Despliegue por anillos.</strong> Liberar un cambio a grupos crecientes de usuarios, con observación entre grupos.</li>
<li><strong>Métricas DORA.</strong> Cinco métricas de entrega de software: tiempo de entrega, frecuencia de despliegue, tiempo de recuperación, tasa de fallo de cambios y tasa de retrabajo.</li>
<li><strong>Tasa de fallo de cambios.</strong> Proporción de despliegues que requieren intervención inmediata.</li>
<li><strong>Shift-left.</strong> Llevar las actividades de calidad a las fases tempranas del proyecto.</li>
<li><strong>Shift-right.</strong> Llevar actividades de calidad a producción, con observación y límites al daño.</li>
<li><strong>Interruptor de función (feature flag).</strong> Mecanismo para activar o apagar una función sin volver a desplegar.</li>
<li><strong>Canary release.</strong> Liberar un cambio a un grupo pequeño de usuarios antes que al resto.</li>
<li><strong>Quality engineering.</strong> Enfoque que trata la calidad como una capacidad de ingeniería que se diseña, automatiza y mide en todo el ciclo.</li>
<li><strong>Matriz de actividades por fase.</strong> Tabla que lista, por fase, la actividad de calidad, sus entradas, salidas y responsable.</li>
<li><strong>Criterio de salida.</strong> Condición que decide que una fase puede cerrarse.</li>
<li><strong>Efectividad de remoción de defectos (DRE).</strong> Defectos hallados en una fase dividido entre los presentes al entrar a ella.</li>
<li><strong>Plan de calidad por fase.</strong> Documento que fija objetivos medibles, actividades, criterios de salida y evidencia para cada fase.</li>
<li><strong>MCAS.</strong> Sistema de aumento de las características de maniobra del Boeing 737 MAX, central en los accidentes de 2018 y 2019.</li>
<li><strong>Ángulo de ataque.</strong> Ángulo entre el ala y el flujo de aire, que un sensor mide en el avión.</li>
<li><strong>SSDF.</strong> Marco de desarrollo seguro de software del NIST, publicado como SP 800-218.</li>
</ul>
</section>
<section id="bibliografía" class="level2" data-number="16">
<h2 data-number="16" class="anchored" data-anchor-id="bibliografía"><span class="header-section-number">16</span> Bibliografía</h2>
<p>Normas y marcos:</p>
<ul>
<li>ISO/IEC/IEEE 12207:2026. <em>Systems and software engineering, Software life cycle processes.</em> 2.a ed., abril de 2026. Sustituye a la edición de 2017. <a href="https://www.iso.org/standard/90219.html">Ficha de ISO</a>. <a href="https://standards.ieee.org/standard/12207-2026.html">Ficha de IEEE</a>.</li>
<li>IEEE 730-2026. <em>Standard for Software Quality Assurance Processes.</em> Publicada el 21 de agosto de 2026. Sustituye a IEEE 730-2014, inactiva-reservada desde el 27 de marzo de 2025. <a href="https://standards.ieee.org/standard/730-2026.html">Ficha de IEEE</a>.</li>
<li>ISO/IEC/IEEE 15288:2023. <em>Systems and software engineering, System life cycle processes.</em> Mencionada en la ficha de IEEE de la 12207:2026.</li>
<li>ISO/IEC 25010:2023. <em>Systems and software engineering, Product quality model.</em> Se desarrolla en la Unidad 1, Tema 2.</li>
<li>Souppaya, M., Scarfone, K. y Dodson, D. (2022). <em>Secure Software Development Framework (SSDF) Version 1.1.</em> NIST SP 800-218. <a href="https://doi.org/10.6028/NIST.SP.800-218">DOI</a>.</li>
<li>Schwaber, K. y Sutherland, J. (2020). <em>La Guía de Scrum.</em> Edición de noviembre de 2020. <a href="https://scrumguides.org/scrum-guide.html">scrumguides.org</a>.</li>
<li>DORA (consulta de enero de 2026). <em>DORA’s software delivery performance metrics.</em> <a href="https://dora.dev/guides/dora-metrics/">Guía</a>. DORA (2024). <em>Accelerate State of DevOps Report 2024.</em> <a href="https://dora.dev/research/2024/dora-report/">Informe</a>.</li>
<li>ISTQB. <em>Certified Tester Foundation Level, versión 4.0.</em> <a href="https://istqb.org/certifications/certified-tester-foundation-level-ctfl-v4-0/">Página</a>.</li>
</ul>
<p>Modelos de ciclo de vida y métricas:</p>
<ul>
<li>Royce, W. W. (1970). Managing the Development of Large Software Systems. <em>Proceedings of IEEE WESCON</em>, pp.&nbsp;328 a 338.</li>
<li>Boehm, B. W. (1988). A Spiral Model of Software Development and Enhancement. <em>IEEE Computer</em>, 21(5), 61 a 72.</li>
<li>Anderson, D. J. (2010). <em>Kanban: Successful Evolutionary Change for Your Technology Business.</em> Blue Hole Press.</li>
<li>Humble, J. y Farley, D. (2010). <em>Continuous Delivery.</em> Addison-Wesley.</li>
<li>Kan, S. H. (2002). <em>Metrics and Models in Software Quality Engineering</em> (2.a ed.). Addison-Wesley.</li>
<li>Pressman, R. S. y Maxim, B. R. <em>Ingeniería del software: un enfoque práctico.</em> Capítulos sobre calidad y aseguramiento de la calidad, bibliografía del curso.</li>
<li>Sommerville, I. (2016). <em>Software Engineering</em> (10.a ed.). Pearson.</li>
</ul>
<p>Caso Boeing 737 MAX:</p>
<ul>
<li>Committee on Transportation and Infrastructure, U.S. House of Representatives (septiembre de 2020). <em>Final Committee Report on the Design, Development and Certification of the Boeing 737 MAX.</em> <a href="https://democrats-transportation.house.gov/imo/media/doc/final_boeing_737_max_report.pdf">Informe</a>. <a href="https://democrats-transportation.house.gov/news/press-releases/after-18-month-investigation-chairs-defazio-and-larsen-release-final-committee-report-on-boeing-737-max">Comunicado del 16 de septiembre de 2020</a>.</li>
<li>KNKT, Comité Nacional de Seguridad en el Transporte de Indonesia (octubre de 2019). <em>Final Aircraft Accident Investigation Report, PT Lion Mentari Airlines, Boeing 737-8 (MAX), PK-LQP.</em></li>
<li>EAIB, Oficina de Investigación de Accidentes de Aeronaves de Etiopía (23 de diciembre de 2022). <em>Final Investigation Report, Ethiopian Airlines Flight ET302.</em> Comentarios de la <a href="https://www.ntsb.gov/investigations/Documents/Response%20to%20EAIB%20final%20report.pdf">NTSB</a>.</li>
<li>FAA (2024). <a href="https://www.faa.gov/newsroom/faa-continues-hold-boeing-accountable-implementing-safety-and-production-quality-fixes">FAA Continues to Hold Boeing Accountable for Implementing Safety and Production Quality Fixes</a>, comunicado de febrero de 2024. FAA. <a href="https://www.faa.gov/newsroom/Sec103_ExpertPanelReview_Report_Final.pdf">Informe del panel de expertos, Sección 103 ODA</a>.</li>
<li>Cobertura de la auditoría de producción: <a href="https://www.nbcnews.com/news/us-news/faa-audit-boeings-737-max-production-reportedly-found-dozens-issues-rcna142923">NBC News (2024)</a>.</li>
<li>Cobertura del informe de la Cámara: <a href="https://abcnews.com/US/house-committee-final-report-boeing-faa-failures-blame/story?id=73035288">ABC News (2020)</a>.</li>
<li>Resumen cronológico: <a href="https://en.wikipedia.org/wiki/Boeing_737_MAX_groundings">Wikipedia, Boeing 737 MAX groundings</a>, solo para fechas y cifras generales de la cronología.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Qué no se pudo leer directamente
</div>
</div>
<div class="callout-body-container callout-body">
<p>El texto de pago de ISO/IEC/IEEE 12207:2026 y de IEEE 730-2026 no se pudo abrir, y las páginas de ISO, de la FAA, de la NTSB y de la Cámara de Representantes no estaban accesibles en la consulta. Los datos de edición y fecha de las normas vienen de las fichas de IEEE y del resumen del catálogo de ISO. Los hechos del caso 737 MAX y de la auditoría de 2024 vienen de cobertura de esos documentos y de la cronología citada. Los libros y artículos de Royce, Boehm, Anderson, Humble y Farley, y Kan se citan como bibliografía clásica del tema, sin haber sido abiertos en línea. Verifica cada uno antes de citarlo en un trabajo.</p>
</div>
</div>
<div class="pie-doc">
<p>Calidad del software (CDS01). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>