<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 1. Métodos, metodologías y estándares de verificación y validación – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-95bfa606010d176c52cfb6b551730f65.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-04/index.html">Unidad 4. Validación y verificación</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html">Tema 1. Métodos, metodologías y estándares de verificación y validación</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Calidad del software y estándares de calidad</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-01-que-es-calidad-quien-la-define/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es la calidad y quién la define</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Calidad de proceso y de producto: ISO/IEC 25010:2023</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Importancia, costo y calidad en un mundo globalizado</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Procesos de calidad del software. Modelos y métricas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-01-sqa-relacion-ingenieria/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es el SQA y su relación con la ingeniería de software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La calidad en cada fase del ciclo de vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-03-roles-habilidades/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Roles, responsabilidades y habilidades del personal de SQA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-04-actividades-sqa/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Actividades del SQA: revisiones, auditorías y gestión de configuración</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-05-modelos-metricas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Modelos y métricas de calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-06-herramientas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 6. Herramientas de SQA en la industria</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 3. Estándares de calidad aplicados al software</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Estándares IEEE para la calidad del software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Marcos para evaluar la usabilidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Madurez de procesos: SPICE y CMMI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 4. Validación y verificación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 1. Métodos, metodologías y estándares de verificación y validación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Validación y verificación de requisitos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-03-control-costo-calidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Control de la calidad y costo de la calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Nomenclatura y certificación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-05-factores-atam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Factores que determinan la calidad y el método ATAM</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#objetivo-y-resultado-de-aprendizaje" id="toc-objetivo-y-resultado-de-aprendizaje" class="nav-link active" data-scroll-target="#objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</a></li>
  <li><a href="#ruta-de-estudio" id="toc-ruta-de-estudio" class="nav-link" data-scroll-target="#ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</a></li>
  <li><a href="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" id="toc-el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="nav-link" data-scroll-target="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</a></li>
  <li><a href="#parte-1.-verificar-y-validar-dos-preguntas-distintas" id="toc-parte-1.-verificar-y-validar-dos-preguntas-distintas" class="nav-link" data-scroll-target="#parte-1.-verificar-y-validar-dos-preguntas-distintas"><span class="header-section-number">4</span> Parte 1. Verificar y validar: dos preguntas distintas</a>
  <ul class="collapse">
  <li><a href="#la-distinción-de-boehm" id="toc-la-distinción-de-boehm" class="nav-link" data-scroll-target="#la-distinción-de-boehm">La distinción de Boehm</a></li>
  <li><a href="#ejemplo-resuelto-1.-la-app-que-cumple-y-no-sirve" id="toc-ejemplo-resuelto-1.-la-app-que-cumple-y-no-sirve" class="nav-link" data-scroll-target="#ejemplo-resuelto-1.-la-app-que-cumple-y-no-sirve">Ejemplo resuelto 1. La app que cumple y no sirve</a></li>
  </ul></li>
  <li><a href="#parte-2.-ieee-1012-el-estándar-que-gradúa-la-vv" id="toc-parte-2.-ieee-1012-el-estándar-que-gradúa-la-vv" class="nav-link" data-scroll-target="#parte-2.-ieee-1012-el-estándar-que-gradúa-la-vv"><span class="header-section-number">5</span> Parte 2. IEEE 1012: el estándar que gradúa la V&amp;V</a>
  <ul class="collapse">
  <li><a href="#qué-es-y-qué-edición-está-vigente" id="toc-qué-es-y-qué-edición-está-vigente" class="nav-link" data-scroll-target="#qué-es-y-qué-edición-está-vigente">Qué es y qué edición está vigente</a></li>
  <li><a href="#niveles-de-integridad-la-idea-central" id="toc-niveles-de-integridad-la-idea-central" class="nav-link" data-scroll-target="#niveles-de-integridad-la-idea-central">Niveles de integridad: la idea central</a></li>
  <li><a href="#cómo-se-razona-sin-la-tabla" id="toc-cómo-se-razona-sin-la-tabla" class="nav-link" data-scroll-target="#cómo-se-razona-sin-la-tabla">Cómo se razona sin la tabla</a></li>
  </ul></li>
  <li><a href="#parte-3.-dónde-encaja-la-vv-en-12207-y-29119" id="toc-parte-3.-dónde-encaja-la-vv-en-12207-y-29119" class="nav-link" data-scroll-target="#parte-3.-dónde-encaja-la-vv-en-12207-y-29119"><span class="header-section-number">6</span> Parte 3. Dónde encaja la V&amp;V en 12207 y 29119</a></li>
  <li><a href="#parte-4.-el-modelo-en-v-cuándo-se-planea-cada-prueba" id="toc-parte-4.-el-modelo-en-v-cuándo-se-planea-cada-prueba" class="nav-link" data-scroll-target="#parte-4.-el-modelo-en-v-cuándo-se-planea-cada-prueba"><span class="header-section-number">7</span> Parte 4. El modelo en V: cuándo se planea cada prueba</a>
  <ul class="collapse">
  <li><a href="#el-modelo-en-v-aplicado-a-la-clínica" id="toc-el-modelo-en-v-aplicado-a-la-clínica" class="nav-link" data-scroll-target="#el-modelo-en-v-aplicado-a-la-clínica">El modelo en V aplicado a la clínica</a></li>
  <li><a href="#los-límites-del-modelo" id="toc-los-límites-del-modelo" class="nav-link" data-scroll-target="#los-límites-del-modelo">Los límites del modelo</a></li>
  </ul></li>
  <li><a href="#parte-5.-técnicas-estáticas-y-técnicas-dinámicas" id="toc-parte-5.-técnicas-estáticas-y-técnicas-dinámicas" class="nav-link" data-scroll-target="#parte-5.-técnicas-estáticas-y-técnicas-dinámicas"><span class="header-section-number">8</span> Parte 5. Técnicas estáticas y técnicas dinámicas</a>
  <ul class="collapse">
  <li><a href="#las-dos-familias" id="toc-las-dos-familias" class="nav-link" data-scroll-target="#las-dos-familias">Las dos familias</a></li>
  <li><a href="#ejemplo-resuelto-2.-el-mismo-defecto-dos-caminos" id="toc-ejemplo-resuelto-2.-el-mismo-defecto-dos-caminos" class="nav-link" data-scroll-target="#ejemplo-resuelto-2.-el-mismo-defecto-dos-caminos">Ejemplo resuelto 2. El mismo defecto, dos caminos</a></li>
  </ul></li>
  <li><a href="#parte-6.-la-vv-como-práctica-diaria-tdd-integración-continua-y-shift-left" id="toc-parte-6.-la-vv-como-práctica-diaria-tdd-integración-continua-y-shift-left" class="nav-link" data-scroll-target="#parte-6.-la-vv-como-práctica-diaria-tdd-integración-continua-y-shift-left"><span class="header-section-number">9</span> Parte 6. La V&amp;V como práctica diaria: TDD, integración continua y shift-left</a>
  <ul class="collapse">
  <li><a href="#desarrollo-guiado-por-pruebas-tdd" id="toc-desarrollo-guiado-por-pruebas-tdd" class="nav-link" data-scroll-target="#desarrollo-guiado-por-pruebas-tdd">Desarrollo guiado por pruebas (TDD)</a></li>
  <li><a href="#integración-continua-ci" id="toc-integración-continua-ci" class="nav-link" data-scroll-target="#integración-continua-ci">Integración continua (CI)</a></li>
  <li><a href="#shift-left" id="toc-shift-left" class="nav-link" data-scroll-target="#shift-left">Shift-left</a></li>
  </ul></li>
  <li><a href="#parte-7.-pruebas-basadas-en-riesgo" id="toc-parte-7.-pruebas-basadas-en-riesgo" class="nav-link" data-scroll-target="#parte-7.-pruebas-basadas-en-riesgo"><span class="header-section-number">10</span> Parte 7. Pruebas basadas en riesgo</a>
  <ul class="collapse">
  <li><a href="#la-idea" id="toc-la-idea" class="nav-link" data-scroll-target="#la-idea">La idea</a></li>
  <li><a href="#ejemplo-resuelto-3.-repartir-40-horas-de-prueba" id="toc-ejemplo-resuelto-3.-repartir-40-horas-de-prueba" class="nav-link" data-scroll-target="#ejemplo-resuelto-3.-repartir-40-horas-de-prueba">Ejemplo resuelto 3. Repartir 40 horas de prueba</a></li>
  </ul></li>
  <li><a href="#parte-8.-verificación-y-validación-independiente-ivv" id="toc-parte-8.-verificación-y-validación-independiente-ivv" class="nav-link" data-scroll-target="#parte-8.-verificación-y-validación-independiente-ivv"><span class="header-section-number">11</span> Parte 8. Verificación y validación independiente (IV&amp;V)</a>
  <ul class="collapse">
  <li><a href="#qué-agrega-la-independencia" id="toc-qué-agrega-la-independencia" class="nav-link" data-scroll-target="#qué-agrega-la-independencia">Qué agrega la independencia</a></li>
  <li><a href="#cuándo-se-exige-el-criterio-de-la-nasa" id="toc-cuándo-se-exige-el-criterio-de-la-nasa" class="nav-link" data-scroll-target="#cuándo-se-exige-el-criterio-de-la-nasa">Cuándo se exige: el criterio de la NASA</a></li>
  <li><a href="#la-ivv-y-ieee-1012" id="toc-la-ivv-y-ieee-1012" class="nav-link" data-scroll-target="#la-ivv-y-ieee-1012">La IV&amp;V y IEEE 1012</a></li>
  <li><a href="#ejemplo-resuelto-4.-necesita-la-clínica-una-ivv" id="toc-ejemplo-resuelto-4.-necesita-la-clínica-una-ivv" class="nav-link" data-scroll-target="#ejemplo-resuelto-4.-necesita-la-clínica-una-ivv">Ejemplo resuelto 4. ¿Necesita la clínica una IV&amp;V?</a></li>
  </ul></li>
  <li><a href="#parte-9.-caso-real-mars-climate-orbiter" id="toc-parte-9.-caso-real-mars-climate-orbiter" class="nav-link" data-scroll-target="#parte-9.-caso-real-mars-climate-orbiter"><span class="header-section-number">12</span> Parte 9. Caso real: Mars Climate Orbiter</a>
  <ul class="collapse">
  <li><a href="#los-hechos" id="toc-los-hechos" class="nav-link" data-scroll-target="#los-hechos">Los hechos</a></li>
  <li><a href="#qué-falló-en-la-vv" id="toc-qué-falló-en-la-vv" class="nav-link" data-scroll-target="#qué-falló-en-la-vv">Qué falló en la V&amp;V</a></li>
  <li><a href="#ejemplo-resuelto-5.-la-prueba-que-faltaba" id="toc-ejemplo-resuelto-5.-la-prueba-que-faltaba" class="nav-link" data-scroll-target="#ejemplo-resuelto-5.-la-prueba-que-faltaba">Ejemplo resuelto 5. La prueba que faltaba</a></li>
  </ul></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes"><span class="header-section-number">13</span> Errores frecuentes</a></li>
  <li><a href="#lo-que-sigue" id="toc-lo-que-sigue" class="nav-link" data-scroll-target="#lo-que-sigue"><span class="header-section-number">14</span> Lo que sigue</a></li>
  <li><a href="#autoevaluación" id="toc-autoevaluación" class="nav-link" data-scroll-target="#autoevaluación"><span class="header-section-number">15</span> Autoevaluación</a></li>
  <li><a href="#lo-que-te-llevas" id="toc-lo-que-te-llevas" class="nav-link" data-scroll-target="#lo-que-te-llevas"><span class="header-section-number">16</span> Lo que te llevas</a></li>
  <li><a href="#glosario" id="toc-glosario" class="nav-link" data-scroll-target="#glosario"><span class="header-section-number">17</span> Glosario</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">18</span> Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-04/index.html">Unidad 4. Validación y verificación</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html">Tema 1. Métodos, metodologías y estándares de verificación y validación</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 1. Métodos, metodologías y estándares de verificación y validación</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">3 de octubre de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 4. Validación y verificación</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 1. Métodos, metodologías y estándares de verificación y validación</td>
</tr>
</tbody>
</table>
</div>
<p><a href="../presentacion-interactiva.html" class="btn-curso">Presentación interactiva de la unidad</a></p>
<p>Tema anterior: <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html">Unidad 3, Tema 4. Madurez de procesos: SPICE y CMMI</a>. Tema siguiente: <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html">Tema 2. Validación y verificación de requisitos</a>. Introducción de la unidad: <a href="../../../calidad-del-software/unidad-04/index.html">Unidad 4. Validación y verificación</a>.</p>
<section id="objetivo-y-resultado-de-aprendizaje" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</h2>
<p>La Unidad 3 mostró que los estándares certifican que una organización sigue un proceso, no que su software funcione. Este tema abre la Unidad 4 con la pregunta que esos estándares dejan abierta, cómo se comprueba, con evidencia, que un producto de software hace lo que se prometió y sirve para lo que se necesita.</p>
<p>Al terminar puedes:</p>
<ul>
<li>Distinguir verificación de validación con la pregunta que responde cada una, y clasificar una actividad concreta en una de las dos.</li>
<li>Explicar cómo IEEE 1012 gradúa la cantidad de V&amp;V según la integridad del sistema, y qué edición está vigente a octubre de 2026.</li>
<li>Ubicar en el modelo en V cada nivel de prueba junto a la fase que lo origina, y decir cuándo se planea.</li>
<li>Combinar técnicas estáticas y dinámicas, y justificar por qué ninguna de las dos reemplaza a la otra.</li>
<li>Explicar cómo TDD, la integración continua y el <em>shift-left</em> convierten la V&amp;V en una práctica diaria.</li>
<li>Repartir un esfuerzo de pruebas limitado según el riesgo de cada función, con cálculo.</li>
<li>Decidir cuándo un proyecto necesita V&amp;V independiente (IV&amp;V) y qué significa que sea independiente.</li>
<li>Analizar un caso real de la NASA, el Mars Climate Orbiter, y señalar qué control de V&amp;V faltó.</li>
</ul>
<p>Prerrequisitos: los Temas 1 y 2 de la Unidad 2 (calidad en el ciclo de vida y revisiones) y el Tema 1 de la Unidad 3 (estándares IEEE e ISO). Necesitas conocer los términos <em>requisito</em>, <em>defecto</em> y <em>falla</em>, y haber visto qué es una prueba unitaria.</p>
<p>Este tema no desarrolla la validación y la verificación de los requisitos, es decir, cómo se comprueba que lo que se pide está bien escrito y es lo que el usuario necesita. Ese es el <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html">Tema 2 de esta unidad</a>. Aquí se presenta el marco general y se aplica sobre todo al diseño, al código y al sistema ya construido.</p>
</section>
<section id="ruta-de-estudio" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</h2>
<p>Son unas 6 horas de trabajo independiente, repartidas en dos o tres sesiones. La presentación interactiva de la unidad sigue las mismas partes y en el mismo orden, así que sirve para repasar.</p>
<div class="calendario">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parte</th>
<th>Qué haces</th>
<th>Tiempo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Verificar y validar</td>
<td>Lees la distinción de Boehm, sigues el ejemplo del cupo y resuelves el Reto 1</td>
<td>40 min</td>
</tr>
<tr class="even">
<td>2. IEEE 1012</td>
<td>Lees qué edición está vigente y cómo se gradúa la V&amp;V</td>
<td>35 min</td>
</tr>
<tr class="odd">
<td>3. 12207 y 29119</td>
<td>Ubicas dónde encaja la V&amp;V en las normas del ciclo de vida</td>
<td>15 min</td>
</tr>
<tr class="even">
<td>4. El modelo en V</td>
<td>Relacionas cada fase con su nivel de prueba</td>
<td>30 min</td>
</tr>
<tr class="odd">
<td>5. Técnicas estáticas y dinámicas</td>
<td>Ves un defecto hallado por las dos vías y resuelves el Reto 2</td>
<td>45 min</td>
</tr>
<tr class="even">
<td>6. TDD, integración continua y shift-left</td>
<td>Lees la V&amp;V como práctica diaria</td>
<td>35 min</td>
</tr>
<tr class="odd">
<td>7. Pruebas basadas en riesgo</td>
<td>Calculas un reparto de horas y resuelves el Reto 3</td>
<td>50 min</td>
</tr>
<tr class="even">
<td>8. V&amp;V independiente</td>
<td>Lees los criterios de la NASA y resuelves el Reto 4</td>
<td>35 min</td>
</tr>
<tr class="odd">
<td>9. Caso real: Mars Climate Orbiter</td>
<td>Analizas el informe oficial y resuelves el Reto 5</td>
<td>45 min</td>
</tr>
<tr class="even">
<td>Cierre</td>
<td>Errores frecuentes, autoevaluación y glosario</td>
<td>30 min</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</h2>
<p>Todo el curso usa un producto ficticio, una app que asigna turnos médicos. Su requisito de partida es “la app asigna hasta 20 turnos por día a cada especialidad”. En este tema la usas como laboratorio para verificarla, validarla, probarla con riesgo y decidir si merece una revisión independiente. Ninguna cifra de la clínica es real, y cada vez que aparece una el texto la marca como ilustrativa.</p>
</section>
<section id="parte-1.-verificar-y-validar-dos-preguntas-distintas" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="parte-1.-verificar-y-validar-dos-preguntas-distintas"><span class="header-section-number">4</span> Parte 1. Verificar y validar: dos preguntas distintas</h2>
<section id="la-distinción-de-boehm" class="level3">
<h3 class="anchored" data-anchor-id="la-distinción-de-boehm">La distinción de Boehm</h3>
<p>Barry Boehm separó dos actividades que en la práctica se confunden. La literatura la resume en dos preguntas breves. La verificación pregunta si el producto se está construyendo correctamente, y la validación pregunta si se está construyendo el producto correcto. Boehm desarrolló la distinción en su artículo de 1984 en <em>IEEE Software</em> (volumen 1, número 1, páginas 75 a 88), y el programa de estudios del ISTQB cita a Boehm (1981) al tratar la validación. Esta guía no pudo leer el texto original, que es de pago, así que presenta las dos preguntas como la forma habitual de citar la distinción y no como una cita literal.</p>
<p>Lo que sí consta en una fuente abierta es la distinción misma. El programa de estudios del nivel fundamental del ISTQB (versión 4.0.1, de septiembre de 2024) dice que las pruebas incluyen verificación, que comprueba si el sistema cumple los requisitos especificados, y validación, que comprueba si cumple las necesidades de los usuarios y de otros interesados en su entorno de operación.</p>
<p>La verificación toma la especificación como punto de referencia. La validación toma como referencia el uso real. Por eso un sistema puede pasar toda su verificación y fallar la validación, si la especificación describía con precisión algo que no era lo que se necesitaba.</p>
<div class="diagrama">
<svg viewbox="0 0 760 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Dos preguntas sobre la misma app de turnos. Verificación compara la app contra la especificación de 20 turnos por especialidad. Validación compara la app contra la necesidad real de Pediatría, que tiene 3 médicos y 60 cupos reales por día." font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="20" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">Dos preguntas sobre la misma app</text> <rect x="20" y="40" width="340" height="150" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="400" y="40" width="340" height="150" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="190" y="66" font-size="15" font-weight="700" fill="#12324f" text-anchor="middle">Verificación</text> <text x="190" y="88" font-size="12" fill="#5b6876" text-anchor="middle">¿Se construyó correctamente?</text> <text x="190" y="114" font-size="12" fill="#12324f" text-anchor="middle">Se compara contra la especificación</text> <text x="190" y="134" font-size="12" fill="#12324f" text-anchor="middle">“hasta 20 turnos por especialidad”</text> <text x="190" y="162" font-size="12" font-weight="600" fill="#0e6f6c" text-anchor="middle">Resultado: cumple, el turno 21 se rechaza</text> <text x="570" y="66" font-size="15" font-weight="700" fill="#0e6f6c" text-anchor="middle">Validación</text> <text x="570" y="88" font-size="12" fill="#3c7d7a" text-anchor="middle">¿Se construyó lo correcto?</text> <text x="570" y="114" font-size="12" fill="#0e6f6c" text-anchor="middle">Se compara contra la necesidad real</text> <text x="570" y="134" font-size="12" fill="#0e6f6c" text-anchor="middle">Pediatría: 3 médicos, 60 cupos al día</text> <text x="570" y="162" font-size="12" font-weight="600" fill="#b5472f" text-anchor="middle">Resultado: no sirve, deja 40 cupos vacíos</text> <rect x="190" y="215" width="380" height="56" rx="12" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="380" y="239" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Una app puede pasar la primera y fallar la segunda</text> <text x="380" y="257" font-size="11.5" fill="#5b6876" text-anchor="middle">porque la especificación era la pieza equivocada</text>
</svg>
</div>
<p>El mismo programa del ISTQB lo formula como un principio de las pruebas, la falacia de la ausencia de defectos. Creer que verificar bien garantiza el éxito de un sistema es un error, porque se pueden probar todos los requisitos especificados, corregir todos los defectos hallados, y aun así entregar un sistema que no cumple lo que los usuarios necesitan.</p>
</section>
<section id="ejemplo-resuelto-1.-la-app-que-cumple-y-no-sirve" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-1.-la-app-que-cumple-y-no-sirve">Ejemplo resuelto 1. La app que cumple y no sirve</h3>
<p>La Clínica Aurora tiene un requisito, R1, escrito así: “la app asigna hasta 20 turnos por día a cada especialidad”. Los datos siguientes son ilustrativos.</p>
<ol type="1">
<li>Verificación. El equipo escribe dos pruebas, una que pide el turno número 20 y otra que pide el 21. La app acepta el 20 y rechaza el 21. Las dos pasan, así que R1 está verificado.</li>
<li>Validación. Una coordinadora de la clínica usa la app durante una semana de piloto. Pediatría tiene 3 médicos y cada uno atiende 20 consultas al día, o sea 60 cupos reales. La demanda del piloto es de 45 solicitudes diarias.</li>
<li>Resultado de la validación. La app acepta 20 y rechaza 45 - 20 = 25 solicitudes, el 25 / 45 = 55,6 % de la demanda. Mientras tanto quedan 60 - 20 = 40 cupos reales sin ofrecer, el 66,7 % de la agenda.</li>
<li>Diagnóstico. El defecto está en R1, que fijó el límite por especialidad cuando la capacidad depende de cuántos médicos atienden. El código implementa fielmente un requisito equivocado.</li>
<li>Corrección. R1 pasa a “la app asigna hasta N turnos por día a cada médico, donde N es la capacidad configurada”, y la validación se repite con la coordinadora.</li>
</ol>
<p>Fíjate en que ninguna prueba contra R1 habría encontrado el problema. Lo encontró alguien que usó la app con una necesidad real. El Tema 2 de esta unidad desarrolla cómo se revisan los requisitos para encontrar este tipo de error antes de escribir código.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Clasifica cada actividad
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para cada actividad, decide si es verificación o validación, y di contra qué se compara.</p>
<ol type="a">
<li>Un revisor compara el código del módulo de recordatorios con el documento de diseño detallado.</li>
<li>Cinco pacientes reales agendan un turno en un prototipo sin ayuda y dicen si lo lograron.</li>
<li>Un analista ejecuta las pruebas unitarias de la regla “máximo 20 turnos” y compara con el resultado esperado.</li>
<li>La gerencia de la clínica revisa una maqueta de la pantalla de agenda antes de que se programe, y confirma que resuelve su problema actual.</li>
<li>Un script revisa que el archivo de turnos que genera la app respete el formato que dice el contrato con el sistema de facturación.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>Verificación. Compara un producto de trabajo (código) contra una especificación (diseño).</p></li>
<li><p>Validación. Compara el sistema, o un prototipo, contra la necesidad real de quien lo usa.</p></li>
<li><p>Verificación. El resultado esperado sale de la especificación.</p></li>
<li><p>Validación. La referencia es el problema real de la gerencia, y ocurre antes de construir. La validación no espera a que exista un sistema terminado.</p></li>
<li><p>Verificación. Compara una salida contra un contrato escrito. Es el tipo de comprobación que habría detectado el error del caso de la Parte 9.</p></li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="parte-2.-ieee-1012-el-estándar-que-gradúa-la-vv" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="parte-2.-ieee-1012-el-estándar-que-gradúa-la-vv"><span class="header-section-number">5</span> Parte 2. IEEE 1012: el estándar que gradúa la V&amp;V</h2>
<section id="qué-es-y-qué-edición-está-vigente" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-y-qué-edición-está-vigente">Qué es y qué edición está vigente</h3>
<p>IEEE 1012 es el estándar del IEEE para los procesos de verificación y validación. Según su ficha oficial, define procesos de V&amp;V para determinar si los productos de desarrollo de una actividad cumplen los requisitos de esa actividad y si el producto satisface su uso previsto y las necesidades de los usuarios. Cubre sistemas, software y hardware, y sus interfaces.</p>
<p>A octubre de 2026 la edición vigente es IEEE 1012-2024, y las anteriores constan como reemplazadas.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Edición</th>
<th>Dato verificado en la ficha del IEEE o en una fuente secundaria</th>
<th>Estado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>IEEE 1012-2012</td>
<td>Amplió el alcance de software a sistemas y hardware, y reemplazó “nivel de integridad de software” por “nivel de integridad” (según un estudio de aplicación de 2017)</td>
<td>Reemplazada</td>
</tr>
<tr class="even">
<td>IEEE 1012-2016</td>
<td>Aprobada por la junta del IEEE el 15 de mayo de 2016 y publicada el 29 de septiembre de 2017. Título “Standard for System, Software, and Hardware Verification and Validation”</td>
<td>Reemplazada por la edición 2024</td>
</tr>
<tr class="odd">
<td>IEEE 1012-2024</td>
<td>Aprobada por la junta el 12 de noviembre de 2024 y publicada el 22 de agosto de 2025. Mismo título que la 2016</td>
<td>Vigente (activa)</td>
</tr>
</tbody>
</table>
<p>Consultas del 3 de octubre de 2026. Las fichas del IEEE no detallan qué cambió entre 2016 y 2024. Una guía anterior de este curso decía que 2024 “amplió” el título para incluir el hardware, y eso no es correcto, porque el título con hardware ya lo traía la edición 2016.</p>
</section>
<section id="niveles-de-integridad-la-idea-central" class="level3">
<h3 class="anchored" data-anchor-id="niveles-de-integridad-la-idea-central">Niveles de integridad: la idea central</h3>
<p>Lo que distingue a IEEE 1012 de una lista de buenas prácticas es que no pide la misma V&amp;V para todo. Pide más o menos según un <em>nivel de integridad</em>, que expresa cuán importante es el sistema, o uno de sus componentes, para quien lo usa. Cuanto más alto es el nivel, mayores son el alcance, la intensidad y el rigor de las tareas de V&amp;V. La ficha del IEEE confirma que los requisitos de V&amp;V se especifican “para distintos niveles de integridad”.</p>
<p>Un estudio de aplicación de IEEE 1012 realizado por una ingeniería del sector nuclear coreano (KEPCO E&amp;C, 2017) permite precisar tres cosas sobre las ediciones 2012 y 2016, que en niveles de integridad son esencialmente iguales.</p>
<ul>
<li>Los niveles de integridad sirven solo para graduar el rigor de la V&amp;V. Al bajar el nivel, bajan el alcance, la intensidad y el rigor exigidos.</li>
<li>No es obligatorio usar el mismo nivel para todos los subsistemas o elementos de un sistema. Un componente crítico puede tener un nivel más alto que el resto.</li>
<li>En los niveles 3 y 4 la organización que hace la V&amp;V debe ejecutar las pruebas por su cuenta. En el nivel 2 las puede ejecutar la organización de diseño y revisarlas la de V&amp;V.</li>
</ul>
<p>Esa tercera idea conecta con la V&amp;V independiente de la Parte 8. La independencia no es una etiqueta que se pone o se quita, aumenta con el nivel de integridad.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Advertencia</span>Lo que esta guía no pudo verificar
</div>
</div>
<div class="callout-body-container callout-body">
<p>El texto completo de IEEE 1012 es de pago y no se pudo leer. La tabla que cruza la probabilidad de la falla con su consecuencia para asignar el nivel, y la lista exacta de tareas por nivel, no se verificaron en fuente primaria, y por eso no se reproducen aquí. La literatura describe cuatro niveles, del 1 al 4, siendo el 4 el más exigente, pero la fuente abierta consultada solo menciona expresamente los niveles 2, 3 y 4. Para citar la tabla en un trabajo, consulta el estándar en la biblioteca de la universidad o en el IEEE.</p>
<p>ISO/IEC/IEEE 15026-3:2023 (tercera edición, octubre de 2023) es la norma conjunta de niveles de integridad de sistemas dentro de la familia de aseguramiento de sistemas y software, y se puede consultar como complemento.</p>
</div>
</div>
</section>
<section id="cómo-se-razona-sin-la-tabla" class="level3">
<h3 class="anchored" data-anchor-id="cómo-se-razona-sin-la-tabla">Cómo se razona sin la tabla</h3>
<p>Aunque la tabla literal de la norma no se reproduzca, la lógica de asignar un nivel es la del riesgo, que la Parte 7 trabaja con números. Dos preguntas bastan para razonar. Cuán probable es que el componente falle de una manera que importe, y cuán grave sería la consecuencia. Un sistema con consecuencias graves recibe más V&amp;V aunque sea pequeño, y uno con consecuencias leves recibe menos aunque sea grande.</p>
<p>En la clínica, el módulo de historial de salud y el de prioridad por urgencia tendrían un nivel alto en una analogía didáctica con IEEE 1012, porque una falla filtra datos sensibles o retrasa a un paciente grave. El selector de colores de la interfaz tendría un nivel bajo. Esa asignación es un ejemplo del curso y no una clasificación de la norma.</p>
</section>
</section>
<section id="parte-3.-dónde-encaja-la-vv-en-12207-y-29119" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="parte-3.-dónde-encaja-la-vv-en-12207-y-29119"><span class="header-section-number">6</span> Parte 3. Dónde encaja la V&amp;V en 12207 y 29119</h2>
<p>La V&amp;V no se hace en el vacío. Se inserta en normas que organizan el ciclo de vida y las pruebas, y esas normas se estudian en el <a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html">Tema 1 de la Unidad 3</a>. Aquí solo se ubican.</p>
<ul>
<li>ISO/IEC/IEEE 12207 describe los procesos del ciclo de vida del software. La edición vigente es ISO/IEC/IEEE 12207:2026, publicada el 15 de abril de 2026, que reemplazó a la de 2017 (ficha del IEEE). Su ficha dice que alinea los propósitos y resultados de sus procesos con ISO/IEC/IEEE 15288:2023, la norma equivalente para sistemas. La V&amp;V se trata en esa familia como procesos del ciclo de vida (dato no verificado en fuente primaria para la edición 2026), y la calidad por fase se explica en el <a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html">Tema 2 de la Unidad 2</a>.</li>
<li>ISO/IEC/IEEE 29119 es la serie de normas de pruebas de software. Según una fuente secundaria (Wikipedia, con datos a octubre de 2025), la parte 1 de conceptos es de 2022, y las partes 2 de procesos de prueba, 3 de documentación y 4 de técnicas son de 2021. La serie se apoya, entre otras, en IEEE 829 para la documentación de pruebas.</li>
</ul>
<p>Una consecuencia práctica es que IEEE 1012 dice qué V&amp;V hace falta según la integridad, 12207 ubica cuándo ocurre en el ciclo de vida, y 29119 describe cómo organizar y documentar las pruebas cuando se ejecutan. Para el detalle del texto de 12207:2026 y de 29119 hace falta el estándar, de pago, que esta guía no leyó, así que no afirma números de cláusulas ni de procesos concretos de la edición 2026.</p>
</section>
<section id="parte-4.-el-modelo-en-v-cuándo-se-planea-cada-prueba" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="parte-4.-el-modelo-en-v-cuándo-se-planea-cada-prueba"><span class="header-section-number">7</span> Parte 4. El modelo en V: cuándo se planea cada prueba</h2>
<p>El <em>modelo en V</em> dibuja el desarrollo como una letra V. Las fases de construcción bajan por el lado izquierdo y los niveles de prueba suben por el derecho, y cada fase de la izquierda queda emparejada con el nivel de prueba que la comprueba. El programa del ISTQB lo clasifica como un modelo de desarrollo secuencial, junto con la cascada.</p>
<p>Lo valioso del modelo es el momento en que se escribe cada plan de pruebas. El plan de aceptación se redacta mientras se levantan los requisitos, y el de pruebas de sistema mientras se diseña la arquitectura. Así, cada pregunta de prueba nace en la fase donde se toma la decisión que prueba.</p>
<div class="diagrama">
<svg viewbox="0 0 760 360" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Modelo en V de la app de turnos. A la izquierda bajan requisitos, diseño de arquitectura, diseño de componentes y diseño detallado. En el vértice está la codificación. A la derecha suben pruebas unitarias, de integración, de sistema y de aceptación. Cada fase se empareja con su prueba mediante una línea punteada." font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">El modelo en V: construcción a la izquierda, prueba a la derecha</text> <g fill="none" stroke="#c7d6e6" stroke-width="1.6" stroke-dasharray="4 4"><path d="M160,60 L600,60"></path><path d="M225,120 L535,120"></path><path d="M290,180 L470,180"></path><path d="M355,240 L405,240"></path></g> <g fill="none" stroke="#8fb3d1" stroke-width="2.2"><path d="M90,60 L155,120 L220,180 L285,240 L380,300"></path><path d="M380,300 L475,240 L540,180 L605,120 L670,60"></path></g> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="20" y="40" width="140" height="40" rx="8"></rect><rect x="85" y="100" width="140" height="40" rx="8"></rect><rect x="150" y="160" width="140" height="40" rx="8"></rect><rect x="215" y="220" width="140" height="40" rx="8"></rect></g> <g fill="#e4f2f1" stroke="#8fc9c5"><rect x="600" y="40" width="140" height="40" rx="8"></rect><rect x="535" y="100" width="140" height="40" rx="8"></rect><rect x="470" y="160" width="140" height="40" rx="8"></rect><rect x="405" y="220" width="140" height="40" rx="8"></rect></g> <rect x="290" y="280" width="180" height="40" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <g text-anchor="middle" font-size="11.5" font-weight="600" fill="#12324f"> <text x="90" y="65">Requisitos</text> <text x="155" y="118">Diseño de</text><text x="155" y="132">arquitectura</text> <text x="220" y="178">Diseño de</text><text x="220" y="192">componentes</text> <text x="285" y="238">Diseño</text><text x="285" y="252">detallado</text> </g> <g text-anchor="middle" font-size="11.5" font-weight="600" fill="#0e6f6c"> <text x="670" y="58">Pruebas de</text><text x="670" y="72">aceptación</text> <text x="605" y="118">Pruebas de</text><text x="605" y="132">sistema</text> <text x="540" y="178">Pruebas de</text><text x="540" y="192">integración</text> <text x="475" y="238">Pruebas</text><text x="475" y="252">unitarias</text> </g> <text x="380" y="305" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Codificación</text> <text x="380" y="345" font-size="11.5" fill="#5b6876" text-anchor="middle">Cada plan de prueba se escribe junto con la fase que lo origina, no al final</text>
</svg>
</div>
<section id="el-modelo-en-v-aplicado-a-la-clínica" class="level3">
<h3 class="anchored" data-anchor-id="el-modelo-en-v-aplicado-a-la-clínica">El modelo en V aplicado a la clínica</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Fase de construcción</th>
<th>Ejemplo en la app de turnos</th>
<th>Nivel de prueba emparejado</th>
<th>Pregunta que responde</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Requisitos</td>
<td>R1, cupo de turnos por médico</td>
<td>Pruebas de aceptación</td>
<td>¿La clínica puede operar con esto? (validación)</td>
</tr>
<tr class="even">
<td>Diseño de arquitectura</td>
<td>App móvil, servicio de agenda, proveedor de SMS</td>
<td>Pruebas de sistema</td>
<td>¿El conjunto cumple de punta a punta?</td>
</tr>
<tr class="odd">
<td>Diseño de componentes</td>
<td>Servicio de agenda y servicio de recordatorios se hablan por una interfaz</td>
<td>Pruebas de integración</td>
<td>¿Los componentes se entienden en la interfaz?</td>
</tr>
<tr class="even">
<td>Diseño detallado y código</td>
<td>Función que decide si hay cupo</td>
<td>Pruebas unitarias</td>
<td>¿Cada función hace lo diseñado?</td>
</tr>
</tbody>
</table>
<p>La tabla sigue la clasificación de niveles de prueba del programa del ISTQB, que define la prueba de componente como la que prueba componentes en aislamiento, la de integración como la que prueba las interfaces y la interacción entre componentes, la de sistema como la del comportamiento global, y la de aceptación como la que se centra en la validación y en la disposición para el despliegue, idealmente a cargo de los usuarios.</p>
</section>
<section id="los-límites-del-modelo" class="level3">
<h3 class="anchored" data-anchor-id="los-límites-del-modelo">Los límites del modelo</h3>
<p>El modelo en V tiene dos límites que conviene conocer antes de usarlo como receta.</p>
<ul>
<li>Es secuencial. El ISTQB señala que, en los modelos secuenciales, el código ejecutable se crea en las fases tardías y por eso no se puede hacer prueba dinámica al principio. En los modelos iterativos e incrementales, en cambio, cada iteración entrega un incremento y se pueden hacer pruebas estáticas y dinámicas en todos los niveles.</li>
<li>Su valor sobrevive a los ciclos cortos. Un equipo ágil no dibuja la V, pero sigue necesitando decidir cuándo se piensa cada nivel de prueba. Lo que cambia es la escala, una V pequeña dentro de cada historia de usuario y no una V grande para todo el proyecto.</li>
</ul>
</section>
</section>
<section id="parte-5.-técnicas-estáticas-y-técnicas-dinámicas" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="parte-5.-técnicas-estáticas-y-técnicas-dinámicas"><span class="header-section-number">8</span> Parte 5. Técnicas estáticas y técnicas dinámicas</h2>
<section id="las-dos-familias" class="level3">
<h3 class="anchored" data-anchor-id="las-dos-familias">Las dos familias</h3>
<p>Las <em>técnicas estáticas</em> examinan un producto de trabajo sin ejecutarlo, y las <em>técnicas dinámicas</em> ejecutan el software y observan lo que hace. Las revisiones y las inspecciones, que la <a href="../../../calidad-del-software/unidad-02/tema-04-actividades-sqa/index.html">Unidad 2</a> trató con IEEE 1028, son técnicas estáticas, igual que el análisis estático de código. Las pruebas unitarias, de integración, de sistema y de aceptación son dinámicas.</p>
<p>El programa del ISTQB señala cuatro diferencias que ayudan a decidir cuál usar.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Aspecto</th>
<th>Técnica estática</th>
<th>Técnica dinámica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Qué encuentra</td>
<td>Defectos, directamente</td>
<td>Fallas, de las que se deduce el defecto</td>
</tr>
<tr class="even">
<td>Sobre qué se aplica</td>
<td>Cualquier producto, también los no ejecutables (requisitos, diseño)</td>
<td>Solo productos ejecutables</td>
</tr>
<tr class="odd">
<td>Caminos del código</td>
<td>Puede llegar a caminos poco ejecutados o difíciles de alcanzar</td>
<td>Solo cubre lo que algún caso de prueba ejecuta</td>
</tr>
<tr class="even">
<td>Qué cualidades mide bien</td>
<td>Las que no dependen de ejecutar, como la mantenibilidad</td>
<td>Las que dependen de ejecutar, como el rendimiento</td>
</tr>
</tbody>
</table>
<p>Lo que el estático encuentra con más facilidad o menor costo, según el mismo programa, incluye defectos de requisitos, defectos de diseño, ciertos defectos de código como variables sin definir o código inalcanzable, desviaciones de estándares e interfaces mal especificadas. Las dos familias se complementan, y hay tipos de defecto que solo una de ellas encuentra.</p>
</section>
<section id="ejemplo-resuelto-2.-el-mismo-defecto-dos-caminos" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-2.-el-mismo-defecto-dos-caminos">Ejemplo resuelto 2. El mismo defecto, dos caminos</h3>
<p>Para el requisito R1 original (20 turnos por especialidad) se escribe esta función y estas dos pruebas. Corren en cualquier equipo con Python y pytest.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># turnos.py</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>CUPO_POR_ESPECIALIDAD <span class="op">=</span> <span class="dv">20</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> hay_cupo(turnos_dados):</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Devuelve True si la especialidad aun tiene cupo ese dia."""</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> turnos_dados <span class="op">&lt;</span> CUPO_POR_ESPECIALIDAD</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># test_turnos.py</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> turnos <span class="im">import</span> hay_cupo</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> test_acepta_el_turno_20():</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> hay_cupo(<span class="dv">19</span>) <span class="kw">is</span> <span class="va">True</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> test_rechaza_el_turno_21():</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> hay_cupo(<span class="dv">20</span>) <span class="kw">is</span> <span class="va">False</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Salida real de ejecutar <code>python -m pytest -q</code> sobre este código, tomada durante la preparación del material. El tiempo varía según el equipo.</p>
<pre class="text"><code>..                                                                       [100%]
2 passed in 0.03s</code></pre>
<p>Ahora suponte que alguien escribe por descuido <code>&lt;=</code> en lugar de <code>&lt;</code>. Hay dos maneras de encontrar ese defecto.</p>
<ol type="1">
<li>Vía estática. Un revisor lee el código junto con R1. El requisito dice “hasta 20”, y con <code>turnos_dados &lt;= 20</code> la función aceptaría un turno 21. El revisor lo marca sin ejecutar nada.</li>
<li>Vía dinámica. La prueba <code>test_rechaza_el_turno_21</code> falla. Salida real al cambiar <code>&lt;</code> por <code>&lt;=</code>:</li>
</ol>
<pre class="text"><code>&gt;       assert hay_cupo(20) is False
E       assert True is False
test_turnos.py:9: AssertionError
FAILED test_turnos.py::test_rechaza_el_turno_21 - assert True is False
1 failed, 1 passed in 0.21s</code></pre>
<p>La prueba que falla es la que mira el valor límite, el turno 21. La que prueba el turno 20 sigue pasando y no lo habría detectado. Por eso las pruebas de valores límite importan. Y fíjate en que la vía estática sirve aun sin pruebas escritas, mientras que la dinámica se vuelve una red de seguridad que se ejecuta sola cada vez que alguien cambia el código.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Escribe la prueba antes que el código
</div>
</div>
<div class="callout-body-container callout-body">
<p>Regla de negocio nueva, R2: “un paciente no puede tener dos turnos de la misma especialidad el mismo día”. Antes de escribir la función, escribe tres pruebas que describan el comportamiento esperado. Luego escribe la función que las hace pasar.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Tres pruebas que cubren el rechazo, la aceptación de otra especialidad y el primer turno del día:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># test_paciente.py</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> paciente <span class="im">import</span> puede_agendar</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> test_rechaza_segundo_turno_de_la_misma_especialidad():</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> puede_agendar([<span class="st">"pediatria"</span>], <span class="st">"pediatria"</span>) <span class="kw">is</span> <span class="va">False</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> test_acepta_otra_especialidad_el_mismo_dia():</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> puede_agendar([<span class="st">"pediatria"</span>], <span class="st">"odontologia"</span>) <span class="kw">is</span> <span class="va">True</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> test_acepta_el_primer_turno_del_dia():</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> puede_agendar([], <span class="st">"pediatria"</span>) <span class="kw">is</span> <span class="va">True</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Con esas pruebas escritas, la función mínima que las hace pasar es:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># paciente.py</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> puede_agendar(especialidades_del_dia, especialidad):</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> especialidad <span class="kw">not</span> <span class="kw">in</span> especialidades_del_dia</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Ejecutadas con pytest, las tres pasan (<code>3 passed</code>). El orden importa. Antes de tener la función, las pruebas fallan, y esa falla confirma que prueban algo. Es el ciclo de la Parte 6.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-6.-la-vv-como-práctica-diaria-tdd-integración-continua-y-shift-left" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="parte-6.-la-vv-como-práctica-diaria-tdd-integración-continua-y-shift-left"><span class="header-section-number">9</span> Parte 6. La V&amp;V como práctica diaria: TDD, integración continua y shift-left</h2>
<p>Los estándares dicen qué V&amp;V hace falta. Estas tres prácticas dicen cómo conseguir que ocurra todos los días sin depender de una fase de pruebas al final.</p>
<section id="desarrollo-guiado-por-pruebas-tdd" class="level3">
<h3 class="anchored" data-anchor-id="desarrollo-guiado-por-pruebas-tdd">Desarrollo guiado por pruebas (TDD)</h3>
<p>El programa del ISTQB describe el <em>desarrollo guiado por pruebas</em> (TDD) con tres pasos. Se escriben las pruebas primero, luego el código que las satisface, y luego se refactorizan las pruebas y el código. La referencia clásica es el libro de Kent Beck, <em>Test-Driven Development: By Example</em> (Addison-Wesley, 2003, según la referencia del ISTQB).</p>
<p>La conexión con este tema es que TDD verifica en el momento de escribir. Cada prueba es una verificación contra una intención explícita, y se conserva como prueba de regresión. La validación sigue haciendo falta, porque las pruebas de TDD solo prueban lo que el equipo entendió.</p>
</section>
<section id="integración-continua-ci" class="level3">
<h3 class="anchored" data-anchor-id="integración-continua-ci">Integración continua (CI)</h3>
<p>Martin Fowler define la <em>integración continua</em> como una práctica donde cada integrante del equipo fusiona sus cambios en la base de código común al menos una vez al día, y cada integración se verifica con una construcción automática que incluye pruebas, para detectar errores de integración lo antes posible. La versión revisada de su artículo es del 18 de enero de 2024.</p>
<p>DORA, el programa de investigación de Google sobre entrega de software, describe la CI con dos elementos, que cada commit dispare una construcción del software y que cada commit dispare una serie de pruebas automáticas que den retroalimentación en pocos minutos. Si las pruebas fallan, el equipo deja lo que hace y lo arregla de inmediato. Fowler recoge la guía de XP de una construcción de diez minutos, que considera razonable para la mayoría de los proyectos.</p>
<div class="diagrama">
<svg viewbox="0 0 760 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Línea de integración continua de la app de turnos. Un commit dispara cuatro etapas en orden: compilar, 1 minuto; pruebas unitarias, 3 minutos; análisis estático, 2 minutos; pruebas de integración, 4 minutos. Si todas pasan se fusiona a la rama principal, en total 10 minutos. Si alguna falla, el equipo arregla antes de seguir." font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t1a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="20" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">Cada commit recorre la línea de integración continua (tiempos ilustrativos)</text> <rect x="10" y="60" width="100" height="64" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <rect x="150" y="60" width="110" height="64" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="290" y="60" width="110" height="64" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <rect x="430" y="60" width="110" height="64" rx="10" fill="#fdf3d0" stroke="#e6cf86"></rect> <rect x="570" y="60" width="110" height="64" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g text-anchor="middle" font-size="12" font-weight="600" fill="#12324f"> <text x="60" y="88">Commit</text> <text x="205" y="88">Compilar</text> <text x="345" y="88">Pruebas</text><text x="345" y="104">unitarias</text> <text x="485" y="88">Análisis</text><text x="485" y="104">estático</text> <text x="625" y="88">Pruebas de</text><text x="625" y="104">integración</text> </g> <g text-anchor="middle" font-size="11.5" fill="#5b6876"> <text x="205" y="116">1 min</text><text x="345" y="120">3 min</text><text x="485" y="120">2 min</text><text x="625" y="120">4 min</text> </g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u4t1a)"><path d="M110,92 L148,92"></path><path d="M260,92 L288,92"></path><path d="M400,92 L428,92"></path><path d="M540,92 L568,92"></path><path d="M680,92 L712,92"></path></g> <rect x="712" y="70" width="40" height="44" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="732" y="96" font-size="11.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Main</text> <rect x="150" y="160" width="440" height="52" rx="12" fill="#fbeae5" stroke="#e0a595"></rect> <text x="370" y="182" font-size="12.5" font-weight="700" fill="#b5472f" text-anchor="middle">Si cualquier etapa falla, el cambio no se fusiona</text> <text x="370" y="200" font-size="11.5" fill="#5b6876" text-anchor="middle">El equipo arregla de inmediato. Total ilustrativo: 1 + 3 + 2 + 4 = 10 minutos</text> <path d="M345,124 L345,160" fill="none" stroke="#e0a595" stroke-width="1.6" stroke-dasharray="4 4"></path> <path d="M485,124 L485,160" fill="none" stroke="#e0a595" stroke-width="1.6" stroke-dasharray="4 4"></path> <text x="380" y="240" font-size="11.5" fill="#5b6876" text-anchor="middle">Una falla se descubre minutos después de escribirla, cuando el autor aún recuerda el cambio</text>
</svg>
</div>
</section>
<section id="shift-left" class="level3">
<h3 class="anchored" data-anchor-id="shift-left">Shift-left</h3>
<p>El ISTQB llama <em>shift-left</em> al principio de pruebas tempranas, por el cual las pruebas se hacen más a la izquierda en la línea de tiempo del desarrollo. Aclara que no significa descuidar las pruebas tardías, y enumera prácticas que lo logran, entre ellas revisar la especificación desde la perspectiva de quien prueba, escribir las pruebas antes del código, usar CI y completar el análisis estático antes de las pruebas dinámicas. Reconoce que puede costar más capacitación y esfuerzo al comienzo, y espera que ahorre esfuerzo y costo después.</p>
<p>La razón económica de fondo, que un defecto cuesta más cuanto más tarde se encuentra, se discutió con sus matices en el <a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html">Tema 3 de la Unidad 1</a>. Aquí interesa la consecuencia técnica. Toda técnica que se pueda aplicar antes, se aplica antes.</p>
</section>
</section>
<section id="parte-7.-pruebas-basadas-en-riesgo" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="parte-7.-pruebas-basadas-en-riesgo"><span class="header-section-number">10</span> Parte 7. Pruebas basadas en riesgo</h2>
<section id="la-idea" class="level3">
<h3 class="anchored" data-anchor-id="la-idea">La idea</h3>
<p>El esfuerzo de prueba siempre es limitado, y probar todo con la misma profundidad es imposible. El programa del ISTQB define el riesgo como un evento potencial cuya ocurrencia causa un efecto adverso, y lo caracteriza con dos factores, la probabilidad de que ocurra y su impacto. Juntos dan el nivel de riesgo, y cuanto más alto, más importante es tratarlo.</p>
<p>El <em>análisis de riesgos del producto</em> sirve para enfocar el esfuerzo de prueba y minimizar el riesgo residual. Según el mismo programa, sus resultados se usan para decidir el alcance de las pruebas, qué niveles y tipos de prueba realizar, qué técnicas y cobertura aplicar, estimar el esfuerzo y priorizar para hallar antes los defectos críticos. La evaluación puede ser cuantitativa, y entonces el nivel de riesgo es la multiplicación de probabilidad por impacto, o cualitativa, con una matriz.</p>
<p>Esta es la misma lógica que IEEE 1012 aplica con los niveles de integridad, con la diferencia de que aquí se usa para repartir el esfuerzo dentro de un producto.</p>
</section>
<section id="ejemplo-resuelto-3.-repartir-40-horas-de-prueba" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-3.-repartir-40-horas-de-prueba">Ejemplo resuelto 3. Repartir 40 horas de prueba</h3>
<p>La Clínica Aurora dispone de 40 horas de prueba para la primera versión. Los equipos puntúan seis funciones con una escala sencilla. Probabilidad de defecto con consecuencia relevante, de 1 (baja) a 3 (alta), e impacto, de 1 (leve) a 4 (grave). Todos los valores son ilustrativos.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Función</th>
<th style="text-align: center;">Probabilidad</th>
<th style="text-align: center;">Impacto</th>
<th style="text-align: center;">Riesgo (P x I)</th>
<th style="text-align: center;">Horas (40 x riesgo / 29)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>F1. Agendar un turno</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">8,3</td>
</tr>
<tr class="even">
<td>F2. Prioridad por urgencia</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">11,0</td>
</tr>
<tr class="odd">
<td>F3. Recordatorio por SMS</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5,5</td>
</tr>
<tr class="even">
<td>F4. Historial y datos de salud</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">11,0</td>
</tr>
<tr class="odd">
<td>F5. Cambiar el tema de color</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1,4</td>
</tr>
<tr class="even">
<td>F6. Reporte mensual de ocupación</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2,8</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">29</td>
<td style="text-align: center;">40,0</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Se calcula el riesgo de cada función multiplicando probabilidad por impacto. La suma da 6 + 8 + 4 + 8 + 1 + 2 = 29.</li>
<li>Cada función recibe una fracción de las 40 horas igual a su riesgo dividido entre 29. Por ejemplo, F2 recibe 40 x 8 / 29 = 11,0 horas.</li>
<li>Las funciones con riesgo 8 (F2 y F4) reciben cerca de 22 de las 40 horas, mientras que el cambio de color recibe 1,4 horas.</li>
<li>Además de las horas, el nivel de riesgo decide el tipo de prueba. F2 y F4, con riesgo 8, justifican pruebas en todos los niveles, revisión de código por una segunda persona y una revisión de seguridad. F5 se conforma con una revisión visual.</li>
</ol>
<p>El reparto proporcional es una simplificación didáctica. El ISTQB dice que el análisis de riesgos orienta el alcance y la intensidad, no que las horas deban repartirse en proporción exacta al riesgo. Cualquier reparto debe revisarse cuando cambia el producto o aparece un defecto.</p>
<div class="diagrama">
<svg viewbox="0 0 760 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Matriz de riesgo con probabilidad de 1 a 3 en el eje horizontal e impacto de 1 a 4 en el vertical. F1 está en probabilidad 2 e impacto 3 con riesgo 6. F2 y F4 están en probabilidad 2 e impacto 4 con riesgo 8. F3 en probabilidad 2 e impacto 2 con riesgo 4. F5 en probabilidad 1 e impacto 1 con riesgo 1. F6 en probabilidad 2 e impacto 1 con riesgo 2." font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="20" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">Matriz de riesgo de la app de turnos (valores ilustrativos)</text> <g stroke="#cfd8e3"> <rect x="90" y="40" width="100" height="56" fill="#fdf3d0"></rect><rect x="190" y="40" width="100" height="56" fill="#fbeae5"></rect><rect x="290" y="40" width="100" height="56" fill="#fbeae5"></rect> <rect x="90" y="96" width="100" height="56" fill="#fdf3d0"></rect><rect x="190" y="96" width="100" height="56" fill="#fbeae5"></rect><rect x="290" y="96" width="100" height="56" fill="#fbeae5"></rect> <rect x="90" y="152" width="100" height="56" fill="#e4f2f1"></rect><rect x="190" y="152" width="100" height="56" fill="#fdf3d0"></rect><rect x="290" y="152" width="100" height="56" fill="#fbeae5"></rect> <rect x="90" y="208" width="100" height="56" fill="#e4f2f1"></rect><rect x="190" y="208" width="100" height="56" fill="#e4f2f1"></rect><rect x="290" y="208" width="100" height="56" fill="#fdf3d0"></rect> </g> <g text-anchor="end" font-size="12" fill="#5b6876"><text x="82" y="72">4 grave</text><text x="82" y="128">3</text><text x="82" y="184">2</text><text x="82" y="240">1 leve</text></g> <g text-anchor="middle" font-size="12" fill="#5b6876"><text x="140" y="284">1 baja</text><text x="240" y="284">2 media</text><text x="340" y="284">3 alta</text></g> <text x="240" y="306" font-size="12.5" font-weight="600" fill="#12324f" text-anchor="middle">Probabilidad</text> <text x="30" y="150" font-size="12.5" font-weight="600" fill="#12324f" text-anchor="middle" transform="rotate(-90 30 150)">Impacto</text> <g text-anchor="middle" font-size="13" font-weight="700" fill="#12324f"> <text x="240" y="64">F2, F4</text><text x="240" y="82" font-size="11" font-weight="400" fill="#5b6876">riesgo 8</text> <text x="240" y="120">F1</text><text x="240" y="138" font-size="11" font-weight="400" fill="#5b6876">riesgo 6</text> <text x="240" y="176">F3</text><text x="240" y="194" font-size="11" font-weight="400" fill="#5b6876">riesgo 4</text> <text x="240" y="232">F6</text><text x="240" y="250" font-size="11" font-weight="400" fill="#5b6876">riesgo 2</text> <text x="140" y="232">F5</text><text x="140" y="250" font-size="11" font-weight="400" fill="#5b6876">riesgo 1</text> </g> <g font-size="12" fill="#12324f"> <text x="440" y="66" font-weight="700">Funciones</text> <text x="440" y="90">F1 Agendar un turno</text> <text x="440" y="110">F2 Prioridad por urgencia</text> <text x="440" y="130">F3 Recordatorio por SMS</text> <text x="440" y="150">F4 Historial y datos de salud</text> <text x="440" y="170">F5 Cambiar el tema de color</text> <text x="440" y="190">F6 Reporte mensual de ocupación</text> </g> <g font-size="11.5" fill="#5b6876"> <rect x="440" y="214" width="14" height="14" fill="#fbeae5" stroke="#cfd8e3"></rect><text x="462" y="226">riesgo alto, 6 o más</text> <rect x="440" y="236" width="14" height="14" fill="#fdf3d0" stroke="#cfd8e3"></rect><text x="462" y="248">riesgo medio, 3 a 5</text> <rect x="440" y="258" width="14" height="14" fill="#e4f2f1" stroke="#cfd8e3"></rect><text x="462" y="270">riesgo bajo, 1 a 2</text> </g>
</svg>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. Reparte 30 horas
</div>
</div>
<div class="callout-body-container callout-body">
<p>La clínica añade cuatro funciones y solo dispone de 30 horas. Calcula el riesgo (P x I) de cada una, su fracción de las 30 horas, y di cuál recibe más y cuál menos.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Función</th>
<th style="text-align: center;">Probabilidad</th>
<th style="text-align: center;">Impacto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A. Cobro de copagos en línea</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td>B. Receta digital firmada</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td>C. Cambio de médico asignado</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td>D. Mensaje de bienvenida</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Riesgos. A = 3 x 2 = 6, B = 1 x 4 = 4, C = 2 x 3 = 6, D = 1 x 1 = 1. La suma es 17.</p>
<p>Horas. Cada función recibe 30 x riesgo / 17. A recibe 10,6 horas, B recibe 7,1, C recibe 10,6 y D recibe 1,8, cerca de 30 en total por el redondeo.</p>
<p>A y C reciben más, con 10,6 horas cada una, y D recibe menos, con 1,8. Observa que B tiene una probabilidad baja y un impacto máximo, y aun así recibe más de 7 horas, porque el producto de los dos factores la deja por encima de D. En la práctica, una función con impacto 4 casi siempre amerita una revisión adicional aunque su probabilidad sea baja, algo que la multiplicación sola no muestra y que el equipo debe agregar con criterio.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-8.-verificación-y-validación-independiente-ivv" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="parte-8.-verificación-y-validación-independiente-ivv"><span class="header-section-number">11</span> Parte 8. Verificación y validación independiente (IV&amp;V)</h2>
<section id="qué-agrega-la-independencia" class="level3">
<h3 class="anchored" data-anchor-id="qué-agrega-la-independencia">Qué agrega la independencia</h3>
<p>Casi toda la V&amp;V la puede ejecutar el mismo equipo que construyó el software. La <em>verificación y validación independiente</em> (IV&amp;V, por <em>independent verification and validation</em>) añade una condición organizacional, que quien verifica y valida no dependa de quien construyó. La razón es práctica. A quien desarrolló le cuesta ver sus propios supuestos, y si además su cronograma o su presupuesto dependen de los hallazgos, la presión de pasar la revisión es real.</p>
<p>El Manual de Ingeniería de Software de la NASA, en la guía del requisito SWE-141, define tres dimensiones de independencia, y las tres deben cumplirse.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Independencia</th>
<th>Qué exige según la guía de la NASA</th>
<th>Ejemplo en la clínica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Técnica</td>
<td>El personal de IV&amp;V no participó en el desarrollo del sistema que evalúa</td>
<td>El revisor del módulo de urgencia no escribió ese módulo</td>
</tr>
<tr class="even">
<td>Gerencial</td>
<td>La IV&amp;V opera bajo una cadena de mando distinta de la del desarrollo, y decide por su cuenta alcance, métodos y calendario</td>
<td>El revisor responde a la dirección de calidad, no a la jefa del proyecto</td>
</tr>
<tr class="odd">
<td>Financiera</td>
<td>El presupuesto de IV&amp;V se controla y administra aparte del de desarrollo</td>
<td>Los honorarios del revisor no salen del presupuesto del proyecto</td>
</tr>
</tbody>
</table>
<p>La misma guía agrega que no debe existir conflicto de interés real ni aparente entre el desarrollador y el agente de IV&amp;V.</p>
</section>
<section id="cuándo-se-exige-el-criterio-de-la-nasa" class="level3">
<h3 class="anchored" data-anchor-id="cuándo-se-exige-el-criterio-de-la-nasa">Cuándo se exige: el criterio de la NASA</h3>
<p>El programa de IV&amp;V de la NASA se creó en 1993 como resultado de recomendaciones del Consejo Nacional de Investigación de Estados Unidos y del informe de la comisión presidencial sobre el accidente del transbordador Challenger. Tiene su sede en el centro IV&amp;V Katherine Johnson, en Fairmont, Virginia Occidental.</p>
<p>La revisión D del NPR 7150.2, el documento de requisitos de ingeniería de software de la NASA, exige IV&amp;V en el requisito 3.6.2 (SWE-141) para proyectos que llegan al punto de decisión clave A, en tres casos.</p>
<ol type="1">
<li>Proyectos de categoría 1 según el NPR 7120.5.</li>
<li>Proyectos de categoría 2 según el NPR 7120.5 con clasificación de riesgo de carga útil clase A o B según el NPR 8705.4.</li>
<li>Proyectos que el administrador asociado de la dirección de misión (MDAA) selecciona de forma explícita.</li>
</ol>
<p>El criterio es de riesgo y de categoría de misión, no de tamaño del equipo ni de ganas del cliente. La guía describe la IV&amp;V como una actividad basada en riesgo, que busca identificar y mitigar riesgos de software para asegurar corrección, seguridad, confiabilidad y protección durante el ciclo de vida.</p>
</section>
<section id="la-ivv-y-ieee-1012" class="level3">
<h3 class="anchored" data-anchor-id="la-ivv-y-ieee-1012">La IV&amp;V y IEEE 1012</h3>
<p>La conexión con la Parte 2 es directa. En las ediciones 2012 y 2016, según el estudio de aplicación ya citado, en los niveles de integridad 3 y 4 la organización de V&amp;V ejecuta las pruebas, mientras que en el nivel 2 las puede ejecutar la de diseño y revisarlas la de V&amp;V. La independencia crece con el nivel, y IEEE 1012 la gradúa, igual que gradúa todo lo demás.</p>
</section>
<section id="ejemplo-resuelto-4.-necesita-la-clínica-una-ivv" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-4.-necesita-la-clínica-una-ivv">Ejemplo resuelto 4. ¿Necesita la clínica una IV&amp;V?</h3>
<ol type="1">
<li>Se parte de la matriz de riesgo de la Parte 7. Solo F2 (prioridad por urgencia) y F4 (historial de salud) llegan al riesgo máximo de 8.</li>
<li>El criterio de la NASA se basa en riesgo y en el efecto de una falla. En F2 una falla puede retrasar la atención de un paciente grave, y en F4 puede exponer datos sensibles.</li>
<li>IEEE 1012 permite asignar un nivel de integridad distinto a cada elemento. La clínica puede entonces aplicar el rigor máximo solo a F2 y F4, y no a toda la app.</li>
<li>Decisión razonable. Una revisión independiente solo de F2 y F4, hecha por una persona externa al equipo, que responde a la dirección de calidad y cuyos honorarios no salen del presupuesto del proyecto. El resto de la app se cubre con la V&amp;V normal del equipo.</li>
</ol>
<p>La NASA no exige esa revisión a una clínica, porque sus criterios son de misiones espaciales. El ejemplo ilustra la lógica de graduar la independencia por el riesgo, no una obligación legal.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 4. Detecta la independencia rota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una consultora desarrolla un sistema de dosificación de medicamentos para un hospital. El equipo de pruebas pertenece a la misma consultora, responde a la jefa del proyecto y se paga con el presupuesto del proyecto. La jefa decide qué se prueba y cuándo. ¿Cuál de las tres independencias (técnica, gerencial, financiera) está rota, cuáles no, y qué cambio mínimo la restauraría?</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Dos están rotas y una está comprometida, según los criterios de la NASA descritos en la Parte 8.</p>
<p>La gerencial está rota porque el equipo de pruebas responde a la jefa del proyecto y ella decide qué se prueba y cuándo, cuando la guía exige que la IV&amp;V decida por su cuenta alcance, métodos y calendario. La financiera está rota porque el presupuesto sale del proyecto. La técnica queda comprometida, porque no se dice si los probadores participaron en el desarrollo, y al ser de la misma consultora hay un conflicto de interés aparente.</p>
<p>Cambio mínimo. Contratar la prueba a un tercero con cadena de mando y presupuesto propios, y exigir que no haya participado en el desarrollo. Como el sistema de dosificación tiene consecuencias graves, en la lógica de IEEE 1012 pertenece a un nivel alto, donde la independencia es más exigente.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-9.-caso-real-mars-climate-orbiter" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="parte-9.-caso-real-mars-climate-orbiter"><span class="header-section-number">12</span> Parte 9. Caso real: Mars Climate Orbiter</h2>
<section id="los-hechos" class="level3">
<h3 class="anchored" data-anchor-id="los-hechos">Los hechos</h3>
<p>El Mars Climate Orbiter (MCO) de la NASA se lanzó el 11 de diciembre de 1998. La señal de la nave se vio por última vez cerca de las 09:04:52 UTC del 23 de septiembre de 1999, durante la maniobra de inserción en la órbita de Marte. Todo lo que sigue sale del informe de la junta de investigación de la NASA, la fase I, del 10 de noviembre de 1999.</p>
<p>La junta determinó una causa raíz. Un archivo de software en tierra, llamado SM_FORCES, entregó los datos del impulso de los propulsores en unidades inglesas (libras fuerza segundo, lbf-s), cuando la especificación de interfaz del software (SIS) exigía unidades métricas (newton segundo, N-s). El software de navegación asumió que recibía newton segundo y por eso subestimó el efecto de los propulsores en un factor de 4,45, que es el factor de conversión de libras fuerza a newtons.</p>
<p>El error era pequeño en cada maniobra, pero se acumuló durante los nueve meses de viaje. Al llegar a Marte, la trayectoria real estaba unos 170 kilómetros más baja que la planeada, y el periapsis estimado después del hecho fue de 57 kilómetros, un valor que la junta consideró demasiado bajo para que la nave sobreviviera. El planeado era de 226 kilómetros.</p>
<div class="diagrama">
<svg viewbox="0 0 760 260" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cadena del error del Mars Climate Orbiter. El software en tierra SM_FORCES escribe el impulso en libras fuerza segundo en el archivo AMD. La especificación de interfaz exigía newton segundo. El software de navegación lee el archivo asumiendo newton segundo y subestima el efecto de los propulsores por un factor de 4,45. Resultado: periapsis de 57 kilómetros en vez de 226." font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t1b" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="20" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">La cadena del error, según el informe de la junta de investigación</text> <rect x="20" y="44" width="200" height="80" rx="10" fill="#fbeae5" stroke="#e0a595"></rect> <rect x="280" y="44" width="200" height="80" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <rect x="540" y="44" width="200" height="80" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <g text-anchor="middle" font-size="12" fill="#12324f"> <text x="120" y="68" font-weight="700">SM_FORCES, en tierra</text> <text x="120" y="88">escribe el impulso en</text><text x="120" y="104">libras fuerza segundo</text> <text x="380" y="68" font-weight="700">Archivo AMD</text> <text x="380" y="88">la especificación (SIS)</text><text x="380" y="104">exigía newton segundo</text> <text x="640" y="68" font-weight="700">Navegación</text> <text x="640" y="88">lee el archivo y asume</text><text x="640" y="104">newton segundo</text> </g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u4t1b)"><path d="M220,84 L278,84"></path><path d="M480,84 L538,84"></path></g> <rect x="120" y="150" width="520" height="44" rx="10" fill="#fdf3d0" stroke="#e6cf86"></rect> <text x="380" y="170" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">El efecto de los propulsores se subestima por un factor de 4,45</text> <text x="380" y="186" font-size="11.5" fill="#5b6876" text-anchor="middle">el error se acumula durante nueve meses de viaje</text> <rect x="190" y="212" width="380" height="36" rx="10" fill="#fbeae5" stroke="#e0a595"></rect> <text x="380" y="235" font-size="12.5" font-weight="700" fill="#b5472f" text-anchor="middle">Periapsis estimado de 57 km, planeado de 226 km</text>
</svg>
</div>
</section>
<section id="qué-falló-en-la-vv" class="level3">
<h3 class="anchored" data-anchor-id="qué-falló-en-la-vv">Qué falló en la V&amp;V</h3>
<p>Lo valioso para este tema es que el informe separa la causa raíz de las ocho causas contribuyentes, y la octava es de V&amp;V. Según la junta, el proceso de verificación y validación no abordó de forma adecuada el software en tierra. El informe señala cuatro cosas.</p>
<ol type="1">
<li>La especificación de interfaz (SIS) se elaboró, pero no se usó correctamente en el desarrollo y la prueba del software de fuerzas pequeñas en tierra.</li>
<li>No parece que se haya hecho la prueba de extremo a extremo para validar el desempeño de ese software frente a la especificación.</li>
<li>No quedó claro que se hubiera hecho la verificación y validación independiente del software en tierra.</li>
<li>El control de interfaces y la verificación de interfaces específicas del sistema de tierra no se completó, o se hizo con rigor insuficiente.</li>
</ol>
<p>Las recomendaciones de la junta para la misión siguiente (Mars Polar Lander) incluyen una matriz de verificación del sistema para todos los requisitos, incluidos los documentos de control de interfaces, y revisiones independientes en todos los eventos críticos de la misión.</p>
<p>Hay una frase del informe que resume el tema. La junta reconoce que los proyectos cometen errores, pero que normalmente hay procesos para detectarlos antes de que amenacen la misión, y que en el MCO la causa raíz no fue detectada por los procesos existentes.</p>
</section>
<section id="ejemplo-resuelto-5.-la-prueba-que-faltaba" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-5.-la-prueba-que-faltaba">Ejemplo resuelto 5. La prueba que faltaba</h3>
<p>La verificación de interfaces compara una salida contra un contrato escrito. Una comprobación mínima habría bastado. Suponte que la salida de SM_FORCES para un evento de desaturación fue de 10 en libras fuerza segundo.</p>
<ol type="1">
<li>El contrato dice newton segundo, así que el valor correcto del archivo debía ser 10 x 4,45 = 44,5 N-s.</li>
<li>La navegación leyó 10 asumiendo newton segundo, y por eso usó 10 donde debía usar 44,5.</li>
<li>El cociente es 44,5 / 10 = 4,45, el factor que reporta la junta.</li>
<li>Una prueba de contrato con un caso conocido, por ejemplo un propulsor con impulso 44,5 N-s esperado, habría fallado de inmediato con la salida en lbf-s.</li>
</ol>
<p>La lección no depende de la astronáutica. Cualquier unión entre dos equipos, o entre un equipo y un proveedor, necesita una prueba que compruebe unidades, formato y zona horaria contra el contrato. En la clínica, por ejemplo, el proveedor de SMS debe recibir la hora del turno en la misma zona horaria con la que la app la guarda.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 5. ¿Verificación, validación o IV&amp;V?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para cada control, di si habría detectado el error del MCO y de qué tipo es (verificación, validación o IV&amp;V), según el informe.</p>
<ol type="a">
<li>Una revisión de código del módulo de tierra contra la especificación de interfaz.</li>
<li>Una prueba de extremo a extremo que usa la salida real de SM_FORCES como entrada de la navegación.</li>
<li>Un equipo externo, con otra cadena de mando y otro presupuesto, que revisa el software de tierra.</li>
<li>Una prueba de que la nave, ya en el espacio, responde a los comandos de los propulsores.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>Sí lo habría detectado, y es verificación estática. Compara el código con el contrato SIS, y la junta dice que la SIS no se usó correctamente en el desarrollo.</p></li>
<li><p>Sí, y es verificación dinámica de extremo a extremo. El informe señala que no parece haberse hecho una prueba de extremo a extremo del software de fuerzas pequeñas.</p></li>
<li><p>Posiblemente, y es IV&amp;V. El informe dice que no quedó claro que se hubiera hecho IV&amp;V del software en tierra. La IV&amp;V no garantiza hallar el error, pero agrega una revisión con otra mirada y sin presión de cronograma.</p></li>
<li><p>No lo habría detectado. El software de a bordo usaba unidades métricas y era correcto, según el informe. El error estaba en el software de tierra, y esa prueba no lo toca.</p></li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="errores-frecuentes" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="errores-frecuentes"><span class="header-section-number">13</span> Errores frecuentes</h2>
<ul>
<li>Usar verificación y validación como sinónimos. Una app puede pasar toda la verificación y fallar la validación, como en el ejemplo del cupo.</li>
<li>Dejar la validación para el final. Una maqueta o un prototipo ya se pueden validar, y cuanto antes se haga, menos cuesta corregir un requisito equivocado.</li>
<li>Creer que más pruebas dinámicas reemplazan las revisiones. Cada familia encuentra defectos que la otra deja pasar.</li>
<li>Pedir la misma V&amp;V para todo el producto. IEEE 1012 grada el rigor por nivel de integridad, y las pruebas basadas en riesgo reparten el esfuerzo.</li>
<li>Citar la tabla de integridad de IEEE 1012 sin haberla leído. Es de pago, y las ediciones cambian.</li>
<li>Dibujar el modelo en V y no planear las pruebas en la fase de la izquierda. Sin el plan escrito junto al requisito, la V es un dibujo.</li>
<li>Confundir CI con tener un servidor de construcción. Sin pruebas automáticas que corran en cada commit y sin arreglar de inmediato lo que falla, no hay integración continua.</li>
<li>Llamar independiente a una revisión que depende del mismo jefe o del mismo presupuesto. La independencia técnica, la gerencial y la financiera se cumplen las tres.</li>
<li>Concluir del caso Mars Climate Orbiter que el problema fue “un error de unidades”. El informe lo llama causa raíz y detalla ocho causas contribuyentes, entre ellas la V&amp;V.</li>
</ul>
</section>
<section id="lo-que-sigue" class="level2" data-number="14">
<h2 data-number="14" class="anchored" data-anchor-id="lo-que-sigue"><span class="header-section-number">14</span> Lo que sigue</h2>
<p>El <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html">Tema 2</a> lleva la distinción de este tema al terreno más barato para aplicarla, los requisitos. Aprenderás a comprobar que un requisito esté bien escrito (verificación de requisitos) y que sea lo que el usuario necesita (validación de requisitos), el trabajo que habría corregido R1 antes de escribir una línea de código.</p>
</section>
<section id="autoevaluación" class="level2" data-number="15">
<h2 data-number="15" class="anchored" data-anchor-id="autoevaluación"><span class="header-section-number">15</span> Autoevaluación</h2>
<p>Marca la opción que consideres correcta y abre la clave para comprobar.</p>
<p><strong>1.</strong> ¿Qué pregunta responde la validación?</p>
<p><label><input type="checkbox"> Si el producto se construyó correctamente contra la especificación</label><br> <label><input type="checkbox"> Si se construyó el producto correcto para el uso previsto</label><br> <label><input type="checkbox"> Si el código tiene errores de sintaxis</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. La verificación compara contra la especificación y la validación contra la necesidad real del usuario.</p>
</div>
</div>
</div>
<p><strong>2.</strong> A octubre de 2026, ¿qué edición de IEEE 1012 está vigente?</p>
<p><label><input type="checkbox"> IEEE 1012-2012</label><br> <label><input type="checkbox"> IEEE 1012-2016</label><br> <label><input type="checkbox"> IEEE 1012-2024</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 3. La ficha del IEEE la muestra como estándar activo, publicado el 22 de agosto de 2025, y reemplaza a la edición 2016.</p>
</div>
</div>
</div>
<p><strong>3.</strong> ¿Para qué sirve el nivel de integridad en IEEE 1012?</p>
<p><label><input type="checkbox"> Para graduar el alcance, la intensidad y el rigor de la V&amp;V según la importancia del sistema o componente</label><br> <label><input type="checkbox"> Para medir cuántas líneas de código tiene el sistema</label><br> <label><input type="checkbox"> Para certificar a la organización</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. A menor nivel, menor alcance, intensidad y rigor. No mide tamaño ni certifica organizaciones.</p>
</div>
</div>
</div>
<p><strong>4.</strong> En el modelo en V, ¿con qué nivel de prueba se empareja la fase de requisitos?</p>
<p><label><input type="checkbox"> Pruebas unitarias</label><br> <label><input type="checkbox"> Pruebas de integración</label><br> <label><input type="checkbox"> Pruebas de aceptación</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 3. El plan de pruebas de aceptación se escribe mientras se levantan los requisitos.</p>
</div>
</div>
</div>
<p><strong>5.</strong> Un revisor encuentra que una condición está mal escrita leyendo el código, sin ejecutarlo. ¿Qué tipo de técnica usó?</p>
<p><label><input type="checkbox"> Estática</label><br> <label><input type="checkbox"> Dinámica</label><br> <label><input type="checkbox"> Ninguna, solo las pruebas encuentran defectos</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Las técnicas estáticas examinan el producto sin ejecutarlo y encuentran los defectos directamente.</p>
</div>
</div>
</div>
<p><strong>6.</strong> ¿Cuál es el orden de los pasos de TDD?</p>
<p><label><input type="checkbox"> Escribir el código, escribir las pruebas, refactorizar</label><br> <label><input type="checkbox"> Escribir las pruebas, escribir el código que las satisface, refactorizar</label><br> <label><input type="checkbox"> Refactorizar, escribir las pruebas, escribir el código</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2, según el programa del ISTQB. Primero se escriben las pruebas, luego el código, y luego se refactoriza.</p>
</div>
</div>
</div>
<p><strong>7.</strong> Dos funciones tienen riesgos de 8 y de 2. Si se reparten 20 horas en proporción al riesgo, ¿cuántas recibe la de riesgo 8?</p>
<p><label><input type="checkbox"> 4 horas</label><br> <label><input type="checkbox"> 16 horas</label><br> <label><input type="checkbox"> 10 horas</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. La suma de riesgos es 10 y 20 x 8 / 10 = 16 horas, mientras que la de riesgo 2 recibe 4.</p>
</div>
</div>
</div>
<p><strong>8.</strong> ¿Qué tres independencias exige la NASA en una IV&amp;V?</p>
<p><label><input type="checkbox"> Técnica, gerencial y financiera</label><br> <label><input type="checkbox"> Legal, comercial y cultural</label><br> <label><input type="checkbox"> Técnica, de calendario y de marca</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Según la guía del requisito SWE-141, las tres deben cumplirse.</p>
</div>
</div>
</div>
<p><strong>9.</strong> Según el informe de la junta de investigación, ¿cuál fue la causa raíz de la pérdida del Mars Climate Orbiter?</p>
<p><label><input type="checkbox"> No se usaron unidades métricas en la codificación de un archivo de software en tierra, usado en los modelos de trayectoria</label><br> <label><input type="checkbox"> Una falla del motor principal</label><br> <label><input type="checkbox"> Una interferencia de radio durante el viaje</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. El informe de la fase I dice que el archivo SM_FORCES usó unidades inglesas, y que la navegación asumió unidades métricas, lo que subestimó el efecto de los propulsores en un factor de 4,45.</p>
</div>
</div>
</div>
<p><strong>10.</strong> Una app pasa todas las pruebas contra su especificación y, aun así, los usuarios no pueden usarla en su trabajo. ¿Qué actividad faltó?</p>
<p><label><input type="checkbox"> Más verificación del código</label><br> <label><input type="checkbox"> Validación con usuarios reales</label><br> <label><input type="checkbox"> Un cambio de lenguaje de programación</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 10
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Es la falacia de la ausencia de defectos que describe el ISTQB, porque verificar bien no garantiza que el sistema cumpla lo que se necesita.</p>
</div>
</div>
</div>
</section>
<section id="lo-que-te-llevas" class="level2" data-number="16">
<h2 data-number="16" class="anchored" data-anchor-id="lo-que-te-llevas"><span class="header-section-number">16</span> Lo que te llevas</h2>
<div class="checklist">
<p><strong>Al salir de este tema deberías poder explicar, sin mirar la guía</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">La diferencia entre verificar y validar, y un ejemplo de una app que cumple su especificación y no sirve</label></li>
<li><label><input type="checkbox">Qué edición de IEEE 1012 está vigente, qué es un nivel de integridad y por qué la V&amp;V se gradúa</label></li>
<li><label><input type="checkbox">Qué fuente de la tabla de integridad no se pudo verificar y por qué</label></li>
<li><label><input type="checkbox">Cómo empareja el modelo en V cada fase con su nivel de prueba y cuándo se planea cada plan</label></li>
<li><label><input type="checkbox">Qué encuentra cada familia, la estática y la dinámica, y por qué se necesitan las dos</label></li>
<li><label><input type="checkbox">Qué aportan TDD, la integración continua y el shift-left a la V&amp;V diaria</label></li>
<li><label><input type="checkbox">Cómo se reparte un esfuerzo de prueba limitado según el riesgo, con cálculo</label></li>
<li><label><input type="checkbox">Qué significa que una V&amp;V sea independiente en lo técnico, lo gerencial y lo financiero, y cuándo la exige la NASA</label></li>
<li><label><input type="checkbox">Qué falló en la V&amp;V del Mars Climate Orbiter según el informe oficial</label></li>
</ul>
</div>
</section>
<section id="glosario" class="level2" data-number="17">
<h2 data-number="17" class="anchored" data-anchor-id="glosario"><span class="header-section-number">17</span> Glosario</h2>
<ul>
<li><strong>Verificación.</strong> Comprobar si el producto, o un producto de trabajo, cumple la especificación acordada. Pregunta si se construyó correctamente.</li>
<li><strong>Validación.</strong> Comprobar si el producto satisface las necesidades reales del usuario en su entorno de uso. Pregunta si se construyó lo correcto.</li>
<li><strong>V&amp;V.</strong> Verificación y validación.</li>
<li><strong>IV&amp;V.</strong> Verificación y validación independientes: hechas por una organización técnica, gerencial y financieramente independiente de la que desarrolla.</li>
<li><strong>IEEE 1012.</strong> Estándar del IEEE para los procesos de V&amp;V de sistemas, software y hardware. Edición vigente a octubre de 2026: 1012-2024.</li>
<li><strong>Nivel de integridad.</strong> Valor que expresa la importancia de un sistema o componente para el usuario y que gradúa el alcance, la intensidad y el rigor de la V&amp;V.</li>
<li><strong>Modelo en V.</strong> Representación secuencial del desarrollo en la que cada fase de construcción se empareja con un nivel de prueba.</li>
<li><strong>Técnica estática.</strong> Examen de un producto de trabajo sin ejecutarlo, como una revisión o el análisis estático de código.</li>
<li><strong>Técnica dinámica.</strong> Prueba que ejecuta el software y observa su comportamiento.</li>
<li><strong>Prueba de componente o unitaria.</strong> Prueba de un componente en aislamiento.</li>
<li><strong>Prueba de integración.</strong> Prueba de las interfaces y la interacción entre componentes.</li>
<li><strong>Prueba de sistema.</strong> Prueba del comportamiento global de un sistema completo.</li>
<li><strong>Prueba de aceptación.</strong> Prueba centrada en la validación y la disposición para el despliegue, idealmente a cargo de los usuarios.</li>
<li><strong>Valor límite.</strong> Valor en el borde de un rango, como el turno 20 y el 21 en un cupo de 20.</li>
<li><strong>TDD.</strong> Desarrollo guiado por pruebas: se escriben primero las pruebas, luego el código y luego se refactoriza.</li>
<li><strong>Integración continua (CI).</strong> Práctica de fusionar cambios a la base común al menos a diario, con una construcción automática que incluye pruebas.</li>
<li><strong>Shift-left.</strong> Hacer las pruebas y las revisiones más temprano en el ciclo de vida.</li>
<li><strong>Riesgo.</strong> Evento potencial cuya ocurrencia causa un efecto adverso, caracterizado por su probabilidad y su impacto.</li>
<li><strong>Prueba basada en riesgo.</strong> Reparto del esfuerzo de prueba según el nivel de riesgo de cada función.</li>
<li><strong>Prueba de regresión.</strong> Prueba que se repite tras un cambio para confirmar que lo anterior sigue funcionando.</li>
<li><strong>Independencia técnica, gerencial y financiera.</strong> Las tres dimensiones que exige la NASA a la IV&amp;V: no haber participado en el desarrollo, tener otra cadena de mando y tener presupuesto propio.</li>
<li><strong>SIS.</strong> Especificación de interfaz de software, el documento que define el formato y las unidades de un archivo entre dos sistemas.</li>
<li><strong>Causa raíz y causa contribuyente.</strong> En una investigación de accidentes, el hecho dominante que originó la falla y los factores que la causaron o agravaron.</li>
</ul>
</section>
<section id="bibliografía" class="level2" data-number="18">
<h2 data-number="18" class="anchored" data-anchor-id="bibliografía"><span class="header-section-number">18</span> Bibliografía</h2>
<p>Consultas hechas el 3 de octubre de 2026.</p>
<p>Sobre verificación, validación y estándares:</p>
<ul>
<li>Boehm, B. W. (1984). Verifying and Validating Software Requirements and Design Specifications. <em>IEEE Software</em>, 1(1), 75 a 88. <a href="https://doi.org/10.1109/MS.1984.233702">doi.org</a>. Texto de pago, no leído.</li>
<li>Boehm, B. W. (1981). <em>Software Engineering Economics.</em> Prentice-Hall. Citado por el programa del ISTQB.</li>
<li>IEEE Standards Association. <a href="https://standards.ieee.org/ieee/1012/7324/">IEEE 1012-2024, Standard for System, Software, and Hardware Verification and Validation</a>. Aprobada el 12 de noviembre de 2024, publicada el 22 de agosto de 2025, activa. Texto de pago, no leído.</li>
<li>IEEE Standards Association. <a href="https://standards.ieee.org/ieee/1012/5609/">IEEE 1012-2016</a>. Publicada el 29 de septiembre de 2017, reemplazada por la 2024.</li>
<li>Kim, J.-K., Woo, J.-B., Kim, S.-J., Kim, H.-W., Ro, Y.-S., Choi, J. y Park, J.-H. (2017). Application Study for Implementing IEEE 1012-2016. <em>Transactions of the Korean Nuclear Society Spring Meeting</em>, Jeju, 18 y 19 de mayo de 2017. Fuente abierta sobre niveles de integridad y cambios entre ediciones.</li>
<li>ISO/IEC/IEEE 15026-3:2023. <em>Systems and software engineering, Systems and software assurance, Part 3: System integrity levels.</em> Tercera edición, octubre de 2023. Se consultó la vista previa del editor.</li>
<li>IEEE Standards Association. <a href="https://standards.ieee.org/ieee/12207/11416">ISO/IEC/IEEE 12207-2026</a>, publicada el 15 de abril de 2026, y <a href="https://standards.ieee.org/ieee/12207/5672/">12207-2017</a>, reemplazada. Ver también el Tema 1 de la Unidad 3.</li>
<li><a href="https://en.wikipedia.org/wiki/ISO/IEC_29119">Wikipedia: ISO/IEC 29119</a>. Fuente secundaria para las ediciones de las partes de la serie. Verifica en el editor.</li>
</ul>
<p>Sobre técnicas, TDD, CI y riesgo:</p>
<ul>
<li>ISTQB (2024). <em>Certified Tester Foundation Level Syllabus, v4.0.1</em>, 15 de septiembre de 2024. <a href="https://www.istqb.org/certifications/certified-tester-foundation-level">Página de la certificación</a>.</li>
<li>Beck, K. (2003). <em>Test-Driven Development: By Example.</em> Addison-Wesley. Año según la referencia del programa del ISTQB.</li>
<li>Fowler, M. (18 de enero de 2024). <a href="https://martinfowler.com/articles/continuousIntegration.html">Continuous Integration</a>.</li>
<li>DORA. <a href="https://dora.dev/capabilities/continuous-integration/">Capability: Continuous integration</a>.</li>
</ul>
<p>Sobre IV&amp;V y el caso real:</p>
<ul>
<li>NASA. <a href="https://swehb.nasa.gov/spaces/SWEHBVD/pages/102695499/SWE-141+-+Software+Independent+Verification+and+Validation">Software Engineering Handbook, SWE-141, Software Independent Verification and Validation</a>. Asociado al NPR 7150.2, revisión D.</li>
<li>NASA. <a href="https://www.nasa.gov/about-nasas-ivv-program/">About NASA’s IV&amp;V Program</a>.</li>
<li>NASA Mishap Investigation Board (10 de noviembre de 1999). <em>Mars Climate Orbiter Mishap Investigation Board, Phase I Report.</em> <a href="https://llis.nasa.gov/llis_lib/pdf/1009464main1_0641-mr.pdf">Copia en el sistema de lecciones aprendidas de la NASA</a> y <a href="https://www.dcs.gla.ac.uk/~johnson/Mars/MCO_report.pdf">copia de la Universidad de Glasgow</a>, de donde se leyó el texto.</li>
<li>NASA. <a href="https://science.nasa.gov/mission/mars-climate-orbiter/">Mars Climate Orbiter</a>. Fechas de lanzamiento y pérdida.</li>
</ul>
<div class="pie-doc">
<p>Calidad del software (CDS01). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado. Las salidas de pytest son capturas reales tomadas durante la preparación del material.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>