<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 2. El dibujo que decide la llave foránea – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-9d905b06f1e8b96cef5de7dac512495c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-02/index.html">Unidad 2. Modelo entidad relación</a></li><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-02/tema-02-representacion-cardinalidad/index.html">Tema 2. El dibujo que decide la llave foránea</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Introducción a los sistemas de bases de datos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-01/tema-01-datos-informacion-conocimiento/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Datos, información y el archivo que se queda corto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-01/tema-02-integracion-organizacional/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Una base de datos, toda la empresa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/actividad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Actividad 1. Profundicen la Unidad 1</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Modelo entidad relación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-02/tema-01-componentes-mer/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Las piezas con las que se dibuja la realidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-02/tema-02-representacion-cardinalidad/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 2. El dibujo que decide la llave foránea</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#para-qué-se-dibuja-un-modelo-antes-de-programarlo" id="toc-para-qué-se-dibuja-un-modelo-antes-de-programarlo" class="nav-link active" data-scroll-target="#para-qué-se-dibuja-un-modelo-antes-de-programarlo"><span class="header-section-number">1</span> Para qué se dibuja un modelo antes de programarlo</a></li>
  <li><a href="#la-notación-de-chen" id="toc-la-notación-de-chen" class="nav-link" data-scroll-target="#la-notación-de-chen"><span class="header-section-number">2</span> La notación de Chen</a></li>
  <li><a href="#cardinalidad-de-mapeo-cuántos-con-cuántos" id="toc-cardinalidad-de-mapeo-cuántos-con-cuántos" class="nav-link" data-scroll-target="#cardinalidad-de-mapeo-cuántos-con-cuántos"><span class="header-section-number">3</span> Cardinalidad de mapeo: cuántos con cuántos</a></li>
  <li><a href="#participación-total-y-parcial" id="toc-participación-total-y-parcial" class="nav-link" data-scroll-target="#participación-total-y-parcial"><span class="header-section-number">4</span> Participación total y parcial</a></li>
  <li><a href="#la-notación-de-pata-de-gallo" id="toc-la-notación-de-pata-de-gallo" class="nav-link" data-scroll-target="#la-notación-de-pata-de-gallo"><span class="header-section-number">5</span> La notación de pata de gallo</a></li>
  <li><a href="#el-caso-de-estudio-la-cafetería-completa" id="toc-el-caso-de-estudio-la-cafetería-completa" class="nav-link" data-scroll-target="#el-caso-de-estudio-la-cafetería-completa"><span class="header-section-number">6</span> El caso de estudio: la cafetería, completa</a></li>
  <li><a href="#el-mismo-modelo-en-pata-de-gallo" id="toc-el-mismo-modelo-en-pata-de-gallo" class="nav-link" data-scroll-target="#el-mismo-modelo-en-pata-de-gallo"><span class="header-section-number">7</span> El mismo modelo en pata de gallo</a></li>
  <li><a href="#traducir-el-diagrama-a-tablas" id="toc-traducir-el-diagrama-a-tablas" class="nav-link" data-scroll-target="#traducir-el-diagrama-a-tablas"><span class="header-section-number">8</span> Traducir el diagrama a tablas</a></li>
  <li><a href="#dos-errores-frecuentes-al-pasar-del-dibujo-a-la-tabla" id="toc-dos-errores-frecuentes-al-pasar-del-dibujo-a-la-tabla" class="nav-link" data-scroll-target="#dos-errores-frecuentes-al-pasar-del-dibujo-a-la-tabla"><span class="header-section-number">9</span> Dos errores frecuentes al pasar del dibujo a la tabla</a></li>
  <li><a href="#lo-que-te-llevas-de-hoy" id="toc-lo-que-te-llevas-de-hoy" class="nav-link" data-scroll-target="#lo-que-te-llevas-de-hoy"><span class="header-section-number">10</span> Lo que te llevas de hoy</a></li>
  <li><a href="#cierre-de-la-unidad-2" id="toc-cierre-de-la-unidad-2" class="nav-link" data-scroll-target="#cierre-de-la-unidad-2"><span class="header-section-number">11</span> Cierre de la Unidad 2</a></li>
  <li><a href="#recursos" id="toc-recursos" class="nav-link" data-scroll-target="#recursos"><span class="header-section-number">12</span> Recursos</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-02/index.html">Unidad 2. Modelo entidad relación</a></li><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-02/tema-02-representacion-cardinalidad/index.html">Tema 2. El dibujo que decide la llave foránea</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 2. El dibujo que decide la llave foránea</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">18 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 88%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 2. Modelo entidad relación</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 2. Representación gráfica, cardinalidad y participación</td>
</tr>
</tbody>
</table>
</div>
<p><a href="../../../base-de-datos/unidad-02/tema-02-representacion-cardinalidad/presentacion.html">Diapositivas de la sesión</a></p>
<p>El Tema 1 de esta unidad dio el vocabulario para nombrar las piezas de un modelo entidad relación, que entidad fuerte y entidad débil, que atributo simple, compuesto, multivaluado o derivado, que relación entre entidades y que clave candidata y clave primaria. Hoy esas piezas se dibujan con una notación estándar, para que el modelo se pueda discutir con alguien que conoce el negocio y no sabe nada de bases de datos, y para que cada relación quede marcada con dos datos que van a decidir directamente cómo se construye la tabla en la Unidad 3, cuántas instancias de una entidad se asocian con cuántas de la otra, que es la cardinalidad, y si una entidad puede existir sin participar en la relación, que es la participación. Cierras el tema con un caso completo, una cafetería que guarda sus pedidos en una sola tabla plana con el teléfono del cliente repetido en cada línea, para modelarla como un diagrama entidad relación completo, con sus entidades separadas, su relación y las llaves foráneas que evitan esa redundancia por diseño.</p>
<section id="para-qué-se-dibuja-un-modelo-antes-de-programarlo" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="para-qué-se-dibuja-un-modelo-antes-de-programarlo"><span class="header-section-number">1</span> Para qué se dibuja un modelo antes de programarlo</h2>
<p>Peter Chen publicó en 1976, en la revista ACM Transactions on Database Systems, el artículo que le dio nombre al modelo entidad relación, con un objetivo explícito en el propio título, ofrecer una vista unificada de los datos que sirviera tanto para el diseño lógico como para el diseño conceptual de una base de datos. La idea que sostiene ese objetivo es que un diagrama, a diferencia de un párrafo de requisitos o de un conjunto de tablas en SQL, o <em>structured query language</em>, el lenguaje estándar para consultar y definir bases de datos relacionales, lo puede leer y corregir alguien que no programa, porque el dibujo usa cajas y líneas en vez de sintaxis, y eso convierte el modelo en un punto de encuentro entre quien conoce el negocio y quien va a construir la base de datos. El diagrama entidad relación es, en palabras de Silberschatz, Korth y Sudarshan en <em>Database System Concepts</em>, la forma de expresar de manera gráfica la estructura lógica completa de una base de datos.</p>
<p>Existen varias notaciones para dibujar ese mismo modelo, y este tema cubre las dos que vas a encontrar con más frecuencia, la notación original de Chen, que separa con cuidado cada concepto en un símbolo distinto, y la notación de pata de gallo, que hoy usan la mayoría de las herramientas de modelado porque combina cardinalidad y participación en un solo símbolo compuesto. Las dos representan exactamente la misma información, así que aprender a traducir de una a la otra es parte del objetivo de hoy.</p>
</section>
<section id="la-notación-de-chen" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="la-notación-de-chen"><span class="header-section-number">2</span> La notación de Chen</h2>
<p>En la notación de Chen, cada concepto del Tema 1 tiene un símbolo geométrico propio. Un rectángulo representa un conjunto de entidades. Un óvalo representa un atributo, conectado por una línea a la entidad o a la relación a la que pertenece, y cuando el atributo es compuesto se dibuja como un pequeño árbol de óvalos, el óvalo del atributo compuesto conectado a los óvalos de sus componentes. El atributo o los atributos que forman la clave primaria se subrayan. Un rombo, o diamante, representa un conjunto de relaciones, y se conecta con líneas a cada uno de los rectángulos que participan en ella. Una entidad débil se dibuja con un rectángulo de borde doble, su discriminador se subraya con una línea punteada en vez de una línea continua, porque por sí solo no identifica de forma única a la entidad, y la relación identificadora que la conecta con su entidad fuerte se dibuja con un rombo de borde doble.</p>
<div class="diagrama">
<svg viewbox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Símbolos de la notación de Chen: rectángulo para entidad fuerte, óvalo para atributo con la clave primaria subrayada, rombo para relación; abajo el mismo trío con borde doble para entidad débil, óvalo punteado para discriminador y rombo doble para relación identificadora" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Cuatro símbolos, cuatro conceptos del Tema 1</text> <g fill="none" stroke="#8fb3d1" stroke-width="1.6"><line x1="176" y1="70" x2="222" y2="70"></line><line x1="330" y1="70" x2="380" y2="70"></line><line x1="486" y1="70" x2="540" y2="70"></line></g> <rect x="30" y="46" width="146" height="48" rx="4" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="103" y="74" font-size="13" font-weight="600" fill="#12324f" text-anchor="middle">Cliente</text> <ellipse cx="276" cy="70" rx="54" ry="26" fill="#eef4fa" stroke="#c7d6e6"></ellipse> <text x="276" y="66" font-size="11.5" fill="#12324f" text-anchor="middle" text-decoration="underline">id_cliente</text> <text x="276" y="80" font-size="11.5" fill="#5b6876" text-anchor="middle">(clave primaria)</text> <polygon points="382,70 434,44 486,70 434,96" fill="#eef4fa" stroke="#c7d6e6"></polygon> <text x="434" y="74" font-size="12" font-weight="600" fill="#12324f" text-anchor="middle">Realiza</text> <rect x="542" y="46" width="146" height="48" rx="4" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="615" y="74" font-size="13" font-weight="600" fill="#12324f" text-anchor="middle">Pedido</text> <g font-size="11" fill="#5b6876" text-anchor="middle"><text x="103" y="110">entidad</text><text x="276" y="118">atributo</text><text x="434" y="122">relación</text><text x="615" y="110">entidad</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.6"><line x1="200" y1="220" x2="238" y2="220"></line><line x1="336" y1="220" x2="378" y2="220"></line><line x1="486" y1="220" x2="528" y2="220"></line></g> <rect x="30" y="196" width="164" height="48" rx="4" fill="#f5f7fa" stroke="#cfd8e3"></rect> <rect x="36" y="202" width="152" height="36" rx="3" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="112" y="224" font-size="12.5" font-weight="600" fill="#12324f" text-anchor="middle">Detalle_Pedido</text> <ellipse cx="280" cy="220" rx="58" ry="26" fill="#f5f7fa" stroke="#cfd8e3" stroke-dasharray="3 3"></ellipse> <text x="280" y="224" font-size="11" fill="#12324f" text-anchor="middle">discriminador</text> <polygon points="382,220 432,196 482,220 432,244" fill="#f5f7fa" stroke="#cfd8e3"></polygon> <polygon points="390,220 432,202 474,220 432,238" fill="none" stroke="#cfd8e3"></polygon> <text x="432" y="224" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">Identifica</text> <rect x="530" y="196" width="146" height="48" rx="4" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="603" y="224" font-size="13" font-weight="600" fill="#12324f" text-anchor="middle">Pedido</text> <g font-size="11" fill="#5b6876" text-anchor="middle"><text x="112" y="260">entidad débil</text><text x="280" y="266">discriminador</text><text x="432" y="270">relación identificadora</text><text x="603" y="260">entidad dueña</text></g> <text x="380" y="290" font-size="11" fill="#5b6876" text-anchor="middle">Borde doble = depende de otra entidad para existir; línea punteada = no identifica por sí sola</text>
</svg>
</div>
<p>La mayoría de relaciones que vas a modelar en este curso son binarias, es decir que conectan exactamente dos conjuntos de entidades, y el resto de este tema trabaja solo con ese caso. También existen relaciones ternarias, de tres entidades, o de grado todavía mayor. Silberschatz, Korth y Sudarshan usan como ejemplo una relación entre instructor, estudiante y proyecto, donde las tres entidades participan a la vez en una sola asociación que no se puede partir limpiamente en dos relaciones binarias. Cuando eso ocurre, la regla de seguridad para el dibujo es que como máximo una de las líneas que salen del rombo puede llevar flecha, porque con dos o más flechas a la vez el diagrama admite más de una lectura posible y deja de ser inequívoco. Ese caso queda fuera del alcance de este curso, pero conviene saber que existe, para no sorprenderte si lo encuentras en un modelo más adelante en la carrera.</p>
</section>
<section id="cardinalidad-de-mapeo-cuántos-con-cuántos" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="cardinalidad-de-mapeo-cuántos-con-cuántos"><span class="header-section-number">3</span> Cardinalidad de mapeo: cuántos con cuántos</h2>
<p>La <em>cardinalidad de mapeo</em> expresa el número de entidades a las que otra entidad puede estar asociada a través de una relación. Para relaciones binarias existen cuatro combinaciones posibles, uno a uno, uno a muchos, muchos a uno y muchos a muchos, y las dos últimas son en realidad la misma idea vista desde cada lado. La notación de Chen dibuja esa cardinalidad con líneas dirigidas o no dirigidas sobre cada extremo de la relación. Una línea dirigida, con flecha, significa que cada instancia del otro lado se asocia como máximo con una instancia de la entidad hacia la que apunta la flecha, y una línea no dirigida, sin flecha, significa que se puede asociar con varias.</p>
<div class="diagrama">
<svg viewbox="0 0 760 320" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Tres filas mostrando la cardinalidad de mapeo entre Cliente y Tarjeta de fidelidad como uno a uno con flecha en ambos extremos, entre Cliente y Pedido como uno a muchos con flecha solo hacia Cliente, y entre Pedido y Producto como muchos a muchos sin flechas" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="base22a" markerwidth="9" markerheight="9" refx="7" refy="3" orient="auto"><path d="M0,0 L7,3 L0,6 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">La flecha va sobre el lado “uno”; la línea sin flecha va sobre el lado “muchos”</text> <g font-size="11.5" font-weight="700" fill="#0e6f6c" text-anchor="middle"><text x="700" y="55">1 a 1</text><text x="700" y="165">1 a N</text><text x="700" y="275">M a N</text></g> <rect x="40" y="34" width="150" height="46" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="115" y="62" font-size="12.5" font-weight="600" fill="#12324f" text-anchor="middle">Cliente</text> <polygon points="260,57 310,34 360,57 310,80" fill="#eef4fa" stroke="#c7d6e6"></polygon> <text x="310" y="61" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">Tiene</text> <rect x="430" y="34" width="180" height="46" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="520" y="62" font-size="12" font-weight="600" fill="#12324f" text-anchor="middle">TarjetaFidelidad</text> <path d="M195,57 L255,57" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#base22a)"></path> <path d="M425,57 L365,57" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#base22a)"></path> <text x="380" y="98" font-size="11.5" fill="#5b6876" text-anchor="middle">cada tarjeta es de un cliente, y cada cliente tiene a lo sumo una tarjeta</text> <rect x="40" y="144" width="150" height="46" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="115" y="172" font-size="12.5" font-weight="600" fill="#12324f" text-anchor="middle">Cliente</text> <polygon points="260,167 310,144 360,167 310,190" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <text x="310" y="171" font-size="11.5" font-weight="600" fill="#0e6f6c" text-anchor="middle">Realiza</text> <rect x="430" y="144" width="180" height="46" rx="6" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="520" y="172" font-size="12.5" font-weight="600" fill="#0e6f6c" text-anchor="middle">Pedido</text> <path d="M195,167 L255,167" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#base22a)"></path> <path d="M425,167 L365,167" fill="none" stroke="#8fb3d1" stroke-width="1.6"></path> <text x="380" y="208" font-size="11.5" fill="#5b6876" text-anchor="middle">cada pedido es de un cliente (flecha), pero un cliente hace varios pedidos (sin flecha)</text> <rect x="40" y="254" width="150" height="46" rx="6" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="115" y="282" font-size="12.5" font-weight="600" fill="#0e6f6c" text-anchor="middle">Pedido</text> <polygon points="260,277 310,254 360,277 310,300" fill="#eef4fa" stroke="#c7d6e6"></polygon> <text x="310" y="281" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">Contiene</text> <rect x="430" y="254" width="180" height="46" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="520" y="282" font-size="12.5" font-weight="600" fill="#12324f" text-anchor="middle">Producto</text> <path d="M195,277 L255,277" fill="none" stroke="#8fb3d1" stroke-width="1.6"></path> <path d="M425,277 L365,277" fill="none" stroke="#8fb3d1" stroke-width="1.6"></path>
</svg>
</div>
<p>Fíjate en algo que va a importar mucho en la Unidad 3, la flecha apunta hacia el lado que en la tabla final va a recibir la llave foránea, es decir hacia el lado uno, exactamente en la misma dirección en que después va a apuntar esa llave. Un pedido pertenece a un cliente, así que la tabla <code>Pedido</code> va a guardar el identificador de ese cliente, nunca al revés. Un producto que aparece en varios pedidos y un pedido que contiene varios productos no dejan que ninguna de las dos tablas guarde una sola llave foránea hacia la otra, y ese es justo el caso muchos a muchos que vas a resolver más adelante con una tabla propia para la relación.</p>
</section>
<section id="participación-total-y-parcial" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="participación-total-y-parcial"><span class="header-section-number">4</span> Participación total y parcial</h2>
<p>La <em>participación</em> de una entidad en una relación dice si toda instancia de esa entidad tiene que aparecer en al menos una ocurrencia de la relación, o si puede quedar sin participar. La participación es <em>total</em> cuando todas las entidades del conjunto participan en al menos una relación del conjunto de relaciones, y es <em>parcial</em> cuando algunas entidades pueden no participar en ninguna, tal como la definen Silberschatz, Korth y Sudarshan. En la notación de Chen, la participación total se dibuja con una línea doble entre la entidad y el rombo, y la parcial con una línea simple.</p>
<p>Entre un instructor y un estudiante existe una relación de asesoría, un <code>advisor</code>, el ejemplo que mejor separa los dos conceptos. La participación del estudiante en esa relación es total, ya que todo estudiante del programa debe tener un instructor asesor asignado, sin excepción. La participación del instructor, en cambio, es parcial, porque un instructor puede no estar asesorando a nadie en un momento dado. Nota que esa asimetría no tiene nada que ver con la cardinalidad, ya que la relación sigue siendo uno a uno de todas formas, cardinalidad y participación son dos preguntas distintas sobre la misma relación, una pregunta por cuántos y la otra por si es obligatorio.</p>
<div class="diagrama">
<svg viewbox="0 0 760 260" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Instructor y estudiante conectados por la relación advisor; el lado estudiante tiene línea doble porque su participación es total, el lado instructor tiene línea simple porque su participación es parcial; abajo la traducción a tabla muestra que estudiante recibe una columna instructor_id NOT NULL mientras que instructor no recibe ninguna columna nueva" font-family="Segoe UI, Inter, system-ui, sans-serif">
<rect x="40" y="30" width="170" height="50" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="125" y="60" font-size="13" font-weight="600" fill="#12324f" text-anchor="middle">Instructor</text> <polygon points="300,55 356,30 412,55 356,80" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <text x="356" y="59" font-size="11" font-weight="600" fill="#0e6f6c" text-anchor="middle">advisor</text> <rect x="500" y="30" width="170" height="50" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="585" y="60" font-size="13" font-weight="600" fill="#12324f" text-anchor="middle">Estudiante</text> <line x1="215" y1="55" x2="295" y2="55" stroke="#8fb3d1" stroke-width="1.6"></line> <line x1="418" y1="52" x2="495" y2="52" stroke="#8fb3d1" stroke-width="1.6"></line> <line x1="418" y1="58" x2="495" y2="58" stroke="#8fb3d1" stroke-width="1.6"></line> <text x="255" y="42" font-size="11" fill="#5b6876" text-anchor="middle">parcial</text> <text x="456" y="42" font-size="11" fill="#0e6f6c" text-anchor="middle">total</text> <rect x="80" y="120" width="270" height="66" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="215" y="140" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">tabla Instructor</text> <text x="215" y="158" font-size="11.5" fill="#5b6876" text-anchor="middle">no recibe ninguna columna nueva</text> <text x="215" y="174" font-size="11.5" fill="#5b6876" text-anchor="middle">de esta relación</text> <rect x="410" y="120" width="270" height="66" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="545" y="140" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">tabla Estudiante</text> <text x="545" y="158" font-size="11.5" fill="#12324f" text-anchor="middle">instructor_id NOT NULL</text> <text x="545" y="174" font-size="11.5" fill="#5b6876" text-anchor="middle">(porque su participación es total)</text> <text x="380" y="222" font-size="11.5" fill="#5b6876" text-anchor="middle">Que instructor sea parcial no genera ninguna columna: la llave foránea solo existe del lado</text> <text x="380" y="238" font-size="11.5" fill="#5b6876" text-anchor="middle">“muchos”, así que garantizar que todo instructor tenga estudiante exige una regla aparte</text>
</svg>
</div>
<p>Esa traducción a tabla es exactamente la regla que vas a formalizar en la Unidad 3, cuando una relación uno a muchos es total del lado muchos, el atributo extra que representa la relación, la llave foránea, se agrega directamente al esquema del lado muchos sin necesitar una tabla propia para la relación. Si la participación del lado muchos fuera parcial, esa misma columna admitiría valores nulos, para las instancias que en ese momento no participan de ninguna relación. Fíjate en el límite real de esta traducción, que la participación del lado uno, la del instructor en este ejemplo, no se refleja en ninguna columna nueva, porque la llave foránea solo vive en la tabla del lado muchos. Garantizar que todo instructor tenga al menos un estudiante asignado no es algo que este esquema relacional simple garantice por sí solo, hace falta una restricción aparte, o una revisión periódica, o una regla de negocio en la aplicación. Es un caso donde la receta de traducir participación a nulidad se queda corta, y conviene saberlo antes de asumir que basta con mirar el diagrama para blindar cualquier regla de negocio.</p>
</section>
<section id="la-notación-de-pata-de-gallo" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="la-notación-de-pata-de-gallo"><span class="header-section-number">5</span> La notación de pata de gallo</h2>
<p>La notación de pata de gallo, en inglés <em>crow’s foot</em>, es la que hoy usan de forma prácticamente universal las herramientas de modelado, porque en vez de separar cardinalidad y participación en dos decisiones distintas, como hace Chen con la flecha y la línea doble, combina las dos en un único par de símbolos junto a cada extremo de la relación. Debe su documentación y estandarización más conocida al método de modelado que Richard Barker publicó en 1990 en el libro <em>CASE*Method: Entity Relationship Modelling</em>, que las herramientas de ingeniería de software asistida por computadora, o CASE (en inglés <em>computer-aided software engineering</em>), adoptaron después como estándar de facto, y que es la razón por la que hoy la reconoces en prácticamente cualquier herramienta de modelado que abras.</p>
<p>Cuatro símbolos, combinados de dos en dos, cubren los mismos cuatro casos que ya viste con Chen. Un círculo junto a la entidad significa cero, el mínimo permitido es que no participe en absoluto. Un trazo corto, una rayita perpendicular a la línea, significa uno, ya sea de mínimo o de máximo. Y la pata de gallo propiamente dicha, tres líneas que se abren en abanico, significa muchos, sin límite superior fijo.</p>
<div class="diagrama">
<svg viewbox="0 0 700 240" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cuatro combinaciones de la notación pata de gallo: círculo y trazo junto a la entidad da cero o uno, trazo y trazo da exactamente uno, círculo y pata de gallo da cero o muchos, trazo y pata de gallo da uno o muchos" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="350" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Círculo = cero, trazo = uno, pata de gallo = muchos</text> <g font-size="12" font-weight="600" fill="#12324f"> <circle cx="60" cy="52" r="7" fill="none" stroke="#8fb3d1" stroke-width="1.8"></circle> <line x1="72" y1="44" x2="72" y2="60" stroke="#8fb3d1" stroke-width="1.8"></line> <text x="100" y="57">0..1 opcional, a lo sumo uno</text> <line x1="52" y1="102" x2="52" y2="118" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="64" y1="102" x2="64" y2="118" stroke="#8fb3d1" stroke-width="1.8"></line> <text x="100" y="115">1..1 obligatorio, exactamente uno</text> <circle cx="55" cy="152" r="7" fill="none" stroke="#8fb3d1" stroke-width="1.8"></circle> <path d="M67,144 L90,152 L67,160 M67,152 L90,152" fill="none" stroke="#8fb3d1" stroke-width="1.6"></path> <text x="100" y="157">0..N opcional, muchos</text> <line x1="46" y1="194" x2="46" y2="210" stroke="#8fb3d1" stroke-width="1.8"></line> <path d="M58,194 L81,202 L58,210 M58,202 L81,202" fill="none" stroke="#8fb3d1" stroke-width="1.6"></path> <text x="100" y="207">1..N obligatorio, muchos</text> </g> <rect x="400" y="30" width="270" height="196" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="535" y="52" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Equivalencia con Chen</text> <g font-size="11" fill="#12324f"><text x="418" y="76">0..1 = línea simple + flecha</text><text x="418" y="98">1..1 = línea doble + flecha</text><text x="418" y="120">0..N = línea simple, sin flecha</text><text x="418" y="142">1..N = línea doble, sin flecha</text></g> <text x="418" y="172" font-size="11.5" fill="#5b6876">El primer número (min) es</text> <text x="418" y="186" font-size="11.5" fill="#5b6876">participación; el segundo (max)</text> <text x="418" y="200" font-size="11.5" fill="#5b6876">es cardinalidad de mapeo.</text>
</svg>
</div>
<p>Esa tabla de equivalencias es la clave para pasar de una notación a la otra sin memorizar dos sistemas distintos, ya que el número mínimo de cada par corresponde exactamente a la participación, un mínimo de uno equivale a la línea doble de Chen y un mínimo de cero a la línea simple, y el número máximo corresponde a la cardinalidad de mapeo, un máximo de uno equivale a la flecha de Chen y un máximo sin límite a la línea sin flecha. Esta misma idea de mínimo y máximo también existe como notación adicional que puede combinarse con Chen, escrita como una etiqueta <code>l..h</code> junto a cada línea (Silberschatz, Korth y Sudarshan), y suele confundir a quien empieza a leer diagramas de otras fuentes. Encontrar <code>0..1</code> o <code>1..*</code> escrito junto a una línea de Chen sin flecha ni doble línea es perfectamente válido, es la misma información que la pata de gallo, expresada con números en vez de con figuras.</p>
</section>
<section id="el-caso-de-estudio-la-cafetería-completa" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="el-caso-de-estudio-la-cafetería-completa"><span class="header-section-number">6</span> El caso de estudio: la cafetería, completa</h2>
<p>Imagina que alguien registró los pedidos de la cafetería en una sola tabla plana, una fila por cada línea de venta, con el pedido, el cliente, su teléfono, el producto y el valor todos mezclados en las mismas columnas.</p>
<div class="tabla-ancha">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Pedido</th>
<th>Cliente</th>
<th>Teléfono</th>
<th>Producto</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1001</td>
<td>Ana Ruiz</td>
<td>300 111 2233</td>
<td>Café</td>
<td>4500</td>
</tr>
<tr class="even">
<td>1002</td>
<td>Ana Ruiz</td>
<td>300 111 2233</td>
<td>Torta</td>
<td>23400</td>
</tr>
<tr class="odd">
<td>1003</td>
<td>Luis Pena</td>
<td>301 444 5566</td>
<td>Café</td>
<td>4500</td>
</tr>
<tr class="even">
<td>1004</td>
<td>Ana Ruiz</td>
<td>300 111 2233</td>
<td>Jugo</td>
<td>6800</td>
</tr>
</tbody>
</table>
</div>
<p>Fíjate en el teléfono de Ana Ruiz, repetido tres veces de forma idéntica en las filas 1001, 1002 y 1004: si Ana cambia de número, alguien tiene que corregirlo en las tres filas a la vez, y si se olvida una, la tabla queda con dos números distintos para la misma persona. Si tuvieras que dibujar esta misma información como un modelo entidad relación, cuántas entidades separarías, y en cuál de ellas dejarías el teléfono, sabiendo que el problema no es el teléfono en sí, sino que la tabla mezcla dos cosas distintas, el pedido y el cliente que lo hizo.</p>
<p>El teléfono nunca debió vivir en la fila del pedido, porque conceptualmente es un dato del cliente, no del pedido, y un cliente puede hacer varios pedidos sin que su teléfono cambie de un pedido a otro. El modelo separa tres entidades, <code>Cliente</code>, con su nombre y su teléfono, <code>Pedido</code>, con su fecha, y <code>Producto</code>, con su nombre y su precio, conectadas por dos relaciones, <code>Realiza</code> entre <code>Cliente</code> y <code>Pedido</code>, y <code>Contiene</code> entre <code>Pedido</code> y <code>Producto</code>.</p>
<p><code>Realiza</code> es uno a muchos, un cliente puede hacer varios pedidos, pero un pedido pertenece a un solo cliente, y en el alcance de este caso, donde todo cliente que aparece en la tabla ya hizo al menos un pedido, la participación es total en los dos lados. <code>Contiene</code> es muchos a muchos, un pedido puede incluir varios productos y un mismo producto aparece en varios pedidos, con un atributo propio de la relación, la cantidad de unidades de ese producto en ese pedido. Aquí la participación es asimétrica, todo pedido tiene que contener al menos un producto, así que <code>Pedido</code> participa de forma total en <code>Contiene</code>, pero el catálogo de productos de la cafetería puede tener un producto nuevo que todavía nadie ha pedido, así que <code>Producto</code> participa de forma parcial.</p>
<div class="diagrama">
<svg viewbox="0 0 760 350" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Diagrama entidad relación completo en notación de Chen: Cliente conectado con línea doble a la relación Realiza y esta con línea doble a Pedido, cardinalidad uno a muchos con flecha hacia Cliente; Pedido conectado con línea doble a la relación Contiene, Contiene conectada con línea simple a Producto, cardinalidad muchos a muchos, con el atributo cantidad colgando de la relación Contiene" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="base22b" markerwidth="9" markerheight="9" refx="7" refy="3" orient="auto"><path d="M0,0 L7,3 L0,6 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">El modelo completo de la cafetería, en notación de Chen</text> <rect x="30" y="120" width="150" height="52" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="105" y="142" font-size="13" font-weight="600" fill="#12324f" text-anchor="middle">Cliente</text> <text x="105" y="160" font-size="11" fill="#5b6876" text-anchor="middle">nombre, teléfono</text> <polygon points="230,146 280,120 330,146 280,172" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <text x="280" y="150" font-size="11" font-weight="600" fill="#0e6f6c" text-anchor="middle">Realiza</text> <rect x="330" y="120" width="150" height="52" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="405" y="142" font-size="13" font-weight="600" fill="#12324f" text-anchor="middle">Pedido</text> <text x="405" y="160" font-size="11" fill="#5b6876" text-anchor="middle">fecha</text> <line x1="184" y1="143" x2="222" y2="143" stroke="#8fb3d1" stroke-width="1.6"></line> <line x1="184" y1="149" x2="222" y2="149" stroke="#8fb3d1" stroke-width="1.6"></line> <path d="M336,143 L296,143" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#base22b)"></path> <line x1="296" y1="149" x2="336" y2="149" stroke="#8fb3d1" stroke-width="1.6"></line> <text x="205" y="182" font-size="11" fill="#0e6f6c" text-anchor="middle">total</text> <text x="355" y="182" font-size="11" fill="#0e6f6c" text-anchor="middle">total, 1 a N</text> <polygon points="230,266 280,240 330,266 280,292" fill="#eef4fa" stroke="#c7d6e6"></polygon> <text x="280" y="270" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">Contiene</text> <ellipse cx="280" cy="330" rx="46" ry="1" fill="none"></ellipse> <rect x="530" y="240" width="150" height="52" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="605" y="262" font-size="13" font-weight="600" fill="#12324f" text-anchor="middle">Producto</text> <text x="605" y="280" font-size="11" fill="#5b6876" text-anchor="middle">nombre, precio</text> <line x1="405" y1="172" x2="405" y2="238" stroke="#8fb3d1" stroke-width="1.6" transform="translate(-4,0)"></line> <line x1="405" y1="172" x2="405" y2="238" stroke="#8fb3d1" stroke-width="1.6" transform="translate(4,0)"></line> <line x1="334" y1="266" x2="524" y2="266" stroke="#8fb3d1" stroke-width="1.6"></line> <text x="465" y="256" font-size="11" fill="#5b6876" text-anchor="middle">parcial, N a M</text> <text x="380" y="222" font-size="11" fill="#0e6f6c" text-anchor="middle">total</text> <ellipse cx="280" cy="318" rx="52" ry="24" fill="#f5f7fa" stroke="#cfd8e3"></ellipse> <text x="280" y="322" font-size="11.5" fill="#12324f" text-anchor="middle">cantidad</text> <line x1="280" y1="294" x2="280" y2="296" stroke="#8fb3d1" stroke-width="1.6"></line>
</svg>
</div>
<p>Con este diagrama, la redundancia de la tabla plana desaparece por diseño, no por disciplina. El teléfono vive una sola vez, como atributo de <code>Cliente</code>, así que cuando Ana cambie de número, se corrige un solo registro, y sus tres pedidos anteriores siguen apuntando al mismo cliente sin que el teléfono tenga que repetirse ni una sola vez.</p>
</section>
<section id="el-mismo-modelo-en-pata-de-gallo" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="el-mismo-modelo-en-pata-de-gallo"><span class="header-section-number">7</span> El mismo modelo en pata de gallo</h2>
<p>Trasladar el diagrama anterior a la notación de pata de gallo cambia la forma de los símbolos, pero no cambia ni una sola decisión de diseño, sigue siendo un cliente con muchos pedidos y una relación muchos a muchos entre pedido y producto. La diferencia visible es que la mayoría de herramientas que usan pata de gallo, a diferencia de Chen, ya dibujan la relación muchos a muchos resuelta como una entidad propia, la que en la Unidad 3 vas a construir como tabla, en vez de dejarla como un rombo abstracto todavía sin resolver.</p>
<div class="diagrama">
<svg viewbox="0 0 760 260" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="El mismo modelo de la cafetería en notación pata de gallo: Cliente con trazo doble hacia sí mismo y pata de gallo hacia Pedido para representar uno obligatorio a muchos; Pedido conectado a una entidad asociativa Detalle_Pedido con trazo y pata de gallo en ambos extremos; Detalle_Pedido conectado a Producto con círculo y pata de gallo del lado Detalle_Pedido, porque un producto puede aparecer en ninguna o en varias filas de detalle, y con trazo doble del lado Producto, porque cada fila de detalle exige exactamente un producto" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">El mismo modelo, en notación pata de gallo</text> <rect x="20" y="80" width="150" height="52" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="95" y="102" font-size="13" font-weight="600" fill="#12324f" text-anchor="middle">Cliente</text> <text x="95" y="120" font-size="11" fill="#5b6876" text-anchor="middle">nombre, teléfono</text> <rect x="300" y="80" width="150" height="52" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="375" y="102" font-size="13" font-weight="600" fill="#12324f" text-anchor="middle">Pedido</text> <text x="375" y="120" font-size="11" fill="#5b6876" text-anchor="middle">fecha</text> <line x1="176" y1="106" x2="180" y2="106" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="183" y1="98" x2="183" y2="114" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="192" y1="98" x2="192" y2="114" stroke="#8fb3d1" stroke-width="1.8"></line> <path d="M280,106 L292,98 M280,106 L292,114 M280,106 L296,106" fill="none" stroke="#8fb3d1" stroke-width="1.6"></path> <text x="235" y="88" font-size="11" fill="#5b6876" text-anchor="middle">1 obligatorio</text> <text x="260" y="128" font-size="11" fill="#5b6876" text-anchor="middle">muchos</text> <rect x="300" y="180" width="150" height="52" rx="6" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="375" y="202" font-size="12" font-weight="600" fill="#12324f" text-anchor="middle">Detalle_Pedido</text> <text x="375" y="220" font-size="11" fill="#5b6876" text-anchor="middle">cantidad</text> <line x1="375" y1="134" x2="375" y2="140" stroke="#8fb3d1" stroke-width="1.8"></line> <path d="M375,150 L367,158 M375,150 L383,158 M375,150 L375,164" fill="none" stroke="#8fb3d1" stroke-width="1.6"></path> <text x="398" y="150" font-size="11" fill="#5b6876">1 obligatorio a muchos</text> <rect x="580" y="180" width="150" height="52" rx="6" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="655" y="202" font-size="13" font-weight="600" fill="#12324f" text-anchor="middle">Producto</text> <text x="655" y="220" font-size="11" fill="#5b6876" text-anchor="middle">nombre, precio</text> <circle cx="466" cy="206" r="6" fill="none" stroke="#8fb3d1" stroke-width="1.6"></circle> <path d="M478,206 L500,198 M478,206 L500,214 M478,206 L504,206" fill="none" stroke="#8fb3d1" stroke-width="1.6"></path> <path d="M450,206 L458,206" fill="none" stroke="#8fb3d1" stroke-width="1.6"></path> <line x1="576" y1="199" x2="576" y2="213" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="560" y1="199" x2="560" y2="213" stroke="#8fb3d1" stroke-width="1.8"></line> <text x="520" y="240" font-size="11" fill="#5b6876" text-anchor="middle">0 opcional a muchos (Detalle_Pedido); 1 obligatorio, exactamente uno (Producto)</text>
</svg>
</div>
</section>
<section id="traducir-el-diagrama-a-tablas" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="traducir-el-diagrama-a-tablas"><span class="header-section-number">8</span> Traducir el diagrama a tablas</h2>
<p>La Unidad 3 va a formalizar el procedimiento completo, pero con este modelo ya puedes anticipar cómo quedan las tablas, porque cada decisión de cardinalidad y de participación que acabas de dibujar tiene una consecuencia directa en el esquema.</p>
<div class="diagrama">
<svg viewbox="0 0 760 280" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cuatro tablas del esquema final: Cliente sin llaves foráneas, Pedido con cliente_id NOT NULL apuntando a Cliente, Producto sin llaves foráneas, y Detalle_Pedido con pedido_id y producto_id NOT NULL formando la clave primaria compuesta y apuntando a Pedido y a Producto" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="base22c" markerwidth="9" markerheight="9" refx="7" refy="3" orient="auto"><path d="M0,0 L7,3 L0,6 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">De la cardinalidad y la participación a las llaves foráneas</text> <rect x="20" y="40" width="180" height="66" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="110" y="60" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Cliente</text> <text x="110" y="78" font-size="11.5" fill="#5b6876" text-anchor="middle">id_cliente (PK)</text> <text x="110" y="94" font-size="11.5" fill="#5b6876" text-anchor="middle">nombre, teléfono</text> <rect x="290" y="40" width="190" height="66" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="385" y="60" font-size="12.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Pedido</text> <text x="385" y="78" font-size="11.5" fill="#3c7d7a" text-anchor="middle">id_pedido (PK), fecha</text> <text x="385" y="94" font-size="11.5" fill="#3c7d7a" text-anchor="middle">cliente_id NOT NULL (FK)</text> <path d="M290,73 L200,73" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#base22c)"></path> <rect x="580" y="40" width="160" height="66" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="660" y="60" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Producto</text> <text x="660" y="78" font-size="11.5" fill="#5b6876" text-anchor="middle">id_producto (PK)</text> <text x="660" y="94" font-size="11.5" fill="#5b6876" text-anchor="middle">nombre, precio</text> <rect x="240" y="180" width="290" height="80" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="385" y="200" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">Detalle_Pedido</text> <text x="385" y="218" font-size="11.5" fill="#5b6876" text-anchor="middle">pedido_id NOT NULL, producto_id NOT NULL</text> <text x="385" y="234" font-size="11.5" fill="#5b6876" text-anchor="middle">cantidad NOT NULL</text> <text x="385" y="250" font-size="11" fill="#0e6f6c" text-anchor="middle">clave primaria compuesta</text> <path d="M385,178 L385,110" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#base22c)"></path> <path d="M530,205 C600,205 650,140 660,108" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#base22c)"></path>
</svg>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> Cliente (</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    id_cliente  <span class="dt">INT</span> <span class="kw">PRIMARY</span> <span class="kw">KEY</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    nombre      <span class="dt">VARCHAR</span>(<span class="dv">80</span>) <span class="kw">NOT</span> <span class="kw">NULL</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    telefono    <span class="dt">VARCHAR</span>(<span class="dv">20</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>);</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> Pedido (</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    id_pedido   <span class="dt">INT</span> <span class="kw">PRIMARY</span> <span class="kw">KEY</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    fecha       <span class="dt">DATE</span> <span class="kw">NOT</span> <span class="kw">NULL</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    cliente_id  <span class="dt">INT</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">REFERENCES</span> Cliente(id_cliente)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>);</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> Producto (</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    id_producto <span class="dt">INT</span> <span class="kw">PRIMARY</span> <span class="kw">KEY</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    nombre      <span class="dt">VARCHAR</span>(<span class="dv">80</span>) <span class="kw">NOT</span> <span class="kw">NULL</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    precio      <span class="dt">DECIMAL</span>(<span class="dv">10</span>,<span class="dv">2</span>) <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>);</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> Detalle_Pedido (</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    pedido_id   <span class="dt">INT</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">REFERENCES</span> Pedido(id_pedido),</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    producto_id <span class="dt">INT</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">REFERENCES</span> Producto(id_producto),</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    cantidad    <span class="dt">INT</span> <span class="kw">NOT</span> <span class="kw">NULL</span>,</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="kw">PRIMARY</span> <span class="kw">KEY</span> (pedido_id, producto_id)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>);</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Fíjate en el detalle que ya adelantó la sección anterior, la participación parcial de <code>Producto</code> en <code>Contiene</code> no produjo ninguna columna que admita nulos en ninguna tabla, porque las relaciones muchos a muchos nunca ponen una llave foránea directamente en las tablas originales, la ponen en su propia tabla intermedia. Un producto que todavía nadie ha pedido simplemente no tiene ninguna fila en <code>Detalle_Pedido</code>, sin que haga falta ningún valor nulo en ningún lado para representar esa ausencia. Esa es una diferencia real entre cómo la participación parcial se traduce en una relación uno a muchos, con una columna que admite nulos, y cómo se traduce en una relación muchos a muchos, sin ninguna columna nula, solo con menos filas en la tabla intermedia.</p>
</section>
<section id="dos-errores-frecuentes-al-pasar-del-dibujo-a-la-tabla" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="dos-errores-frecuentes-al-pasar-del-dibujo-a-la-tabla"><span class="header-section-number">9</span> Dos errores frecuentes al pasar del dibujo a la tabla</h2>
<p>Dos errores comunes al construir un diagrama entidad relación (Silberschatz, Korth y Sudarshan) aparecen una y otra vez en trabajos de estudiantes que recién empiezan.</p>
<p>El primero es confundir un atributo con una entidad, o al revés. El teléfono de este mismo caso es un buen ejemplo de los dos lados del error, guardarlo como atributo de <code>Pedido</code> en vez de <code>Cliente</code> fue el error de la tabla plana con la que abrió este caso, pero convertirlo en una entidad propia también sería un error, en este caso por exceso, porque cada cliente de la cafetería tiene un solo teléfono y ninguna metadata adicional sobre él. La señal correcta para preferir una entidad sobre un atributo aparece cuando el negocio necesita guardar varios valores del mismo tipo por instancia, o información adicional sobre cada uno de esos valores, por ejemplo si la cafetería quisiera guardar el celular y el fijo de cada cliente, con una etiqueta que diga cuál es cuál. Mientras eso no ocurra, el atributo simple <code>telefono</code> dentro de <code>Cliente</code> es la representación correcta, ni de más ni de menos.</p>
<p>El segundo error, que igualmente conviene evitar, es intentar resolver una relación muchos a muchos poniendo una llave foránea en cada una de las dos tablas originales, en vez de crear la tabla intermedia. Es imposible expresar correctamente una relación muchos a muchos así, porque una columna <code>producto_id</code> dentro de <code>Pedido</code> solo puede guardar un valor a la vez, y un pedido con varios productos necesitaría varias columnas o varias filas repetidas del pedido, la misma anomalía de redundancia de la tabla plana con la que abrió este caso, solo que aplicada ahora al producto en vez de al teléfono.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Cardinalidad y participación a ojo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para cada situación, marca la cardinalidad que corresponde antes de seguir leyendo.</p>
<p><label><input type="checkbox"> Un país tiene una sola capital, y una ciudad es capital de un solo país</label><br> <label><input type="checkbox"> Un curso de este programa lo dicta un solo docente por semestre, pero un docente dicta varios cursos</label><br> <label><input type="checkbox"> Un estudiante se matricula en varias asignaturas, y cada asignatura tiene varios estudiantes matriculados</label></p>
<p>Escribe junto a cada situación si es uno a uno, uno a muchos o muchos a muchos, y para la segunda situación indica además de qué lado pondrías la flecha si la dibujaras en notación de Chen.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La primera situación es uno a uno, porque cada país tiene exactamente una capital y cada ciudad capital pertenece a exactamente un país, así que la flecha en notación de Chen iría en los dos extremos de la relación.</p>
<p>La segunda situación es uno a muchos. Un docente dicta varios cursos, pero cada curso, en un semestre dado, lo dicta un solo docente, así que la flecha va del lado del rombo hacia <code>Docente</code>, porque cada curso se asocia como máximo con un docente, y la línea sin flecha va hacia <code>Curso</code>, porque un docente se asocia con varios.</p>
<p>La tercera situación es muchos a muchos, porque un estudiante toma varias asignaturas a la vez y una misma asignatura reúne a varios estudiantes matriculados, así que ninguno de los dos extremos lleva flecha, y en la traducción a tablas de la Unidad 3 esta relación va a necesitar su propia tabla intermedia, del mismo tipo que <code>Detalle_Pedido</code> en el caso de la cafetería.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Encuentra el error de este diseño
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un compañero de curso propone esta forma de guardar los pedidos de la cafetería, sin tabla intermedia:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode sql code-with-copy"><code class="sourceCode sql"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">CREATE</span> <span class="kw">TABLE</span> Pedido (</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    id_pedido    <span class="dt">INT</span> <span class="kw">PRIMARY</span> <span class="kw">KEY</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    cliente_id   <span class="dt">INT</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">REFERENCES</span> Cliente(id_cliente),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    producto_id  <span class="dt">INT</span> <span class="kw">NOT</span> <span class="kw">NULL</span> <span class="kw">REFERENCES</span> Producto(id_producto),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    cantidad     <span class="dt">INT</span> <span class="kw">NOT</span> <span class="kw">NULL</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>);</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>Antes de leer la solución, responde en un párrafo corto, qué pasa si el pedido 1002 de Ana incluyó a la vez una torta y un jugo, con esta estructura de tabla, y qué anomalía de la tabla plana original de este tema vuelve a aparecer aquí, solo que en otro campo.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Con esta tabla, un pedido que incluye dos productos distintos no cabe en una sola fila, porque la columna <code>producto_id</code> solo admite un valor. La única forma de registrar que el pedido 1002 llevó torta y jugo es repetir la fila completa del pedido 1002 dos veces, una por cada producto, con el mismo <code>id_pedido</code>, el mismo <code>cliente_id</code> y la misma fecha implícita, cambiando solo <code>producto_id</code> y <code>cantidad</code>. Es la misma anomalía de redundancia que el teléfono de Ana en la tabla plana con la que abrió este caso, solo que ahora el dato que se repite y se puede desincronizar no es el teléfono, es el propio pedido.</p>
<p>La corrección es la tabla <code>Detalle_Pedido</code> que ya viste en este tema, con clave primaria compuesta por <code>pedido_id</code> y <code>producto_id</code>, que separa la relación muchos a muchos en su propia tabla en vez de forzarla dentro de <code>Pedido</code>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. El programa de fidelización
</div>
</div>
<div class="callout-body-container callout-body">
<p>Imagina que la cafetería lanza una tarjeta de fidelidad, y ahora se puede registrar como cliente a alguien que todavía no ha hecho ningún pedido, con solo su nombre y su teléfono, porque quiere empezar a acumular puntos antes de su primera compra.</p>
<p>Responde en un párrafo, qué cambia en la participación de <code>Cliente</code> en la relación <code>Realiza</code> con esta nueva regla de negocio, y si ese cambio obliga a modificar la columna <code>cliente_id</code> de la tabla <code>Pedido</code> que ya construiste en este tema.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La participación de <code>Cliente</code> en <code>Realiza</code> deja de ser total y pasa a ser parcial, porque ahora puede existir un cliente registrado por la tarjeta de fidelidad que todavía no aparece en ninguna fila de <code>Pedido</code>. En la notación de Chen, la línea entre <code>Cliente</code> y el rombo <code>Realiza</code> pasaría de doble a simple, y en pata de gallo el extremo de <code>Cliente</code> pasaría de trazo a círculo.</p>
<p>Ese cambio no obliga a modificar la columna <code>cliente_id</code> de <code>Pedido</code> para nada, porque esa columna representa la participación de <code>Pedido</code> en la relación, que sigue siendo total, todo pedido sigue necesitando un cliente. La participación de <code>Cliente</code> no se refleja en ninguna columna de <code>Pedido</code> ni de <code>Cliente</code>, exactamente el mismo límite de la traducción que ya viste con el ejemplo de instructor y estudiante, la participación del lado uno de una relación uno a muchos no aparece como ninguna columna nueva en ningún esquema.</p>
</div>
</div>
</div>
</section>
<section id="lo-que-te-llevas-de-hoy" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="lo-que-te-llevas-de-hoy"><span class="header-section-number">10</span> Lo que te llevas de hoy</h2>
<div class="checklist">
<p>Al salir de este tema deberías poder explicar, sin mirar la guía, los siguientes puntos:</p>
<ul class="task-list">
<li><label><input type="checkbox">Los símbolos de la notación de Chen, rectángulo, óvalo, rombo, y sus variantes de borde doble para entidad débil y relación identificadora</label></li>
<li><label><input type="checkbox">La diferencia entre cardinalidad de mapeo, uno a uno, uno a muchos y muchos a muchos, y participación, total o parcial, sobre la misma relación</label></li>
<li><label><input type="checkbox">Cómo leer la flecha y la línea doble de Chen, y su equivalente en la pata de gallo, círculo, trazo y pata de gallo</label></li>
<li><label><input type="checkbox">Por qué la flecha de cardinalidad apunta hacia el mismo lado donde después va la llave foránea</label></li>
<li><label><input type="checkbox">Por qué una relación uno a muchos total en el lado muchos produce una columna NOT NULL, y por qué la participación del lado uno no se refleja en ninguna columna</label></li>
<li><label><input type="checkbox">Por qué una relación muchos a muchos siempre necesita una tabla propia, y por qué su participación parcial no genera columnas nulas</label></li>
<li><label><input type="checkbox">Cómo el modelo entidad relación completo de la cafetería elimina, por diseño, la anomalía del teléfono repetido de la tabla plana original</label></li>
</ul>
</div>
</section>
<section id="cierre-de-la-unidad-2" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="cierre-de-la-unidad-2"><span class="header-section-number">11</span> Cierre de la Unidad 2</h2>
<p>Con este tema se cierra la Unidad 2. Empezaste nombrando las piezas sueltas del modelo entidad relación, entidades, atributos, relaciones y claves, y terminaste dibujándolas con una notación estándar, marcando cuántas instancias se asocian entre sí y si esa asociación es obligatoria. La cafetería, que abrió este tema como una tabla plana con un problema de redundancia, ahora es un diagrama completo con tres entidades, dos relaciones y una tabla intermedia, listo para el siguiente paso.</p>
<p>La Unidad 3 toma exactamente este diagrama y lo convierte en el vocabulario formal del modelo relacional, cada entidad con su llave primaria, cada relación resuelta con llaves foráneas o con una tabla propia, tal como ya empezaste a anticipar en este tema. Después vienen las formas de normalización, primera, segunda, tercera y cuarta, que son el procedimiento con reglas explícitas para confirmar que un diseño como el de hoy de verdad eliminó la redundancia, y no solo la escondió mejor.</p>
</section>
<section id="recursos" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="recursos"><span class="header-section-number">12</span> Recursos</h2>
<ul>
<li>Silberschatz, A., Korth, H. F. y Sudarshan, S. <em>Database System Concepts</em> (7.a ed.). Capítulo 6, “Database Design Using the E-R Model”. Material de apoyo oficial de los autores en <a href="https://www.db-book.com">db-book.com</a>, diapositivas del capítulo consultadas en <a href="https://www.db-book.com/slides-dir/PDF-dir/ch6.pdf">db-book.com/slides-dir/PDF-dir/ch6.pdf</a>.</li>
<li>Chen, P. P. (1976). <em>The Entity-Relationship Model, Toward a Unified View of Data.</em> ACM Transactions on Database Systems, 1(1), 9 a 36. DOI: <a href="https://doi.org/10.1145/320434.320440">10.1145/320434.320440</a>.</li>
<li>Barker, R. (1990). <em>CASE*Method: Entity Relationship Modelling.</em> Addison-Wesley. Fuente donde se documentó y estandarizó la notación de pata de gallo tal como la usan hoy las herramientas CASE.</li>
<li>Elmasri, R. y Navathe, S. B. <em>Fundamentals of Database Systems.</em> Capítulo sobre modelado entidad relación, notación gráfica y cardinalidad.</li>
<li>Connolly, T. M. y Begg, C. E. <em>Database Systems: A Practical Approach to Design, Implementation, and Management.</em> Capítulo sobre el modelo entidad relación y sus restricciones de cardinalidad y participación.</li>
<li>Thalheim, B. (2000). <em>Entity-Relationship Modeling: Foundations of Database Technology.</em> Springer. Tratamiento formal de cardinalidad y restricciones de participación, para quien quiera profundizar más allá del nivel de pregrado.</li>
</ul>
<div class="pie-doc">
<p>Base de datos (DBA03). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>