<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 4. Nomenclatura y certificación – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-95bfa606010d176c52cfb6b551730f65.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-04/index.html">Unidad 4. Validación y verificación</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html">Tema 4. Nomenclatura y certificación</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Calidad del software y estándares de calidad</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-01-que-es-calidad-quien-la-define/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es la calidad y quién la define</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Calidad de proceso y de producto: ISO/IEC 25010:2023</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Importancia, costo y calidad en un mundo globalizado</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Procesos de calidad del software. Modelos y métricas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-01-sqa-relacion-ingenieria/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es el SQA y su relación con la ingeniería de software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La calidad en cada fase del ciclo de vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-03-roles-habilidades/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Roles, responsabilidades y habilidades del personal de SQA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-04-actividades-sqa/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Actividades del SQA: revisiones, auditorías y gestión de configuración</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-05-modelos-metricas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Modelos y métricas de calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-06-herramientas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 6. Herramientas de SQA en la industria</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 3. Estándares de calidad aplicados al software</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Estándares IEEE para la calidad del software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Marcos para evaluar la usabilidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Madurez de procesos: SPICE y CMMI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 4. Validación y verificación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Métodos, metodologías y estándares de verificación y validación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Validación y verificación de requisitos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-03-control-costo-calidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Control de la calidad y costo de la calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 4. Nomenclatura y certificación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-05-factores-atam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Factores que determinan la calidad y el método ATAM</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#objetivo-y-resultado-de-aprendizaje" id="toc-objetivo-y-resultado-de-aprendizaje" class="nav-link active" data-scroll-target="#objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</a></li>
  <li><a href="#ruta-de-estudio" id="toc-ruta-de-estudio" class="nav-link" data-scroll-target="#ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</a></li>
  <li><a href="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" id="toc-el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="nav-link" data-scroll-target="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</a></li>
  <li><a href="#parte-1.-nomenclatura-el-vocabulario-y-el-nombre-de-las-normas" id="toc-parte-1.-nomenclatura-el-vocabulario-y-el-nombre-de-las-normas" class="nav-link" data-scroll-target="#parte-1.-nomenclatura-el-vocabulario-y-el-nombre-de-las-normas"><span class="header-section-number">4</span> Parte 1. Nomenclatura: el vocabulario y el nombre de las normas</a>
  <ul class="collapse">
  <li><a href="#por-qué-hace-falta-un-vocabulario-común" id="toc-por-qué-hace-falta-un-vocabulario-común" class="nav-link" data-scroll-target="#por-qué-hace-falta-un-vocabulario-común">Por qué hace falta un vocabulario común</a></li>
  <li><a href="#el-vocabulario-de-la-ingeniería-de-software-isoiecieee-24765" id="toc-el-vocabulario-de-la-ingeniería-de-software-isoiecieee-24765" class="nav-link" data-scroll-target="#el-vocabulario-de-la-ingeniería-de-software-isoiecieee-24765">El vocabulario de la ingeniería de software: ISO/IEC/IEEE 24765</a></li>
  <li><a href="#anatomía-del-nombre-de-una-norma" id="toc-anatomía-del-nombre-de-una-norma" class="nav-link" data-scroll-target="#anatomía-del-nombre-de-una-norma">Anatomía del nombre de una norma</a></li>
  <li><a href="#nombres-nacionales-las-ntc" id="toc-nombres-nacionales-las-ntc" class="nav-link" data-scroll-target="#nombres-nacionales-las-ntc">Nombres nacionales: las NTC</a></li>
  <li><a href="#ejemplo-resuelto-descomponer-cinco-nombres-reales" id="toc-ejemplo-resuelto-descomponer-cinco-nombres-reales" class="nav-link" data-scroll-target="#ejemplo-resuelto-descomponer-cinco-nombres-reales">Ejemplo resuelto: descomponer cinco nombres reales</a></li>
  </ul></li>
  <li><a href="#parte-2.-el-ciclo-de-vida-de-una-norma-y-cómo-saber-si-está-vigente" id="toc-parte-2.-el-ciclo-de-vida-de-una-norma-y-cómo-saber-si-está-vigente" class="nav-link" data-scroll-target="#parte-2.-el-ciclo-de-vida-de-una-norma-y-cómo-saber-si-está-vigente"><span class="header-section-number">5</span> Parte 2. El ciclo de vida de una norma y cómo saber si está vigente</a>
  <ul class="collapse">
  <li><a href="#las-etapas" id="toc-las-etapas" class="nav-link" data-scroll-target="#las-etapas">Las etapas</a></li>
  <li><a href="#ejemplo-resuelto-la-vida-de-la-iso-90012015" id="toc-ejemplo-resuelto-la-vida-de-la-iso-90012015" class="nav-link" data-scroll-target="#ejemplo-resuelto-la-vida-de-la-iso-90012015">Ejemplo resuelto: la vida de la ISO 9001:2015</a></li>
  <li><a href="#un-estado-de-iso-no-es-lo-mismo-que-la-validez-de-un-certificado" id="toc-un-estado-de-iso-no-es-lo-mismo-que-la-validez-de-un-certificado" class="nav-link" data-scroll-target="#un-estado-de-iso-no-es-lo-mismo-que-la-validez-de-un-certificado">Un estado de ISO no es lo mismo que la validez de un certificado</a></li>
  <li><a href="#ejemplo-resuelto-el-certificado-de-la-clínica-aurora" id="toc-ejemplo-resuelto-el-certificado-de-la-clínica-aurora" class="nav-link" data-scroll-target="#ejemplo-resuelto-el-certificado-de-la-clínica-aurora">Ejemplo resuelto: el certificado de la Clínica Aurora</a></li>
  <li><a href="#cómo-comprobar-si-una-norma-está-vigente" id="toc-cómo-comprobar-si-una-norma-está-vigente" class="nav-link" data-scroll-target="#cómo-comprobar-si-una-norma-está-vigente">Cómo comprobar si una norma está vigente</a></li>
  <li><a href="#ejemplo-resuelto-calcular-el-cierre-de-una-votación" id="toc-ejemplo-resuelto-calcular-el-cierre-de-una-votación" class="nav-link" data-scroll-target="#ejemplo-resuelto-calcular-el-cierre-de-una-votación">Ejemplo resuelto: calcular el cierre de una votación</a></li>
  </ul></li>
  <li><a href="#parte-3.-qué-es-certificar" id="toc-parte-3.-qué-es-certificar" class="nav-link" data-scroll-target="#parte-3.-qué-es-certificar"><span class="header-section-number">6</span> Parte 3. Qué es certificar</a>
  <ul class="collapse">
  <li><a href="#definiciones-de-iso" id="toc-definiciones-de-iso" class="nav-link" data-scroll-target="#definiciones-de-iso">Definiciones de ISO</a></li>
  <li><a href="#tres-objetos-que-se-pueden-certificar" id="toc-tres-objetos-que-se-pueden-certificar" class="nav-link" data-scroll-target="#tres-objetos-que-se-pueden-certificar">Tres objetos que se pueden certificar</a></li>
  <li><a href="#caso-de-análisis-la-propuesta-comercial-de-la-clínica-aurora" id="toc-caso-de-análisis-la-propuesta-comercial-de-la-clínica-aurora" class="nav-link" data-scroll-target="#caso-de-análisis-la-propuesta-comercial-de-la-clínica-aurora">Caso de análisis: la propuesta comercial de la Clínica Aurora</a></li>
  </ul></li>
  <li><a href="#parte-4.-certificar-un-sistema-de-gestión" id="toc-parte-4.-certificar-un-sistema-de-gestión" class="nav-link" data-scroll-target="#parte-4.-certificar-un-sistema-de-gestión"><span class="header-section-number">7</span> Parte 4. Certificar un sistema de gestión</a>
  <ul class="collapse">
  <li><a href="#iso-9001-qué-es-y-qué-certifica" id="toc-iso-9001-qué-es-y-qué-certifica" class="nav-link" data-scroll-target="#iso-9001-qué-es-y-qué-certifica">ISO 9001: qué es y qué certifica</a></li>
  <li><a href="#normas-de-gestión-de-otros-sectores" id="toc-normas-de-gestión-de-otros-sectores" class="nav-link" data-scroll-target="#normas-de-gestión-de-otros-sectores">Normas de gestión de otros sectores</a></li>
  <li><a href="#la-apreciación-cmmi-no-es-un-certificado-de-iso" id="toc-la-apreciación-cmmi-no-es-un-certificado-de-iso" class="nav-link" data-scroll-target="#la-apreciación-cmmi-no-es-un-certificado-de-iso">La apreciación CMMI no es un certificado de ISO</a></li>
  <li><a href="#ejemplo-resuelto-leer-el-certificado-de-la-clínica-aurora" id="toc-ejemplo-resuelto-leer-el-certificado-de-la-clínica-aurora" class="nav-link" data-scroll-target="#ejemplo-resuelto-leer-el-certificado-de-la-clínica-aurora">Ejemplo resuelto: leer el certificado de la Clínica Aurora</a></li>
  </ul></li>
  <li><a href="#parte-5.-certificar-un-producto" id="toc-parte-5.-certificar-un-producto" class="nav-link" data-scroll-target="#parte-5.-certificar-un-producto"><span class="header-section-number">8</span> Parte 5. Certificar un producto</a>
  <ul class="collapse">
  <li><a href="#common-criteria-e-isoiec-15408" id="toc-common-criteria-e-isoiec-15408" class="nav-link" data-scroll-target="#common-criteria-e-isoiec-15408">Common Criteria e ISO/IEC 15408</a></li>
  <li><a href="#qué-edición-está-vigente" id="toc-qué-edición-está-vigente" class="nav-link" data-scroll-target="#qué-edición-está-vigente">Qué edición está vigente</a></li>
  <li><a href="#el-reconocimiento-entre-países-ccra" id="toc-el-reconocimiento-entre-países-ccra" class="nav-link" data-scroll-target="#el-reconocimiento-entre-países-ccra">El reconocimiento entre países: CCRA</a></li>
  <li><a href="#el-esquema-europeo-eucc" id="toc-el-esquema-europeo-eucc" class="nav-link" data-scroll-target="#el-esquema-europeo-eucc">El esquema europeo EUCC</a></li>
  <li><a href="#una-certificación-es-una-fotografía" id="toc-una-certificación-es-una-fotografía" class="nav-link" data-scroll-target="#una-certificación-es-una-fotografía">Una certificación es una fotografía</a></li>
  <li><a href="#dónde-falla-la-certificación-de-producto-el-caso-de-la-homologación-de-emisiones" id="toc-dónde-falla-la-certificación-de-producto-el-caso-de-la-homologación-de-emisiones" class="nav-link" data-scroll-target="#dónde-falla-la-certificación-de-producto-el-caso-de-la-homologación-de-emisiones">Dónde falla la certificación de producto: el caso de la homologación de emisiones</a></li>
  </ul></li>
  <li><a href="#parte-6.-certificar-personas" id="toc-parte-6.-certificar-personas" class="nav-link" data-scroll-target="#parte-6.-certificar-personas"><span class="header-section-number">9</span> Parte 6. Certificar personas</a>
  <ul class="collapse">
  <li><a href="#isoiec-17024" id="toc-isoiec-17024" class="nav-link" data-scroll-target="#isoiec-17024">ISO/IEC 17024</a></li>
  <li><a href="#el-esquema-istqb" id="toc-el-esquema-istqb" class="nav-link" data-scroll-target="#el-esquema-istqb">El esquema ISTQB</a></li>
  <li><a href="#otros-ejemplos-de-certificación-de-personas" id="toc-otros-ejemplos-de-certificación-de-personas" class="nav-link" data-scroll-target="#otros-ejemplos-de-certificación-de-personas">Otros ejemplos de certificación de personas</a></li>
  <li><a href="#qué-dice-una-certificación-de-personas" id="toc-qué-dice-una-certificación-de-personas" class="nav-link" data-scroll-target="#qué-dice-una-certificación-de-personas">Qué dice una certificación de personas</a></li>
  </ul></li>
  <li><a href="#parte-7.-la-auditoría-de-certificación-de-un-sistema-de-gestión" id="toc-parte-7.-la-auditoría-de-certificación-de-un-sistema-de-gestión" class="nav-link" data-scroll-target="#parte-7.-la-auditoría-de-certificación-de-un-sistema-de-gestión"><span class="header-section-number">10</span> Parte 7. La auditoría de certificación de un sistema de gestión</a>
  <ul class="collapse">
  <li><a href="#las-etapas-1" id="toc-las-etapas-1" class="nav-link" data-scroll-target="#las-etapas-1">Las etapas</a></li>
  <li><a href="#qué-se-muestrea-y-qué-no" id="toc-qué-se-muestrea-y-qué-no" class="nav-link" data-scroll-target="#qué-se-muestrea-y-qué-no">Qué se muestrea y qué no</a></li>
  <li><a href="#ejemplo-resuelto-clasificar-un-hallazgo" id="toc-ejemplo-resuelto-clasificar-un-hallazgo" class="nav-link" data-scroll-target="#ejemplo-resuelto-clasificar-un-hallazgo">Ejemplo resuelto: clasificar un hallazgo</a></li>
  </ul></li>
  <li><a href="#parte-8.-acreditación-organismos-y-reconocimiento-internacional" id="toc-parte-8.-acreditación-organismos-y-reconocimiento-internacional" class="nav-link" data-scroll-target="#parte-8.-acreditación-organismos-y-reconocimiento-internacional"><span class="header-section-number">11</span> Parte 8. Acreditación, organismos y reconocimiento internacional</a>
  <ul class="collapse">
  <li><a href="#la-cadena-de-confianza" id="toc-la-cadena-de-confianza" class="nav-link" data-scroll-target="#la-cadena-de-confianza">La cadena de confianza</a></li>
  <li><a href="#colombia-icontec-y-onac" id="toc-colombia-icontec-y-onac" class="nav-link" data-scroll-target="#colombia-icontec-y-onac">Colombia: ICONTEC y ONAC</a></li>
  <li><a href="#reconocimiento-internacional" id="toc-reconocimiento-internacional" class="nav-link" data-scroll-target="#reconocimiento-internacional">Reconocimiento internacional</a></li>
  <li><a href="#cómo-verificar-un-certificado" id="toc-cómo-verificar-un-certificado" class="nav-link" data-scroll-target="#cómo-verificar-un-certificado">Cómo verificar un certificado</a></li>
  </ul></li>
  <li><a href="#parte-9.-caso-volkswagen-certificaciones-vigentes-y-un-fraude-de-emisiones" id="toc-parte-9.-caso-volkswagen-certificaciones-vigentes-y-un-fraude-de-emisiones" class="nav-link" data-scroll-target="#parte-9.-caso-volkswagen-certificaciones-vigentes-y-un-fraude-de-emisiones"><span class="header-section-number">12</span> Parte 9. Caso Volkswagen: certificaciones vigentes y un fraude de emisiones</a>
  <ul class="collapse">
  <li><a href="#los-hechos" id="toc-los-hechos" class="nav-link" data-scroll-target="#los-hechos">Los hechos</a></li>
  <li><a href="#qué-certificaciones-tenía-el-grupo" id="toc-qué-certificaciones-tenía-el-grupo" class="nav-link" data-scroll-target="#qué-certificaciones-tenía-el-grupo">Qué certificaciones tenía el grupo</a></li>
  <li><a href="#análisis" id="toc-análisis" class="nav-link" data-scroll-target="#análisis">Análisis</a></li>
  </ul></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes"><span class="header-section-number">13</span> Errores frecuentes</a></li>
  <li><a href="#autoevaluación" id="toc-autoevaluación" class="nav-link" data-scroll-target="#autoevaluación"><span class="header-section-number">14</span> Autoevaluación</a></li>
  <li><a href="#lo-que-te-llevas" id="toc-lo-que-te-llevas" class="nav-link" data-scroll-target="#lo-que-te-llevas"><span class="header-section-number">15</span> Lo que te llevas</a></li>
  <li><a href="#fuentes-y-límites-de-la-verificación" id="toc-fuentes-y-límites-de-la-verificación" class="nav-link" data-scroll-target="#fuentes-y-límites-de-la-verificación"><span class="header-section-number">16</span> Fuentes y límites de la verificación</a></li>
  <li><a href="#glosario" id="toc-glosario" class="nav-link" data-scroll-target="#glosario"><span class="header-section-number">17</span> Glosario</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">18</span> Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-04/index.html">Unidad 4. Validación y verificación</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html">Tema 4. Nomenclatura y certificación</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 4. Nomenclatura y certificación</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">3 de octubre de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 89%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 4. Validación y verificación</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 4. Nomenclatura y certificación</td>
</tr>
</tbody>
</table>
</div>
<p><a href="../presentacion-interactiva.html" class="btn-curso">Presentación interactiva de la unidad</a></p>
<p>Tema anterior: <a href="../../../calidad-del-software/unidad-04/tema-03-control-costo-calidad/index.html">Tema 3. Control y costo de la calidad</a>. Tema siguiente: <a href="../../../calidad-del-software/unidad-04/tema-05-factores-atam/index.html">Tema 5. Factores de calidad y el método ATAM</a>.</p>
<section id="objetivo-y-resultado-de-aprendizaje" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</h2>
<p>Los temas anteriores de la unidad mostraron cómo un equipo verifica y valida su propio trabajo y cuánto cuesta hacerlo bien. Este tema trata de lo que viene después, que es demostrarle a un tercero (un cliente, un regulador, un empleador) que ese trabajo se hizo, y hacerlo con un idioma que ambas partes entiendan. Ese idioma tiene dos piezas: la nomenclatura, que es cómo se nombran y se numeran las normas, y la certificación, que es la evidencia emitida por un tercero independiente.</p>
<p>Al terminar puedes:</p>
<ul>
<li>Leer el nombre completo de una norma (organismo, número, parte, año, enmienda) y explicar qué dice cada elemento.</li>
<li>Usar el vocabulario normalizado de la ingeniería de software (ISO/IEC/IEEE 24765) para fijar el sentido de un término.</li>
<li>Describir el ciclo de vida de una norma y comprobar, con la ficha del catálogo de ISO, si una edición está vigente.</li>
<li>Distinguir certificación de producto, de sistema de gestión (proceso) y de personas, y decir qué garantiza y qué no garantiza cada una.</li>
<li>Describir las etapas de una auditoría de certificación y el papel de la acreditación.</li>
<li>Explicar quién es quién en Colombia (ICONTEC, ONAC) y cómo se reconoce un certificado entre países.</li>
<li>Verificar la validez de un certificado y analizar el caso Volkswagen con fuentes oficiales.</li>
</ul>
<p>Prerrequisitos: haber visto la ISO 9001 en el <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html">Tema 2 de la Unidad 3</a> y la idea de verificación y validación del <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html">Tema 1 de esta unidad</a>. Aquí solo se retoma lo necesario de ellos.</p>
</section>
<section id="ruta-de-estudio" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</h2>
<p>Son unas 6 horas de trabajo independiente, que se pueden partir en tres sesiones. La presentación interactiva de la unidad sigue los mismos conceptos, así que sirve como repaso. Todas las actividades son individuales.</p>
<div class="calendario">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parte</th>
<th>Qué haces</th>
<th>Tiempo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Nomenclatura: nombres y vocabulario</td>
<td>Lees el vocabulario normalizado, descompones nombres de normas y resuelves el Reto 1</td>
<td>35 min</td>
</tr>
<tr class="even">
<td>2. Ciclo de vida de una norma</td>
<td>Sigues los códigos de etapa, calculas fechas y resuelves el Reto 2</td>
<td>35 min</td>
</tr>
<tr class="odd">
<td>3. Qué es certificar</td>
<td>Distingues certificación, acreditación y los tres objetos certificables</td>
<td>40 min</td>
</tr>
<tr class="even">
<td>4. Certificar un sistema de gestión</td>
<td>Lees un certificado de ISO 9001 y la apreciación CMMI, y resuelves el Reto 3</td>
<td>45 min</td>
</tr>
<tr class="odd">
<td>5. Certificar un producto</td>
<td>Estudias Common Criteria y EUCC, y resuelves el Reto 4</td>
<td>45 min</td>
</tr>
<tr class="even">
<td>6. Certificar personas</td>
<td>Lees ISO/IEC 17024 y el esquema ISTQB, y resuelves el Reto 5</td>
<td>30 min</td>
</tr>
<tr class="odd">
<td>7. La auditoría de certificación</td>
<td>Recorres las etapas del ciclo de tres años</td>
<td>30 min</td>
</tr>
<tr class="even">
<td>8. Acreditación y reconocimiento</td>
<td>Sigues la cadena ICONTEC, ONAC y organismos internacionales</td>
<td>35 min</td>
</tr>
<tr class="odd">
<td>9. Caso Volkswagen</td>
<td>Analizas hechos oficiales y resuelves el Reto 6</td>
<td>45 min</td>
</tr>
<tr class="even">
<td>Cierre</td>
<td>Errores frecuentes, autoevaluación, glosario</td>
<td>40 min</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</h2>
<p>El producto del curso es una app que asigna turnos médicos. En este tema la Clínica Aurora quiere venderla a un hospital, el Hospital San Rafael (ficticio como todo el hilo conductor). El pliego del hospital pide tres cosas: un sistema de gestión de la calidad certificado en ISO 9001, personal de pruebas con certificación reconocida y evidencia de seguridad del producto. Esas tres peticiones corresponden a los tres objetos que se pueden certificar, y cada una exige un tipo de evidencia distinto.</p>
<p>Los datos propios de la clínica (fechas, cantidades, alcance de su certificado) son ilustrativos. Los datos de normas, organismos y casos reales fueron consultados en fuentes primarias el 3 de octubre de 2026 y se citan en la bibliografía. Cuando una fuente de pago no se pudo leer, o un sitio bloqueó la consulta, el texto lo dice de forma explícita.</p>
</section>
<section id="parte-1.-nomenclatura-el-vocabulario-y-el-nombre-de-las-normas" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="parte-1.-nomenclatura-el-vocabulario-y-el-nombre-de-las-normas"><span class="header-section-number">4</span> Parte 1. Nomenclatura: el vocabulario y el nombre de las normas</h2>
<section id="por-qué-hace-falta-un-vocabulario-común" class="level3">
<h3 class="anchored" data-anchor-id="por-qué-hace-falta-un-vocabulario-común">Por qué hace falta un vocabulario común</h3>
<p>Dos personas pueden usar la misma palabra y entender cosas distintas. “Verificación”, “validación”, “certificación” y “acreditación” son ejemplos frecuentes. En un contrato, una diferencia de significado se convierte en una discusión sobre qué se prometió. Por eso la ingeniería de software dispone de un vocabulario normalizado.</p>
</section>
<section id="el-vocabulario-de-la-ingeniería-de-software-isoiecieee-24765" class="level3">
<h3 class="anchored" data-anchor-id="el-vocabulario-de-la-ingeniería-de-software-isoiecieee-24765">El vocabulario de la ingeniería de software: ISO/IEC/IEEE 24765</h3>
<p>La norma ISO/IEC/IEEE 24765, titulada <em>Systems and software engineering, Vocabulary</em>, reúne y normaliza la terminología de todo el trabajo de ingeniería de sistemas y de software. Su edición vigente es la segunda, de septiembre de 2017, con 522 páginas, y la prepara el comité conjunto ISO/IEC JTC 1/SC 7. Reemplazó a la edición de 2010. La ficha de ISO registra que fue revisada y confirmada en 2026, de modo que sigue vigente.</p>
<p>El vocabulario no inventa definiciones. Según su resumen en ISO, incluye referencias a las normas fuente de cada definición, para que quien lo consulte pueda profundizar en el concepto en la norma de origen. Esa trazabilidad es la que permite resolver una disputa de términos, porque la definición que manda en un contrato es la de la norma que el contrato dice cumplir.</p>
<p>Existen otros vocabularios especializados que conviene saber ubicar:</p>
<ul>
<li><strong>ISO 9000.</strong> Fundamentos y vocabulario de los sistemas de gestión de la calidad. La edición vigente es la ISO 9000:2026 (quinta edición, publicada en mayo de 2026), que reemplazó a la de 2015.</li>
<li><strong>ISO/IEC 17000.</strong> Vocabulario y principios generales de la evaluación de la conformidad, es decir, de términos como certificación, acreditación e inspección. La edición de 2020 reemplazó a la de 2004.</li>
</ul>
</section>
<section id="anatomía-del-nombre-de-una-norma" class="level3">
<h3 class="anchored" data-anchor-id="anatomía-del-nombre-de-una-norma">Anatomía del nombre de una norma</h3>
<p>El nombre de una norma no es un código arbitrario. Cada parte dice algo, y leerlo bien evita citar una edición equivocada. El diagrama descompone dos nombres reales del catálogo de ISO.</p>
<div class="diagrama">
<svg viewbox="0 0 760 270" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Anatomia de dos nombres de norma. El primero, ISO/IEC 15408-1:2026, se divide en organismos que publican, numero de la norma, parte y año de la edicion. El segundo, ISO 9001:2015/Amd 1:2024, se divide en organismo, numero, edicion base y enmienda numero uno del año 2024" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t4a" markerwidth="9" markerheight="9" refx="7" refy="2.8" orient="auto"><path d="M0,0 L7,2.8 L0,5.6 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Cómo se lee el nombre de una norma</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="30" y="36" width="150" height="46" rx="8"></rect><rect x="200" y="36" width="150" height="46" rx="8"></rect><rect x="370" y="36" width="120" height="46" rx="8"></rect></g> <rect x="510" y="36" width="220" height="46" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g font-size="16" font-weight="700" fill="#12324f" text-anchor="middle"><text x="105" y="66">ISO/IEC</text><text x="275" y="66">15408</text><text x="430" y="66">-1</text></g> <text x="620" y="66" font-size="16" font-weight="700" fill="#0e6f6c" text-anchor="middle">:2026</text> <g font-size="11.5" fill="#5b6876" text-anchor="middle"><text x="105" y="102">Quién la publica</text><text x="275" y="102">Número de la norma</text><text x="430" y="102">Parte de la serie</text><text x="620" y="102">Año de la edición</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.4" marker-end="url(#u4t4a)"><path d="M105,84 L105,90"></path><path d="M275,84 L275,90"></path><path d="M430,84 L430,90"></path><path d="M620,84 L620,90"></path></g> <line x1="30" y1="130" x2="730" y2="130" stroke="#cfd8e3" stroke-dasharray="4 4"></line> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="30" y="152" width="110" height="46" rx="8"></rect><rect x="160" y="152" width="130" height="46" rx="8"></rect><rect x="310" y="152" width="130" height="46" rx="8"></rect></g> <rect x="460" y="152" width="270" height="46" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g font-size="16" font-weight="700" fill="#12324f" text-anchor="middle"><text x="85" y="182">ISO</text><text x="225" y="182">9001</text><text x="375" y="182">:2015</text></g> <text x="595" y="182" font-size="16" font-weight="700" fill="#0e6f6c" text-anchor="middle">/Amd 1:2024</text> <g font-size="11.5" fill="#5b6876" text-anchor="middle"><text x="85" y="218">Organismo</text><text x="225" y="218">Número</text><text x="375" y="218">Edición base</text><text x="595" y="218">Enmienda 1, publicada en 2024</text></g> <text x="380" y="256" font-size="11.5" fill="#5b6876" text-anchor="middle">Dos normas con el mismo número y distinto año son ediciones distintas</text>
</svg>
</div>
<p>Los elementos más comunes son estos.</p>
<ul>
<li><strong>Prefijo de organismos.</strong> ISO, IEC (Comisión Electrotécnica Internacional) o IEEE, solos o combinados. ISO/IEC indica una norma de comités conjuntos. ISO/IEC/IEEE indica que además participó el IEEE, como en la ISO/IEC/IEEE 24765.</li>
<li><strong>Número.</strong> Identifica la norma dentro de su catálogo. No cambia entre ediciones.</li>
<li><strong>Parte.</strong> Una norma grande se divide en partes que se publican y se revisan por separado. La ISO/IEC 15408, por ejemplo, tiene cinco partes (15408-1 a 15408-5).</li>
<li><strong>Año tras los dos puntos.</strong> Identifica la edición. Un certificado o un contrato que cite solo “ISO 9001” es ambiguo, porque no dice a cuál edición se refiere.</li>
<li><strong>Enmienda y corrigendo.</strong> <code>/Amd 1:2024</code> es una enmienda: añade contenido que no está en el texto original. Un corrigendo (<code>/Cor 1:2009</code>) corrige errores. Ambos se citan junto a la norma base.</li>
<li><strong>Tipo de documento.</strong> Además de la norma internacional existen la especificación técnica (TS), el informe técnico (TR), la especificación disponible al público (PAS), el acuerdo de taller (IWA) y las guías (Guide). ISO publica los tipos en su sección de entregables.</li>
<li><strong>Borradores.</strong> DIS (borrador de norma internacional) y FDIS (borrador final) llevan esas siglas mientras la norma no se publica, como en “ISO/IEC FDIS 17065”.</li>
</ul>
<p>Dos precisiones sobre tipos de documento, tomadas de la página de entregables de ISO. Una PAS tiene una vida máxima de seis años, tras la cual se convierte en norma internacional o se retira. Un IWA se revisa a los tres años de su publicación.</p>
<p>En el caso del IEEE, sus normas propias se designan con la forma <code>IEEE Std 1012-2016</code>, con guion antes del año. Esa convención no pudo confirmarse en la página del IEEE durante la consulta, porque el sitio bloqueó el acceso, así que conviene comprobarla en el documento cuando se cite.</p>
</section>
<section id="nombres-nacionales-las-ntc" class="level3">
<h3 class="anchored" data-anchor-id="nombres-nacionales-las-ntc">Nombres nacionales: las NTC</h3>
<p>Los países adoptan las normas internacionales con un nombre propio. En Colombia las publica ICONTEC, el organismo nacional de normalización, como Normas Técnicas Colombianas (NTC). ONAC, por ejemplo, lista entre sus esquemas de acreditación la NTC ISO/IEC 17024. Una NTC adoptada de una norma ISO conserva el número y el año de la norma de origen. Quien cite una norma en un documento colombiano debe decir si cita la NTC o la norma internacional, porque pueden tener ediciones distintas en un momento dado.</p>
</section>
<section id="ejemplo-resuelto-descomponer-cinco-nombres-reales" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-descomponer-cinco-nombres-reales">Ejemplo resuelto: descomponer cinco nombres reales</h3>
<div class="tabla-ancha">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Nombre</th>
<th>Organismo</th>
<th>Número y parte</th>
<th>Edición</th>
<th>Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ISO/IEC/IEEE 24765:2017</td>
<td>ISO, IEC e IEEE</td>
<td>24765</td>
<td>2017</td>
<td>Vocabulario de ingeniería de sistemas y de software. Segunda edición</td>
</tr>
<tr class="even">
<td>ISO/IEC 15408-1:2026</td>
<td>ISO e IEC</td>
<td>15408, parte 1</td>
<td>2026</td>
<td>Introducción y modelo general de los criterios de evaluación de seguridad TI</td>
</tr>
<tr class="odd">
<td>ISO 9001:2015/Amd 1:2024</td>
<td>ISO</td>
<td>9001</td>
<td>2015 más enmienda 1 de 2024</td>
<td>Requisitos del sistema de gestión de la calidad, con la enmienda de acción climática</td>
</tr>
<tr class="even">
<td>ISO/IEC/IEEE 90003:2018</td>
<td>ISO, IEC e IEEE</td>
<td>90003</td>
<td>2018</td>
<td>Guía para aplicar la ISO 9001:2015 al software</td>
</tr>
<tr class="odd">
<td>NTC ISO/IEC 17024</td>
<td>ICONTEC (adopción)</td>
<td>17024</td>
<td>la que cite la NTC</td>
<td>Adopción colombiana de la norma sobre certificación de personas</td>
</tr>
</tbody>
</table>
</div>
<p>La ficha de ISO titula la ISO/IEC/IEEE 90003:2018 como guía para la aplicación de la ISO 9001:2015 al software, y su resumen dice que ofrece orientación para adquirir, suministrar, desarrollar, operar y mantener software. Como guía, orienta y no fija requisitos certificables. La ISO 9001 sí se puede certificar, como se ve en la Parte 4.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Lee el nombre completo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Marca las afirmaciones correctas sobre la norma <code>ISO 9001:2015/Amd 1:2024</code>.</p>
<p><label><input type="checkbox"> Se refiere a la edición 2015 de la ISO 9001, con una enmienda publicada en 2024</label><br> <label><input type="checkbox"> Es una edición nueva y completa de la ISO 9001, que reemplaza a la de 2015</label><br> <label><input type="checkbox"> El número 9001 identifica la norma, y no cambia cuando aparece una edición nueva</label><br> <label><input type="checkbox"> Una organización certificada en ISO 9001 queda cubierta por este nombre sin necesidad de decir la edición</label></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Son correctas la primera y la tercera. La enmienda añade contenido a la edición 2015 sin sustituirla, y el número 9001 se conserva de edición en edición.</p>
<p>La segunda es falsa, porque una edición nueva y completa se nombra con un año nuevo (como ISO 9001:2026) y no con “/Amd”. La cuarta es falsa, porque un certificado debe indicar la edición contra la que se evaluó, y citar solo “ISO 9001” no lo hace.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-2.-el-ciclo-de-vida-de-una-norma-y-cómo-saber-si-está-vigente" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="parte-2.-el-ciclo-de-vida-de-una-norma-y-cómo-saber-si-está-vigente"><span class="header-section-number">5</span> Parte 2. El ciclo de vida de una norma y cómo saber si está vigente</h2>
<section id="las-etapas" class="level3">
<h3 class="anchored" data-anchor-id="las-etapas">Las etapas</h3>
<p>Una norma internacional de ISO atraviesa etapas identificadas con códigos numéricos de dos cifras, más un subcódigo de dos cifras. Estos códigos, publicados por ISO como códigos armonizados de etapa, son la manera exacta de decir en qué punto está un documento. Cuando alguien lee la ficha de una norma en el catálogo, esos códigos aparecen con sus fechas.</p>
<div class="diagrama">
<svg viewbox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Ciclo de vida de una norma ISO. Las etapas son 00 preliminar, 10 propuesta, 20 preparatoria, 30 comite, 40 consulta con borrador DIS, 50 aprobacion con borrador FDIS y 60 publicacion. Despues viene la etapa 90 de revision sistematica cada cinco años, que termina en tres resultados posibles, 90.93 confirmada, 90.92 por revisar con una edicion nueva, o 95.99 retirada" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t4b" markerwidth="9" markerheight="9" refx="7" refy="2.8" orient="auto"><path d="M0,0 L7,2.8 L0,5.6 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Ciclo de vida de una norma de ISO</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="10" y="36" width="96" height="58" rx="8"></rect><rect x="118" y="36" width="96" height="58" rx="8"></rect><rect x="226" y="36" width="96" height="58" rx="8"></rect><rect x="334" y="36" width="96" height="58" rx="8"></rect><rect x="442" y="36" width="96" height="58" rx="8"></rect><rect x="550" y="36" width="96" height="58" rx="8"></rect></g> <rect x="658" y="36" width="92" height="58" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g text-anchor="middle" font-size="13" font-weight="700" fill="#12324f"><text x="58" y="58">00</text><text x="166" y="58">10</text><text x="274" y="58">20</text><text x="382" y="58">30</text><text x="490" y="58">40</text><text x="598" y="58">50</text></g> <text x="704" y="58" font-size="13" font-weight="700" fill="#0e6f6c" text-anchor="middle">60</text> <g text-anchor="middle" font-size="10.6" fill="#5b6876"><text x="58" y="76">Preliminar</text><text x="166" y="76">Propuesta</text><text x="274" y="76">Preparatoria</text><text x="382" y="76">Comité (CD)</text><text x="490" y="76">Consulta (DIS)</text><text x="598" y="76">Aprobación (FDIS)</text></g> <text x="704" y="76" font-size="10.6" fill="#3c7d7a" text-anchor="middle">Publicación</text> <g fill="none" stroke="#8fb3d1" stroke-width="1.5" marker-end="url(#u4t4b)"><path d="M106,65 L116,65"></path><path d="M214,65 L224,65"></path><path d="M322,65 L332,65"></path><path d="M430,65 L440,65"></path><path d="M538,65 L548,65"></path><path d="M646,65 L656,65"></path></g> <rect x="250" y="150" width="260" height="56" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="380" y="173" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">90 Revisión sistemática</text> <text x="380" y="192" font-size="10.8" fill="#5b6876" text-anchor="middle">cada 5 años se decide qué hacer</text> <path d="M704,94 C704,130 560,140 512,164" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#u4t4b)"></path> <g fill="#e4f2f1" stroke="#8fc9c5"><rect x="40" y="238" width="190" height="48" rx="8"></rect></g> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="285" y="238" width="190" height="48" rx="8"></rect><rect x="530" y="238" width="190" height="48" rx="8"></rect></g> <g text-anchor="middle"><text x="135" y="258" font-size="12" font-weight="700" fill="#0e6f6c">90.93 Confirmada</text><text x="135" y="276" font-size="10.4" fill="#3c7d7a">sigue vigente 5 años más</text><text x="380" y="258" font-size="12" font-weight="700" fill="#12324f">90.92 Por revisar</text><text x="380" y="276" font-size="10.4" fill="#5b6876">se prepara una edición nueva</text><text x="625" y="258" font-size="12" font-weight="700" fill="#12324f">95.99 Retirada</text><text x="625" y="276" font-size="10.4" fill="#5b6876">la edición deja de ser vigente</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#u4t4b)"><path d="M300,206 C250,222 200,230 160,236"></path><path d="M380,206 L380,236"></path><path d="M460,206 C510,222 560,230 600,236"></path></g>
</svg>
</div>
<p>Los códigos principales, tomados de la tabla de códigos armonizados de etapa de ISO, son los siguientes.</p>
<div class="calendario">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Código</th>
<th>Significado</th>
<th>Qué pasa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10.99</td>
<td>Nuevo proyecto aprobado</td>
<td>El comité acepta que la norma hace falta</td>
</tr>
<tr class="even">
<td>30.00</td>
<td>Borrador de comité (CD) registrado</td>
<td>Comienza el trabajo técnico de redacción</td>
</tr>
<tr class="odd">
<td>40.20</td>
<td>Votación del DIS iniciada, 12 semanas</td>
<td>Los países miembros votan el borrador</td>
</tr>
<tr class="even">
<td>50.20</td>
<td>Votación del FDIS iniciada, 8 semanas</td>
<td>Voto final sobre el texto definitivo</td>
</tr>
<tr class="odd">
<td>60.60</td>
<td>Norma internacional publicada</td>
<td>Nace la edición</td>
</tr>
<tr class="even">
<td>90.20</td>
<td>En revisión sistemática</td>
<td>Se evalúa si la norma sigue sirviendo</td>
</tr>
<tr class="odd">
<td>90.93</td>
<td>Norma confirmada</td>
<td>Se conserva sin cambios</td>
</tr>
<tr class="even">
<td>90.92</td>
<td>Norma por revisar</td>
<td>Se abre el trabajo de una edición nueva</td>
</tr>
<tr class="odd">
<td>95.99</td>
<td>Retiro de la norma</td>
<td>La edición se retira del catálogo vigente</td>
</tr>
</tbody>
</table>
</div>
<p>La ficha de cada norma en el catálogo dice además que una norma se revisa cada cinco años. Esa revisión es la que explica por qué hay normas con ediciones de 2012 o de 2015 que aún están vigentes (porque las confirmaron) y otras que se renovaron.</p>
</section>
<section id="ejemplo-resuelto-la-vida-de-la-iso-90012015" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-la-vida-de-la-iso-90012015">Ejemplo resuelto: la vida de la ISO 9001:2015</h3>
<p>Según su ficha en el catálogo de ISO, la ISO 9001:2015 (quinta edición) recorrió estas fechas.</p>
<ol type="1">
<li>Proyecto nuevo aprobado el 5 de octubre de 2012 (código 10.99).</li>
<li>Norma publicada el 22 de septiembre de 2015 (código 60.60).</li>
<li>Revisión sistemática cerrada con confirmación el 20 de mayo de 2021 (código 90.93).</li>
<li>Decisión de revisarla el 16 de noviembre de 2023 (código 90.92), el mismo día en que se aprobó el proyecto de la sexta edición.</li>
<li>Retirada el 16 de septiembre de 2026 (código 95.99), el día en que se publicó la ISO 9001:2026.</li>
</ol>
<p>Entre la decisión de revisar (16 de noviembre de 2023) y la publicación de la edición nueva (16 de septiembre de 2026) pasaron 34 meses, es decir, 2 años y 10 meses. La edición 2015 estuvo en circulación desde el 22 de septiembre de 2015 hasta el 16 de septiembre de 2026, casi once años.</p>
</section>
<section id="un-estado-de-iso-no-es-lo-mismo-que-la-validez-de-un-certificado" class="level3">
<h3 class="anchored" data-anchor-id="un-estado-de-iso-no-es-lo-mismo-que-la-validez-de-un-certificado">Un estado de ISO no es lo mismo que la validez de un certificado</h3>
<p>La ficha de la ISO 9001:2015 muestra hoy el estado “retirada”. Esa palabra se refiere al documento normativo, no a los certificados ya emitidos. En su página sobre la ISO 9001:2026, ISO explica que las organizaciones certificadas deben pasar a la edición nueva dentro del plazo que fije su ciclo de certificación, y recomienda consultar con el organismo de certificación los detalles de la transición.</p>
<p>Organismos de certificación citados en la consulta (como DNV y DQS) informan una transición de tres años, con certificados de 2015 válidos hasta el 30 de septiembre de 2029, sujeta a la confirmación final del organismo internacional de acreditación. Esa fecha no pudo verificarse en un documento primario del organismo de acreditación, así que debe confirmarse con el organismo de certificación antes de citarla en un documento formal.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Cómo leer una fecha de transición
</div>
</div>
<div class="callout-body-container callout-body">
<p>La vigencia de un certificado depende de tres cosas que pertenecen a actores distintos: ISO decide qué edición de la norma es la vigente, el organismo de acreditación y el foro internacional fijan las reglas de transición, y el organismo de certificación aplica esas reglas a cada cliente. Ninguna de las tres sustituye a las otras.</p>
</div>
</div>
</section>
<section id="ejemplo-resuelto-el-certificado-de-la-clínica-aurora" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-el-certificado-de-la-clínica-aurora">Ejemplo resuelto: el certificado de la Clínica Aurora</h3>
<p>Datos ilustrativos. La Clínica Aurora tiene un certificado ISO 9001:2015, emitido el 15 de marzo de 2024 y con vencimiento el 14 de marzo de 2027. Hoy es el 3 de octubre de 2026. El hospital pregunta si el certificado está vigente.</p>
<ol type="1">
<li>El certificado no ha vencido. Del 3 de octubre de 2026 al 14 de marzo de 2027 hay 162 días, que salen de sumar 28 días de octubre, 30 de noviembre, 31 de diciembre, 31 de enero, 28 de febrero y 14 de marzo.</li>
<li>La edición en la que se emitió ya no es la vigente en el catálogo de ISO, pues se retiró el 16 de septiembre de 2026.</li>
<li>La respuesta correcta es que el certificado sigue vigente mientras el organismo de certificación lo mantenga, y que la clínica debe planificar con ese organismo la auditoría de transición a la edición 2026 antes de que termine el plazo de transición.</li>
<li>El hospital hace bien en pedir el certificado, la edición, el alcance y la fecha de la próxima auditoría, y no solo la frase “tenemos ISO 9001”.</li>
</ol>
</section>
<section id="cómo-comprobar-si-una-norma-está-vigente" class="level3">
<h3 class="anchored" data-anchor-id="cómo-comprobar-si-una-norma-está-vigente">Cómo comprobar si una norma está vigente</h3>
<p>La ficha de una norma en el catálogo de ISO trae todo lo necesario. Estos son los pasos.</p>
<ol type="1">
<li>Buscar la norma por su número en el catálogo de ISO y abrir su ficha.</li>
<li>Leer el estado (publicada o retirada), la edición y el código de etapa.</li>
<li>Buscar la nota “Revised by” o “New version available”, que apunta a la edición que la reemplazó.</li>
<li>Leer la línea “last reviewed and confirmed in” que indica el último año de confirmación.</li>
<li>Mirar si existen enmiendas o corrigendos que modifican la edición base.</li>
<li>Para una norma colombiana, repetir la consulta en ICONTEC, que puede tener otra edición adoptada.</li>
</ol>
<p>La tabla muestra el estado de varias normas de este curso en la fecha de consulta (3 de octubre de 2026), tomado de las fichas de ISO.</p>
<div class="tabla-ancha">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Norma</th>
<th>Estado en el catálogo de ISO</th>
<th>Observación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ISO/IEC/IEEE 24765:2017</td>
<td>Publicada, edición 2, confirmada</td>
<td>Vocabulario de ingeniería de software</td>
</tr>
<tr class="even">
<td>ISO/IEC/IEEE 90003:2018</td>
<td>Publicada, edición 1, confirmada en 2025</td>
<td>Su título la liga a la ISO 9001:2015</td>
</tr>
<tr class="odd">
<td>ISO/IEC 25010:2023</td>
<td>Publicada, edición 2</td>
<td>Modelo de calidad del producto (Tema 2 de la Unidad 1)</td>
</tr>
<tr class="even">
<td>ISO 9001:2026</td>
<td>Publicada el 16 de septiembre de 2026, sexta edición</td>
<td>Reemplaza a la ISO 9001:2015, retirada</td>
</tr>
<tr class="odd">
<td>ISO 9000:2026</td>
<td>Publicada en mayo de 2026, quinta edición</td>
<td>Reemplaza a la ISO 9000:2015</td>
</tr>
<tr class="even">
<td>ISO 14001:2026</td>
<td>Publicada en abril de 2026, cuarta edición</td>
<td>La ISO 14001:2015 se retiró el 15 de abril de 2026</td>
</tr>
<tr class="odd">
<td>ISO 19011:2026</td>
<td>Publicada en mayo de 2026, cuarta edición</td>
<td>Directrices de auditoría de sistemas de gestión</td>
</tr>
<tr class="even">
<td>ISO/IEC 15408-1:2026</td>
<td>Publicada en mayo de 2026, quinta edición</td>
<td>La edición 2022 se retiró el 19 de mayo de 2026</td>
</tr>
<tr class="odd">
<td>ISO/IEC 17024:2026</td>
<td>Publicada en marzo de 2026, tercera edición</td>
<td>La edición 2012 se retiró el 31 de marzo de 2026</td>
</tr>
<tr class="even">
<td>ISO/IEC 17021-1:2015</td>
<td>Publicada, en revisión (código 90.60)</td>
<td>Requisitos de organismos que certifican sistemas de gestión</td>
</tr>
<tr class="odd">
<td>ISO/IEC 17065:2012</td>
<td>Publicada, marcada por revisar</td>
<td>La ficha indica que un FDIS la reemplazaría en los próximos meses</td>
</tr>
<tr class="even">
<td>ISO/IEC 17011:2017</td>
<td>Publicada, confirmada en 2023</td>
<td>Requisitos de los organismos de acreditación</td>
</tr>
</tbody>
</table>
</div>
<p>Un detalle que conviene destacar. La ISO/IEC/IEEE 90003:2018 sigue vigente, pero su título se refiere a la ISO 9001:2015, que ya fue reemplazada. Si ISO la revisará para alinearla con la edición 2026 no pudo verificarse en el catálogo, por lo que queda como un pendiente para quien la use.</p>
</section>
<section id="ejemplo-resuelto-calcular-el-cierre-de-una-votación" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-calcular-el-cierre-de-una-votación">Ejemplo resuelto: calcular el cierre de una votación</h3>
<p>Los códigos de etapa traen fechas, y con las duraciones se pueden calcular las siguientes. Sea una norma ficticia cuyo borrador DIS inició su votación el 1 de abril de 2025 (código 40.20). La votación del DIS dura 12 semanas, es decir 84 días. Abril tiene 30 días, así que el 1 de abril más 29 días llega al 30 de abril, y quedan 55 días: 31 de mayo consume 31 y quedan 24, que caen el 24 de junio. La votación cierra el 24 de junio de 2025 (código 40.60).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Lee el expediente de una norma
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una norma ficticia tiene este historial. Responde sin consultar la tabla de códigos y luego compara.</p>
<ul>
<li>40.20 el 1 de abril de 2025</li>
<li>40.60 el 24 de junio de 2025</li>
<li>40.99 el 15 de septiembre de 2025</li>
<li>50.20 el 6 de octubre de 2025</li>
</ul>
<ol type="1">
<li>¿En qué etapa está al 6 de octubre de 2025 y cuántas semanas dura esa votación?</li>
<li>¿En qué fecha cierra esa votación?</li>
<li>¿Ya existe la norma publicada?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Está en la etapa 50, aprobación. El código 50.20 significa que inició la votación del FDIS, que dura 8 semanas.</li>
<li>Ocho semanas son 56 días. Del 6 de octubre al 31 de octubre hay 25 días, y quedan 31 días de noviembre que se consumen 30, de modo que sobra 1 día, el 1 de diciembre. La votación cierra el 1 de diciembre de 2025 (código 50.60).</li>
<li>Todavía no. La norma queda publicada cuando aparece el código 60.60, que viene después del cierre de la votación y de la preparación del texto final.</li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="parte-3.-qué-es-certificar" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="parte-3.-qué-es-certificar"><span class="header-section-number">6</span> Parte 3. Qué es certificar</h2>
<section id="definiciones-de-iso" class="level3">
<h3 class="anchored" data-anchor-id="definiciones-de-iso">Definiciones de ISO</h3>
<p>ISO define la certificación como el aseguramiento escrito (el certificado) que entrega un organismo independiente de que un producto, proceso, servicio o sistema cumple requisitos específicos. Es lo que también se llama evaluación de la conformidad de tercera parte. ISO no emite certificados ni presta servicios de evaluación de la conformidad, y recomienda contactar a un organismo de certificación externo.</p>
<p>La acreditación es otra cosa. ISO la define como el reconocimiento formal, por parte de un organismo independiente (el organismo de acreditación), de que un organismo de certificación opera conforme a normas internacionales. La acreditación no es obligatoria, y que un certificador no esté acreditado no significa que carezca de reputación, pero la acreditación entrega una confirmación independiente de su competencia.</p>
</section>
<section id="tres-objetos-que-se-pueden-certificar" class="level3">
<h3 class="anchored" data-anchor-id="tres-objetos-que-se-pueden-certificar">Tres objetos que se pueden certificar</h3>
<p>Una frase como “mi software está certificado” puede significar tres cosas distintas, según lo que haya pasado por la evaluación del tercero. El comité de evaluación de la conformidad de ISO (CASCO) publica una norma de requisitos para cada tipo de organismo certificador.</p>
<div class="diagrama">
<svg viewbox="0 0 760 280" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Tres objetos que se pueden certificar. Producto o servicio con la norma ISO IEC 17065 para el organismo certificador y el ejemplo Common Criteria. Sistema de gestion con la norma ISO IEC 17021 guion 1 y los ejemplos ISO 9001 e ISO 14001. Personas con la norma ISO IEC 17024 y el ejemplo del esquema ISTQB" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t4c" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Qué se evalúa en cada tipo de certificación</text> <rect x="285" y="32" width="190" height="46" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="60" font-size="13" font-weight="700" fill="#0e6f6c" text-anchor="middle">Certificación</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="10" y="130" width="235" height="140" rx="10"></rect><rect x="262" y="130" width="235" height="140" rx="10"></rect><rect x="515" y="130" width="235" height="140" rx="10"></rect></g> <g text-anchor="middle" font-size="13" font-weight="700" fill="#12324f"><text x="127" y="156">Producto o servicio</text><text x="380" y="156">Sistema de gestión</text><text x="632" y="156">Personas</text></g> <g text-anchor="middle" font-size="10.8" fill="#5b6876"><text x="127" y="178">Evalúa el objeto concreto</text><text x="380" y="178">Evalúa cómo trabaja la organización</text><text x="632" y="178">Evalúa la competencia individual</text></g> <g text-anchor="middle" font-size="10.8" fill="#12324f" font-weight="600"><text x="127" y="206">Norma del certificador</text><text x="127" y="222">ISO/IEC 17065</text><text x="380" y="206">Norma del certificador</text><text x="380" y="222">ISO/IEC 17021-1</text><text x="632" y="206">Norma del certificador</text><text x="632" y="222">ISO/IEC 17024</text></g> <g text-anchor="middle" font-size="10.4" fill="#3c7d7a"><text x="127" y="248">Ej.: Common Criteria</text><text x="380" y="248">Ej.: ISO 9001, ISO 14001</text><text x="632" y="248">Ej.: esquema ISTQB</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u4t4c)"><path d="M340,78 C290,100 190,112 140,128"></path><path d="M380,78 L380,128"></path><path d="M420,78 C470,100 570,112 620,128"></path></g>
</svg>
</div>
<div class="tabla-ancha">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Objeto</th>
<th>Qué evalúa</th>
<th>Norma del organismo certificador</th>
<th>Qué dice</th>
<th>Qué no dice</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Producto o servicio</td>
<td>Un producto concreto, con alcance y supuestos definidos</td>
<td>ISO/IEC 17065</td>
<td>Ese producto cumplió esos requisitos en esa configuración</td>
<td>Que otros productos de la organización sean iguales, ni que no vaya a fallar</td>
</tr>
<tr class="even">
<td>Sistema de gestión</td>
<td>La forma de trabajar de una organización</td>
<td>ISO/IEC 17021-1</td>
<td>La organización opera un sistema que cumple la norma</td>
<td>Que cada producto que sale de ella esté libre de defectos</td>
</tr>
<tr class="odd">
<td>Personas</td>
<td>El conocimiento o la competencia de un individuo</td>
<td>ISO/IEC 17024</td>
<td>Esa persona demostró cierta competencia al examinarse</td>
<td>Que el producto en que trabaja sea de calidad</td>
</tr>
</tbody>
</table>
</div>
<p>La ISO/IEC 17021-1 contiene, según su resumen en ISO, principios y requisitos de competencia, consistencia e imparcialidad de los organismos que auditan y certifican cualquier tipo de sistema de gestión. La ISO/IEC 17065 aplica a los organismos que certifican productos, procesos y servicios. La ISO/IEC 17024 aplica a los que certifican personas.</p>
</section>
<section id="caso-de-análisis-la-propuesta-comercial-de-la-clínica-aurora" class="level3">
<h3 class="anchored" data-anchor-id="caso-de-análisis-la-propuesta-comercial-de-la-clínica-aurora">Caso de análisis: la propuesta comercial de la Clínica Aurora</h3>
<p>Situación ilustrativa. La propuesta de la clínica al Hospital San Rafael dice, en su página de presentación, “Nuestra app está certificada”. Como respaldo adjunta dos documentos, el certificado ISO 9001 de la organización y los certificados ISTQB de dos analistas de pruebas. El hospital pregunta si esa evidencia le basta para confiar en que la app protege los datos clínicos. Piensa la respuesta antes de seguir.</p>
<p>No le basta. El certificado ISO 9001 pertenece al objeto sistema de gestión, y los certificados ISTQB pertenecen al objeto personas. Ninguno examinó el producto. Para la parte de seguridad, el hospital necesita evidencia sobre el producto mismo, como un informe de pruebas de seguridad realizado sobre esta app o, si el riesgo lo justifica, una certificación de producto con alcance y supuestos declarados por escrito. Las tres evidencias juntas dan una imagen completa, y ninguna reemplaza a las otras.</p>
</section>
</section>
<section id="parte-4.-certificar-un-sistema-de-gestión" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="parte-4.-certificar-un-sistema-de-gestión"><span class="header-section-number">7</span> Parte 4. Certificar un sistema de gestión</h2>
<section id="iso-9001-qué-es-y-qué-certifica" class="level3">
<h3 class="anchored" data-anchor-id="iso-9001-qué-es-y-qué-certifica">ISO 9001: qué es y qué certifica</h3>
<p>La ISO 9001 fija los requisitos de un sistema de gestión de la calidad. Su contenido se estudia en el <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html">Tema 2 de la Unidad 3</a> y aquí no se repite. Lo que interesa en este tema es el acto de certificar.</p>
<p>La página de ISO sobre la ISO 9001 aporta datos verificables. Más de un millón de organizaciones tienen certificados en 189 países. La ISO 9001 es la única norma de la familia ISO 9000 contra la cual se puede certificar, y la certificación no es obligatoria. La edición vigente, la sexta (ISO 9001:2026), se publicó el 16 de septiembre de 2026 y, según ISO, pone énfasis en la cultura de calidad y el liderazgo, y separa los riesgos de las oportunidades.</p>
</section>
<section id="normas-de-gestión-de-otros-sectores" class="level3">
<h3 class="anchored" data-anchor-id="normas-de-gestión-de-otros-sectores">Normas de gestión de otros sectores</h3>
<p>Existen esquemas de gestión sectoriales que se certifican de la misma manera. ICONTEC menciona, entre los de mayor relevancia, la ISO 14001 (gestión ambiental), la ISO 13485 (dispositivos médicos) y la IATF 16949 (sector automotriz). Para este curso interesa recordar que “ISO 14001” y “EMAS” son esquemas de gestión ambiental, no de producto, una distinción que reaparece en el caso Volkswagen.</p>
</section>
<section id="la-apreciación-cmmi-no-es-un-certificado-de-iso" class="level3">
<h3 class="anchored" data-anchor-id="la-apreciación-cmmi-no-es-un-certificado-de-iso">La apreciación CMMI no es un certificado de ISO</h3>
<p>El CMMI se estudia en el <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html">Tema 4 de la Unidad 3</a>. Para la nomenclatura importa que su mecanismo se llama apreciación (<em>appraisal</em>), y que no corresponde a una certificación ISO. Según el sitio de CMMI Institute (hoy parte de ISACA), la apreciación de tipo Benchmark requiere un líder de apreciación certificado y produce una calificación con vigencia de 3 años. La apreciación de tipo Sustainment, un chequeo posterior, tiene vigencia de 2 años, y no se permiten más de tres seguidas antes de volver a una Benchmark. Las organizaciones pueden publicar el nivel logrado en el sistema de resultados publicados (PARS).</p>
<p>Dos conclusiones útiles. La primera, un nivel CMMI siempre tiene fecha de vencimiento. La segunda, el nivel dice cómo trabaja la organización según el modelo, y el resultado se publica solo si la organización lo decide.</p>
</section>
<section id="ejemplo-resuelto-leer-el-certificado-de-la-clínica-aurora" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-leer-el-certificado-de-la-clínica-aurora">Ejemplo resuelto: leer el certificado de la Clínica Aurora</h3>
<p>Datos ilustrativos. El certificado de la clínica dice: norma ISO 9001:2015, alcance “diseño, desarrollo y mantenimiento de software de gestión de turnos en la sede Medellín”, emitido por un organismo de certificación con acreditación vigente de ONAC, emitido el 15 de marzo de 2024 y con vencimiento el 14 de marzo de 2027.</p>
<p>Lectura paso a paso.</p>
<ol type="1">
<li><strong>Norma y edición.</strong> ISO 9001:2015. Hoy esa edición está retirada, y la clínica debe llevar el plan de transición con su organismo de certificación.</li>
<li><strong>Alcance.</strong> Cubre el diseño, el desarrollo y el mantenimiento en la sede Medellín. Si la app se desarrollara también en otra sede, esa parte no estaría cubierta.</li>
<li><strong>Organismo.</strong> Un organismo acreditado por ONAC. Se verifica en el Directorio Oficial de Acreditados de ONAC.</li>
<li><strong>Fechas.</strong> Emisión y vencimiento. La vigencia se mantiene mientras las auditorías de seguimiento sean favorables.</li>
<li><strong>Lo que no dice.</strong> Ninguna línea afirma que la app de turnos esté libre de defectos ni que sea segura. Certifica el sistema de gestión.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. Qué afirma de verdad el certificado
</div>
</div>
<div class="callout-body-container callout-body">
<p>Marca las afirmaciones que el certificado de la Clínica Aurora (descrito arriba) sí respalda.</p>
<p><label><input type="checkbox"> La clínica opera un sistema de gestión de la calidad conforme a la ISO 9001:2015 en el alcance declarado</label><br> <label><input type="checkbox"> La app de turnos no tiene defectos de seguridad</label><br> <label><input type="checkbox"> El desarrollo hecho en una sede distinta a Medellín queda cubierto</label><br> <label><input type="checkbox"> Hay un organismo de certificación identificable, cuya acreditación puede verificarse</label></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Respaldan la primera y la cuarta. La primera es el objeto exacto de la certificación, y la cuarta se sigue de que el certificado nombra al organismo, cuya acreditación se consulta en el directorio de ONAC.</p>
<p>La segunda no la respalda ningún certificado de sistema de gestión. La tercera tampoco, porque el alcance dice Medellín, y lo que quede fuera de ese alcance no fue evaluado.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-5.-certificar-un-producto" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="parte-5.-certificar-un-producto"><span class="header-section-number">8</span> Parte 5. Certificar un producto</h2>
<section id="common-criteria-e-isoiec-15408" class="level3">
<h3 class="anchored" data-anchor-id="common-criteria-e-isoiec-15408">Common Criteria e ISO/IEC 15408</h3>
<p>Common Criteria es el esquema de certificación de producto más conocido en seguridad de la información. Su texto se publica como la norma ISO/IEC 15408, en cinco partes, y su metodología de evaluación como la ISO/IEC 18045 (CEM). El fabricante declara qué propiedades de seguridad reclama para su producto en un documento llamado blanco de seguridad (<em>security target</em>) o se ciñe a un perfil de protección (<em>protection profile</em>), y un laboratorio evalúa ese reclamo.</p>
<p>El resultado incluye un nivel de garantía de evaluación (EAL, <em>evaluation assurance level</em>), del EAL1 al EAL7. Según la parte 5 de CC:2022, los siete niveles se llaman: EAL1 probado funcionalmente, EAL2 probado estructuralmente, EAL3 probado y verificado metódicamente, EAL4 diseñado, probado y revisado metódicamente, EAL5 diseño semiformal verificado y probado, EAL6 diseño semiformalmente verificado y probado y EAL7 diseño formalmente verificado y probado. Un “+” tras el nivel (EAL4+) significa que se añadieron componentes de garantía a los del nivel. El nivel mide qué tan a fondo se verificó el reclamo, no qué tan seguro es el producto.</p>
</section>
<section id="qué-edición-está-vigente" class="level3">
<h3 class="anchored" data-anchor-id="qué-edición-está-vigente">Qué edición está vigente</h3>
<p>Aquí aparece una situación que ilustra la importancia de leer la edición. Según el sitio del Common Criteria Portal consultado, el texto vigente es CC:2022 Release 1, publicado en noviembre de 2022. La política de transición de CC v3.1 a CC:2022 fija estas reglas.</p>
<ul>
<li>Las evaluaciones iniciales nuevas basadas en CC v3.1 R5 podían iniciarse hasta el 30 de junio de 2024.</li>
<li>Las certificaciones de producto contra un perfil de protección con conformidad exacta, basadas en CC v3.1 R5, podían iniciarse hasta el 31 de diciembre de 2025.</li>
<li>Un blanco de seguridad basado en CC:2022 puede declarar conformidad con un perfil de protección basado en CC v3.1 hasta el 31 de diciembre de 2027.</li>
<li>Tras el 30 de junio de 2024, las reevaluaciones basadas en CC v3.1 pueden iniciarse durante 2 años desde la fecha de la certificación inicial.</li>
</ul>
<p>Al mismo tiempo, el catálogo de ISO muestra que las cinco partes de la ISO/IEC 15408 y la ISO/IEC 18045 se publicaron en nuevas ediciones entre abril y mayo de 2026 (por ejemplo, la ISO/IEC 15408-1:2026, quinta edición), y que las ediciones de 2022 aparecen como retiradas. En la fecha de consulta, el portal de Common Criteria seguía presentando CC:2022 como su texto, y no se encontró en las páginas consultadas una nota que explique cómo se relacionan las ediciones 2026 de ISO con CC:2022. Esa relación queda como no verificada, y quien cite estas normas debe indicar con precisión la edición.</p>
</section>
<section id="el-reconocimiento-entre-países-ccra" class="level3">
<h3 class="anchored" data-anchor-id="el-reconocimiento-entre-países-ccra">El reconocimiento entre países: CCRA</h3>
<p>El acuerdo de reconocimiento de Common Criteria (CCRA), en su texto de 2014, cubre los certificados con reclamos contra perfiles de protección colaborativos (cPP) con actividades de garantía de hasta el nivel 4 más la remediación de fallas (ALC_FLR), o contra niveles EAL1 a EAL2 más ALC_FLR. Es decir, los niveles superiores quedan fuera de ese reconocimiento automático. Según Wikipedia (fuente secundaria), los países del acuerdo europeo SOG-IS suelen reconocer niveles más altos.</p>
</section>
<section id="el-esquema-europeo-eucc" class="level3">
<h3 class="anchored" data-anchor-id="el-esquema-europeo-eucc">El esquema europeo EUCC</h3>
<p>El Reglamento de Ejecución (UE) 2024/482, del 31 de enero de 2024, adoptó el esquema europeo de certificación de ciberseguridad basado en Common Criteria (EUCC). Según el resumen de la consulta en EUR-Lex, es plenamente aplicable desde el 27 de febrero de 2025, reemplaza el esquema fragmentado SOG-IS y define Common Criteria por referencia a las partes de la ISO/IEC 15408 y a la ISO/IEC 18045. Como los textos citados por el reglamento son los de 2022, y existen ahora ediciones 2026 de ISO, conviene consultar la versión consolidada del reglamento antes de afirmar qué edición exige. El texto completo del reglamento no pudo abrirse durante la consulta.</p>
</section>
<section id="una-certificación-es-una-fotografía" class="level3">
<h3 class="anchored" data-anchor-id="una-certificación-es-una-fotografía">Una certificación es una fotografía</h3>
<p>Un ejemplo muy citado es el de Windows XP y Windows Server 2003. Según Wikipedia, que cita una nota de noticias de diciembre de 2005, fueron certificados con EAL4+. Wikipedia explica también que ambos siguieron recibiendo parches de seguridad.</p>
<p>La razón es que una evaluación Common Criteria verifica reclamos de seguridad en una configuración evaluada y bajo supuestos del entorno declarados en el blanco de seguridad, y no promete que no vayan a aparecer vulnerabilidades nuevas. Estos datos vienen de una fuente secundaria. No se pudo abrir la ficha original del certificado en el portal oficial, y por eso el ejemplo se usa solo para ilustrar la idea y no se presenta como dato de auditoría.</p>
<div class="diagrama">
<svg viewbox="0 0 760 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Linea de tiempo de una certificacion de producto. En el momento de la evaluacion, el producto se evalua en una configuracion y con supuestos de entorno declarados, y los reclamos quedan verificados. Con el tiempo aparecen vulnerabilidades nuevas y parches. La certificacion no cubre cambios ni configuraciones fuera de lo evaluado" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t4d" markerwidth="9" markerheight="9" refx="7" refy="2.8" orient="auto"><path d="M0,0 L7,2.8 L0,5.6 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Una certificación de producto es una fotografía</text> <path d="M40,70 L720,70" stroke="#c7d6e6" stroke-width="2.5" fill="none" marker-end="url(#u4t4d)"></path> <g fill="#0e6f6c"><circle cx="170" cy="70" r="7"></circle><circle cx="590" cy="70" r="7"></circle></g> <text x="170" y="52" font-size="11.5" font-weight="700" fill="#12324f" text-anchor="middle">Momento de la evaluación</text> <text x="590" y="52" font-size="11.5" font-weight="700" fill="#12324f" text-anchor="middle">Años después</text> <rect x="50" y="98" width="240" height="106" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <rect x="470" y="98" width="240" height="106" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <g text-anchor="middle" font-size="11.2" fill="#3c7d7a"><text x="170" y="122" font-weight="700" fill="#0e6f6c">Configuración evaluada</text><text x="170" y="142">Supuestos del entorno</text><text x="170" y="158">declarados por escrito</text><text x="170" y="184">Los reclamos quedan verificados</text></g> <g text-anchor="middle" font-size="11.2" fill="#5b6876"><text x="590" y="122" font-weight="700" fill="#12324f">Cambia el entorno</text><text x="590" y="142">Aparecen vulnerabilidades</text><text x="590" y="158">y salen parches</text><text x="590" y="184">La certificación no se actualiza sola</text></g> <text x="380" y="232" font-size="11.2" fill="#5b6876" text-anchor="middle">Un nivel más alto significa una evaluación más profunda, no una promesa de seguridad futura</text>
</svg>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 4. Aplica las reglas de transición
</div>
</div>
<div class="callout-body-container callout-body">
<p>Con las reglas de transición de CC v3.1 a CC:2022 de arriba, decide si cada caso era admisible.</p>
<ol type="1">
<li>Un fabricante inicia el 2 de septiembre de 2024 la evaluación de un producto con un blanco de seguridad basado en CC v3.1 R5 y sin perfil de protección.</li>
<li>Un fabricante presenta el 10 de octubre de 2027 un blanco de seguridad basado en CC:2022 que declara conformidad con un perfil de protección certificado según CC v3.1.</li>
<li>Un producto certificado el 1 de marzo de 2023 bajo CC v3.1 R5 inicia una reevaluación el 1 de febrero de 2025.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>No era admisible. Las evaluaciones iniciales nuevas bajo CC v3.1 R5 podían empezar hasta el 30 de junio de 2024, y el 2 de septiembre de 2024 ya había pasado ese plazo.</li>
<li>Sí era admisible. El blanco de seguridad basado en CC:2022 puede declarar conformidad con un perfil de CC v3.1 hasta el 31 de diciembre de 2027, y el 10 de octubre de 2027 está dentro de ese plazo.</li>
<li>Sí era admisible. La reevaluación basada en CC v3.1 puede iniciarse durante 2 años desde la certificación inicial, es decir hasta el 1 de marzo de 2025, y el 1 de febrero de 2025 queda dentro.</li>
</ol>
<p>Las reglas se tomaron de la política de transición del portal de Common Criteria. Antes de aplicarlas a un caso real debe revisarse la versión vigente de esa política, porque las ediciones 2026 de ISO pueden traer ajustes.</p>
</div>
</div>
</div>
</section>
<section id="dónde-falla-la-certificación-de-producto-el-caso-de-la-homologación-de-emisiones" class="level3">
<h3 class="anchored" data-anchor-id="dónde-falla-la-certificación-de-producto-el-caso-de-la-homologación-de-emisiones">Dónde falla la certificación de producto: el caso de la homologación de emisiones</h3>
<p>Los vehículos también se certifican como producto. Para venderlos en Estados Unidos, un modelo debe pasar las pruebas de certificación de emisiones de la EPA, cuyos procedimientos de laboratorio están fijados en el Código de Regulaciones Federales. Una certificación de producto asegura que el producto superó una prueba definida, y el caso Volkswagen de la Parte 9 muestra qué pasa cuando el producto reconoce la prueba.</p>
</section>
</section>
<section id="parte-6.-certificar-personas" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="parte-6.-certificar-personas"><span class="header-section-number">9</span> Parte 6. Certificar personas</h2>
<section id="isoiec-17024" class="level3">
<h3 class="anchored" data-anchor-id="isoiec-17024">ISO/IEC 17024</h3>
<p>La ISO/IEC 17024 fija los requisitos de los organismos que certifican personas. En su edición vigente, la tercera (marzo de 2026), que retiró a la de 2012, ISO explica que busca que esos organismos operen de manera consistente, confiable y reconocida internacionalmente, y que la revisión más reciente incorpora los desafíos de las herramientas de evaluación basadas en inteligencia artificial. Una certificación de personas asegura que un individuo cumplió los requisitos de competencia de un esquema de certificación específico. En Colombia, ONAC acredita organismos de certificación de personas, y su reconocimiento internacional cubre ese esquema.</p>
</section>
<section id="el-esquema-istqb" class="level3">
<h3 class="anchored" data-anchor-id="el-esquema-istqb">El esquema ISTQB</h3>
<p>El Consejo Internacional de Calificaciones de Pruebas de Software, ISTQB (<em>International Software Testing Qualifications Board</em>), se estableció en 1998 y administra el esquema Certified Tester. Según su sitio, a mayo de 2025 el ISTQB había administrado 1,5 millones de exámenes y emitido más de 1,1 millones de certificaciones en más de 130 países. Esas cifras tienen fecha y cambian, de modo que debe citarse la fecha de corte.</p>
<p>El esquema tiene un nivel Foundation, que es prerrequisito de los demás, y niveles Core Advanced, Specialist y Expert. La versión vigente del programa de Foundation es CTFL v4.0, con examen de 40 preguntas, nota de aprobación de 26 puntos sobre 40 (65 %), duración de 60 minutos y 25 % más de tiempo para quien no presenta en su lengua nativa. Según el sitio, los certificados de nivel Expert son válidos por 7 años.</p>
</section>
<section id="otros-ejemplos-de-certificación-de-personas" class="level3">
<h3 class="anchored" data-anchor-id="otros-ejemplos-de-certificación-de-personas">Otros ejemplos de certificación de personas</h3>
<p>CMMI Institute ofrece cuatro certificaciones de personas, con especializaciones. ASQ (American Society for Quality) ofrece certificaciones de calidad entre las que figura la de ingeniero de calidad de software (CSQE), pero el sitio de ASQ bloqueó la consulta y no se pudieron verificar sus requisitos, su examen ni su vigencia, así que no se detallan aquí.</p>
</section>
<section id="qué-dice-una-certificación-de-personas" class="level3">
<h3 class="anchored" data-anchor-id="qué-dice-una-certificación-de-personas">Qué dice una certificación de personas</h3>
<p>Dice que la persona demostró, en un momento dado, conocer lo que el esquema evalúa. No dice que el producto en que trabaja sea bueno, ni que la persona aplique ese conocimiento en cada proyecto, ni garantiza su actualización si el esquema no exige renovación.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 5. Reparte las evidencias de la propuesta
</div>
</div>
<div class="callout-body-container callout-body">
<p>La propuesta de la Clínica Aurora trae cuatro evidencias. Indica para cada una a cuál de los tres objetos (producto, sistema de gestión, personas) corresponde y qué afirmación del pliego respalda.</p>
<ol type="1">
<li>Un certificado ISTQB Foundation Level de la analista de pruebas Marcela.</li>
<li>El certificado ISO 9001 de la organización.</li>
<li>Un informe de una evaluación de seguridad independiente de la app.</li>
<li>Un certificado de apreciación CMMI Benchmark de la organización, con vigencia de 3 años.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li>Personas. Respalda la afirmación sobre personal de pruebas con certificación reconocida.</li>
<li>Sistema de gestión. Respalda el pliego de un sistema de gestión certificado en ISO 9001.</li>
<li>Producto. Es la evidencia de seguridad del producto que pide el pliego, aunque no sea una certificación formal.</li>
<li>Sistema de gestión, en la forma de apreciación del proceso. No pertenece al pliego (que pide ISO 9001) y debe presentarse como lo que es, una apreciación con vigencia de 3 años.</li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="parte-7.-la-auditoría-de-certificación-de-un-sistema-de-gestión" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="parte-7.-la-auditoría-de-certificación-de-un-sistema-de-gestión"><span class="header-section-number">10</span> Parte 7. La auditoría de certificación de un sistema de gestión</h2>
<p>El ciclo de certificación de un sistema de gestión sigue una secuencia que las normas y los organismos de certificación describen de forma parecida. Las etapas que siguen corresponden a la práctica habitual. El detalle exacto está en la ISO/IEC 17021-1, que es de pago y no se pudo leer, así que esta descripción debe contrastarse con la norma o con el organismo de certificación.</p>
<div class="diagrama">
<svg viewbox="0 0 760 270" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Ciclo habitual de certificacion de un sistema de gestion. Solicitud y alcance, auditoria de etapa uno de preparacion, auditoria de etapa dos de implementacion, decision de certificacion y emision del certificado, auditorias de seguimiento en los años uno y dos, y recertificacion al llegar al año tres" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t4e" markerwidth="9" markerheight="9" refx="7" refy="2.8" orient="auto"><path d="M0,0 L7,2.8 L0,5.6 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Ciclo habitual de certificación (ilustrativo)</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="10" y="40" width="102" height="62" rx="8"></rect><rect x="124" y="40" width="102" height="62" rx="8"></rect><rect x="238" y="40" width="102" height="62" rx="8"></rect></g> <rect x="352" y="40" width="130" height="62" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g text-anchor="middle" font-size="11" font-weight="700" fill="#12324f"><text x="61" y="64">1. Solicitud</text><text x="175" y="64">2. Etapa 1</text><text x="289" y="64">3. Etapa 2</text></g> <text x="417" y="64" font-size="11" font-weight="700" fill="#0e6f6c" text-anchor="middle">4. Decisión y</text> <text x="417" y="80" font-size="11" font-weight="700" fill="#0e6f6c" text-anchor="middle">certificado</text> <g text-anchor="middle" font-size="10" fill="#5b6876"><text x="61" y="82">y alcance</text><text x="175" y="82">preparación</text><text x="289" y="82">implementación</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.5" marker-end="url(#u4t4e)"><path d="M112,71 L122,71"></path><path d="M226,71 L236,71"></path><path d="M340,71 L350,71"></path></g> <path d="M40,150 L720,150" stroke="#c7d6e6" stroke-width="2.5" fill="none"></path> <g fill="#0e6f6c"><circle cx="417" cy="150" r="7"></circle></g> <g fill="#8fb3d1"><circle cx="520" cy="150" r="6"></circle><circle cx="620" cy="150" r="6"></circle></g> <circle cx="720" cy="150" r="7" fill="#0e6f6c"></circle> <g text-anchor="middle" font-size="11" fill="#12324f"><text x="417" y="176" font-weight="700">Año 0</text><text x="520" y="176" font-weight="700">Año 1</text><text x="620" y="176" font-weight="700">Año 2</text><text x="715" y="176" font-weight="700">Año 3</text></g> <g text-anchor="middle" font-size="10.2" fill="#5b6876"><text x="417" y="194">se emite</text><text x="520" y="194">seguimiento</text><text x="620" y="194">seguimiento</text><text x="715" y="194">recertificación</text></g> <path d="M417,102 L417,142" fill="none" stroke="#8fb3d1" stroke-width="1.5" marker-end="url(#u4t4e)"></path> <rect x="150" y="214" width="460" height="40" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="380" y="238" font-size="11" fill="#5b6876" text-anchor="middle">Una no conformidad sin resolver puede suspender o retirar el certificado</text>
</svg>
</div>
<section id="las-etapas-1" class="level3">
<h3 class="anchored" data-anchor-id="las-etapas-1">Las etapas</h3>
<ol type="1">
<li><strong>Solicitud y alcance.</strong> La organización pide la certificación y acuerda con el organismo el alcance: qué sedes, qué actividades, qué productos o servicios.</li>
<li><strong>Auditoría de etapa 1.</strong> El equipo auditor revisa la preparación: documentos del sistema, alcance, si la organización hizo su propia auditoría interna y su revisión por la dirección.</li>
<li><strong>Auditoría de etapa 2.</strong> El equipo audita la implementación en el terreno. Entrevista, observa y toma muestras de registros.</li>
<li><strong>Hallazgos.</strong> Los incumplimientos de un requisito se registran como no conformidades. La organización responde con un plan de acciones correctivas, y el organismo decide si son suficientes.</li>
<li><strong>Decisión y certificado.</strong> Una decisión de certificación, tomada dentro del organismo, emite el certificado con la norma y edición, el alcance y las fechas.</li>
<li><strong>Seguimiento.</strong> En el ciclo habitual de tres años se hacen auditorías de seguimiento intermedias, que verifican parte del sistema.</li>
<li><strong>Recertificación.</strong> Al cierre del ciclo se evalúa de nuevo el sistema completo para renovar el certificado.</li>
</ol>
<p>Las directrices para auditar sistemas de gestión están en la ISO 19011, cuya edición vigente es la ISO 19011:2026 (cuarta edición, publicada en mayo de 2026). Esa norma orienta el trabajo de los auditores, y la ISO/IEC 17021-1 fija los requisitos de los organismos que certifican.</p>
</section>
<section id="qué-se-muestrea-y-qué-no" class="level3">
<h3 class="anchored" data-anchor-id="qué-se-muestrea-y-qué-no">Qué se muestrea y qué no</h3>
<p>Una auditoría de certificación es un muestreo. El equipo auditor no puede revisar todos los registros de todos los proyectos, y por eso toma una muestra de sedes, procesos y registros. Eso explica una limitación importante: una auditoría examina si el sistema de gestión se sigue y deja evidencia, y no inspecciona línea por línea el código de un producto.</p>
</section>
<section id="ejemplo-resuelto-clasificar-un-hallazgo" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-clasificar-un-hallazgo">Ejemplo resuelto: clasificar un hallazgo</h3>
<p>Datos ilustrativos. En la auditoría de la clínica, el equipo toma una muestra de 10 liberaciones del último trimestre. El procedimiento de la clínica exige ejecutar la suite de pruebas de regresión y registrar el resultado antes de liberar. En 3 de las 10 liberaciones no hay registro de esa ejecución.</p>
<ol type="1">
<li>Fracción sin evidencia: 3 de 10, es decir 30 %.</li>
<li>El hallazgo es una no conformidad, porque el procedimiento propio exige el registro y no existe en parte de la muestra.</li>
<li>La acción correctiva esperable incluye corregir la causa (por ejemplo, impedir la liberación sin registro de pruebas en el flujo automatizado) y revisar las liberaciones pasadas.</li>
<li>Una auditoría de seguimiento revisaría si el cambio se mantiene.</li>
</ol>
<p>Ese hallazgo se refiere al cumplimiento del procedimiento propio. Un sistema puede cumplir sus procedimientos y aun así tener procedimientos débiles. La certificación asegura la coherencia entre lo que la organización dice que hace y lo que hace, y no que lo que dice sea suficiente para el producto.</p>
</section>
</section>
<section id="parte-8.-acreditación-organismos-y-reconocimiento-internacional" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="parte-8.-acreditación-organismos-y-reconocimiento-internacional"><span class="header-section-number">11</span> Parte 8. Acreditación, organismos y reconocimiento internacional</h2>
<section id="la-cadena-de-confianza" class="level3">
<h3 class="anchored" data-anchor-id="la-cadena-de-confianza">La cadena de confianza</h3>
<p>El diagrama muestra quién respalda a quién. ISO y los demás organismos de normalización publican las normas. Un organismo de certificación audita a la organización y emite el certificado. Un organismo de acreditación evalúa al organismo de certificación contra la ISO/IEC 17011, que fija los requisitos de los organismos de acreditación y cuya edición vigente es la de 2017. Un acuerdo internacional de reconocimiento hace que los certificados acreditados se acepten entre países.</p>
<div class="diagrama">
<svg viewbox="0 0 760 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cadena de confianza de la certificacion. Las normas las publican ISO e IEC y los organismos nacionales como ICONTEC. Un organismo de certificacion audita y emite el certificado a la organizacion. Un organismo de acreditacion, en Colombia ONAC, evalua y acredita al organismo de certificacion. Un acuerdo internacional, a cargo de Global ACI, permite reconocer los certificados entre paises" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t4f" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Quién respalda a quién</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="10" y="40" width="172" height="104" rx="10"></rect><rect x="200" y="40" width="172" height="104" rx="10"></rect><rect x="390" y="40" width="172" height="104" rx="10"></rect></g> <rect x="580" y="40" width="170" height="104" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g text-anchor="middle" font-size="12.5" font-weight="700" fill="#12324f"><text x="96" y="64">Normas</text><text x="286" y="64">Certificación</text><text x="476" y="64">Acreditación</text></g> <text x="665" y="64" font-size="12.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Reconocimiento</text> <g text-anchor="middle" font-size="10.4" fill="#5b6876"><text x="96" y="86">ISO, IEC, IEEE</text><text x="96" y="102">y organismos nacionales</text><text x="96" y="118">(ICONTEC en Colombia)</text><text x="286" y="86">Audita y emite el</text><text x="286" y="102">certificado a la</text><text x="286" y="118">organización</text><text x="476" y="86">Evalúa al certificador</text><text x="476" y="102">(ISO/IEC 17011).</text><text x="476" y="118">En Colombia, ONAC</text></g> <g text-anchor="middle" font-size="10.4" fill="#3c7d7a"><text x="665" y="86">Acuerdos entre países.</text><text x="665" y="102">Global ACI desde 2026</text><text x="665" y="118">(antes IAF e ILAC)</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u4t4f)"><path d="M182,92 L198,92"></path><path d="M372,92 L388,92"></path><path d="M562,92 L578,92"></path></g> <rect x="200" y="196" width="172" height="52" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="286" y="218" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">Organización</text> <text x="286" y="236" font-size="10.4" fill="#5b6876" text-anchor="middle">(Clínica Aurora)</text> <path d="M286,196 L286,146" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u4t4f)"></path> <text x="300" y="176" font-size="10.4" fill="#5b6876">pide la certificación</text> <text x="380" y="276" font-size="10.8" fill="#5b6876" text-anchor="middle">ISO no certifica: la certificación la hace un organismo externo</text>
</svg>
</div>
</section>
<section id="colombia-icontec-y-onac" class="level3">
<h3 class="anchored" data-anchor-id="colombia-icontec-y-onac">Colombia: ICONTEC y ONAC</h3>
<p>ICONTEC se describe en su sitio como una organización privada sin ánimo de lucro, creada en 1963, que presta servicios de normalización (como organismo nacional de normalización de Colombia), educación, evaluación de la conformidad (certificación de producto, de sistemas de gestión, inspección, validación y verificación) y venta de normas. Es además el socio colombiano de IQNET, una red de certificadores, y quienes certifican sistemas de gestión con ICONTEC reciben un certificado IQNET. Una organización que normaliza y a la vez certifica cumple funciones distintas, y por eso existe un tercer actor que vigila a quien certifica.</p>
<p>ONAC es el Organismo Nacional de Acreditación de Colombia. Su sitio lo describe como una corporación del Subsistema Nacional de la Calidad (SICAL), de carácter privado, naturaleza mixta y sin ánimo de lucro. Acredita a los organismos de evaluación de la conformidad (laboratorios, certificadores, inspectores) y mantiene el Directorio Oficial de Acreditados, que ONAC presenta como la única fuente oficial de información sobre las acreditaciones en Colombia. Los certificados de acreditación suspendidos, vencidos o retirados también aparecen en ese directorio.</p>
</section>
<section id="reconocimiento-internacional" class="level3">
<h3 class="anchored" data-anchor-id="reconocimiento-internacional">Reconocimiento internacional</h3>
<p>ONAC informa que fue admitido como miembro del International Accreditation Forum (IAF) en 2010, y que tiene reconocimientos internacionales por IAAC (cooperación regional de las Américas), por ILAC y por IAF, para los esquemas de laboratorios, de organismos certificadores de producto, de sistemas de gestión, de validación y verificación y de personas.</p>
<p>Hay un cambio reciente. Según ISO, la Global Accreditation Cooperation Incorporated (Global ACI) asumió los papeles que antes tenían IAF e ILAC. Boletines de organismos de acreditación (APAC, NATA y SAC) indican que Global ACI quedó plenamente operativa el 1 de enero de 2026, como sociedad sin ánimo de lucro registrada en Nueva Zelanda, y que las acreditaciones y marcas vigentes de IAF e ILAC siguen reconocidas mientras se migra a la marca nueva. Esos boletines no se pudieron abrir en la consulta directa, y el dato se tomó de resúmenes de búsqueda, con la confirmación parcial de la página de ISO. La página de ONAC consultada aún nombra a IAF e ILAC.</p>
<p>El reconocimiento mutuo también existe por esquema. La Parte 5 mostró el CCRA para Common Criteria. El ISTQB funciona con juntas nacionales miembros. Y el reglamento europeo EUCC establece su propio marco de reconocimiento para la Unión Europea.</p>
</section>
<section id="cómo-verificar-un-certificado" class="level3">
<h3 class="anchored" data-anchor-id="cómo-verificar-un-certificado">Cómo verificar un certificado</h3>
<p>ISO recomienda dos rutas para verificar un certificado emitido por un organismo acreditado: consultar la base de datos global IAF CertSearch, que reúne datos de organismos de acreditación y de certificación y permite confirmar el estado de la certificación y de la acreditación, o contactar al organismo de certificación, al de acreditación o a Global ACI. En Colombia se agrega el Directorio Oficial de Acreditados de ONAC y la consulta de certificaciones de ICONTEC.</p>
<p>Pasos recomendados.</p>
<ol type="1">
<li>Pedir el número del certificado, la norma y la edición, el alcance, el organismo y las fechas.</li>
<li>Buscar el organismo en el directorio de ONAC o en el del acreditador de su país.</li>
<li>Confirmar en IAF CertSearch o con el organismo de certificación que el certificado esté vigente.</li>
<li>Comparar el alcance del certificado con lo que se está contratando.</li>
<li>Anotar la fecha de consulta, porque la vigencia puede cambiar.</li>
</ol>
</section>
</section>
<section id="parte-9.-caso-volkswagen-certificaciones-vigentes-y-un-fraude-de-emisiones" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="parte-9.-caso-volkswagen-certificaciones-vigentes-y-un-fraude-de-emisiones"><span class="header-section-number">12</span> Parte 9. Caso Volkswagen: certificaciones vigentes y un fraude de emisiones</h2>
<section id="los-hechos" class="level3">
<h3 class="anchored" data-anchor-id="los-hechos">Los hechos</h3>
<p>Los hechos de esta parte se tomaron de la página oficial de la EPA sobre las violaciones de Volkswagen (última actualización del 10 de junio de 2026) y de los informes de la propia empresa.</p>
<ul>
<li>Volkswagen, Audi y Porsche instalaron un software que detectaba cuándo el vehículo estaba en una prueba de emisiones y activaba los controles completos solo durante la prueba. En conducción normal, los vehículos emitían óxidos de nitrógeno hasta 40 veces por encima del estándar.</li>
<li>El 18 de septiembre de 2015, la EPA emitió una notificación de violación de la Ley de Aire Limpio por los motores diésel de 2,0 litros de los modelos de 2009 a 2015.</li>
<li>El 2 de noviembre de 2015, emitió otra por los motores de 3,0 litros de 2014 a 2016 (hasta 9 veces el estándar). El 19 de noviembre de 2015, la empresa informó que el dispositivo existía en todos sus modelos diésel de 3,0 litros en Estados Unidos desde 2009.</li>
<li>El 4 de enero de 2016, el Departamento de Justicia presentó una demanda en nombre de la EPA.</li>
<li>El acuerdo por los motores de 2,0 litros se anunció el 28 de junio de 2016 y entró en vigor el 25 de octubre de 2016. El de 3,0 litros, el 20 de diciembre de 2016.</li>
<li>El 11 de enero de 2017, Volkswagen aceptó declararse culpable de tres delitos graves y pagar 2.800 millones de dólares de multa penal, y 1.500 millones de dólares en resoluciones civiles de reclamos ambientales, de aduanas y financieros.</li>
<li>La EPA resume el caso como la venta de unos 590.000 vehículos diésel de los años modelo 2009 a 2016 con dispositivos de desactivación.</li>
</ul>
<div class="diagrama">
<svg viewbox="0 0 760 280" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Linea de tiempo del caso Volkswagen. 18 de septiembre de 2015 notificacion de violacion por los motores de dos litros. 2 de noviembre de 2015 notificacion por los motores de tres litros. 4 de enero de 2016 demanda del Departamento de Justicia. 28 de junio de 2016 acuerdo por los motores de dos litros. 20 de diciembre de 2016 acuerdo por los de tres litros. 11 de enero de 2017 declaracion de culpabilidad con multa penal de 2800 millones de dolares" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">El caso en fechas</text> <path d="M30,120 L730,120" stroke="#c7d6e6" stroke-width="2.5" fill="none"></path> <g fill="#0e6f6c"><circle cx="70" cy="120" r="7"></circle><circle cx="170" cy="120" r="7"></circle><circle cx="270" cy="120" r="7"></circle><circle cx="440" cy="120" r="7"></circle><circle cx="600" cy="120" r="7"></circle><circle cx="700" cy="120" r="7"></circle></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.4"><path d="M70,113 L70,92"></path><path d="M170,127 L170,148"></path><path d="M270,113 L270,92"></path><path d="M440,127 L440,148"></path><path d="M600,113 L600,92"></path><path d="M700,127 L700,148"></path></g> <g text-anchor="middle" font-size="10.6" font-weight="700" fill="#12324f"><text x="70" y="40">18 sep 2015</text><text x="170" y="178">2 nov 2015</text><text x="270" y="40">4 ene 2016</text><text x="440" y="178">28 jun 2016</text><text x="600" y="40">20 dic 2016</text><text x="700" y="178">11 ene 2017</text></g> <g text-anchor="middle" font-size="10" fill="#5b6876"><text x="70" y="56">Aviso por motores</text><text x="70" y="70">de 2,0 litros</text><text x="170" y="196">Aviso por motores</text><text x="170" y="210">de 3,0 litros</text><text x="270" y="56">Demanda del</text><text x="270" y="70">Dpto. de Justicia</text><text x="440" y="196">Acuerdo por</text><text x="440" y="210">motores de 2,0 litros</text><text x="600" y="56">Acuerdo por</text><text x="600" y="70">motores de 3,0 litros</text><text x="700" y="196">Culpabilidad y multa</text><text x="700" y="210">penal de 2.800 millones</text></g> <rect x="150" y="236" width="460" height="34" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="380" y="258" font-size="10.8" fill="#5b6876" text-anchor="middle">Fuente: página de la EPA sobre las violaciones de Volkswagen, actualizada el 10 de junio de 2026</text>
</svg>
</div>
</section>
<section id="qué-certificaciones-tenía-el-grupo" class="level3">
<h3 class="anchored" data-anchor-id="qué-certificaciones-tenía-el-grupo">Qué certificaciones tenía el grupo</h3>
<p>Las fuentes oficiales de la empresa permiten afirmar lo siguiente.</p>
<ul>
<li>Informe de sostenibilidad 2016: al cierre de 2016, 97 de los 120 sitios de producción del Grupo tenían un certificado ISO 14001 o EMAS vigente. En el desarrollo técnico de Wolfsburg se decidió suspender de forma temporal el registro EMAS para 2015, y el sitio volvió al registro en noviembre de 2016 tras la revisión de auditores ambientales. El departamento de desarrollo técnico de la marca Volkswagen se recertificó en 2016 a la ISO 14001:2015.</li>
<li>En ese mismo informe, la empresa escribe que su gestión de la calidad se basa en la ISO 9001 y que debe cumplir esa norma para obtener la homologación de sus vehículos.</li>
<li>Informe de sostenibilidad 2023: 106 de 115 sitios con ISO 14001 o EMAS, equivalentes a más de 99 % de los empleados.</li>
<li>Informe anual 2025: el sistema de gestión de la calidad del Grupo se basa en la ISO 9001 y en los requisitos oficiales de homologación, y se pide a todos los sitios de producción y desarrollo tener su gestión ambiental certificada en ISO 14001 o validada por EMAS.</li>
</ul>
<p>Para el cálculo, 97 de 120 equivale a 80,8 %, y 106 de 115 a 92,2 %.</p>
<p>Lo que las fuentes consultadas no permiten afirmar es que, en 2015, Volkswagen AG tuviera un certificado ISO 9001 emitido por un organismo de certificación para toda la organización. Los informes dicen que la gestión de la calidad “se basa” en la ISO 9001, que es distinto de declarar un certificado con alcance y fecha. El caso se analiza con lo que sí está documentado, que es la certificación ISO 14001 o EMAS de la mayoría de los sitios en 2016. Los certificados originales, con su alcance y fechas, no se pudieron consultar.</p>
</section>
<section id="análisis" class="level3">
<h3 class="anchored" data-anchor-id="análisis">Análisis</h3>
<p>Pregunta de análisis antes de leer la respuesta. Si la mayoría de los sitios del Grupo tenía un sistema de gestión ambiental certificado y la gestión de la calidad se basaba en la ISO 9001, ¿por qué ninguno de esos mecanismos impidió que un producto emitiera hasta 40 veces el límite en carretera?</p>
<p>Tres razones se desprenden de los hechos.</p>
<ol type="1">
<li><strong>El objeto certificado era el sistema, no el producto.</strong> ISO 14001 evalúa un sistema de gestión ambiental, y no mide las emisiones de cada motor en carretera. Un sistema puede existir y cumplirse sin que cada producto cumpla la ley.</li>
<li><strong>La prueba que sí evaluaba el producto fue la engañada.</strong> Las pruebas de certificación de emisiones se hacen en laboratorio, con ciclos definidos, y el software reconocía esas condiciones. El mecanismo de producto falló porque el producto sabía que lo evaluaban.</li>
<li><strong>Una auditoría muestrea evidencia, no revisa intenciones.</strong> Un auditor de sistemas de gestión revisa procedimientos, registros y una muestra. Un dispositivo diseñado para ocultarse de una prueba externa no tiene por qué aparecer en esa muestra.</li>
</ol>
<p>La consecuencia práctica para quien lee un certificado es preguntar siempre qué objeto cubre y qué no cubre. La suspensión temporal del registro EMAS de Wolfsburg en 2015 muestra además que los certificados se reportan por sitio y por año, y que un resumen como “el Grupo está certificado” omite esos detalles.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Lo que este caso no dice
</div>
</div>
<div class="callout-body-container callout-body">
<p>El caso no demuestra que las certificaciones carezcan de valor. Las certificaciones de sistemas de gestión verifican prácticas organizacionales y cumplen esa función. El caso muestra que no sirven como sustituto de la evidencia técnica sobre el producto, y que tampoco evitan decisiones deliberadas de la dirección de una empresa.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 6. Qué evidencia habría detectado el problema
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un hospital evalúa a un fabricante que presenta un certificado ISO 14001 vigente y dice que “su producto cumple la normativa de emisiones”. Con lo aprendido en el caso, marca las acciones que sí aportan evidencia sobre el producto.</p>
<p><label><input type="checkbox"> Pedir el certificado ISO 14001 y verificar su vigencia en el directorio del organismo acreditador</label><br> <label><input type="checkbox"> Solicitar resultados de pruebas de emisiones en condiciones de uso real, hechas por un laboratorio independiente</label><br> <label><input type="checkbox"> Leer el informe de sostenibilidad de la empresa</label><br> <label><input type="checkbox"> Revisar si el producto tiene una certificación de producto con alcance y supuestos declarados</label></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Aportan evidencia sobre el producto la segunda y la cuarta. Las pruebas independientes en condiciones reales miden el producto cuando no sabe que lo prueban, y una certificación de producto con alcance y supuestos declarados dice exactamente qué se verificó.</p>
<p>La primera y la tercera son útiles para conocer el sistema de gestión y el discurso de la empresa, pero no miden el producto. Verificar el certificado es el primer paso de la lectura crítica, y no la conclusión.</p>
</div>
</div>
</div>
</section>
</section>
<section id="errores-frecuentes" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="errores-frecuentes"><span class="header-section-number">13</span> Errores frecuentes</h2>
<ul>
<li>Citar una norma sin su año, o con un año que ya fue reemplazado.</li>
<li>Confundir “retirada” en el catálogo de ISO con “certificados inválidos”. La validez de los certificados la regula la transición.</li>
<li>Decir que “ISO certifica” una organización, cuando ISO publica normas y la certificación la hacen organismos externos.</li>
<li>Presentar el certificado de una organización como si fuera una certificación del producto.</li>
<li>Presentar un certificado de personas (como ISTQB) como garantía de calidad de un producto.</li>
<li>Tomar el nivel EAL de Common Criteria como medida de seguridad, cuando mide la profundidad de la evaluación.</li>
<li>No leer el alcance de un certificado, y darlo por válido para sedes o productos que no cubre.</li>
<li>Citar cifras del ISTQB, de certificados de ISO 9001 o de transiciones sin fecha de corte ni fuente.</li>
<li>Dar por verificada una fecha de transición que solo aparece en blogs de organismos de certificación.</li>
<li>Suponer que un certificado vigente prueba que no hubo conducta indebida.</li>
</ul>
</section>
<section id="autoevaluación" class="level2" data-number="14">
<h2 data-number="14" class="anchored" data-anchor-id="autoevaluación"><span class="header-section-number">14</span> Autoevaluación</h2>
<p>Responde sin mirar la guía. Marca tu opción y abre la clave para comprobarla. Es una práctica formativa y no tiene nota.</p>
<p><strong>1.</strong> En el nombre <code>ISO/IEC 15408-1:2026</code>, ¿qué indican <code>-1</code> y <code>:2026</code>?</p>
<p><label><input type="checkbox"> La parte 1 de la serie y el año de la edición</label><br> <label><input type="checkbox"> La versión 1 del proyecto y el año de la última enmienda</label><br> <label><input type="checkbox"> El nivel de garantía 1 y el año del certificado</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. La parte distingue documentos de una misma serie, y el año tras los dos puntos identifica la edición. Las enmiendas se escriben aparte, como <code>/Amd 1:2024</code>.</p>
</div>
</div>
</div>
<p><strong>2.</strong> Una ficha de ISO muestra el código de etapa 90.93. ¿Qué significa?</p>
<p><label><input type="checkbox"> La norma fue confirmada tras una revisión sistemática</label><br> <label><input type="checkbox"> La norma fue retirada</label><br> <label><input type="checkbox"> La norma está en votación de borrador final</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. El 90.93 es “norma internacional confirmada”. El retiro es 95.99 y la votación del borrador final es 50.20.</p>
</div>
</div>
</div>
<p><strong>3.</strong> El 3 de octubre de 2026, la ficha de ISO muestra la ISO 9001:2015 como retirada. ¿Qué se puede afirmar con las fuentes de la guía?</p>
<p><label><input type="checkbox"> Todos los certificados ISO 9001:2015 quedaron anulados en esa fecha</label><br> <label><input type="checkbox"> Los certificados no se anulan automáticamente, y la organización debe pasar a la edición nueva dentro del plazo que fije su ciclo de certificación</label><br> <label><input type="checkbox"> La ISO 9001:2026 solo es una recomendación</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. ISO indica que las organizaciones certificadas deben hacer la transición en el plazo de su ciclo de certificación y consultar con su organismo. La fecha concreta de fin de transición debe confirmarse con ese organismo.</p>
</div>
</div>
</div>
<p><strong>4.</strong> ¿Quién emite el certificado ISO 9001 de una organización?</p>
<p><label><input type="checkbox"> ISO</label><br> <label><input type="checkbox"> Un organismo de certificación externo</label><br> <label><input type="checkbox"> El organismo de acreditación del país</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. ISO publica la norma y no certifica. El organismo de acreditación evalúa al certificador, y no emite el certificado de la organización.</p>
</div>
</div>
</div>
<p><strong>5.</strong> ¿Cuál es el papel de ONAC en Colombia?</p>
<p><label><input type="checkbox"> Publicar las normas técnicas colombianas</label><br> <label><input type="checkbox"> Acreditar a los organismos de evaluación de la conformidad, como los certificadores</label><br> <label><input type="checkbox"> Certificar el sistema de gestión de las empresas</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Las NTC las publica ICONTEC como organismo nacional de normalización, y la certificación la hacen certificadores como ICONTEC o los demás organismos acreditados.</p>
</div>
</div>
</div>
<p><strong>6.</strong> Una analista tiene el certificado ISTQB Foundation Level. ¿Qué respalda?</p>
<p><label><input type="checkbox"> Que el producto en que trabaja está libre de defectos</label><br> <label><input type="checkbox"> Que demostró conocimiento de los fundamentos de pruebas, según el esquema</label><br> <label><input type="checkbox"> Que la organización donde trabaja cumple la ISO 9001</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Es una certificación de personas: evalúa competencia individual y no dice nada del producto ni de la organización.</p>
</div>
</div>
</div>
<p><strong>7.</strong> Una organización obtuvo una apreciación CMMI de tipo Benchmark. ¿Cuál es su vigencia según CMMI Institute?</p>
<p><label><input type="checkbox"> 1 año</label><br> <label><input type="checkbox"> 2 años</label><br> <label><input type="checkbox"> 3 años</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 3. La apreciación Sustainment, el chequeo posterior, tiene vigencia de 2 años.</p>
</div>
</div>
</div>
<p><strong>8.</strong> Un producto tiene un certificado Common Criteria con EAL4+. ¿Qué dice el nivel?</p>
<p><label><input type="checkbox"> Que el producto es seguro frente a cualquier ataque futuro</label><br> <label><input type="checkbox"> Qué tan a fondo se verificó el reclamo de seguridad, en la configuración y con los supuestos declarados</label><br> <label><input type="checkbox"> Que fue evaluado por un organismo de acreditación</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. El nivel mide la profundidad de la evaluación, y el “+” indica componentes de garantía añadidos. No promete seguridad futura.</p>
</div>
</div>
</div>
<p><strong>9.</strong> Según el informe de sostenibilidad 2016, 97 de 120 sitios de producción tenían certificado ISO 14001 o EMAS vigente al cierre de 2016. ¿Qué porcentaje es, y qué se puede concluir sobre el fraude de emisiones?</p>
<p><label><input type="checkbox"> 80,8 %, y la certificación garantizaba que los motores cumplían los límites</label><br> <label><input type="checkbox"> 80,8 %, y el certificado de gestión ambiental de los sitios no impedía por sí mismo que un producto incumpliera los límites</label><br> <label><input type="checkbox"> 97 %, y todos los sitios estaban certificados</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. 97 dividido entre 120 es 0,808, es decir 80,8 %. El certificado ISO 14001 evalúa un sistema de gestión ambiental y no mide las emisiones de cada vehículo.</p>
</div>
</div>
</div>
<p><strong>10.</strong> Una empresa muestra un certificado ISO 9001. ¿Qué haces primero para evaluarlo?</p>
<p><label><input type="checkbox"> Aceptarlo porque tiene el logotipo de un organismo</label><br> <label><input type="checkbox"> Leer norma, edición, alcance, organismo y fechas, y verificarlo en el directorio de acreditados o en IAF CertSearch</label><br> <label><input type="checkbox"> Pedir a ISO que lo confirme</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 10
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. ISO no certifica ni confirma certificados de terceros. La verificación se hace con el organismo, con el acreditador o con IAF CertSearch.</p>
</div>
</div>
</div>
</section>
<section id="lo-que-te-llevas" class="level2" data-number="15">
<h2 data-number="15" class="anchored" data-anchor-id="lo-que-te-llevas"><span class="header-section-number">15</span> Lo que te llevas</h2>
<div class="checklist">
<p><strong>Al salir de este tema deberías poder explicar, sin mirar la guía</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Qué dice cada elemento del nombre de una norma y qué norma fija el vocabulario de ingeniería de software</label></li>
<li><label><input type="checkbox">Las etapas de una norma, qué significan 90.93, 90.92 y 95.99, y cómo se comprueba la vigencia en el catálogo de ISO</label></li>
<li><label><input type="checkbox">Por qué una norma retirada no anula de inmediato los certificados emitidos</label></li>
<li><label><input type="checkbox">Los tres objetos certificables y qué dice y qué no dice cada tipo de certificado</label></li>
<li><label><input type="checkbox">Qué es una apreciación CMMI y por qué su resultado tiene fecha de vencimiento</label></li>
<li><label><input type="checkbox">Qué mide el nivel EAL de Common Criteria y por qué una certificación de producto es una fotografía</label></li>
<li><label><input type="checkbox">Las etapas de una auditoría de certificación y por qué una auditoría es un muestreo</label></li>
<li><label><input type="checkbox">Quién es quién en la cadena norma, certificador, acreditador y reconocimiento, y cómo verificar un certificado</label></li>
<li><label><input type="checkbox">Qué objeto estaba certificado en el caso Volkswagen y por qué no impidió el fraude</label></li>
</ul>
</div>
</section>
<section id="fuentes-y-límites-de-la-verificación" class="level2" data-number="16">
<h2 data-number="16" class="anchored" data-anchor-id="fuentes-y-límites-de-la-verificación"><span class="header-section-number">16</span> Fuentes y límites de la verificación</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Qué se verificó y qué no (consulta del 3 de octubre de 2026)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Verificado en fuente primaria: fichas del catálogo de ISO (24765, 9001:2015 y 2026, 9000:2026, 14001:2026, 15408 partes 1 a 5 y 18045 en sus ediciones 2026, 17024:2026, 17011, 17021-1, 17065, 90003, 25010, 19011:2026), tabla de códigos de etapa y páginas de ISO sobre certificación, entregables y encuesta; política de transición y texto del CCRA del Common Criteria Portal; página de la EPA sobre Volkswagen; informes de sostenibilidad 2016 y 2023 e informe anual 2025 de Volkswagen; sitios de ICONTEC, ONAC, ISTQB y CMMI Institute.</p>
<p>No verificado en fuente primaria, y marcado así en el texto: la fecha de fin de transición de la ISO 9001:2015 (30 de septiembre de 2029) y las reglas de transición de Global ACI, tomadas de organismos de certificación y de resúmenes de búsqueda.</p>
<p>También quedan sin verificar: el texto del Reglamento (UE) 2024/482 (EUR-Lex bloqueó la consulta); la convención de designación de normas del IEEE; los requisitos y la vigencia de las certificaciones de ASQ; la ficha original de Windows XP y Server 2003 en Common Criteria; el detalle exacto de las etapas de la auditoría (ISO/IEC 17021-1 es de pago); la relación entre las ediciones 2026 de la ISO/IEC 15408 y CC:2022; la existencia de un certificado ISO 9001 emitido a Volkswagen AG en 2015; y las sentencias y cifras de la demanda del Departamento de Justicia, cuyo sitio bloqueó la consulta automática (las cifras citadas vienen de la página de la EPA).</p>
</div>
</div>
</div>
</section>
<section id="glosario" class="level2" data-number="17">
<h2 data-number="17" class="anchored" data-anchor-id="glosario"><span class="header-section-number">17</span> Glosario</h2>
<ul>
<li><strong>Nomenclatura.</strong> Conjunto de reglas para nombrar y numerar normas, y vocabulario normalizado para los términos de un campo.</li>
<li><strong>ISO/IEC/IEEE 24765.</strong> Vocabulario de ingeniería de sistemas y de software; su edición vigente es la de 2017.</li>
<li><strong>Edición.</strong> Versión de una norma identificada por su año, como ISO 9001:2026.</li>
<li><strong>Parte.</strong> Subdivisión de una norma que se publica y revisa por separado, como la 15408-1.</li>
<li><strong>Enmienda (Amd).</strong> Documento que añade contenido a una edición, como ISO 9001:2015/Amd 1:2024.</li>
<li><strong>Corrigendo (Cor).</strong> Documento que corrige errores de una edición.</li>
<li><strong>Norma internacional, TS, TR, PAS, IWA y Guide.</strong> Tipos de documento que publica ISO.</li>
<li><strong>DIS y FDIS.</strong> Borrador de norma internacional y borrador final, que se votan antes de publicar.</li>
<li><strong>Código armonizado de etapa.</strong> Código numérico que dice en qué punto del ciclo está un documento de ISO.</li>
<li><strong>Revisión sistemática.</strong> Revisión de una norma cada cinco años, que termina en confirmar, revisar o retirar.</li>
<li><strong>Norma retirada.</strong> Edición que deja de ser la vigente en el catálogo. No anula por sí sola los certificados ya emitidos.</li>
<li><strong>NTC.</strong> Norma Técnica Colombiana, publicada por ICONTEC, muchas veces adopción de una norma ISO.</li>
<li><strong>Evaluación de la conformidad.</strong> Demostración de que un producto, proceso, sistema, servicio o persona cumple requisitos.</li>
<li><strong>Certificación.</strong> Aseguramiento escrito de un organismo independiente de que algo cumple requisitos específicos.</li>
<li><strong>Certificación de producto, de sistema de gestión y de personas.</strong> Los tres objetos que se pueden certificar.</li>
<li><strong>Organismo de certificación.</strong> Organismo externo que audita y emite el certificado.</li>
<li><strong>Acreditación.</strong> Reconocimiento formal de que un organismo de certificación opera conforme a normas internacionales.</li>
<li><strong>Organismo de acreditación.</strong> El que acredita a los certificadores; en Colombia, ONAC.</li>
<li><strong>Alcance.</strong> Parte de la organización, de sus actividades o de sus productos que cubre un certificado.</li>
<li><strong>Auditoría de etapa 1 y de etapa 2.</strong> Revisión de la preparación y revisión de la implementación del sistema.</li>
<li><strong>Auditoría de seguimiento y recertificación.</strong> Auditorías intermedias del ciclo y renovación al cierre de este.</li>
<li><strong>No conformidad.</strong> Incumplimiento de un requisito, registrado en una auditoría.</li>
<li><strong>Apreciación (appraisal).</strong> Evaluación de procesos contra el CMMI, con calificación y vigencia definida.</li>
<li><strong>PARS.</strong> Sistema donde las organizaciones pueden publicar resultados de apreciación CMMI.</li>
<li><strong>Common Criteria (ISO/IEC 15408).</strong> Esquema internacional de evaluación de seguridad de productos de tecnología.</li>
<li><strong>EAL.</strong> Nivel de garantía de evaluación, del 1 al 7, que mide la profundidad de la evaluación.</li>
<li><strong>Blanco de seguridad y perfil de protección.</strong> Documentos que declaran los reclamos de seguridad de un producto.</li>
<li><strong>CCRA.</strong> Acuerdo de reconocimiento mutuo de certificados Common Criteria entre países.</li>
<li><strong>EUCC.</strong> Esquema europeo de certificación de ciberseguridad basado en Common Criteria.</li>
<li><strong>Certificación de personas.</strong> Certificación de la competencia de un individuo, regida por la ISO/IEC 17024.</li>
<li><strong>ISTQB.</strong> Consejo Internacional de Calificaciones de Pruebas de Software, responsable del esquema Certified Tester.</li>
<li><strong>ICONTEC.</strong> Organismo nacional de normalización de Colombia, que también certifica.</li>
<li><strong>ONAC.</strong> Organismo Nacional de Acreditación de Colombia.</li>
<li><strong>SICAL.</strong> Subsistema Nacional de la Calidad de Colombia.</li>
<li><strong>Global ACI.</strong> Organización internacional de acreditación que asumió los papeles de IAF e ILAC.</li>
<li><strong>IAF CertSearch.</strong> Base de datos global para verificar certificaciones acreditadas.</li>
<li><strong>Dispositivo de desactivación (defeat device).</strong> Software o mecanismo que anula un control de emisiones, prohibido por la Ley de Aire Limpio de Estados Unidos.</li>
<li><strong>EMAS.</strong> Esquema europeo de gestión y auditoría ambiental, alternativo a la ISO 14001 en los informes de Volkswagen.</li>
</ul>
</section>
<section id="bibliografía" class="level2" data-number="18">
<h2 data-number="18" class="anchored" data-anchor-id="bibliografía"><span class="header-section-number">18</span> Bibliografía</h2>
<p>Normas y catálogo de ISO (fichas consultadas el 3 de octubre de 2026):</p>
<ul>
<li>ISO/IEC/IEEE 24765:2017. <em>Systems and software engineering, Vocabulary.</em> <a href="https://www.iso.org/standard/71952.html">Ficha</a>.</li>
<li>ISO 9001:2026. <em>Quality management systems, Requirements.</em> Sexta edición. <a href="https://www.iso.org/standard/88464.html">Ficha</a>. Edición anterior: <a href="https://www.iso.org/standard/62085.html">ISO 9001:2015</a>, retirada.</li>
<li>ISO 9000:2026. <em>Quality management systems, Fundamentals and vocabulary.</em> <a href="https://www.iso.org/standard/88465.html">Ficha</a>.</li>
<li>ISO 14001:2026. <em>Environmental management systems, Requirements with guidance for use.</em> <a href="https://www.iso.org/standard/92300.html">Ficha</a>.</li>
<li>ISO 19011:2026. <em>Guidelines for auditing management systems.</em> <a href="https://www.iso.org/standard/19011">Ficha</a>.</li>
<li>ISO/IEC/IEEE 90003:2018. <em>Software engineering, Guidelines for the application of ISO 9001:2015 to computer software.</em> <a href="https://www.iso.org/standard/74348.html">Ficha</a>.</li>
<li>ISO/IEC 25010:2023. <em>Systems and software engineering, Systems and software Quality Requirements and Evaluation (SQuaRE), Product quality model.</em> <a href="https://www.iso.org/standard/78176.html">Ficha</a>.</li>
<li>ISO/IEC 15408-1:2026, 15408-2:2026 y ISO/IEC 18045:2026. <a href="https://www.iso.org/standard/88134.html">15408-1</a>, <a href="https://www.iso.org/standard/88135.html">15408-2</a>, <a href="https://www.iso.org/standard/88141.html">18045</a>. Ediciones de 2022 en <a href="https://www.iso.org/standard/72891.html">15408-1:2022</a>, retirada.</li>
<li>ISO/IEC 17021-1:2015, <a href="https://www.iso.org/standard/61651.html">ficha</a>; ISO/IEC 17065:2012, <a href="https://www.iso.org/standard/46568.html">ficha</a>; ISO/IEC 17024:2026, <a href="https://www.iso.org/standard/86291.html">ficha</a>; ISO/IEC 17011:2017, <a href="https://www.iso.org/standard/67198.html">ficha</a>. Evaluación de la conformidad.</li>
<li>ISO. <em>International harmonized stage codes.</em> <a href="https://www.iso.org/stage-codes.html">Tabla de códigos</a>. ISO. <a href="https://www.iso.org/deliverables-all.html">Entregables de ISO</a>. ISO. <a href="https://www.iso.org/conformity-assessment.html">Evaluación de la conformidad</a> y <a href="https://www.iso.org/certification.html">certificación</a>. ISO. <a href="https://www.iso.org/the-iso-survey.html">The ISO Survey</a>.</li>
</ul>
<p>Common Criteria y EUCC:</p>
<ul>
<li>Common Criteria Portal. <a href="https://www.commoncriteriaportal.org/cc/index.cfm">CC:2022 Release 1 y CEM:2022</a>. <a href="https://www.commoncriteriaportal.org/files/ccfiles/CC2022CEM2022TransitionPolicy.pdf">Política de transición CC:2022</a>. <em>CC:2022 Parte 5, Pre-defined packages of security assurance components.</em> <a href="https://www.commoncriteriaportal.org/files/ccfiles/CC2022PART5R1.pdf">Documento</a>.</li>
<li>CCRA (2014). <em>Arrangement on the Recognition of Common Criteria Certificates in the Field of Information Technology Security.</em> <a href="https://www.commoncriteriaportal.org/ccra/index.cfm">Documento</a>.</li>
<li>Reglamento de Ejecución (UE) 2024/482 de la Comisión, de 31 de enero de 2024 (EUCC). <a href="https://eur-lex.europa.eu/eli/reg_impl/2024/482/oj/eng">EUR-Lex</a>.</li>
<li>Wikipedia. <a href="https://en.wikipedia.org/wiki/Common_Criteria">Common Criteria</a>. Fuente secundaria usada solo para el ejemplo de Windows XP y Windows Server 2003.</li>
</ul>
<p>Certificación de sistemas, productos y personas:</p>
<ul>
<li>ISTQB. <a href="https://istqb.org/what-we-do/">What we do</a>, <a href="https://istqb.org/who-we-are/">Who we are</a> y <a href="https://istqb.org/certifications/certified-tester-foundation-level-ctfl-v4-0/">CTFL v4.0</a>. Cifras a mayo de 2025.</li>
<li>CMMI Institute (ISACA). <a href="https://cmmiinstitute.com/learning/appraisals/types">Tipos de apreciación</a>, <a href="https://cmmiinstitute.com/learning/appraisals/results">resultados publicados</a> y <a href="https://cmmiinstitute.com/">CMMI</a>.</li>
<li>ICONTEC. <a href="https://www.icontec.org/quienes-somos/">Quiénes somos</a> y <a href="https://www.icontec.org/eval_conformidad/certificacion-de-sistemas-de-gestion/">certificación de sistemas de gestión</a>.</li>
<li>ONAC. <a href="https://onac.org.co/acerca-de-onac/">Acerca de ONAC</a>, <a href="https://onac.org.co/acerca-de-onac/acuerdos-de-reconocimiento-internacional/">acuerdos de reconocimiento internacional</a> y <a href="https://onac.org.co/directorio-de-acreditados/">Directorio Oficial de Acreditados</a>.</li>
<li>Global Accreditation Cooperation Incorporated. Información recogida de <a href="https://www.apac-accreditation.org/global-accreditation-cooperation-incorporated-to-replace-iaf-and-ilac/">APAC</a>, <a href="https://nata.com.au/news/a-milestone-for-global-accreditation-new-leadership-and-a-new-era/">NATA</a> y <a href="https://www.sac-accreditation.gov.sg/sac-maintains-full-recognition-following-global-accreditation-cooperation-incorporated-launch/">SAC</a>, consultada por resúmenes de búsqueda.</li>
</ul>
<p>Caso Volkswagen:</p>
<ul>
<li>EPA. <a href="https://www.epa.gov/vw/learn-about-volkswagen-violations">Learn About Volkswagen Violations</a>. Última actualización: 10 de junio de 2026.</li>
<li>Volkswagen AG (2017). <em>Sustainability Report 2016.</em> <a href="https://www.volkswagen-group.com/en/more-publications-15769">Informe</a>.</li>
<li>Volkswagen AG (2024). <em>Group Sustainability Report 2023.</em> <a href="https://www.volkswagen-group.com/en/more-publications-15769">Informe</a>.</li>
<li>Volkswagen AG (2026). <em>Annual Report 2025.</em> <a href="https://www.volkswagen-group.com/en/more-publications-15769">Informe</a>.</li>
</ul>
<p>Textos de la disciplina:</p>
<ul>
<li>Sommerville, I. (2016). <em>Software Engineering</em> (10.a ed.). Pearson. Capítulos sobre gestión de calidad y estándares.</li>
<li>Pressman, R. S. y Maxim, B. R. (2020). <em>Software Engineering: A Practitioner’s Approach</em> (9.a ed.). McGraw-Hill. Capítulos sobre aseguramiento de la calidad.</li>
<li>Galin, D. (2018). <em>Software Quality: Concepts and Practice.</em> Wiley-IEEE Computer Society Press. Capítulos sobre certificación y estándares.</li>
</ul>
<div class="pie-doc">
<p>Calidad del software (CDS01). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>