<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 1. Del telégrafo al internet de las cosas – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-9d905b06f1e8b96cef5de7dac512495c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../telematica-iot/unidad-01/index.html">Unidad 1. Fundamentos de telecomunicaciones y telemática</a></li><li class="breadcrumb-item"><a href="../../../telematica-iot/unidad-01/tema-01-historia-principios-convergencia/index.html">Tema 1. Del telégrafo al internet de las cosas</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../telematica-iot/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Fundamentos de telecomunicaciones y telemática</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../telematica-iot/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../telematica-iot/unidad-01/tema-01-historia-principios-convergencia/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 1. Del telégrafo al internet de las cosas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../telematica-iot/unidad-01/tema-02-transmision-senales/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Cómo un bit se convierte en señal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../telematica-iot/unidad-01/tema-03-medios-transmision/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. El camino de la señal</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Modelo OSI y arquitectura TCP/IP</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../telematica-iot/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../telematica-iot/unidad-02/tema-01-modelo-osi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. El mapa de siete capas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../telematica-iot/unidad-02/tema-02-arquitectura-tcp-ip/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. El modelo que ya estaba funcionando</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../telematica-iot/unidad-02/tema-03-capa-acceso-ethernet/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. El cartero de la red local</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#telemática-dos-mundos-que-se-juntan" id="toc-telemática-dos-mundos-que-se-juntan" class="nav-link active" data-scroll-target="#telemática-dos-mundos-que-se-juntan"><span class="header-section-number">1</span> Telemática, dos mundos que se juntan</a></li>
  <li><a href="#doscientos-años-resolviendo-el-mismo-problema" id="toc-doscientos-años-resolviendo-el-mismo-problema" class="nav-link" data-scroll-target="#doscientos-años-resolviendo-el-mismo-problema"><span class="header-section-number">2</span> Doscientos años resolviendo el mismo problema</a></li>
  <li><a href="#los-elementos-de-toda-comunicación-el-modelo-de-shannon-y-weaver" id="toc-los-elementos-de-toda-comunicación-el-modelo-de-shannon-y-weaver" class="nav-link" data-scroll-target="#los-elementos-de-toda-comunicación-el-modelo-de-shannon-y-weaver"><span class="header-section-number">3</span> Los elementos de toda comunicación, el modelo de Shannon y Weaver</a></li>
  <li><a href="#dato-y-señal-dos-palabras-que-se-confunden" id="toc-dato-y-señal-dos-palabras-que-se-confunden" class="nav-link" data-scroll-target="#dato-y-señal-dos-palabras-que-se-confunden"><span class="header-section-number">4</span> Dato y señal, dos palabras que se confunden</a></li>
  <li><a href="#cómo-se-organiza-una-red-para-que-el-mensaje-llegue" id="toc-cómo-se-organiza-una-red-para-que-el-mensaje-llegue" class="nav-link" data-scroll-target="#cómo-se-organiza-una-red-para-que-el-mensaje-llegue"><span class="header-section-number">5</span> Cómo se organiza una red para que el mensaje llegue</a></li>
  <li><a href="#cuánto-puede-transportar-un-canal-los-límites-de-nyquist-y-de-shannon" id="toc-cuánto-puede-transportar-un-canal-los-límites-de-nyquist-y-de-shannon" class="nav-link" data-scroll-target="#cuánto-puede-transportar-un-canal-los-límites-de-nyquist-y-de-shannon"><span class="header-section-number">6</span> Cuánto puede transportar un canal, los límites de Nyquist y de Shannon</a></li>
  <li><a href="#convergencia-por-qué-todo-cabe-en-un-solo-cable" id="toc-convergencia-por-qué-todo-cabe-en-un-solo-cable" class="nav-link" data-scroll-target="#convergencia-por-qué-todo-cabe-en-un-solo-cable"><span class="header-section-number">7</span> Convergencia, por qué todo cabe en un solo cable</a></li>
  <li><a href="#cuando-la-convergencia-falla-el-caso-del-voip-y-el-911" id="toc-cuando-la-convergencia-falla-el-caso-del-voip-y-el-911" class="nav-link" data-scroll-target="#cuando-la-convergencia-falla-el-caso-del-voip-y-el-911"><span class="header-section-number">8</span> Cuando la convergencia falla, el caso del VoIP y el 911</a></li>
  <li><a href="#el-recorrido-de-un-dato-de-punta-a-punta" id="toc-el-recorrido-de-un-dato-de-punta-a-punta" class="nav-link" data-scroll-target="#el-recorrido-de-un-dato-de-punta-a-punta"><span class="header-section-number">9</span> El recorrido de un dato, de punta a punta</a></li>
  <li><a href="#una-prueba-de-treinta-segundos" id="toc-una-prueba-de-treinta-segundos" class="nav-link" data-scroll-target="#una-prueba-de-treinta-segundos"><span class="header-section-number">10</span> Una prueba de treinta segundos</a></li>
  <li><a href="#lo-que-te-llevas-de-hoy" id="toc-lo-que-te-llevas-de-hoy" class="nav-link" data-scroll-target="#lo-que-te-llevas-de-hoy"><span class="header-section-number">11</span> Lo que te llevas de hoy</a></li>
  <li><a href="#antes-del-tema-2" id="toc-antes-del-tema-2" class="nav-link" data-scroll-target="#antes-del-tema-2"><span class="header-section-number">12</span> Antes del Tema 2</a></li>
  <li><a href="#recursos" id="toc-recursos" class="nav-link" data-scroll-target="#recursos"><span class="header-section-number">13</span> Recursos</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../telematica-iot/unidad-01/index.html">Unidad 1. Fundamentos de telecomunicaciones y telemática</a></li><li class="breadcrumb-item"><a href="../../../telematica-iot/unidad-01/tema-01-historia-principios-convergencia/index.html">Tema 1. Del telégrafo al internet de las cosas</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 1. Del telégrafo al internet de las cosas</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">17 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 89%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 1. Fundamentos de telecomunicaciones y telemática</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 1. Historia, principios y convergencia de las telecomunicaciones</td>
</tr>
</tbody>
</table>
</div>
<p>La sesión de reconocimiento con la que arrancó este curso dejó tres ideas sueltas, qué es la telemática, qué elementos tiene toda comunicación y por qué las redes convergieron en una sola. Este tema retoma esas tres ideas y las profundiza hasta el nivel que necesitas para el resto de la unidad, con la historia que explica de dónde viene el vocabulario que vas a usar todo el semestre, el modelo formal detrás de la cadena fuente-canal-destino y el marco normativo real que sustenta la convergencia. Cierra preparando el terreno para el Tema 2, donde esa misma cadena se aterriza en señales, codificación y modulación.</p>
<section id="telemática-dos-mundos-que-se-juntan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="telemática-dos-mundos-que-se-juntan"><span class="header-section-number">1</span> Telemática, dos mundos que se juntan</h2>
<p>La palabra viene del francés <em>télématique</em>, que Simon Nora y Alain Minc acuñaron en 1978 como la contracción de <em>telecomunicaciones</em> e <em>informática</em>.</p>
<div class="diagrama">
<svg viewbox="0 0 720 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="La telematica surge del cruce entre las telecomunicaciones y la informatica" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="tiot1a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <rect x="8" y="8" width="215" height="96" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="8" y="146" width="215" height="96" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="285" y="77" width="160" height="96" rx="14" fill="#e4f2f1" stroke="#8fc9c5"></rect> <rect x="500" y="77" width="212" height="96" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <path d="M225,56 C262,56 250,110 281,113" fill="none" stroke="#8fb3d1" stroke-width="2" marker-end="url(#tiot1a)"></path> <path d="M225,194 C262,194 250,140 281,137" fill="none" stroke="#8fb3d1" stroke-width="2" marker-end="url(#tiot1a)"></path> <path d="M447,125 L494,125" fill="none" stroke="#8fb3d1" stroke-width="2" marker-end="url(#tiot1a)"></path> <g text-anchor="middle"> <g font-size="16.5" font-weight="600" fill="#12324f"> <text x="116" y="40">Telecomunicaciones</text> <text x="116" y="178">Informática</text> <text x="606" y="110">Actuar a distancia</text> </g> <g font-size="12.5" fill="#5b6876"> <text x="116" y="62">Llevar una señal de</text> <text x="116" y="80">un punto a otro</text> <text x="116" y="200">Procesar y almacenar</text> <text x="116" y="218">información</text> <text x="606" y="132">sobre información que</text> <text x="606" y="150">está en otro lugar</text> </g> <text x="365" y="131" font-size="17" font-weight="700" fill="#0e6f6c" letter-spacing="1.2">TELEMÁTICA</text> </g>
</svg>
</div>
<p>Un termómetro que muestra la temperatura en su pantalla es informática, sin más. Una radio que transmite voz es telecomunicaciones, sin más. Un sensor que mide la temperatura de un cuarto frío, la envía a un servidor y recibe la orden de encender el compresor combina las dos cosas, así que es telemática, y ese tercer caso es justo el tipo de sistema que vas a construir en la Unidad 4. Para entender bien esa combinación conviene primero saber de dónde viene, porque cada pieza del vocabulario de este curso arrastra casi dos siglos de decisiones concretas.</p>
</section>
<section id="doscientos-años-resolviendo-el-mismo-problema" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="doscientos-años-resolviendo-el-mismo-problema"><span class="header-section-number">2</span> Doscientos años resolviendo el mismo problema</h2>
<p>Entre el primer telégrafo y un sensor de humedad conectado a internet hay casi dos siglos, y el problema de fondo nunca cambió, ya que siempre hubo que convertir información en una señal, mandarla por un medio imperfecto y recuperarla al otro lado con el menor daño posible. Repasar cómo se fue resolviendo ese problema explica por qué existen instituciones como la UIT, por qué se habla de conmutación de paquetes y por qué la fibra óptica tardó casi un siglo entero en volverse práctica.</p>
<div class="diagrama">
<svg viewbox="0 0 760 172" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Linea de tiempo con cinco hitos: 1844 telegrafo, 1865 nace la UIT, 1932 fusion y nombre UIT, 1969 ARPANET y 1970 fibra optica viable" font-family="Segoe UI, Inter, system-ui, sans-serif">
<g fill="#f5f7fa" stroke="#cfd8e3"> <rect x="9" y="12" width="142" height="84" rx="9"></rect> <rect x="159" y="12" width="142" height="84" rx="9"></rect> <rect x="309" y="12" width="142" height="84" rx="9"></rect> <rect x="459" y="12" width="142" height="84" rx="9"></rect> <rect x="609" y="12" width="142" height="84" rx="9"></rect> </g> <g stroke="#c7d6e6" stroke-width="2"> <path d="M80,96 L80,118"></path> <path d="M230,96 L230,118"></path> <path d="M380,96 L380,118"></path> <path d="M530,96 L530,118"></path> <path d="M680,96 L680,118"></path> </g> <path d="M50,122 L710,122" stroke="#c7d6e6" stroke-width="2"></path> <g fill="#0e6f6c" stroke="#ffffff" stroke-width="3"> <circle cx="80" cy="122" r="6.5"></circle> <circle cx="230" cy="122" r="6.5"></circle> <circle cx="380" cy="122" r="6.5"></circle> <circle cx="530" cy="122" r="6.5"></circle> <circle cx="680" cy="122" r="6.5"></circle> </g> <g text-anchor="middle"> <g font-size="13.5" font-weight="600" fill="#12324f"> <text x="80" y="42">Telégrafo</text> <text x="230" y="42">Nace la UIT</text> <text x="380" y="42">Fusión y nombre</text> <text x="530" y="42">ARPANET</text> <text x="680" y="42">Fibra óptica viable</text> </g> <g font-size="11" fill="#5b6876"> <text x="80" y="64">Morse conecta</text> <text x="80" y="80">Washington y Baltimore</text> <text x="230" y="64">20 países firman el</text> <text x="230" y="80">Convenio de París</text> <text x="380" y="64">Telégrafo y radio se</text> <text x="380" y="80">unen en Madrid</text> <text x="530" y="64">Primer mensaje por</text> <text x="530" y="80">conmutación de paquetes</text> <text x="680" y="64">Kao y Hockham bajan</text> <text x="680" y="80">la atenuación teórica</text> </g> <g font-size="15" font-weight="700" fill="#0e6f6c"> <text x="80" y="152">1844</text> <text x="230" y="152">1865</text> <text x="380" y="152">1932</text> <text x="530" y="152">1969</text> <text x="680" y="152">1970</text> </g> </g>
</svg>
</div>
<p>El 24 de mayo de 1844, Samuel Morse envió el mensaje “What hath God wrought” entre Washington D.C. y Baltimore, unos 60 kilómetros, usando el código que lleva su nombre sobre una línea de hilo de cobre. Es una cita bíblica que en español significa “Mira lo que ha hecho Dios”, y Morse la eligió porque quería un mensaje a la altura de lo que ese primer telégrafo significaba, la posibilidad de que una idea humana viajara más rápido de lo que podía viajar cualquier persona o caballo. La prensa y los ferrocarriles fueron los primeros en adoptar el telégrafo, porque necesitaban coordinar horarios y noticias más rápido de lo que viajaba una persona a caballo. Esa adopción masiva y transnacional trajo un problema nuevo, ya que las redes telegráficas de distintos países necesitaban hablar entre sí, y la solución fue diplomática antes que técnica, así que veinte países fundadores firmaron en París, el 17 de mayo de 1865, el primer Convenio Telegráfico Internacional. Ese acto es el nacimiento de lo que hoy es la Unión Internacional de Telecomunicaciones, la UIT, la organización internacional más antigua dedicada a regular tecnología, y esa misma fecha se conmemora cada año como el Día Mundial de las Telecomunicaciones y la Sociedad de la Información.</p>
<p>La telefonía llegó después y obligó a la misma unión a estirarse. La patente del teléfono, en 1876, se atribuye a Alexander Graham Bell, aunque la disputa con Elisha Gray por quién llegó primero sigue documentada en los archivos de patentes de la época. Para 1885, en la Conferencia de Berlín, la Unión Telegráfica ya había extendido su regulación a la telefonía, porque el problema de interoperar entre redes nacionales era exactamente el mismo que con el telégrafo, solo que con una señal distinta. En paralelo, Guglielmo Marconi desarrollaba la radiotelegrafía inalámbrica, cuya patente solicitó en 1896 y le fue concedida al año siguiente, y cuya utilidad para la comunicación marítima, donde tender un cable no es una opción, motivó una Conferencia Preliminar sobre Telegrafía sin Hilos en Berlín en 1903 y, en 1906, la creación de una Unión Radiotelegráfica Internacional independiente de la telegráfica.</p>
<p>Durante casi tres décadas hubo entonces dos uniones internacionales paralelas, una para cable y otra para radio, hasta que la conferencia radiotelegráfica de 1932 en Madrid las fusionó en una sola organización y adoptó el nombre que usamos hoy, Unión Internacional de Telecomunicaciones. Fue en esa misma fusión donde el término <em>telecomunicación</em> se definió por primera vez de forma unificada, cubriendo ya no solo el telégrafo o el teléfono por separado, sino cualquier transmisión de información a distancia por medios eléctricos. El acuerdo institucional llegó, en otras palabras, casi un siglo después del primer telégrafo, y solo porque la tecnología ya lo exigía.</p>
<p>La segunda gran ruptura llegó con la era digital. En los años sesenta, dos grupos de investigación que no se conocían entre sí, uno en la corporación RAND, con Paul Baran, y otro en el National Physical Laboratory británico, con Donald Davies, desarrollaron por separado la misma idea, que consistía en dividir la información en fragmentos pequeños que viajan de forma independiente por la red en vez de reservar una línea completa para cada comunicación. Davies fue quien le puso nombre a esa idea, conmutación de paquetes, y Leonard Kleinrock aportó la teoría matemática de colas que explicaba por qué ese esquema podía funcionar sin colapsar la red. El resultado práctico fue ARPANET, y el 29 de octubre de 1969 se transmitió el primer mensaje entre la Universidad de California en Los Ángeles y el Stanford Research Institute. Se pretendía enviar la palabra “LOGIN” (que en español significa “iniciar sesión”), pero el sistema colapsó justo después de transmitir las dos primeras letras, así que el primer mensaje de la red que dio origen a internet fue, literalmente, “LO”.</p>
<p>El último hito de este recorrido tiene que ver con el medio, no con el protocolo. En 1966, Charles K. Kao, investigador de Standard Telecommunications Laboratories en el Reino Unido, junto con George Hockham, demostró en teoría que la atenuación de la fibra óptica podía reducirse por debajo de 20 decibeles por kilómetro, un umbral que hasta entonces parecía inalcanzable y que hacía viable la fibra como medio de telecomunicaciones a gran distancia. El primer cable de fibra óptica práctico se fabricó en 1970, y ese avance teórico le valió a Kao la mitad del Premio Nobel de Física de 2009, reconocido como uno de los responsables de que hoy la fibra óptica lleve la mayor parte del tráfico de internet del planeta. La Unidad 1 vuelve sobre este mismo medio en el Tema 3, cuando compares fibra óptica con cobre y con radio.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Verdadero o falso, la historia que casi todos cuentan mal
</div>
</div>
<div class="callout-body-container callout-body">
<p>Antes de revisar la solución, marca qué afirmaciones crees que son verdaderas según lo que acabas de leer.</p>
<p><label><input type="checkbox"> El teléfono se inventó antes que el telégrafo.</label> <label><input type="checkbox"> El primer mensaje de ARPANET se transmitió completo, sin ningún fallo.</label> <label><input type="checkbox"> La Unión Internacional de Telecomunicaciones existía, con otro nombre, antes de que se patentara el teléfono.</label> <label><input type="checkbox"> La fibra óptica se volvió viable para telecomunicaciones gracias a un avance teórico sobre la atenuación de la luz, no a un invento repentino.</label></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>Falso.</strong> El telégrafo es de 1844 y la patente del teléfono es de 1876, así que el telégrafo lleva más de tres décadas de ventaja.</li>
<li><strong>Falso.</strong> El plan era transmitir “LOGIN”, pero el sistema colapsó después de la “L” y la “O”, así que el primer mensaje real de ARPANET quedó en “LO”.</li>
<li><strong>Verdadero.</strong> El Convenio Telegráfico Internacional de 1865, antecedente directo de la UIT, es once años anterior a la patente del teléfono de 1876.</li>
<li><strong>Verdadero.</strong> Kao y Hockham publicaron en 1966 el resultado teórico sobre atenuación por debajo de 20 dB/km que hizo pensable la fibra como medio de telecomunicaciones; el primer cable práctico llegó cuatro años después, en 1970, una vez que la teoría mostró que el problema tenía solución.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="los-elementos-de-toda-comunicación-el-modelo-de-shannon-y-weaver" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="los-elementos-de-toda-comunicación-el-modelo-de-shannon-y-weaver"><span class="header-section-number">3</span> Los elementos de toda comunicación, el modelo de Shannon y Weaver</h2>
<p>Da igual si hablamos de un telégrafo de 1844 o de un sensor con wifi, porque los elementos que intervienen en cualquier comunicación son los mismos, y el primero en formalizarlos con precisión matemática fue Claude E. Shannon, en su artículo “A Mathematical Theory of Communication”, publicado en 1948 en el Bell System Technical Journal. Ese modelo, que la literatura del área conoce como modelo de Shannon y Weaver, sigue siendo la referencia académica estándar para explicar cómo se arma la comunicación entre dos dispositivos, y es literalmente uno de los resultados de aprendizaje de esta unidad.</p>
<div class="diagrama">
<svg viewbox="0 0 760 215" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cadena de fuente, transmisor, canal, receptor y destino, con el ruido entrando al canal" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="tiot1b" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <g fill="#eef4fa" stroke="#c7d6e6"> <rect x="5" y="28" width="130" height="104" rx="10"></rect> <rect x="160" y="28" width="130" height="104" rx="10"></rect> <rect x="470" y="28" width="130" height="104" rx="10"></rect> <rect x="625" y="28" width="130" height="104" rx="10"></rect> </g> <rect x="315" y="28" width="130" height="104" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g fill="none" stroke="#8fb3d1" stroke-width="2" marker-end="url(#tiot1b)"> <path d="M137,80 L155,80"></path> <path d="M292,80 L310,80"></path> <path d="M447,80 L465,80"></path> <path d="M602,80 L620,80"></path> </g> <path d="M380,168 L380,138" fill="none" stroke="#8fb3d1" stroke-width="2" stroke-dasharray="5 4" marker-end="url(#tiot1b)"></path> <rect x="330" y="169" width="100" height="32" rx="16" fill="#f5f7fa" stroke="#cfd8e3"></rect> <g text-anchor="middle"> <g font-size="15" font-weight="600" fill="#12324f"> <text x="70" y="62">Fuente</text> <text x="225" y="62">Transmisor</text> <text x="380" y="62">Canal</text> <text x="535" y="62">Receptor</text> <text x="690" y="62">Destino</text> </g> <g font-size="11.5" fill="#5b6876"> <text x="70" y="86">genera el</text> <text x="70" y="103">mensaje</text> <text x="225" y="86">codifica el mensaje</text> <text x="225" y="103">en una señal</text> <text x="380" y="86">par, fibra</text> <text x="380" y="103">o aire</text> <text x="535" y="86">decodifica la señal</text> <text x="535" y="103">y recupera el mensaje</text> <text x="690" y="86">consume la</text> <text x="690" y="103">información</text> </g> <text x="380" y="190" font-size="12.5" font-weight="600" fill="#12324f" letter-spacing="0.6">RUIDO</text> </g>
</svg>
</div>
<p>La fuente genera el mensaje, un transmisor o codificador lo convierte en una señal apta para el medio, como haría un modulador o un conversor analógico a digital, el canal es el medio físico por el que viaja esa señal, ya sea un par de cobre, una fibra o el aire, un receptor o decodificador invierte esa codificación para recuperar el mensaje, y el destino es quien finalmente consume la información. El elemento que más sorprende a quien ve este modelo por primera vez es el ruido, que Shannon modela como una fuente de perturbación independiente que se mete en el canal y degrada la señal sin que nadie se lo pida, y que explica por qué a veces llega algo distinto de lo que se envió.</p>
<p>Los libros de comunicaciones de datos que usa este curso, en la línea de Forouzan y de Stallings, refinan ese esquema general para sistemas digitales concretos, encadenando más pasos entre la fuente y el destino, fuente, codificador de fuente, que comprime o digitaliza el mensaje, codificador de canal, que le añade redundancia para poder detectar o corregir errores más adelante, modulador, canal, demodulador, decodificador de canal, decodificador de fuente y destino. Esa cadena más larga es exactamente el puente hacia el Tema 2, porque ahí vas a estudiar en detalle qué significa codificar en banda base y qué significa modular en paso banda, dos pasos que en este modelo aparecen todavía como cajas negras.</p>
</section>
<section id="dato-y-señal-dos-palabras-que-se-confunden" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="dato-y-señal-dos-palabras-que-se-confunden"><span class="header-section-number">4</span> Dato y señal, dos palabras que se confunden</h2>
<p>Antes de seguir conviene separar dos palabras que se usan como sinónimos fuera de este curso y que aquí significan cosas distintas.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Término</th>
<th>Qué representa</th>
<th>Ejemplo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Dato</strong></td>
<td>La información en sí misma</td>
<td>El número 23.4</td>
</tr>
<tr class="even">
<td><strong>Señal</strong></td>
<td>El fenómeno físico que representa al dato mientras viaja por el canal</td>
<td>Un voltaje en un cable, un pulso de luz en una fibra, una onda de radio</td>
</tr>
</tbody>
</table>
<p>El dato no viaja, viaja la señal que lo representa, y esa distinción es la que hace posible que el mismo dato, el número 23.4, se transporte igual de bien por cobre, por fibra o por el aire, cambiando solo la forma física de la señal, nunca la información que carga. El ruido del diagrama anterior entra siempre por el lado de la señal, nunca por el del dato, porque lo que se degrada en el canal es el fenómeno físico, no el número que ese fenómeno intenta representar.</p>
</section>
<section id="cómo-se-organiza-una-red-para-que-el-mensaje-llegue" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="cómo-se-organiza-una-red-para-que-el-mensaje-llegue"><span class="header-section-number">5</span> Cómo se organiza una red para que el mensaje llegue</h2>
<p>El modelo de Shannon describe una comunicación entre dos puntos, pero una red conecta a muchos más que dos, y ahí aparecen dos decisiones de arquitectura que Kurose y Ross, en el primer capítulo de su libro de referencia sobre redes de computadores, presentan como estructurales, cómo se reparte el enlace entre comunicaciones que compiten por él y cómo se organiza el software que hace posible esa comunicación.</p>
<p>La primera decisión es entre conmutación de circuitos y conmutación de paquetes. En circuitos, que es el modelo con el que nació la telefonía clásica, los recursos de un enlace se reservan de forma exclusiva durante toda la sesión, aunque nadie esté hablando en un instante dado. En paquetes, que es la idea que Baran y Davies desarrollaron en los años sesenta, el mensaje se fragmenta en piezas pequeñas que usan los recursos del enlace solo bajo demanda, compitiendo por el acceso con las piezas de otras comunicaciones y encolándose cuando el enlace está ocupado.</p>
<div class="diagrama">
<svg viewbox="0 0 760 258" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Comparacion entre conmutacion de circuitos, con un enlace reservado de extremo a extremo, y conmutacion de paquetes, donde los paquetes comparten la red y pueden esperar en cola" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="tiot1d" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <text x="185" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Conmutación de circuitos</text> <text x="575" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Conmutación de paquetes</text> <rect x="20" y="34" width="90" height="56" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="260" y="34" width="90" height="56" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <path d="M114,62 L256,62" stroke="#0e6f6c" stroke-width="5"></path> <text x="185" y="54" font-size="11.5" fill="#0e6f6c" text-anchor="middle">enlace reservado</text> <text x="185" y="112" font-size="11.5" fill="#5b6876" text-anchor="middle">el circuito queda ocupado toda la llamada,</text> <text x="185" y="128" font-size="11.5" fill="#5b6876" text-anchor="middle">aunque nadie hable en ese instante</text> <g text-anchor="middle" font-size="13" font-weight="600" fill="#12324f"> <text x="65" y="66">A</text> <text x="305" y="66">B</text> </g> <rect x="410" y="34" width="80" height="56" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="650" y="34" width="80" height="56" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="530" y="24" width="90" height="76" rx="38" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="575" y="58" font-size="11" fill="#5b6876" text-anchor="middle">red</text> <text x="575" y="72" font-size="11" fill="#5b6876" text-anchor="middle">compartida</text> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#tiot1d)"> <path d="M492,50 L526,44"></path> <path d="M492,62 L526,62"></path> <path d="M492,74 L526,80"></path> <path d="M622,50 L648,50"></path> <path d="M622,70 L648,70"></path> </g> <g text-anchor="middle" font-size="13" font-weight="600" fill="#12324f"> <text x="450" y="66">A</text> <text x="690" y="66">B</text> </g> <text x="575" y="112" font-size="11.5" fill="#5b6876" text-anchor="middle">cada paquete compite por el enlace</text> <text x="575" y="128" font-size="11.5" fill="#5b6876" text-anchor="middle">y puede esperar en una cola</text> <rect x="30" y="150" width="700" height="90" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="174" font-size="12.5" font-weight="600" fill="#0e6f6c" text-anchor="middle">Por qué importa para IoT</text> <text x="380" y="196" font-size="11.5" fill="#12324f" text-anchor="middle">Un circuito dedicado por cada sensor sería carísimo e imposible de escalar a</text> <text x="380" y="214" font-size="11.5" fill="#12324f" text-anchor="middle">miles de dispositivos. Los paquetes dejan que todos compartan la misma red.</text>
</svg>
</div>
<p>La segunda decisión es la estratificación en capas de protocolo, es decir, la idea de que cada capa del software de red le ofrece un servicio a la capa que tiene encima, escondiéndole los detalles de cómo lo implementa por dentro. Gracias a esa separación, la aplicación que muestra la temperatura de tu sensor en el celular no necesita saber si el dato viajó por wifi, por cable o por una red celular, porque esa capa inferior queda oculta detrás de un contrato estable. Es la misma arquitectura por capas la que hizo posible que voz, video y datos terminaran compartiendo la misma infraestructura de red basada en el Protocolo de Internet, IP, sin que cada aplicación tuviera que conocer el medio físico subyacente, y ese punto es exactamente el que retoma la sección de convergencia más abajo.</p>
</section>
<section id="cuánto-puede-transportar-un-canal-los-límites-de-nyquist-y-de-shannon" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="cuánto-puede-transportar-un-canal-los-límites-de-nyquist-y-de-shannon"><span class="header-section-number">6</span> Cuánto puede transportar un canal, los límites de Nyquist y de Shannon</h2>
<p>Toda la cadena de la sección anterior tiene un límite físico, porque ningún canal transporta bits sin importar qué tan bueno sea el equipo en los dos extremos. Ese límite se formaliza con dos teoremas que vas a usar todo el semestre, y que aquí solo se presentan a nivel introductorio porque el Tema 2 los retoma con profundidad al hablar de ancho de banda y de modulación.</p>
<div class="diagrama">
<svg viewbox="0 0 760 230" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="El ancho de banda B y la relacion senal ruido SNR entran a un canal y determinan su capacidad maxima C en bits por segundo, segun los teoremas de Nyquist y de Shannon Hartley" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="tiot1e" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <rect x="20" y="18" width="170" height="46" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="20" y="80" width="170" height="46" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="300" y="42" width="160" height="80" rx="12" fill="#e4f2f1" stroke="#8fc9c5"></rect> <rect x="560" y="42" width="180" height="80" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <g fill="none" stroke="#8fb3d1" stroke-width="2" marker-end="url(#tiot1e)"> <path d="M192,41 C240,41 250,70 296,74"></path> <path d="M192,103 C240,103 250,90 296,88"></path> <path d="M462,82 L556,82"></path> </g> <g text-anchor="middle"> <g font-size="12.5" font-weight="600" fill="#12324f"> <text x="105" y="46">Ancho de banda</text> <text x="105" y="108">Relación señal-ruido</text> <text x="380" y="76">Canal</text> <text x="650" y="76">Capacidad máxima</text> </g> <g font-size="12" fill="#5b6876"> <text x="105" y="62">B, en Hz</text> <text x="105" y="124">SNR</text> <text x="650" y="96">C, en bits/s</text> </g> </g> <rect x="30" y="150" width="330" height="66" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <rect x="400" y="150" width="330" height="66" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="195" y="170" font-size="12" font-weight="600" fill="#12324f" text-anchor="middle">Nyquist, canal ideal sin ruido</text> <text x="195" y="190" font-size="12.5" fill="#0e6f6c" text-anchor="middle">C = 2 B log2(n)</text> <text x="195" y="206" font-size="10.5" fill="#5b6876" text-anchor="middle">n = niveles discretos de señal</text> <text x="565" y="170" font-size="12" font-weight="600" fill="#12324f" text-anchor="middle">Shannon-Hartley, canal real con ruido</text> <text x="565" y="190" font-size="12.5" fill="#0e6f6c" text-anchor="middle">C = B log2(1 + SNR)</text> <text x="565" y="206" font-size="10.5" fill="#5b6876" text-anchor="middle">límite físico, ningún esquema real lo alcanza</text>
</svg>
</div>
<p>El teorema de Nyquist describe un canal ideal, sin ruido, y dice que su capacidad máxima es C = 2 B log2(n), donde B es el ancho de banda del canal en hercios y n es la cantidad de niveles discretos que puede tomar la señal. El teorema de Shannon-Hartley, en cambio, describe un canal real, con ruido, y dice que su capacidad máxima es C = B log2(1 + SNR), donde SNR es la relación entre la potencia de la señal y la potencia del ruido. Este segundo teorema es el límite físico infranqueable de cualquier canal ruidoso de ancho de banda B, así que ningún esquema de modulación real logra alcanzarlo, apenas se le puede acercar.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Los dos límites de un mismo canal
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una línea telefónica análoga clásica tiene un ancho de banda aproximado de B = 3000 Hz, entre 300 Hz y 3300 Hz, el rango que basta para transportar la voz humana con claridad, y una relación señal-ruido típica de SNR = 1000, equivalente a unos 30 decibeles.</p>
<p>Calcula dos cosas y compáralas.</p>
<ol type="1">
<li>La capacidad según Nyquist si la línea transmite en binario puro, es decir con n = 2 niveles de señal.</li>
<li>La capacidad según Shannon-Hartley con esa misma línea, redondeando log2(1001) a 10 si te ayuda.</li>
</ol>
<p>Después responde en un párrafo, si los dos resultados no coinciden, ¿cuál de los dos describe mejor el límite real de esa línea, y por qué la diferencia no significa que uno de los dos teoremas esté equivocado?</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Con Nyquist y n = 2, C = 2 x 3000 x log2(2) = 2 x 3000 x 1 = 6000 bits por segundo.</p>
<p>Con Shannon-Hartley, C = 3000 x log2(1 + 1000) = 3000 x log2(1001), y log2(1001) es aproximadamente 10, así que C es aproximadamente 3000 x 10 = 30 000 bits por segundo.</p>
<p>Los dos teoremas no compiten entre sí, responden preguntas distintas. Nyquist calcula la capacidad para un número de niveles de señal que tú eliges de antemano, así que 6000 bits por segundo es el límite solo si te quedas en binario puro, con dos niveles. Shannon-Hartley, en cambio, calcula el límite absoluto sobre todos los esquemas de codificación posibles para ese ancho de banda y ese ruido, sin fijar de antemano cuántos niveles usa la señal. La brecha entre los dos números es justamente el espacio que ocupan los esquemas de modulación que el Tema 2 va a estudiar, como ASK, FSK y PSK, que codifican más de un bit por símbolo transmitido y por eso se acercan más al techo de Shannon-Hartley que el binario puro de Nyquist.</p>
</div>
</div>
</div>
</section>
<section id="convergencia-por-qué-todo-cabe-en-un-solo-cable" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="convergencia-por-qué-todo-cabe-en-un-solo-cable"><span class="header-section-number">7</span> Convergencia, por qué todo cabe en un solo cable</h2>
<p>Hasta los años noventa cada servicio tenía su propia red, una para telefonía, otra para televisión y otra para datos. Hoy los tres viajan por la misma red de paquetes basada en IP, y ese cambio no ocurrió solo, tiene un nombre técnico y un respaldo normativo concreto.</p>
<div class="diagrama">
<svg viewbox="0 0 760 240" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Telefonia, television y datos convergen en una sola red de paquetes IP" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="tiot1f" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <g fill="#eef4fa" stroke="#c7d6e6"> <rect x="8" y="18" width="175" height="58" rx="10"></rect> <rect x="8" y="91" width="175" height="58" rx="10"></rect> <rect x="8" y="164" width="175" height="58" rx="10"></rect> </g> <rect x="280" y="72" width="190" height="96" rx="12" fill="#e4f2f1" stroke="#8fc9c5"></rect> <rect x="540" y="72" width="212" height="96" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <g fill="none" stroke="#8fb3d1" stroke-width="2" marker-end="url(#tiot1f)"> <path d="M185,47 C230,47 232,100 276,104"></path> <path d="M185,120 L276,120"></path> <path d="M185,193 C230,193 232,140 276,136"></path> <path d="M472,120 L536,120"></path> </g> <g text-anchor="middle"> <g font-size="15" font-weight="600" fill="#12324f"> <text x="95.5" y="53">Telefonía</text> <text x="95.5" y="126">Televisión</text> <text x="95.5" y="199">Datos</text> </g> <text x="375" y="113" font-size="15.5" font-weight="700" fill="#0e6f6c" letter-spacing="0.8">UNA SOLA RED</text> <text x="375" y="136" font-size="13" fill="#5b6876">de paquetes IP</text> <g font-size="13.5" fill="#5b6876"> <text x="646" y="105">Internet, televisión</text> <text x="646" y="125">y teléfono por</text> <text x="646" y="145">el mismo cable</text> </g> </g>
</svg>
</div>
<p>La recomendación ITU-T Y.2001, publicada por la UIT en diciembre de 2004 bajo el título “General overview of NGN” (en español, “Panorama general de las NGN”), formaliza este cambio con el concepto de red de próxima generación, NGN por sus siglas en inglés. La recomendación la define como una red basada en paquetes, capaz de proveer servicios de telecomunicación a los usuarios y de aprovechar múltiples tecnologías de transporte de banda ancha con calidad de servicio, en la que las funciones relacionadas con el servicio quedan independientes de la tecnología de transporte que hay por debajo. La propia recomendación establece de forma explícita que uno de los objetivos mayores de la NGN es facilitar tanto la convergencia de redes como la convergencia de servicios, y entre las características que enumera incluye los servicios convergentes entre redes fijas y móviles, sin que la recomendación llegue a acuñar una sigla propia para esa idea.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Servicio</th>
<th>Antes</th>
<th>Ahora</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Telefonía</td>
<td>Red de circuitos, un canal dedicado por llamada</td>
<td>La voz se digitaliza y viaja en paquetes, VoIP</td>
</tr>
<tr class="even">
<td>Televisión</td>
<td>Difusión analógica por aire o coaxial</td>
<td>Video sobre IP y bajo demanda, IPTV</td>
</tr>
<tr class="odd">
<td>Datos</td>
<td>Red de datos aparte</td>
<td>La misma red que las dos anteriores</td>
</tr>
</tbody>
</table>
<p>La manifestación comercial de esta convergencia es lo que se conoce como triple play, un paquete que combina acceso a internet, telefonía por VoIP y televisión por IPTV sobre una misma conexión de acceso, típicamente xDSL, cable-módem o una red óptica pasiva de las que la propia UIT normó, primero la familia G.983 para BPON y después la familia G.984 para GPON. Ese empaquetamiento comercial fue la fuerza que obligó a los operadores tradicionales de voz y a los operadores de cable a competir directamente entre sí, y terminó erosionando el modelo de negocio de la telefonía conmutada tradicional, la PSTN, mientras el tráfico se desplazaba hacia redes de transporte convergentes basadas en MPLS y Ethernet. Para el IoT la consecuencia es directa, un dispositivo nuevo no necesita levantar una red propia, solo se conecta a la que ya existe.</p>
</section>
<section id="cuando-la-convergencia-falla-el-caso-del-voip-y-el-911" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="cuando-la-convergencia-falla-el-caso-del-voip-y-el-911"><span class="header-section-number">8</span> Cuando la convergencia falla, el caso del VoIP y el 911</h2>
<p>Compartir infraestructura trae ventajas de costo, pero también significa heredar los puntos de falla de esa infraestructura compartida, y hay un ejemplo real y bien documentado de eso.</p>
<p>Considera el caso de un hogar que reemplaza su teléfono fijo tradicional por un servicio de VoIP que corre sobre la misma conexión de internet que usa para navegar, y que además sufre un corte de energía eléctrica en el barrio. A partir de esa situación conviene preguntarse si el servicio de telefonía de ese hogar sigue funcionando durante el corte eléctrico, igual que funcionaba el teléfono fijo de antes, y qué explica la diferencia si la respuesta es que no.</p>
<p>La respuesta, documentada por la Comisión Federal de Comunicaciones de Estados Unidos, la FCC, es que no, y la razón es estructural, no un descuido puntual de un operador. La telefonía fija tradicional recibe su propia energía desde la central telefónica a través del mismo par de cobre, así que sigue funcionando aunque se corte la luz de la casa. El servicio VoIP, en cambio, depende de routers, módems y adaptadores que se alimentan de la red eléctrica del usuario, así que si se corta la energía o falla la conexión a internet, el servicio deja de funcionar por completo, incluidas las llamadas a servicios de emergencia. La FCC documentó además casos donde llamadas VoIP al 911 no lograron enrutarse al centro de despacho correcto según la ubicación real de quien llamaba, porque un número IP no está atado geográficamente como un número de línea fija tradicional, o no lograron transmitir de forma automática el número y la ubicación de quien llamaba. Una serie de incidentes ampliamente documentados por la propia FCC llevó a que, en 2005, emitiera una orden obligando a los proveedores de VoIP interconectado a ofrecer el servicio de emergencias mejorado, conocido como E911, como característica estándar y obligatoria, y a obtener del cliente un reconocimiento explícito de las limitaciones del servicio.</p>
<p>La lección para este curso no es que el VoIP sea una mala idea, porque claramente no lo es, sino que converger sobre una sola red significa que un fallo de esa red, un corte eléctrico, una caída de internet, ya no afecta solo a un servicio, afecta a todos los que dependen de ella al mismo tiempo. La red telefónica conmutada tradicional, diseñada para un único propósito, no sufría ese problema concreto, y esa es precisamente la clase de compromiso que vas a evaluar cada vez que diseñes un sistema IoT que dependa de una sola red compartida para funciones críticas.</p>
</section>
<section id="el-recorrido-de-un-dato-de-punta-a-punta" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="el-recorrido-de-un-dato-de-punta-a-punta"><span class="header-section-number">9</span> El recorrido de un dato, de punta a punta</h2>
<p>Vuelve ahora al ejemplo que vas a desarmar durante todo el semestre, un sensor de temperatura que termina mostrando un número en tu celular, y ubica en él todo lo que acabas de leer.</p>
<div class="diagrama">
<svg viewbox="0 0 760 160" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Recorrido del dato desde el sensor hasta el celular pasando por el router, internet y un servidor" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="tiot1g" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <g fill="#eef4fa" stroke="#c7d6e6"> <rect x="5" y="28" width="130" height="88" rx="10"></rect> <rect x="160" y="28" width="130" height="88" rx="10"></rect> <rect x="470" y="28" width="130" height="88" rx="10"></rect> <rect x="625" y="28" width="130" height="88" rx="10"></rect> </g> <rect x="315" y="28" width="130" height="88" rx="44" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g fill="none" stroke="#8fb3d1" stroke-width="2" marker-end="url(#tiot1g)"> <path d="M137,72 L155,72"></path> <path d="M292,72 L310,72"></path> <path d="M447,72 L465,72"></path> <path d="M602,72 L620,72"></path> </g> <g text-anchor="middle" font-size="14.5" font-weight="600" fill="#12324f"> <text x="70" y="66">Sensor de</text> <text x="70" y="86">temperatura</text> <text x="225" y="66">Router o</text> <text x="225" y="86">gateway</text> <text x="380" y="78" fill="#0e6f6c" letter-spacing="0.8">INTERNET</text> <text x="535" y="66">Servidor</text> <text x="535" y="86">en la nube</text> <text x="690" y="78">Tu celular</text> </g>
</svg>
</div>
<p>Cada tramo de ese camino queda ahora anclado a una idea concreta de este tema, y cada uno se convierte además en una unidad distinta del curso.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Tramo</th>
<th>Qué resuelve</th>
<th>Dónde lo viste hoy</th>
<th style="text-align: center;">Unidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Del sensor al cable o al aire</td>
<td>Cómo se convierte una medida en una señal que viaja</td>
<td>Modelo de Shannon, dato y señal</td>
<td style="text-align: center;">U1</td>
</tr>
<tr class="even">
<td>Del cable al router</td>
<td>Con qué reglas se ponen de acuerdo dos equipos</td>
<td>Circuitos, paquetes y capas</td>
<td style="text-align: center;">U2</td>
</tr>
<tr class="odd">
<td>Del router a internet</td>
<td>Qué dirección tiene cada equipo y cómo se decide el camino</td>
<td>Convergencia sobre una sola red IP</td>
<td style="text-align: center;">U3</td>
</tr>
<tr class="even">
<td>Del servidor a tu celular</td>
<td>Cómo se arma la solución completa</td>
<td>El caso del VoIP y el 911</td>
<td style="text-align: center;">U4</td>
</tr>
</tbody>
</table>
<p>Un dispositivo IoT real no inventa una red propia para ese recorrido, usa exactamente la misma infraestructura convergente de la que hablaste arriba, con las mismas ventajas de costo y los mismos riesgos si esa infraestructura falla.</p>
</section>
<section id="una-prueba-de-treinta-segundos" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="una-prueba-de-treinta-segundos"><span class="header-section-number">10</span> Una prueba de treinta segundos</h2>
<p>Antes de cerrar, mide un tramo real de ese camino. Abre una terminal, en Windows con <code>Win+R</code>, escribiendo <code>cmd</code> y presionando Enter, o la aplicación Terminal en macOS y Linux.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode powershell code-with-copy"><code class="sourceCode powershell"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>ping <span class="op">-</span>n <span class="dv">4</span> <span class="dv">8.8</span><span class="op">.</span><span class="dv">8.8</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<p>El <code>-n 4</code> pide cuatro intentos. En macOS y Linux el parámetro equivalente es <code>-c</code>, así que el comando queda <code>ping -c 4 8.8.8.8</code>, y sin ese parámetro el comando no se detiene solo en esos sistemas, toca cortarlo con <code>Ctrl+C</code>.</p>
<p>Salida real en el equipo donde preparé esta guía, el resultado varía según el equipo y la red desde donde lo ejecutes:</p>
<pre class="text"><code>Haciendo ping a 8.8.8.8 con 32 bytes de datos:
Respuesta desde 8.8.8.8: bytes=32 tiempo=14ms TTL=118
Respuesta desde 8.8.8.8: bytes=32 tiempo=15ms TTL=118
Respuesta desde 8.8.8.8: bytes=32 tiempo=15ms TTL=118
Respuesta desde 8.8.8.8: bytes=32 tiempo=14ms TTL=118

Estadísticas de ping para 8.8.8.8:
    Paquetes: enviados = 4, recibidos = 4, perdidos = 0
    (0% perdidos),
Tiempos aproximados de ida y vuelta en milisegundos:
    Mínimo = 14ms, Máximo = 15ms, Media = 14ms</code></pre>
<p>Catorce milisegundos es lo que tardó un paquete en llegar hasta un servidor de Google y volver, y ese número tiene nombre, <em>latencia</em>, una de las tres magnitudes con las que se mide la calidad de un enlace de paquetes. Las otras dos son el <em>jitter</em>, cuánto varía esa latencia de un paquete a otro, y la <em>pérdida</em>, el porcentaje de paquetes que nunca llegaron. Fíjate en que esas tres magnitudes solo tienen sentido porque estás en una red de conmutación de paquetes, donde cada paquete puede tomar un camino distinto y esperar un tiempo distinto en cada cola, algo que en una red de circuitos tradicional no existe, porque el circuito reservado entrega siempre el mismo retardo constante mientras dura la llamada.</p>
<p>Si tu equipo no responde nada, no te preocupes, muchas redes institucionales bloquean esos paquetes a propósito. Lo vemos en clase.</p>
</section>
<section id="lo-que-te-llevas-de-hoy" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="lo-que-te-llevas-de-hoy"><span class="header-section-number">11</span> Lo que te llevas de hoy</h2>
<div class="checklist">
<p><strong>Al salir de este tema deberías poder explicar, sin mirar la guía</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Qué es la telemática y en qué se diferencia de las telecomunicaciones y la informática</label></li>
<li><label><input type="checkbox">Los hitos que llevaron del telégrafo de 1844 a la fusión de 1932 que creó la UIT, y de ahí a la conmutación de paquetes y la fibra óptica</label></li>
<li><label><input type="checkbox">Los cinco elementos del modelo de Shannon y Weaver, y qué hace cada uno</label></li>
<li><label><input type="checkbox">La diferencia entre un dato y una señal</label></li>
<li><label><input type="checkbox">La diferencia entre conmutación de circuitos y conmutación de paquetes, y por qué IoT necesita la segunda</label></li>
<li><label><input type="checkbox">Qué dice, a nivel de idea, el teorema de Nyquist y qué dice el de Shannon-Hartley, y por qué no compiten entre sí</label></li>
<li><label><input type="checkbox">Qué es la convergencia de redes, qué es una NGN según la UIT, y un caso real donde converger trajo también un riesgo nuevo</label></li>
<li><label><input type="checkbox">Qué es la latencia</label></li>
</ul>
</div>
</section>
<section id="antes-del-tema-2" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="antes-del-tema-2"><span class="header-section-number">12</span> Antes del Tema 2</h2>
<p>Guarda tus respuestas del Reto 2, porque el Tema 2 empieza exactamente donde este tema las dejó abiertas, con la pregunta de cómo se le sacan más bits por segundo a un mismo canal usando esquemas de modulación como ASK, FSK y PSK en vez de binario puro. Ahí vas a ver con precisión la diferencia entre dato y señal que introdujiste hoy, cómo se codifica una señal digital en banda base, cómo se modula sobre una portadora, y por qué el ancho de banda de un canal es, en la práctica, el recurso más escaso de cualquier red.</p>
</section>
<section id="recursos" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="recursos"><span class="header-section-number">13</span> Recursos</h2>
<ul>
<li>ITU. “Overview of ITU’s History.” <a href="https://www.itu.int/en/history/pages/ITUsHistory.aspx">itu.int/en/history/pages/ITUsHistory.aspx</a></li>
<li>ITU. “ITU history, 1865, 1890s.” <a href="https://www.itu.int/160/our-history/1865-1890s/">itu.int/160/our-history/1865-1890s</a></li>
<li>ITU-T Recommendation Y.2001 (12/2004). “General overview of NGN.” <a href="https://www.itu.int/rec/dologin_pub.asp?lang=e&amp;id=T-REC-Y.2001-200412-I!!PDF-E&amp;type=items">itu.int, T-REC-Y.2001-200412-I</a></li>
<li>Federal Communications Commission. “VoIP and 911 Service.” <a href="https://www.fcc.gov/consumers/guides/voip-and-911-service">fcc.gov/consumers/guides/voip-and-911-service</a></li>
<li>The Nobel Prize. “The Nobel Prize in Physics 2009”, Charles K. Kao. <a href="https://www.nobelprize.org/prizes/physics/2009/summary/">nobelprize.org/prizes/physics/2009/summary</a></li>
<li>Shannon, C. E. (1948). <em>A Mathematical Theory of Communication.</em> Bell System Technical Journal. <a href="https://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf">Copia en la Universidad de Harvard</a>.</li>
<li>Kurose, J. F. y Ross, K. W. <em>Redes de computadoras, un enfoque descendente.</em> Capítulo 1, conmutación de circuitos frente a conmutación de paquetes, y estratificación en capas.</li>
<li>Forouzan, B. A. <em>Data Communications and Networking.</em> Capítulos sobre el modelo de comunicación de datos y los teoremas de Nyquist y de Shannon.</li>
<li>Stallings, W. <em>Comunicaciones y redes de computadores.</em> Capítulos introductorios sobre el modelo de comunicación de datos y la evolución histórica de las telecomunicaciones.</li>
<li>ITU-T Recommendation G.983 series (APON/BPON) y G.984 series (GPON), familias de redes ópticas pasivas de banda ancha usadas en despliegues de triple play.</li>
</ul>
<div class="pie-doc">
<p>Telemática para IoT (TPI01). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redaccion de esta guia conto con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>