<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 1. Las piezas con las que se dibuja la realidad – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-9d905b06f1e8b96cef5de7dac512495c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-02/index.html">Unidad 2. Modelo entidad relación</a></li><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-02/tema-01-componentes-mer/index.html">Tema 1. Las piezas con las que se dibuja la realidad</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Introducción a los sistemas de bases de datos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-01/tema-01-datos-informacion-conocimiento/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Datos, información y el archivo que se queda corto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-01/tema-02-integracion-organizacional/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Una base de datos, toda la empresa</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Modelo entidad relación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-02/tema-01-componentes-mer/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 1. Las piezas con las que se dibuja la realidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-02/tema-02-representacion-cardinalidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. El dibujo que decide la llave foránea</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#qué-es-una-entidad-y-qué-es-un-conjunto-de-entidades" id="toc-qué-es-una-entidad-y-qué-es-un-conjunto-de-entidades" class="nav-link active" data-scroll-target="#qué-es-una-entidad-y-qué-es-un-conjunto-de-entidades"><span class="header-section-number">1</span> Qué es una entidad y qué es un conjunto de entidades</a></li>
  <li><a href="#entidades-fuertes-y-débiles" id="toc-entidades-fuertes-y-débiles" class="nav-link" data-scroll-target="#entidades-fuertes-y-débiles"><span class="header-section-number">2</span> Entidades fuertes y débiles</a></li>
  <li><a href="#cómo-se-describe-una-entidad-con-atributos" id="toc-cómo-se-describe-una-entidad-con-atributos" class="nav-link" data-scroll-target="#cómo-se-describe-una-entidad-con-atributos"><span class="header-section-number">3</span> Cómo se describe una entidad con atributos</a></li>
  <li><a href="#cuando-el-atributo-multivaluado-se-maltrata" id="toc-cuando-el-atributo-multivaluado-se-maltrata" class="nav-link" data-scroll-target="#cuando-el-atributo-multivaluado-se-maltrata"><span class="header-section-number">4</span> Cuando el atributo multivaluado se maltrata</a>
  <ul class="collapse">
  <li><a href="#cuándo-pasar-un-atributo-a-entidad-propia" id="toc-cuándo-pasar-un-atributo-a-entidad-propia" class="nav-link" data-scroll-target="#cuándo-pasar-un-atributo-a-entidad-propia">Cuándo pasar un atributo a entidad propia</a></li>
  </ul></li>
  <li><a href="#relaciones-entre-entidades" id="toc-relaciones-entre-entidades" class="nav-link" data-scroll-target="#relaciones-entre-entidades"><span class="header-section-number">5</span> Relaciones entre entidades</a></li>
  <li><a href="#cómo-se-identifica-una-entidad-sin-ambigüedad-con-una-clave" id="toc-cómo-se-identifica-una-entidad-sin-ambigüedad-con-una-clave" class="nav-link" data-scroll-target="#cómo-se-identifica-una-entidad-sin-ambigüedad-con-una-clave"><span class="header-section-number">6</span> Cómo se identifica una entidad sin ambigüedad con una clave</a></li>
  <li><a href="#lo-que-te-llevas-de-hoy" id="toc-lo-que-te-llevas-de-hoy" class="nav-link" data-scroll-target="#lo-que-te-llevas-de-hoy"><span class="header-section-number">7</span> Lo que te llevas de hoy</a></li>
  <li><a href="#antes-del-tema-2" id="toc-antes-del-tema-2" class="nav-link" data-scroll-target="#antes-del-tema-2"><span class="header-section-number">8</span> Antes del Tema 2</a></li>
  <li><a href="#recursos" id="toc-recursos" class="nav-link" data-scroll-target="#recursos"><span class="header-section-number">9</span> Recursos</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-02/index.html">Unidad 2. Modelo entidad relación</a></li><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-02/tema-01-componentes-mer/index.html">Tema 1. Las piezas con las que se dibuja la realidad</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 1. Las piezas con las que se dibuja la realidad</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">17 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 2. Modelo entidad relación</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 1. Componentes del modelo: entidades, atributos, relaciones y claves</td>
</tr>
</tbody>
</table>
</div>
<p>La Unidad 1 cerró con el caso de Ana Ruiz, la clienta de la cafetería cuyo teléfono quedaba escrito por separado en tres hojas distintas y terminaba desactualizado en dos de ellas apenas ella lo cambiaba. Ese caso mostró qué sale mal cuando no existe un modelo compartido de la realidad antes de guardar un dato, pero se quedó ahí, en el diagnóstico del problema, sin decir cómo se dibuja ese modelo compartido. Esta unidad trae la herramienta que resuelve justo eso, el modelo entidad relación, un lenguaje con el que alguien dibuja primero cómo es el negocio, cliente, pedido, producto, y solo después decide en qué tablas queda guardado. Hoy aprendes las cuatro piezas con las que se arma ese dibujo, la entidad, el atributo, la relación y la clave, y las vas a ver aplicadas de principio a fin sobre la misma cafetería que ya conoces.</p>
<section id="qué-es-una-entidad-y-qué-es-un-conjunto-de-entidades" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="qué-es-una-entidad-y-qué-es-un-conjunto-de-entidades"><span class="header-section-number">1</span> Qué es una entidad y qué es un conjunto de entidades</h2>
<p>Una <em>entidad</em> es un objeto que existe y que se puede distinguir de cualquier otro objeto, como Silberschatz, Korth y Sudarshan la definen en el capítulo dedicado al diseño con el modelo entidad relación de <em>Fundamentos de bases de datos</em>. Ana Ruiz es una entidad, Luis Pena es otra, y aunque las dos sean clientas de la misma cafetería, cada una es distinguible de la otra porque cada una es una persona real distinta. Un <em>conjunto de entidades</em> agrupa entidades del mismo tipo que comparten las mismas propiedades, como el conjunto de todos los clientes de la cafetería, sin que eso implique que dos clientes cualesquiera tengan que parecerse en sus valores, solo que ambos se describen con los mismos campos.</p>
<p>En el diagrama de un modelo entidad relación, un rectángulo representa un conjunto de entidades, y el nombre que va dentro nombra al tipo, no a una persona concreta. Esa distinción entre el conjunto y cada miembro suyo es la misma que separa una clase de un objeto en programación orientada a objetos, solo que aquí el vocabulario cambia, entidad en vez de objeto y conjunto de entidades en vez de clase.</p>
<div class="diagrama">
<svg viewbox="0 0 720 240" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="El conjunto de entidades Cliente arriba, con tres entidades individuales debajo, cada una distinguible por sus propios valores de id_cliente y nombre, conectadas al conjunto por una flecha de instancia de" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="base21a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="360" y="16" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Un conjunto de entidades agrupa objetos distinguibles del mismo tipo</text> <rect x="230" y="26" width="260" height="50" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="360" y="56" font-size="14.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">conjunto de entidades Cliente</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="20" y="150" width="210" height="80" rx="10"></rect><rect x="255" y="150" width="210" height="80" rx="10"></rect><rect x="490" y="150" width="210" height="80" rx="10"></rect></g> <g fill="none" stroke="#8fb3d1" stroke-width="2" marker-end="url(#base21a)"><path d="M300,76 C260,104 180,124 125,148"></path><path d="M360,76 L360,148"></path><path d="M420,76 C460,104 540,124 595,148"></path></g> <g text-anchor="middle" font-size="12.5" font-weight="600" fill="#12324f"><text x="125" y="174">entidad cliente 1</text><text x="360" y="174">entidad cliente 2</text><text x="595" y="174">entidad cliente 3</text></g> <g text-anchor="middle" font-size="11" fill="#5b6876"><text x="125" y="194">id_cliente = 1</text><text x="125" y="208">nombre = Ana Ruiz</text><text x="360" y="194">id_cliente = 2</text><text x="360" y="208">nombre = Luis Pena</text><text x="595" y="194">id_cliente = 3</text><text x="595" y="208">nombre = Karen Diaz</text></g> <text x="360" y="228" font-size="11" fill="#0e6f6c" text-anchor="middle">cada entidad se distingue de las demas, aunque pertenezca al mismo conjunto</text>
</svg>
</div>
<p>De aquí en adelante, todo el tema se apoya en el mismo negocio, la cafetería que ya conoces, así que antes de seguir conviene plantearse una pregunta de análisis. Si tuvieras que rediseñar esa cafetería para que el teléfono de un cliente viviera en un único lugar, sin que las tres áreas del Tema 1 de la Unidad 1 volvieran a escribirlo cada una por su cuenta, cuáles serían las piezas mínimas necesarias y cómo se conectarían entre sí. La respuesta se construye pieza por pieza en el resto de este tema, y empieza por identificar los conjuntos de entidades que hacen falta, Cliente, Pedido y Producto.</p>
</section>
<section id="entidades-fuertes-y-débiles" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="entidades-fuertes-y-débiles"><span class="header-section-number">2</span> Entidades fuertes y débiles</h2>
<p>Un conjunto de entidades es <em>fuerte</em> cuando tiene suficientes atributos propios para identificar sin ambigüedad a cada una de sus entidades, sin depender de ningún otro conjunto de entidades para lograrlo. Cliente, Pedido y Producto son fuertes en la cafetería, ya que cada uno trae su propio identificador, id_cliente, numero_pedido o codigo_producto, que basta por sí solo para distinguir cualquier entidad de ese conjunto.</p>
<p>Un conjunto de entidades es <em>débil</em> cuando su existencia depende de otro conjunto de entidades, al que Silberschatz, Korth y Sudarshan llaman el conjunto identificador o propietario. Una entidad débil no tiene atributos propios suficientes para identificarse sola, así que toma prestada la clave del propietario y le agrega un atributo propio llamado <em>discriminador</em>, que solo necesita ser único dentro del propietario, no en toda la base de datos. El ejemplo verificado del propio libro es la entidad <code>section</code>, que depende de <code>course</code> porque una sección de un curso no existe sin el curso al que pertenece, y que se identifica con la clave de <code>course</code> más un discriminador propio de la sección.</p>
<p>En la cafetería, cada línea de un pedido, el renglón que dice qué producto se pidió y en qué cantidad, solo tiene sentido dentro del pedido al que pertenece. Un <code>DetallePedido</code> no existe suelto, nace cuando nace un <code>Pedido</code> y muere si ese pedido se elimina, así que es una entidad débil cuyo propietario es <code>Pedido</code>, identificada por el <code>numero_pedido</code> del propietario más un discriminador propio, el <code>numero_linea</code> dentro de ese pedido.</p>
<p>En la notación del diagrama, un conjunto de entidades débil se dibuja con un rectángulo de doble borde, la relación que lo conecta con su propietario se dibuja con un rombo de doble borde porque es una <em>relación identificadora</em>, y el discriminador se subraya con una línea punteada en vez de la línea continua que marca la clave primaria de una entidad fuerte.</p>
<div class="diagrama">
<svg viewbox="0 0 760 260" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Pedido es una entidad fuerte con numero_pedido subrayado como clave primaria; DetallePedido es una entidad debil dibujada con doble rectangulo, conectada a Pedido por la relacion identificadora tiene en doble rombo; el discriminador numero_linea se subraya con linea discontinua, y la clave primaria completa de DetallePedido combina numero_pedido mas numero_linea" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Entidad fuerte a la izquierda, entidad debil a la derecha</text> <rect x="20" y="70" width="190" height="120" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="115" y="94" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">Pedido</text> <text x="115" y="120" font-size="12" fill="#12324f" text-anchor="middle" text-decoration="underline">numero_pedido</text> <text x="115" y="140" font-size="12" fill="#12324f" text-anchor="middle">fecha</text> <text x="115" y="172" font-size="11" fill="#0e6f6c" text-anchor="middle">entidad fuerte</text> <polygon points="330,75 400,130 330,185 260,130" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <polygon points="330,87 388,130 330,173 272,130" fill="none" stroke="#8fc9c5"></polygon> <text x="330" y="126" font-size="12" font-weight="700" fill="#0e6f6c" text-anchor="middle">tiene</text> <text x="330" y="142" font-size="11" fill="#0e6f6c" text-anchor="middle">identificadora</text> <line x1="210" y1="130" x2="260" y2="130" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="400" y1="130" x2="555" y2="130" stroke="#8fb3d1" stroke-width="1.8"></line> <rect x="555" y="55" width="185" height="150" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="562" y="62" width="171" height="136" rx="6" fill="none" stroke="#c7d6e6"></rect> <text x="647" y="84" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">DetallePedido</text> <text x="647" y="108" font-size="12" fill="#12324f" text-anchor="middle">numero_linea</text> <line x1="610" y1="112" x2="684" y2="112" stroke="#12324f" stroke-width="1.2" stroke-dasharray="3 2"></line> <text x="647" y="130" font-size="12" fill="#12324f" text-anchor="middle">cantidad</text> <text x="647" y="150" font-size="12" fill="#12324f" text-anchor="middle">precio_unitario</text> <text x="647" y="180" font-size="11" fill="#0e6f6c" text-anchor="middle">entidad debil, discriminador punteado</text> <text x="380" y="230" font-size="12" fill="#12324f" text-anchor="middle">clave primaria de DetallePedido = numero_pedido (heredado de Pedido) + numero_linea</text> <text x="380" y="252" font-size="11" fill="#5b6876" text-anchor="middle">DetallePedido no puede existir sin un Pedido al cual pertenecer</text>
</svg>
</div>
<p>Así se ve, en un esquema simplificado, lo que ese diagrama termina produciendo cuando el modelo se traduce a tablas. La flecha de la unidad siguiente todavía no llega, pero conviene adelantar el resultado para que la idea de entidad débil no se quede solo en la forma del dibujo:</p>
<pre><code>Pedido(numero_pedido, fecha)
DetallePedido(numero_pedido, numero_linea, cantidad, precio_unitario)</code></pre>
<p>Fíjate en que <code>numero_pedido</code> aparece dentro de <code>DetallePedido</code>, aunque en el diagrama ese atributo vive en <code>Pedido</code> y no se repite explícitamente dentro del rectángulo doble. Ese detalle sorprende la primera vez que se ve, porque parece una contradicción, se supone que la entidad débil no tenía ese atributo propio y sin embargo termina en su tabla. Lo que pasa es que la relación identificadora es la que aporta ese atributo al pasar a tablas, ya que sin él ninguna fila de <code>DetallePedido</code> sabría a qué pedido pertenece. La Unidad 3 formaliza ese paso completo de diagrama a tablas, así que por ahora basta con quedarse con la idea de que toda entidad débil termina cargando, en su clave primaria, la clave completa de su propietario.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Diseña la entidad débil Ejemplar
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una biblioteca universitaria guarda un conjunto de entidades <code>Libro</code>, identificado por su propio <code>isbn</code>. Cada libro puede tener varios ejemplares físicos en el estante, y cada ejemplar se presta y se devuelve por separado, con su propio estado, disponible o prestado. Ningún ejemplar tiene sentido sin el libro al que pertenece.</p>
<p>Diseña el conjunto de entidades <code>Ejemplar</code> como entidad débil, siguiendo el mismo patrón que <code>DetallePedido</code>. Decide qué atributo propio usarías como discriminador dentro de cada libro, y escribe cuál sería la clave primaria completa de <code>Ejemplar</code> una vez combinada con la clave de <code>Libro</code>. No hace falta que dibujes el diagrama completo, con la clave primaria y una frase que justifique por qué <code>Ejemplar</code> no puede ser una entidad fuerte es suficiente.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>Ejemplar</code> es una entidad débil porque ningún atributo propio del ejemplar alcanza para distinguirlo sin apoyarse en el libro al que pertenece, ya que dos ejemplares del mismo libro no tienen, por sí solos, nada que los diferencie entre sí. El discriminador puede ser <code>numero_ejemplar</code>, un consecutivo que solo necesita ser único dentro de cada libro, así que el primer ejemplar de un <code>isbn</code> concreto lleva <code>numero_ejemplar = 1</code>, el segundo <code>numero_ejemplar = 2</code>, y así sucesivamente, sin que ese número tenga que ser distinto frente a los ejemplares de otro libro.</p>
<p>La clave primaria completa de <code>Ejemplar</code> combina la clave del propietario con el discriminador propio, así que queda formada por <code>isbn</code>, heredado de <code>Libro</code>, más <code>numero_ejemplar</code>. <code>Ejemplar</code> no puede ser una entidad fuerte porque, sin el <code>isbn</code> del libro al que pertenece, dos ejemplares con el mismo <code>numero_ejemplar</code> de libros distintos serían indistinguibles entre sí.</p>
</div>
</div>
</div>
</section>
<section id="cómo-se-describe-una-entidad-con-atributos" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="cómo-se-describe-una-entidad-con-atributos"><span class="header-section-number">3</span> Cómo se describe una entidad con atributos</h2>
<p>Un <em>atributo</em> es una propiedad descriptiva que poseen todos los miembros de un conjunto de entidades, y el conjunto de valores permitidos para ese atributo es su <em>dominio</em>. El capítulo 6 de <em>Fundamentos de bases de datos</em> clasifica los atributos en cuatro formas que no se excluyen entre sí, un mismo atributo puede ser compuesto y además derivado, por ejemplo, aunque en la práctica la mayoría de los atributos de un modelo caen limpiamente en una sola categoría.</p>
<p>Un atributo es <em>simple</em> cuando no se puede subdividir en partes más pequeñas con significado propio, como <code>id_cliente</code>. Un atributo es <em>compuesto</em> cuando sí admite esa subdivisión, como el <code>nombre</code> de un cliente, que se separa en <code>primer_nombre</code> y <code>apellido</code>, cada uno con sentido propio incluso por separado. Un atributo es <em>monovaluado</em> cuando cada entidad guarda un solo valor para él, como <code>fecha_registro</code>, y es <em>multivaluado</em> cuando una misma entidad puede tener varios valores válidos al mismo tiempo, como <code>telefono</code>, porque Ana Ruiz puede tener un celular personal y un número fijo de su casa, los dos vigentes a la vez. Un atributo es <em>derivado</em> cuando su valor se calcula a partir de otros atributos en vez de guardarse directamente, como <code>antiguedad</code>, que se obtiene restando <code>fecha_registro</code> de la fecha de hoy y que cambia solo porque el tiempo pasa, no porque alguien lo edite.</p>
<p>En la notación de Chen, cada atributo se dibuja como un óvalo conectado a su entidad. Un atributo compuesto se dibuja con óvalos más pequeños colgando del óvalo principal, uno por cada subparte. Un atributo multivaluado se dibuja con un óvalo de doble borde. Un atributo derivado se dibuja con un óvalo de borde punteado. La clave primaria de la entidad se subraya, igual que en los rectángulos de las entidades.</p>
<div class="diagrama">
<svg viewbox="0 0 760 365" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="La entidad Cliente en el centro conectada a cinco atributos: id_cliente simple y subrayado como clave primaria a la izquierda, nombre compuesto arriba que se divide en primer_nombre y apellido, telefono multivaluado a la derecha dibujado con ovalo doble, fecha_registro simple abajo a la izquierda y antiguedad derivada abajo a la derecha dibujada con ovalo punteado" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="14" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Cuatro formas de atributo alrededor de una misma entidad</text> <line x1="290" y1="78" x2="358" y2="102" stroke="#8fb3d1" stroke-width="1.6"></line> <line x1="470" y1="78" x2="402" y2="102" stroke="#8fb3d1" stroke-width="1.6"></line> <line x1="380" y1="144" x2="380" y2="192" stroke="#8fb3d1" stroke-width="1.6"></line> <line x1="163" y1="219" x2="305" y2="219" stroke="#8fb3d1" stroke-width="1.6"></line> <line x1="597" y1="219" x2="455" y2="219" stroke="#8fb3d1" stroke-width="1.6"></line> <line x1="205" y1="292" x2="330" y2="248" stroke="#8fb3d1" stroke-width="1.6"></line> <line x1="555" y1="292" x2="430" y2="248" stroke="#8fb3d1" stroke-width="1.6" stroke-dasharray="4 3"></line> <ellipse cx="290" cy="56" rx="62" ry="24" fill="#eef4fa" stroke="#c7d6e6"></ellipse> <ellipse cx="470" cy="56" rx="58" ry="24" fill="#eef4fa" stroke="#c7d6e6"></ellipse> <ellipse cx="380" cy="120" rx="56" ry="24" fill="#eef4fa" stroke="#c7d6e6"></ellipse> <ellipse cx="95" cy="219" rx="68" ry="26" fill="#eef4fa" stroke="#c7d6e6"></ellipse> <ellipse cx="665" cy="219" rx="68" ry="28" fill="#eef4fa" stroke="#c7d6e6"></ellipse> <ellipse cx="665" cy="219" rx="56" ry="20" fill="none" stroke="#c7d6e6"></ellipse> <ellipse cx="140" cy="308" rx="80" ry="26" fill="#eef4fa" stroke="#c7d6e6"></ellipse> <ellipse cx="620" cy="308" rx="78" ry="26" fill="#f5f7fa" stroke="#cfd8e3" stroke-dasharray="4 3"></ellipse> <rect x="305" y="192" width="150" height="54" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="224" font-size="14.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Cliente</text> <text x="290" y="60" font-size="11.5" fill="#12324f" text-anchor="middle">primer_nombre</text> <text x="470" y="60" font-size="11.5" fill="#12324f" text-anchor="middle">apellido</text> <text x="380" y="124" font-size="12" fill="#12324f" text-anchor="middle">nombre</text> <text x="380" y="170" font-size="11" fill="#5b6876" text-anchor="middle">compuesto</text> <text x="95" y="223" font-size="12" fill="#12324f" text-anchor="middle" text-decoration="underline">id_cliente</text> <text x="95" y="263" font-size="11" fill="#0e6f6c" text-anchor="middle">simple, clave primaria</text> <text x="665" y="223" font-size="12" fill="#12324f" text-anchor="middle">telefono</text> <text x="665" y="263" font-size="11" fill="#5b6876" text-anchor="middle">multivaluado, ovalo doble</text> <text x="140" y="312" font-size="12" fill="#12324f" text-anchor="middle">fecha_registro</text> <text x="140" y="350" font-size="11" fill="#5b6876" text-anchor="middle">simple</text> <text x="620" y="312" font-size="12" fill="#12324f" text-anchor="middle">antiguedad</text> <text x="620" y="350" font-size="11" fill="#5b6876" text-anchor="middle">derivado, ovalo punteado</text>
</svg>
</div>
<p>Al pasar del diagrama a tablas, un atributo compuesto se aplana en columnas separadas, <code>primer_nombre</code> y <code>apellido</code> en vez de un único <code>nombre</code>. Un atributo derivado casi siempre se descarta de la tabla, ya que guardarlo obligaría a mantenerlo sincronizado cada vez que cambie el atributo del que depende, así que lo normal es calcularlo con una consulta cuando se necesite, un tema que retomas en la Unidad 4. El atributo multivaluado es el que exige más cuidado, porque no cabe en una sola columna sin romper la idea misma de lo que es una columna, y de eso trata la siguiente sección.</p>
</section>
<section id="cuando-el-atributo-multivaluado-se-maltrata" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="cuando-el-atributo-multivaluado-se-maltrata"><span class="header-section-number">4</span> Cuando el atributo multivaluado se maltrata</h2>
<p>Imagina que quien diseña la base de datos de la cafetería no conoce todavía la regla anterior y decide guardar los teléfonos de cada cliente como un solo texto separado por comas dentro de una única columna <code>telefono</code>, porque a primera vista parece la salida más rápida. Antes de ver qué falla conviene plantearse cómo se busca a un cliente por su segundo número de teléfono si ese número vive enterrado dentro de un texto más largo, y qué pasa el día que ese cliente pide que se elimine solo uno de sus dos números.</p>
<p>La respuesta es que ninguna de las dos operaciones es directa. Buscar exige comparar subcadenas dentro de un texto en vez de comparar un valor completo contra otro, lo cual es más lento y más frágil, ya que un espacio de más o un orden distinto de los números rompe la comparación. Borrar un solo número exige leer el texto completo, encontrar el fragmento correcto y reescribir toda la columna sin el fragmento borrado, en vez de simplemente eliminar una fila. Silberschatz, Korth y Sudarshan resuelven este mismo problema, con el atributo multivaluado <code>phone_number</code> de la entidad <code>instructor</code>, moviendo ese atributo a un esquema aparte, uno con la clave primaria de la entidad más el atributo multivaluado, de modo que cada valor ocupa su propia fila.</p>
<div class="diagrama">
<svg viewbox="0 0 760 260" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A la izquierda una tabla Cliente con telefono aplanado en una sola columna con dos numeros separados por coma; a la derecha el esquema correcto con dos tablas, Cliente sin telefono y Cliente_Telefono con una fila por cada numero" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Un atributo multivaluado no cabe en una sola columna</text> <rect x="20" y="40" width="330" height="30" rx="6" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="185" y="60" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Cliente, telefono aplanado (mal disenado)</text> <rect x="20" y="72" width="330" height="90" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="36" y="96" font-size="11.5" fill="#12324f">id_cliente = 1</text> <text x="36" y="114" font-size="11.5" fill="#12324f">nombre = Ana Ruiz</text> <text x="36" y="132" font-size="11.5" fill="#0e6f6c">telefono = “3001112233,3001119999”</text> <text x="36" y="150" font-size="11" fill="#5b6876">un solo texto con dos numeros adentro</text> <rect x="400" y="40" width="150" height="30" rx="6" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="475" y="60" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Cliente</text> <rect x="400" y="72" width="150" height="60" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="414" y="96" font-size="11.5" fill="#12324f">id_cliente = 1</text> <text x="414" y="114" font-size="11.5" fill="#12324f">nombre = Ana Ruiz</text> <rect x="565" y="40" width="175" height="30" rx="6" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="652" y="60" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Cliente_Telefono</text> <rect x="565" y="72" width="175" height="90" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="579" y="96" font-size="11" fill="#12324f">id=1, telefono=3001112233</text> <text x="579" y="114" font-size="11" fill="#12324f">id=1, telefono=3001119999</text> <text x="579" y="140" font-size="11" fill="#0e6f6c">una fila por cada numero, misma clave id_cliente</text> <line x1="20" y1="180" x2="740" y2="180" stroke="#cfd8e3" stroke-width="1.2"></line> <text x="185" y="204" font-size="11.5" fill="#5b6876" text-anchor="middle">buscar el segundo numero exige leer y partir el texto completo</text> <text x="580" y="204" font-size="11.5" fill="#5b6876" text-anchor="middle">buscar el segundo numero es una fila mas en Cliente_Telefono</text> <text x="380" y="234" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">borrar un telefono en la version aplanada obliga a reescribir todo el texto de la columna</text>
</svg>
</div>
<p>Vale la pena conectar este error con lo que ya viste en la Unidad 1, porque no es el mismo problema pero nace de la misma familia. El teléfono repetido de Ana Ruiz en tres archivos distintos era redundancia entre archivos separados, mientras que el teléfono aplanado en una sola columna es un error dentro de una única tabla, pero los dos comparten la misma raíz, que es tratar como un valor atómico algo que en realidad tiene una estructura interna, varios teléfonos en vez de uno, y esa estructura se pierde apenas se aplana. La Unidad 3 retoma esta misma idea con nombre propio cuando hable de la primera forma normal.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Clasifica los atributos de Cliente
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para cada atributo de la entidad <code>Cliente</code> que aparece en el diagrama de esta sección, marca en cuál de las cuatro categorías encaja mejor antes de seguir leyendo.</p>
<p><label><input type="checkbox"> nombre, dividido en primer_nombre y apellido</label><br> <label><input type="checkbox"> telefono, con uno o varios números vigentes a la vez</label><br> <label><input type="checkbox"> fecha_registro, un único valor por cliente</label><br> <label><input type="checkbox"> antiguedad, calculada a partir de fecha_registro</label></p>
<p>Escribe junto a cada atributo si es simple, compuesto, monovaluado, multivaluado o derivado, y ten en cuenta que un atributo puede pertenecer a más de una categoría a la vez.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>nombre</code> es compuesto, porque se divide en <code>primer_nombre</code> y <code>apellido</code>, cada uno con significado propio. Además, cada una de esas dos subpartes es a su vez simple y monovaluada, porque no se dividen más y cada cliente tiene un solo valor vigente para cada una.</p>
<p><code>telefono</code> es multivaluado, porque un mismo cliente puede tener más de un número vigente al mismo tiempo, y también es simple, porque cada número individual no se subdivide en partes con significado propio.</p>
<p><code>fecha_registro</code> es simple y monovaluado, porque no se subdivide y cada cliente tiene exactamente un valor para él, el día en que quedó registrado.</p>
<p><code>antiguedad</code> es derivado, porque no se guarda directamente sino que se calcula restando <code>fecha_registro</code> de la fecha de hoy, y también es simple y monovaluado, ya que un cliente solo tiene una antigüedad vigente en cada momento.</p>
</div>
</div>
</div>
<section id="cuándo-pasar-un-atributo-a-entidad-propia" class="level3">
<h3 class="anchored" data-anchor-id="cuándo-pasar-un-atributo-a-entidad-propia">Cuándo pasar un atributo a entidad propia</h3>
<p>No siempre está claro si algo debe modelarse como atributo o como entidad propia, y el propio capítulo 6 de Silberschatz, Korth y Sudarshan dedica una sección a este tipo de decisiones de diseño. El criterio que proponen es preguntarse si ese dato necesita información adicional propia o si admite varios valores que conviene consultar por separado. En la cafetería, <code>telefono</code> funciona bien como atributo multivaluado de <code>Cliente</code> mientras solo interese guardar el número. Pero si mañana la cafetería necesitara saber, además, el operador de cada línea o si un número es el preferido para avisos de pedido listo, <code>telefono</code> dejaría de alcanzar como atributo y convendría ascenderlo a un conjunto de entidades propio, con sus propios atributos, <code>numero</code>, <code>operador</code> y <code>es_preferido</code>, relacionado con <code>Cliente</code>. La misma pregunta, necesita este dato cargar información propia que ya no cabe en un solo valor, es la que vas a usar cada vez que dudes entre dejar algo como atributo o subirlo a entidad.</p>
</section>
</section>
<section id="relaciones-entre-entidades" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="relaciones-entre-entidades"><span class="header-section-number">5</span> Relaciones entre entidades</h2>
<p>Una <em>relación</em> es una asociación entre entidades, y un <em>conjunto de relaciones</em> es el conjunto matemático de esas asociaciones entre dos o más conjuntos de entidades. En el diagrama, un rombo representa el conjunto de relaciones, y una línea conecta el rombo con cada conjunto de entidades que participa. En la cafetería, <code>Cliente</code> y <code>Pedido</code> se conectan mediante la relación <code>realiza</code>, ya que cada cliente realiza uno o varios pedidos.</p>
<p>El <em>grado</em> de una relación es el número de conjuntos de entidades que participan en ella. La mayoría de las relaciones que vas a modelar en este curso son binarias, con dos conjuntos de entidades, como <code>realiza</code>. Las relaciones también pueden ser ternarias o de mayor grado, y el propio texto guía trae un ejemplo verificado, <code>proj_guide</code>, que conecta a la vez <code>instructor</code>, <code>student</code> y <code>project</code> en un proyecto de investigación. Una relación, además de conectar entidades, puede tener sus propios atributos, información que no pertenece a ninguna de las entidades por separado sino a la asociación entre ellas. En la cafetería, el canal por el que llegó un pedido concreto de un cliente concreto, si fue en el mostrador o a domicilio, es un dato de esa asociación puntual, no un dato permanente del cliente ni del pedido en abstracto, así que se modela como atributo de la relación <code>realiza</code>.</p>
<div class="diagrama">
<svg viewbox="0 0 700 230" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="La entidad Cliente y la entidad Pedido conectadas por la relacion realiza dibujada como un rombo; el rombo tiene su propio atributo canal_pedido dibujado como un ovalo colgando debajo" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="350" y="16" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Una relacion tambien puede tener su propio atributo</text> <rect x="20" y="70" width="150" height="70" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="95" y="96" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">Cliente</text> <text x="95" y="118" font-size="11.5" fill="#12324f" text-anchor="middle" text-decoration="underline">id_cliente</text> <rect x="530" y="70" width="150" height="70" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="605" y="96" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">Pedido</text> <text x="605" y="118" font-size="11.5" fill="#12324f" text-anchor="middle" text-decoration="underline">numero_pedido</text> <polygon points="350,65 420,105 350,145 280,105" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <text x="350" y="110" font-size="12.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">realiza</text> <line x1="170" y1="105" x2="280" y2="105" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="420" y1="105" x2="530" y2="105" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="350" y1="145" x2="350" y2="168" stroke="#8fb3d1" stroke-width="1.6"></line> <ellipse cx="350" cy="192" rx="72" ry="24" fill="#f5f7fa" stroke="#cfd8e3"></ellipse> <text x="350" y="196" font-size="12" fill="#12324f" text-anchor="middle">canal_pedido</text> <text x="350" y="222" font-size="11" fill="#5b6876" text-anchor="middle">valores: mostrador o domicilio, propio de cada pedido concreto de cada cliente</text>
</svg>
</div>
<p>Una relación también puede conectar un conjunto de entidades consigo mismo, lo que se llama una <em>relación recursiva</em>, y ahí hace falta distinguir el papel que juega cada participación con un <em>rol</em>, porque el nombre del conjunto de entidades ya no basta para saber cuál es cuál. El propio texto guía lo ilustra con <code>course_id</code> y <code>prereq_id</code> en una relación de prerrequisitos entre cursos consigo mismos. Este mismo programa académico tiene un ejemplo real de esa idea, sin necesidad de inventarlo, la asignatura Base de datos que estás cursando tiene como prerrequisito a Estructura de datos, según la ficha de este mismo curso.</p>
<div class="diagrama">
<svg viewbox="0 0 700 260" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="La entidad Asignatura relacionada consigo misma mediante la relacion recursiva es_prerrequisito_de; dos lineas distintas salen del mismo rombo hacia la misma entidad, una con el rol asignatura y otra con el rol prerrequisito, ilustrado con el caso real de que Base de datos tiene como prerrequisito a Estructura de datos" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="350" y="16" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Una relacion recursiva conecta una entidad consigo misma</text> <polygon points="370,30 435,68 370,106 305,68" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <text x="370" y="72" font-size="11.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">es prerrequisito de</text> <rect x="270" y="160" width="200" height="66" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="370" y="188" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">Asignatura</text> <text x="370" y="208" font-size="11.5" fill="#12324f" text-anchor="middle" text-decoration="underline">codigo_asignatura</text> <path d="M305,68 C240,100 260,140 300,160" fill="none" stroke="#8fb3d1" stroke-width="1.7"></path> <path d="M435,68 C500,100 470,140 440,160" fill="none" stroke="#8fb3d1" stroke-width="1.7"></path> <text x="210" y="118" font-size="11" fill="#12324f" text-anchor="middle">rol: asignatura</text> <text x="530" y="118" font-size="11" fill="#12324f" text-anchor="middle">rol: prerrequisito</text> <text x="370" y="244" font-size="11.5" fill="#5b6876" text-anchor="middle">caso real de este programa: Base de datos tiene como prerrequisito a Estructura de datos</text>
</svg>
</div>
<p>Vale la pena cerrar esta sección con una advertencia que el propio texto guía hace explícita. Cualquier relación de grado mayor que dos se puede reescribir como varias relaciones binarias, creando una entidad artificial que conecte a cada participante por separado, pero el mismo texto advierte que esa conversión no siempre logra traducir todas las restricciones de la relación original, así que pueden aparecer, en el esquema convertido, combinaciones que no correspondían a ninguna instancia válida de la relación de partida. No es una regla mecánica libre de riesgo, es una decisión de diseño que hay que revisar caso por caso, y por eso el propio libro prefiere, para relaciones de grado mayor que dos, permitir una sola flecha de cardinalidad hacia como mucho un participante, precisamente para no introducir ambigüedades de lectura, un detalle de notación que la Unidad retoma en el Tema 2.</p>
</section>
<section id="cómo-se-identifica-una-entidad-sin-ambigüedad-con-una-clave" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="cómo-se-identifica-una-entidad-sin-ambigüedad-con-una-clave"><span class="header-section-number">6</span> Cómo se identifica una entidad sin ambigüedad con una clave</h2>
<p>Una <em>superclave</em> es un conjunto de atributos cuyos valores identifican, sin ambigüedad, a cada entidad de un conjunto, para cualquier estado posible de esa base de datos, no solo para los datos que hay hoy cargados. Esa última condición es la que más sorprende, porque un atributo puede parecer único con los datos actuales y aun así no servir como clave, si nada garantiza que seguirá siendo único después. Una <em>clave candidata</em> es una superclave mínima, es decir que ninguno de sus subconjuntos propios sigue siendo superclave, así que quitarle cualquier atributo la rompe. Cuando un conjunto de entidades tiene más de una clave candidata, el diseñador elige una de ellas como <em>clave primaria</em>, la que de ahí en adelante se usa para identificar entidades en el resto del modelo.</p>
<p>Toma la entidad <code>Cliente</code> con tres atributos, <code>id_cliente</code>, <code>nombre</code> y <code>telefono</code>, y estos tres registros de ejemplo.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>id_cliente</th>
<th>nombre</th>
<th>telefono</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Ana Ruiz</td>
<td>3001112233</td>
</tr>
<tr class="even">
<td>2</td>
<td>Luis Pena</td>
<td>3014445566</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Ana Ruiz</td>
<td>3007778899</td>
</tr>
</tbody>
</table>
<p><code>id_cliente</code> es superclave, porque ningún cliente puede compartir su número con otro, y además es mínima, un solo atributo no se puede reducir más, así que es clave candidata y también la clave primaria elegida. <code>nombre</code> no es superclave, porque el registro 1 y el registro 3 comparten el mismo valor, Ana Ruiz, sin ser el mismo cliente. <code>telefono</code> sí es único en esta muestra concreta de tres filas, pero eso no lo convierte en clave, porque nada en el negocio garantiza que dos clientes nunca vayan a compartir el mismo número, ni que un cliente no vaya a cambiar su número más adelante, así que un buen diseño no lo declara clave aunque hoy no se repita. <code>{id_cliente, nombre}</code> sí es superclave, porque incluye a <code>id_cliente</code>, pero no es mínima, ya que quitarle <code>nombre</code> deja intacta la unicidad, así que no es clave candidata.</p>
<div class="diagrama">
<svg viewbox="0 0 740 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Diagrama anidado: el rectangulo mas grande agrupa las superclaves de Cliente, dentro un rectangulo mas chico marca la unica clave candidata, y dentro de esta el rectangulo mas interno marca la clave primaria elegida, id_cliente; a la derecha, fuera de las superclaves, se marcan nombre y telefono como combinaciones que no sirven de clave" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="370" y="16" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">De superclave a clave candidata a clave primaria</text> <rect x="30" y="34" width="440" height="200" rx="12" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="50" y="54" font-size="12" font-weight="700" fill="#12324f">superclaves de Cliente</text> <rect x="60" y="70" width="200" height="130" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="80" y="88" font-size="11.5" font-weight="700" fill="#0e6f6c">clave candidata</text> <text x="80" y="104" font-size="11" fill="#5b6876">superclave minima</text> <rect x="80" y="114" width="150" height="46" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="155" y="134" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">id_cliente</text> <text x="155" y="150" font-size="11" fill="#0e6f6c" text-anchor="middle">clave primaria elegida</text> <g font-size="11" fill="#12324f"><text x="285" y="90">id_cliente, nombre</text><text x="285" y="112">id_cliente, telefono</text><text x="285" y="134">id_cliente, nombre, telefono</text></g> <text x="285" y="156" font-size="11" fill="#5b6876">superclaves validas, pero no minimas</text> <rect x="500" y="60" width="220" height="150" rx="12" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="610" y="80" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">esto no sirve de clave</text> <text x="514" y="106" font-size="11" fill="#12324f">nombre</text> <text x="514" y="122" font-size="11" fill="#5b6876">se repite: dos Ana Ruiz distintas</text> <text x="514" y="150" font-size="11" fill="#12324f">telefono</text> <text x="514" y="166" font-size="11" fill="#5b6876">unico hoy, pero no garantizado</text> <text x="514" y="180" font-size="11" fill="#5b6876">para siempre en cualquier estado</text>
</svg>
</div>
<p>Este mismo vocabulario resuelve, con precisión, dos preguntas que ya rondaban las secciones anteriores. La clave primaria de una entidad débil es la clave primaria de su propietario más el discriminador propio, exactamente lo que ya viste con <code>DetallePedido</code>, cuya clave completa es <code>numero_pedido</code> más <code>numero_linea</code>. Y la clave primaria de un conjunto de relaciones depende de cómo participen las entidades, si ambos lados pueden repetirse en la relación hace falta la unión completa de las dos claves, pero si un lado participa como mucho una vez, con su clave sola basta, una regla que se entiende del todo solo después de ver cardinalidad en el Tema 2, así que por ahora basta con saber que existe y que depende de cómo se conectan las entidades, no solo de cuáles son.</p>
<p>Conviene una última precisión bibliográfica, útil para cuando compares este tema con otros libros de la bibliografía del curso. Silberschatz, Korth y Sudarshan formalizan superclave y clave candidata en el capítulo del modelo relacional, y los retoman de forma más simple, casi siempre solo como clave primaria, cuando llegan al capítulo del modelo entidad relación. Otros textos de la misma bibliografía, como el de Elmasri y Navathe, suelen introducir clave candidata ya dentro del propio capítulo de modelado entidad relación. Ninguna de las dos formas está mal, es una diferencia de organización entre libros, no de definición.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. Identifica las claves candidatas
</div>
</div>
<div class="callout-body-container callout-body">
<p>Vuelve a la tabla de <code>Cliente</code> de esta sección, con <code>id_cliente</code>, <code>nombre</code> y <code>telefono</code>. Para cada una de estas combinaciones de atributos, marca si es superclave, y si además es clave candidata, antes de seguir leyendo.</p>
<p><label><input type="checkbox"> {id_cliente}</label><br> <label><input type="checkbox"> {nombre}</label><br> <label><input type="checkbox"> {telefono}</label><br> <label><input type="checkbox"> {id_cliente, nombre}</label><br> <label><input type="checkbox"> {nombre, telefono}</label></p>
<p>Para la última combinación, {nombre, telefono}, justifica tu respuesta pensando en la fila 1 y la fila 3 de la tabla de ejemplo.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>{id_cliente}</code> es superclave y también clave candidata, porque un solo atributo ya garantiza unicidad y no se puede reducir más.</p>
<p><code>{nombre}</code> no es superclave, porque la fila 1 y la fila 3 comparten el mismo nombre, Ana Ruiz, sin ser el mismo cliente.</p>
<p><code>{telefono}</code> no se declara superclave, aunque en esta muestra de tres filas no se repite ningún número, porque nada en el negocio garantiza esa unicidad para cualquier estado futuro de la tabla.</p>
<p><code>{id_cliente, nombre}</code> sí es superclave, ya que incluye a <code>id_cliente</code>, pero no es clave candidata, porque quitarle <code>nombre</code> y quedarse solo con <code>id_cliente</code> sigue siendo superclave, así que no es mínima.</p>
<p><code>{nombre, telefono}</code> sí distingue a la fila 1 de la fila 3 en esta muestra concreta, porque aunque comparten el nombre, tienen teléfonos distintos, 3001112233 contra 3007778899. Pero, igual que pasaba con <code>telefono</code> solo, esa combinación depende de que dos clientes con el mismo nombre nunca terminen compartiendo también el mismo teléfono, algo que el negocio no puede prometer para siempre, así que tampoco se declara clave.</p>
</div>
</div>
</div>
</section>
<section id="lo-que-te-llevas-de-hoy" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="lo-que-te-llevas-de-hoy"><span class="header-section-number">7</span> Lo que te llevas de hoy</h2>
<div class="checklist">
<p>Al salir de este tema deberías poder explicar, sin mirar la guía, los siguientes puntos:</p>
<ul class="task-list">
<li><label><input type="checkbox">La diferencia entre una entidad y un conjunto de entidades</label></li>
<li><label><input type="checkbox">Qué distingue a una entidad fuerte de una entidad débil, y qué es un discriminador</label></li>
<li><label><input type="checkbox">Las cuatro formas de atributo, simple, compuesto, multivaluado y derivado, con un ejemplo propio de cada una</label></li>
<li><label><input type="checkbox">Por qué un atributo multivaluado no se puede guardar como texto aplanado en una sola columna</label></li>
<li><label><input type="checkbox">Qué es una relación, su grado, un rol y un atributo propio de la relación</label></li>
<li><label><input type="checkbox">La diferencia entre superclave, clave candidata y clave primaria, y por qué un valor único hoy no siempre alcanza para ser clave</label></li>
<li><label><input type="checkbox">Cómo se arma la clave primaria de una entidad débil a partir de la clave de su propietario</label></li>
</ul>
</div>
</section>
<section id="antes-del-tema-2" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="antes-del-tema-2"><span class="header-section-number">8</span> Antes del Tema 2</h2>
<ol type="1">
<li>Resuelve el Reto 1 si todavía no lo hiciste, diseñando la entidad débil <code>Ejemplar</code> de la biblioteca con su clave primaria completa.</li>
<li>Dibuja, en una hoja o en cualquier editor, las tres entidades fuertes de la cafetería, <code>Cliente</code>, <code>Pedido</code> y <code>Producto</code>, con al menos dos atributos cada una, y la entidad débil <code>DetallePedido</code> con su discriminador.</li>
<li>Piensa en un sistema que uses a diario, una app de mensajería, una plataforma de streaming, un sistema de matrícula, e identifica al menos una entidad fuerte, una relación con un atributo propio y, si la hay, una entidad débil.</li>
</ol>
<p>Hoy quedaron listas las piezas sueltas, la entidad, el atributo, la relación y la clave, pero todavía falta una parte central del modelo, cuántas entidades de un lado se pueden asociar con cuántas del otro. El Tema 2 de esta unidad retoma exactamente la misma cafetería, con las mismas entidades que acabas de conocer, y le agrega la notación completa de Chen y la notación de pata de gallo, la cardinalidad uno a uno, uno a muchos y muchos a muchos, y la participación total y parcial, hasta cerrar con el diagrama entidad relación completo de la cafetería, la primera pieza terminada de principio a fin de todo el curso.</p>
</section>
<section id="recursos" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="recursos"><span class="header-section-number">9</span> Recursos</h2>
<ul>
<li>Silberschatz, A., Korth, H. F. y Sudarshan, S. <em>Fundamentos de bases de datos.</em> Capítulo 6, diseño de bases de datos usando el modelo entidad relación. Material de apoyo oficial de los autores en <a href="https://www.db-book.com">db-book.com</a>.</li>
<li>Silberschatz, A., Korth, H. F. y Sudarshan, S. <em>Fundamentos de bases de datos.</em> Capítulo 2, introducción al modelo relacional, sección de claves, superclave, clave candidata y clave primaria.</li>
<li>Silberschatz, A., Korth, H. F. y Sudarshan, S. <em>Fundamentos de bases de datos.</em> Capítulo 7, diseño de bases de datos relacionales, definición formal de superclave y clave candidata mediante dependencias funcionales.</li>
<li>Elmasri, R. y Navathe, S. B. <em>Fundamentals of Database Systems.</em> Capítulo de modelado con el modelo entidad relación, entidades, atributos, relaciones y claves.</li>
<li>Connolly, T. M. y Begg, C. E. <em>Database Systems: A Practical Approach to Design, Implementation, and Management.</em> Capítulo de modelado entidad relación.</li>
<li>Chen, P. P.-S. (1976). <em>The Entity-Relationship Model, Toward a Unified View of Data.</em> ACM Transactions on Database Systems, 1(1), 9 a 36. DOI: 10.1145/320434.320440. Artículo original que introdujo el modelo entidad relación y su notación.</li>
<li><a href="https://www.db-book.com/slides-dir/PDF-dir/ch6.pdf">Diapositivas oficiales del capítulo 6, db-book.com</a></li>
<li><a href="https://www.db-book.com/slides-dir/PDF-dir/ch2.pdf">Diapositivas oficiales del capítulo 2, db-book.com</a></li>
<li><a href="https://www.db-book.com/slides-dir/PDF-dir/ch7.pdf">Diapositivas oficiales del capítulo 7, db-book.com</a></li>
<li><a href="https://www.db-book.com/">Sitio oficial del libro, db-book.com</a></li>
</ul>
<div class="pie-doc">
<p>Base de datos (DBA03). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>