<!DOCTYPE html>
<html lang="es"><head>
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Oscar Leonel Sánchez Conde">
  <title>Tema 1. Las piezas con las que se dibuja la realidad</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../../site_libs/revealjs/dist/theme/quarto-54c1bed68faba7d40addbad1d35990bb.css">
  <link href="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Tema 1. Las piezas con las que se dibuja la realidad</h1>
  <p class="subtitle">Base de datos (DBA03). Unidad 2</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Oscar Leonel Sánchez Conde 
</div>
</div>
</div>

</section>
<section id="recorrido-de-la-sesión" class="slide level2 center">
<h2>Recorrido de la sesión</h2>
<div class="tarjetas">
<div class="clave">
<p><span class="titulo">1. Entidades</span></p>
<p>Qué es una entidad y un conjunto de entidades, concretas y abstractas, fuertes y débiles.</p>
</div>
<div class="tarjeta">
<p><span class="titulo">2. Atributos</span></p>
<p>Las cuatro formas de describir una entidad, y cuál atributo la identifica.</p>
</div>
<div class="tarjeta">
<p><span class="titulo">3. Relaciones</span></p>
<p>Cómo se conectan las entidades entre sí, y una primera mirada a cuántas veces se conectan.</p>
</div>
<div class="tarjeta">
<p><span class="titulo">4. Claves</span></p>
<p>Cómo se identifica sin ambigüedad cada entidad.</p>
</div>
</div>
<div class="neutro">
<p>No partimos de cero. Partimos de la tabla que ya analizaron la clase pasada. Hoy le ponemos nombre técnico a lo que ustedes mismos encontraron.</p>
</div>
</section>
<section id="lo-que-ya-encontraron-la-clase-pasada" class="slide level2 center">
<h2>Lo que ya encontraron la clase pasada</h2>
<p>Esta es la misma tabla de pedidos de la cafetería que trabajaron en la actividad diagnóstica.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Cliente</th>
<th>Teléfono(s)</th>
<th>Pedido</th>
<th>Producto</th>
<th>Cantidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ana Ruiz</td>
<td>3001112233, 6045551122</td>
<td>1001</td>
<td>Café americano</td>
<td>2</td>
</tr>
<tr class="even">
<td>Ana Ruiz</td>
<td>3001112233, 6045551122</td>
<td>1001</td>
<td>Torta de chocolate</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Luis Peña</td>
<td>3014445566</td>
<td>1002</td>
<td>Capuchino</td>
<td>1</td>
</tr>
<tr class="even">
<td>María López</td>
<td>3157778899, 3205556677</td>
<td>1003</td>
<td>Café americano</td>
<td>3</td>
</tr>
<tr class="odd">
<td>María López</td>
<td>3157778899, 3205556677</td>
<td>1003</td>
<td>Jugo de naranja</td>
<td>2</td>
</tr>
<tr class="even">
<td>Ana Ruiz</td>
<td>3001112233, 6045551122</td>
<td>1004</td>
<td>Jugo de naranja</td>
<td>1</td>
</tr>
</tbody>
</table>
<div class="destacado">
<p>Ya respondieron diez preguntas sobre esta tabla: qué tipos de cosas hay, en qué grupos las separarían, qué las diferencia entre sí y qué se está repitiendo sin necesidad. Hoy convertimos esas respuestas en el modelo entidad relación.</p>
</div>
</section>
<section id="reto-qué-tipos-de-cosas-distintas-hay-en-la-tabla" class="slide level2 center">
<h2>Reto: qué tipos de cosas distintas hay en la tabla</h2>
<div class="destacado">
<p>Si tuvieran que separar esta información en varios grupos, cada uno con su propia identidad, ¿cuáles grupos crearían? ¿Qué los distingue?</p>
</div>
</section>
<section id="lo-que-ya-identificaron-tres-tipos-de-cosas" class="slide level2 center">
<h2>Lo que ya identificaron: tres tipos de cosas</h2>
<div class="tarjetas">
<div class="clave">
<p><span class="titulo">Cliente</span></p>
<p>Ana Ruiz, Luis Peña, María López. Cada uno es distinguible de los demás.</p>
</div>
<div class="tarjeta">
<p><span class="titulo">Pedido</span></p>
<p>1001, 1002, 1003, 1004. Cada uno ocurrió en una fecha y le pertenece a un cliente.</p>
</div>
<div class="tarjeta">
<p><span class="titulo">Producto</span></p>
<p>Café americano, capuchino, torta de chocolate, jugo de naranja.</p>
</div>
</div>
<div class="destacado">
<p><strong>Entidad</strong>: un objeto que existe y se puede distinguir de cualquier otro objeto.</p>
<p><strong>Conjunto de entidades</strong>: un grupo de entidades del mismo tipo, que comparten los mismos atributos.</p>
</div>
<div class="neutro">
<p>Silberschatz, Korth y Sudarshan lo definen así en <em>Fundamentos de bases de datos</em>. <code>Cliente</code> es el conjunto, el tipo. Ana Ruiz es una entidad, un caso concreto de ese tipo.</p>
</div>
</section>
<section id="entidad-y-conjunto-de-entidades" class="slide level2 center">
<h2>Entidad y conjunto de entidades</h2>
<div class="neutro">
<p>En el diagrama solo se dibuja el rectángulo, el conjunto. Las personas reales no se dibujan, son datos que pertenecen a ese conjunto.</p>
</div>
<div class="diagrama corto">
<svg viewbox="0 0 700 190" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Un unico rectangulo representa la entidad Cliente, la unica notacion formal; a la derecha, en texto simple sin rectangulo, se listan tres entidades de ese conjunto, Ana Ruiz, Luis Pena y Maria Lopez" font-family="Segoe UI, Inter, system-ui, sans-serif">
<rect x="40" y="45" width="220" height="100" rx="10" fill="#e4f2f1" stroke="#8fc9c5" stroke-width="2"></rect> <text x="150" y="100" font-size="18" font-weight="700" fill="#0e6f6c" text-anchor="middle">Cliente</text> <text x="150" y="70" font-size="10.5" fill="#5b6876" text-anchor="middle">así se dibuja un conjunto de entidades</text> <line x1="260" y1="95" x2="330" y2="95" stroke="#8fb3d1" stroke-width="1.6" stroke-dasharray="4 3"></line> <text x="360" y="65" font-size="11.5" fill="#5b6876">tres entidades de ese conjunto,</text> <text x="360" y="82" font-size="11.5" fill="#5b6876">en texto simple, no en el diagrama</text> <text x="360" y="108" font-size="13" font-weight="600" fill="#12324f">Ana Ruiz</text> <text x="360" y="128" font-size="13" font-weight="600" fill="#12324f">Luis Peña</text> <text x="360" y="148" font-size="13" font-weight="600" fill="#12324f">María López</text>
</svg>
</div>
</section>
<section id="entidades-concretas-y-entidades-abstractas" class="slide level2 center">
<h2>Entidades concretas y entidades abstractas</h2>
<div class="destacado">
<p>Miren otra vez <code>Cliente</code>, <code>Pedido</code> y <code>Producto</code>. ¿Cuáles se pueden señalar o tocar? ¿Y cuál no tiene esa forma física, aunque sea igual de real para el negocio?</p>
</div>
<div class="columns">
<div class="column" style="width:48%;">
<div class="neutro">
<p><strong>Entidad concreta</strong></p>
<p>Se puede señalar o tocar en el mundo físico. <code>Cliente</code> y <code>Producto</code>, en la cafetería.</p>
</div>
</div><div class="column" style="width:48%;">
<div class="tarjeta">
<p><strong>Entidad abstracta</strong></p>
<p>No tiene existencia física propia, es un evento o un concepto, pero el negocio la necesita igual de identificada. <code>Pedido</code>, en la cafetería.</p>
</div>
</div></div>
<div class="diagrama corto">
<svg viewbox="0 0 700 190" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A la izquierda dos rectangulos de linea continua para las entidades concretas Cliente y Producto; a la derecha un rectangulo de linea punteada para la entidad abstracta Pedido, que representa un evento y no un objeto fisico" font-family="Segoe UI, Inter, system-ui, sans-serif">
<rect x="20" y="55" width="180" height="80" rx="10" fill="#eef4fa" stroke="#8fb3d1" stroke-width="2"></rect> <text x="110" y="90" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Cliente</text> <text x="110" y="110" font-size="11" fill="#5b6876" text-anchor="middle">se puede señalar</text> <rect x="250" y="55" width="180" height="80" rx="10" fill="#eef4fa" stroke="#8fb3d1" stroke-width="2"></rect> <text x="340" y="90" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Producto</text> <text x="340" y="110" font-size="11" fill="#5b6876" text-anchor="middle">se puede tocar</text> <rect x="500" y="55" width="180" height="80" rx="10" fill="#f5f7fa" stroke="#8fc9c5" stroke-width="2" stroke-dasharray="6 4"></rect> <text x="590" y="90" font-size="13.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Pedido</text> <text x="590" y="110" font-size="11" fill="#5b6876" text-anchor="middle">un evento, no un objeto</text> <text x="350" y="165" font-size="11.5" fill="#5b6876" text-anchor="middle">las tres son entidades igual de válidas, aunque solo dos se puedan tocar</text>
</svg>
</div>
</section>
<section id="la-misma-idea-en-otros-negocios" class="slide level2 center">
<h2>La misma idea, en otros negocios</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Campo</th>
<th>Entidad</th>
<th>Tipo</th>
<th>Qué la distingue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cafetería</td>
<td><code>Cliente</code></td>
<td>concreta</td>
<td><code>id_cliente</code></td>
</tr>
<tr class="even">
<td>Cafetería</td>
<td><code>Pedido</code></td>
<td>abstracta</td>
<td><code>numero_pedido</code></td>
</tr>
<tr class="odd">
<td>Universidad</td>
<td><code>Estudiante</code></td>
<td>concreta</td>
<td><code>codigo_estudiante</code></td>
</tr>
<tr class="even">
<td>Aerolínea</td>
<td><code>Vuelo</code></td>
<td>abstracta</td>
<td><code>numero_vuelo</code> más <code>fecha</code></td>
</tr>
</tbody>
</table>
<div class="neutro">
<p>Un vuelo no se toca, pero pasa en una fecha concreta y tiene asientos concretos ocupándolo. Igual que un pedido, es abstracto y de todas formas necesita su propia identidad.</p>
</div>
</section>
<section id="entidades-fuertes-y-débiles" class="slide level2 center">
<h2>Entidades fuertes y débiles</h2>
<div class="destacado">
<p>Piensen en la pregunta 9 de la actividad diagnóstica: la cantidad de café que pidió Ana Ruiz, ¿es del café en general o de ese pedido en particular? Esa misma pregunta separa dos tipos de entidad.</p>
</div>
<div class="columns">
<div class="column" style="width:48%;">
<div class="neutro">
<p><strong>Entidad fuerte</strong></p>
<p>Tiene atributos propios suficientes para identificarse sola. <code>Cliente</code>, <code>Pedido</code> y <code>Producto</code>.</p>
</div>
</div><div class="column" style="width:48%;">
<div class="tarjeta">
<p><strong>Entidad débil</strong></p>
<p>Depende de otra para existir, y toma prestada su clave más un discriminador propio.</p>
</div>
</div></div>
<div class="neutro">
<p>Cada línea de un pedido, el renglón que dice qué producto se pidió y en qué cantidad, solo existe dentro de ese pedido. A eso lo llamamos <code>DetallePedido</code>, y volvemos sobre él más adelante, al hablar de relaciones.</p>
</div>
</section>
<section id="detallepedido-una-entidad-débil" class="slide level2 center">
<h2>DetallePedido, una entidad débil</h2>
<div class="diagrama corto">
<svg viewbox="0 0 700 190" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Pedido es entidad fuerte con numero_pedido subrayado; DetallePedido es entidad debil con doble rectangulo, conectada por la relacion identificadora tiene en doble rombo, con el discriminador numero_linea subrayado con linea punteada" font-family="Segoe UI, Inter, system-ui, sans-serif">
<rect x="10" y="50" width="170" height="100" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="95" y="76" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Pedido</text> <text x="95" y="102" font-size="12" fill="#12324f" text-anchor="middle" text-decoration="underline">numero_pedido</text> <text x="95" y="122" font-size="12" fill="#12324f" text-anchor="middle">fecha</text> <polygon points="285,55 350,100 285,145 220,100" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <polygon points="285,66 340,100 285,134 230,100" fill="none" stroke="#8fc9c5"></polygon> <text x="285" y="96" font-size="11.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">tiene</text> <text x="285" y="112" font-size="10.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">identificadora</text> <line x1="180" y1="100" x2="220" y2="100" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="350" y1="100" x2="490" y2="100" stroke="#8fb3d1" stroke-width="1.8"></line> <rect x="490" y="45" width="200" height="112" rx="9" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="497" y="52" width="186" height="98" rx="7" fill="none" stroke="#c7d6e6"></rect> <text x="590" y="76" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">DetallePedido</text> <line x1="545" y1="93" x2="635" y2="93" stroke="#12324f" stroke-width="1.2" stroke-dasharray="3 2"></line> <text x="590" y="90" font-size="11.5" fill="#12324f" text-anchor="middle">numero_linea</text> <text x="590" y="112" font-size="11.5" fill="#12324f" text-anchor="middle">cantidad</text> <text x="590" y="132" font-size="11.5" fill="#12324f" text-anchor="middle">producto</text> <text x="350" y="180" font-size="11.5" fill="#5b6876" text-anchor="middle">clave completa de DetallePedido = numero_pedido (heredado) + numero_linea</text>
</svg>
</div>
</section>
<section id="reto-qué-columnas-describen-a-cada-entidad" class="slide level2 center">
<h2>Reto: qué columnas describen a cada entidad</h2>
<div class="destacado">
<p>Elijan <code>Cliente</code>. De las columnas de la tabla, ¿cuáles describen a un cliente? Y de esas, ¿cuál sola alcanza para diferenciar un cliente de otro?</p>
</div>
</section>
<section id="lo-que-ya-encontraron-atributos-y-el-que-identifica" class="slide level2 center">
<h2>Lo que ya encontraron: atributos, y el que identifica</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><span class="titulo">nombre</span></p>
<p>Describe al cliente. Atributo normal.</p>
</div>
<div class="tarjeta">
<p><span class="titulo">teléfono</span></p>
<p>Describe al cliente. Atributo normal.</p>
</div>
<div class="clave">
<p><span class="titulo">id_cliente</span></p>
<p>Solo este basta para diferenciar un cliente de otro. Atributo clave.</p>
</div>
</div>
<div class="destacado">
<p><strong>Atributo</strong>: una propiedad descriptiva que tienen todas las entidades de un conjunto. <strong>Atributo clave</strong>: el que, por sí solo, distingue sin ambigüedad a cada entidad. <strong>Atributo normal</strong>: describe la entidad, pero no alcanza para distinguirla de las demás.</p>
</div>
</section>
<section id="las-cuatro-formas-de-atributo" class="slide level2 center">
<h2>Las cuatro formas de atributo</h2>
<div class="destacado">
<p>Miren <code>telefono</code>, <code>nombre</code> y una posible <code>antiguedad</code> como cliente. ¿Todos guardan su valor de la misma forma, o hay diferencias en cómo se comporta cada uno?</p>
</div>
<div class="tarjetas">
<div class="tarjeta">
<p><span class="titulo">Simple</span></p>
<p>No se subdivide. <code>id_cliente</code>.</p>
</div>
<div class="tarjeta">
<p><span class="titulo">Compuesto</span></p>
<p>Se divide en partes con sentido propio. <code>nombre</code> en <code>primer_nombre</code> y <code>apellido</code>.</p>
</div>
<div class="clave">
<p><span class="titulo">Multivaluado</span></p>
<p>Varios valores a la vez. Justo lo que vieron en la columna Teléfono(s): dos números en una sola celda.</p>
</div>
<div class="tarjeta">
<p><span class="titulo">Derivado</span></p>
<p>Se calcula, no se guarda. <code>antiguedad</code> desde <code>fecha_registro</code>.</p>
</div>
</div>
</section>
<section id="las-mismas-cuatro-formas-en-otros-campos" class="slide level2 center">
<h2>Las mismas cuatro formas, en otros campos</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><span class="titulo">Simple</span></p>
<p><code>numero_historia_clinica</code> de un <code>Paciente</code>, en un hospital.</p>
</div>
<div class="tarjeta">
<p><span class="titulo">Compuesto</span></p>
<p><code>direccion</code> de un <code>Estudiante</code>, dividida en <code>calle</code>, <code>ciudad</code> y <code>codigo_postal</code>, en una universidad.</p>
</div>
<div class="clave">
<p><span class="titulo">Multivaluado</span></p>
<p><code>idiomas</code> que habla un <code>Piloto</code>, en una aerolínea.</p>
</div>
<div class="tarjeta">
<p><span class="titulo">Derivado</span></p>
<p><code>edad</code> de un <code>Paciente</code>, calculada desde <code>fecha_nacimiento</code>, en un hospital.</p>
</div>
</div>
<div class="neutro">
<p>La forma del atributo no cambia de un negocio a otro. Lo que cambia es si ese dato se subdivide, si admite varios valores a la vez, o si se calcula en vez de guardarse.</p>
</div>
</section>
<section id="lo-que-ya-señalaron-el-teléfono-no-cabe-en-una-sola-columna" class="slide level2 center">
<h2>Lo que ya señalaron: el teléfono no cabe en una sola columna</h2>
<div class="neutro">
<p>En la pregunta 8 de la actividad ya dijeron que dos teléfonos en una celda no es una buena forma de organizar la información. Esto es exactamente por qué.</p>
</div>
<div class="diagrama corto">
<svg viewbox="0 0 700 200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A la izquierda una tabla Cliente con telefono aplanado en una sola columna con dos numeros separados por coma; a la derecha el esquema correcto con dos tablas, Cliente sin telefono y Cliente_Telefono con una fila por cada numero" font-family="Segoe UI, Inter, system-ui, sans-serif">
<rect x="10" y="20" width="320" height="30" rx="6" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="170" y="40" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Cliente, teléfono aplanado (mal diseñado)</text> <rect x="10" y="52" width="320" height="66" rx="8" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="26" y="76" font-size="11.5" fill="#12324f">id_cliente = C001, nombre = Ana Ruiz</text> <text x="26" y="96" font-size="11.5" fill="#0e6f6c">telefono = “3001112233,6045551122”</text> <text x="26" y="112" font-size="10.5" fill="#5b6876">un solo texto con dos números adentro</text> <rect x="380" y="20" width="140" height="30" rx="6" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="450" y="40" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Cliente</text> <rect x="380" y="52" width="140" height="50" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="394" y="72" font-size="11" fill="#12324f">id_cliente = C001</text> <text x="394" y="90" font-size="11" fill="#12324f">nombre = Ana Ruiz</text> <rect x="545" y="20" width="155" height="30" rx="6" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="622" y="40" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">Cliente_Telefono</text> <rect x="545" y="52" width="155" height="66" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="559" y="72" font-size="10.5" fill="#12324f">id=C001, telefono=3001112233</text> <text x="559" y="90" font-size="10.5" fill="#12324f">id=C001, telefono=6045551122</text> <text x="559" y="100" font-size="10" fill="#0e6f6c">una fila por número,</text> <text x="559" y="112" font-size="10" fill="#0e6f6c">misma clave</text> <text x="350" y="150" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">borrar un teléfono en la versión aplanada obliga a reescribir toda la columna</text> <text x="170" y="176" font-size="11" fill="#5b6876" text-anchor="middle">buscar exige leer y partir el texto completo</text> <text x="600" y="176" font-size="11" fill="#5b6876" text-anchor="middle">buscar es una fila más en Cliente_Telefono</text>
</svg>
</div>
</section>
<section id="cuándo-pasar-un-atributo-a-entidad" class="slide level2 center">
<h2>Cuándo pasar un atributo a entidad</h2>
<div class="destacado">
<p>¿El dato necesita información adicional propia, o admite varios valores que conviene consultar por separado? Si la respuesta es sí, asciende a entidad.</p>
</div>
<div class="tarjetas">
<div class="tarjeta">
<p><span class="titulo">Se queda como atributo</span></p>
<p><code>telefono</code> de <code>Cliente</code>, mientras solo interese guardar el número.</p>
</div>
<div class="clave">
<p><span class="titulo">Asciende a entidad</span></p>
<p>Si además hace falta el operador de cada línea o cuál es el preferido, <code>Telefono(numero, operador, es_preferido)</code> relacionado con <code>Cliente</code>.</p>
</div>
</div>
</section>
<section id="reto-cómo-se-conectan-cliente-pedido-y-producto" class="slide level2 center">
<h2>Reto: cómo se conectan Cliente, Pedido y Producto</h2>
<div class="destacado">
<p>¿Qué conecta a <code>Cliente</code> con <code>Pedido</code>? ¿Y qué conecta a <code>Pedido</code> con <code>Producto</code>?</p>
</div>
</section>
<section id="lo-revelamos-dos-relaciones" class="slide level2 center">
<h2>Lo revelamos: dos relaciones</h2>
<div class="destacado">
<p><strong>Relación</strong>: una asociación entre entidades. <strong>Conjunto de relaciones</strong>: el conjunto de esas asociaciones entre dos o más conjuntos de entidades.</p>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Campo</th>
<th>Relación</th>
<th>Conecta</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cafetería</td>
<td><code>realiza</code></td>
<td><code>Cliente</code> con <code>Pedido</code></td>
</tr>
<tr class="even">
<td>Cafetería</td>
<td><code>incluye</code></td>
<td><code>Pedido</code> con <code>Producto</code></td>
</tr>
<tr class="odd">
<td>Universidad</td>
<td><code>se_matricula_en</code></td>
<td><code>Estudiante</code> con <code>Curso</code></td>
</tr>
<tr class="even">
<td>Hospital</td>
<td><code>atiende</code></td>
<td><code>Medico</code> con <code>Paciente</code></td>
</tr>
</tbody>
</table>
<div class="neutro">
<p>Todas son binarias, conectan exactamente dos conjuntos de entidades, el caso más común en este curso.</p>
</div>
</section>
<section id="ya-lo-habían-resuelto-la-cantidad-es-de-la-relación-no-del-producto" class="slide level2 center">
<h2>Ya lo habían resuelto: la cantidad es de la relación, no del producto</h2>
<div class="neutro">
<p>La pregunta 9 de la actividad pedía decidir si la cantidad pertenece al producto en general o a un pedido específico. Ya respondieron que depende del pedido. Eso significa que <code>cantidad</code> no es un atributo de <code>Producto</code>, es un atributo de la relación <code>incluye</code> entre <code>Pedido</code> y <code>Producto</code>.</p>
</div>
<div class="diagrama corto">
<svg viewbox="0 0 700 220" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="La entidad Pedido y la entidad Producto conectadas por la relacion incluye dibujada como un rombo, con su propio atributo cantidad colgando debajo" font-family="Segoe UI, Inter, system-ui, sans-serif">
<rect x="10" y="55" width="150" height="70" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="85" y="82" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Pedido</text> <text x="85" y="104" font-size="11.5" fill="#12324f" text-anchor="middle" text-decoration="underline">numero_pedido</text> <rect x="540" y="55" width="150" height="70" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="615" y="82" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Producto</text> <text x="615" y="104" font-size="11.5" fill="#12324f" text-anchor="middle" text-decoration="underline">codigo_producto</text> <polygon points="350,50 415,90 350,130 285,90" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <text x="350" y="95" font-size="12.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">incluye</text> <line x1="160" y1="90" x2="285" y2="90" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="415" y1="90" x2="540" y2="90" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="350" y1="130" x2="350" y2="153" stroke="#8fb3d1" stroke-width="1.6"></line> <ellipse cx="350" cy="177" rx="55" ry="24" fill="#f5f7fa" stroke="#cfd8e3"></ellipse> <text x="350" y="181" font-size="12" fill="#12324f" text-anchor="middle">cantidad</text> <text x="350" y="213" font-size="10.5" fill="#5b6876" text-anchor="middle">propio de cada pedido concreto, no del producto en general</text>
</svg>
</div>
<div class="neutro">
<p>Es la misma idea que <code>DetallePedido</code>, que ya vimos con las entidades, dibujada de otra forma. Una relación con atributo propio y una entidad débil identificadora describen el mismo hecho del negocio.</p>
</div>
</section>
<section id="relación-recursiva" class="slide level2 center">
<h2>Relación recursiva</h2>
<div class="diagrama corto">
<svg viewbox="0 0 700 220" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="La entidad Asignatura relacionada consigo misma mediante la relacion recursiva es_prerrequisito_de; dos lineas salen del mismo rombo hacia la misma entidad, una con el rol asignatura y otra con el rol prerrequisito" font-family="Segoe UI, Inter, system-ui, sans-serif">
<polygon points="350,25 415,63 350,101 285,63" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <text x="350" y="67" font-size="11.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">es prerrequisito de</text> <rect x="250" y="150" width="200" height="60" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="350" y="176" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Asignatura</text> <text x="350" y="196" font-size="11.5" fill="#12324f" text-anchor="middle" text-decoration="underline">codigo_asignatura</text> <path d="M285,63 C220,95 240,132 280,150" fill="none" stroke="#8fb3d1" stroke-width="1.7"></path> <path d="M415,63 C480,95 450,132 420,150" fill="none" stroke="#8fb3d1" stroke-width="1.7"></path> <text x="190" y="112" font-size="11" fill="#12324f" text-anchor="middle">rol: asignatura</text> <text x="510" y="112" font-size="11" fill="#12324f" text-anchor="middle">rol: prerrequisito</text>
</svg>
</div>
<div class="fuente">
<p>Caso real de este programa: Base de datos tiene como prerrequisito a Estructura de datos.</p>
</div>
</section>
<section id="el-grado-de-una-relación" class="slide level2 center">
<h2>El grado de una relación</h2>
<div class="tarjetas">
<div class="clave">
<p><span class="titulo">Binaria</span></p>
<p>Dos conjuntos de entidades. La mayoría de las relaciones del curso, como <code>realiza</code> e <code>incluye</code>.</p>
</div>
<div class="tarjeta">
<p><span class="titulo">Ternaria o mayor</span></p>
<p>Tres o más conjuntos a la vez, como <code>instructor</code>, <code>student</code> y <code>project</code> en un mismo proyecto.</p>
</div>
</div>
<div class="destacado">
<p>En una relación de grado mayor que dos, como máximo una línea puede llevar flecha de cardinalidad, para no dejar el diagrama con más de una lectura posible.</p>
</div>
</section>
<section id="primera-mirada-cuántas-veces-se-conecta" class="slide level2 center">
<h2>Primera mirada: cuántas veces se conecta</h2>
<div class="destacado">
<p><strong>Cardinalidad</strong>: cuántas veces, como máximo, participa cada entidad en la relación.</p>
</div>
<div class="diagrama corto">
<svg viewbox="0 0 700 170" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cliente conectado a Pedido con cardinalidad 1 a N, y Pedido conectado a Producto con cardinalidad N a M, evidenciado con los datos de la tabla de la cafeteria" font-family="Segoe UI, Inter, system-ui, sans-serif">
<rect x="10" y="55" width="140" height="60" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="80" y="90" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Cliente</text> <line x1="150" y1="85" x2="290" y2="85" stroke="#8fb3d1" stroke-width="1.8"></line> <text x="170" y="76" font-size="12" font-weight="700" fill="#0e6f6c">1</text> <text x="270" y="76" font-size="12" font-weight="700" fill="#0e6f6c">N</text> <rect x="290" y="55" width="140" height="60" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="360" y="90" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Pedido</text> <line x1="430" y1="85" x2="570" y2="85" stroke="#8fb3d1" stroke-width="1.8"></line> <text x="450" y="76" font-size="12" font-weight="700" fill="#0e6f6c">N</text> <text x="550" y="76" font-size="12" font-weight="700" fill="#0e6f6c">M</text> <rect x="570" y="55" width="120" height="60" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="630" y="90" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Producto</text> <text x="350" y="145" font-size="11" fill="#5b6876" text-anchor="middle">Ana Ruiz: tres pedidos (1 a N). El café americano: en dos pedidos, cada pedido con varios productos (N a M)</text>
</svg>
</div>
</section>
<section id="reto-y-si-dos-clientes-se-llamaran-igual" class="slide level2 center">
<h2>Reto: y si dos clientes se llamaran igual</h2>
<div class="destacado">
<p>Imaginen que, además de Ana Ruiz (C001), otra clienta nueva también se llamara Ana Ruiz, con id C004. ¿Serviría el <code>nombre</code> como clave? ¿Qué columna sí serviría, siempre, sin importar cuántas Ana Ruiz existan?</p>
</div>
</section>
<section id="lo-que-ya-respondieron-id_cliente-sí-nombre-no" class="slide level2 center">
<h2>Lo que ya respondieron: id_cliente sí, nombre no</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><span class="titulo">nombre no sirve</span></p>
<p>Con dos Ana Ruiz en la tabla, esta columna ya no distingue a una clienta de otra.</p>
</div>
<div class="clave">
<p><span class="titulo">id_cliente sí sirve</span></p>
<p>Nunca se repite, sin importar cuántas clientas se llamen igual.</p>
</div>
</div>
</section>
<section id="definición" class="slide level2 center">
<h2>Definición</h2>
<div class="destacado">
<p><strong>Superclave</strong>: un conjunto de atributos que identifica sin ambigüedad a cada entidad, para cualquier estado posible de la base de datos.</p>
<p><strong>Clave candidata</strong>: una superclave mínima, ningún subconjunto suyo sigue siendo superclave.</p>
<p><strong>Clave primaria</strong>: la clave candidata que el diseñador elige para identificar entidades en el resto del modelo.</p>
</div>
</section>
<section id="de-superclave-a-clave-primaria" class="slide level2 center">
<h2>De superclave a clave primaria</h2>
<div class="diagrama corto">
<svg viewbox="0 0 700 220" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="El rectangulo mas grande agrupa las superclaves de Cliente, dentro un rectangulo mas chico marca la unica clave candidata, y dentro de este el rectangulo mas interno marca la clave primaria elegida, id_cliente" font-family="Segoe UI, Inter, system-ui, sans-serif">
<rect x="10" y="20" width="420" height="180" rx="12" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="26" y="42" font-size="12" font-weight="700" fill="#12324f">superclaves de Cliente</text> <rect x="34" y="58" width="190" height="120" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="50" y="78" font-size="11.5" font-weight="700" fill="#0e6f6c">clave candidata</text> <text x="50" y="94" font-size="10.5" fill="#5b6876">superclave mínima</text> <rect x="50" y="104" width="145" height="46" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="122" y="124" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">id_cliente</text> <text x="122" y="140" font-size="10.5" fill="#0e6f6c" text-anchor="middle">clave primaria elegida</text> <g font-size="10.5" fill="#12324f"><text x="245" y="78">id_cliente, nombre</text><text x="245" y="98">id_cliente, telefono</text><text x="245" y="118">id_cliente, nombre, telefono</text></g> <text x="245" y="140" font-size="10.5" fill="#5b6876">superclaves válidas, pero no mínimas</text> <rect x="470" y="45" width="220" height="150" rx="12" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="580" y="66" font-size="12" font-weight="700" fill="#12324f" text-anchor="middle">esto no sirve de clave</text> <text x="484" y="94" font-size="11" fill="#12324f">nombre</text> <text x="484" y="110" font-size="10.5" fill="#5b6876">se repetiría con la nueva Ana Ruiz</text> <text x="484" y="140" font-size="11" fill="#12324f">telefono</text> <text x="484" y="156" font-size="10.5" fill="#5b6876">único hoy, pero no garantizado</text>
</svg>
</div>
</section>
<section id="lo-que-te-llevas-de-hoy" class="slide level2 center">
<h2>Lo que te llevas de hoy</h2>
<div class="destacado">
<p>Hoy armaron las cuatro piezas con las que se dibuja cualquier negocio, partiendo de la misma tabla que ya habían analizado.</p>
</div>
<div class="neutro">
<p>La <strong>entidad</strong> distingue un objeto de cualquier otro de su mismo tipo, puede ser concreta o abstracta, y fuerte, si se identifica sola, o débil, si depende de otra y necesita un discriminador. El <strong>atributo</strong> describe esa entidad, en cuatro formas, simple, compuesto, multivaluado o derivado, y uno de ellos es la clave que la identifica. La <strong>relación</strong> conecta entidades entre sí, con su propio grado, sus roles, a veces su propio atributo, y una cardinalidad que dice cuántas veces se conecta, tema de la próxima clase. Y la <strong>clave</strong> garantiza que, sin ambigüedad y para siempre, cada entidad se pueda distinguir de las demás.</p>
</div>
</section>
<section id="el-diagrama-completo-de-la-cafetería" class="slide level2 center">
<h2>El diagrama completo de la cafetería</h2>
<div class="diagrama">
<svg viewbox="0 0 980 400" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Diagrama entidad relacion completo de la cafeteria: Cliente con id_cliente, nombre y telefono multivaluado, relacionado por realiza en cardinalidad 1 a N con Pedido, que tiene numero_pedido y fecha; Pedido relacionado por incluye en cardinalidad N a M con Producto, que tiene codigo_producto, nombre y precio; la relacion incluye trae el atributo propio cantidad" font-family="Segoe UI, Inter, system-ui, sans-serif">
<rect x="10" y="120" width="190" height="150" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="105" y="146" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">Cliente</text> <text x="105" y="168" font-size="12" fill="#12324f" text-anchor="middle" text-decoration="underline">id_cliente</text> <text x="105" y="188" font-size="12" fill="#12324f" text-anchor="middle">nombre</text> <ellipse cx="105" cy="230" rx="70" ry="24" fill="none" stroke="#8fc9c5" stroke-width="1.4"></ellipse> <ellipse cx="105" cy="230" rx="63" ry="18" fill="#f5f7fa" stroke="#cfd8e3"></ellipse> <text x="105" y="234" font-size="11.5" fill="#12324f" text-anchor="middle">telefono</text> <line x1="200" y1="190" x2="270" y2="190" stroke="#8fb3d1" stroke-width="1.8"></line> <polygon points="270,150 335,190 270,230 205,190" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <text x="270" y="185" font-size="11.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">realiza</text> <text x="270" y="200" font-size="10" font-weight="700" fill="#0e6f6c" text-anchor="middle">1 : N</text> <line x1="335" y1="190" x2="405" y2="190" stroke="#8fb3d1" stroke-width="1.8"></line> <rect x="405" y="120" width="180" height="140" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="495" y="146" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">Pedido</text> <text x="495" y="168" font-size="12" fill="#12324f" text-anchor="middle" text-decoration="underline">numero_pedido</text> <text x="495" y="188" font-size="12" fill="#12324f" text-anchor="middle">fecha</text> <line x1="585" y1="190" x2="655" y2="190" stroke="#8fb3d1" stroke-width="1.8"></line> <polygon points="655,150 720,190 655,230 590,190" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <text x="655" y="185" font-size="11.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">incluye</text> <text x="655" y="200" font-size="10" font-weight="700" fill="#0e6f6c" text-anchor="middle">N : M</text> <line x1="655" y1="230" x2="655" y2="270" stroke="#8fb3d1" stroke-width="1.6"></line> <ellipse cx="655" cy="292" rx="55" ry="22" fill="#f5f7fa" stroke="#cfd8e3"></ellipse> <text x="655" y="296" font-size="11.5" fill="#12324f" text-anchor="middle">cantidad</text> <line x1="720" y1="190" x2="790" y2="190" stroke="#8fb3d1" stroke-width="1.8"></line> <rect x="790" y="120" width="180" height="150" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="880" y="146" font-size="14" font-weight="700" fill="#12324f" text-anchor="middle">Producto</text> <text x="880" y="168" font-size="12" fill="#12324f" text-anchor="middle" text-decoration="underline">codigo_producto</text> <text x="880" y="188" font-size="12" fill="#12324f" text-anchor="middle">nombre</text> <text x="880" y="208" font-size="12" fill="#12324f" text-anchor="middle">precio</text> <text x="490" y="350" font-size="12" fill="#5b6876" text-anchor="middle">tres entidades, sus atributos y claves, dos relaciones y su cardinalidad, un atributo propio de una relación</text>
</svg>
</div>
</section>
<section id="esto-ya-lo-habían-dibujado-ustedes" class="slide level2 center">
<h2>Esto ya lo habían dibujado ustedes</h2>
<div class="neutro">
<p>En la pregunta 10 de la actividad diagnóstica ya propusieron grupos, datos por grupo y conexiones entre ellos, en su propio lenguaje.</p>
</div>
<div class="destacado">
<p>Comparen su propuesta de esa pregunta contra el diagrama anterior. Lo que ustedes llamaron grupo, es entidad. Lo que ustedes llamaron dato de cada grupo, es atributo. Lo que ustedes llamaron conexión, es relación. La propuesta de la clase pasada ya era, en el fondo, un modelo entidad relación.</p>
</div>
</section>
<section id="ahora-aplican-el-mismo-procedimiento-a-un-caso-nuevo" class="slide level2 seccion" data-background-color="#12324f">
<h2>Ahora aplican el mismo procedimiento a un caso nuevo</h2>
<div class="rotulo">
<p>Para practicar, guiados</p>
</div>
<p>Con las mismas cuatro piezas, guiados paso a paso, resuelven un negocio distinto.</p>
</section>
<section id="el-caso-una-red-social" class="slide level2 center">
<h2>El caso: una red social</h2>
<p>Una red social permite que los usuarios publiquen contenido, que otros usuarios comenten esas publicaciones, y que cada usuario decida a quién seguir para ver su contenido en su muro.</p>
<ol type="1">
<li>Cada usuario tiene un nombre y uno o más intereses que sigue, por ejemplo deportes, tecnología o música.</li>
<li>Cada publicación tiene un texto y una fecha, y se hizo desde la web o desde el celular.</li>
<li>Cada comentario de una publicación tiene su propio texto y su propia fecha.</li>
<li>Un usuario puede seguir a otros usuarios, y un mismo usuario puede tener muchos seguidores.</li>
</ol>
</section>
<section id="antes-de-resolver" class="slide level2 center">
<h2>Antes de resolver</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><span class="titulo">1. Entidades</span></p>
<p>¿Qué objetos necesitan identidad propia?</p>
</div>
<div class="tarjeta">
<p><span class="titulo">2. Atributos</span></p>
<p>¿Cómo se describe cada uno?</p>
</div>
<div class="tarjeta">
<p><span class="titulo">3. Relaciones</span></p>
<p>¿Cómo se conectan?</p>
</div>
<div class="clave">
<p><span class="titulo">4. Claves</span></p>
<p>¿Qué los identifica sin ambigüedad?</p>
</div>
</div>
<p>Vamos a resolver el caso en ese mismo orden, y en cada paso van a ver por qué se toma esa decisión, no solo cuál es la respuesta.</p>
</section>
<section id="paso-1-qué-entidades-hacen-falta" class="slide level2 center">
<h2>Paso 1: ¿qué entidades hacen falta?</h2>
<div class="destacado">
<p>Antes de seguir, de los cuatro hechos del enunciado, decidan cuáles objetos necesitan identidad propia, y cuál de ellos no puede existir por sí solo.</p>
</div>
</section>
<section id="paso-1-solución-las-entidades-fuertes" class="slide level2 center">
<h2>Paso 1, solución: las entidades fuertes</h2>
<div class="columns">
<div class="column" style="width:48%;">
<div class="tarjeta">
<p><strong>Usuario</strong></p>
<p><code>id_usuario</code> por sí solo distingue a cualquier usuario de cualquier otro, sin apoyarse en nada más. Por eso es una entidad fuerte.</p>
</div>
</div><div class="column" style="width:48%;">
<div class="tarjeta">
<p><strong>Publicacion</strong></p>
<p><code>id_publicacion</code> por sí solo distingue a cualquier publicación. También es fuerte, aunque toda publicación tenga siempre un autor.</p>
</div>
</div></div>
<div class="neutro">
<p>El hecho de que una publicación siempre tenga un usuario detrás no la hace débil. Lo que decide si es débil es si tiene, o no, un atributo propio que baste para identificarla.</p>
</div>
</section>
<section id="paso-1-solución-la-entidad-débil" class="slide level2 center">
<h2>Paso 1, solución: la entidad débil</h2>
<div class="destacado">
<p>Un comentario no tiene sentido fuera de la publicación en la que aparece. Si esa publicación se borra, el comentario deja de tener a qué pertenecer.</p>
</div>
<div class="columns">
<div class="column" style="width:48%;">
<div class="neutro">
<p><strong>Comentario es débil</strong></p>
<p>Ni siquiera su propio texto alcanza para distinguirlo sin apoyarse en la publicación a la que pertenece.</p>
</div>
</div><div class="column" style="width:48%;">
<div class="clave">
<p><strong>Su propietario es Publicacion</strong></p>
<p>Toma prestada la clave de <code>Publicacion</code> y agrega un discriminador propio, <code>numero_comentario</code>, único solo dentro de esa publicación.</p>
</div>
</div></div>
</section>
<section id="paso-2-cómo-se-describe-cada-entidad" class="slide level2 center">
<h2>Paso 2: ¿cómo se describe cada entidad?</h2>
<div class="destacado">
<p>Antes de seguir, para <code>nombre</code> e <code>intereses</code> de <code>Usuario</code>, decidan en cuál de las cuatro formas de atributo cae cada uno, y por qué.</p>
</div>
</section>
<section id="paso-2-solución-los-atributos-de-usuario" class="slide level2 center">
<h2>Paso 2, solución: los atributos de Usuario</h2>
<div class="tarjetas">
<div class="tarjeta">
<p><span class="titulo">Compuesto</span></p>
<p><code>nombre</code>, se divide en <code>primer_nombre</code> y <code>apellido</code>, cada uno con sentido propio por separado.</p>
</div>
<div class="clave">
<p><span class="titulo">Multivaluado</span></p>
<p><code>intereses</code>, un mismo usuario puede seguir deportes y tecnología a la vez, sin que uno excluya al otro.</p>
</div>
<div class="tarjeta">
<p><span class="titulo">Derivado</span></p>
<p><code>antiguedad_cuenta</code>, no se guarda, se calcula restando <code>fecha_registro</code> de la fecha de hoy.</p>
</div>
</div>
<div class="neutro">
<p><code>intereses</code> también sigue siendo simple, cada interés individual, deportes, no se subdivide en partes con sentido propio.</p>
</div>
</section>
<section id="paso-2-solución-el-resto-de-las-entidades" class="slide level2 center">
<h2>Paso 2, solución: el resto de las entidades</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Entidad</th>
<th>Atributos simples</th>
<th>Discriminador</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Publicacion</code></td>
<td><code>id_publicacion</code>, <code>texto</code>, <code>fecha_publicacion</code></td>
<td>no aplica</td>
</tr>
<tr class="even">
<td><code>Comentario</code></td>
<td><code>texto_comentario</code>, <code>fecha_comentario</code></td>
<td><code>numero_comentario</code></td>
</tr>
</tbody>
</table>
<div class="neutro">
<p><code>Comentario</code> no necesita, por ahora, un atributo compuesto, multivaluado o derivado propio, solo su discriminador y dos atributos simples. Eso también es una decisión de diseño válida, no todas las entidades necesitan las cuatro formas a la vez.</p>
</div>
</section>
<section id="paso-3-cómo-se-conectan" class="slide level2 center">
<h2>Paso 3: ¿cómo se conectan?</h2>
<div class="destacado">
<p>Antes de seguir, respondan: ¿qué conecta a <code>Usuario</code> con <code>Publicacion</code>? ¿Qué conecta a <code>Publicacion</code> con <code>Comentario</code>, y por qué esa conexión es distinta de las demás? ¿Y qué conecta a un <code>Usuario</code> con otro <code>Usuario</code>?</p>
</div>
</section>
<section id="paso-3-solución-publica-y-recibe" class="slide level2 center">
<h2>Paso 3, solución: Publica y Recibe</h2>
<div class="diagrama">
<svg viewbox="0 0 920 230" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Usuario conectado por la relacion Publica con atributo dispositivo hacia Publicacion, y Publicacion conectada por la relacion identificadora doble Recibe hacia la entidad debil Comentario con su discriminador numero_comentario" font-family="Segoe UI, Inter, system-ui, sans-serif">
<rect x="10" y="55" width="150" height="90" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="85" y="90" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Usuario</text> <text x="85" y="112" font-size="11.5" fill="#12324f" text-anchor="middle" text-decoration="underline">id_usuario</text> <polygon points="180,100 235,55 290,100 235,145" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <text x="235" y="104" font-size="12" font-weight="700" fill="#0e6f6c" text-anchor="middle">Publica</text> <line x1="160" y1="100" x2="180" y2="100" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="290" y1="100" x2="335" y2="100" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="235" y1="145" x2="235" y2="163" stroke="#8fb3d1" stroke-width="1.6"></line> <ellipse cx="235" cy="185" rx="62" ry="22" fill="#f5f7fa" stroke="#cfd8e3"></ellipse> <text x="235" y="189" font-size="11.5" fill="#12324f" text-anchor="middle">dispositivo</text> <text x="235" y="221" font-size="10.5" fill="#5b6876" text-anchor="middle">web o movil, propio de cada publicacion concreta</text> <rect x="335" y="55" width="180" height="90" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="425" y="88" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Publicacion</text> <text x="425" y="110" font-size="11.5" fill="#12324f" text-anchor="middle" text-decoration="underline">id_publicacion</text> <polygon points="540,100 595,55 650,100 595,145" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <polygon points="550,100 595,63 640,100 595,137" fill="none" stroke="#8fc9c5"></polygon> <text x="595" y="96" font-size="11.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Recibe</text> <text x="595" y="112" font-size="10" font-weight="700" fill="#0e6f6c" text-anchor="middle">identificadora</text> <line x1="515" y1="100" x2="540" y2="100" stroke="#8fb3d1" stroke-width="1.8"></line> <line x1="650" y1="100" x2="695" y2="100" stroke="#8fb3d1" stroke-width="1.8"></line> <rect x="695" y="45" width="200" height="112" rx="9" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="702" y="52" width="186" height="98" rx="7" fill="none" stroke="#c7d6e6"></rect> <text x="795" y="76" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Comentario</text> <line x1="730" y1="93" x2="860" y2="93" stroke="#12324f" stroke-width="1.2" stroke-dasharray="3 2"></line> <text x="795" y="90" font-size="11" fill="#12324f" text-anchor="middle">numero_comentario</text> <text x="795" y="112" font-size="11.5" fill="#12324f" text-anchor="middle">texto_comentario</text> <text x="795" y="132" font-size="11.5" fill="#12324f" text-anchor="middle">fecha_comentario</text>
</svg>
</div>
<div class="neutro">
<p><code>Publica</code> conecta <code>Usuario</code> con <code>Publicacion</code>, y trae su propio atributo, <code>dispositivo</code>, porque ese dato describe cómo ocurrió esa publicación concreta, ni una propiedad permanente del usuario ni de la publicación en abstracto. <code>Recibe</code> conecta <code>Publicacion</code> con su entidad débil <code>Comentario</code>, así que se dibuja con rombo y rectángulo dobles, la relación identificadora.</p>
</div>
</section>
<section id="paso-3-solución-sigue-la-relación-recursiva" class="slide level2 center">
<h2>Paso 3, solución: Sigue, la relación recursiva</h2>
<div class="diagrama corto">
<svg viewbox="0 0 700 220" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="La entidad Usuario relacionada consigo misma mediante la relacion recursiva Sigue; dos lineas salen del mismo rombo hacia la misma entidad, una con el rol seguidor y otra con el rol seguido" font-family="Segoe UI, Inter, system-ui, sans-serif">
<polygon points="350,25 415,63 350,101 285,63" fill="#e4f2f1" stroke="#8fc9c5"></polygon> <text x="350" y="67" font-size="12" font-weight="700" fill="#0e6f6c" text-anchor="middle">sigue</text> <rect x="250" y="150" width="200" height="60" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="350" y="176" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Usuario</text> <text x="350" y="196" font-size="11.5" fill="#12324f" text-anchor="middle" text-decoration="underline">id_usuario</text> <path d="M285,63 C220,95 240,132 280,150" fill="none" stroke="#8fb3d1" stroke-width="1.7"></path> <path d="M415,63 C480,95 450,132 420,150" fill="none" stroke="#8fb3d1" stroke-width="1.7"></path> <text x="190" y="112" font-size="11" fill="#12324f" text-anchor="middle">rol: seguidor</text> <text x="510" y="112" font-size="11" fill="#12324f" text-anchor="middle">rol: seguido</text>
</svg>
</div>
<div class="neutro">
<p><code>Sigue</code> conecta <code>Usuario</code> consigo mismo, así que el nombre del conjunto de entidades ya no basta para saber cuál es cuál. Hacen falta roles, <code>seguidor</code> para quien sigue y <code>seguido</code> para quien es seguido, el mismo patrón que <code>Asignatura</code> prerrequisito de sí misma.</p>
</div>
</section>
<section id="paso-4-qué-identifica-a-cada-uno" class="slide level2 center">
<h2>Paso 4: ¿qué identifica a cada uno?</h2>
<div class="destacado">
<p>Antes de seguir, con <code>Usuario(id_usuario, nombre)</code> y estos tres registros, decidan cuál combinación de atributos sirve de clave, y por qué las otras no sirven.</p>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th>id_usuario</th>
<th>nombre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Camila Rios</td>
</tr>
<tr class="even">
<td>2</td>
<td>Julian Vega</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Camila Rios</td>
</tr>
</tbody>
</table>
</section>
<section id="paso-4-solución-la-clave-de-usuario" class="slide level2 center">
<h2>Paso 4, solución: la clave de Usuario</h2>
<div class="neutro">
<p><code>nombre</code> no sirve de clave, el registro 1 y el registro 3 comparten Camila Rios sin ser la misma usuaria. <code>id_usuario</code> sí es superclave, y además es mínima, un solo atributo no se puede reducir más, así que es clave candidata y también la clave primaria elegida.</p>
</div>
<div class="destacado">
<p>La clave completa de <code>Comentario</code> combina la clave de su propietario con su discriminador, <code>id_publicacion</code> (heredado) más <code>numero_comentario</code>, el mismo patrón que <code>DetallePedido</code>.</p>
</div>
</section>
<section id="paso-5-una-decisión-de-diseño" class="slide level2 center">
<h2>Paso 5: una decisión de diseño</h2>
<div class="destacado">
<p>La red social ahora quiere saber, de cada interés de un usuario, desde cuándo lo sigue y si lo marcó como favorito. ¿Qué cambia en el modelo?</p>
</div>
<div class="tarjetas">
<div class="tarjeta">
<p><span class="titulo">Antes</span></p>
<p><code>intereses</code> alcanza como atributo multivaluado de <code>Usuario</code>.</p>
</div>
<div class="clave">
<p><span class="titulo">Ahora</span></p>
<p><code>intereses</code> necesita información propia que ya no cabe en un solo valor, así que asciende a entidad, <code>Interes(nombre, desde_cuando, es_favorito)</code> relacionada con <code>Usuario</code>.</p>
</div>
</div>
</section>
<section id="lo-que-construyeron-hoy" class="slide level2 center">
<h2>Lo que construyeron hoy</h2>
<div class="destacado">
<p>Con el mismo procedimiento con el que se resuelve cualquier caso, entidades, atributos, relaciones y claves, en ese orden, armaron una red social completa.</p>
</div>
<div class="neutro">
<p>Dos entidades fuertes, <code>Usuario</code> y <code>Publicacion</code>, y una entidad débil, <code>Comentario</code>. Cuatro formas de atributo aplicadas a un negocio nuevo, incluida la decisión de subir <code>intereses</code> a entidad propia. Tres relaciones, <code>Publica</code> con su propio atributo, <code>Recibe</code> identificadora, y <code>Sigue</code> recursiva con roles. Y la clave primaria de cada entidad, incluida la clave heredada de <code>Comentario</code>.</p>
</div>
</section>
<section id="lo-que-queda-pendiente" class="slide level2 center">
<h2>Lo que queda pendiente</h2>
<div class="destacado">
<p>Todavía no dijimos cuántas publicaciones puede tener un mismo usuario, ni cuántos seguidores puede tener, ni si toda publicación tiene que tener al menos un comentario.</p>
</div>
<p>Eso es exactamente lo que responde la cardinalidad y la participación, el tema de la próxima clase, sobre esta misma red social.</p>
</section>
<section id="ahora-les-toca-a-ustedes" class="slide level2 seccion" data-background-color="#12324f">
<h2>Ahora les toca a ustedes</h2>
<div class="rotulo">
<p>Para practicar, solos</p>
</div>
<p>Con el mismo procedimiento de hoy, resuelvan estos dos casos por su cuenta, en grupos.</p>
</section>
<section id="ejercicio-1-una-biblioteca-universitaria" class="slide level2 center">
<h2>Ejercicio 1: una biblioteca universitaria</h2>
<p>Una biblioteca presta libros a los estudiantes. Cada libro puede tener varios ejemplares físicos en el estante, y cada ejemplar se presta y se devuelve por separado.</p>
<ol type="1">
<li>Cada estudiante tiene un nombre y un código.</li>
<li>Cada libro tiene un título, un autor, y puede tener varios ejemplares.</li>
<li>Cada ejemplar solo tiene sentido dentro del libro al que pertenece.</li>
<li>Cuando un estudiante pide prestado un ejemplar, se registra la fecha de préstamo y la fecha de devolución esperada.</li>
</ol>
<div class="destacado">
<p>Sigan el mismo orden de hoy: primero las entidades, concretas o abstractas y fuertes o débil, luego los atributos, luego las relaciones con sus atributos propios, y por último las claves.</p>
</div>
</section>
<section id="ejercicio-2-una-app-de-mensajería" class="slide level2 center">
<h2>Ejercicio 2: una app de mensajería</h2>
<p>Una app de mensajería permite que los usuarios conversen en chats, y que cada chat tenga varios mensajes. Un usuario puede agregar a otros usuarios como contactos.</p>
<ol type="1">
<li>Cada usuario tiene un nombre y un número de teléfono.</li>
<li>Cada chat tiene una fecha de creación.</li>
<li>Cada mensaje de un chat tiene su propio texto, su propia fecha y su propia hora.</li>
<li>Un usuario puede agregar a otro usuario como contacto.</li>
</ol>
<div class="destacado">
<p>Este caso trae, otra vez, una relación recursiva. Piensen qué roles necesita, y por qué el nombre del conjunto de entidades no basta para distinguirlos.</p>
</div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: false,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copiado");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copiado");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>