<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 3. Marcos para evaluar la usabilidad del software – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-95bfa606010d176c52cfb6b551730f65.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/index.html">Unidad 3. Estándares de calidad aplicados al software</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html">Tema 3. Marcos para evaluar la usabilidad</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Calidad del software y estándares de calidad</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-01-que-es-calidad-quien-la-define/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es la calidad y quién la define</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Calidad de proceso y de producto: ISO/IEC 25010:2023</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Importancia, costo y calidad en un mundo globalizado</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Procesos de calidad del software. Modelos y métricas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-01-sqa-relacion-ingenieria/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es el SQA y su relación con la ingeniería de software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La calidad en cada fase del ciclo de vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-03-roles-habilidades/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Roles, responsabilidades y habilidades del personal de SQA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-04-actividades-sqa/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Actividades del SQA: revisiones, auditorías y gestión de configuración</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-05-modelos-metricas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Modelos y métricas de calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-06-herramientas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 6. Herramientas de SQA en la industria</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 3. Estándares de calidad aplicados al software</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Estándares IEEE para la calidad del software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 3. Marcos para evaluar la usabilidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Madurez de procesos: SPICE y CMMI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 4. Validación y verificación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Métodos, metodologías y estándares de verificación y validación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Validación y verificación de requisitos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-03-control-costo-calidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Control de la calidad y costo de la calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Nomenclatura y certificación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-05-factores-atam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Factores que determinan la calidad y el método ATAM</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#objetivo-y-resultado-de-aprendizaje" id="toc-objetivo-y-resultado-de-aprendizaje" class="nav-link active" data-scroll-target="#objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</a></li>
  <li><a href="#ruta-de-estudio" id="toc-ruta-de-estudio" class="nav-link" data-scroll-target="#ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</a></li>
  <li><a href="#el-hilo-conductor-el-formulario-de-pedir-turno-de-la-clínica-aurora" id="toc-el-hilo-conductor-el-formulario-de-pedir-turno-de-la-clínica-aurora" class="nav-link" data-scroll-target="#el-hilo-conductor-el-formulario-de-pedir-turno-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: el formulario de pedir turno de la Clínica Aurora</a></li>
  <li><a href="#parte-1.-qué-es-la-usabilidad-iso-9241-112018" id="toc-parte-1.-qué-es-la-usabilidad-iso-9241-112018" class="nav-link" data-scroll-target="#parte-1.-qué-es-la-usabilidad-iso-9241-112018"><span class="header-section-number">4</span> Parte 1. Qué es la usabilidad: ISO 9241-11:2018</a>
  <ul class="collapse">
  <li><a href="#la-definición-vigente" id="toc-la-definición-vigente" class="nav-link" data-scroll-target="#la-definición-vigente">La definición vigente</a></li>
  <li><a href="#las-tres-medidas-y-el-contexto-de-uso" id="toc-las-tres-medidas-y-el-contexto-de-uso" class="nav-link" data-scroll-target="#las-tres-medidas-y-el-contexto-de-uso">Las tres medidas y el contexto de uso</a></li>
  <li><a href="#ejemplo-resuelto-el-contexto-de-uso-y-las-metas-medibles-del-formulario" id="toc-ejemplo-resuelto-el-contexto-de-uso-y-las-metas-medibles-del-formulario" class="nav-link" data-scroll-target="#ejemplo-resuelto-el-contexto-de-uso-y-las-metas-medibles-del-formulario">Ejemplo resuelto: el contexto de uso y las metas medibles del formulario</a></li>
  <li><a href="#usabilidad-no-es-lo-mismo-que-se-ve-bonito" id="toc-usabilidad-no-es-lo-mismo-que-se-ve-bonito" class="nav-link" data-scroll-target="#usabilidad-no-es-lo-mismo-que-se-ve-bonito">Usabilidad no es lo mismo que “se ve bonito”</a></li>
  </ul></li>
  <li><a href="#parte-2.-diseño-centrado-en-las-personas-iso-9241-2102019" id="toc-parte-2.-diseño-centrado-en-las-personas-iso-9241-2102019" class="nav-link" data-scroll-target="#parte-2.-diseño-centrado-en-las-personas-iso-9241-2102019"><span class="header-section-number">5</span> Parte 2. Diseño centrado en las personas: ISO 9241-210:2019</a>
  <ul class="collapse">
  <li><a href="#qué-es-y-qué-cubre" id="toc-qué-es-y-qué-cubre" class="nav-link" data-scroll-target="#qué-es-y-qué-cubre">Qué es y qué cubre</a></li>
  <li><a href="#los-seis-principios" id="toc-los-seis-principios" class="nav-link" data-scroll-target="#los-seis-principios">Los seis principios</a></li>
  <li><a href="#las-cuatro-actividades" id="toc-las-cuatro-actividades" class="nav-link" data-scroll-target="#las-cuatro-actividades">Las cuatro actividades</a></li>
  <li><a href="#aplicado-a-la-clínica" id="toc-aplicado-a-la-clínica" class="nav-link" data-scroll-target="#aplicado-a-la-clínica">Aplicado a la clínica</a></li>
  </ul></li>
  <li><a href="#parte-3.-capacidad-de-interacción-y-calidad-en-uso" id="toc-parte-3.-capacidad-de-interacción-y-calidad-en-uso" class="nav-link" data-scroll-target="#parte-3.-capacidad-de-interacción-y-calidad-en-uso"><span class="header-section-number">6</span> Parte 3. Capacidad de interacción y calidad en uso</a>
  <ul class="collapse">
  <li><a href="#capacidad-de-interacción-en-la-isoiec-250102023" id="toc-capacidad-de-interacción-en-la-isoiec-250102023" class="nav-link" data-scroll-target="#capacidad-de-interacción-en-la-isoiec-250102023">Capacidad de interacción en la ISO/IEC 25010:2023</a></li>
  <li><a href="#calidad-en-uso-en-la-isoiec-250192023" id="toc-calidad-en-uso-en-la-isoiec-250192023" class="nav-link" data-scroll-target="#calidad-en-uso-en-la-isoiec-250192023">Calidad en uso en la ISO/IEC 25019:2023</a></li>
  <li><a href="#cómo-se-conectan-las-tres-normas" id="toc-cómo-se-conectan-las-tres-normas" class="nav-link" data-scroll-target="#cómo-se-conectan-las-tres-normas">Cómo se conectan las tres normas</a></li>
  </ul></li>
  <li><a href="#parte-4.-evaluación-por-heurísticas-las-diez-de-nielsen" id="toc-parte-4.-evaluación-por-heurísticas-las-diez-de-nielsen" class="nav-link" data-scroll-target="#parte-4.-evaluación-por-heurísticas-las-diez-de-nielsen"><span class="header-section-number">7</span> Parte 4. Evaluación por heurísticas: las diez de Nielsen</a>
  <ul class="collapse">
  <li><a href="#qué-es-una-evaluación-heurística" id="toc-qué-es-una-evaluación-heurística" class="nav-link" data-scroll-target="#qué-es-una-evaluación-heurística">Qué es una evaluación heurística</a></li>
  <li><a href="#las-diez-heurísticas-aplicadas-al-formulario" id="toc-las-diez-heurísticas-aplicadas-al-formulario" class="nav-link" data-scroll-target="#las-diez-heurísticas-aplicadas-al-formulario">Las diez heurísticas, aplicadas al formulario</a></li>
  <li><a href="#severidad-cómo-priorizar-los-hallazgos" id="toc-severidad-cómo-priorizar-los-hallazgos" class="nav-link" data-scroll-target="#severidad-cómo-priorizar-los-hallazgos">Severidad: cómo priorizar los hallazgos</a></li>
  <li><a href="#ejemplo-resuelto-evaluación-del-formulario-por-tres-evaluadores" id="toc-ejemplo-resuelto-evaluación-del-formulario-por-tres-evaluadores" class="nav-link" data-scroll-target="#ejemplo-resuelto-evaluación-del-formulario-por-tres-evaluadores">Ejemplo resuelto: evaluación del formulario por tres evaluadores</a></li>
  </ul></li>
  <li><a href="#parte-5.-pruebas-de-usabilidad-con-personas" id="toc-parte-5.-pruebas-de-usabilidad-con-personas" class="nav-link" data-scroll-target="#parte-5.-pruebas-de-usabilidad-con-personas"><span class="header-section-number">8</span> Parte 5. Pruebas de usabilidad con personas</a>
  <ul class="collapse">
  <li><a href="#qué-es-y-cómo-se-planea" id="toc-qué-es-y-cómo-se-planea" class="nav-link" data-scroll-target="#qué-es-y-cómo-se-planea">Qué es y cómo se planea</a></li>
  <li><a href="#ejemplo-resuelto-cinco-adultos-mayores-piden-un-turno" id="toc-ejemplo-resuelto-cinco-adultos-mayores-piden-un-turno" class="nav-link" data-scroll-target="#ejemplo-resuelto-cinco-adultos-mayores-piden-un-turno">Ejemplo resuelto: cinco adultos mayores piden un turno</a></li>
  <li><a href="#cuánta-confianza-da-un-60-con-cinco-personas" id="toc-cuánta-confianza-da-un-60-con-cinco-personas" class="nav-link" data-scroll-target="#cuánta-confianza-da-un-60-con-cinco-personas">Cuánta confianza da un 60 % con cinco personas</a></li>
  <li><a href="#cuántas-personas-hacen-falta" id="toc-cuántas-personas-hacen-falta" class="nav-link" data-scroll-target="#cuántas-personas-hacen-falta">Cuántas personas hacen falta</a></li>
  <li><a href="#los-límites-de-la-regla-de-las-cinco-personas" id="toc-los-límites-de-la-regla-de-las-cinco-personas" class="nav-link" data-scroll-target="#los-límites-de-la-regla-de-las-cinco-personas">Los límites de la regla de las cinco personas</a></li>
  <li><a href="#ejemplo-resuelto-cuántas-personas-para-encontrar-al-menos-90-de-los-problemas" id="toc-ejemplo-resuelto-cuántas-personas-para-encontrar-al-menos-90-de-los-problemas" class="nav-link" data-scroll-target="#ejemplo-resuelto-cuántas-personas-para-encontrar-al-menos-90-de-los-problemas">Ejemplo resuelto: cuántas personas para encontrar al menos 90 % de los problemas</a></li>
  </ul></li>
  <li><a href="#parte-6.-el-cuestionario-sus" id="toc-parte-6.-el-cuestionario-sus" class="nav-link" data-scroll-target="#parte-6.-el-cuestionario-sus"><span class="header-section-number">9</span> Parte 6. El cuestionario SUS</a>
  <ul class="collapse">
  <li><a href="#qué-es-y-de-dónde-viene" id="toc-qué-es-y-de-dónde-viene" class="nav-link" data-scroll-target="#qué-es-y-de-dónde-viene">Qué es y de dónde viene</a></li>
  <li><a href="#los-diez-ítems" id="toc-los-diez-ítems" class="nav-link" data-scroll-target="#los-diez-ítems">Los diez ítems</a></li>
  <li><a href="#cómo-se-calcula" id="toc-cómo-se-calcula" class="nav-link" data-scroll-target="#cómo-se-calcula">Cómo se calcula</a></li>
  <li><a href="#ejemplo-resuelto-participante-p1" id="toc-ejemplo-resuelto-participante-p1" class="nav-link" data-scroll-target="#ejemplo-resuelto-participante-p1">Ejemplo resuelto: participante P1</a></li>
  <li><a href="#resultados-de-los-cinco-participantes" id="toc-resultados-de-los-cinco-participantes" class="nav-link" data-scroll-target="#resultados-de-los-cinco-participantes">Resultados de los cinco participantes</a></li>
  <li><a href="#cómo-interpretar-la-puntuación-la-referencia-de-68" id="toc-cómo-interpretar-la-puntuación-la-referencia-de-68" class="nav-link" data-scroll-target="#cómo-interpretar-la-puntuación-la-referencia-de-68">Cómo interpretar la puntuación: la referencia de 68</a></li>
  <li><a href="#qué-concluye-el-equipo" id="toc-qué-concluye-el-equipo" class="nav-link" data-scroll-target="#qué-concluye-el-equipo">Qué concluye el equipo</a></li>
  <li><a href="#errores-frecuentes-con-el-sus" id="toc-errores-frecuentes-con-el-sus" class="nav-link" data-scroll-target="#errores-frecuentes-con-el-sus">Errores frecuentes con el SUS</a></li>
  </ul></li>
  <li><a href="#parte-7.-accesibilidad-con-wcag-2.2" id="toc-parte-7.-accesibilidad-con-wcag-2.2" class="nav-link" data-scroll-target="#parte-7.-accesibilidad-con-wcag-2.2"><span class="header-section-number">10</span> Parte 7. Accesibilidad con WCAG 2.2</a>
  <ul class="collapse">
  <li><a href="#qué-es-wcag-y-qué-versión-rige" id="toc-qué-es-wcag-y-qué-versión-rige" class="nav-link" data-scroll-target="#qué-es-wcag-y-qué-versión-rige">Qué es WCAG y qué versión rige</a></li>
  <li><a href="#principios-y-niveles-de-conformidad" id="toc-principios-y-niveles-de-conformidad" class="nav-link" data-scroll-target="#principios-y-niveles-de-conformidad">Principios y niveles de conformidad</a></li>
  <li><a href="#ejemplo-resuelto-contraste-del-texto-del-formulario" id="toc-ejemplo-resuelto-contraste-del-texto-del-formulario" class="nav-link" data-scroll-target="#ejemplo-resuelto-contraste-del-texto-del-formulario">Ejemplo resuelto: contraste del texto del formulario</a></li>
  <li><a href="#ejemplo-resuelto-revisión-del-formulario-contra-diez-criterios" id="toc-ejemplo-resuelto-revisión-del-formulario-contra-diez-criterios" class="nav-link" data-scroll-target="#ejemplo-resuelto-revisión-del-formulario-contra-diez-criterios">Ejemplo resuelto: revisión del formulario contra diez criterios</a></li>
  <li><a href="#wcag-2.2-como-norma-iso-y-el-borrador-de-wcag-3.0" id="toc-wcag-2.2-como-norma-iso-y-el-borrador-de-wcag-3.0" class="nav-link" data-scroll-target="#wcag-2.2-como-norma-iso-y-el-borrador-de-wcag-3.0">WCAG 2.2 como norma ISO y el borrador de WCAG 3.0</a></li>
  </ul></li>
  <li><a href="#parte-8.-marco-normativo-de-accesibilidad" id="toc-parte-8.-marco-normativo-de-accesibilidad" class="nav-link" data-scroll-target="#parte-8.-marco-normativo-de-accesibilidad"><span class="header-section-number">11</span> Parte 8. Marco normativo de accesibilidad</a>
  <ul class="collapse">
  <li><a href="#colombia" id="toc-colombia" class="nav-link" data-scroll-target="#colombia">Colombia</a></li>
  <li><a href="#la-ntc-5854" id="toc-la-ntc-5854" class="nav-link" data-scroll-target="#la-ntc-5854">La NTC 5854</a></li>
  <li><a href="#unión-europea" id="toc-unión-europea" class="nav-link" data-scroll-target="#unión-europea">Unión Europea</a></li>
  <li><a href="#mapa-de-marcos-de-accesibilidad" id="toc-mapa-de-marcos-de-accesibilidad" class="nav-link" data-scroll-target="#mapa-de-marcos-de-accesibilidad">Mapa de marcos de accesibilidad</a></li>
  </ul></li>
  <li><a href="#parte-9.-un-plan-de-evaluación-integrado" id="toc-parte-9.-un-plan-de-evaluación-integrado" class="nav-link" data-scroll-target="#parte-9.-un-plan-de-evaluación-integrado"><span class="header-section-number">12</span> Parte 9. Un plan de evaluación integrado</a>
  <ul class="collapse">
  <li><a href="#qué-marco-usar-y-cuándo" id="toc-qué-marco-usar-y-cuándo" class="nav-link" data-scroll-target="#qué-marco-usar-y-cuándo">Qué marco usar y cuándo</a></li>
  <li><a href="#ejemplo-resuelto-plan-de-una-iteración-para-el-formulario" id="toc-ejemplo-resuelto-plan-de-una-iteración-para-el-formulario" class="nav-link" data-scroll-target="#ejemplo-resuelto-plan-de-una-iteración-para-el-formulario">Ejemplo resuelto: plan de una iteración para el formulario</a></li>
  </ul></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes"><span class="header-section-number">13</span> Errores frecuentes</a></li>
  <li><a href="#autoevaluación" id="toc-autoevaluación" class="nav-link" data-scroll-target="#autoevaluación"><span class="header-section-number">14</span> Autoevaluación</a></li>
  <li><a href="#lo-que-te-llevas" id="toc-lo-que-te-llevas" class="nav-link" data-scroll-target="#lo-que-te-llevas"><span class="header-section-number">15</span> Lo que te llevas</a></li>
  <li><a href="#glosario" id="toc-glosario" class="nav-link" data-scroll-target="#glosario"><span class="header-section-number">16</span> Glosario</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">17</span> Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/index.html">Unidad 3. Estándares de calidad aplicados al software</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html">Tema 3. Marcos para evaluar la usabilidad</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 3. Marcos para evaluar la usabilidad del software</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">4 de octubre de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 89%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 3. Estándares de calidad aplicados al software</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 3. Marcos para evaluar la usabilidad del software</td>
</tr>
</tbody>
</table>
</div>
<p><a href="../presentacion-interactiva.html" class="btn-curso">Presentación interactiva de la unidad</a></p>
<p>Tema anterior: <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</a>. Tema siguiente: <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html">Tema 4. Madurez de procesos: SPICE y CMMI</a>.</p>
<section id="objetivo-y-resultado-de-aprendizaje" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</h2>
<p>La carta descriptiva de la asignatura pide que el estudiante reconozca los marcos de referencia para la evaluación de la usabilidad del software. Este tema cubre ese resultado de punta a punta. Recorre las normas que definen la usabilidad, los métodos con los que se mide y los marcos de accesibilidad que la complementan, y aplica todo a un caso concreto: el formulario de pedir turno de la app de la clínica, usado por un adulto mayor.</p>
<p>Al terminar puedes:</p>
<ul>
<li>Definir usabilidad con la ISO 9241-11:2018 y descomponerla en efectividad, eficiencia, satisfacción y contexto de uso.</li>
<li>Describir el proceso de diseño centrado en las personas de la ISO 9241-210:2019, con sus seis principios y cuatro actividades.</li>
<li>Ubicar la usabilidad dentro de la ISO/IEC 25010:2023 (capacidad de interacción) y de la ISO/IEC 25019:2023 (calidad en uso).</li>
<li>Evaluar una interfaz con las diez heurísticas de Nielsen y priorizar los hallazgos con una escala de severidad.</li>
<li>Planear una prueba de usabilidad, calcular sus medidas y decir con honestidad qué permite concluir un tamaño de muestra pequeño.</li>
<li>Calcular la puntuación SUS paso a paso e interpretarla sin tomar la referencia de 68 como un umbral universal.</li>
<li>Revisar un formulario contra criterios concretos de WCAG 2.2 y ubicar WCAG 3.0, ISO/IEC 40500, la Resolución 1519 de 2020, la NTC 5854 y el European Accessibility Act en el panorama normativo.</li>
<li>Armar un plan de evaluación que combine varios marcos y justifique cada uno.</li>
</ul>
<p>Prerrequisitos: los Temas 1 y 2 de la Unidad 1 (calidad de producto y calidad en uso) y el Tema 2 de esta unidad (la familia SQuaRE). Necesitas distinguir característica, subcaracterística y medida.</p>
</section>
<section id="ruta-de-estudio" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</h2>
<p>Son unas 8 horas de trabajo independiente. Puedes partirlas en tres o cuatro sesiones. La presentación interactiva de la unidad tiene una sección por tema y sirve como repaso. Esta guía es la fuente completa.</p>
<div class="calendario">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parte</th>
<th>Qué haces</th>
<th>Tiempo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Qué es la usabilidad</td>
<td>Lees la ISO 9241-11, defines el contexto de uso y resuelves el Reto 1</td>
<td>50 min</td>
</tr>
<tr class="even">
<td>2. Diseño centrado en las personas</td>
<td>Lees la ISO 9241-210 y resuelves el Reto 2</td>
<td>35 min</td>
</tr>
<tr class="odd">
<td>3. Capacidad de interacción y calidad en uso</td>
<td>Conectas ISO 25010:2023 e ISO 25019:2023 con la ISO 9241-11</td>
<td>35 min</td>
</tr>
<tr class="even">
<td>4. Evaluación por heurísticas</td>
<td>Aplicas las diez heurísticas y resuelves el Reto 3</td>
<td>55 min</td>
</tr>
<tr class="odd">
<td>5. Pruebas de usabilidad</td>
<td>Sigues el ejemplo, calculas intervalos y muestra, y resuelves el Reto 4</td>
<td>75 min</td>
</tr>
<tr class="even">
<td>6. El cuestionario SUS</td>
<td>Calculas puntuaciones y resuelves el Reto 5</td>
<td>55 min</td>
</tr>
<tr class="odd">
<td>7. Accesibilidad con WCAG 2.2</td>
<td>Revisas el formulario contra criterios y resuelves el Reto 6</td>
<td>70 min</td>
</tr>
<tr class="even">
<td>8. Marco normativo de accesibilidad</td>
<td>Lees Colombia, la Unión Europea y los borradores, y resuelves el Reto 7</td>
<td>40 min</td>
</tr>
<tr class="odd">
<td>9. Un plan de evaluación integrado</td>
<td>Armas el plan para el formulario</td>
<td>30 min</td>
</tr>
<tr class="even">
<td>Cierre</td>
<td>Errores frecuentes, autoevaluación y glosario</td>
<td>35 min</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="el-hilo-conductor-el-formulario-de-pedir-turno-de-la-clínica-aurora" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="el-hilo-conductor-el-formulario-de-pedir-turno-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: el formulario de pedir turno de la Clínica Aurora</h2>
<p>El curso usa una app ficticia que asigna turnos médicos. En este tema se evalúa una sola pantalla: el formulario de pedir turno. La usa Marta, una paciente de 72 años que pide turno de medicina general para el jueves. Marta usa un celular Android de gama baja, con la letra del sistema ampliada, y ve con dificultad cuando hay poca luz. Marta es un personaje inventado, igual que todas las cifras de la clínica de este tema. Cada número propio se marca como ilustrativo.</p>
<p>El formulario tiene cuatro pasos: elegir especialidad, elegir fecha, escribir los datos del paciente y confirmar. Los defectos que se encuentran más adelante se diseñaron a propósito para practicar.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Sobre las normas de pago
</div>
</div>
<div class="callout-body-container callout-body">
<p>Las normas ISO y la NTC colombiana se venden. Para esta guía se consultaron las fichas públicas de ISO (resumen, edición, estado y fecha de revisión), las especificaciones gratuitas de W3C y las fuentes oficiales que se citan en la bibliografía. Cuando un dato viene del texto completo de una norma de pago y no se pudo leer ahí, la guía lo dice. Las definiciones de la ISO 9241-11 y los principios de la ISO 9241-210 se presentan en paráfrasis.</p>
</div>
</div>
</section>
<section id="parte-1.-qué-es-la-usabilidad-iso-9241-112018" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="parte-1.-qué-es-la-usabilidad-iso-9241-112018"><span class="header-section-number">4</span> Parte 1. Qué es la usabilidad: ISO 9241-11:2018</h2>
<section id="la-definición-vigente" class="level3">
<h3 class="anchored" data-anchor-id="la-definición-vigente">La definición vigente</h3>
<p>La ISO 9241-11:2018 (<em>Ergonomics of human-system interaction, Part 11: Usability: Definitions and concepts</em>) es la segunda edición, de marzo de 2018. Sustituyó a la de 1998. La ficha de ISO indica que fue revisada y confirmada en 2023, de modo que esa edición sigue vigente en octubre de 2026.</p>
<p>Según la norma, la usabilidad es el grado en que usuarios específicos pueden usar un sistema, producto o servicio para lograr metas específicas con efectividad, eficiencia y satisfacción, en un contexto de uso específico. La palabra repetida es “específico”. La usabilidad no es una propiedad que el producto tenga por sí solo. Depende de quién lo usa, para qué y dónde.</p>
<p>La ficha de ISO agrega que la norma explica la usabilidad como un resultado del uso, define términos y fundamentos, y no describe procesos ni métodos concretos para tenerla en cuenta en el diseño o la evaluación. Para eso están la ISO 9241-210 y otras partes de la serie ISO 9241.</p>
</section>
<section id="las-tres-medidas-y-el-contexto-de-uso" class="level3">
<h3 class="anchored" data-anchor-id="las-tres-medidas-y-el-contexto-de-uso">Las tres medidas y el contexto de uso</h3>
<p>La norma define tres resultados del uso. La paráfrasis que sigue resume sus definiciones.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Medida</th>
<th>Qué significa</th>
<th>Cómo suele medirse</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Efectividad</td>
<td>Exactitud y completitud con que las personas logran sus metas</td>
<td>Porcentaje de tareas completadas, errores que impiden la meta</td>
</tr>
<tr class="even">
<td>Eficiencia</td>
<td>Recursos gastados en relación con los resultados logrados</td>
<td>Tiempo en tarea, número de pasos, esfuerzo percibido</td>
</tr>
<tr class="odd">
<td>Satisfacción</td>
<td>Respuestas físicas, cognitivas y emocionales que cumplen necesidades y expectativas</td>
<td>Cuestionarios como SUS, comentarios, abandono</td>
</tr>
</tbody>
</table>
<p>El contexto de uso es la combinación de usuarios, metas y tareas, recursos (equipo, software, información) y entorno físico y social. Cambiar uno de esos cuatro elementos cambia la usabilidad, aunque la pantalla sea idéntica. Un formulario cómodo para una persona joven con fibra óptica en casa puede fallar para Marta en una sala de espera con datos móviles lentos.</p>
<div class="diagrama">
<svg viewbox="0 0 760 272" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Modelo de la ISO 9241-11: un contexto de uso formado por usuarios, metas y tareas, recursos y entorno rodea el uso del producto, que produce tres resultados: efectividad, eficiencia y satisfacción" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t3a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">La usabilidad según la ISO 9241-11:2018</text> <rect x="16" y="30" width="470" height="232" rx="14" fill="none" stroke="#8fb3d1" stroke-width="1.6" stroke-dasharray="6 5"></rect> <text x="32" y="52" font-size="12.5" font-weight="700" fill="#5b6876">Contexto de uso</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="32" y="62" width="170" height="40" rx="8"></rect><rect x="32" y="110" width="170" height="40" rx="8"></rect><rect x="32" y="158" width="170" height="40" rx="8"></rect><rect x="32" y="206" width="170" height="40" rx="8"></rect></g> <g font-size="12" font-weight="600" fill="#12324f" text-anchor="middle"><text x="117" y="87">Usuarios</text><text x="117" y="135">Metas y tareas</text><text x="117" y="183">Recursos</text><text x="117" y="231">Entorno</text></g> <path d="M202,82 L232,82 L232,226 L202,226 M232,154 L282,154" fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#u3t3a)"></path> <rect x="290" y="120" width="180" height="68" rx="12" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="380" y="150" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Uso del producto</text> <text x="380" y="170" font-size="11" fill="#5b6876" text-anchor="middle">el formulario de turnos</text> <g fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#u3t3a)"><path d="M486,154 C510,154 520,80 546,80"></path><path d="M486,154 L546,154"></path><path d="M486,154 C510,154 520,228 546,228"></path></g> <g fill="#e4f2f1" stroke="#8fc9c5"><rect x="548" y="50" width="196" height="60" rx="10"></rect><rect x="548" y="124" width="196" height="60" rx="10"></rect><rect x="548" y="198" width="196" height="60" rx="10"></rect></g> <g text-anchor="middle"><g font-size="13" font-weight="700" fill="#0e6f6c"><text x="646" y="76">Efectividad</text><text x="646" y="150">Eficiencia</text><text x="646" y="224">Satisfacción</text></g><g font-size="11" fill="#3c7d7a"><text x="646" y="95">exactitud y completitud</text><text x="646" y="169">recursos frente a resultados</text><text x="646" y="243">respuestas del usuario</text></g></g>
</svg>
</div>
</section>
<section id="ejemplo-resuelto-el-contexto-de-uso-y-las-metas-medibles-del-formulario" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-el-contexto-de-uso-y-las-metas-medibles-del-formulario">Ejemplo resuelto: el contexto de uso y las metas medibles del formulario</h3>
<p>Antes de evaluar hay que escribir contra qué se evalúa. El equipo de la clínica describe el contexto de uso y fija metas medibles. Las metas de la tabla son ilustrativas, no vienen de ninguna norma.</p>
<ol type="1">
<li>Usuarios. Adultos de 65 a 85 años, con uso ocasional del celular y, en algunos casos, vista cansada.</li>
<li>Metas y tareas. Obtener un turno de medicina general sin llamar a la clínica. Tarea: elegir especialidad, fecha y confirmar.</li>
<li>Recursos. Celular Android de gama baja, pantalla de unas 5,5 pulgadas, datos móviles lentos.</li>
<li>Entorno. Casa o sala de espera, luz variable, interrupciones frecuentes.</li>
<li>Se traduce cada medida de la norma en una meta.</li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Medida</th>
<th>Meta ilustrativa para el formulario</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Efectividad</td>
<td>Al menos 8 de cada 10 adultos mayores completan la tarea sin ayuda</td>
</tr>
<tr class="even">
<td>Eficiencia</td>
<td>Las personas que completan la tarea tardan 120 segundos o menos</td>
</tr>
<tr class="odd">
<td>Satisfacción</td>
<td>La puntuación SUS promedio llega al menos a 68</td>
</tr>
</tbody>
</table>
<p>Con esa tabla, “el formulario es usable” deja de ser una opinión. Se vuelve una afirmación que una prueba puede confirmar o refutar. Más adelante, en la Parte 5, se compara una prueba real (ficticia) contra estas tres metas.</p>
</section>
<section id="usabilidad-no-es-lo-mismo-que-se-ve-bonito" class="level3">
<h3 class="anchored" data-anchor-id="usabilidad-no-es-lo-mismo-que-se-ve-bonito">Usabilidad no es lo mismo que “se ve bonito”</h3>
<p>La confusión más común es tratar la usabilidad como estética. Una pantalla atractiva puede tener usabilidad baja si la persona no logra su meta, y una pantalla sobria puede tener usabilidad alta. La norma mide resultados del uso (lograr, con qué esfuerzo, con qué respuesta), no apariencia.</p>
<p>También se confunde con la facilidad de aprendizaje. Aprender rápido es una parte de la usabilidad, pero un sistema que se aprende en un minuto y luego obliga a hacer veinte pasos para una tarea diaria tiene mala eficiencia.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Contexto de uso y medidas de “cancelar un turno”
</div>
</div>
<div class="callout-body-container callout-body">
<p>La clínica agrega la tarea “cancelar un turno ya pedido”. Escribe el contexto de uso para Marta (los cuatro elementos) y tres metas medibles, una por cada medida de la ISO 9241-11. Indica también qué cambiaría en el contexto si quien cancela es el hijo de Marta, de 40 años, desde el computador de la oficina.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Contexto para Marta: usuaria de 72 años con uso ocasional del celular; meta de cancelar un turno que ya no puede cumplir, sin llamar; recursos de celular de gama baja y datos lentos; entorno de casa con interrupciones.</p>
<p>Metas ilustrativas: efectividad, al menos 9 de cada 10 cancelaciones completadas sin ayuda (cancelar no debería ser más difícil que pedir); eficiencia, 60 segundos o menos desde abrir la app; satisfacción, SUS de al menos 68 después de la tarea.</p>
<p>Si cancela el hijo, cambian los usuarios (adulto con experiencia digital), los recursos (computador con pantalla grande y teclado) y el entorno (oficina, con prisa). Las metas de eficiencia podrían endurecerse. La conclusión es que la misma pantalla se evalúa de nuevo para cada contexto. Tu redacción puede variar mientras los cuatro elementos y las tres medidas estén presentes.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-2.-diseño-centrado-en-las-personas-iso-9241-2102019" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="parte-2.-diseño-centrado-en-las-personas-iso-9241-2102019"><span class="header-section-number">5</span> Parte 2. Diseño centrado en las personas: ISO 9241-210:2019</h2>
<section id="qué-es-y-qué-cubre" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-y-qué-cubre">Qué es y qué cubre</h3>
<p>La ISO 9241-210:2019 (<em>Human-centred design for interactive systems</em>) es la segunda edición, de julio de 2019, y la ficha de ISO indica que fue revisada y confirmada en 2025. Está vigente. Da requisitos y recomendaciones sobre los principios y las actividades del diseño centrado en las personas durante el ciclo de vida de sistemas interactivos. Es una norma de gestión del proceso. No detalla técnicas de investigación ni de diseño, y tampoco entra en seguridad y salud en detalle.</p>
<p>La relación con la ISO 9241-11 es de pregunta y respuesta. La ISO 9241-11 dice qué es usabilidad y qué medir. La ISO 9241-210 dice cómo organizar el trabajo de diseño para llegar a ella.</p>
</section>
<section id="los-seis-principios" class="level3">
<h3 class="anchored" data-anchor-id="los-seis-principios">Los seis principios</h3>
<p>Los seis principios se tomaron de fuentes secundarias que los resumen (el texto completo de la norma es de pago). Se parafrasean aquí.</p>
<ol type="1">
<li>El diseño parte de una comprensión explícita de las personas usuarias, sus tareas y sus entornos.</li>
<li>Las personas usuarias participan durante todo el diseño y el desarrollo.</li>
<li>El diseño se guía y se refina con evaluación centrada en las personas.</li>
<li>El proceso es iterativo.</li>
<li>El diseño atiende toda la experiencia de la persona usuaria.</li>
<li>El equipo de diseño reúne habilidades y perspectivas multidisciplinarias.</li>
</ol>
</section>
<section id="las-cuatro-actividades" class="level3">
<h3 class="anchored" data-anchor-id="las-cuatro-actividades">Las cuatro actividades</h3>
<p>Las actividades se repiten en ciclo hasta que el diseño cumple los requisitos.</p>
<div class="diagrama">
<svg viewbox="0 0 760 270" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Ciclo de la ISO 9241-210 en cuatro actividades: entender y especificar el contexto de uso, especificar los requisitos de las personas usuarias, producir soluciones de diseño y evaluar contra los requisitos, con una flecha que vuelve al inicio si el diseño no cumple" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t3b" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Las cuatro actividades de diseño centrado en las personas</text> <g fill="#fff3d6" stroke="#e6c46f"><rect x="14" y="44" width="170" height="96" rx="12"></rect><rect x="200" y="44" width="170" height="96" rx="12"></rect><rect x="386" y="44" width="170" height="96" rx="12"></rect><rect x="572" y="44" width="170" height="96" rx="12"></rect></g> <g text-anchor="middle" font-size="12.5" font-weight="700" fill="#12324f"><text x="99" y="68">1. Contexto de uso</text><text x="285" y="68">2. Requisitos</text><text x="471" y="68">3. Diseño</text><text x="657" y="68">4. Evaluación</text></g> <g text-anchor="middle" font-size="11" fill="#5b6876"><text x="99" y="90">Entender y especificar</text><text x="99" y="105">quién usa, para qué</text><text x="99" y="120">y dónde</text><text x="285" y="90">Especificar lo que</text><text x="285" y="105">las personas necesitan</text><text x="285" y="120">lograr, con medidas</text><text x="471" y="90">Producir soluciones:</text><text x="471" y="105">bocetos, prototipos,</text><text x="471" y="120">versiones</text><text x="657" y="90">Evaluar contra los</text><text x="657" y="105">requisitos, con personas</text><text x="657" y="120">reales</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u3t3b)"><path d="M184,92 L198,92"></path><path d="M370,92 L384,92"></path><path d="M556,92 L570,92"></path><path d="M657,142 C657,226 99,226 99,144"></path></g> <text x="378" y="216" font-size="12" fill="#5b6876" text-anchor="middle">Si la evaluación muestra que el diseño no cumple, se vuelve a una actividad anterior</text> <rect x="190" y="232" width="380" height="30" rx="8" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="252" font-size="12" fill="#0e6f6c" text-anchor="middle" font-weight="600">Cuando cumple los requisitos, el ciclo termina</text>
</svg>
</div>
</section>
<section id="aplicado-a-la-clínica" class="level3">
<h3 class="anchored" data-anchor-id="aplicado-a-la-clínica">Aplicado a la clínica</h3>
<p>En la clínica, el equipo hizo el formulario con una plantilla de otra app y nunca habló con pacientes mayores. La tabla dice qué principio y qué actividad faltaron.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Qué ocurrió</th>
<th>Principio que se incumple</th>
<th>Actividad que faltó</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nadie observó a un adulto mayor usando celular</td>
<td>1. Comprensión explícita de personas, tareas y entornos</td>
<td>1. Contexto de uso</td>
</tr>
<tr class="even">
<td>El diseño se aprobó entre desarrolladores</td>
<td>2. Participación de las personas usuarias; 6. Equipo multidisciplinario</td>
<td>2. Requisitos</td>
</tr>
<tr class="odd">
<td>Se publicó la primera versión sin probarla con pacientes</td>
<td>3. Guiado por evaluación; 4. Iterativo</td>
<td>4. Evaluación</td>
</tr>
<tr class="even">
<td>Solo se pensó en la pantalla, no en llegar a la clínica con el turno</td>
<td>5. Toda la experiencia</td>
<td>1. Contexto de uso</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Qué principio falta
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un equipo mide la usabilidad solo una vez, con 5 pacientes, al final del proyecto, y no corrige nada porque “ya no hay tiempo”. Indica qué principios de la ISO 9241-210 se incumplen y cómo reorganizarías las cuatro actividades para el siguiente trimestre.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Se incumplen el principio 3 (el diseño no se guía por la evaluación, porque sus resultados no se usan) y el principio 4 (no hay iteración). Si además la prueba llega al final, también se debilita el principio 2, ya que las personas usuarias no participaron durante el desarrollo.</p>
<p>Reorganización posible: pruebas cortas con prototipos desde la actividad 3, evaluaciones al terminar cada iteración (actividad 4), y una reserva de tiempo para corregir lo hallado antes de la siguiente. La idea de fondo es que evaluar tarde cuesta lo mismo que evaluar temprano, pero corregir cuesta más (véase el costo de la calidad en la Unidad 1, Tema 3, con las advertencias que allí se hacen sobre esas cifras).</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-3.-capacidad-de-interacción-y-calidad-en-uso" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="parte-3.-capacidad-de-interacción-y-calidad-en-uso"><span class="header-section-number">6</span> Parte 3. Capacidad de interacción y calidad en uso</h2>
<section id="capacidad-de-interacción-en-la-isoiec-250102023" class="level3">
<h3 class="anchored" data-anchor-id="capacidad-de-interacción-en-la-isoiec-250102023">Capacidad de interacción en la ISO/IEC 25010:2023</h3>
<p>La ISO/IEC 25010:2023 (edición 2, noviembre de 2023) define el modelo de calidad del producto con nueve características. Una de ellas es la capacidad de interacción (<em>interaction capability</em>). En la edición de 2011 esa característica se llamaba usabilidad. El Tema 2 de la Unidad 1 explica el modelo completo. Aquí se retoma solo lo que importa para evaluar usabilidad.</p>
<p>La capacidad de interacción tiene ocho subcaracterísticas. Cada una se puede convertir en requisito y en prueba. La tabla las aplica al formulario de turnos. Las definiciones están en paráfrasis, porque el texto completo de la norma es de pago.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Subcaracterística</th>
<th>Pregunta para el formulario</th>
<th>Medida candidata</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reconocibilidad de la adecuación</td>
<td>¿Marta entiende al abrir que es para pedir turnos?</td>
<td>Porcentaje que acierta la finalidad tras 5 segundos</td>
</tr>
<tr class="even">
<td>Capacidad de aprendizaje</td>
<td>¿Pide su primer turno sin manual?</td>
<td>Tareas completadas en el primer uso</td>
</tr>
<tr class="odd">
<td>Operabilidad</td>
<td>¿Los controles se manejan con facilidad?</td>
<td>Errores de pulsación, tamaño de botones</td>
</tr>
<tr class="even">
<td>Protección frente a errores del usuario</td>
<td>¿Evita y corrige equivocaciones?</td>
<td>Errores evitados o corregidos con un mensaje claro</td>
</tr>
<tr class="odd">
<td>Participación del usuario</td>
<td>¿Invita a seguir usándolo de forma agradable?</td>
<td>Porcentaje que vuelve a usar la app</td>
</tr>
<tr class="even">
<td>Inclusividad</td>
<td>¿Pueden usarla personas con distintas capacidades?</td>
<td>Criterios de accesibilidad cumplidos</td>
</tr>
<tr class="odd">
<td>Asistencia al usuario</td>
<td>¿Recibe ayuda cuando la necesita?</td>
<td>Ayuda disponible en cada paso</td>
</tr>
<tr class="even">
<td>Autodescriptividad</td>
<td>¿Muestra la información para entender qué hace?</td>
<td>Mensajes claros, sin códigos internos</td>
</tr>
</tbody>
</table>
</section>
<section id="calidad-en-uso-en-la-isoiec-250192023" class="level3">
<h3 class="anchored" data-anchor-id="calidad-en-uso-en-la-isoiec-250192023">Calidad en uso en la ISO/IEC 25019:2023</h3>
<p>La ISO/IEC 25019:2023 (edición 1, noviembre de 2023) define el modelo de calidad en uso. Según su resumen público, el modelo tiene tres características y se aplica cuando un producto o sistema se usa en un contexto de uso específico. Hasta 2023 ese modelo estaba dentro de la ISO/IEC 25010. Hoy vive en su propia norma.</p>
<p>Las tres características son beneficiosidad, libertad de riesgo y aceptabilidad, y la usabilidad y la accesibilidad aparecen como subcaracterísticas de la beneficiosidad. Ese detalle viene de la lectura que hace el Tema 2 de la Unidad 1. El resumen público de ISO no lo menciona, y el texto completo es de pago.</p>
</section>
<section id="cómo-se-conectan-las-tres-normas" class="level3">
<h3 class="anchored" data-anchor-id="cómo-se-conectan-las-tres-normas">Cómo se conectan las tres normas</h3>
<p>La ISO 9241-11 define la usabilidad como resultado del uso. La ISO/IEC 25010:2023 describe propiedades del producto que hacen probable ese resultado, y la ISO/IEC 25019:2023 organiza el resultado como calidad en uso. Si el formulario cumple todos los requisitos de producto y Marta igual no logra su turno, la calidad de producto fue suficiente y la calidad en uso fue baja. La diferencia es la que se vio en el Tema 2 de la Unidad 1.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Norma</th>
<th>Qué aporta</th>
<th>Pregunta que responde</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ISO 9241-11:2018</td>
<td>Definición de usabilidad y sus tres medidas</td>
<td>¿Qué es la usabilidad y qué se mide?</td>
</tr>
<tr class="even">
<td>ISO 9241-210:2019</td>
<td>Proceso de diseño centrado en las personas</td>
<td>¿Cómo se organiza el trabajo para lograrla?</td>
</tr>
<tr class="odd">
<td>ISO/IEC 25010:2023</td>
<td>Subcaracterísticas de capacidad de interacción</td>
<td>¿Qué propiedades del producto la sostienen?</td>
</tr>
<tr class="even">
<td>ISO/IEC 25019:2023</td>
<td>Modelo de calidad en uso</td>
<td>¿Qué efecto tiene el uso en quien lo usa?</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="parte-4.-evaluación-por-heurísticas-las-diez-de-nielsen" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="parte-4.-evaluación-por-heurísticas-las-diez-de-nielsen"><span class="header-section-number">7</span> Parte 4. Evaluación por heurísticas: las diez de Nielsen</h2>
<section id="qué-es-una-evaluación-heurística" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-una-evaluación-heurística">Qué es una evaluación heurística</h3>
<p>Una evaluación heurística es un método de inspección. Algunas personas expertas recorren la interfaz y la juzgan contra una lista de principios, llamados heurísticas. No requiere usuarios, así que es barata y se puede hacer temprano, con un prototipo. Su límite es que muestra lo que los evaluadores creen que fallará, no lo que las personas reales hacen.</p>
<p>Las diez heurísticas de Jakob Nielsen se publicaron en 1994 y Nielsen Norman Group revisó su texto por última vez el 30 de enero de 2024. Son las más usadas. Un procedimiento recomendado por NN/g (Moran y Gordon, 2023) pide que tres a cinco personas evalúen la misma interfaz de forma independiente, porque cada una pasa por alto problemas que otra ve.</p>
</section>
<section id="las-diez-heurísticas-aplicadas-al-formulario" class="level3">
<h3 class="anchored" data-anchor-id="las-diez-heurísticas-aplicadas-al-formulario">Las diez heurísticas, aplicadas al formulario</h3>
<p>La segunda columna es una paráfrasis en español de cada una. La tercera aplica la heurística a un defecto posible del formulario de la clínica.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>N.°</th>
<th>Heurística</th>
<th>Qué pide</th>
<th>Defecto posible en el formulario</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Visibilidad del estado del sistema</td>
<td>Informar qué ocurre con retroalimentación a tiempo</td>
<td>Tras tocar Confirmar no pasa nada visible durante 4 segundos</td>
</tr>
<tr class="even">
<td>2</td>
<td>Correspondencia entre el sistema y el mundo real</td>
<td>Hablar el lenguaje de la persona, sin jerga</td>
<td>La lista de especialidades muestra códigos internos como MED-GEN-01</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Control y libertad del usuario</td>
<td>Salida de emergencia clara de acciones por error</td>
<td>El botón Atrás del celular borra todo lo escrito</td>
</tr>
<tr class="even">
<td>4</td>
<td>Consistencia y estándares</td>
<td>Mismas palabras y acciones para lo mismo</td>
<td>El botón dice Aceptar, Continuar y Siguiente en tres pasos</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Prevención de errores</td>
<td>Evitar el problema antes de que ocurra</td>
<td>El campo fecha acepta días pasados</td>
</tr>
<tr class="even">
<td>6</td>
<td>Reconocer en lugar de recordar</td>
<td>Mostrar opciones y datos en vez de exigir memoria</td>
<td>Pide el número de afiliación sin mostrarlo en ningún lado</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Flexibilidad y eficiencia de uso</td>
<td>Atajos para quien ya sabe, sin estorbar al novato</td>
<td>No hay opción de repetir el último turno para quien pide siempre lo mismo</td>
</tr>
<tr class="even">
<td>8</td>
<td>Diseño estético y minimalista</td>
<td>No mostrar información irrelevante o rara vez necesaria</td>
<td>Un banner promocional ocupa la mitad de la pantalla</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Ayudar a reconocer, diagnosticar y recuperarse de errores</td>
<td>Mensajes en lenguaje claro que indican el problema y sugieren solución</td>
<td>Un fallo muestra Error 400</td>
</tr>
<tr class="even">
<td>10</td>
<td>Ayuda y documentación</td>
<td>Ayuda breve, buscable y en el contexto de la tarea</td>
<td>El teléfono de la clínica está escondido en el pie de página</td>
</tr>
</tbody>
</table>
</section>
<section id="severidad-cómo-priorizar-los-hallazgos" class="level3">
<h3 class="anchored" data-anchor-id="severidad-cómo-priorizar-los-hallazgos">Severidad: cómo priorizar los hallazgos</h3>
<p>Encontrar problemas no basta. Hay que decidir cuáles se arreglan primero. Nielsen propuso una escala de severidad de 0 a 4 en 1994, que NN/g mantiene publicada.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Valor</th>
<th>Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td>No se considera un problema de usabilidad</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td>Problema cosmético: no urge, se arregla si sobra tiempo</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td>Problema menor: prioridad baja</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td>Problema mayor: importante, prioridad alta</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td>Catástrofe de usabilidad: hay que arreglarlo antes de lanzar</td>
</tr>
</tbody>
</table>
<p>Nielsen explica que la severidad combina tres factores: la frecuencia con que ocurre el problema, el impacto cuando ocurre y la persistencia, es decir, si la persona lo supera una vez o tropieza con él siempre. También advierte que es difícil obtener buenas estimaciones durante la propia evaluación, de modo que conviene promediar las valoraciones de varias personas.</p>
</section>
<section id="ejemplo-resuelto-evaluación-del-formulario-por-tres-evaluadores" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-evaluación-del-formulario-por-tres-evaluadores">Ejemplo resuelto: evaluación del formulario por tres evaluadores</h3>
<p>Tres evaluadores recorren el formulario por separado. Se encontraron diez hallazgos, uno por heurística. Los números son ilustrativos. La columna 25010 relaciona cada hallazgo con una subcaracterística de capacidad de interacción.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Hallazgo (heurística)</th>
<th>Subcaracterística 25010:2023</th>
<th style="text-align: center;">Evaluador A</th>
<th style="text-align: center;">B</th>
<th style="text-align: center;">C</th>
<th style="text-align: center;">Promedio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>9. Error 400 sin explicación</td>
<td>Autodescriptividad</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3,67</td>
</tr>
<tr class="even">
<td>5. Fecha pasada aceptada</td>
<td>Protección frente a errores</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3,00</td>
</tr>
<tr class="odd">
<td>3. Atrás borra lo escrito</td>
<td>Protección frente a errores</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3,33</td>
</tr>
<tr class="even">
<td>2. Códigos en vez de nombres</td>
<td>Autodescriptividad</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">3,33</td>
</tr>
<tr class="odd">
<td>1. Sin progreso al confirmar</td>
<td>Autodescriptividad</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">3,00</td>
</tr>
<tr class="even">
<td>4. Tres nombres para el botón</td>
<td>Capacidad de aprendizaje</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2,00</td>
</tr>
<tr class="odd">
<td>6. Número de afiliación de memoria</td>
<td>Capacidad de aprendizaje</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2,33</td>
</tr>
<tr class="even">
<td>8. Banner promocional</td>
<td>Operabilidad</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2,00</td>
</tr>
<tr class="odd">
<td>10. Ayuda escondida</td>
<td>Asistencia al usuario</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">2,33</td>
</tr>
<tr class="even">
<td>7. Sin repetir último turno</td>
<td>Operabilidad</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">1,00</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Calcula el promedio de cada fila. Por ejemplo, el hallazgo 9: (4 + 4 + 3) / 3 = 3,67.</li>
<li>Ordena de mayor a menor promedio: 9 (3,67), luego 3 y 2 (3,33), luego 5 y 1 (3,00), luego 6 y 10 (2,33), luego 4 y 8 (2,00), y al final 7 (1,00).</li>
<li>Aplica la escala. Cinco hallazgos tienen promedio de 3 o más (9, 3, 2, 5 y 1). Son problemas mayores o catástrofes y se corrigen antes de salir.</li>
<li>Decide. Si el equipo solo tiene tiempo para tres arreglos, elige los de los hallazgos 9, 3 y 2.</li>
<li>Anota lo que la inspección no responde. No dice cuántos pacientes se perderán ni cuánto tardarán. Eso exige observar a personas.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. Prioriza con las valoraciones
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cuatro hallazgos nuevos, valorados por tres evaluadores (A, B, C). Hallazgo W: 4, 3, 3. Hallazgo X: 2, 2, 3. Hallazgo Y: 4, 4, 3. Hallazgo Z: 1, 2, 1. Calcula cada promedio, ordénalos y decide cuáles bloquean el lanzamiento según la escala de Nielsen. Explica por qué el promedio es más confiable que la valoración de una sola persona.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Promedios: W = 10 / 3 = 3,33; X = 7 / 3 = 2,33; Y = 11 / 3 = 3,67; Z = 4 / 3 = 1,33. Orden: Y, W, X, Z.</p>
<p>Con la escala, un 4 indica una catástrofe que hay que arreglar antes de lanzar. Y tiene dos valoraciones de 4 y una de 3, así que se trata como bloqueo. W tiene un 4 y dos 3: también conviene arreglarlo antes de salir, porque al menos un evaluador lo considera catástrofe y los otros dos lo ven como problema mayor. X y Z pueden esperar.</p>
<p>El promedio reduce el sesgo de cada evaluador, porque Nielsen advierte que las estimaciones individuales durante la evaluación son poco fiables. Tu criterio sobre W puede variar si justificas por qué lo tratas como bloqueo o no.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-5.-pruebas-de-usabilidad-con-personas" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="parte-5.-pruebas-de-usabilidad-con-personas"><span class="header-section-number">8</span> Parte 5. Pruebas de usabilidad con personas</h2>
<section id="qué-es-y-cómo-se-planea" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-y-cómo-se-planea">Qué es y cómo se planea</h3>
<p>En una prueba de usabilidad se observa a personas representativas intentando tareas reales con el producto. Se mide qué logran, cuánto tardan, dónde se equivocan y qué dicen. A diferencia de la inspección, muestra lo que ocurre de verdad. Su límite es el costo y el tamaño de la muestra.</p>
<p>Un plan mínimo de prueba responde seis preguntas.</p>
<ol type="1">
<li>Qué se quiere saber. Por ejemplo, si adultos mayores logran pedir un turno sin ayuda.</li>
<li>Quiénes participan. Personas del contexto de uso de la Parte 1, no compañeros del equipo.</li>
<li>Qué tareas hacen. Tareas con un resultado claro, escritas como una situación y no como instrucciones de pantalla.</li>
<li>Qué se mide. Completitud, tiempo, errores y satisfacción.</li>
<li>Cómo se registra. Notas, tiempos y, con permiso, grabación.</li>
<li>Qué criterio decide el resultado. Las metas de la Parte 1.</li>
</ol>
<p>Una regla útil es no ayudar. Si la persona se atasca, el facilitador espera. Si pide ayuda y se le da, la tarea se anota como completada con ayuda, que es un resultado distinto de completada sin ayuda.</p>
</section>
<section id="ejemplo-resuelto-cinco-adultos-mayores-piden-un-turno" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-cinco-adultos-mayores-piden-un-turno">Ejemplo resuelto: cinco adultos mayores piden un turno</h3>
<p>El equipo de la clínica prueba el formulario con cinco adultos mayores. La tarea es la siguiente: “Pida un turno de medicina general para el próximo jueves”. Los resultados de la tabla son ilustrativos. C significa completó sin ayuda, A completó con ayuda y F no completó.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 31%">
<col style="width: 31%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Participante</th>
<th style="text-align: center;">Resultado</th>
<th style="text-align: center;">Tiempo (segundos)</th>
<th>Observación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P1</td>
<td style="text-align: center;">C</td>
<td style="text-align: center;">95</td>
<td>Dudó en el campo fecha</td>
</tr>
<tr class="even">
<td>P2</td>
<td style="text-align: center;">C</td>
<td style="text-align: center;">148</td>
<td>Escribió la fecha con el formato equivocado y rehízo el paso</td>
</tr>
<tr class="odd">
<td>P3</td>
<td style="text-align: center;">A</td>
<td style="text-align: center;">210</td>
<td>Pidió ayuda cuando apareció Error 400</td>
</tr>
<tr class="even">
<td>P4</td>
<td style="text-align: center;">F</td>
<td style="text-align: center;">300 (se detuvo)</td>
<td>Se rindió en el paso de la fecha</td>
</tr>
<tr class="odd">
<td>P5</td>
<td style="text-align: center;">C</td>
<td style="text-align: center;">120</td>
<td>Tocó dos veces el botón Continuar</td>
</tr>
</tbody>
</table>
<ul>
<li>Efectividad. Tres de cinco completaron sin ayuda, o sea 60 %. Cuatro de cinco lograron el turno si se cuenta la ayuda, 80 %. La meta era al menos 80 % sin ayuda, así que el resultado queda por debajo.</li>
<li>Eficiencia. Entre quienes completaron sin ayuda, el tiempo medio fue (95 + 148 + 120) / 3 = 121 segundos. La meta era 120 segundos o menos. El resultado la roza, pero con tres datos no hay base para afirmar que se cumple.</li>
<li>Satisfacción. Se mide con el cuestionario SUS de la Parte 6.</li>
</ul>
</section>
<section id="cuánta-confianza-da-un-60-con-cinco-personas" class="level3">
<h3 class="anchored" data-anchor-id="cuánta-confianza-da-un-60-con-cinco-personas">Cuánta confianza da un 60 % con cinco personas</h3>
<p>Un porcentaje con muestras pequeñas viene con una incertidumbre grande. Un método sencillo para una proporción es el intervalo de Agresti y Coull (1998), también llamado Wald ajustado. Con un nivel de confianza de 95 % (z = 1,96, z al cuadrado = 3,8416) se calcula así.</p>
<ol type="1">
<li>Datos: x = 3 éxitos, n = 5 intentos.</li>
<li>Proporción ajustada: p = (x + 1,9208) / (n + 3,8416) = 4,9208 / 8,8416 = 0,5566.</li>
<li>Error estándar: raíz de p (1 - p) / (n + 3,8416) = raíz de (0,5566 x 0,4434 / 8,8416) = 0,1671.</li>
<li>Intervalo: p mas o menos 1,96 x 0,1671 = 0,5566 mas o menos 0,3275, es decir, de 22,9 % a 88,4 %.</li>
</ol>
<p>El intervalo va de 22,9 % a 88,4 %. La meta de 80 % cae dentro. La prueba no confirma que la meta se cumpla ni que falle. Lo que sí entrega es otra cosa: los problemas que explican los resultados (formato de fecha, error 400, botón repetido). Una prueba con cinco personas sirve para encontrar problemas, no para estimar porcentajes con precisión.</p>
</section>
<section id="cuántas-personas-hacen-falta" class="level3">
<h3 class="anchored" data-anchor-id="cuántas-personas-hacen-falta">Cuántas personas hacen falta</h3>
<p>Nielsen y Landauer propusieron en 1993 un modelo matemático. Si N es el total de problemas de la interfaz y L la proporción que descubre una sola persona, con n personas se encuentra una proporción de 1 - (1 - L) elevado a n.&nbsp;Nielsen indica que el valor típico de L, promediado sobre los proyectos que estudiaron, fue de 31 %.</p>
<p>Con L = 0,31, la proporción descubierta es 1 - 0,69 elevado a n.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Personas (n)</th>
<th style="text-align: center;">Problemas hallados</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">31,0 %</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">52,4 %</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">67,1 %</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">77,3 %</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">84,4 %</td>
</tr>
<tr class="even">
<td style="text-align: center;">7</td>
<td style="text-align: center;">92,6 %</td>
</tr>
<tr class="odd">
<td style="text-align: center;">10</td>
<td style="text-align: center;">97,6 %</td>
</tr>
<tr class="even">
<td style="text-align: center;">15</td>
<td style="text-align: center;">99,6 %</td>
</tr>
</tbody>
</table>
<div class="diagrama">
<svg viewbox="0 0 760 302" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Diez barras del modelo de descubrimiento de problemas con L igual a 31 por ciento: de 31 por ciento con una persona a 97,6 por ciento con diez; con cinco personas se llega a 84,4 por ciento" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Problemas descubiertos según el número de personas (modelo con L = 31 %)</text> <line x1="60" y1="240" x2="700" y2="240" stroke="#cfd8e3" stroke-width="1.4"></line> <rect x="80" y="181.1" width="44" height="58.9" rx="3" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="140" y="140.4" width="44" height="99.6" rx="3" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="200" y="112.5" width="44" height="127.5" rx="3" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="260" y="93.1" width="44" height="146.9" rx="3" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="320" y="79.6" width="44" height="160.4" rx="3" fill="#fff3d6" stroke="#e6c46f"></rect><rect x="380" y="70.5" width="44" height="169.5" rx="3" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="440" y="64.1" width="44" height="175.9" rx="3" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="500" y="59.7" width="44" height="180.3" rx="3" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="560" y="56.7" width="44" height="183.3" rx="3" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="620" y="54.6" width="44" height="185.4" rx="3" fill="#eef4fa" stroke="#c7d6e6"></rect> <g font-size="11" fill="#12324f" text-anchor="middle"><text x="102" y="175.1">31,0</text><text x="162" y="134.4">52,4</text><text x="222" y="106.5">67,1</text><text x="282" y="87.1">77,3</text><text x="342" y="73.6" font-weight="700">84,4</text><text x="402" y="64.5">89,2</text><text x="462" y="58.1">92,6</text><text x="522" y="53.7">94,9</text><text x="582" y="50.7">96,5</text><text x="642" y="48.6">97,6</text></g> <g font-size="11.5" fill="#5b6876" text-anchor="middle"><text x="102" y="258">1</text><text x="162" y="258">2</text><text x="222" y="258">3</text><text x="282" y="258">4</text><text x="342" y="258" font-weight="700" fill="#12324f">5</text><text x="402" y="258">6</text><text x="462" y="258">7</text><text x="522" y="258">8</text><text x="582" y="258">9</text><text x="642" y="258">10</text></g> <text x="380" y="276" font-size="11.5" fill="#5b6876" text-anchor="middle">Personas que prueban (n). Porcentaje de problemas descubiertos sobre el eje vertical.</text> <text x="380" y="293" font-size="11.5" fill="#855400" text-anchor="middle">Es un promedio. En conjuntos reales de cinco personas se observaron valores entre 55 % y 99 % (Faulkner, 2003).</text>
</svg>
</div>
</section>
<section id="los-límites-de-la-regla-de-las-cinco-personas" class="level3">
<h3 class="anchored" data-anchor-id="los-límites-de-la-regla-de-las-cinco-personas">Los límites de la regla de las cinco personas</h3>
<p>El resultado se sostiene para estudios cualitativos, donde el objetivo es encontrar problemas, pero tiene límites que hay que conocer.</p>
<ol type="1">
<li>Es un promedio. Faulkner (2003) probó 60 personas y sacó conjuntos aleatorios de cinco. Algunos conjuntos de cinco hallaron 99 % de los problemas y otros solo 55 %. Con diez personas el peor conjunto subió a 80 %, y con veinte a 95 %.</li>
<li>L cambia según el proyecto. Si los problemas son difíciles de ver, L es menor. Con L = 0,10, cinco personas descubren 1 - 0,9 elevado a 5 = 41 %.</li>
<li>Hay grupos distintos. Nielsen recomienda 3 o 4 personas por cada categoría si son dos grupos, y 3 por categoría si son tres o más.</li>
<li>Hay estudios que no son de problemas. Nielsen (2012) indica al menos 20 personas para estudios cuantitativos de usabilidad y 15 por grupo para ordenamiento de tarjetas.</li>
<li>Probar más veces rinde más que probar más personas. Nielsen prefiere varios estudios pequeños, con correcciones entre uno y otro, a un estudio grande.</li>
</ol>
<p>Para la clínica, esto significa una prueba con cinco personas mayores, arreglar lo hallado y repetir con otros cinco. Si además hay pacientes con baja visión que usan lector de pantalla, constituyen un segundo grupo con sus propias personas.</p>
</section>
<section id="ejemplo-resuelto-cuántas-personas-para-encontrar-al-menos-90-de-los-problemas" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-cuántas-personas-para-encontrar-al-menos-90-de-los-problemas">Ejemplo resuelto: cuántas personas para encontrar al menos 90 % de los problemas</h3>
<p>El equipo quiere un 90 % de descubrimiento con L = 0,31. Se resuelve 1 - 0,69 elevado a n mayor o igual a 0,90.</p>
<ol type="1">
<li>Despeja: 0,69 elevado a n menor o igual a 0,10.</li>
<li>Toma logaritmos: n mayor o igual a ln(0,10) / ln(0,69) = (-2,3026) / (-0,3711) = 6,2.</li>
<li>Redondea hacia arriba: n = 7. Con 7 personas se descubre 92,6 %. Con 6 se queda en 89,2 %, por debajo de la meta.</li>
<li>Ajusta por grupos. Si la clínica prueba con dos grupos (adultos mayores y personas con baja visión), aplica 3 o 4 por grupo, es decir, de 6 a 8 en total.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 4. Muestra e intervalo
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="a">
<li>De 8 personas, 7 completan una tarea sin ayuda. Calcula el intervalo de Agresti y Coull con 95 % de confianza. b) Con L = 0,31, ¿cuántas personas se necesitan para descubrir al menos 95 % de los problemas?</li>
<li>¿Qué conclusión sobre una meta de 90 % de efectividad permite el resultado del punto a?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>p = (7 + 1,9208) / (8 + 3,8416) = 8,9208 / 11,8416 = 0,7533. Error estándar: raíz de (0,7533 x 0,2467 / 11,8416) = 0,1253. Intervalo: 0,7533 mas o menos 1,96 x 0,1253 = 0,7533 mas o menos 0,2456, es decir, de 50,8 % a 99,9 %.</p></li>
<li><p>0,69 elevado a n menor o igual a 0,05: n mayor o igual a ln(0,05) / ln(0,69) = (-2,9957) / (-0,3711) = 8,07. Se necesitan 9 personas (con 8 se llega a 94,9 %).</p></li>
<li><p>El intervalo va de 50,8 % a unos 99,9 % y contiene el 90 %. Con 8 personas no se puede afirmar ni que la meta se cumple ni que se incumple. Para decidirlo hace falta una muestra mayor.</p></li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="parte-6.-el-cuestionario-sus" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="parte-6.-el-cuestionario-sus"><span class="header-section-number">9</span> Parte 6. El cuestionario SUS</h2>
<section id="qué-es-y-de-dónde-viene" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-y-de-dónde-viene">Qué es y de dónde viene</h3>
<p>La <em>System Usability Scale</em> (SUS) es un cuestionario de diez ítems que mide la usabilidad percibida con una puntuación de 0 a 100. John Brooke la desarrolló en Digital Equipment Co.&nbsp;Ltd.&nbsp;(Reino Unido), con aviso de derechos de 1986, como una medida “rápida y sencilla”, y la describió en un capítulo de 1996. Brooke la puso a disposición gratuita, con la condición de citar la fuente. La publicación original aclara que la puntuación es global y que los ítems por separado no significan nada por sí solos.</p>
<p>Se usa después de que la persona haya usado el sistema y antes de cualquier conversación sobre él. Se pide la reacción inmediata y se responden todos los ítems. Si una persona no puede responder uno, marca el punto medio.</p>
</section>
<section id="los-diez-ítems" class="level3">
<h3 class="anchored" data-anchor-id="los-diez-ítems">Los diez ítems</h3>
<p>Cada ítem se responde en una escala de 1 (muy en desacuerdo) a 5 (muy de acuerdo). Los ítems alternan afirmaciones positivas (impares) y negativas (pares). Esa alternancia obliga a leer cada frase. La traducción siguiente es propia de esta guía. Para un estudio formal conviene usar una versión en español con validación publicada.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 62%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">N.°</th>
<th>Ítem (traducción de esta guía del original de Brooke)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td>Creo que me gustaría usar este sistema con frecuencia</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td>Encontré el sistema innecesariamente complejo</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td>Pensé que el sistema era fácil de usar</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td>Creo que necesitaría el apoyo de una persona técnica para poder usar este sistema</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td>Encontré que las diversas funciones del sistema estaban bien integradas</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td>Pensé que había demasiada inconsistencia en este sistema</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td>Imagino que la mayoría de las personas aprendería a usar este sistema muy rápido</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td>Encontré el sistema muy incómodo de usar</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td>Me sentí muy seguro usando el sistema</td>
</tr>
<tr class="even">
<td style="text-align: center;">10</td>
<td>Necesité aprender muchas cosas antes de poder empezar con este sistema</td>
</tr>
</tbody>
</table>
</section>
<section id="cómo-se-calcula" class="level3">
<h3 class="anchored" data-anchor-id="cómo-se-calcula">Cómo se calcula</h3>
<p>La regla de Brooke tiene tres pasos.</p>
<ol type="1">
<li>En los ítems impares (1, 3, 5, 7, 9), la contribución es la respuesta menos 1.</li>
<li>En los ítems pares (2, 4, 6, 8, 10), la contribución es 5 menos la respuesta.</li>
<li>Se suman las diez contribuciones (cada una va de 0 a 4) y la suma se multiplica por 2,5. El resultado va de 0 a 100.</li>
</ol>
<p>El multiplicador 2,5 aparece porque la suma máxima es 40 y 40 x 2,5 = 100. La puntuación no es un porcentaje. Un 70 no significa 70 % de usabilidad.</p>
</section>
<section id="ejemplo-resuelto-participante-p1" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-participante-p1">Ejemplo resuelto: participante P1</h3>
<p>P1 respondió los diez ítems en este orden: 4, 2, 4, 2, 4, 2, 3, 2, 4, 2.</p>
<ol type="1">
<li>Ítems impares: 1 (respuesta 4), 3 (respuesta 4), 5 (respuesta 4), 7 (respuesta 3), 9 (respuesta 4). Contribuciones: 3, 3, 3, 2, 3. Suma: 14.</li>
<li>Ítems pares: 2 (respuesta 2), 4 (respuesta 2), 6 (respuesta 2), 8 (respuesta 2), 10 (respuesta 2). Contribuciones: 3, 3, 3, 3, 3. Suma: 15.</li>
<li>Total: 14 + 15 = 29.</li>
<li>Puntuación SUS: 29 x 2,5 = 72,5.</li>
</ol>
</section>
<section id="resultados-de-los-cinco-participantes" class="level3">
<h3 class="anchored" data-anchor-id="resultados-de-los-cinco-participantes">Resultados de los cinco participantes</h3>
<p>Los otros cuatro participantes de la prueba de la Parte 5 también respondieron el SUS. Los números son ilustrativos.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Participante</th>
<th>Respuestas (ítems 1 a 10)</th>
<th style="text-align: center;">Suma impares</th>
<th style="text-align: center;">Suma pares</th>
<th style="text-align: center;">Total</th>
<th style="text-align: center;">SUS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P1</td>
<td>4, 2, 4, 2, 4, 2, 3, 2, 4, 2</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">29</td>
<td style="text-align: center;">72,5</td>
</tr>
<tr class="even">
<td>P2</td>
<td>3, 3, 3, 3, 3, 3, 3, 3, 3, 3</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">50,0</td>
</tr>
<tr class="odd">
<td>P3</td>
<td>3, 3, 3, 3, 3, 2, 3, 3, 3, 3</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">52,5</td>
</tr>
<tr class="even">
<td>P4</td>
<td>2, 4, 3, 4, 3, 4, 2, 4, 3, 3</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">14</td>
<td style="text-align: center;">35,0</td>
</tr>
<tr class="odd">
<td>P5</td>
<td>4, 2, 3, 2, 4, 2, 4, 2, 3, 2</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">70,0</td>
</tr>
</tbody>
</table>
<p>La media es (72,5 + 50,0 + 52,5 + 35,0 + 70,0) / 5 = 280 / 5 = 56,0. La desviación estándar de la muestra es 15,5. Con t de Student para 4 grados de libertad (2,776), el intervalo de 95 % es 56,0 mas o menos 2,776 x 15,5 / raíz de 5, es decir, 56,0 mas o menos 19,2, de 36,8 a 75,2.</p>
</section>
<section id="cómo-interpretar-la-puntuación-la-referencia-de-68" class="level3">
<h3 class="anchored" data-anchor-id="cómo-interpretar-la-puntuación-la-referencia-de-68">Cómo interpretar la puntuación: la referencia de 68</h3>
<p>Para dar sentido a un número, MeasuringU (Jeff Sauro) compara la puntuación con una base de datos acumulada. La página consultada habla de unas tres décadas de uso y más de 10.000 respuestas de cientos de productos, y ubica el promedio, en el percentil 50, en 68. Esa cifra es una referencia de esa base de datos, no un umbral que defina la norma ni el propio Brooke.</p>
<p>La misma fuente da una escala de notas por rangos. Los rangos de abajo vienen de su tabla.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 35%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Rango SUS</th>
<th style="text-align: center;">Nota</th>
<th>Adjetivo</th>
<th>Aceptabilidad (según la tabla de MeasuringU)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>84,1 a 100</td>
<td style="text-align: center;">A+</td>
<td>Mejor imaginable</td>
<td>Aceptable</td>
</tr>
<tr class="even">
<td>80,8 a 84,0</td>
<td style="text-align: center;">A</td>
<td>Excelente</td>
<td>Aceptable</td>
</tr>
<tr class="odd">
<td>71,1 a 80,7</td>
<td style="text-align: center;">C+ a A-</td>
<td>Bueno (solo de 71,1 a 72,5)</td>
<td>Aceptable</td>
</tr>
<tr class="even">
<td>62,7 a 71,0</td>
<td style="text-align: center;">C- y C</td>
<td>(sin adjetivo propio)</td>
<td>Marginal</td>
</tr>
<tr class="odd">
<td>51,7 a 62,6</td>
<td style="text-align: center;">D</td>
<td>OK</td>
<td>Marginal</td>
</tr>
<tr class="even">
<td>25,1 a 51,6</td>
<td style="text-align: center;">F</td>
<td>Pobre</td>
<td>No aceptable</td>
</tr>
<tr class="odd">
<td>0 a 25,0</td>
<td style="text-align: center;">F</td>
<td>Peor imaginable</td>
<td>No aceptable</td>
</tr>
</tbody>
</table>
<div class="diagrama">
<svg viewbox="0 0 760 252" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Escala SUS de 0 a 100 con bandas de nota: F hasta 51,6; D de 51,7 a 62,6; C- y C de 62,7 a 71,0; C+ a A- de 71,1 a 80,7; A y A+ de 80,8 a 100. Marcas: promedio de referencia 68, media del ejemplo 56,0 con intervalo de 36,8 a 75,2" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Escala SUS y el resultado del formulario</text> <g stroke-width="1"><rect x="60" y="70" width="330.2" height="34" fill="#fbeae5" stroke="#e0a595"></rect><rect x="390.9" y="70" width="70.1" height="34" fill="#fff3d6" stroke="#e6c46f"></rect><rect x="461" y="70" width="53.7" height="34" fill="#eef4fa" stroke="#c7d6e6"></rect><rect x="514.7" y="70" width="62.1" height="34" fill="#e4f2f1" stroke="#8fc9c5"></rect><rect x="576.8" y="70" width="123.2" height="34" fill="#cfe9e6" stroke="#8fc9c5"></rect></g> <g font-size="12" font-weight="700" fill="#12324f" text-anchor="middle"><text x="225" y="92">F</text><text x="426" y="92">D</text><text x="488" y="92">C</text><text x="546" y="92">C+ a A-</text><text x="638" y="92">A y A+</text></g> <g font-size="11" fill="#5b6876" text-anchor="middle"><text x="60" y="120">0</text><text x="124" y="120">10</text><text x="188" y="120">20</text><text x="252" y="120">30</text><text x="316" y="120">40</text><text x="380" y="120">50</text><text x="444" y="120">60</text><text x="508" y="120">70</text><text x="572" y="120">80</text><text x="636" y="120">90</text><text x="700" y="120">100</text></g> <line x1="295.5" y1="150" x2="541.3" y2="150" stroke="#12324f" stroke-width="2"></line> <line x1="295.5" y1="142" x2="295.5" y2="158" stroke="#12324f" stroke-width="2"></line><line x1="541.3" y1="142" x2="541.3" y2="158" stroke="#12324f" stroke-width="2"></line> <circle cx="418.4" cy="150" r="7" fill="#fff3d6" stroke="#855400" stroke-width="2"></circle> <line x1="495.2" y1="40" x2="495.2" y2="196" stroke="#0e6f6c" stroke-width="1.8" stroke-dasharray="5 4"></line> <text x="495" y="36" font-size="11.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Referencia de MeasuringU: 68</text> <text x="418" y="178" font-size="12" font-weight="700" fill="#855400" text-anchor="middle">Media del ejemplo: 56,0</text> <text x="418" y="196" font-size="11" fill="#12324f" text-anchor="middle">Intervalo de 95 %: de 36,8 a 75,2</text> <rect x="60" y="212" width="640" height="30" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="380" y="232" font-size="11.5" fill="#12324f" text-anchor="middle">El intervalo cruza el 68: con cinco personas no se puede decir que el formulario esté por debajo del promedio</text>
</svg>
</div>
</section>
<section id="qué-concluye-el-equipo" class="level3">
<h3 class="anchored" data-anchor-id="qué-concluye-el-equipo">Qué concluye el equipo</h3>
<ol type="1">
<li>La media de 56,0 cae en la nota D, en el rango marginal.</li>
<li>La meta de la Parte 1 era una media de al menos 68. El resultado está por debajo, pero el intervalo (36,8 a 75,2) incluye el 68.</li>
<li>Con cinco personas, la conclusión honesta es “indicios de usabilidad marginal, a confirmar”. Se debe repetir con más personas después de corregir los problemas.</li>
<li>La dispersión es grande: P1 y P5 puntúan 72,5 y 70,0 y P4 solo 35,0. Esa diferencia es una pista. Hay que mirar quién es P4 y qué le pasó en la prueba.</li>
<li>El SUS dice cuánto, no por qué. El porqué sale de las observaciones de la Parte 5 y de la inspección de la Parte 4.</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 5. Calcula y piensa
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="a">
<li>Un participante respondió: 5, 1, 4, 2, 5, 1, 5, 1, 4, 1. Calcula su puntuación SUS y ubícala en la tabla de notas. b) Otro participante marcó 5 en los diez ítems. Calcula su puntuación y explica qué muestra sobre la alternancia de ítems positivos y negativos. c) ¿Qué dos advertencias harías antes de comparar la media de la clínica contra 68?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>Impares: 5, 4, 5, 5, 4 menos 1 cada uno: 4, 3, 4, 4, 3, suma 18. Pares: 1, 2, 1, 1, 1; cinco menos la respuesta: 4, 3, 4, 4, 4, suma 19. Total 37, por 2,5 da 92,5. Está en el rango de 84,1 a 100, nota A+.</p></li>
<li><p>Impares: 5 menos 1 son 4 por cinco ítems, suma 20. Pares: 5 menos 5 son 0, suma 0. Total 20, por 2,5 da 50,0. Una persona que marca todo 5 sin leer no obtiene un resultado extremo, porque las frases negativas contrarrestan a las positivas. Esa es la función de la alternancia.</p></li>
<li><p>Primera, que 68 es el promedio de la base de datos de MeasuringU, no un umbral normativo, y que la clínica debería compararse con su versión anterior y con productos parecidos. Segunda, que con pocas personas el intervalo es amplio y puede incluir el 68, de modo que la comparación no es concluyente.</p></li>
</ol>
</div>
</div>
</div>
</section>
<section id="errores-frecuentes-con-el-sus" class="level3">
<h3 class="anchored" data-anchor-id="errores-frecuentes-con-el-sus">Errores frecuentes con el SUS</h3>
<ul>
<li>Interpretar un ítem aislado. Brooke advierte que los ítems por separado no tienen significado.</li>
<li>Leer la puntuación como porcentaje.</li>
<li>Cambiar o quitar ítems sin avisar y seguir comparando con 68.</li>
<li>Pasar el cuestionario antes de que la persona termine las tareas.</li>
<li>Concluir con 5 personas como si fueran 50.</li>
</ul>
</section>
</section>
<section id="parte-7.-accesibilidad-con-wcag-2.2" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="parte-7.-accesibilidad-con-wcag-2.2"><span class="header-section-number">10</span> Parte 7. Accesibilidad con WCAG 2.2</h2>
<section id="qué-es-wcag-y-qué-versión-rige" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-wcag-y-qué-versión-rige">Qué es WCAG y qué versión rige</h3>
<p>Las Pautas de Accesibilidad para el Contenido Web (<em>Web Content Accessibility Guidelines</em>, WCAG) las publica el W3C. La versión 2.2 es Recomendación del W3C. Se publicó el 5 de octubre de 2023 y la versión consultada es la republicación del 12 de diciembre de 2024. WCAG 2.2 extiende a la 2.1 (junio de 2018) y el W3C indica que el contenido que cumple WCAG 2.2 también cumple WCAG 2.0 y 2.1.</p>
<p>Hay un cambio de versión que conviene conocer. WCAG 2.2 agrega nueve criterios de éxito nuevos y elimina el 4.1.1 (Análisis sintáctico), que el W3C considera siempre cumplido para HTML y XML. Según fuentes secundarias, la versión 2.2 queda con 86 criterios (los 78 de WCAG 2.1, más 9, menos 1). WCAG 2.2 no invalida a 2.0 ni a 2.1.</p>
</section>
<section id="principios-y-niveles-de-conformidad" class="level3">
<h3 class="anchored" data-anchor-id="principios-y-niveles-de-conformidad">Principios y niveles de conformidad</h3>
<p>WCAG se organiza en cuatro principios: perceptible, operable, comprensible y robusto. Cada criterio de éxito tiene un nivel de conformidad: A, AA o AAA. Cumplir el nivel AA exige satisfacer todos los criterios A y AA. El nivel AA es el que exige la Resolución 1519 de 2020 de Colombia, con WCAG 2.1.</p>
<p>Los nueve criterios nuevos de WCAG 2.2 son los siguientes.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 45%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Criterio</th>
<th style="text-align: center;">Nivel</th>
<th>Qué pide</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2.4.11 Foco no oculto (mínimo)</td>
<td style="text-align: center;">AA</td>
<td>Al recibir foco del teclado, el elemento queda al menos parcialmente visible</td>
</tr>
<tr class="even">
<td>2.4.12 Foco no oculto (mejorado)</td>
<td style="text-align: center;">AAA</td>
<td>El elemento con foco queda totalmente visible</td>
</tr>
<tr class="odd">
<td>2.4.13 Apariencia del foco</td>
<td style="text-align: center;">AAA</td>
<td>El indicador de foco tiene tamaño y contraste mínimos</td>
</tr>
<tr class="even">
<td>2.5.7 Movimientos de arrastre</td>
<td style="text-align: center;">AA</td>
<td>Todo lo que se hace arrastrando tiene una alternativa con un solo puntero</td>
</tr>
<tr class="odd">
<td>2.5.8 Tamaño del objetivo (mínimo)</td>
<td style="text-align: center;">AA</td>
<td>Los objetivos táctiles miden al menos 24 por 24 píxeles CSS, o tienen espacio suficiente</td>
</tr>
<tr class="even">
<td>3.2.6 Ayuda consistente</td>
<td style="text-align: center;">A</td>
<td>Los mecanismos de ayuda aparecen en el mismo lugar entre páginas</td>
</tr>
<tr class="odd">
<td>3.3.7 Entrada redundante</td>
<td style="text-align: center;">A</td>
<td>No se pide dos veces lo ya escrito en el mismo proceso</td>
</tr>
<tr class="even">
<td>3.3.8 Autenticación accesible (mínimo)</td>
<td style="text-align: center;">AA</td>
<td>No se exige una prueba de función cognitiva sin alternativa o ayuda</td>
</tr>
<tr class="odd">
<td>3.3.9 Autenticación accesible (mejorado)</td>
<td style="text-align: center;">AAA</td>
<td>Ni siquiera con reconocimiento de objetos o contenido personal</td>
</tr>
</tbody>
</table>
</section>
<section id="ejemplo-resuelto-contraste-del-texto-del-formulario" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-contraste-del-texto-del-formulario">Ejemplo resuelto: contraste del texto del formulario</h3>
<p>El criterio 1.4.3 Contraste (mínimo, AA) pide una relación de contraste de al menos 4,5 a 1 para el texto, y de 3 a 1 para texto grande (18 puntos, o 14 puntos en negrita). La relación se calcula con (L1 + 0,05) / (L2 + 0,05), donde L1 es la luminancia relativa del color más claro y L2 la del más oscuro. La luminancia de un color sRGB es 0,2126 R + 0,7152 G + 0,0722 B, con cada canal convertido primero.</p>
<p>La etiqueta del formulario usa gris #999999 sobre fondo blanco.</p>
<ol type="1">
<li>Canal: 153 / 255 = 0,6. Conversión: ((0,6 + 0,055) / 1,055) elevado a 2,4 = 0,3185.</li>
<li>Los tres canales valen lo mismo, así que la luminancia del gris es 0,3185. La del blanco es 1.</li>
<li>Contraste: (1 + 0,05) / (0,3185 + 0,05) = 1,05 / 0,3685 = 2,85 a 1.</li>
<li>Conclusión: 2,85 es menor que 4,5, así que el criterio falla. Tampoco llega a 3 a 1.</li>
<li>Corrección: gris #595959. Canal 89 / 255 = 0,349, conversión 0,0999. Contraste: 1,05 / 0,1499 = 7,0 a 1. Pasa, con holgura.</li>
</ol>
<p>El gris más claro que todavía pasa el criterio 1.4.3 sobre blanco es #767676, con 4,54 a 1.</p>
</section>
<section id="ejemplo-resuelto-revisión-del-formulario-contra-diez-criterios" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-revisión-del-formulario-contra-diez-criterios">Ejemplo resuelto: revisión del formulario contra diez criterios</h3>
<p>Una persona revisa el formulario contra diez criterios de WCAG 2.2. Los resultados son ilustrativos y se diseñaron para el ejercicio.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 45%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Criterio</th>
<th style="text-align: center;">Resultado</th>
<th>Hallazgo en el formulario</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.3.5 Identificar el propósito de los campos (AA)</td>
<td style="text-align: center;">Falla</td>
<td>Los campos de nombre y cédula no declaran su propósito para el autocompletado</td>
</tr>
<tr class="even">
<td>1.4.3 Contraste mínimo (AA)</td>
<td style="text-align: center;">Falla</td>
<td>Etiquetas en gris #999999, contraste 2,85 a 1</td>
</tr>
<tr class="odd">
<td>1.4.4 Cambio de tamaño del texto (AA)</td>
<td style="text-align: center;">Pasa</td>
<td>El texto se amplía al 200 % sin perder contenido</td>
</tr>
<tr class="even">
<td>1.4.10 Reflujo (AA)</td>
<td style="text-align: center;">Falla</td>
<td>A 320 píxeles de ancho el botón Continuar queda fuera de pantalla y exige desplazarse en horizontal</td>
</tr>
<tr class="odd">
<td>2.1.1 Teclado (A)</td>
<td style="text-align: center;">Falla</td>
<td>El selector de fecha personalizado no se puede operar con teclado</td>
</tr>
<tr class="even">
<td>2.5.8 Tamaño del objetivo, mínimo (AA)</td>
<td style="text-align: center;">Falla</td>
<td>Cancelar mide 18 por 18 píxeles y está pegado a Continuar</td>
</tr>
<tr class="odd">
<td>3.3.1 Identificación de errores (A)</td>
<td style="text-align: center;">Falla</td>
<td>El mensaje Error 400 no dice qué campo falló ni por qué</td>
</tr>
<tr class="even">
<td>3.3.2 Etiquetas o instrucciones (A)</td>
<td style="text-align: center;">Pasa</td>
<td>Cada campo tiene su etiqueta visible</td>
</tr>
<tr class="odd">
<td>3.3.7 Entrada redundante (A)</td>
<td style="text-align: center;">Falla</td>
<td>La cédula se pide en el paso 1 y de nuevo en el paso 3</td>
</tr>
<tr class="even">
<td>3.3.8 Autenticación accesible, mínimo (AA)</td>
<td style="text-align: center;">Falla</td>
<td>El campo de clave bloquea pegar y no ofrece otra forma de ingresar</td>
</tr>
</tbody>
</table>
<p>Resultado: 2 criterios pasan y 8 fallan, así que el formulario no alcanza el nivel AA. Se corrige empezando por los que bloquean la tarea (teclado, errores, reflujo) y se vuelve a revisar con los diez criterios.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Lo que una revisión así no cubre
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los diez criterios de la tabla son una muestra. Una evaluación completa de WCAG 2.2 AA revisa todos los criterios A y AA aplicables. Además, ninguna herramienta automática sustituye la revisión manual ni la prueba con personas que usan tecnologías de apoyo, como lectores de pantalla. Cumplir WCAG tampoco garantiza buena usabilidad: un formulario puede cumplir todos los criterios y seguir confundiendo a Marta.</p>
</div>
</div>
</section>
<section id="wcag-2.2-como-norma-iso-y-el-borrador-de-wcag-3.0" class="level3">
<h3 class="anchored" data-anchor-id="wcag-2.2-como-norma-iso-y-el-borrador-de-wcag-3.0">WCAG 2.2 como norma ISO y el borrador de WCAG 3.0</h3>
<p>WCAG 2.2 también es norma ISO. La ficha de ISO muestra la ISO/IEC 40500:2025 (edición 2, septiembre de 2025), titulada <em>Information technology, W3C Web Content Accessibility Guidelines (WCAG) 2.2</em>, de descarga gratuita. En esa misma ficha, ISO indica que se espera que sea reemplazada por una versión en borrador (ISO/IEC DIS 40500) en los próximos meses. Por eso conviene volver a consultar la ficha antes de citarla en un documento formal.</p>
<p>WCAG 3.0 es un borrador. La versión consultada es un <em>Working Draft</em> del 10 de septiembre de 2026. El propio documento dice que puede ser actualizado, reemplazado u obsoleto en cualquier momento y que es inapropiado citarlo como algo distinto de un trabajo en progreso. Además dice que es sucesor de WCAG 2.2 y que no reemplaza a WCAG 2. Usa un modelo distinto, con resultados, requisitos y métodos, en lugar de criterios de éxito. Hoy no hay base para exigirlo a un producto: los requisitos vigentes se escriben contra WCAG 2.x.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 6. Contraste y objetivo táctil
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="a">
<li>El texto de ayuda del formulario es gris #8A8A8A sobre fondo blanco, a 16 píxeles. Con la luminancia 0,2542 calcula el contraste y decide si cumple 1.4.3. b) ¿Cambiaría la respuesta si el texto fuera de 24 píxeles en negrita? c) El botón Cancelar mide 18 por 18 píxeles y el vecino está a 4 píxeles. ¿Se cumple 2.5.8? ¿Qué cambio mínimo lo arregla?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>Contraste: (1 + 0,05) / (0,2542 + 0,05) = 1,05 / 0,3042 = 3,45 a 1. Es menor que 4,5, así que no cumple 1.4.3 para texto normal.</p></li>
<li><p>Sí podría cambiar. Texto grande es de al menos 18 puntos, o 14 puntos en negrita. Un texto de 24 píxeles en negrita equivale a 18 puntos en negrita, así que cuenta como texto grande, que solo exige 3 a 1, y 3,45 cumple. Con 16 píxeles no se acerca a ser texto grande.</p></li>
<li><p>No se cumple: el objetivo es menor de 24 por 24 píxeles y el espacio de 4 píxeles no basta para la excepción, en la que los círculos de 24 píxeles de diámetro centrados en cada objetivo no deben cruzarse con otros. El cambio mínimo es llevar el objetivo a 24 por 24 píxeles. Un tamaño mayor resulta más cómodo para Marta.</p></li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="parte-8.-marco-normativo-de-accesibilidad" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="parte-8.-marco-normativo-de-accesibilidad"><span class="header-section-number">11</span> Parte 8. Marco normativo de accesibilidad</h2>
<section id="colombia" class="level3">
<h3 class="anchored" data-anchor-id="colombia">Colombia</h3>
<p>En Colombia, el marco legal parte de la Ley 1618 de 2013, que exige definir estándares de accesibilidad web (su artículo 16, numeral 11, según se cita en los considerandos de la resolución). La Resolución 1519 de 2020 del Ministerio de Tecnologías de la Información y las Comunicaciones (MinTIC), del 24 de agosto de 2020, define las directrices de accesibilidad web.</p>
<p>Lo que dice la resolución, en su artículo 3 y en el Anexo 1, es lo siguiente.</p>
<ul>
<li>Desde el 1 de enero de 2022, los sujetos obligados deben cumplir los estándares AA de WCAG en su versión 2.1.</li>
<li>Los sujetos obligados son los del artículo 5 de la Ley 1712 de 2014, la ley de transparencia.</li>
<li>La resolución deroga la Resolución MinTIC 3564 de 2015.</li>
<li>El Anexo 1 define alcance, definiciones y criterios para sitios web y contenidos a cargo de los sujetos obligados.</li>
</ul>
<p>Se verificó el texto de la resolución y de su Anexo 1 en el sitio de MinTIC. El estándar exigido es WCAG 2.1 nivel AA, no WCAG 2.2. No se verificó si una norma posterior lo actualizó.</p>
</section>
<section id="la-ntc-5854" class="level3">
<h3 class="anchored" data-anchor-id="la-ntc-5854">La NTC 5854</h3>
<p>La NTC 5854 es una norma técnica colombiana de ICONTEC titulada “Accesibilidad a páginas web”. El catálogo de la tienda de ICONTEC la lista con la edición 2011 (NTC 5854:2011). Eso es lo que se pudo verificar en fuente primaria.</p>
<p>Lo que no se verificó, porque el texto es de pago y no se leyó, es su alcance exacto, su relación técnica con las versiones de WCAG y si el organismo la confirmó o la actualizó después de 2011. Lo que sí se verificó es que ni el cuerpo de la Resolución 1519 de 2020 ni su Anexo 1 mencionan la NTC 5854: la exigencia vigente del Estado para sus portales se escribe contra WCAG 2.1 AA. Quien la cite debe decir la edición (2011) y consultar su estado con ICONTEC.</p>
<p>Para la Clínica Aurora, el análisis jurídico es otro. La Resolución 1519 aplica a los sujetos del artículo 5 de la Ley 1712. Una clínica privada sin función pública no figura, en principio, entre ellos, pero esa conclusión depende del texto del artículo y de la naturaleza de la entidad, y la debe confirmar un asesor jurídico. Aun sin obligación legal, usar WCAG 2.2 AA como criterio interno es una decisión razonable de calidad.</p>
</section>
<section id="unión-europea" class="level3">
<h3 class="anchored" data-anchor-id="unión-europea">Unión Europea</h3>
<p>Para productos y servicios que se ofrecen en la UE hay dos instrumentos relevantes. La Directiva (UE) 2016/2102 cubre sitios web y aplicaciones móviles del sector público, y la lista de políticas del W3C indica que usa WCAG 2.1 mediante la norma europea EN 301 549. El Acta Europea de Accesibilidad (<em>European Accessibility Act</em>, Directiva (UE) 2019/882) cubre además al sector privado.</p>
<p>Sobre el Acta Europea de Accesibilidad, las fuentes consultadas indican que sus requisitos aplican desde el 28 de junio de 2025 para los productos y servicios cubiertos (por ejemplo, comercio electrónico, servicios bancarios, libros electrónicos, cajeros automáticos y expendedores de boletos), y que los Estados miembros debían adoptar las normas de transposición antes del 28 de junio de 2022.</p>
<p>La Wikipedia, que cita a la Comisión Europea, también menciona una excepción para microempresas de servicios (menos de 10 personas y facturación o balance de hasta 2 millones de euros).</p>
<p>Los portales de la Unión Europea no se pudieron abrir para esta guía, de modo que la fecha de aplicación y la excepción provienen de fuentes secundarias. Consulta el texto oficial en EUR-Lex antes de usarlas en un documento formal.</p>
<p>Una clínica colombiana que no ofrece servicios en la UE no queda cubierta. El Acta sirve aquí como ejemplo de hacia dónde va la regulación: exigencias para productos y servicios privados, y no solo para el Estado.</p>
</section>
<section id="mapa-de-marcos-de-accesibilidad" class="level3">
<h3 class="anchored" data-anchor-id="mapa-de-marcos-de-accesibilidad">Mapa de marcos de accesibilidad</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Marco</th>
<th>Qué es</th>
<th>A quién aplica</th>
<th>Estado verificado (3 de octubre de 2026)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>WCAG 2.2</td>
<td>Recomendación del W3C</td>
<td>Voluntaria, y base técnica de normas</td>
<td>Vigente, 12 de diciembre de 2024</td>
</tr>
<tr class="even">
<td>ISO/IEC 40500:2025</td>
<td>WCAG 2.2 como norma ISO</td>
<td>Voluntaria</td>
<td>Publicada, con aviso de reemplazo próximo</td>
</tr>
<tr class="odd">
<td>WCAG 3.0</td>
<td>Borrador del W3C</td>
<td>Ninguno</td>
<td><em>Working Draft</em> del 10 de septiembre de 2026</td>
</tr>
<tr class="even">
<td>Resolución MinTIC 1519 de 2020</td>
<td>Directrices de accesibilidad web de Colombia</td>
<td>Sujetos del artículo 5 de la Ley 1712 de 2014</td>
<td>Verificada en el sitio de MinTIC. Exige WCAG 2.1 AA desde 2022</td>
</tr>
<tr class="odd">
<td>NTC 5854:2011</td>
<td>Norma colombiana “Accesibilidad a páginas web”</td>
<td>Voluntaria</td>
<td>Edición 2011 en el catálogo de ICONTEC. Alcance y vigencia no verificados (de pago)</td>
</tr>
<tr class="even">
<td>Directiva (UE) 2016/2102</td>
<td>Accesibilidad de sitios y apps del sector público de la UE</td>
<td>Entes públicos de la UE</td>
<td>Usa WCAG 2.1 por EN 301 549, según W3C</td>
</tr>
<tr class="odd">
<td>European Accessibility Act</td>
<td>Accesibilidad de productos y servicios en la UE</td>
<td>Sector privado y público de la UE</td>
<td>Aplica desde el 28 de junio de 2025, según fuentes secundarias</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 7. Qué norma citar
</div>
</div>
<div class="callout-body-container callout-body">
<p>La clínica quiere declarar en su sitio qué estándar de accesibilidad sigue. Un compañero propone citar “la NTC 5854 vigente”. Otro propone “WCAG 3.0, que es la más nueva”. Un tercero propone “WCAG 2.2 nivel AA”. Evalúa cada propuesta con la evidencia de esta guía y redacta una frase que la clínica pueda publicar.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La primera propuesta es débil: la NTC 5854 que consta en el catálogo es de 2011, su alcance y su estado actual no se pudieron verificar en la fuente, y la norma que el Estado exige a sus portales (Resolución 1519) no la menciona. Si se cita, hay que decir la edición y comprobar su estado con ICONTEC.</p>
<p>La segunda es incorrecta: WCAG 3.0 es un borrador del 10 de septiembre de 2026, el W3C advierte que no se debe citar como algo distinto de un trabajo en progreso y no reemplaza a WCAG 2.</p>
<p>La tercera es la más defendible: WCAG 2.2 es Recomendación vigente, cubre a 2.1 (que es lo que exige la Resolución 1519 a las entidades públicas) y existe como ISO/IEC 40500:2025.</p>
<p>Frase posible: “Nuestra aplicación toma como referencia las Pautas de Accesibilidad para el Contenido Web (WCAG) 2.2, nivel AA. Algunos puntos están en revisión. Puedes reportar un problema de accesibilidad al correo de contacto”. Como no hay una evaluación completa, la frase no debe afirmar conformidad plena. Tu redacción puede variar mientras no declare más de lo que se verificó.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-9.-un-plan-de-evaluación-integrado" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="parte-9.-un-plan-de-evaluación-integrado"><span class="header-section-number">12</span> Parte 9. Un plan de evaluación integrado</h2>
<section id="qué-marco-usar-y-cuándo" class="level3">
<h3 class="anchored" data-anchor-id="qué-marco-usar-y-cuándo">Qué marco usar y cuándo</h3>
<p>Ningún marco resuelve todo. Cada uno responde una pregunta distinta, y un plan serio combina varios.</p>
<div class="diagrama">
<svg viewbox="0 0 760 292" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Mapa de marcos: tres columnas, normas que definen (ISO 9241-11, 9241-210, 25010, 25019), métodos que miden (heurísticas, pruebas con personas, SUS) y accesibilidad (WCAG 2.2, Resolución 1519, NTC 5854, Acta Europea), con flechas hacia un plan de evaluación del formulario" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u3t3c" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Tres familias de marcos que se combinan</text> <g fill="#f1ecf8" stroke="#b9a6d8"><rect x="20" y="34" width="220" height="150" rx="12"></rect></g> <g fill="#fff3d6" stroke="#e6c46f"><rect x="270" y="34" width="220" height="150" rx="12"></rect></g> <g fill="#e4f2f1" stroke="#8fc9c5"><rect x="520" y="34" width="220" height="150" rx="12"></rect></g> <g text-anchor="middle" font-size="13" font-weight="700"><text x="130" y="58" fill="#5b3f8c">Normas que definen</text><text x="380" y="58" fill="#855400">Métodos que miden</text><text x="630" y="58" fill="#0e6f6c">Accesibilidad</text></g> <g text-anchor="middle" font-size="11.5" fill="#12324f"><text x="130" y="86">ISO 9241-11: qué es</text><text x="130" y="106">ISO 9241-210: proceso</text><text x="130" y="126">ISO/IEC 25010: producto</text><text x="130" y="146">ISO/IEC 25019: calidad en uso</text><text x="380" y="86">Heurísticas de Nielsen</text><text x="380" y="106">Pruebas con personas</text><text x="380" y="126">Cuestionario SUS</text><text x="380" y="146">Intervalos y muestra</text><text x="630" y="86">WCAG 2.2 y ISO/IEC 40500</text><text x="630" y="106">Resolución 1519 de 2020</text><text x="630" y="126">NTC 5854</text><text x="630" y="146">European Accessibility Act</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u3t3c)"><path d="M130,186 C130,206 330,206 360,226"></path><path d="M380,186 L380,224"></path><path d="M630,186 C630,206 430,206 400,226"></path></g> <rect x="210" y="228" width="340" height="50" rx="12" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="380" y="250" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Plan de evaluación del formulario</text> <text x="380" y="267" font-size="11" fill="#5b6876" text-anchor="middle">una pregunta, un método y una evidencia por marco</text>
</svg>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Pregunta</th>
<th>Marco o método</th>
<th>Cuándo</th>
<th>Evidencia que produce</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>¿Qué significa que el formulario sea usable aquí?</td>
<td>ISO 9241-11</td>
<td>Antes de diseñar</td>
<td>Contexto de uso y metas medibles</td>
</tr>
<tr class="even">
<td>¿Cómo organizamos el trabajo?</td>
<td>ISO 9241-210</td>
<td>Todo el proyecto</td>
<td>Ciclo de cuatro actividades</td>
</tr>
<tr class="odd">
<td>¿Qué propiedades debe tener el producto?</td>
<td>ISO/IEC 25010:2023</td>
<td>Requisitos</td>
<td>Requisitos de capacidad de interacción</td>
</tr>
<tr class="even">
<td>¿Dónde fallará según expertos?</td>
<td>Heurísticas de Nielsen</td>
<td>Prototipo</td>
<td>Hallazgos con severidad</td>
</tr>
<tr class="odd">
<td>¿Qué hacen personas reales?</td>
<td>Prueba de usabilidad</td>
<td>Cada iteración</td>
<td>Tareas, tiempos, observaciones</td>
</tr>
<tr class="even">
<td>¿Qué tan satisfechas quedan?</td>
<td>SUS</td>
<td>Tras las tareas</td>
<td>Puntuación con intervalo</td>
</tr>
<tr class="odd">
<td>¿Es accesible técnicamente?</td>
<td>WCAG 2.2 AA</td>
<td>Antes de lanzar y en cada cambio</td>
<td>Tabla de criterios cumplidos</td>
</tr>
<tr class="even">
<td>¿Qué efecto tiene el uso en la persona?</td>
<td>ISO/IEC 25019:2023</td>
<td>Tras el lanzamiento</td>
<td>Indicadores de calidad en uso</td>
</tr>
</tbody>
</table>
</section>
<section id="ejemplo-resuelto-plan-de-una-iteración-para-el-formulario" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-plan-de-una-iteración-para-el-formulario">Ejemplo resuelto: plan de una iteración para el formulario</h3>
<p>El equipo dispone de tres semanas. Este es el plan.</p>
<ol type="1">
<li>Semana 1. Se escribe el contexto de uso y las metas (Parte 1) y tres evaluadores hacen la inspección heurística (Parte 4). Se corrigen los hallazgos de severidad 3 y 4.</li>
<li>Semana 1, en paralelo. Una persona revisa los diez criterios de WCAG 2.2 y se corrigen los que bloquean (teclado, errores, reflujo, contraste).</li>
<li>Semana 2. Se prueba la versión corregida con 5 adultos mayores y se aplica el SUS. Se reportan intervalos, no solo medias.</li>
<li>Semana 3. Se corrige lo hallado y se prueba con otros 5. Si además hay pacientes con baja visión que usan lector de pantalla, se agregan 3 a 4 personas de ese grupo.</li>
<li>Decisión. La versión sale si se cumplen las metas de la Parte 1 con la evidencia disponible, y se declara lo que no se pudo confirmar.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Una advertencia sobre el orden
</div>
</div>
<div class="callout-body-container callout-body">
<p>La inspección va antes de la prueba para no gastar el tiempo de los participantes en problemas que un experto detecta en una hora. La prueba va antes del SUS dentro de cada sesión, porque el SUS mide la percepción tras usar el producto.</p>
</div>
</div>
</section>
</section>
<section id="errores-frecuentes" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="errores-frecuentes"><span class="header-section-number">13</span> Errores frecuentes</h2>
<ul>
<li>Confundir usabilidad con diseño visual, o con facilidad de aprendizaje a secas.</li>
<li>Evaluar sin escribir antes el contexto de uso ni las metas medibles.</li>
<li>Probar con compañeros del equipo y no con personas del contexto de uso.</li>
<li>Citar la regla de las cinco personas como ley, sin los límites de la Parte 5.</li>
<li>Presentar un porcentaje de cinco personas sin su intervalo.</li>
<li>Tratar el 68 del SUS como un umbral oficial.</li>
<li>Citar WCAG 3.0 como requisito, o la NTC 5854 sin decir la edición ni verificar su estado.</li>
<li>Creer que cumplir WCAG garantiza usabilidad, o que una herramienta automática basta para declarar conformidad.</li>
<li>Evaluar una sola vez al final, en lugar de iterar.</li>
</ul>
</section>
<section id="autoevaluación" class="level2" data-number="14">
<h2 data-number="14" class="anchored" data-anchor-id="autoevaluación"><span class="header-section-number">14</span> Autoevaluación</h2>
<p>Marca tu respuesta y compárala con la clave. Cada clave explica la respuesta.</p>
<p><strong>1.</strong> Según la ISO 9241-11:2018, ¿cuáles son las tres medidas de la usabilidad?</p>
<p><label><input type="checkbox"> Rapidez, belleza y bajo costo</label><br> <label><input type="checkbox"> Efectividad, eficiencia y satisfacción</label><br> <label><input type="checkbox"> Seguridad, desempeño y mantenibilidad</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. La norma las define para usuarios específicos, metas específicas y un contexto de uso específico.</p>
</div>
</div>
</div>
<p><strong>2.</strong> El contexto de uso de la ISO 9241-11 está formado por:</p>
<p><label><input type="checkbox"> Usuarios, metas y tareas, recursos y entorno</label><br> <label><input type="checkbox"> Requisitos, diseño, código y pruebas</label><br> <label><input type="checkbox"> Cliente, proveedor, contrato y precio</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Cambiar cualquiera de los cuatro cambia la usabilidad, aunque la pantalla sea la misma.</p>
</div>
</div>
</div>
<p><strong>3.</strong> La ISO 9241-210:2019 se ocupa de:</p>
<p><label><input type="checkbox"> Definir cómo se calcula el SUS</label><br> <label><input type="checkbox"> Los principios y las actividades del diseño centrado en las personas, en ciclo iterativo</label><br> <label><input type="checkbox"> Los criterios de accesibilidad de las páginas web</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Sus cuatro actividades son contexto de uso, requisitos, diseño y evaluación, y se repiten hasta que el diseño cumple.</p>
</div>
</div>
</div>
<p><strong>4.</strong> En la ISO/IEC 25010:2023, la característica que antes se llamaba usabilidad se llama:</p>
<p><label><input type="checkbox"> Flexibilidad</label><br> <label><input type="checkbox"> Seguridad frente a daños</label><br> <label><input type="checkbox"> Capacidad de interacción</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 3. El modelo de calidad en uso salió de la ISO/IEC 25010 y quedó en la ISO/IEC 25019:2023.</p>
</div>
</div>
</div>
<p><strong>5.</strong> Una evaluación heurística de Nielsen:</p>
<p><label><input type="checkbox"> Requiere cientos de usuarios</label><br> <label><input type="checkbox"> Es un método de inspección en el que expertos juzgan la interfaz contra principios, sin necesidad de usuarios</label><br> <label><input type="checkbox"> Mide la satisfacción con un cuestionario de diez ítems</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Se recomienda que tres a cinco personas evalúen de forma independiente.</p>
</div>
</div>
</div>
<p><strong>6.</strong> Con L = 0,31, cinco personas en una prueba descubren aproximadamente:</p>
<p><label><input type="checkbox"> 31 % de los problemas</label><br> <label><input type="checkbox"> 100 % de los problemas</label><br> <label><input type="checkbox"> 84 % de los problemas, como promedio y con variación entre grupos reales</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 3. Es 1 - 0,69 elevado a 5, igual a 84,4 %. Faulkner (2003) halló conjuntos de cinco personas que encontraron entre 55 % y 99 %.</p>
</div>
</div>
</div>
<p><strong>7.</strong> Un participante responde un SUS así: 5, 1, 4, 2, 5, 1, 5, 1, 4, 1. Su puntuación es:</p>
<p><label><input type="checkbox"> 92,5</label><br> <label><input type="checkbox"> 37</label><br> <label><input type="checkbox"> 74</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. La suma de contribuciones es 37 y 37 x 2,5 = 92,5. La opción 2 olvida el multiplicador.</p>
</div>
</div>
</div>
<p><strong>8.</strong> La referencia de 68 para el SUS es:</p>
<p><label><input type="checkbox"> Un umbral obligatorio de la ISO 9241-11</label><br> <label><input type="checkbox"> El promedio de la base de datos de MeasuringU, una referencia útil pero no un umbral normativo</label><br> <label><input type="checkbox"> El puntaje mínimo que fija Brooke para aprobar</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Ni la ISO 9241-11 ni Brooke fijan umbral alguno. Es el percentil 50 de una base de datos acumulada.</p>
</div>
</div>
</div>
<p><strong>9.</strong> WCAG 3.0, en octubre de 2026, es:</p>
<p><label><input type="checkbox"> Una Recomendación del W3C que reemplazó a WCAG 2.2</label><br> <label><input type="checkbox"> Una norma ISO obligatoria en la Unión Europea</label><br> <label><input type="checkbox"> Un borrador de trabajo (Working Draft) que no reemplaza a WCAG 2</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 3. El borrador consultado es del 10 de septiembre de 2026, y el documento dice que no debe citarse como algo distinto de un trabajo en progreso.</p>
</div>
</div>
</div>
<p><strong>10.</strong> La Resolución 1519 de 2020 de MinTIC exige a los sujetos obligados, desde el 1 de enero de 2022:</p>
<p><label><input type="checkbox"> WCAG 2.2 nivel AAA</label><br> <label><input type="checkbox"> WCAG 2.1 nivel AA</label><br> <label><input type="checkbox"> La NTC 5854 nivel A</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 10
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2, según el artículo 3 y el Anexo 1. La resolución no menciona la NTC 5854 y deroga la Resolución 3564 de 2015.</p>
</div>
</div>
</div>
</section>
<section id="lo-que-te-llevas" class="level2" data-number="15">
<h2 data-number="15" class="anchored" data-anchor-id="lo-que-te-llevas"><span class="header-section-number">15</span> Lo que te llevas</h2>
<div class="checklist">
<p><strong>Al salir de este tema deberías poder explicar, sin mirar la guía</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">La definición de usabilidad de la ISO 9241-11 y sus tres medidas y el contexto de uso</label></li>
<li><label><input type="checkbox">Los seis principios y las cuatro actividades de la ISO 9241-210</label></li>
<li><label><input type="checkbox">Qué es la capacidad de interacción en la ISO/IEC 25010:2023 y qué es la calidad en uso de la ISO/IEC 25019:2023</label></li>
<li><label><input type="checkbox">Las diez heurísticas de Nielsen y cómo se prioriza con la escala de severidad</label></li>
<li><label><input type="checkbox">Cómo se planea una prueba de usabilidad, qué calcula y qué límites tiene una muestra de cinco personas</label></li>
<li><label><input type="checkbox">Cómo se calcula el SUS y por qué 68 es una referencia y no un umbral</label></li>
<li><label><input type="checkbox">Qué piden varios criterios de WCAG 2.2 y cómo se calcula un contraste</label></li>
<li><label><input type="checkbox">Qué estado tienen WCAG 3.0, ISO/IEC 40500, la Resolución 1519, la NTC 5854 y el European Accessibility Act</label></li>
</ul>
</div>
</section>
<section id="glosario" class="level2" data-number="16">
<h2 data-number="16" class="anchored" data-anchor-id="glosario"><span class="header-section-number">16</span> Glosario</h2>
<ul>
<li><strong>Usabilidad.</strong> Grado en que usuarios específicos pueden usar un sistema, producto o servicio para lograr metas específicas con efectividad, eficiencia y satisfacción en un contexto de uso específico (ISO 9241-11:2018).</li>
<li><strong>Efectividad.</strong> Exactitud y completitud con que las personas logran sus metas.</li>
<li><strong>Eficiencia.</strong> Recursos gastados en relación con los resultados logrados.</li>
<li><strong>Satisfacción.</strong> Respuestas de la persona (físicas, cognitivas y emocionales) frente al uso del producto.</li>
<li><strong>Contexto de uso.</strong> Combinación de usuarios, metas y tareas, recursos y entorno en que se usa un producto.</li>
<li><strong>Diseño centrado en las personas.</strong> Enfoque de desarrollo que busca sistemas usables y útiles centrándose en las personas usuarias y sus necesidades (ISO 9241-210).</li>
<li><strong>Capacidad de interacción.</strong> Característica de la ISO/IEC 25010:2023 que antes se llamaba usabilidad, con ocho subcaracterísticas.</li>
<li><strong>Calidad en uso.</strong> Efecto del uso de un producto en quienes lo usan, en un contexto específico (ISO/IEC 25019:2023).</li>
<li><strong>Evaluación heurística.</strong> Método de inspección en que evaluadores juzgan una interfaz contra principios de usabilidad.</li>
<li><strong>Heurística.</strong> Principio general de diseño usado como criterio de evaluación, como las diez de Nielsen.</li>
<li><strong>Severidad.</strong> Gravedad de un problema de usabilidad, combinación de frecuencia, impacto y persistencia, en una escala de 0 a 4.</li>
<li><strong>Prueba de usabilidad.</strong> Observación de personas representativas realizando tareas reales con el producto.</li>
<li><strong>Completada sin ayuda.</strong> Resultado de una tarea en que la persona llegó a la meta sin intervención del facilitador.</li>
<li><strong>Intervalo de Agresti y Coull (Wald ajustado).</strong> Intervalo de confianza para una proporción, recomendado para muestras pequeñas.</li>
<li><strong>L.</strong> En el modelo de Nielsen y Landauer, proporción de problemas que descubre una sola persona.</li>
<li><strong>SUS.</strong> <em>System Usability Scale</em>, cuestionario de diez ítems con puntuación de 0 a 100.</li>
<li><strong>Percentil 50.</strong> Valor que supera a la mitad de las observaciones de una base de datos, que en el SUS de MeasuringU es 68.</li>
<li><strong>WCAG.</strong> <em>Web Content Accessibility Guidelines</em>, pautas de accesibilidad del W3C.</li>
<li><strong>Criterio de éxito.</strong> Requisito comprobable de WCAG, con nivel A, AA o AAA.</li>
<li><strong>Relación de contraste.</strong> Cociente (L1 + 0,05) / (L2 + 0,05) entre las luminancias del color más claro y el más oscuro.</li>
<li><strong>ISO/IEC 40500.</strong> Norma que publica WCAG como norma ISO; la edición 2025 corresponde a WCAG 2.2.</li>
<li><strong>NTC 5854.</strong> Norma técnica colombiana de ICONTEC sobre accesibilidad a páginas web, edición 2011 en el catálogo consultado.</li>
<li><strong>Resolución 1519 de 2020.</strong> Resolución de MinTIC con directrices de accesibilidad web para los sujetos obligados.</li>
<li><strong>European Accessibility Act.</strong> Directiva (UE) 2019/882 sobre requisitos de accesibilidad de productos y servicios.</li>
<li><strong>EN 301 549.</strong> Norma europea de requisitos de accesibilidad para productos y servicios TIC.</li>
</ul>
</section>
<section id="bibliografía" class="level2" data-number="17">
<h2 data-number="17" class="anchored" data-anchor-id="bibliografía"><span class="header-section-number">17</span> Bibliografía</h2>
<p>Normas y fichas oficiales (consultadas el 3 de octubre de 2026):</p>
<ul>
<li>ISO 9241-11:2018. <em>Ergonomics of human-system interaction, Part 11: Usability: Definitions and concepts.</em> Edición 2, marzo de 2018, revisada y confirmada en 2023. <a href="https://www.iso.org/standard/63500.html">Ficha</a>.</li>
<li>ISO 9241-210:2019. <em>Ergonomics of human-system interaction, Part 210: Human-centred design for interactive systems.</em> Edición 2, julio de 2019, revisada y confirmada en 2025. <a href="https://www.iso.org/standard/77520.html">Ficha</a>.</li>
<li>ISO/IEC 25010:2023. <em>Systems and software engineering, SQuaRE, Product quality model.</em> Edición 2, noviembre de 2023. <a href="https://www.iso.org/standard/78176.html">Ficha</a>.</li>
<li>ISO/IEC 25019:2023. <em>Systems and software engineering, SQuaRE, Quality-in-use model.</em> Edición 1, noviembre de 2023. <a href="https://www.iso.org/standard/78177.html">Ficha</a>.</li>
<li>ISO/IEC 40500:2025. <em>Information technology, W3C Web Content Accessibility Guidelines (WCAG) 2.2.</em> Edición 2, septiembre de 2025. <a href="https://www.iso.org/standard/91029.html">Ficha</a>.</li>
<li>ICONTEC. NTC 5854:2011, <em>Accesibilidad a páginas web.</em> <a href="https://tienda.icontec.org/tienda-icontec/buscar/?q=5854">Tienda de ICONTEC</a>.</li>
</ul>
<p>Accesibilidad:</p>
<ul>
<li>W3C (2024). <em>Web Content Accessibility Guidelines (WCAG) 2.2.</em> Recomendación del W3C, 12 de diciembre de 2024. <a href="https://www.w3.org/TR/WCAG22/">Especificación</a>.</li>
<li>W3C. <em>What’s New in WCAG 2.2.</em> <a href="https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/">Página</a>.</li>
<li>W3C (2026). <em>W3C Accessibility Guidelines (WCAG) 3.0.</em> Working Draft, 10 de septiembre de 2026. <a href="https://www.w3.org/TR/wcag-3.0/">Borrador</a>.</li>
<li>W3C WAI. <em>Web Accessibility Laws and Policies: Colombia</em> y <em>European Union.</em> <a href="https://www.w3.org/WAI/policies/colombia/">Colombia</a>, <a href="https://www.w3.org/WAI/policies/european-union/">Unión Europea</a>.</li>
<li>MinTIC (2020). <em>Resolución 1519 del 24 de agosto de 2020</em>, con su Anexo 1, <em>Directrices de accesibilidad web.</em> <a href="https://gobiernodigital.mintic.gov.co/692/articles-178657_resolucion_1519_2020.pdf">Resolución</a>, <a href="https://gobiernodigital.mintic.gov.co/692/articles-160770_Directrices_Accesibilidad_web.pdf">Anexo 1</a>.</li>
<li>Congreso de Colombia (2013). <em>Ley Estatutaria 1618 de 2013.</em> Y (2014). <em>Ley 1712 de 2014</em>, de transparencia y acceso a la información pública. Se citan según los considerandos de la Resolución 1519.</li>
<li>Parlamento Europeo y Consejo (2019). <em>Directiva (UE) 2019/882 sobre los requisitos de accesibilidad de los productos y servicios.</em> <a href="https://eur-lex.europa.eu/eli/dir/2019/882/oj/eng">EUR-Lex</a>. La fecha de aplicación y la excepción para microempresas se tomaron de fuentes secundarias, como <a href="https://en.wikipedia.org/wiki/European_Accessibility_Act">Wikipedia, European Accessibility Act</a>, que cita a la Comisión Europea.</li>
<li>Parlamento Europeo y Consejo (2016). <em>Directiva (UE) 2016/2102 sobre la accesibilidad de los sitios web y aplicaciones móviles de los organismos del sector público.</em></li>
</ul>
<p>Heurísticas, pruebas y muestra:</p>
<ul>
<li>Nielsen, J. (1994). <em>10 Usability Heuristics for User Interface Design.</em> Texto actualizado el 30 de enero de 2024. <a href="https://www.nngroup.com/articles/ten-usability-heuristics/">Nielsen Norman Group</a>.</li>
<li>Nielsen, J. (1994). <em>Severity Ratings for Usability Problems.</em> <a href="https://www.nngroup.com/articles/how-to-rate-the-severity-of-usability-problems/">Nielsen Norman Group</a>.</li>
<li>Moran, K. y Gordon, K. (2023). <em>How to Conduct a Heuristic Evaluation.</em> <a href="https://www.nngroup.com/articles/how-to-conduct-a-heuristic-evaluation/">Nielsen Norman Group</a>.</li>
<li>Nielsen, J. y Landauer, T. K. (1993). A mathematical model of the finding of usability problems. <em>Proceedings of ACM INTERCHI’93</em>, 206 a 213.</li>
<li>Nielsen, J. (2000). <em>Why You Only Need to Test with 5 Users.</em> <a href="https://www.nngroup.com/articles/why-you-only-need-to-test-with-5-users/">Nielsen Norman Group</a>.</li>
<li>Nielsen, J. (2012). <em>How Many Test Users in a Usability Study?</em> <a href="https://www.nngroup.com/articles/how-many-test-users/">Nielsen Norman Group</a>.</li>
<li>Faulkner, L. (2003). Beyond the five-user assumption: Benefits of increased sample sizes in usability testing. <em>Behavior Research Methods, Instruments, &amp; Computers</em>, 35, 379 a 383. <a href="https://link.springer.com/article/10.3758/BF03195514">Ficha</a>.</li>
<li>Agresti, A. y Coull, B. A. (1998). Approximate is better than “exact” for interval estimation of binomial proportions. <em>The American Statistician</em>, 52(2), 119 a 126.</li>
</ul>
<p>Cuestionario SUS:</p>
<ul>
<li>Brooke, J. (1996). SUS: A quick and dirty usability scale. En P. W. Jordan et al.&nbsp;(Eds.), <em>Usability Evaluation in Industry.</em> Taylor &amp; Francis. <a href="https://hell.meiert.org/core/pdf/sus.pdf">Texto</a>.</li>
<li>Sauro, J. <em>5 Ways to Interpret a SUS Score.</em> MeasuringU. <a href="https://measuringu.com/interpret-sus-score/">Artículo</a>.</li>
<li>Bangor, A., Kortum, P. T. y Miller, J. T. (2008). An empirical evaluation of the System Usability Scale. <em>International Journal of Human-Computer Interaction</em>, 24(6). Citado según MeasuringU.</li>
</ul>
<p>Cómo se usó cada fuente: las normas ISO, solo en su ficha pública. Agresti y Coull (1998) y Bangor et al.&nbsp;(2008) no se abrieron en esta consulta: la primera aporta la fórmula estándar del intervalo y la segunda se cita según MeasuringU.</p>
<div class="pie-doc">
<p>Calidad del software (CDS01). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>