<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 2. Calidad de proceso y de producto: el modelo ISO/IEC 25010:2023 – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-95bfa606010d176c52cfb6b551730f65.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-01/index.html">Unidad 1. Calidad del software y estándares de calidad</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html">Tema 2. Calidad de proceso y de producto: ISO/IEC 25010:2023</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Calidad del software y estándares de calidad</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-01-que-es-calidad-quien-la-define/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es la calidad y quién la define</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 2. Calidad de proceso y de producto: ISO/IEC 25010:2023</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Importancia, costo y calidad en un mundo globalizado</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Procesos de calidad del software. Modelos y métricas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-01-sqa-relacion-ingenieria/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es el SQA y su relación con la ingeniería de software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La calidad en cada fase del ciclo de vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-03-roles-habilidades/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Roles, responsabilidades y habilidades del personal de SQA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-04-actividades-sqa/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Actividades del SQA: revisiones, auditorías y gestión de configuración</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-05-modelos-metricas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Modelos y métricas de calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-06-herramientas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 6. Herramientas de SQA en la industria</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 3. Estándares de calidad aplicados al software</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Estándares IEEE para la calidad del software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Marcos para evaluar la usabilidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Madurez de procesos: SPICE y CMMI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 4. Validación y verificación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Métodos, metodologías y estándares de verificación y validación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Validación y verificación de requisitos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-03-control-costo-calidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Control de la calidad y costo de la calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Nomenclatura y certificación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-05-factores-atam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Factores que determinan la calidad y el método ATAM</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#objetivo-y-resultado-de-aprendizaje" id="toc-objetivo-y-resultado-de-aprendizaje" class="nav-link active" data-scroll-target="#objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</a></li>
  <li><a href="#cómo-se-recorre-este-tema" id="toc-cómo-se-recorre-este-tema" class="nav-link" data-scroll-target="#cómo-se-recorre-este-tema"><span class="header-section-number">2</span> Cómo se recorre este tema</a></li>
  <li><a href="#el-producto-que-usamos-en-los-ejemplos" id="toc-el-producto-que-usamos-en-los-ejemplos" class="nav-link" data-scroll-target="#el-producto-que-usamos-en-los-ejemplos"><span class="header-section-number">3</span> El producto que usamos en los ejemplos</a></li>
  <li><a href="#parte-1.-calidad-de-proceso-y-calidad-de-producto" id="toc-parte-1.-calidad-de-proceso-y-calidad-de-producto" class="nav-link" data-scroll-target="#parte-1.-calidad-de-proceso-y-calidad-de-producto"><span class="header-section-number">4</span> Parte 1. Calidad de proceso y calidad de producto</a>
  <ul class="collapse">
  <li><a href="#quién-evalúa-cada-una" id="toc-quién-evalúa-cada-una" class="nav-link" data-scroll-target="#quién-evalúa-cada-una">Quién evalúa cada una</a></li>
  </ul></li>
  <li><a href="#parte-2.-el-modelo-de-la-isoiec-250102023" id="toc-parte-2.-el-modelo-de-la-isoiec-250102023" class="nav-link" data-scroll-target="#parte-2.-el-modelo-de-la-isoiec-250102023"><span class="header-section-number">5</span> Parte 2. El modelo de la ISO/IEC 25010:2023</a>
  <ul class="collapse">
  <li><a href="#cómo-está-organizada" id="toc-cómo-está-organizada" class="nav-link" data-scroll-target="#cómo-está-organizada">2.1 Cómo está organizada</a></li>
  <li><a href="#qué-cambió-desde-2011" id="toc-qué-cambió-desde-2011" class="nav-link" data-scroll-target="#qué-cambió-desde-2011">2.2 Qué cambió desde 2011</a></li>
  <li><a href="#las-nueve-características" id="toc-las-nueve-características" class="nav-link" data-scroll-target="#las-nueve-características">2.3 Las nueve características</a></li>
  <li><a href="#square-como-mapa" id="toc-square-como-mapa" class="nav-link" data-scroll-target="#square-como-mapa">2.4 SQuaRE como mapa</a></li>
  <li><a href="#isoiec-25059-calidad-de-sistemas-con-inteligencia-artificial" id="toc-isoiec-25059-calidad-de-sistemas-con-inteligencia-artificial" class="nav-link" data-scroll-target="#isoiec-25059-calidad-de-sistemas-con-inteligencia-artificial">2.5 ISO/IEC 25059: calidad de sistemas con inteligencia artificial</a></li>
  </ul></li>
  <li><a href="#parte-3.-calidad-en-uso" id="toc-parte-3.-calidad-en-uso" class="nav-link" data-scroll-target="#parte-3.-calidad-en-uso"><span class="header-section-number">6</span> Parte 3. Calidad en uso</a>
  <ul class="collapse">
  <li><a href="#un-ejemplo-resuelto" id="toc-un-ejemplo-resuelto" class="nav-link" data-scroll-target="#un-ejemplo-resuelto">Un ejemplo resuelto</a></li>
  </ul></li>
  <li><a href="#parte-4.-requisitos-de-calidad-medibles" id="toc-parte-4.-requisitos-de-calidad-medibles" class="nav-link" data-scroll-target="#parte-4.-requisitos-de-calidad-medibles"><span class="header-section-number">7</span> Parte 4. Requisitos de calidad medibles</a>
  <ul class="collapse">
  <li><a href="#por-qué-debe-ser-rápido-no-sirve" id="toc-por-qué-debe-ser-rápido-no-sirve" class="nav-link" data-scroll-target="#por-qué-debe-ser-rápido-no-sirve">4.1 Por qué “debe ser rápido” no sirve</a></li>
  <li><a href="#las-cinco-piezas" id="toc-las-cinco-piezas" class="nav-link" data-scroll-target="#las-cinco-piezas">4.2 Las cinco piezas</a></li>
  <li><a href="#ejemplo-resuelto-1-desempeño" id="toc-ejemplo-resuelto-1-desempeño" class="nav-link" data-scroll-target="#ejemplo-resuelto-1-desempeño">4.3 Ejemplo resuelto 1: desempeño</a></li>
  <li><a href="#ejemplo-resuelto-2-capacidad-de-interacción" id="toc-ejemplo-resuelto-2-capacidad-de-interacción" class="nav-link" data-scroll-target="#ejemplo-resuelto-2-capacidad-de-interacción">4.4 Ejemplo resuelto 2: capacidad de interacción</a></li>
  <li><a href="#ejemplo-resuelto-3-fiabilidad" id="toc-ejemplo-resuelto-3-fiabilidad" class="nav-link" data-scroll-target="#ejemplo-resuelto-3-fiabilidad">4.5 Ejemplo resuelto 3: fiabilidad</a></li>
  <li><a href="#medir-bien-promedio-contra-percentil-95" id="toc-medir-bien-promedio-contra-percentil-95" class="nav-link" data-scroll-target="#medir-bien-promedio-contra-percentil-95">4.6 Medir bien: promedio contra percentil 95</a></li>
  <li><a href="#ejemplos-resueltos-para-las-nueve-características" id="toc-ejemplos-resueltos-para-las-nueve-características" class="nav-link" data-scroll-target="#ejemplos-resueltos-para-las-nueve-características">4.7 Ejemplos resueltos para las nueve características</a></li>
  <li><a href="#los-requisitos-chocan-entre-sí" id="toc-los-requisitos-chocan-entre-sí" class="nav-link" data-scroll-target="#los-requisitos-chocan-entre-sí">4.8 Los requisitos chocan entre sí</a></li>
  </ul></li>
  <li><a href="#parte-5.-caso-real-ariane-5-vuelo-501" id="toc-parte-5.-caso-real-ariane-5-vuelo-501" class="nav-link" data-scroll-target="#parte-5.-caso-real-ariane-5-vuelo-501"><span class="header-section-number">8</span> Parte 5. Caso real: Ariane 5, vuelo 501</a>
  <ul class="collapse">
  <li><a href="#qué-pasó" id="toc-qué-pasó" class="nav-link" data-scroll-target="#qué-pasó">5.1 Qué pasó</a></li>
  <li><a href="#la-cadena-de-causas" id="toc-la-cadena-de-causas" class="nav-link" data-scroll-target="#la-cadena-de-causas">5.2 La cadena de causas</a></li>
  <li><a href="#análisis-con-el-modelo-de-la-isoiec-250102023" id="toc-análisis-con-el-modelo-de-la-isoiec-250102023" class="nav-link" data-scroll-target="#análisis-con-el-modelo-de-la-isoiec-250102023">5.3 Análisis con el modelo de la ISO/IEC 25010:2023</a></li>
  <li><a href="#lo-que-el-caso-enseña" id="toc-lo-que-el-caso-enseña" class="nav-link" data-scroll-target="#lo-que-el-caso-enseña">5.4 Lo que el caso enseña</a></li>
  </ul></li>
  <li><a href="#cierre" id="toc-cierre" class="nav-link" data-scroll-target="#cierre"><span class="header-section-number">9</span> Cierre</a>
  <ul class="collapse">
  <li><a href="#lo-que-te-llevas" id="toc-lo-que-te-llevas" class="nav-link" data-scroll-target="#lo-que-te-llevas">Lo que te llevas</a></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes">Errores frecuentes</a></li>
  <li><a href="#autoevaluación" id="toc-autoevaluación" class="nav-link" data-scroll-target="#autoevaluación">Autoevaluación</a></li>
  <li><a href="#glosario-del-tema" id="toc-glosario-del-tema" class="nav-link" data-scroll-target="#glosario-del-tema">Glosario del tema</a></li>
  </ul></li>
  <li><a href="#lo-que-sigue" id="toc-lo-que-sigue" class="nav-link" data-scroll-target="#lo-que-sigue"><span class="header-section-number">10</span> Lo que sigue</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">11</span> Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-01/index.html">Unidad 1. Calidad del software y estándares de calidad</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html">Tema 2. Calidad de proceso y de producto: ISO/IEC 25010:2023</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 2. Calidad de proceso y de producto: el modelo ISO/IEC 25010:2023</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">3 de octubre de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 87%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 1. Calidad del software y estándares de calidad</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 2. Calidad de proceso y de producto: el modelo ISO/IEC 25010:2023</td>
</tr>
</tbody>
</table>
</div>
<p><a href="presentacion-interactiva.html" class="btn-curso">Presentación interactiva</a></p>
<p>Tema anterior: <a href="../../../calidad-del-software/unidad-01/tema-01-que-es-calidad-quien-la-define/index.html">Tema 1. Qué es la calidad y quién la define</a>. Tema siguiente: <a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html">Tema 3. Importancia de la calidad y mundo globalizado</a>.</p>
<section id="objetivo-y-resultado-de-aprendizaje" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</h2>
<p>El Tema 1 te dejó una idea que este tema vuelve operativa: la calidad se juzga contra requisitos que alguien escribió y que otra persona puede comprobar. Aquí aprendes de qué cosas se compone esa calidad en un producto de software, cómo se distingue de la calidad con la que trabaja un equipo y cómo se escribe un requisito de calidad que se pueda medir.</p>
<p>Resultado de aprendizaje de la unidad: identifica los diferentes elementos de la calidad del software. Al terminar este tema puedes:</p>
<ul>
<li>Distinguir calidad de proceso, calidad de producto y calidad en uso, y explicar cómo se relacionan.</li>
<li>Nombrar las nueve características del modelo de la ISO/IEC 25010:2023 con sus subcaracterísticas.</li>
<li>Decir qué cambió respecto a la edición de 2011, que tenía ocho características.</li>
<li>Convertir una queja como “la app es lenta” en un requisito medible con cinco piezas.</li>
<li>Analizar un caso real, el vuelo 501 del Ariane 5, con el vocabulario del modelo.</li>
</ul>
</section>
<section id="cómo-se-recorre-este-tema" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="cómo-se-recorre-este-tema"><span class="header-section-number">2</span> Cómo se recorre este tema</h2>
<p>Estudias solo, así que esta guía trae todo lo necesario: explicación, ejemplos resueltos, ejercicios con solución, autoevaluación con clave y glosario. La presentación interactiva cubre las mismas partes, en el mismo orden y con los mismos nombres, y sirve para ver animaciones y practicar.</p>
<div class="calendario">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parte</th>
<th>Qué haces</th>
<th>Tiempo sugerido</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Proceso y producto</td>
<td>Lees, haces el Reto 1 y el Reto 2</td>
<td>35 min</td>
</tr>
<tr class="even">
<td>2. El modelo de la ISO/IEC 25010:2023</td>
<td>Lees las nueve características y haces el Reto 3</td>
<td>90 min</td>
</tr>
<tr class="odd">
<td>3. Calidad en uso</td>
<td>Lees y revisas un ejemplo resuelto</td>
<td>25 min</td>
</tr>
<tr class="even">
<td>4. Requisitos de calidad medibles</td>
<td>Sigues tres ejemplos resueltos y haces el Reto 4</td>
<td>90 min</td>
</tr>
<tr class="odd">
<td>5. Caso real: Ariane 5</td>
<td>Lees el informe resumido y haces el Reto 5</td>
<td>40 min</td>
</tr>
<tr class="even">
<td>Presentación interactiva</td>
<td>Recorres las diapositivas y practicas</td>
<td>60 min</td>
</tr>
<tr class="odd">
<td>Cierre</td>
<td>Autoevaluación, glosario, errores frecuentes</td>
<td>30 min</td>
</tr>
</tbody>
</table>
</div>
<p>En total son unas seis horas. Si vas justo de tiempo, lee las partes 1, 2 y 4 completas y deja la 5 para después, pero no te saltes la autoevaluación.</p>
</section>
<section id="el-producto-que-usamos-en-los-ejemplos" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="el-producto-que-usamos-en-los-ejemplos"><span class="header-section-number">3</span> El producto que usamos en los ejemplos</h2>
<p>Todos los ejemplos usan un mismo producto ficticio, la app de turnos de la Clínica Aurora. Los pacientes piden, reprograman y cancelan turnos desde el teléfono, y el personal de la clínica ve la agenda del día. El requisito más corto de la app lo conoces del Tema 1.</p>
<blockquote class="blockquote">
<p>RF-01. La app asigna hasta 20 turnos por día a cada especialidad.</p>
</blockquote>
<p>Cuando el ejemplo pide un número, como un tiempo o un porcentaje, el número es inventado para poder razonar. En un proyecto real lo fija el negocio con datos. Lo que sí es real es la estructura del razonamiento.</p>
</section>
<section id="parte-1.-calidad-de-proceso-y-calidad-de-producto" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="parte-1.-calidad-de-proceso-y-calidad-de-producto"><span class="header-section-number">4</span> Parte 1. Calidad de proceso y calidad de producto</h2>
<p>Cuando alguien dice que una empresa tiene calidad, puede estar hablando de tres cosas distintas, y cada una se evalúa con un instrumento diferente.</p>
<p>La <em>calidad de proceso</em> es el grado en que las actividades con las que se construye el software están definidas, se siguen y se mejoran. Se ve en cómo trabaja el equipo. En la clínica sería que cada cambio de código lo revise otra persona y que el acta de la revisión se conserve.</p>
<p>La <em>calidad de producto</em> es el grado en que el software ya construido cumple sus requisitos. Se ve en el sistema. En la clínica sería que la lista de turnos cargue en 1,8 segundos.</p>
<p>La <em>calidad en uso</em> es el resultado que obtiene una persona real al usar el producto en un contexto concreto. Se ve en la experiencia. En la clínica sería que una paciente de 70 años saque su turno sin pedir ayuda. La norma que la define es la ISO/IEC 25019:2023, que veremos en la Parte 3.</p>
<div class="diagrama">
<svg viewbox="0 0 760 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Tres cajas encadenadas: calidad de proceso, calidad de producto y calidad en uso, unidas por flechas que dicen hace mas probable" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="c2a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#56615A"></path></marker></defs> <rect x="14" y="40" width="208" height="170" rx="12" fill="#FDF0D0" stroke="#F2B33D" stroke-width="1.5"></rect> <rect x="276" y="40" width="208" height="170" rx="12" fill="#E3EFFA" stroke="#3B82C4" stroke-width="1.5"></rect> <rect x="538" y="40" width="208" height="170" rx="12" fill="#E1F2E8" stroke="#2F8F5B" stroke-width="1.5"></rect> <g fill="none" stroke="#56615A" stroke-width="2" marker-end="url(#c2a)"><path d="M226,125 L272,125"></path><path d="M488,125 L534,125"></path></g> <g text-anchor="middle" font-size="11" fill="#56615A"><text x="249" y="108">hace</text><text x="249" y="121">más</text><text x="249" y="148">probable</text><text x="511" y="108">hace</text><text x="511" y="121">más</text><text x="511" y="148">probable</text></g> <g text-anchor="middle"> <g font-size="15" font-weight="700" fill="#1F2A24"><text x="118" y="70">Calidad de proceso</text><text x="380" y="70">Calidad de producto</text><text x="642" y="70">Calidad en uso</text></g> <g font-size="12" fill="#1F2A24"><text x="118" y="96">Cómo trabaja el equipo</text><text x="380" y="96">Qué entrega el equipo</text><text x="642" y="96">Qué logra la persona</text></g> <g font-size="12" font-weight="600" fill="#1F2A24"><text x="118" y="132">Revisiones con acta</text><text x="380" y="132">La lista carga en 1,8 s</text><text x="642" y="132">Saca su turno sin ayuda</text></g> <g font-size="11.5" fill="#56615A"><text x="118" y="170">Se evalúa con</text><text x="118" y="186">auditorías y valoraciones</text><text x="380" y="170">Se evalúa con</text><text x="380" y="186">pruebas y mediciones</text><text x="642" y="170">Se evalúa con</text><text x="642" y="186">observación de uso real</text></g> <text x="380" y="236" font-size="12" fill="#56615A">Cada flecha sube la probabilidad. Ninguna la lleva a 100 %</text> </g>
</svg>
</div>
<p>La flecha es la parte delicada de la Parte 1. Un proceso ordenado hace más probable un buen producto y no lo asegura, porque el proceso decide qué se revisa y qué se prueba, y siempre queda algo que nadie pensó revisar. Un proceso caótico también puede entregar un buen producto una vez, por suerte, pero no puede repetirlo. La Parte 5 trae un caso donde las pruebas de equipo eran rigurosas y aun así faltó la prueba que importaba.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Predice antes de seguir
</div>
</div>
<div class="callout-body-container callout-body">
<p>El equipo de la clínica revisa todo el código, guarda el acta de cada revisión y automatiza sus pruebas. Marca la afirmación que te parezca correcta.</p>
<p><label><input type="checkbox"> El producto no puede tener defectos, porque el proceso es riguroso</label></p>
<p><label><input type="checkbox"> El producto tiene menos probabilidad de defectos, pero puede fallar si nadie revisó un caso concreto</label></p>
<p><label><input type="checkbox"> El proceso no influye en el producto, solo las pruebas finales importan</label></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La segunda afirmación es la correcta. La primera confunde probabilidad con garantía, y la tercera ignora que la mayoría de los defectos nacen antes de la prueba final, en los requisitos y en el diseño. Un caso concreto sin revisar basta para que falle: si nadie pensó en el paciente número 20, el equipo puede cumplir todo su proceso y aun así entregar <code>numeroTurno &lt; CUPO</code>.</p>
</div>
</div>
</div>
<section id="quién-evalúa-cada-una" class="level3">
<h3 class="anchored" data-anchor-id="quién-evalúa-cada-una">Quién evalúa cada una</h3>
<p>El Tema 1 mostró que la calidad se juzga contra requisitos. Lo que cambia entre las tres es el objeto que se juzga y la evidencia que se acepta.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Calidad de</th>
<th>Se juzga</th>
<th>Evidencia típica</th>
<th>Dónde se estudia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Proceso</td>
<td>Las actividades del equipo</td>
<td>Actas, registros, auditorías, valoraciones de madurez</td>
<td>Unidad 2 y Unidad 3</td>
</tr>
<tr class="even">
<td>Producto</td>
<td>El sistema construido</td>
<td>Resultados de pruebas y mediciones contra el modelo de la ISO/IEC 25010</td>
<td>Este tema</td>
</tr>
<tr class="odd">
<td>Uso</td>
<td>La experiencia real de las personas</td>
<td>Observación, pilotos, encuestas, registros de uso</td>
<td>Este tema y Unidad 3 (usabilidad)</td>
</tr>
</tbody>
</table>
<p>Una nota sobre las normas de proceso. La ISO 9001 certifica un sistema de gestión de la calidad de una organización, no un producto. Según fuentes de certificadoras que consulté, apareció una edición nueva en 2026, y conviene confirmar la vigente en iso.org. El modelo de madurez CMMI se explica en la Unidad 3, así que aquí solo se menciona. Lo que importa en este tema es que una certificación de proceso no sustituye medir el producto.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Clasifica seis frases
</div>
</div>
<div class="callout-body-container callout-body">
<p>Escribe en cada frase si habla de calidad de proceso, de producto o de uso.</p>
<ol type="1">
<li>“Cada cambio se revisa por dos personas antes de integrarse.”</li>
<li>“La consulta de turnos responde en menos de 2 segundos.”</li>
<li>“El equipo conserva el acta de cada auditoría interna.”</li>
<li>“Un paciente con baja visión completa su turno sin ayuda.”</li>
<li>“La app rechaza una fecha de reprogramación anterior a hoy.”</li>
<li>“Las pruebas se ejecutan automáticamente en cada versión.”</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Frase</th>
<th>Calidad de</th>
<th>Por qué</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Proceso</td>
<td>Describe cómo trabaja el equipo</td>
</tr>
<tr class="even">
<td>2</td>
<td>Producto</td>
<td>Es una propiedad medible del sistema</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Proceso</td>
<td>Es un registro de una actividad del equipo</td>
</tr>
<tr class="even">
<td>4</td>
<td>Uso</td>
<td>Habla del resultado de una persona real con una tarea</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Producto</td>
<td>Es un comportamiento del sistema, verificable con una prueba</td>
</tr>
<tr class="even">
<td>6</td>
<td>Proceso</td>
<td>Es una actividad del equipo. Los resultados de esas pruebas serían evidencia del producto</td>
</tr>
</tbody>
</table>
<p>La frase 6 es la más traicionera. La actividad de ejecutar pruebas es de proceso, pero lo que esas pruebas encuentran habla del producto.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-2.-el-modelo-de-la-isoiec-250102023" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="parte-2.-el-modelo-de-la-isoiec-250102023"><span class="header-section-number">5</span> Parte 2. El modelo de la ISO/IEC 25010:2023</h2>
<p>La ISO/IEC 25010 es la norma que ordena la calidad de un producto de software en piezas que se pueden especificar, medir y evaluar. Su segunda edición salió en noviembre de 2023, cancela y reemplaza la de 2011 y define un modelo de calidad de producto de nueve características, cada una dividida en subcaracterísticas.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Cómo cito esta norma
</div>
</div>
<div class="callout-body-container callout-body">
<p>El texto completo de la norma es de pago y no está reproducido aquí. Los nombres de las nueve características y los cambios respecto a 2011 están verificados en el prefacio y la introducción de la propia norma, que una editorial publica como vista previa gratuita. Las definiciones de las subcaracterísticas son paráfrasis mías, y los nombres en español son traducciones propias porque el oficial es el inglés. Para citar una frase exacta, consigue el texto por la biblioteca o en iso.org.</p>
</div>
</div>
<section id="cómo-está-organizada" class="level3">
<h3 class="anchored" data-anchor-id="cómo-está-organizada">2.1 Cómo está organizada</h3>
<p>El modelo tiene tres niveles. Una <em>característica</em> es un atributo amplio de calidad, como la fiabilidad. Una <em>subcaracterística</em> es una parte concreta de esa característica, como la disponibilidad. Una <em>medida</em> es lo que realmente se calcula, como el porcentaje de minutos operativos en un mes. El requisito de calidad de un proyecto fija un valor para esa medida.</p>
<div class="diagrama">
<svg viewbox="0 0 760 230" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cuatro cajas encadenadas: caracteristica, subcaracteristica, medida y requisito, con un ejemplo de eficiencia de desempeno en la app de turnos" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="c2b" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#56615A"></path></marker></defs> <g fill="#ECE6F8" stroke="#7A5BC7" stroke-width="1.5"><rect x="10" y="50" width="162" height="140" rx="12"></rect><rect x="202" y="50" width="162" height="140" rx="12"></rect></g> <g fill="#E3EFFA" stroke="#3B82C4" stroke-width="1.5"><rect x="394" y="50" width="162" height="140" rx="12"></rect><rect x="586" y="50" width="162" height="140" rx="12"></rect></g> <g fill="none" stroke="#56615A" stroke-width="2" marker-end="url(#c2b)"><path d="M174,120 L198,120"></path><path d="M366,120 L390,120"></path><path d="M558,120 L582,120"></path></g> <g text-anchor="middle"> <g font-size="13" font-weight="700" fill="#1F2A24"><text x="91" y="76">Característica</text><text x="283" y="76">Subcaracterística</text><text x="475" y="76">Medida</text><text x="667" y="76">Requisito</text></g> <g font-size="12" fill="#1F2A24"><text x="91" y="118">Eficiencia</text><text x="91" y="134">de desempeño</text><text x="283" y="118">Comportamiento</text><text x="283" y="134">temporal</text><text x="475" y="112">Tiempo de</text><text x="475" y="128">respuesta al listar</text><text x="475" y="144">los turnos</text><text x="667" y="112">El 95 % responde</text><text x="667" y="128">en 2 s o menos</text><text x="667" y="144">con 200 pacientes</text></g> <g font-size="11" fill="#56615A"><text x="91" y="172">lo fija la norma</text><text x="283" y="172">lo fija la norma</text><text x="475" y="172">la elige el equipo</text><text x="667" y="172">lo fija el negocio</text></g> <text x="380" y="216" font-size="12" fill="#56615A">La norma da los dos primeros niveles. Las medidas y los valores se deciden en cada proyecto</text> </g>
</svg>
</div>
</section>
<section id="qué-cambió-desde-2011" class="level3">
<h3 class="anchored" data-anchor-id="qué-cambió-desde-2011">2.2 Qué cambió desde 2011</h3>
<p>La edición de 2011 tenía ocho características: adecuación funcional, eficiencia de desempeño, compatibilidad, usabilidad, fiabilidad, seguridad, mantenibilidad y portabilidad. La de 2023 tiene nueve. El prefacio de la norma lista los cambios principales.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Cambio</th>
<th>Qué pasó</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nueva característica</td>
<td>Se agregó <em>safety</em> (seguridad frente a daños), con cinco subcaracterísticas</td>
</tr>
<tr class="even">
<td>Renombrada</td>
<td>Usabilidad pasó a ser capacidad de interacción</td>
</tr>
<tr class="odd">
<td>Renombrada</td>
<td>Portabilidad pasó a ser flexibilidad</td>
</tr>
<tr class="even">
<td>Subcaracterística nueva</td>
<td>Inclusividad y autodescriptividad, en capacidad de interacción</td>
</tr>
<tr class="odd">
<td>Subcaracterística nueva</td>
<td>Resistencia, en seguridad</td>
</tr>
<tr class="even">
<td>Subcaracterística nueva</td>
<td>Escalabilidad, en flexibilidad</td>
</tr>
<tr class="odd">
<td>Reemplazada</td>
<td>Estética de la interfaz de usuario pasó a ser participación del usuario</td>
</tr>
<tr class="even">
<td>Reemplazada</td>
<td>Madurez pasó a ser ausencia de fallos</td>
</tr>
<tr class="odd">
<td>Dividida</td>
<td>Accesibilidad se dividió en inclusividad y asistencia al usuario</td>
</tr>
<tr class="even">
<td>Movida</td>
<td>El modelo de calidad en uso salió de esta norma y quedó en la ISO/IEC 25019</td>
</tr>
<tr class="odd">
<td>Ampliado</td>
<td>El objeto del modelo pasó de “software” a productos de las tecnologías de la información y las comunicaciones</td>
</tr>
</tbody>
</table>
<p>Dos observaciones útiles. La primera es que el modelo de calidad en uso ya no vive dentro de la ISO/IEC 25010, y muchos textos anteriores a 2023 todavía lo presentan como parte de ella. La segunda es que con la lista de subcaracterísticas de la sección siguiente suman 40 en 2023, según mi propia cuenta.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Una confusión frecuente de traducción
</div>
</div>
<div class="callout-body-container callout-body">
<p>En español, security y safety se traducen casi siempre como seguridad. En este tema escribo seguridad informática para <em>security</em> (proteger datos y accesos) y seguridad frente a daños para <em>safety</em> (evitar que el producto cause daño a personas, bienes o entorno). La novena característica de 2023 es <em>safety</em>.</p>
</div>
</div>
</section>
<section id="las-nueve-características" class="level3">
<h3 class="anchored" data-anchor-id="las-nueve-características">2.3 Las nueve características</h3>
<div class="diagrama">
<svg viewbox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cuadricula de tres por tres con las nueve caracteristicas de la ISO IEC 25010 de 2023" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="14" y="26" font-size="14" font-weight="700" fill="#1F2A24">ISO/IEC 25010:2023. Modelo de calidad de producto</text> <g fill="#E3EFFA" stroke="#3B82C4" stroke-width="1.2"> <rect x="14" y="42" width="232" height="66" rx="10"></rect><rect x="264" y="42" width="232" height="66" rx="10"></rect><rect x="514" y="42" width="232" height="66" rx="10"></rect> <rect x="14" y="120" width="232" height="66" rx="10"></rect><rect x="264" y="120" width="232" height="66" rx="10"></rect><rect x="514" y="120" width="232" height="66" rx="10"></rect> <rect x="14" y="198" width="232" height="66" rx="10"></rect><rect x="264" y="198" width="232" height="66" rx="10"></rect> </g> <rect x="514" y="198" width="232" height="66" rx="10" fill="#FBE3DB" stroke="#E4572E" stroke-width="1.2"></rect> <g text-anchor="middle"> <g font-size="13.5" font-weight="700" fill="#1F2A24"><text x="130" y="70">1. Adecuación funcional</text><text x="380" y="70">2. Eficiencia de desempeño</text><text x="630" y="70">3. Compatibilidad</text><text x="130" y="148">4. Capacidad de interacción</text><text x="380" y="148">5. Fiabilidad</text><text x="630" y="148">6. Seguridad informática</text><text x="130" y="226">7. Mantenibilidad</text><text x="380" y="226">8. Flexibilidad</text><text x="630" y="226">9. Seguridad frente a daños</text></g> <g font-size="11.5" fill="#56615A"><text x="130" y="90">3 subcaracterísticas</text><text x="380" y="90">3 subcaracterísticas</text><text x="630" y="90">2 subcaracterísticas</text><text x="130" y="168">8, antes usabilidad</text><text x="380" y="168">4 subcaracterísticas</text><text x="630" y="168">6 subcaracterísticas</text><text x="130" y="246">5 subcaracterísticas</text><text x="380" y="246">4, antes portabilidad</text><text x="630" y="246">5, nueva en 2023</text></g> <text x="380" y="288" font-size="11.5" fill="#56615A">Rojo marca la que habla de riesgo de daño. Todas son atributos del producto</text> </g>
</svg>
</div>
<p>Cada característica va con una tabla de sus subcaracterísticas. La última columna aplica la idea a la app de la clínica. Los ejemplos de seguridad frente a daños son diseño ficticio y no una guía clínica.</p>
<section id="adecuación-funcional" class="level4">
<h4 class="anchored" data-anchor-id="adecuación-funcional">1. Adecuación funcional</h4>
<p>Grado en que el producto ofrece las funciones que satisfacen las necesidades declaradas e implícitas de quien lo usa. Pregunta clave: ¿hace lo que se necesita, y lo hace bien?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Subcaracterística</th>
<th>Qué significa</th>
<th>En la app de turnos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Completitud funcional</td>
<td>Las funciones cubren todas las tareas y objetivos del usuario</td>
<td>La app permite pedir, reprogramar y cancelar. Si faltara cancelar, estaría incompleta</td>
</tr>
<tr class="even">
<td>Corrección funcional</td>
<td>Da resultados correctos con la precisión necesaria</td>
<td>El paciente 20 recibe su turno. El defecto <code>numeroTurno &lt; CUPO</code> es una falla de corrección</td>
</tr>
<tr class="odd">
<td>Pertinencia funcional</td>
<td>Las funciones facilitan la tarea y no la complican</td>
<td>Pedir un turno toma tres pasos, no doce</td>
</tr>
</tbody>
</table>
</section>
<section id="eficiencia-de-desempeño" class="level4">
<h4 class="anchored" data-anchor-id="eficiencia-de-desempeño">2. Eficiencia de desempeño</h4>
<p>Desempeño en relación con los recursos que usa, bajo condiciones establecidas. Pregunta clave: ¿qué tan rápido responde y cuántos recursos gasta?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Subcaracterística</th>
<th>Qué significa</th>
<th>En la app de turnos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Comportamiento temporal</td>
<td>Tiempos de respuesta y de procesamiento y tasas de rendimiento</td>
<td>La lista de turnos carga en menos de 2 segundos</td>
</tr>
<tr class="even">
<td>Utilización de recursos</td>
<td>Cantidad y tipo de recursos que consume</td>
<td>La app gasta pocos datos móviles en un plan prepago</td>
</tr>
<tr class="odd">
<td>Capacidad</td>
<td>Límites máximos que soporta</td>
<td>A las 7 de la mañana la app atiende 200 pacientes a la vez</td>
</tr>
</tbody>
</table>
</section>
<section id="compatibilidad" class="level4">
<h4 class="anchored" data-anchor-id="compatibilidad">3. Compatibilidad</h4>
<p>Grado en que el producto intercambia información con otros y cumple sus funciones compartiendo el mismo entorno de hardware o software. Pregunta clave: ¿convive y se entiende con los demás?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Subcaracterística</th>
<th>Qué significa</th>
<th>En la app de turnos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Coexistencia</td>
<td>Funciona junto a otros productos que comparten recursos, sin dañarlos ni ser dañado</td>
<td>El servidor de la app comparte máquina con otros sistemas de la clínica sin quitarles memoria</td>
</tr>
<tr class="even">
<td>Interoperabilidad</td>
<td>Intercambia información con otros sistemas y la usa</td>
<td>Cada turno asignado se envía al sistema de historia clínica con el formato acordado</td>
</tr>
</tbody>
</table>
</section>
<section id="capacidad-de-interacción" class="level4">
<h4 class="anchored" data-anchor-id="capacidad-de-interacción">4. Capacidad de interacción</h4>
<p>Grado en que usuarios específicos pueden usar el producto para lograr sus metas con eficacia, eficiencia y satisfacción. En 2011 se llamaba usabilidad. Pregunta clave: ¿la persona logra su tarea sin tropezar?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Subcaracterística</th>
<th>Qué significa</th>
<th>En la app de turnos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reconocibilidad de la adecuación</td>
<td>La persona reconoce si el producto le sirve para lo que necesita</td>
<td>Al abrirla, una paciente entiende que es para pedir citas</td>
</tr>
<tr class="even">
<td>Capacidad de aprendizaje</td>
<td>Se aprende a usar rápido</td>
<td>La primera vez se saca un turno sin manual</td>
</tr>
<tr class="odd">
<td>Operabilidad</td>
<td>Los controles son fáciles de manejar y de controlar</td>
<td>Los botones se pulsan con facilidad en una pantalla pequeña</td>
</tr>
<tr class="even">
<td>Protección frente a errores del usuario</td>
<td>Evita que la persona se equivoque o la ayuda a corregir</td>
<td>Pide confirmación antes de cancelar un turno y no acepta fechas pasadas</td>
</tr>
<tr class="odd">
<td>Participación del usuario</td>
<td>La interfaz invita a seguir usándola de forma agradable</td>
<td>El diseño es claro y el proceso se siente fluido</td>
</tr>
<tr class="even">
<td>Inclusividad</td>
<td>Pueden usarla personas de la más amplia gama de capacidades y características</td>
<td>Texto ajustable, contraste suficiente y compatibilidad con lector de pantalla</td>
</tr>
<tr class="odd">
<td>Asistencia al usuario</td>
<td>Ayuda a quien la necesita cuando la necesita</td>
<td>Hay ayuda en cada pantalla y el teléfono de la clínica a la vista</td>
</tr>
<tr class="even">
<td>Autodescriptividad</td>
<td>Muestra la información adecuada para entender qué hace y cómo</td>
<td>El mensaje dice “sin cupo hoy, el próximo turno es el lunes” y no “Error 500”</td>
</tr>
</tbody>
</table>
</section>
<section id="fiabilidad" class="level4">
<h4 class="anchored" data-anchor-id="fiabilidad">5. Fiabilidad</h4>
<p>Grado en que el sistema cumple sus funciones bajo condiciones específicas durante un periodo específico. Pregunta clave: ¿funciona cuando se le necesita, y se recupera si falla?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Subcaracterística</th>
<th>Qué significa</th>
<th>En la app de turnos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ausencia de fallos</td>
<td>Funciona sin fallas en operación normal. En 2011 se llamaba madurez</td>
<td>La asignación de turnos no se cae en un día normal</td>
</tr>
<tr class="even">
<td>Disponibilidad</td>
<td>Está operativo y accesible cuando se requiere</td>
<td>La app responde de 6 a. m. a 8 p.&nbsp;m., que es cuando la clínica atiende</td>
</tr>
<tr class="odd">
<td>Tolerancia a fallos</td>
<td>Sigue operando aunque haya fallas de hardware o de software</td>
<td>Si el servicio de mensajes de texto cae, la app sigue asignando turnos y avisa por correo</td>
</tr>
<tr class="even">
<td>Recuperabilidad</td>
<td>Restablece los datos y el estado tras una falla</td>
<td>Tras una caída recupera todos los turnos asignados hasta el último minuto</td>
</tr>
</tbody>
</table>
</section>
<section id="seguridad-informática" class="level4">
<h4 class="anchored" data-anchor-id="seguridad-informática">6. Seguridad informática</h4>
<p>Grado en que el producto protege la información y los datos para que cada persona o sistema tenga solo el acceso que corresponde a su autorización. En inglés es <em>security</em>. Pregunta clave: ¿quién puede ver o cambiar qué?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Subcaracterística</th>
<th>Qué significa</th>
<th>En la app de turnos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Confidencialidad</td>
<td>Los datos son accesibles solo a quien está autorizado</td>
<td>Un paciente nunca ve los turnos de otro</td>
</tr>
<tr class="even">
<td>Integridad</td>
<td>Impide el acceso o la modificación no autorizados</td>
<td>Nadie altera un turno sin dejar rastro</td>
</tr>
<tr class="odd">
<td>No repudio</td>
<td>Se puede probar que una acción ocurrió, de modo que no pueda negarse</td>
<td>Queda registro de que la paciente confirmó la cancelación</td>
</tr>
<tr class="even">
<td>Responsabilidad</td>
<td>Cada acción se atribuye a quien la hizo</td>
<td>Cada cambio del personal queda con su usuario</td>
</tr>
<tr class="odd">
<td>Autenticidad</td>
<td>Se puede demostrar la identidad de una persona o recurso</td>
<td>El ingreso verifica quién es el paciente</td>
</tr>
<tr class="even">
<td>Resistencia</td>
<td>Resiste, responde y se recupera ante ataques</td>
<td>Tras varios intentos fallidos de ingreso, la cuenta se bloquea y avisa</td>
</tr>
</tbody>
</table>
<p>Los datos de salud son datos sensibles según el artículo 5 de la Ley 1581 de 2012, la ley colombiana de protección de datos personales. Eso sube el peso de esta característica en la app de la clínica, y por eso un requisito de confidencialidad no es opcional.</p>
</section>
<section id="mantenibilidad" class="level4">
<h4 class="anchored" data-anchor-id="mantenibilidad">7. Mantenibilidad</h4>
<p>Grado de eficacia y eficiencia con que los mantenedores previstos pueden modificar el producto. Pregunta clave: ¿se puede seguir mejorando sin romperlo?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Subcaracterística</th>
<th>Qué significa</th>
<th>En la app de turnos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Modularidad</td>
<td>Cambiar un componente afecta poco a los demás</td>
<td>El módulo de cupos está separado del de notificaciones</td>
</tr>
<tr class="even">
<td>Reutilizabilidad</td>
<td>Un componente sirve en otros sistemas</td>
<td>El ingreso de usuarios se reutiliza en otra app de la clínica</td>
</tr>
<tr class="odd">
<td>Analizabilidad</td>
<td>Se puede evaluar el efecto de un cambio y diagnosticar fallas</td>
<td>Un registro permite ver por qué se rechazó el turno 20</td>
</tr>
<tr class="even">
<td>Modificabilidad</td>
<td>Se modifica sin introducir defectos ni empeorar el producto</td>
<td>El cupo diario cambia sin tocar el código de asignación</td>
</tr>
<tr class="odd">
<td>Capacidad de ser probado</td>
<td>Se pueden definir criterios de prueba y ejecutarlos</td>
<td>El límite de cupo se verifica con una prueba automática</td>
</tr>
</tbody>
</table>
</section>
<section id="flexibilidad" class="level4">
<h4 class="anchored" data-anchor-id="flexibilidad">8. Flexibilidad</h4>
<p>Grado en que el producto se adapta a hardware, software o entornos de operación distintos o cambiantes. En 2011 se llamaba portabilidad. Pregunta clave: ¿cambia con su entorno?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Subcaracterística</th>
<th>Qué significa</th>
<th>En la app de turnos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Adaptabilidad</td>
<td>Se adapta a entornos distintos o que evolucionan</td>
<td>Funciona en Android, en iPhone y en el navegador</td>
</tr>
<tr class="even">
<td>Escalabilidad</td>
<td>Maneja el crecimiento de carga o de capacidad</td>
<td>Pasa de una sede a cinco sin rehacerse</td>
</tr>
<tr class="odd">
<td>Instalabilidad</td>
<td>Se instala y desinstala con éxito en un entorno</td>
<td>Se instala desde la tienda sin pasos manuales</td>
</tr>
<tr class="even">
<td>Reemplazabilidad</td>
<td>Puede sustituir a otro producto con el mismo propósito</td>
<td>Reemplaza el sistema de turnos anterior y migra sus datos</td>
</tr>
</tbody>
</table>
</section>
<section id="seguridad-frente-a-daños-safety" class="level4">
<h4 class="anchored" data-anchor-id="seguridad-frente-a-daños-safety">9. Seguridad frente a daños (safety)</h4>
<p>Grado en que el producto evita causar daño a personas, al negocio, a bienes o al entorno en un contexto de uso. Es la característica nueva de 2023. Pregunta clave: si algo sale mal, ¿a quién puede hacerle daño el producto?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Subcaracterística</th>
<th>Qué significa</th>
<th>En la app de turnos (ejemplo ficticio)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Restricción operacional</td>
<td>Limita la operación a parámetros seguros</td>
<td>No deja agendar un procedimiento sin que se registren las alergias</td>
</tr>
<tr class="even">
<td>Identificación de riesgos</td>
<td>Identifica riesgos que pueden causar daño</td>
<td>La clínica lista qué fallas de la app podrían perjudicar a un paciente</td>
</tr>
<tr class="odd">
<td>Falla segura</td>
<td>Si falla, pasa a un estado seguro</td>
<td>Si el módulo de prioridades falla, la app remite al teléfono de la clínica y no asigna un turno normal</td>
</tr>
<tr class="even">
<td>Aviso de peligros</td>
<td>Advierte de riesgos a quien puede sufrirlos</td>
<td>Si la paciente marca síntomas de alarma, ve un aviso de acudir a urgencias</td>
</tr>
<tr class="odd">
<td>Integración segura</td>
<td>Mantiene la seguridad al combinarse con otros sistemas</td>
<td>Un cambio de formato en la historia clínica nunca mezcla datos de dos pacientes</td>
</tr>
</tbody>
</table>
<p>El caso del Tema 1 sobre una máquina de radioterapia habla de esta característica. Aquí la consecuencia más seria no es una pantalla fea sino un paciente perjudicado.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. Ubica seis quejas en el modelo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para cada queja, escribe la característica y la subcaracterística que mejor la describen.</p>
<ol type="1">
<li>“Pedí mi turno y la app me mostró el de otra persona.”</li>
<li>“A las 7 de la mañana la pantalla se queda cargando.”</li>
<li>“Mi mamá, que usa letra grande, no logra leer los botones.”</li>
<li>“Cuando se cayó el servicio de mensajes, la app dejó de asignar turnos.”</li>
<li>“Para cambiar el cupo diario tuvieron que reescribir medio programa.”</li>
<li>“La app asignó turno de cirugía a un paciente sin registrar alergias.”</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Queja</th>
<th>Característica</th>
<th>Subcaracterística</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Seguridad informática</td>
<td>Confidencialidad</td>
</tr>
<tr class="even">
<td>2</td>
<td>Eficiencia de desempeño</td>
<td>Comportamiento temporal (o capacidad, si ocurre solo con muchos usuarios)</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Capacidad de interacción</td>
<td>Inclusividad</td>
</tr>
<tr class="even">
<td>4</td>
<td>Fiabilidad</td>
<td>Tolerancia a fallos</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Mantenibilidad</td>
<td>Modificabilidad</td>
</tr>
<tr class="even">
<td>6</td>
<td>Seguridad frente a daños</td>
<td>Restricción operacional</td>
</tr>
</tbody>
</table>
<p>En la queja 2 hay dos lecturas válidas. Si ocurre con una sola persona, es comportamiento temporal. Si solo ocurre cuando hay muchas a la vez, es capacidad. Elegir bien depende de los datos, y esa es otra razón para medir antes de opinar.</p>
</div>
</div>
</div>
</section>
</section>
<section id="square-como-mapa" class="level3">
<h3 class="anchored" data-anchor-id="square-como-mapa">2.4 SQuaRE como mapa</h3>
<p>La ISO/IEC 25010 es una pieza de una familia, SQuaRE, siglas en inglés de <em>Systems and software Quality Requirements and Evaluation</em> (requisitos y evaluación de la calidad de sistemas y software). La introducción de la propia norma la organiza en divisiones, que sirven de mapa.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Serie</th>
<th>División</th>
<th>Ejemplos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2500n</td>
<td>Gestión de la calidad</td>
<td>25000 (guía), 25001 (planificación), 25002 (uso de los modelos)</td>
</tr>
<tr class="even">
<td>2501n</td>
<td>Modelos de calidad</td>
<td>25010 (producto), 25011 (servicios), 25012 (datos), 25019 (calidad en uso)</td>
</tr>
<tr class="odd">
<td>2502n</td>
<td>Medición de la calidad</td>
<td>Medidas de producto, de datos y de uso</td>
</tr>
<tr class="even">
<td>2503n</td>
<td>Requisitos de calidad</td>
<td>25030, cómo especificar requisitos de calidad</td>
</tr>
<tr class="odd">
<td>2504n</td>
<td>Evaluación de la calidad</td>
<td>25040, el marco de evaluación</td>
</tr>
<tr class="even">
<td>25050 a 25099</td>
<td>Extensiones</td>
<td>Calidad de software listo para usar, nuevas tecnologías como la nube y la inteligencia artificial</td>
</tr>
</tbody>
</table>
<p>El detalle de la familia, junto con ISO 9001 e inteligencia artificial, es del Tema 2 de la Unidad 3. Aquí basta con saber dónde encaja cada pieza. Hay una sola mención extra porque conecta con la Parte 4: la ISO/IEC 25030:2019 trata los requisitos de calidad y la ISO/IEC 25023:2016 trae medidas para las características. La 25023 es anterior al modelo de 2023, así que no afirmo cómo se alinea con él.</p>
</section>
<section id="isoiec-25059-calidad-de-sistemas-con-inteligencia-artificial" class="level3">
<h3 class="anchored" data-anchor-id="isoiec-25059-calidad-de-sistemas-con-inteligencia-artificial">2.5 ISO/IEC 25059: calidad de sistemas con inteligencia artificial</h3>
<p>La ISO/IEC 25059:2023 es una extensión de SQuaRE que define un modelo de calidad para sistemas de inteligencia artificial. Agrega propiedades que el modelo base no cubre bien, como la adaptabilidad funcional (usar lo aprendido en predicciones futuras), la robustez, la transparencia, la controlabilidad por el usuario y la mitigación de riesgos éticos y sociales.</p>
<p>La edición de 2023 extiende el modelo de 2011. Según fuentes secundarias, hay una segunda edición en elaboración que se alinea con la ISO/IEC 25010:2023, y no pude confirmar su estado en la ficha oficial. Si la app de la clínica sumara un asistente que sugiere la especialidad según los síntomas, aplicarían las dos normas a la vez.</p>
</section>
</section>
<section id="parte-3.-calidad-en-uso" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="parte-3.-calidad-en-uso"><span class="header-section-number">6</span> Parte 3. Calidad en uso</h2>
<p>El modelo de producto describe lo que el sistema es. La calidad en uso describe lo que ocurre cuando alguien lo usa. La ISO/IEC 25019:2023 la define como el efecto que tiene el uso del sistema sobre quienes lo usan, en un contexto de uso específico. Tiene tres características.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Característica</th>
<th>Subcaracterísticas</th>
<th>Idea</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Beneficiosidad</td>
<td>Usabilidad, accesibilidad, idoneidad</td>
<td>Cuánto beneficio resulta de usar el producto</td>
</tr>
<tr class="even">
<td>Libertad de riesgo</td>
<td>Riesgo económico, riesgo ambiental y social, riesgo para la salud, riesgo para la vida</td>
<td>Cuánto reduce el producto el riesgo en su contexto</td>
</tr>
<tr class="odd">
<td>Aceptabilidad</td>
<td>Experiencia, confianza (<em>trustworthiness</em>), cumplimiento</td>
<td>Cuánto favorece la respuesta humana al aceptarlo</td>
</tr>
</tbody>
</table>
<p>La edición de 2011 de la ISO/IEC 25010 definía otro modelo de calidad en uso con cinco características: eficacia, eficiencia, satisfacción, libertad de riesgo y cobertura del contexto. Si lees un texto anterior a 2023, ahí está.</p>
<section id="un-ejemplo-resuelto" class="level3">
<h3 class="anchored" data-anchor-id="un-ejemplo-resuelto">Un ejemplo resuelto</h3>
<p>Situación. La app de la clínica cumple todos sus requisitos de producto. Responde en 1,8 segundos, asigna el turno 20, protege los datos. Aun así, en el piloto con diez pacientes mayores de 65 años, solo tres logran sacar su turno sin ayuda.</p>
<p>Paso 1, pregunta de análisis. ¿La app incumple su especificación? No.&nbsp;Todas las pruebas de producto pasan.</p>
<p>Paso 2. ¿Entonces la calidad es buena? Depende de a qué calidad te refieras. La calidad de producto es buena contra los requisitos escritos. La calidad en uso es mala, porque la tarea de la persona no se completa.</p>
<p>Paso 3. Ubica la brecha. La beneficiosidad falla en su subcaracterística de usabilidad. En el modelo de producto, la causa probable está en capacidad de interacción, en inclusividad y autodescriptividad, que nadie había convertido en requisito.</p>
<p>Paso 4. Qué hacer. Se agregan requisitos de capacidad de interacción medibles, como los de la Parte 4, y se repite el piloto.</p>
<p>Esta es la versión moderna de la tensión que viste en el Tema 1 entre Crosby (conformidad) y Juran (aptitud para el uso). Un producto conforme puede no servir, y una norma separa esas dos preguntas en dos modelos. Verificación y validación, que se estudian en la Unidad 4, nacen de esa misma separación.</p>
<p>El <em>contexto de uso</em> decide el resultado. El mismo producto, con los mismos usuarios, da otra calidad en uso en una sala de espera ruidosa, con luz solar fuerte, con un teléfono viejo o con datos móviles limitados. Por eso conviene escribir el contexto en el requisito, como verás en la Parte 4.</p>
</section>
</section>
<section id="parte-4.-requisitos-de-calidad-medibles" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="parte-4.-requisitos-de-calidad-medibles"><span class="header-section-number">7</span> Parte 4. Requisitos de calidad medibles</h2>
<p>Un requisito de calidad, también llamado requisito no funcional, dice qué tan bien debe hacer algo el producto y no solo qué debe hacer. Es donde más se pierde el control de la calidad, porque cualquiera puede escribir “debe ser rápido” y nadie puede comprobarlo.</p>
<section id="por-qué-debe-ser-rápido-no-sirve" class="level3">
<h3 class="anchored" data-anchor-id="por-qué-debe-ser-rápido-no-sirve">4.1 Por qué “debe ser rápido” no sirve</h3>
<p>Una frase como “la app tiene que ser rápida” parece un requisito y es una opinión. Si el paciente dice que es lenta y el equipo dice que es rápida, no existe nada escrito que decida quién tiene razón. Gana quien tenga más poder en la reunión, como ya viste en el Tema 1.</p>
<p>Un requisito de calidad se puede comprobar cuando responde cinco preguntas.</p>
</section>
<section id="las-cinco-piezas" class="level3">
<h3 class="anchored" data-anchor-id="las-cinco-piezas">4.2 Las cinco piezas</h3>
<ol type="1">
<li>Característica. ¿De qué parte del modelo de la ISO/IEC 25010 habla?</li>
<li>Medida. ¿Qué se mide y cómo se calcula?</li>
<li>Umbral. ¿Cuál es el valor límite que separa cumplir de no cumplir?</li>
<li>Condiciones. ¿Con qué carga, datos, equipo y personas vale ese umbral?</li>
<li>Verificación. ¿Con qué método y en qué momento se comprueba?</li>
</ol>
<div class="diagrama">
<svg viewbox="0 0 760 270" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Las cinco piezas de un requisito de calidad medible, con el ejemplo de tiempo de respuesta de la app de turnos" font-family="Segoe UI, Inter, system-ui, sans-serif">
<g fill="#E3EFFA" stroke="#3B82C4" stroke-width="1.3"><rect x="10" y="44" width="140" height="150" rx="10"></rect><rect x="158" y="44" width="140" height="150" rx="10"></rect><rect x="306" y="44" width="140" height="150" rx="10"></rect><rect x="454" y="44" width="140" height="150" rx="10"></rect></g> <rect x="602" y="44" width="140" height="150" rx="10" fill="#E1F2E8" stroke="#2F8F5B" stroke-width="1.3"></rect> <text x="380" y="26" text-anchor="middle" font-size="14" font-weight="700" fill="#1F2A24">Cinco piezas de un requisito de calidad medible</text> <g text-anchor="middle"> <g font-size="12.5" font-weight="700" fill="#1F2A24"><text x="80" y="68">1. Característica</text><text x="228" y="68">2. Medida</text><text x="376" y="68">3. Umbral</text><text x="524" y="68">4. Condiciones</text><text x="672" y="68">5. Verificación</text></g> <g font-size="11.5" fill="#1F2A24"> <text x="80" y="102">Eficiencia de</text><text x="80" y="117">desempeño,</text><text x="80" y="132">comportamiento</text><text x="80" y="147">temporal</text> <text x="228" y="102">Tiempo de</text><text x="228" y="117">respuesta al</text><text x="228" y="132">listar turnos,</text><text x="228" y="147">percentil 95</text> <text x="376" y="102">2 segundos</text><text x="376" y="117">o menos</text> <text x="524" y="102">200 pacientes</text><text x="524" y="117">conectados,</text><text x="524" y="132">agenda de un</text><text x="524" y="147">día lleno</text> <text x="672" y="102">Prueba de carga</text><text x="672" y="117">antes de cada</text><text x="672" y="132">versión</text> </g> <text x="380" y="224" font-size="12" fill="#56615A">Si quitas una pieza, el requisito vuelve a ser una opinión con forma de requisito</text> <text x="380" y="246" font-size="12" fill="#56615A">Azul: producto y requisitos. Verde: la evidencia que lo demuestra</text> </g>
</svg>
</div>
<p>Existen otras formas de decir lo mismo. Los escenarios de atributos de calidad de Bass, Clements y Kazman, en el libro de arquitectura de software de la bibliografía, usan seis partes: fuente, estímulo, artefacto, entorno, respuesta y medida de la respuesta. Las cinco piezas de esta guía son una versión compacta de esa idea.</p>
</section>
<section id="ejemplo-resuelto-1-desempeño" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-1-desempeño">4.3 Ejemplo resuelto 1: desempeño</h3>
<p>Queja del paciente: “La app es lenta.”</p>
<p>Paso 1, característica. “Lenta” habla de tiempo, así que es eficiencia de desempeño, subcaracterística comportamiento temporal.</p>
<p>Paso 2, medida. Hay que decidir qué operación se mide. Se elige la que más duele, listar los turnos disponibles. La medida es el tiempo entre tocar el botón y ver la lista completa.</p>
<p>Paso 3, umbral. Se pregunta qué espera una persona razonable y qué puede lograr el sistema. Se fija 2 segundos. Un promedio sería engañoso, así que se mide con el percentil 95, que se explica en la sección 4.6.</p>
<p>Paso 4, condiciones. Un tiempo sin carga no dice nada. Se agrega la carga más dura que se espera: 200 pacientes conectados a las 7 de la mañana, con la agenda de un día lleno.</p>
<p>Paso 5, verificación. Se decide cómo y cuándo se comprueba: una prueba de carga antes de cada versión.</p>
<p>Requisito resultante.</p>
<blockquote class="blockquote">
<p>RNF-01. En la lista de turnos disponibles, el 95 % de las solicitudes responde en 2 segundos o menos, medido en el servidor, con 200 pacientes conectados y la agenda de un día lleno. Se comprueba con una prueba de carga antes de cada versión.</p>
</blockquote>
<p>Ahora cualquier persona puede decir si se cumple, sin preguntarle al autor qué quiso decir.</p>
</section>
<section id="ejemplo-resuelto-2-capacidad-de-interacción" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-2-capacidad-de-interacción">4.4 Ejemplo resuelto 2: capacidad de interacción</h3>
<p>Queja de la clínica: “La app debe ser fácil para los mayores.”</p>
<p>Paso 1, característica. “Fácil” mezcla aprendizaje y acceso. La parte “para los mayores” apunta a inclusividad y capacidad de aprendizaje, ambas de capacidad de interacción.</p>
<p>Paso 2, medida. Se elige una medida de logro de tarea: el porcentaje de personas que completan el turno sin pedir ayuda.</p>
<p>Paso 3, umbral. Se fija que 8 de cada 10 lo logren en 3 minutos o menos.</p>
<p>Paso 4, condiciones. Se dice quiénes: personas de 65 años o más, en su propio teléfono, sin haber usado la app antes. Se agrega un criterio técnico de accesibilidad, la conformidad con la WCAG 2.2, la versión vigente de las pautas del W3C, en nivel AA.</p>
<p>Paso 5, verificación. Una prueba de uso con diez personas del grupo, antes del lanzamiento.</p>
<blockquote class="blockquote">
<p>RNF-02. Al menos 8 de cada 10 personas de 65 años o más, usando por primera vez la app en su propio teléfono, completan una solicitud de turno en 3 minutos o menos y sin ayuda. La interfaz cumple la WCAG 2.2 nivel AA. Se comprueba con una prueba de uso con 10 personas antes del lanzamiento.</p>
</blockquote>
<p>Observa que este requisito mide calidad en uso y exige una característica de producto a la vez. Esa es la forma habitual de un buen requisito de capacidad de interacción.</p>
</section>
<section id="ejemplo-resuelto-3-fiabilidad" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-3-fiabilidad">4.5 Ejemplo resuelto 3: fiabilidad</h3>
<p>Queja de la clínica: “No se puede caer.”</p>
<p>Paso 1, característica. “No caerse” es disponibilidad, de fiabilidad. Si además importa qué pasa cuando cae, entra la recuperabilidad.</p>
<p>Paso 2, medida. Disponibilidad mensual es el porcentaje de minutos del horario de atención en los que el inicio de sesión funciona. Hay que definir qué cuenta como caída, y se define: todo minuto en que el inicio de sesión falle.</p>
<p>Paso 3, umbral. 99,5 % mensual. En un mes de 30 días con 14 horas de atención al día, eso permite poco más de dos horas de caída, y conviene hacer la cuenta para ver si el negocio la acepta.</p>
<p>Paso 4, condiciones. Solo cuenta el horario de atención, de 6 a. m. a 8 p.&nbsp;m. Los mantenimientos anunciados con 48 horas de antelación no cuentan como caída.</p>
<p>Paso 5, verificación. Se calcula cada mes con los registros del sistema de monitoreo.</p>
<blockquote class="blockquote">
<p>RNF-03. La disponibilidad mensual del inicio de sesión es de 99,5 % o más, contando como caída todo minuto del horario de atención en que falle. El mantenimiento anunciado con 48 horas de antelación no cuenta. Se calcula cada mes con los registros del monitoreo.</p>
</blockquote>
<p>La cuenta, para que la revises. Son 14 horas por 30 días, es decir 420 horas de atención al mes, o 25.200 minutos. El 0,5 % de eso son 126 minutos, algo más de dos horas.</p>
</section>
<section id="medir-bien-promedio-contra-percentil-95" class="level3">
<h3 class="anchored" data-anchor-id="medir-bien-promedio-contra-percentil-95">4.6 Medir bien: promedio contra percentil 95</h3>
<p>Un promedio puede esconder lo que más duele. Imagina diez consultas de la lista de turnos, nueve que tardan 1 segundo y una que tarda 12.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Medida</th>
<th>Valor</th>
<th>Cómo se calcula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Promedio</td>
<td>2,1 segundos</td>
<td>(9 por 1 más 12) entre 10</td>
</tr>
<tr class="even">
<td>Mediana</td>
<td>1 segundo</td>
<td>El valor central, entre el quinto y el sexto, ambos de 1 s</td>
</tr>
<tr class="odd">
<td>Percentil 95</td>
<td>12 segundos</td>
<td>El valor bajo el cual queda el 95 % de las mediciones, con el método del rango más cercano</td>
</tr>
</tbody>
</table>
<p>El percentil 95 se calcula así: se ordenan las mediciones, se multiplica 0,95 por el número de mediciones, se redondea hacia arriba y se toma el valor de esa posición. Con diez mediciones la posición es la 10, que vale 12.</p>
<p>Con el promedio, la app parece aceptable a 2,1 s. Con el percentil 95, se ve que una de cada diez personas espera 12 segundos. Un requisito que exige “el 95 % en 2 segundos o menos” habría detectado el problema. La presentación interactiva trae una simulación para ver esta diferencia con carga variable.</p>
</section>
<section id="ejemplos-resueltos-para-las-nueve-características" class="level3">
<h3 class="anchored" data-anchor-id="ejemplos-resueltos-para-las-nueve-características">4.7 Ejemplos resueltos para las nueve características</h3>
<p>Cada fila sigue el mismo método de las cinco piezas. Los números son del ejemplo.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Característica y subcaracterística</th>
<th>Queja</th>
<th>Requisito medible</th>
<th>Verificación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Adecuación funcional, corrección</td>
<td>“A veces el último turno del día no sale”</td>
<td>RNF-04. La app asigna los turnos del 1 al 20 de cada especialidad y rechaza el 21, en el 100 % de los casos de borde definidos para el cupo</td>
<td>Pruebas automáticas de borde en cada versión</td>
</tr>
<tr class="even">
<td>Compatibilidad, interoperabilidad</td>
<td>“La historia clínica no recibe los turnos”</td>
<td>RNF-05. El 99,9 % de los mensajes de turno enviados al sistema de historia clínica cumple el esquema acordado y se confirma recibido en 1 minuto</td>
<td>Prueba de contrato entre sistemas y registro de mensajes</td>
</tr>
<tr class="odd">
<td>Seguridad informática, confidencialidad</td>
<td>“No quiero que otros vean mis datos”</td>
<td>RNF-06. Ninguna consulta de un paciente devuelve turnos de otro paciente, y los datos de salud viajan cifrados</td>
<td>Prueba de autorización por rol y revisión de seguridad antes de cada versión</td>
</tr>
<tr class="even">
<td>Mantenibilidad, modificabilidad</td>
<td>“Cambiar el cupo cuesta días”</td>
<td>RNF-07. Cambiar el cupo de una especialidad es un cambio de configuración, sin recompilar y sin tocar el módulo de asignación</td>
<td>Revisión del diseño y una prueba que cambia el cupo y verifica el resultado</td>
</tr>
<tr class="odd">
<td>Flexibilidad, escalabilidad</td>
<td>“Vamos a abrir más sedes”</td>
<td>RNF-08. Al pasar de una a cinco sedes, el tiempo de respuesta de RNF-01 se mantiene con 1.000 pacientes conectados</td>
<td>Prueba de carga con el volumen proyectado</td>
</tr>
<tr class="even">
<td>Seguridad frente a daños, aviso de peligros</td>
<td>“Hubo un paciente grave que pidió turno normal”</td>
<td>RNF-09. Si el paciente marca un síntoma de alarma, la app muestra el aviso de acudir a urgencias antes de asignar cualquier turno, en el 100 % de los casos</td>
<td>Pruebas funcionales de cada síntoma de la lista y revisión clínica de la lista</td>
</tr>
</tbody>
</table>
<p>La fila 9 es diseño ficticio y no una guía clínica. La lista real de síntomas la define un profesional de la salud.</p>
</section>
<section id="los-requisitos-chocan-entre-sí" class="level3">
<h3 class="anchored" data-anchor-id="los-requisitos-chocan-entre-sí">4.8 Los requisitos chocan entre sí</h3>
<p>Las características se estorban entre ellas, y casi todo requisito de calidad cuesta algo en otra característica.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Si subes</th>
<th>Puede costar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Seguridad informática, por ejemplo una doble verificación al ingresar</td>
<td>Capacidad de interacción, porque la paciente de 70 años tarda más</td>
</tr>
<tr class="even">
<td>Eficiencia de desempeño, por ejemplo guardar menos datos para ir más rápido</td>
<td>Recuperabilidad, porque quedan menos copias para recuperar</td>
</tr>
<tr class="odd">
<td>Flexibilidad, por ejemplo soportar muchos entornos</td>
<td>Mantenibilidad, porque hay más combinaciones que probar</td>
</tr>
</tbody>
</table>
<p>No todas las características pesan igual. Se priorizan por riesgo, es decir, por qué tan grave es que fallen y qué tan probable es. En la app de la clínica pesan más la confidencialidad (datos de salud), la disponibilidad y la seguridad frente a daños, y pesan menos la reutilizabilidad o la instalabilidad.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 4. Reescribe tres quejas como requisitos medibles
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para cada queja, escribe un requisito con las cinco piezas. Inventa los números, pero hazlos razonables.</p>
<ol type="1">
<li>“La app debe ser segura.”</li>
<li>“La app tiene que aguantar muchos pacientes.”</li>
<li>“A la gente se le olvida su turno.”</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Tu redacción puede variar. Lo que debe coincidir es la estructura: característica, medida, umbral, condiciones y verificación.</p>
<ol type="1">
<li>“Segura” es demasiado amplio. Hay que escoger una subcaracterística. Por ejemplo, confidencialidad: “Ningún usuario autenticado puede consultar turnos de otro paciente. Se comprueba con una prueba de autorización por rol en cada versión”. Otra opción es resistencia: “Tras 5 intentos fallidos de ingreso en 10 minutos, la cuenta se bloquea y se avisa al titular. Se comprueba con una prueba de seguridad antes del lanzamiento”.</li>
<li>“Muchos” es capacidad. “La app mantiene RNF-01 con 500 pacientes conectados y 50 solicitudes de turno por segundo, con la agenda de un día lleno. Se comprueba con una prueba de carga antes de cada versión”.</li>
<li>Esta queja no es de una característica técnica, es de calidad en uso: la gente no logra su objetivo, que es llegar a su cita. La respuesta puede ser funcional, como un recordatorio: “El 95 % de los turnos asignados genera un recordatorio 24 horas antes, y el 98 % de los recordatorios se envía correctamente. Se comprueba con los registros de envío cada semana”. Fíjate que el requisito mide algo del producto, pero lo que se quiere mejorar es el resultado de la persona.</li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="parte-5.-caso-real-ariane-5-vuelo-501" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="parte-5.-caso-real-ariane-5-vuelo-501"><span class="header-section-number">8</span> Parte 5. Caso real: Ariane 5, vuelo 501</h2>
<p>El caso de este tema es el primer vuelo del cohete Ariane 5. La fuente primaria es el informe de la comisión de investigación, presidida por el profesor J. L. Lions y fechada el 19 de julio de 1996. Aquí se resumen los hechos que el informe afirma, y lo que sigue, el análisis con el modelo, es mío.</p>
<section id="qué-pasó" class="level3">
<h3 class="anchored" data-anchor-id="qué-pasó">5.1 Qué pasó</h3>
<p>El 4 de junio de 1996, el vuelo inaugural del Ariane 5 despegó de Kourou, en la Guayana Francesa. A los 37 segundos de iniciada la secuencia de ignición del motor principal, que son 30 segundos después del despegue, el cohete perdió por completo la información de guía y de actitud. A los 39 segundos se desintegró por fuerzas aerodinámicas, y la autodestrucción se activó sola, como estaba diseñada, a unos 4 kilómetros de altitud.</p>
<p>La comisión concluyó que la pérdida de información se debió a errores de especificación y de diseño en el software del sistema de referencia inercial, el equipo que le dice al cohete cómo está orientado y cómo se mueve.</p>
</section>
<section id="la-cadena-de-causas" class="level3">
<h3 class="anchored" data-anchor-id="la-cadena-de-causas">5.2 La cadena de causas</h3>
<div class="diagrama">
<svg viewbox="0 0 760 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cadena de cinco pasos del vuelo 501 del Ariane 5, desde la reutilizacion del codigo del Ariane 4 hasta la desintegracion del cohete" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="c2c" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#56615A"></path></marker></defs> <text x="380" y="24" text-anchor="middle" font-size="14" font-weight="700" fill="#1F2A24">Vuelo 501: de una decisión de reutilización a un cohete destruido</text> <rect x="8" y="46" width="138" height="190" rx="10" fill="#FDF0D0" stroke="#F2B33D" stroke-width="1.3"></rect> <rect x="156" y="46" width="138" height="190" rx="10" fill="#E3EFFA" stroke="#3B82C4" stroke-width="1.3"></rect> <g fill="#FBE3DB" stroke="#E4572E" stroke-width="1.3"><rect x="304" y="46" width="138" height="190" rx="10"></rect><rect x="452" y="46" width="138" height="190" rx="10"></rect><rect x="600" y="46" width="152" height="190" rx="10"></rect></g> <g fill="none" stroke="#56615A" stroke-width="2" marker-end="url(#c2c)"><path d="M147,140 L153,140"></path><path d="M295,140 L301,140"></path><path d="M443,140 L449,140"></path><path d="M591,140 L597,140"></path></g> <g text-anchor="middle"> <g font-size="12" font-weight="700" fill="#1F2A24"><text x="77" y="70">Decisión</text><text x="225" y="70">Contexto nuevo</text><text x="373" y="70">Defecto</text><text x="521" y="70">Falla</text><text x="676" y="70">Consecuencia</text></g> <g font-size="11" fill="#1F2A24"> <text x="77" y="100">Se reutiliza el</text><text x="77" y="115">software de</text><text x="77" y="130">referencia inercial</text><text x="77" y="145">del Ariane 4,</text><text x="77" y="160">sin revisar si</text><text x="77" y="175">aplica</text> <text x="225" y="100">El Ariane 5 gana</text><text x="225" y="115">velocidad</text><text x="225" y="130">horizontal cinco</text><text x="225" y="145">veces más rápido</text><text x="225" y="160">y el valor BH</text><text x="225" y="175">es mucho mayor</text> <text x="373" y="100">La conversión de</text><text x="373" y="115">BH de 64 bits a</text><text x="373" y="130">16 bits con signo</text><text x="373" y="145">no estaba</text><text x="373" y="160">protegida y se</text><text x="373" y="175">desborda</text> <text x="521" y="100">Las dos unidades,</text><text x="521" y="115">idénticas, se</text><text x="521" y="130">detienen. La</text><text x="521" y="145">activa envía un</text><text x="521" y="160">código de</text><text x="521" y="175">diagnóstico</text> <text x="676" y="100">El computador de a</text><text x="676" y="115">bordo lo lee como</text><text x="676" y="130">datos de vuelo y</text><text x="676" y="145">ordena giros</text><text x="676" y="160">extremos de las</text><text x="676" y="175">toberas. A los 39 s</text><text x="676" y="190">el cohete se rompe</text> </g> <g font-size="11" fill="#56615A"><text x="77" y="222">Proceso</text><text x="225" y="222">Requisito y contexto</text><text x="373" y="222">En el producto</text><text x="521" y="222">Al operar</text><text x="676" y="222">Resultado</text></g> <text x="380" y="264" font-size="12" fill="#56615A">Maíz: decisión de proceso. Azul: contexto y requisito. Rojo: defecto y falla</text> <text x="380" y="286" font-size="12" fill="#56615A">Fuente de los hechos: informe de la comisión de investigación, 19 de julio de 1996</text> </g>
</svg>
</div>
<p>Los detalles que sostienen esta cadena, con su ubicación en el informe.</p>
<ul>
<li>La excepción de software se produjo al convertir un valor de punto flotante de 64 bits en un entero con signo de 16 bits. La variable era BH, el sesgo horizontal, relacionado con la velocidad horizontal que mide la plataforma (sección 2.1).</li>
<li>El módulo que calculaba esa variable solo da resultados útiles antes del despegue. Tras el despegue no sirve para nada, pero siguió funcionando porque era un requisito del Ariane 4 que se mantuvo por razones de uniformidad (sección 2.1).</li>
<li>No todas las conversiones tenían protección. Se había fijado un objetivo máximo de carga del 80 % para el computador, y un análisis dejó tres variables sin proteger por considerar que estaban limitadas físicamente o que tenían un amplio margen. El informe dice que ese razonamiento resultó defectuoso para BH (sección 2.1).</li>
<li>El valor de BH fue mucho mayor de lo esperado porque la primera parte de la trayectoria del Ariane 5 difiere de la del Ariane 4. Su aceleración inicial es alta y la velocidad horizontal se acumula cinco veces más rápido (secciones 2.1 y 3.1).</li>
<li>Los dos equipos, el activo y el de respaldo, eran idénticos en hardware y en software. El de respaldo se detuvo primero, en el ciclo de datos anterior de 72 milisegundos. El activo declaró una falla y dejó de enviar datos de actitud (sección 2.1).</li>
<li>El computador de a bordo interpretó el patrón de diagnóstico de la unidad detenida como datos de vuelo y ordenó desviaciones completas de las toberas. El informe dice que la decisión de detener el procesador fue la que resultó fatal (sección 2.1).</li>
<li>Las pruebas de equipo del sistema de referencia inercial se hicieron con rigor, pero ninguna verificó su comportamiento con la secuencia de cuenta regresiva y la trayectoria del Ariane 5. La especificación no incluía los datos de la trayectoria del Ariane 5 como requisito (sección 2.3).</li>
<li>La comisión describe una cultura del programa que solo trataba las fallas aleatorias de hardware, y por eso la redundancia pensada para ellas no protegió de un defecto de software que las dos unidades compartían (sección 2.2).</li>
</ul>
<p>El informe no da una cifra de pérdida económica. Las cifras que circulan en otras fuentes no están verificadas contra un documento primario, así que aquí no se repiten.</p>
</section>
<section id="análisis-con-el-modelo-de-la-isoiec-250102023" class="level3">
<h3 class="anchored" data-anchor-id="análisis-con-el-modelo-de-la-isoiec-250102023">5.3 Análisis con el modelo de la ISO/IEC 25010:2023</h3>
<p>El informe de 1996 es anterior a esta norma, así que no usa su vocabulario. La tabla es mi lectura del caso con el modelo de 2023.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Hecho del informe</th>
<th>Característica y subcaracterística</th>
<th>Calidad de proceso asociada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Un módulo seguía activo tras el despegue sin cumplir ninguna función útil</td>
<td>Adecuación funcional, pertinencia</td>
<td>Un requisito heredado se mantuvo sin revisar si aplicaba al nuevo cohete</td>
</tr>
<tr class="even">
<td>La conversión se desbordó con un valor que sí podía ocurrir en vuelo</td>
<td>Adecuación funcional, corrección</td>
<td>No se verificó el rango de valores que podía tomar la variable</td>
</tr>
<tr class="odd">
<td>Las dos unidades idénticas fallaron de la misma forma</td>
<td>Fiabilidad, tolerancia a fallos</td>
<td>Se trató la redundancia como protección contra fallas aleatorias de hardware, no contra defectos de software</td>
</tr>
<tr class="even">
<td>La unidad se detuvo en vez de seguir enviando sus mejores datos</td>
<td>Seguridad frente a daños, falla segura</td>
<td>La decisión de detener el procesador ante cualquier excepción no se cuestionó</td>
</tr>
<tr class="odd">
<td>Ninguna prueba usó la trayectoria del Ariane 5</td>
<td>No es una característica</td>
<td>Las pruebas fueron rigurosas, pero con datos que no representaban el contexto nuevo</td>
</tr>
</tbody>
</table>
<p>La última fila es la lección de proceso. El equipo probó, y probó bien, pero con los datos equivocados. Eso muestra, otra vez, que un proceso riguroso no garantiza un producto sin fallas y que la calidad en uso depende del contexto: el mismo software que funcionó bien en el Ariane 4 falló en un contexto distinto.</p>
</section>
<section id="lo-que-el-caso-enseña" class="level3">
<h3 class="anchored" data-anchor-id="lo-que-el-caso-enseña">5.4 Lo que el caso enseña</h3>
<ul>
<li>Reutilizar no exime de revalidar. El código funcionó en el contexto para el que se escribió y dejó de servir cuando el contexto cambió.</li>
<li>Verificar con datos que representen el uso real, no con los datos que ya se tenían.</li>
<li>Una redundancia idéntica protege de una falla aleatoria, no de un defecto que ambas copias comparten.</li>
<li>Un requisito heredado también se revisa. El módulo que no hacía falta en el Ariane 5 fue el que falló.</li>
</ul>
<p>En la clínica, la analogía es directa. Si el equipo reutiliza la app de turnos en una clínica pediátrica, el requisito de “hasta 20 turnos por día” y el límite de longitud de un nombre pueden no servir. Reutilizar exige repasar cada supuesto, no copiar el código.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 5. Analiza otra reutilización
</div>
</div>
<div class="callout-body-container callout-body">
<p>La Clínica Aurora quiere reutilizar su app de turnos para un laboratorio que atiende 400 muestras al día y que agenda por franjas de 10 minutos. Responde sin mirar la solución.</p>
<ol type="1">
<li>Escribe tres supuestos de la app actual que podrían dejar de ser ciertos.</li>
<li>Para cada uno, di qué característica del modelo se vería afectada.</li>
<li>Di qué actividad de proceso habría que hacer antes de reutilizar el código.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Tu lista puede ser distinta. Estos son supuestos razonables.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Supuesto que cambia</th>
<th>Característica afectada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“Hasta 20 turnos por día” cuando ahora son 400</td>
<td>Adecuación funcional, corrección, y eficiencia de desempeño, capacidad</td>
</tr>
<tr class="even">
<td>Los turnos duran un tiempo fijo y no hay franjas de 10 minutos</td>
<td>Adecuación funcional, completitud</td>
</tr>
<tr class="odd">
<td>Los pacientes piden turnos en horario de oficina y ahora hay picos a las 6 de la mañana</td>
<td>Eficiencia de desempeño, comportamiento temporal, y fiabilidad, disponibilidad</td>
</tr>
</tbody>
</table>
<p>La actividad de proceso es la misma que faltó en el Ariane 5: una revisión de los supuestos del código reutilizado contra el contexto nuevo, y pruebas con datos que representen ese contexto.</p>
</div>
</div>
</div>
</section>
</section>
<section id="cierre" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="cierre"><span class="header-section-number">9</span> Cierre</h2>
<section id="lo-que-te-llevas" class="level3">
<h3 class="anchored" data-anchor-id="lo-que-te-llevas">Lo que te llevas</h3>
<div class="checklist">
<p>Al terminar este tema deberías poder explicar sin mirar la guía:</p>
<ul class="task-list">
<li><label><input type="checkbox">La diferencia entre calidad de proceso, de producto y en uso, con un ejemplo de cada una</label></li>
<li><label><input type="checkbox">Por qué un proceso bueno hace más probable un buen producto y no lo garantiza</label></li>
<li><label><input type="checkbox">Las nueve características de la ISO/IEC 25010:2023 y al menos dos subcaracterísticas de cada una</label></li>
<li><label><input type="checkbox">Qué cambió respecto a 2011 y dónde está hoy el modelo de calidad en uso</label></li>
<li><label><input type="checkbox">Las cinco piezas de un requisito de calidad medible</label></li>
<li><label><input type="checkbox">Por qué el percentil 95 dice más que el promedio</label></li>
<li><label><input type="checkbox">Qué falló en el Ariane 5 y cómo se lee con el modelo</label></li>
</ul>
</div>
</section>
<section id="errores-frecuentes" class="level3">
<h3 class="anchored" data-anchor-id="errores-frecuentes">Errores frecuentes</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Error</th>
<th>Corrección</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Decir que la ISO/IEC 25010 tiene ocho características</td>
<td>Son nueve desde 2023. Las ocho eran las de 2011</td>
</tr>
<tr class="even">
<td>Llamar usabilidad y portabilidad a las características de 2023</td>
<td>Se llaman capacidad de interacción y flexibilidad. Usabilidad es una subcaracterística de la calidad en uso</td>
</tr>
<tr class="odd">
<td>Buscar el modelo de calidad en uso dentro de la ISO/IEC 25010</td>
<td>Está en la ISO/IEC 25019:2023</td>
</tr>
<tr class="even">
<td>Confundir security con safety</td>
<td>Seguridad informática protege datos y accesos. Seguridad frente a daños evita que el producto lastime</td>
</tr>
<tr class="odd">
<td>Creer que una certificación de proceso asegura un producto sin fallas</td>
<td>Hace más probable el buen producto. Lo demuestra la medición del producto</td>
</tr>
<tr class="even">
<td>Escribir “rápido” o “seguro” como requisito</td>
<td>Convertirlo en medida, umbral, condiciones y verificación</td>
</tr>
<tr class="odd">
<td>Medir con el promedio</td>
<td>Usar el percentil que represente al usuario que peor lo pasa</td>
</tr>
<tr class="even">
<td>Reutilizar código sin revisar sus supuestos</td>
<td>Revisar el contexto nuevo y verificar con datos que lo representen</td>
</tr>
</tbody>
</table>
</section>
<section id="autoevaluación" class="level3">
<h3 class="anchored" data-anchor-id="autoevaluación">Autoevaluación</h3>
<p>Contesta cada pregunta por escrito antes de abrir la clave. Las respuestas no se guardan.</p>
<p><strong>Pregunta 1.</strong> El equipo de la clínica revisa todo su código y guarda las actas, y aun así entrega una falla. ¿Qué conclusión es la correcta?</p>
<ol type="a">
<li>El proceso de revisión no sirve.</li>
<li>El proceso baja la probabilidad de defectos, pero no la lleva a cero.</li>
<li>La falla prueba que las pruebas son inútiles.</li>
<li>La falla no puede ocurrir en un proceso con actas.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La respuesta es b. Un proceso ordenado hace más probable un buen producto sin asegurarlo, porque siempre queda algo que nadie revisó. Las demás opciones tratan la probabilidad como certeza.</p>
</div>
</div>
</div>
<p><strong>Pregunta 2.</strong> “La lista de turnos carga en 1,8 segundos” es una afirmación de calidad de…</p>
<ol type="a">
<li>proceso.</li>
<li>producto.</li>
<li>uso.</li>
<li>ninguna de las tres.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La respuesta es b. Es una propiedad medible del sistema, en la característica eficiencia de desempeño. No describe cómo trabaja el equipo ni qué logra una persona.</p>
</div>
</div>
</div>
<p><strong>Pregunta 3.</strong> ¿Cuántas características tiene el modelo de producto de la ISO/IEC 25010:2023 y cuál es nueva respecto a 2011?</p>
<ol type="a">
<li>Ocho, y la nueva es fiabilidad.</li>
<li>Nueve, y la nueva es safety, seguridad frente a daños.</li>
<li>Nueve, y la nueva es usabilidad.</li>
<li>Diez, y la nueva es portabilidad.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La respuesta es b. Son nueve, y safety se agregó en 2023. Usabilidad y portabilidad no son nuevas, fueron renombradas como capacidad de interacción y flexibilidad.</p>
</div>
</div>
</div>
<p><strong>Pregunta 4.</strong> ¿Dónde está hoy el modelo de calidad en uso?</p>
<ol type="a">
<li>Dentro de la ISO/IEC 25010:2023.</li>
<li>En la ISO/IEC 25019:2023.</li>
<li>En la ISO 9001.</li>
<li>En la ISO/IEC 25059.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La respuesta es b. La edición de 2011 de la ISO/IEC 25010 lo incluía. La de 2023 lo movió a la ISO/IEC 25019, y por eso muchos textos anteriores a 2023 todavía lo ubican donde ya no está.</p>
</div>
</div>
</div>
<p><strong>Pregunta 5.</strong> “Pedí mi turno y vi el de otra persona.” ¿A qué característica y subcaracterística corresponde?</p>
<ol type="a">
<li>Fiabilidad, disponibilidad.</li>
<li>Seguridad informática, confidencialidad.</li>
<li>Seguridad frente a daños, aviso de peligros.</li>
<li>Adecuación funcional, completitud.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La respuesta es b. Los datos de una persona se mostraron a alguien no autorizado. Es seguridad informática, no seguridad frente a daños, que trata del daño físico o material que causa el producto.</p>
</div>
</div>
</div>
<p><strong>Pregunta 6.</strong> ¿Cuál de estos es un requisito de calidad medible?</p>
<ol type="a">
<li>La app debe ser rápida.</li>
<li>La app debe ser segura y estable.</li>
<li>El 95 % de las consultas de turnos responde en 2 segundos o menos con 200 pacientes conectados, y se comprueba con una prueba de carga.</li>
<li>La app debe cargar sin demoras molestas.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La respuesta es c.&nbsp;Tiene medida (tiempo de respuesta), umbral (2 segundos), porcentaje (95 %), condiciones (200 pacientes) y verificación (prueba de carga). Las otras tres son opiniones.</p>
</div>
</div>
</div>
<p><strong>Pregunta 7.</strong> Diez consultas tardan 1 segundo cada una, excepto una que tarda 12 segundos. El requisito dice “el percentil 95 será de 2 segundos o menos”. ¿Se cumple?</p>
<ol type="a">
<li>Sí, porque el promedio es 2,1 segundos, casi 2.</li>
<li>Sí, porque la mediana es 1 segundo.</li>
<li>No, porque el percentil 95 con diez mediciones es 12 segundos.</li>
<li>No se puede saber con diez mediciones.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La respuesta es c.&nbsp;Con el método del rango más cercano, la posición es la 10 (0,95 por 10, redondeado hacia arriba), y el valor de esa posición es 12. El promedio y la mediana ocultan que una de cada diez personas espera 12 segundos.</p>
</div>
</div>
</div>
<p><strong>Pregunta 8.</strong> En el Ariane 5, las dos unidades de referencia inercial fallaron casi a la vez. ¿Qué característica del modelo estaba en juego?</p>
<ol type="a">
<li>Eficiencia de desempeño, capacidad.</li>
<li>Fiabilidad, tolerancia a fallos.</li>
<li>Compatibilidad, coexistencia.</li>
<li>Flexibilidad, instalabilidad.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La respuesta es b. Las dos unidades eran idénticas en hardware y software, así que compartían el mismo defecto y la redundancia no sirvió. La tolerancia a fallos exige que el sistema siga operando ante una falla, y una copia idéntica no protege de un defecto común.</p>
</div>
</div>
</div>
<p><strong>Pregunta 9.</strong> ¿Qué actividad de proceso habría ayudado más a detectar el problema del Ariane 5 antes del vuelo?</p>
<ol type="a">
<li>Cambiar a unidades redundantes de otro fabricante sin probarlas.</li>
<li>Probar el sistema de referencia inercial con la trayectoria y los datos del Ariane 5.</li>
<li>Aumentar el número de documentos del proyecto.</li>
<li>Reducir las pruebas para ahorrar tiempo.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La respuesta es b. El informe señala que ninguna prueba verificó el comportamiento del equipo con la trayectoria del Ariane 5, y una de sus recomendaciones es hacer pruebas del sistema completo con datos realistas. Las demás opciones no atacan la causa que describe el informe.</p>
</div>
</div>
</div>
<p><strong>Pregunta 10.</strong> La ISO/IEC 25059:2023 es una norma de la familia SQuaRE que…</p>
<ol type="a">
<li>reemplaza a la ISO/IEC 25010:2023.</li>
<li>define un modelo de calidad para sistemas de inteligencia artificial, como extensión de SQuaRE.</li>
<li>certifica a las organizaciones que usan inteligencia artificial.</li>
<li>mide la calidad del proceso de desarrollo.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 10
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La respuesta es b. Es una extensión que agrega propiedades propias de la inteligencia artificial. No reemplaza a la ISO/IEC 25010 ni certifica organizaciones, porque SQuaRE son modelos y guías, no esquemas de certificación.</p>
</div>
</div>
</div>
</section>
<section id="glosario-del-tema" class="level3">
<h3 class="anchored" data-anchor-id="glosario-del-tema">Glosario del tema</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Término</th>
<th>Significado en este tema</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Calidad de proceso</td>
<td>Grado en que las actividades con que se construye el software están definidas, se siguen y se mejoran</td>
</tr>
<tr class="even">
<td>Calidad de producto</td>
<td>Grado en que el software construido cumple sus requisitos, descrita por el modelo de la ISO/IEC 25010</td>
</tr>
<tr class="odd">
<td>Calidad en uso</td>
<td>Resultado que obtiene una persona real al usar el producto en un contexto concreto, modelo de la ISO/IEC 25019</td>
</tr>
<tr class="even">
<td>Modelo de calidad</td>
<td>Conjunto de características y subcaracterísticas que sirve como marco para especificar y evaluar calidad</td>
</tr>
<tr class="odd">
<td>Característica</td>
<td>Atributo amplio de calidad del modelo, como fiabilidad o seguridad informática</td>
</tr>
<tr class="even">
<td>Subcaracterística</td>
<td>Parte concreta de una característica, como disponibilidad dentro de fiabilidad</td>
</tr>
<tr class="odd">
<td>Medida</td>
<td>Cálculo concreto que cuantifica una subcaracterística, como el porcentaje de minutos operativos</td>
</tr>
<tr class="even">
<td>Requisito de calidad</td>
<td>Requisito que dice qué tan bien debe hacer algo el producto, también llamado no funcional</td>
</tr>
<tr class="odd">
<td>Umbral</td>
<td>Valor límite que separa cumplir de no cumplir una medida</td>
</tr>
<tr class="even">
<td>Percentil 95</td>
<td>Valor bajo el cual queda el 95 % de las mediciones, útil para no esconder a quien peor lo pasa</td>
</tr>
<tr class="odd">
<td>Contexto de uso</td>
<td>Usuarios, tareas, equipo y entorno en los que se usa el producto</td>
</tr>
<tr class="even">
<td>SQuaRE</td>
<td>Familia ISO/IEC 25000 de requisitos y evaluación de la calidad de sistemas y software</td>
</tr>
<tr class="odd">
<td>ISO/IEC 25010:2023</td>
<td>Norma del modelo de calidad de producto, con nueve características</td>
</tr>
<tr class="even">
<td>ISO/IEC 25019:2023</td>
<td>Norma del modelo de calidad en uso, con tres características</td>
</tr>
<tr class="odd">
<td>ISO/IEC 25059:2023</td>
<td>Extensión de SQuaRE con un modelo de calidad para sistemas de inteligencia artificial</td>
</tr>
<tr class="even">
<td>Capacidad de interacción</td>
<td>Característica que en 2011 se llamaba usabilidad</td>
</tr>
<tr class="odd">
<td>Flexibilidad</td>
<td>Característica que en 2011 se llamaba portabilidad</td>
</tr>
<tr class="even">
<td>Seguridad informática</td>
<td>Traducción de <em>security</em>, protección de datos y accesos</td>
</tr>
<tr class="odd">
<td>Seguridad frente a daños</td>
<td>Traducción de <em>safety</em>, evitar que el producto cause daño a personas, bienes o entorno</td>
</tr>
<tr class="even">
<td>Tolerancia a fallos</td>
<td>Capacidad de seguir operando aunque haya fallas de hardware o de software</td>
</tr>
<tr class="odd">
<td>Redundancia</td>
<td>Duplicar un componente para que un respaldo tome el control si falla el principal</td>
</tr>
<tr class="even">
<td>Falla segura</td>
<td>Pasar a un estado seguro cuando algo falla</td>
</tr>
<tr class="odd">
<td>Inclusividad</td>
<td>Que el producto pueda ser usado por la más amplia gama de personas</td>
</tr>
<tr class="even">
<td>Contexto heredado</td>
<td>Requisito o código que viene de un producto anterior y debe revisarse antes de reutilizarse</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="lo-que-sigue" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="lo-que-sigue"><span class="header-section-number">10</span> Lo que sigue</h2>
<p>Hoy viste de qué se compone la calidad de un producto y cómo se escribe un requisito que se pueda exigir. El Tema 3 pregunta por qué le importa esto a un negocio, cuánto cuesta ignorarla y cómo cambia el panorama cuando el software se produce y se vende entre países. Ahí aparecen los demás casos reales del curso y las cifras de costo, con el mismo cuidado por la fuente que usamos aquí.</p>
</section>
<section id="bibliografía" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="bibliografía"><span class="header-section-number">11</span> Bibliografía</h2>
<ul>
<li>ISO/IEC 25010:2023. <em>Systems and software engineering. Systems and software Quality Requirements and Evaluation (SQuaRE). Product quality model.</em> Segunda edición, noviembre de 2023. <a href="https://www.iso.org/standard/78176.html">Ficha</a>. Vista previa gratuita con prefacio e introducción: <a href="https://assets.vde-verlag.de/iec-normen/preview-pdf/info_isoiec25010%7Bed2.0%7Den.pdf">PDF</a>.</li>
<li>ISO/IEC 25010:2011. <em>Systems and software engineering. SQuaRE. System and software quality models.</em> Edición histórica, cancelada por la de 2023. <a href="https://www.iso.org/standard/35733.html">Ficha</a>.</li>
<li>ISO/IEC 25019:2023. <em>SQuaRE. Quality-in-use model.</em> Noviembre de 2023. <a href="https://www.iso.org/standard/78177.html">Ficha</a>.</li>
<li>ISO/IEC 25059:2023. <em>Software engineering. SQuaRE. Quality model for AI systems.</em> <a href="https://www.iso.org/standard/80655.html">Ficha</a>.</li>
<li>ISO/IEC 25002:2024. <em>SQuaRE. Quality model overview and usage.</em> <a href="https://www.iso.org/standard/78175.html">Ficha</a>.</li>
<li>ISO/IEC 25030:2019. <em>SQuaRE. Quality requirements framework.</em> <a href="https://www.iso.org/standard/72116.html">Ficha</a>.</li>
<li>ISO/IEC 25023:2016. <em>SQuaRE. Measurement of system and software product quality.</em> <a href="https://www.iso.org/standard/35747.html">Ficha</a>.</li>
<li>ISO/IEC 25040:2024. <em>SQuaRE. Quality evaluation framework.</em> <a href="https://www.iso.org/standard/83467.html">Ficha</a>.</li>
<li>ISO/IEC/IEEE 29148:2018. <em>Systems and software engineering. Life cycle processes. Requirements engineering.</em> <a href="https://www.iso.org/standard/72089.html">Ficha</a>.</li>
<li>ISO/IEC/IEEE 24765:2017. <em>Systems and software engineering. Vocabulary.</em> <a href="https://www.iso.org/standard/71952.html">Ficha</a>.</li>
<li>Lions, J. L. y otros (1996). <em>Ariane 5. Flight 501 Failure. Report by the Inquiry Board.</em> París, 19 de julio de 1996. Copias públicas: <a href="https://ocw.mit.edu/courses/16-355j-software-engineering-concepts-fall-2005/91f1e550b30b00ad797293f430220f18_ari5fail_ful_rep.pdf">MIT OpenCourseWare</a> y <a href="https://www-users.cse.umn.edu/~arnold/disasters/ariane5rep.html">Universidad de Minnesota</a>.</li>
<li>W3C (2023). <em>Web Content Accessibility Guidelines (WCAG) 2.2.</em> <a href="https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/">Novedades</a>.</li>
<li>Congreso de Colombia (2012). <em>Ley Estatutaria 1581 de 2012, por la cual se dictan disposiciones generales para la protección de datos personales.</em> <a href="https://www.saludcapital.gov.co/Normo/gsp/ley_1581_de_2012.pdf">Texto</a>.</li>
<li>Bass, L., Clements, P. y Kazman, R. (2021). <em>Software Architecture in Practice.</em> Cuarta edición. Addison-Wesley.</li>
<li>Sommerville, I. <em>Ingeniería de software.</em> Pearson. Capítulos sobre gestión de la calidad.</li>
<li>Pressman, R. S. <em>Ingeniería del software. Un enfoque práctico.</em> McGraw-Hill.</li>
<li>Galin, D. <em>Software Quality: Concepts and Practice.</em> Wiley-IEEE.</li>
</ul>
<div class="pie-doc">
<p>Calidad del software (CDS01). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>