<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 1. Datos, información y el archivo que se queda corto – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-9d905b06f1e8b96cef5de7dac512495c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-01/index.html">Unidad 1. Introducción a los sistemas de bases de datos</a></li><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-01/tema-01-datos-informacion-conocimiento/index.html">Tema 1. Datos, información y el archivo que se queda corto</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Introducción a los sistemas de bases de datos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-01/tema-01-datos-informacion-conocimiento/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 1. Datos, información y el archivo que se queda corto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-01/tema-02-integracion-organizacional/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Una base de datos, toda la empresa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/actividad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Actividad 1. Profundicen la Unidad 1</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Modelo entidad relación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-02/tema-01-componentes-mer/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Las piezas con las que se dibuja la realidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-02/tema-02-representacion-cardinalidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. El dibujo que decide la llave foránea</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 3. Modelo relacional</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-03/tema-01-de-er-a-relacional/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Seis reglas para convertir el diagrama en tablas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-03/tema-02-formas-normalizacion/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. El teléfono de Ana, resuelto en cuatro pasos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../base-de-datos/unidad-03/tema-03-diseno-tablas-integridad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. La tabla que vigila sus propias reglas, y las que se le escapan</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#la-escalera-de-dato-a-sabiduría" id="toc-la-escalera-de-dato-a-sabiduría" class="nav-link active" data-scroll-target="#la-escalera-de-dato-a-sabiduría"><span class="header-section-number">1</span> La escalera de dato a sabiduría</a></li>
  <li><a href="#el-procesamiento-por-archivos-antes-del-sgbd" id="toc-el-procesamiento-por-archivos-antes-del-sgbd" class="nav-link" data-scroll-target="#el-procesamiento-por-archivos-antes-del-sgbd"><span class="header-section-number">2</span> El procesamiento por archivos antes del SGBD</a>
  <ul class="collapse">
  <li><a href="#las-tres-anomalías-con-nombre-propio" id="toc-las-tres-anomalías-con-nombre-propio" class="nav-link" data-scroll-target="#las-tres-anomalías-con-nombre-propio">Las tres anomalías, con nombre propio</a></li>
  </ul></li>
  <li><a href="#lo-que-resuelve-el-sgbd" id="toc-lo-que-resuelve-el-sgbd" class="nav-link" data-scroll-target="#lo-que-resuelve-el-sgbd"><span class="header-section-number">3</span> Lo que resuelve el SGBD</a></li>
  <li><a href="#caso-de-estudio.-por-qué-american-airlines-dejó-de-usar-tableros-manuales" id="toc-caso-de-estudio.-por-qué-american-airlines-dejó-de-usar-tableros-manuales" class="nav-link" data-scroll-target="#caso-de-estudio.-por-qué-american-airlines-dejó-de-usar-tableros-manuales"><span class="header-section-number">4</span> Caso de estudio. Por qué American Airlines dejó de usar tableros manuales</a></li>
  <li><a href="#cuando-el-sgbd-tampoco-basta-por-sí-solo" id="toc-cuando-el-sgbd-tampoco-basta-por-sí-solo" class="nav-link" data-scroll-target="#cuando-el-sgbd-tampoco-basta-por-sí-solo"><span class="header-section-number">5</span> Cuando el SGBD tampoco basta por sí solo</a></li>
  <li><a href="#lo-que-te-llevas-de-hoy" id="toc-lo-que-te-llevas-de-hoy" class="nav-link" data-scroll-target="#lo-que-te-llevas-de-hoy"><span class="header-section-number">6</span> Lo que te llevas de hoy</a></li>
  <li><a href="#lo-que-sigue" id="toc-lo-que-sigue" class="nav-link" data-scroll-target="#lo-que-sigue"><span class="header-section-number">7</span> Lo que sigue</a></li>
  <li><a href="#recursos" id="toc-recursos" class="nav-link" data-scroll-target="#recursos"><span class="header-section-number">8</span> Recursos</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-01/index.html">Unidad 1. Introducción a los sistemas de bases de datos</a></li><li class="breadcrumb-item"><a href="../../../base-de-datos/unidad-01/tema-01-datos-informacion-conocimiento/index.html">Tema 1. Datos, información y el archivo que se queda corto</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 1. Datos, información y el archivo que se queda corto</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">17 de agosto de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 90%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 1. Introducción a los sistemas de bases de datos</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 1. Datos, información, conocimiento y bases de datos frente a sistemas de archivos</td>
</tr>
</tbody>
</table>
</div>
<p>Un <em>sistema gestor de bases de datos</em>, o SGBD (en inglés <em>database management system</em>, DBMS), es el software que crea, organiza y controla el acceso a una base de datos: decide dónde y cómo se guarda cada dato, quién puede leerlo o modificarlo, y cómo se recupera esa información sin perder consistencia. Vas a ver esas dos siglas, SGBD y DBMS, usadas indistintamente en el resto del curso y en la documentación técnica, así que conviene familiarizarse con ambas desde ahora.</p>
<p>Esta unidad abre el curso desde la pregunta más básica de todas, que es por qué existe algo llamado base de datos si toda organización ya tenía archivos antes de que ese nombre se pusiera de moda. Hoy separas tres palabras que se usan como si fueran sinónimos, dato, información y conocimiento, y después revisas qué problemas concretos tenía el procesamiento por archivos y qué características concretas trajo el SGBD para resolverlos. Cierra el tema con dos casos reales, uno que muestra por qué una organización entera decidió dejar los archivos sueltos, y otro que muestra que ni siquiera tener un SGBD garantiza que el problema desaparezca del todo si el diseño o la gobernanza de los datos fallan.</p>
<section id="la-escalera-de-dato-a-sabiduría" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="la-escalera-de-dato-a-sabiduría"><span class="header-section-number">1</span> La escalera de dato a sabiduría</h2>
<p>El modelo académico de referencia para separar estas palabras se llama DIKW, sigla en inglés de <em>Data, Information, Knowledge, Wisdom</em>, y su versión más citada la formalizó Russell L. Ackoff en el artículo <em>From Data to Wisdom</em> (1989), que originalmente fue un discurso presidencial ante la International Society for General Systems Research en 1988. Ackoff abre el texto con una frase que resume la idea completa: “An ounce of information is worth a pound of data. An ounce of knowledge is worth a pound of information. An ounce of understanding is worth a pound of knowledge.” Traducida, dice que una onza de información vale una libra de datos, que una onza de conocimiento vale una libra de información y que una onza de entendimiento vale una libra de conocimiento. Lo que Ackoff está diciendo con esa comparación de pesos es que cantidad y valor no son lo mismo, ya que subir un peldaño en la escalera compacta muchísima cantidad del peldaño anterior en algo mucho más útil, aunque pese menos y ocupe menos espacio.</p>
<div class="diagrama">
<svg viewbox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Escalera de cuatro peldaños ascendentes de dato a información, de información a conocimiento y de conocimiento a sabiduría, con un ejemplo de clima y ventas en cada peldaño" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="base1a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Cada peldaño compacta y da más valor que una gran cantidad del anterior</text> <rect x="10" y="212" width="170" height="68" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <rect x="205" y="152" width="170" height="68" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="400" y="92" width="170" height="68" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="595" y="32" width="155" height="68" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g fill="none" stroke="#8fb3d1" stroke-width="2" marker-end="url(#base1a)"> <path d="M182,238 C196,238 194,196 203,190"></path> <path d="M377,178 C391,178 389,136 398,130"></path> <path d="M572,118 C586,118 584,76 593,70"></path> </g> <g text-anchor="middle"> <g font-size="14.5" font-weight="700" fill="#12324f"> <text x="95" y="238">Dato</text> <text x="290" y="178">Información</text> <text x="485" y="118">Conocimiento</text> </g> <text x="672" y="58" font-size="14.5" font-weight="700" fill="#0e6f6c">Sabiduría</text> <g font-size="11" fill="#5b6876"> <text x="95" y="258">23 grados, un</text> <text x="95" y="272">número suelto</text> <text x="290" y="198">En Medellín son 23</text> <text x="290" y="212">grados a las 3 pm</text> <text x="485" y="138">Los martes se vende menos</text> <text x="485" y="152">bebida caliente que los viernes</text> </g> <g font-size="11" fill="#3c7d7a"> <text x="672" y="78">Reducir el turno de</text> <text x="672" y="90">café caliente los martes</text> </g> </g>
</svg>
</div>
<p>Cada peldaño se puede definir con precisión. El <em>dato</em> es un símbolo o un hecho bruto que no trae contexto propio, como la cifra veintitrés sola. La <em>información</em> es ese mismo dato organizado y puesto en contexto, la que responde preguntas de qué, quién, dónde o cuándo, como en la temperatura en Medellín a las tres de la tarde son veintitrés grados. El <em>conocimiento</em> es información comprendida y aplicable gracias a la experiencia y el análisis, el saber-cómo que aparece cuando alguien compara muchos casos de información y encuentra un patrón, como que los martes bajan las ventas de bebida caliente frente a los viernes. La <em>sabiduría</em> es el peldaño más alto y también el más discutido en la literatura, ya que implica aplicar ese conocimiento con juicio, con criterio y con visión de las consecuencias, como decidir reducir el turno de café caliente un día y ampliarlo otro.</p>
<p>Conviene fijar aquí una definición normativa que complementa la de Ackoff con precisión de ingeniería, porque no viene de la literatura de gestión sino de un estándar técnico. El vocabulario conjunto ISO/IEC 2382 define el dato como una representación reinterpretable de información, hecha de manera formalizada para que se pueda comunicar, interpretar o procesar. Esa definición separa con claridad lo que es el dato, la representación formal, de lo que es la información, el significado que alguien le atribuye a esa representación, y es la que vas a usar durante todo el curso cuando hables del contenido que guarda una base de datos.</p>
<p>Vale la pena cerrar esta sección con dos precisiones que la literatura discute y que conviene conocer antes de repetir el modelo sin pensarlo. La primera es que la idea de que dato, información y conocimiento se construyen unos sobre otros no nació con Ackoff, sino que Nicholas L. Henry la planteó antes, en 1974, y que la forma de pirámide con la que casi siempre se dibuja este modelo es una convención posterior de la literatura de gestión del conocimiento, ya que ni Ackoff ni Milan Zeleny, a quienes se les suele acreditar la forma piramidal, la usaron literalmente en sus textos originales. La segunda es una crítica seria al modelo completo, la que hace el escritor David Weinberger, quien argumenta que hay una discontinuidad real entre el dato y la información, que viven cómodos dentro de una computadora, y el conocimiento y la sabiduría, que dependen de una persona y de su experiencia, así que tratar los cuatro niveles como si subieran por la misma escalera automática simplifica demasiado cómo se construye el conocimiento en la práctica. Esa crítica es justamente la razón por la que, más adelante en este tema, vas a ver que un sistema gestor de base de datos puede resolver los problemas del dato y de la información sin que eso garantice, por sí solo, que la organización tome mejores decisiones.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Ubica el peldaño
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para cada frase, marca en cuál peldaño de la escalera encaja mejor antes de seguir leyendo.</p>
<p><label><input type="checkbox"> “4500” aparece en una columna llamada valor</label><br> <label><input type="checkbox"> “El pedido 1002 costó 23400 pesos el martes 12 de agosto”</label><br> <label><input type="checkbox"> “Los pedidos de café bajan un 30 por ciento los martes frente a los viernes, según los últimos tres meses”</label><br> <label><input type="checkbox"> “Vamos a mover al barista de turno del martes al viernes, porque ahí es donde de verdad se necesita”</label></p>
<p>Escribe junto a cada frase si es dato, información, conocimiento o sabiduría, y explica en una línea que le falta a cada una para subir al siguiente peldaño.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La primera frase es un dato, porque es un número suelto sin contexto que le diga a qué corresponde ni cuándo ocurrió. Le falta contexto para subir a información.</p>
<p>La segunda frase ya es información, porque el mismo número aparece con contexto completo, que pedido, que valor y que día, y responde preguntas concretas de qué, cuándo y cuánto. Le falta comparación con otros casos para subir a conocimiento.</p>
<p>La tercera frase es conocimiento, porque compara muchos casos de información a lo largo de tres meses y encuentra un patrón que se repite. Le falta que alguien decida actuar sobre ese patrón para subir a sabiduría.</p>
<p>La cuarta frase es sabiduría, porque alguien aplica el patrón encontrado con un criterio de consecuencias, mover un turno de trabajo, y esa decisión ya no la toma ningún motor de base de datos, la toma una persona.</p>
</div>
</div>
</div>
</section>
<section id="el-procesamiento-por-archivos-antes-del-sgbd" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="el-procesamiento-por-archivos-antes-del-sgbd"><span class="header-section-number">2</span> El procesamiento por archivos antes del SGBD</h2>
<p>Antes de que existieran los sistemas gestores de bases de datos, entre las décadas de 1960 y 1970, cada aplicación de una organización mantenía su propio archivo maestro independiente, la nómina en un archivo, las matrículas en otro, el inventario en un tercero, cada uno procesado por programas hechos a la medida para ese archivo específico. Piensa en una cafetería del campus que empieza a organizarse así, con tres personas que llevan tres cosas distintas, quien vende anota los pedidos en su propia hoja, quien cobra lleva las cuentas pendientes en la suya y quien atiende reclamos guarda los datos de contacto en una tercera.</p>
<p>Antes de ver que pasa en la práctica, conviene plantearse una pregunta de análisis. Si el mismo cliente, con el mismo teléfono, tiene que quedar registrado en las tres hojas porque cada área necesita saber quién es, que tendría que existir en ese sistema de hojas sueltas para que las tres queden de acuerdo el día que ese cliente cambie de número.</p>
<p>La respuesta es que no existe nada que las mantenga de acuerdo, porque ninguna de las tres personas sabe que las otras dos ya escribieron ese mismo dato antes. El mismo cliente termina escrito por separado en las tres hojas, y cuando Ana cambia de teléfono, como muestra el diagrama siguiente, alguna de las tres queda desactualizada sin que nada en el sistema avise del desacuerdo.</p>
<div class="diagrama">
<svg viewbox="0 0 760 260" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Tres áreas de la cafetería, ventas, cartera y servicio, cada una con su propio archivo; ventas y cartera muestran el teléfono antiguo del cliente y servicio muestra el teléfono ya actualizado, sin que las otras dos se enteren" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Un mismo dato repetido en tres archivos independientes</text> <g fill="#eef4fa" stroke="#c7d6e6"> <rect x="20" y="60" width="215" height="100" rx="10"></rect> <rect x="272" y="60" width="215" height="100" rx="10"></rect> </g> <rect x="524" y="60" width="215" height="100" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g text-anchor="middle" font-size="13.5" font-weight="600" fill="#12324f"> <text x="127" y="84">Archivo de Ventas</text> <text x="379" y="84">Archivo de Cartera</text> </g> <text x="631" y="84" font-size="13.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Archivo de Servicio</text> <g text-anchor="middle" font-size="12" fill="#5b6876"> <text x="127" y="112">cliente: Ana Ruiz</text> <text x="127" y="130">teléfono: 300 111 2233</text> <text x="379" y="112">cliente: Ana Ruiz</text> <text x="379" y="130">teléfono: 300 111 2233</text> </g> <g text-anchor="middle" font-size="12" fill="#3c7d7a"> <text x="631" y="112">cliente: Ana Ruiz</text> <text x="631" y="130">teléfono: 300 111 9999</text> </g> <g text-anchor="middle" font-size="11" fill="#5b6876"> <text x="127" y="148">sin actualizar</text> <text x="379" y="148">sin actualizar</text> </g> <text x="631" y="148" font-size="11" font-weight="600" fill="#0e6f6c" text-anchor="middle">recién actualizado</text> <text x="380" y="196" font-size="12.5" fill="#12324f" text-anchor="middle">Ana cambió de teléfono y solo Servicio lo corrigió.</text> <text x="380" y="216" font-size="12.5" fill="#12324f" text-anchor="middle">Ventas y Cartera siguen mostrando el número viejo, y nada en el sistema avisa del desacuerdo.</text>
</svg>
</div>
<p>Ese desacuerdo entre tres copias del mismo dato no es un accidente raro, es el primero de una lista de problemas bien documentada en la bibliografía del curso. Silberschatz, Korth y Sudarshan, en el capítulo introductorio de <em>Fundamentos de bases de datos</em>, describen siete problemas del procesamiento por archivos que conviene conocer con el mismo nombre que usan los libros de texto, porque son el vocabulario que vas a encontrar en cualquier discusión técnica sobre el tema.</p>
<ul>
<li><strong>Redundancia e inconsistencia de datos.</strong> Los mismos datos se repiten en varios archivos con formatos distintos, y cuando se actualiza una copia sin actualizar las demás, los datos quedan inconsistentes entre sí, exactamente lo que le pasó al teléfono de Ana en el diagrama de arriba.</li>
<li><strong>Dificultad para acceder a los datos.</strong> Cada necesidad de consulta nueva obliga a escribir un programa nuevo, porque no existe una forma flexible de preguntarle algo al sistema que nadie anticipó de antemano.</li>
<li><strong>Aislamiento de datos.</strong> Los datos quedan dispersos en archivos de formatos distintos, escritos por programas distintos, lo que dificulta escribir un programa que necesite combinar información de más de un archivo a la vez.</li>
<li><strong>Problemas de integridad.</strong> Las restricciones sobre los datos, como que el saldo de una cuenta no puede ser negativo, quedan enterradas dentro del código de cada programa de aplicación en vez de declararse una sola vez en un lugar visible, lo que hace difícil añadirlas o cambiarlas después.</li>
<li><strong>Problemas de atomicidad.</strong> Si el sistema falla a mitad de una operación compuesta, como una transferencia entre dos cuentas bancarias que debe restar de una y sumar a la otra, puede quedar en un estado a medias, con la resta aplicada y la suma no.</li>
<li><strong>Anomalías de acceso concurrente.</strong> En archivos tradicionales, varios programas solo pueden acceder al mismo archivo al tiempo si todos leen sin escribir, porque el acceso concurrente de escritura sin control produce condiciones de carrera donde una escritura pisa a la otra.</li>
<li><strong>Problemas de seguridad.</strong> No todos los usuarios de un sistema deberían poder ver todos los datos, pero en archivos sueltos es difícil aplicar controles de acceso finos, ya que suelen quedar atados al sistema operativo de archivos entero y no al contenido específico de cada dato.</li>
</ul>
<p>Connolly y Begg, en <em>Database Systems: A Practical Approach</em>, resumen el mismo diagnóstico con otro énfasis, centrado en cómo cada departamento de una organización termina trabajando aislado de los demás. Ellos hablan de separación y aislamiento de los datos, porque cada programa mantiene su propio conjunto de datos sin que los usuarios de un programa sepan que datos útiles guarda otro programa distinto de la misma organización. Hablan también de duplicación de datos, porque el enfoque descentralizado hace que el mismo dato se mantenga por separado en varios programas, lo que desperdicia espacio de almacenamiento y abre la puerta a que ese dato termine con valores distintos en cada copia. Y hablan de dependencia de los datos, porque la estructura de cada archivo queda escrita dentro del código del programa que lo usa, así que cambiar esa estructura más adelante obliga a modificar cada programa que la toca, uno por uno.</p>
<section id="las-tres-anomalías-con-nombre-propio" class="level3">
<h3 class="anchored" data-anchor-id="las-tres-anomalías-con-nombre-propio">Las tres anomalías, con nombre propio</h3>
<p>De esos problemas nacen tres formas concretas en que una tabla mal diseñada falla en la práctica, y aunque el nombre técnico completo se formaliza más adelante en la Unidad 3 sobre normalización, la raíz conceptual está aquí, en la comparación entre archivo y base de datos.</p>
<div class="diagrama">
<svg viewbox="0 0 760 260" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Un dato duplicado en varias filas de una tabla provoca tres anomalías distintas: de inserción, de actualización y de borrado" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="base1b" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <rect x="290" y="16" width="180" height="52" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="380" y="38" font-size="12.5" font-weight="600" fill="#12324f" text-anchor="middle">Dato duplicado en</text> <text x="380" y="56" font-size="12.5" font-weight="600" fill="#12324f" text-anchor="middle">varias filas de una tabla</text> <g fill="none" stroke="#8fb3d1" stroke-width="2" marker-end="url(#base1b)"> <path d="M330,68 C230,110 140,130 120,158"></path> <path d="M380,68 L380,158"></path> <path d="M430,68 C530,110 620,130 640,158"></path> </g> <g fill="#eef4fa" stroke="#c7d6e6"> <rect x="20" y="160" width="200" height="86" rx="10"></rect> <rect x="280" y="160" width="200" height="86" rx="10"></rect> <rect x="540" y="160" width="200" height="86" rx="10"></rect> </g> <g text-anchor="middle" font-size="13" font-weight="700" fill="#0e6f6c"> <text x="120" y="184">Inserción</text> <text x="380" y="184">Actualización</text> <text x="640" y="184">Borrado</text> </g> <g text-anchor="middle" font-size="11" fill="#5b6876"> <text x="120" y="206">Un cliente nuevo no</text> <text x="120" y="220">existe hasta que hace</text> <text x="120" y="234">su primer pedido</text> <text x="380" y="206">Cambiar un teléfono</text> <text x="380" y="220">obliga a corregir</text> <text x="380" y="234">varias filas a la vez</text> <text x="640" y="206">Borrar un pedido borra</text> <text x="640" y="220">también datos de un</text> <text x="640" y="234">cliente que sigue activo</text> </g>
</svg>
</div>
<p>La <em>anomalía de inserción</em> aparece cuando no se puede registrar un dato nuevo sin que dependa artificialmente de la existencia de otro, como no poder guardar los datos de un cliente hasta que haya hecho al menos un pedido, si ambos datos viven forzados dentro de la misma fila. La <em>anomalía de actualización</em> es justo lo que le pasó al teléfono de Ana, aparece cuando un dato duplicado en varias filas se corrige en unas y se olvida en otras, dejando el sistema en un estado inconsistente sin que nadie lo haya querido así. La <em>anomalía de borrado</em> aparece cuando eliminar una fila hace desaparecer, de paso, un dato que en realidad era independiente de esa fila, como perder el único registro del teléfono de un cliente porque se borró su único pedido.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. La tabla de la cafetería
</div>
</div>
<div class="callout-body-container callout-body">
<p>La cafetería decidió juntar todo en una sola tabla, sin separar clientes, pedidos y productos. Esta es la tabla:</p>
<div class="tabla-ancha">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Pedido</th>
<th>Cliente</th>
<th>Teléfono</th>
<th>Producto</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1001</td>
<td>Ana Ruiz</td>
<td>300 111 2233</td>
<td>Café</td>
<td>4500</td>
</tr>
<tr class="even">
<td>1002</td>
<td>Ana Ruiz</td>
<td>300 111 2233</td>
<td>Torta</td>
<td>23400</td>
</tr>
<tr class="odd">
<td>1003</td>
<td>Luis Pena</td>
<td>301 444 5566</td>
<td>Café</td>
<td>4500</td>
</tr>
<tr class="even">
<td>1004</td>
<td>Ana Ruiz</td>
<td>300 111 2233</td>
<td>Jugo</td>
<td>6800</td>
</tr>
</tbody>
</table>
</div>
<p>Responde las tres preguntas mirando solo la tabla, sin saber nada más de bases de datos todavía.</p>
<ol type="1">
<li>Ana cambia de teléfono. Cuántas filas hay que corregir, y qué pasa si alguien corrige dos y se le olvida la tercera.</li>
<li>Llega un cliente nuevo que todavía no ha pedido nada. Dónde lo guardan.</li>
<li>Se anula el pedido 1003 y se borra la fila. Qué información se pierde además del pedido mismo.</li>
</ol>
<p>Para cada respuesta, nombra cuál de las tres anomalías está ocurriendo, inserción, actualización o borrado.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Pregunta 1, anomalía de actualización. El teléfono de Ana aparece en tres filas, la 1001, la 1002 y la 1004, así que corregirlo obliga a tocar las tres. Si alguien corrige dos y olvida la tercera, la tabla queda con dos teléfonos distintos para la misma persona, y nada en la estructura de la tabla avisa de esa contradicción.</p>
<p>Pregunta 2, anomalía de inserción. No hay ninguna fila donde poner solo los datos de un cliente nuevo, porque cada fila exige también un pedido, un producto y un valor. El cliente nuevo se queda sin registrar hasta que compre algo, aunque ya sea un cliente real.</p>
<p>Pregunta 3, anomalía de borrado. Luis Pena solo aparece en la fila del pedido 1003. Al borrar esa fila desaparece también el único registro de que Luis Pena existe como cliente, aunque el pedido y el cliente sean conceptualmente dos cosas distintas.</p>
</div>
</div>
</div>
</section>
</section>
<section id="lo-que-resuelve-el-sgbd" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="lo-que-resuelve-el-sgbd"><span class="header-section-number">3</span> Lo que resuelve el SGBD</h2>
<p>Cada problema del procesamiento por archivos tiene una contraparte directa en el enfoque de bases de datos. La siguiente tabla empareja cada problema del archivo con la característica concreta del SGBD que lo resuelve.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Problema del procesamiento por archivos</th>
<th>Cómo lo resuelve el enfoque de bases de datos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Redundancia e inconsistencia de datos</td>
<td>Naturaleza autodescriptiva: el catálogo del SGBD guarda la estructura una sola vez, sin repetirla en cada programa</td>
</tr>
<tr class="even">
<td>Dificultad para acceder a los datos</td>
<td>Un lenguaje de consulta declarativo permite pedir datos sin escribir un programa nuevo cada vez</td>
</tr>
<tr class="odd">
<td>Aislamiento de datos</td>
<td>Arquitectura de tres esquemas, que reúne toda la información bajo una sola estructura conceptual</td>
</tr>
<tr class="even">
<td>Problemas de integridad</td>
<td>Las restricciones se declaran una sola vez en el esquema conceptual, no dentro de cada programa</td>
</tr>
<tr class="odd">
<td>Problemas de atomicidad</td>
<td>El SGBD agrupa varias operaciones en una transacción que se aplica entera o no se aplica</td>
</tr>
<tr class="even">
<td>Anomalías de acceso concurrente</td>
<td>El SGBD controla el orden de los accesos simultáneos para que unos no pisen a otros</td>
</tr>
<tr class="odd">
<td>Problemas de seguridad</td>
<td>El control de acceso se define sobre el contenido de los datos, no sobre el sistema operativo</td>
</tr>
</tbody>
</table>
<p>Dos de esas características merecen más detalle porque son las que de verdad distinguen a un SGBD de cualquier otro programa que guarde archivos. La primera es la <em>naturaleza autodescriptiva</em>, que significa que el catálogo del SGBD almacena la descripción completa de la base de datos, sus estructuras, sus tipos y sus restricciones, lo que permite que el mismo software de SGBD trabaje con bases de datos distintas y con aplicaciones distintas, algo que un sistema de archivos no ofrece, porque ahí la descripción de los datos queda implícita, escrita a mano dentro del código de cada aplicación.</p>
<p>La segunda es la <em>independencia entre programas y datos</em>, que es posible gracias a la arquitectura de tres esquemas que también describen Elmasri y Navathe. El nivel interno define las estructuras físicas de almacenamiento, cómo está organizado el dato en disco. El nivel conceptual define la estructura y las restricciones de toda la base de datos para la comunidad completa de usuarios, sin importar cómo se guarde físicamente ni quien la use después. El nivel externo define vistas particulares para distintos grupos de usuarios, cada uno viendo solo lo que le corresponde.</p>
<div class="diagrama">
<svg viewbox="0 0 700 320" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Arquitectura de tres esquemas: nivel externo con varias vistas de usuario arriba, nivel conceptual en medio con toda la estructura y las reglas, nivel interno abajo con el almacenamiento físico; la independencia lógica protege las vistas de cambios en el conceptual y la independencia física protege el conceptual de cambios en el interno" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="base1c" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <text x="350" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">La arquitectura de tres esquemas de Elmasri y Navathe</text> <g fill="#eef4fa" stroke="#c7d6e6"> <rect x="20" y="32" width="150" height="56" rx="9"></rect> <rect x="275" y="32" width="150" height="56" rx="9"></rect> <rect x="530" y="32" width="150" height="56" rx="9"></rect> </g> <g text-anchor="middle" font-size="12" font-weight="600" fill="#12324f"> <text x="95" y="56">Vista contabilidad</text> <text x="350" y="56">Vista ventas</text> <text x="605" y="56">Vista soporte</text> </g> <text x="350" y="106" font-size="12" font-weight="700" fill="#0e6f6c" text-anchor="middle">Nivel externo</text> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#base1c)"> <path d="M95,88 L95,148"></path> <path d="M350,88 L350,148"></path> <path d="M605,88 L605,148"></path> </g> <rect x="140" y="150" width="420" height="66" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="350" y="176" font-size="14" font-weight="700" fill="#0e6f6c" text-anchor="middle">Nivel conceptual</text> <text x="350" y="196" font-size="11.5" fill="#3c7d7a" text-anchor="middle">toda la estructura y las reglas de negocio, para toda la comunidad de usuarios</text> <text x="30" y="192" font-size="11" fill="#5b6876" text-anchor="middle">independencia lógica: cambiar aquí no rompe las vistas de arriba</text> <path d="M350,216 L350,254" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#base1c)"></path> <rect x="220" y="256" width="260" height="52" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="350" y="278" font-size="13" font-weight="600" fill="#12324f" text-anchor="middle">Nivel interno</text> <text x="350" y="296" font-size="11.5" fill="#5b6876" text-anchor="middle">estructuras físicas de almacenamiento en disco</text> <text x="670" y="290" font-size="11" fill="#5b6876" text-anchor="middle">independencia física: cambiar aquí no rompe el conceptual</text>
</svg>
</div>
<p>Esa separación en capas produce dos tipos de independencia que la bibliografía distingue con cuidado. La <em>independencia lógica de los datos</em> es la capacidad de cambiar el esquema conceptual sin tener que cambiar los esquemas externos ni los programas de aplicación que ya funcionan, por ejemplo añadir un campo nuevo a la estructura conceptual sin romper las vistas que ya existían. La <em>independencia física de los datos</em> es la capacidad de cambiar el esquema interno, por ejemplo mover los archivos a un disco distinto o cambiar la forma de indexarlos, sin tener que tocar el esquema conceptual ni los programas que dependen de el. Ninguna de las dos existe en un sistema de archivos tradicional, porque ahí la estructura del archivo está escrita directamente dentro del código del programa que lo usa, que es justo la dependencia de los datos que describían Connolly y Begg.</p>
</section>
<section id="caso-de-estudio.-por-qué-american-airlines-dejó-de-usar-tableros-manuales" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="caso-de-estudio.-por-qué-american-airlines-dejó-de-usar-tableros-manuales"><span class="header-section-number">4</span> Caso de estudio. Por qué American Airlines dejó de usar tableros manuales</h2>
<p>Antes de 1961, la disponibilidad de asientos en American Airlines se gestionaba con tableros manuales y con un dispositivo electromecánico llamado Magnetronic Reservisor, que desde 1952 reemplazaba fichas de cartón por luces que indicaban si un vuelo tenía cupo. El problema de fondo era que cada oficina de reservas en cada ciudad trabajaba con su propia información, sin una forma rápida de saber en tiempo real que hacían las demás oficinas con los mismos asientos.</p>
<p>Antes de leer la solución, conviene plantearse una pregunta de análisis. Si dos agentes de reservas, en dos ciudades distintas, venden el mismo asiento del mismo vuelo casi al mismo tiempo, que tendría que pasar para que el sistema completo se diera cuenta antes de que el avión despegue con un pasajero de más.</p>
<p>American Airlines e IBM anunciaron en 1961 el sistema SABRE, que entró en operación en 1964 conectando las terminales de reserva de todo el país a un centro de procesamiento central montado sobre dos mainframes IBM 7090. La sigla se expande de forma distinta según la fuente consultada, IBM la documenta como Semi-Automated Business Research Environment mientras que el Engineering and Technology History Wiki del IEEE la documenta como Semi-Automated Business Reservations Environment, así que conviene saber que las dos fuentes primarias citadas en este tema coinciden en el sistema y en el año pero no en el nombre completo de la sigla. La solución al problema de arriba fue exactamente eliminar la duplicación, en vez de que cada oficina llevara su propio inventario de asientos, todas las oficinas leían y escribían sobre el mismo inventario centralizado, así que si un agente vendía un asiento en Nueva York, ese asiento dejaba de estar disponible para el agente de Los Angeles casi al instante.</p>
<div class="diagrama">
<svg viewbox="0 0 760 200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Línea de tiempo desde SABRE en 1964 hasta hoy, pasando por el modelo relacional que Codd publicó en 1970" font-family="Segoe UI, Inter, system-ui, sans-serif">
<path d="M40,150 L720,150" stroke="#c7d6e6" stroke-width="2.5" fill="none"></path> <g fill="#0e6f6c"> <circle cx="110" cy="150" r="7"></circle> <circle cx="380" cy="150" r="7"></circle> <circle cx="650" cy="150" r="7"></circle> </g> <g text-anchor="middle"> <g font-size="13.5" font-weight="700" fill="#12324f"> <text x="110" y="55">1964</text> <text x="380" y="55">1970</text> <text x="650" y="55">Hoy</text> </g> <g font-size="11" fill="#5b6876"> <text x="110" y="76">SABRE conecta las</text> <text x="110" y="90">oficinas de American</text> <text x="110" y="104">Airlines a un solo</text> <text x="110" y="118">centro de cómputo</text> <text x="380" y="76">Codd pública el</text> <text x="380" y="90">modelo relacional en</text> <text x="380" y="104">un artículo de la ACM</text> <text x="650" y="76">SQL sigue siendo el</text> <text x="650" y="90">lenguaje de consulta</text> <text x="650" y="104">más usado en bases</text> <text x="650" y="118">de datos relacionales</text> </g> </g>
</svg>
</div>
<p>Conviene precisar algo con cuidado, porque es un error común repetir SABRE como si fuera la primera base de datos relacional, y no lo es. SABRE es anterior al modelo relacional, que Edgar F. Codd publicó en 1970 en la revista de la ACM con el artículo <em>A Relational Model of Data for Large Shared Data Banks</em>, y es anterior también a los primeros motores de bases de datos relacionales comerciales, que llegaron a finales de esa década. Lo correcto es presentar SABRE como el antecedente que empujó a la industria hacia el procesamiento centralizado de datos compartidos, el mismo problema que después el modelo relacional y el SGBD resolverían de forma más general y con una base matemática sólida detrás, no como una base de datos en el sentido técnico que vas a estudiar en este curso.</p>
</section>
<section id="cuando-el-sgbd-tampoco-basta-por-sí-solo" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="cuando-el-sgbd-tampoco-basta-por-sí-solo"><span class="header-section-number">5</span> Cuando el SGBD tampoco basta por sí solo</h2>
<p>El caso de SABRE muestra por qué una organización adopta el procesamiento centralizado de datos. Pero tener un SGBD detrás de cada sistema no garantiza automáticamente que el problema de inconsistencia desaparezca, y hay un caso real y documentado que lo demuestra en un sector donde el costo de un dato duplicado o mal enlazado es especialmente alto, el de la salud.</p>
<p>Antes de seguir, conviene plantearse una pregunta de análisis. Si un hospital, una clínica y un laboratorio, cada uno con su propio sistema de historia clínica electrónica, es decir cada uno con su propio SGBD detrás, comparten datos de pacientes a través de una red de intercambio de información de salud, que tendría que fallar para que el mismo paciente termine registrado como si fueran varias personas distintas.</p>
<p>Zech, Husk, Moore y Shapiro publicaron en 2016, en la revista <em>Applied Clinical Informatics</em>, un estudio que responde justo esa pregunta con datos reales. Los autores compararon los datos demográficos del Social Security Death Master File, una base de referencia de 85.8 millones de registros, contra los de Healthix, una red de intercambio de información de salud de la ciudad de Nueva York con 11.6 millones de identificadores de pacientes repartidos en más de cien organizaciones distintas. El hallazgo fue que la tasa de identificadores duplicados dentro de Healthix era mayor que en la base de referencia, es decir que el mismo paciente aparecía con perfiles separados y fragmentados, lo que los autores llaman perfiles divididos, en registros distintos dentro de la propia red.</p>
<div class="diagrama">
<svg viewbox="0 0 760 280" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A la izquierda una persona real conectada a un solo registro base de referencia; a la derecha la misma persona real conectada a tres perfiles distintos y con identificadores distintos dentro de una red de intercambio de datos de salud con más de cien organizaciones" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs> <marker id="base1d" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"> <path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path> </marker> </defs> <text x="380" y="16" font-size="13" font-weight="700" fill="#12324f" text-anchor="middle">Una misma persona, un solo registro base contra varios perfiles fragmentados</text> <circle cx="130" cy="60" r="24" fill="#eef4fa" stroke="#c7d6e6"></circle> <circle cx="600" cy="60" r="24" fill="#eef4fa" stroke="#c7d6e6"></circle> <text x="130" y="65" font-size="11" fill="#12324f" text-anchor="middle">Ana</text> <text x="600" y="65" font-size="11" fill="#12324f" text-anchor="middle">Ana</text> <path d="M130,84 L130,140" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#base1d)"></path> <g fill="none" stroke="#8fb3d1" stroke-width="1.6" marker-end="url(#base1d)"> <path d="M600,84 C560,110 500,120 470,140"></path> <path d="M600,84 L600,140"></path> <path d="M600,84 C640,110 700,120 730,140"></path> </g> <rect x="40" y="142" width="180" height="68" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="130" y="166" font-size="12" font-weight="600" fill="#0e6f6c" text-anchor="middle">Registro base</text> <text x="130" y="184" font-size="11" fill="#3c7d7a" text-anchor="middle">Social Security</text> <text x="130" y="198" font-size="11" fill="#3c7d7a" text-anchor="middle">Death Master File</text> <g fill="#f5f7fa" stroke="#cfd8e3"> <rect x="390" y="142" width="160" height="68" rx="10"></rect> <rect x="520" y="142" width="160" height="68" rx="10"></rect> <rect x="650" y="142" width="90" height="68" rx="10"></rect> </g> <g text-anchor="middle" font-size="11" fill="#12324f"> <text x="470" y="164">Hospital A</text> <text x="470" y="180">id 10432</text> <text x="600" y="164">Clínica B</text> <text x="600" y="180">id A-7781</text> <text x="695" y="164">Lab C</text> <text x="695" y="180">id 55290</text> </g> <rect x="380" y="230" width="360" height="38" rx="8" fill="none" stroke="#cfd8e3" stroke-dasharray="4 4"></rect> <text x="560" y="253" font-size="11" fill="#5b6876" text-anchor="middle">Healthix: red de intercambio con más de 100 organizaciones</text>
</svg>
</div>
<p>Este caso es pedagógicamente valioso porque muestra dónde falla la idea que acabas de estudiar en esta misma sección, ya que la anomalía de duplicación que motivó el paso de archivos a bases de datos puede reaparecer, incluso dentro de una arquitectura de SGBD bien construida, si falla el diseño de las claves o de los identificadores únicos al integrar datos entre organizaciones distintas. Cada hospital, cada clínica y cada laboratorio de este caso ya tenía su propio SGBD funcionando correctamente puertas adentro. Lo que falló no fue la tecnología de cada sistema por separado, sino la gobernanza del dato compartido entre sistemas, es decir que no existía un identificador consistente que todas las organizaciones usaran igual para referirse a la misma persona. El SGBD resuelve el problema técnico de un archivo aislado dentro de una organización, pero no resuelve por sí solo un problema organizacional de coordinación entre varias organizaciones distintas.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. Diagnostica el caso de Healthix
</div>
</div>
<div class="callout-body-container callout-body">
<p>Con lo que acabas de leer sobre el caso de Zech y colegas, responde en un párrafo corto. Si tuvieras que proponer una solución de diseño para reducir los perfiles fragmentados dentro de una red como Healthix, sin cambiar ningún sistema interno de los hospitales, en qué parte del problema concentrarías el esfuerzo, en la tecnología de cada SGBD por separado o en el acuerdo entre organizaciones sobre cómo identificar a la misma persona. Justifica tu respuesta con lo que leíste sobre la diferencia entre problema técnico y problema organizacional.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>El esfuerzo hay que concentrarlo en el acuerdo entre organizaciones sobre cómo identificar a la misma persona, no en la tecnología interna de cada SGBD. El estudio de Zech y colegas encontró fragmentación de perfiles a pesar de que cada organización dentro de Healthix ya operaba su propio sistema de historia clínica electrónica con su propio SGBD detrás, funcionando correctamente puertas adentro. El problema no era que a algún hospital le faltara tecnología de base de datos, era que no existía un identificador único consistente que todas las organizaciones usaran de la misma forma para referirse a Ana, así que cada una le asignaba su propio número interno y el sistema de intercambio no tenía como saber con certeza que esos tres números correspondían a la misma persona. Cambiar la tecnología interna de cada hospital no habría resuelto nada, porque el desacuerdo estaba en la capa de integración entre organizaciones, no dentro de ninguna de ellas por separado.</p>
</div>
</div>
</div>
</section>
<section id="lo-que-te-llevas-de-hoy" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="lo-que-te-llevas-de-hoy"><span class="header-section-number">6</span> Lo que te llevas de hoy</h2>
<div class="checklist">
<p>Al salir de este tema deberías poder explicar, sin mirar la guía, los siguientes puntos:</p>
<ul class="task-list">
<li><label><input type="checkbox">La diferencia entre dato, información, conocimiento y sabiduría, con un ejemplo propio de cada peldaño</label></li>
<li><label><input type="checkbox">Por qué la definición de dato de la norma ISO/IEC 2382 complementa, en vez de reemplazar, la escalera de Ackoff</label></li>
<li><label><input type="checkbox">Los siete problemas del procesamiento por archivos según Silberschatz, Korth y Sudarshan, y las tres limitaciones que resaltan Connolly y Begg</label></li>
<li><label><input type="checkbox">Las tres anomalías, inserción, actualización y borrado, con un ejemplo propio de cada una</label></li>
<li><label><input type="checkbox">Las características del enfoque de bases de datos de Elmasri y Navathe que resuelven cada problema del archivo, incluida la arquitectura de tres esquemas</label></li>
<li><label><input type="checkbox">La diferencia entre independencia lógica e independencia física de los datos</label></li>
<li><label><input type="checkbox">Por qué SABRE es un antecedente histórico y no una base de datos relacional</label></li>
<li><label><input type="checkbox">Por qué un SGBD bien construido puede seguir teniendo datos inconsistentes si falla la gobernanza entre organizaciones, con el caso de Healthix como ejemplo</label></li>
</ul>
</div>
</section>
<section id="lo-que-sigue" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="lo-que-sigue"><span class="header-section-number">7</span> Lo que sigue</h2>
<p>Hoy quedó claro qué problema resuelve un SGBD frente a un archivo suelto, con el vocabulario técnico que vas a usar el resto del semestre. El Tema 2 de esta misma unidad da un paso más práctico, se aleja de la teoría de por qué existe un SGBD y entra en dónde aparece uno de verdad dentro de una organización, que aplicaciones típicas lo usan, que beneficios concretos trae en integridad, concurrencia, seguridad e independencia de los datos, y también que limitaciones reales tiene, en costo, en complejidad y en el riesgo de que un solo sistema centralizado se vuelva un punto único de falla.</p>
</section>
<section id="recursos" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="recursos"><span class="header-section-number">8</span> Recursos</h2>
<ul>
<li>Ackoff, R. L. (1989). <em>From Data to Wisdom.</em> Journal of Applied Systems Analysis, 16, 3 a 9. <a href="https://faculty.ung.edu/kmelton/documents/datawisdom.pdf">Copia consultable</a>.</li>
<li>International Organization for Standardization e International Electrotechnical Commission. <em>ISO/IEC 2382:2015. Information technology, Vocabulary.</em> <a href="https://www.iso.org/standard/63598.html">Ficha del estándar</a>.</li>
<li>Silberschatz, A., Korth, H. F. y Sudarshan, S. <em>Fundamentos de bases de datos.</em> Capítulo 1, desventajas del procesamiento por archivos. Material de apoyo oficial de los autores en <a href="https://www.db-book.com">db-book.com</a>.</li>
<li>Elmasri, R. y Navathe, S. B. <em>Fundamentals of Database Systems.</em> Capítulo 1, secciones sobre procesamiento tradicional por archivos y características del enfoque de bases de datos.</li>
<li>Connolly, T. M. y Begg, C. E. <em>Database Systems: A Practical Approach to Design, Implementation, and Management.</em> Capítulo introductorio, limitaciones del enfoque basado en archivos.</li>
<li>Codd, E. F. (1970). <em>A Relational Model of Data for Large Shared Data Banks.</em> Communications of the ACM, 13(6). <a href="https://www.engineering.upenn.edu/~zives/03f/cis550/codd.pdf">Copia en la Universidad de Pensilvania</a>.</li>
<li>Zech, J., Husk, G., Moore, T. y Shapiro, J. S. (2016). <em>Measuring the Degree of Unmatched Patient Records in a Health Information Exchange Using Exact Matching.</em> Applied Clinical Informatics. <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC4941843/">Disponible en PubMed Central</a>.</li>
<li>Engineering and Technology History Wiki, IEEE. <em>SABRE Airline Reservation System.</em> <a href="https://ethw.org/SABRE_Airline_Reservation_System">ethw.org/SABRE_Airline_Reservation_System</a>.</li>
<li>IBM Corporate History. <em>Sabre.</em> <a href="https://www.ibm.com/history/sabre">ibm.com/history/sabre</a>.</li>
<li>Computer History Museum. <em>SABRE, American Airlines’ computerized reservation system.</em> <a href="https://www.computerhistory.org/revolution/mainframe-computers/7/176/702">computerhistory.org</a>.</li>
</ul>
<div class="pie-doc">
<p>Base de datos (DBA03). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>