<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 3. Importancia, costo y calidad en un mundo globalizado – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-95bfa606010d176c52cfb6b551730f65.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-01/index.html">Unidad 1. Calidad del software y estándares de calidad</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html">Tema 3. Importancia, costo y calidad en un mundo globalizado</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Calidad del software y estándares de calidad</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-01-que-es-calidad-quien-la-define/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es la calidad y quién la define</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Calidad de proceso y de producto: ISO/IEC 25010:2023</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 3. Importancia, costo y calidad en un mundo globalizado</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Procesos de calidad del software. Modelos y métricas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-01-sqa-relacion-ingenieria/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es el SQA y su relación con la ingeniería de software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La calidad en cada fase del ciclo de vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-03-roles-habilidades/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Roles, responsabilidades y habilidades del personal de SQA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-04-actividades-sqa/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Actividades del SQA: revisiones, auditorías y gestión de configuración</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-05-modelos-metricas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Modelos y métricas de calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-06-herramientas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 6. Herramientas de SQA en la industria</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 3. Estándares de calidad aplicados al software</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Estándares IEEE para la calidad del software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Marcos para evaluar la usabilidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Madurez de procesos: SPICE y CMMI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 4. Validación y verificación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Métodos, metodologías y estándares de verificación y validación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Validación y verificación de requisitos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-03-control-costo-calidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Control de la calidad y costo de la calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Nomenclatura y certificación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-05-factores-atam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Factores que determinan la calidad y el método ATAM</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#objetivo-y-resultado-de-aprendizaje" id="toc-objetivo-y-resultado-de-aprendizaje" class="nav-link active" data-scroll-target="#objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</a></li>
  <li><a href="#ruta-de-estudio" id="toc-ruta-de-estudio" class="nav-link" data-scroll-target="#ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</a></li>
  <li><a href="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" id="toc-el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="nav-link" data-scroll-target="#el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</a></li>
  <li><a href="#parte-1.-por-qué-importa-la-calidad" id="toc-parte-1.-por-qué-importa-la-calidad" class="nav-link" data-scroll-target="#parte-1.-por-qué-importa-la-calidad"><span class="header-section-number">4</span> Parte 1. Por qué importa la calidad</a></li>
  <li><a href="#parte-2.-el-costo-de-la-mala-calidad" id="toc-parte-2.-el-costo-de-la-mala-calidad" class="nav-link" data-scroll-target="#parte-2.-el-costo-de-la-mala-calidad"><span class="header-section-number">5</span> Parte 2. El costo de la mala calidad</a>
  <ul class="collapse">
  <li><a href="#dos-cifras-que-se-citan-mucho" id="toc-dos-cifras-que-se-citan-mucho" class="nav-link" data-scroll-target="#dos-cifras-que-se-citan-mucho">Dos cifras que se citan mucho</a></li>
  <li><a href="#cómo-leer-una-cifra-como-esa" id="toc-cómo-leer-una-cifra-como-esa" class="nav-link" data-scroll-target="#cómo-leer-una-cifra-como-esa">Cómo leer una cifra como esa</a></li>
  <li><a href="#el-costo-visible-y-el-costo-oculto" id="toc-el-costo-visible-y-el-costo-oculto" class="nav-link" data-scroll-target="#el-costo-visible-y-el-costo-oculto">El costo visible y el costo oculto</a></li>
  <li><a href="#el-modelo-de-los-cuatro-costos" id="toc-el-modelo-de-los-cuatro-costos" class="nav-link" data-scroll-target="#el-modelo-de-los-cuatro-costos">El modelo de los cuatro costos</a></li>
  </ul></li>
  <li><a href="#parte-3.-la-curva-del-costo-del-defecto" id="toc-parte-3.-la-curva-del-costo-del-defecto" class="nav-link" data-scroll-target="#parte-3.-la-curva-del-costo-del-defecto"><span class="header-section-number">6</span> Parte 3. La curva del costo del defecto</a>
  <ul class="collapse">
  <li><a href="#lo-que-afirma-la-curva" id="toc-lo-que-afirma-la-curva" class="nav-link" data-scroll-target="#lo-que-afirma-la-curva">Lo que afirma la curva</a></li>
  <li><a href="#lectura-crítica" id="toc-lectura-crítica" class="nav-link" data-scroll-target="#lectura-crítica">Lectura crítica</a></li>
  <li><a href="#el-principio-shift-left" id="toc-el-principio-shift-left" class="nav-link" data-scroll-target="#el-principio-shift-left">El principio <em>shift-left</em></a></li>
  <li><a href="#ejemplo-resuelto-el-turno-20-en-cuatro-momentos" id="toc-ejemplo-resuelto-el-turno-20-en-cuatro-momentos" class="nav-link" data-scroll-target="#ejemplo-resuelto-el-turno-20-en-cuatro-momentos">Ejemplo resuelto: el turno 20 en cuatro momentos</a></li>
  </ul></li>
  <li><a href="#parte-4.-ejemplo-resuelto-costo-de-la-calidad-de-la-app" id="toc-parte-4.-ejemplo-resuelto-costo-de-la-calidad-de-la-app" class="nav-link" data-scroll-target="#parte-4.-ejemplo-resuelto-costo-de-la-calidad-de-la-app"><span class="header-section-number">7</span> Parte 4. Ejemplo resuelto: costo de la calidad de la app</a>
  <ul class="collapse">
  <li><a href="#datos-del-trimestre" id="toc-datos-del-trimestre" class="nav-link" data-scroll-target="#datos-del-trimestre">Datos del trimestre</a></li>
  <li><a href="#paso-a-paso" id="toc-paso-a-paso" class="nav-link" data-scroll-target="#paso-a-paso">Paso a paso</a></li>
  <li><a href="#escenario-b-invertir-más-en-prevención" id="toc-escenario-b-invertir-más-en-prevención" class="nav-link" data-scroll-target="#escenario-b-invertir-más-en-prevención">Escenario B: invertir más en prevención</a></li>
  </ul></li>
  <li><a href="#parte-5.-tres-casos-reales" id="toc-parte-5.-tres-casos-reales" class="nav-link" data-scroll-target="#parte-5.-tres-casos-reales"><span class="header-section-number">8</span> Parte 5. Tres casos reales</a>
  <ul class="collapse">
  <li><a href="#knight-capital-1-de-agosto-de-2012" id="toc-knight-capital-1-de-agosto-de-2012" class="nav-link" data-scroll-target="#knight-capital-1-de-agosto-de-2012">Knight Capital, 1 de agosto de 2012</a></li>
  <li><a href="#tsb-bank-abril-de-2018" id="toc-tsb-bank-abril-de-2018" class="nav-link" data-scroll-target="#tsb-bank-abril-de-2018">TSB Bank, abril de 2018</a></li>
  <li><a href="#crowdstrike-19-de-julio-de-2024" id="toc-crowdstrike-19-de-julio-de-2024" class="nav-link" data-scroll-target="#crowdstrike-19-de-julio-de-2024">CrowdStrike, 19 de julio de 2024</a></li>
  <li><a href="#qué-tienen-en-común-los-tres-casos" id="toc-qué-tienen-en-común-los-tres-casos" class="nav-link" data-scroll-target="#qué-tienen-en-común-los-tres-casos">Qué tienen en común los tres casos</a></li>
  </ul></li>
  <li><a href="#parte-6.-estándares-y-contexto-colombiano" id="toc-parte-6.-estándares-y-contexto-colombiano" class="nav-link" data-scroll-target="#parte-6.-estándares-y-contexto-colombiano"><span class="header-section-number">9</span> Parte 6. Estándares y contexto colombiano</a>
  <ul class="collapse">
  <li><a href="#los-estándares-como-idioma-común" id="toc-los-estándares-como-idioma-común" class="nav-link" data-scroll-target="#los-estándares-como-idioma-común">Los estándares como idioma común</a></li>
  <li><a href="#vigente-e-histórico-la-iso-9001" id="toc-vigente-e-histórico-la-iso-9001" class="nav-link" data-scroll-target="#vigente-e-histórico-la-iso-9001">Vigente e histórico: la ISO 9001</a></li>
  <li><a href="#qué-aporta-cada-estándar-en-este-curso" id="toc-qué-aporta-cada-estándar-en-este-curso" class="nav-link" data-scroll-target="#qué-aporta-cada-estándar-en-este-curso">Qué aporta cada estándar en este curso</a></li>
  <li><a href="#qué-certifica-una-certificación" id="toc-qué-certifica-una-certificación" class="nav-link" data-scroll-target="#qué-certifica-una-certificación">Qué certifica una certificación</a></li>
  <li><a href="#colombia-icontec-onac-y-la-sic" id="toc-colombia-icontec-onac-y-la-sic" class="nav-link" data-scroll-target="#colombia-icontec-onac-y-la-sic">Colombia: ICONTEC, ONAC y la SIC</a></li>
  </ul></li>
  <li><a href="#parte-7.-equipos-distribuidos-y-trabajo-asíncrono" id="toc-parte-7.-equipos-distribuidos-y-trabajo-asíncrono" class="nav-link" data-scroll-target="#parte-7.-equipos-distribuidos-y-trabajo-asíncrono"><span class="header-section-number">10</span> Parte 7. Equipos distribuidos y trabajo asíncrono</a>
  <ul class="collapse">
  <li><a href="#por-qué-la-distancia-cuesta" id="toc-por-qué-la-distancia-cuesta" class="nav-link" data-scroll-target="#por-qué-la-distancia-cuesta">Por qué la distancia cuesta</a></li>
  <li><a href="#cuánto-solapan-dos-horarios" id="toc-cuánto-solapan-dos-horarios" class="nav-link" data-scroll-target="#cuánto-solapan-dos-horarios">Cuánto solapan dos horarios</a></li>
  <li><a href="#comunicación-asíncrona-tres-hábitos-que-protegen-la-calidad" id="toc-comunicación-asíncrona-tres-hábitos-que-protegen-la-calidad" class="nav-link" data-scroll-target="#comunicación-asíncrona-tres-hábitos-que-protegen-la-calidad">Comunicación asíncrona: tres hábitos que protegen la calidad</a></li>
  </ul></li>
  <li><a href="#parte-8.-cumplimiento-regulatorio-y-sbom" id="toc-parte-8.-cumplimiento-regulatorio-y-sbom" class="nav-link" data-scroll-target="#parte-8.-cumplimiento-regulatorio-y-sbom"><span class="header-section-number">11</span> Parte 8. Cumplimiento regulatorio y SBOM</a>
  <ul class="collapse">
  <li><a href="#ley-de-ciberresiliencia-de-la-ue-cra" id="toc-ley-de-ciberresiliencia-de-la-ue-cra" class="nav-link" data-scroll-target="#ley-de-ciberresiliencia-de-la-ue-cra">Ley de Ciberresiliencia de la UE (CRA)</a></li>
  <li><a href="#ley-de-ia-de-la-ue" id="toc-ley-de-ia-de-la-ue" class="nav-link" data-scroll-target="#ley-de-ia-de-la-ue">Ley de IA de la UE</a></li>
  <li><a href="#ley-1581-de-2012-de-colombia" id="toc-ley-1581-de-2012-de-colombia" class="nav-link" data-scroll-target="#ley-1581-de-2012-de-colombia">Ley 1581 de 2012 de Colombia</a></li>
  <li><a href="#sbom-la-lista-de-ingredientes-del-software" id="toc-sbom-la-lista-de-ingredientes-del-software" class="nav-link" data-scroll-target="#sbom-la-lista-de-ingredientes-del-software">SBOM: la lista de ingredientes del software</a></li>
  </ul></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes"><span class="header-section-number">12</span> Errores frecuentes</a></li>
  <li><a href="#autoevaluación" id="toc-autoevaluación" class="nav-link" data-scroll-target="#autoevaluación"><span class="header-section-number">13</span> Autoevaluación</a></li>
  <li><a href="#lo-que-te-llevas" id="toc-lo-que-te-llevas" class="nav-link" data-scroll-target="#lo-que-te-llevas"><span class="header-section-number">14</span> Lo que te llevas</a></li>
  <li><a href="#glosario" id="toc-glosario" class="nav-link" data-scroll-target="#glosario"><span class="header-section-number">15</span> Glosario</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">16</span> Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-01/index.html">Unidad 1. Calidad del software y estándares de calidad</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html">Tema 3. Importancia, costo y calidad en un mundo globalizado</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 3. Importancia, costo y calidad en un mundo globalizado</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">3 de octubre de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 87%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 1. Calidad del software y estándares de calidad</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 3. Importancia, costo y calidad en un mundo globalizado</td>
</tr>
</tbody>
</table>
</div>
<p><a href="presentacion-interactiva.html" class="btn-curso">Presentación interactiva</a></p>
<p>Tema anterior: <a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html">Tema 2. Calidad de proceso y de producto</a>. Tema siguiente: <a href="../../../calidad-del-software/unidad-02/tema-01-sqa-relacion-ingenieria/index.html">Unidad 2, Tema 1. El SQA y su relación con la ingeniería de software</a>.</p>
<section id="objetivo-y-resultado-de-aprendizaje" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</h2>
<p>Este tema cierra la Unidad 1. Los dos anteriores te dieron el vocabulario de la calidad y el modelo de producto. Aquí respondes tres preguntas prácticas: por qué una organización debe invertir en calidad, cuánto cuesta no hacerlo y qué cambia cuando el software se construye y se vende entre países.</p>
<p>Al terminar puedes:</p>
<ul>
<li>Explicar con ejemplos por qué la calidad importa para el negocio, la seguridad, la sociedad y la reputación.</li>
<li>Leer con criterio una cifra sobre el costo de la mala calidad, y decir qué mide y qué no mide.</li>
<li>Interpretar la curva de costo del defecto de Boehm junto con la evidencia que la discute, y justificar el principio <em>shift-left</em>.</li>
<li>Calcular el costo de la calidad de un producto con sus cuatro componentes y decidir dónde conviene invertir.</li>
<li>Analizar tres casos reales (Knight Capital, TSB y CrowdStrike 2024) y nombrar el control de calidad que faltó en cada uno.</li>
<li>Explicar cómo los estándares internacionales, el cumplimiento regulatorio y las prácticas de trabajo distribuido sostienen la calidad entre países.</li>
</ul>
<p>Prerrequisitos: los Temas 1 y 2 de esta unidad. Necesitas distinguir <em>requisito</em>, <em>defecto</em> y <em>falla</em>, y saber qué es una norma y qué es una certificación.</p>
</section>
<section id="ruta-de-estudio" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</h2>
<p>Son unas 6 horas de trabajo independiente. Puedes partirlas en tres sesiones. La presentación interactiva sigue las mismas partes y en el mismo orden, así que sirve como repaso o como primera mirada.</p>
<div class="calendario">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parte</th>
<th>Qué haces</th>
<th>Tiempo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Por qué importa la calidad</td>
<td>Lees las cuatro razones y las aplicas a la clínica</td>
<td>25 min</td>
</tr>
<tr class="even">
<td>2. El costo de la mala calidad</td>
<td>Lees las cifras, sus límites y el modelo de cuatro costos</td>
<td>40 min</td>
</tr>
<tr class="odd">
<td>3. La curva del defecto</td>
<td>Lees la curva de Boehm, su crítica y el principio <em>shift-left</em>, y resuelves el Reto 2</td>
<td>40 min</td>
</tr>
<tr class="even">
<td>4. Ejemplo resuelto de costo de la calidad</td>
<td>Sigues el cálculo y resuelves el Reto 3</td>
<td>50 min</td>
</tr>
<tr class="odd">
<td>5. Tres casos reales</td>
<td>Analizas Knight Capital, TSB y CrowdStrike, y resuelves el Reto 4</td>
<td>60 min</td>
</tr>
<tr class="even">
<td>6. Estándares y contexto colombiano</td>
<td>Lees cómo funcionan las normas entre países</td>
<td>35 min</td>
</tr>
<tr class="odd">
<td>7. Equipos distribuidos</td>
<td>Calculas ventanas de trabajo y resuelves el Reto 5</td>
<td>40 min</td>
</tr>
<tr class="even">
<td>8. Cumplimiento regulatorio y SBOM</td>
<td>Lees las obligaciones y resuelves el Reto 6</td>
<td>50 min</td>
</tr>
<tr class="odd">
<td>Cierre</td>
<td>Autoevaluación y glosario</td>
<td>30 min</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="el-hilo-conductor-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: la app de turnos de la Clínica Aurora</h2>
<p>Todo el curso usa un producto ficticio, una app que asigna turnos médicos. Su requisito de partida es “la app asigna hasta 20 turnos por día a cada especialidad”. En este tema la usas como laboratorio: le calculas costos, la lanzas a otro país, le agregas proveedores y le aplicas leyes. Ninguna cifra de la clínica es real. Cada vez que aparece un número propio, el texto lo marca como ilustrativo.</p>
</section>
<section id="parte-1.-por-qué-importa-la-calidad" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="parte-1.-por-qué-importa-la-calidad"><span class="header-section-number">4</span> Parte 1. Por qué importa la calidad</h2>
<p>En el Tema 1 viste que la calidad se juzga contra requisitos y contra la necesidad de quien usa el producto. La pregunta de ahora es otra, porque un equipo puede entender esa definición y aun así decidir que no tiene tiempo para la calidad. Hay cuatro razones para no tomar esa decisión.</p>
<div class="diagrama">
<svg viewbox="0 0 760 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="La calidad del software se ramifica en cuatro razones: negocio, seguridad, sociedad y reputación, cada una con un ejemplo de la clínica" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u1t3a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Cuatro razones para invertir en calidad</text> <rect x="270" y="30" width="220" height="60" rx="12" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="66" font-size="14.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Calidad del software</text> <g fill="#eef4fa" stroke="#c7d6e6"><rect x="20" y="170" width="165" height="100" rx="10"></rect><rect x="200" y="170" width="165" height="100" rx="10"></rect><rect x="380" y="170" width="165" height="100" rx="10"></rect><rect x="560" y="170" width="165" height="100" rx="10"></rect></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u1t3a)"><path d="M330,90 C260,120 170,140 102,168"></path><path d="M360,90 C330,120 310,140 282,168"></path><path d="M400,90 C420,120 440,140 462,168"></path><path d="M430,90 C500,120 580,140 642,168"></path></g> <g text-anchor="middle"> <g font-size="13" font-weight="600" fill="#12324f"><text x="102" y="194">Negocio</text><text x="282" y="194">Seguridad</text><text x="462" y="194">Sociedad</text><text x="642" y="194">Reputación</text></g> <g font-size="11" fill="#5b6876"><text x="102" y="216">Citas perdidas, soporte</text><text x="102" y="231">y retrabajo cuestan</text><text x="102" y="246">dinero cada semana</text><text x="282" y="216">Los datos de salud son</text><text x="282" y="231">sensibles y atraen</text><text x="282" y="246">a los atacantes</text><text x="462" y="216">Una persona enferma</text><text x="462" y="231">depende de sacar</text><text x="462" y="246">su turno a tiempo</text><text x="642" y="216">Un paciente que falla</text><text x="642" y="231">una vez cuenta la</text><text x="642" y="246">historia a otros</text></g> </g>
</svg>
</div>
<p>Negocio. Un defecto que llega a producción cuesta más que uno corregido a tiempo, y además cuesta en otras monedas. La clínica pierde citas que no se atendieron, el equipo de soporte atiende reclamos, y los desarrolladores dejan de construir funciones nuevas para apagar incendios. Más adelante en este tema pones números a eso.</p>
<p>Seguridad. Un defecto no siempre produce un resultado equivocado visible. A veces abre una puerta. La Ley 1581 de 2012 de Colombia, que verás en la Parte 8, clasifica los datos de salud como sensibles, así que una app de turnos médicos maneja justo el tipo de información que más daño causa si se filtra. El informe del CISQ de 2022 atribuye la mayor parte del aumento de la mala calidad del software en Estados Unidos al delito informático, con 1,44 billones de dólares en 2022 (la cifra y sus límites están en la Parte 2).</p>
<p>Sociedad. Sommerville (<em>Software Engineering</em>, 10.a ed.) sostiene que las sociedades modernas no funcionan sin sistemas de software grandes y confiables, desde la energía hasta el transporte. Un sistema de turnos de una clínica no es una planta eléctrica, pero quien lo usa suele tener una necesidad de salud, y una falla le cuesta tiempo que a veces no tiene.</p>
<p>Reputación. Una falla repetida erosiona la confianza. En un mercado donde el cliente no puede leer tu código, la confianza es lo que decide si te contrata. Por eso existen las certificaciones, que estudias en la Parte 6.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Clasifica el impacto
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una falla de la app hace que 40 pacientes reciban dos veces el mismo turno. Escribe, para cada una de las cuatro razones, una consecuencia concreta que podría producir esa falla.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Negocio: el personal de recepción dedica horas a reasignar turnos y la clínica atiende a menos pacientes de los que podría.</li>
<li>Seguridad: si el error de duplicación nace de una consulta que mezcla registros, podría mostrar datos de un paciente a otro, lo que es un incidente con datos de salud.</li>
<li>Sociedad: algunos de esos pacientes llegan a su cita y no encuentran cupo, y una persona con una necesidad médica pierde tiempo.</li>
<li>Reputación: los pacientes cuentan lo ocurrido y la clínica pierde confianza, lo que pesa más que el costo de corregir el defecto.</li>
</ul>
<p>Tu respuesta puede variar mientras cada consecuencia se conecte con su razón.</p>
</div>
</div>
</div>
</section>
<section id="parte-2.-el-costo-de-la-mala-calidad" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="parte-2.-el-costo-de-la-mala-calidad"><span class="header-section-number">5</span> Parte 2. El costo de la mala calidad</h2>
<p>Todo el mundo repite que la mala calidad es cara, pero casi nadie dice cuánto ni sobre qué base. Esta parte presenta las dos cifras más citadas y te enseña a leerlas.</p>
<section id="dos-cifras-que-se-citan-mucho" class="level3">
<h3 class="anchored" data-anchor-id="dos-cifras-que-se-citan-mucho">Dos cifras que se citan mucho</h3>
<p>La primera es del NIST de Estados Unidos. En 2002, el informe de planificación 02-3, preparado por RTI International, estimó que las fallas por pruebas inadecuadas costaban a la economía estadounidense unos 59.500 millones de dólares al año. El estudio midió con detalle dos sectores, manufactura y servicios financieros, que sumaron 5.850 millones, y extrapoló el resultado al resto de la economía a partir del impacto por empleado.</p>
<p>La segunda es del CISQ (<em>Consortium for Information and Software Quality</em>). Su informe de 2022, de Herb Krasner, estima que la mala calidad del software costó a Estados Unidos al menos 2,41 billones de dólares en 2022 (billón en el sentido de millón de millones). Aparte, calcula una deuda técnica acumulada de unos 1,52 billones, que no se suma al total anterior. El propio informe explica que el aumento viene sobre todo del delito informático, con 1,44 billones de dólares en 2022.</p>
<p>Esa es la versión más reciente del CISQ que consta en octubre de 2026. El informe de 2022 anunciaba otro para 2024, y no consta que se haya publicado.</p>
</section>
<section id="cómo-leer-una-cifra-como-esa" class="level3">
<h3 class="anchored" data-anchor-id="cómo-leer-una-cifra-como-esa">Cómo leer una cifra como esa</h3>
<p>Ninguna de las dos es una medición directa. Antes de usar una cifra, hazle estas cuatro preguntas.</p>
<ol type="1">
<li>Quién la estimó y con qué datos. El CISQ explica en su apéndice que el informe de 2020, sobre el que se apoya el de 2022, se construyó extrapolando 88 fuentes públicas combinadas con criterio experto. El NIST extrapoló de dos sectores.</li>
<li>Qué incluye. El CISQ suma fallas operativas, proyectos fallidos y sistemas heredados, y su propio apéndice admite que la mayoría de las organizaciones no registra su costo de mala calidad.</li>
<li>De qué año y de qué país. Ambas cifras son de Estados Unidos y de su año. No se trasladan a Colombia multiplicando.</li>
<li>Qué dice el propio autor sobre su límite. El CISQ escribe “al menos”, un piso, no un valor exacto.</li>
</ol>
<p>Con esas cuatro preguntas, la frase correcta para citar a CISQ es “una estimación del CISQ para 2022, de al menos 2,41 billones de dólares en Estados Unidos, construida por extrapolación”. La frase incorrecta es “la mala calidad cuesta 2,41 billones al año en el mundo”.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Una advertencia sobre las cifras de mercado
</div>
</div>
<div class="callout-body-container callout-body">
<p>Muchos artículos y entradas de blog repiten tamaños de mercado de la subcontratación de software que vienen de una sola consultora, sin metodología pública. Esta guía no usa cifras de ese tipo. Si necesitas una, busca el informe original y verifica quién la calculó y cómo.</p>
</div>
</div>
</section>
<section id="el-costo-visible-y-el-costo-oculto" class="level3">
<h3 class="anchored" data-anchor-id="el-costo-visible-y-el-costo-oculto">El costo visible y el costo oculto</h3>
<p>El costo de una falla incluye lo que se ve y lo que no. Lo visible es la hora de un desarrollador corrigiendo el defecto. Lo oculto es todo lo demás.</p>
<div class="diagrama">
<svg viewbox="0 0 760 270" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Costo visible de una falla, el arreglo, sobre una línea, y costos ocultos debajo: soporte, retrabajo, citas perdidas, reputación, sanciones y deuda técnica" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Lo que se ve y lo que no se ve de una falla</text> <rect x="270" y="34" width="220" height="50" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="56" font-size="12.5" font-weight="700" fill="#0e6f6c" text-anchor="middle">Costo visible</text> <text x="380" y="73" font-size="11" fill="#3c7d7a" text-anchor="middle">horas de corregir el defecto</text> <line x1="40" y1="106" x2="720" y2="106" stroke="#8fb3d1" stroke-width="2" stroke-dasharray="6 5"></line> <text x="46" y="124" font-size="11" fill="#5b6876">línea de flotación</text> <g fill="#f5f7fa" stroke="#cfd8e3"><rect x="40" y="140" width="200" height="56" rx="8"></rect><rect x="280" y="140" width="200" height="56" rx="8"></rect><rect x="520" y="140" width="200" height="56" rx="8"></rect><rect x="40" y="206" width="200" height="56" rx="8"></rect><rect x="280" y="206" width="200" height="56" rx="8"></rect><rect x="520" y="206" width="200" height="56" rx="8"></rect></g> <g text-anchor="middle" font-size="12" font-weight="600" fill="#12324f"><text x="140" y="164">Soporte y reclamos</text><text x="380" y="164">Retrabajo y retrasos</text><text x="620" y="164">Ingresos perdidos</text><text x="140" y="230">Reputación</text><text x="380" y="230">Sanciones y multas</text><text x="620" y="230">Deuda técnica</text></g> <g text-anchor="middle" font-size="11" fill="#5b6876"><text x="140" y="181">llamadas, correos, visitas</text><text x="380" y="181">se atrasa lo planeado</text><text x="620" y="181">citas no atendidas</text><text x="140" y="247">el paciente no vuelve</text><text x="380" y="247">si se incumple una ley</text><text x="620" y="247">el parche queda dentro</text></g>
</svg>
</div>
</section>
<section id="el-modelo-de-los-cuatro-costos" class="level3">
<h3 class="anchored" data-anchor-id="el-modelo-de-los-cuatro-costos">El modelo de los cuatro costos</h3>
<p>Para organizar esos costos se usa el modelo del costo de la calidad, con origen en los trabajos de Juran y de Crosby (la Unidad 4 lo estudia a fondo). Aquí necesitas la idea central, que separa el dinero que gastas para tener calidad del dinero que gastas por no tenerla.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Costo</th>
<th>Qué incluye</th>
<th>Ejemplo en la clínica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Prevención</td>
<td>Todo lo que evita que nazcan defectos</td>
<td>Talleres de requisitos, plantillas de revisión, capacitación</td>
</tr>
<tr class="even">
<td>Evaluación</td>
<td>Todo lo que busca defectos antes de entregar</td>
<td>Revisión de código, pruebas automáticas, pilotos con pacientes</td>
</tr>
<tr class="odd">
<td>Fallas internas</td>
<td>Corregir lo que se halló antes de entregar</td>
<td>Horas de arreglar los defectos que las pruebas encontraron</td>
</tr>
<tr class="even">
<td>Fallas externas</td>
<td>Corregir lo que llegó al usuario</td>
<td>Defectos en producción, soporte, citas perdidas</td>
</tr>
</tbody>
</table>
<p>Los dos primeros se llaman costo de conformidad, porque los pagas para cumplir. Los dos últimos son costo de no conformidad, porque los pagas por no haber cumplido. Una idea muy citada del modelo es que gastar un poco más en prevención reduce las fallas, y por eso baja el total. Más abajo calculas si eso ocurre en la clínica.</p>
</section>
</section>
<section id="parte-3.-la-curva-del-costo-del-defecto" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="parte-3.-la-curva-del-costo-del-defecto"><span class="header-section-number">6</span> Parte 3. La curva del costo del defecto</h2>
<section id="lo-que-afirma-la-curva" class="level3">
<h3 class="anchored" data-anchor-id="lo-que-afirma-la-curva">Lo que afirma la curva</h3>
<p>Barry Boehm, en <em>Software Engineering Economics</em> (1981), planteó que un defecto cuesta más a medida que avanza el proyecto. En su artículo con Victor Basili de 2001, <em>Software Defect Reduction Top 10 List</em> (IEEE Computer), lo resumen así: corregir un problema después de entregar el software es a menudo cien veces más caro que corregirlo en la fase de requisitos o de diseño. Los autores añaden que en sistemas pequeños y no críticos el factor se parece más a 5 que a 100.</p>
<div class="diagrama">
<svg viewbox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Tres barras: corregir un defecto en requisitos o diseño vale 1; después de entregar en un sistema pequeño y no crítico vale cerca de 5; después de entregar en un sistema grande y crítico vale cerca de 100" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Costo relativo de corregir un defecto según Boehm y Basili (2001)</text> <line x1="60" y1="250" x2="700" y2="250" stroke="#cfd8e3" stroke-width="1.4"></line> <rect x="110" y="246" width="110" height="4" rx="2" fill="#e4f2f1" stroke="#8fc9c5"></rect> <rect x="320" y="230" width="110" height="20" rx="4" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="530" y="50" width="110" height="200" rx="4" fill="#fbeae5" stroke="#e0a595"></rect> <g text-anchor="middle" font-size="13" font-weight="700" fill="#12324f"><text x="165" y="238">1</text><text x="375" y="222">cerca de 5</text><text x="585" y="42">cerca de 100</text></g> <g text-anchor="middle" font-size="11.5" fill="#12324f"><text x="165" y="270">En requisitos o diseño</text><text x="375" y="270">Tras entregar, sistema</text><text x="375" y="284">pequeño y no crítico</text><text x="585" y="270">Tras entregar, sistema</text><text x="585" y="284">grande y crítico</text></g>
</svg>
</div>
<p>El diagrama solo dibuja los tres valores que los autores publican. No hay barras intermedias porque esa fuente no da valores para las fases del medio, y inventarlos le daría a la curva una precisión que no tiene.</p>
</section>
<section id="lectura-crítica" class="level3">
<h3 class="anchored" data-anchor-id="lectura-crítica">Lectura crítica</h3>
<p>La curva es útil como intuición y peligrosa como dato. Hay tres cosas que debes saber antes de citarla.</p>
<p>Primera, Laurent Bossavit examina en <em>The Leprechauns of Software Engineering</em> (2013) el origen de la curva y sostiene que la evidencia que se cita en su favor es débil y que algunos estudios se describen mal. Es una crítica de un autor, no un experimento, y conviene leerla como tal.</p>
<p>Segunda, Menzies, Nichols, Shull y Layman (<em>Empirical Software Engineering</em>, 2017) estudiaron 171 proyectos de software recogidos entre 2006 y 2014 y no encontraron el efecto de que los problemas tardíos sean más difíciles de resolver. Concluyen que ese principio podría ser una reliquia histórica que aparece de forma intermitente solo en ciertos tipos de proyectos.</p>
<p>Tercera, ese resultado no demuestra que la curva sea falsa en todos los contextos. Muestra que no se puede aplicar como ley universal. Un defecto en un sistema ya entregado, con datos de usuarios y con contratos de por medio, sigue teniendo costos que un defecto de diseño no tiene. Lo que el estudio de Menzies invita a hacer es medir tu propio proyecto, no confiar en un factor ajeno.</p>
</section>
<section id="el-principio-shift-left" class="level3">
<h3 class="anchored" data-anchor-id="el-principio-shift-left">El principio <em>shift-left</em></h3>
<p>El principio <em>shift-left</em> (mover a la izquierda) se apoya en la intuición de la curva, pero sobrevive a su crítica. Consiste en llevar las actividades de calidad lo más temprano posible en la línea de tiempo del proyecto, porque un defecto hallado antes de escribir código evita todo el trabajo que se habría construido encima. Se concreta en prácticas como revisar los requisitos, definir criterios de aceptación antes de programar y automatizar pruebas que corren en cada cambio.</p>
<p>Mover a la izquierda no significa abandonar las pruebas finales ni la validación con usuarios. Significa sumar controles tempranos a los tardíos, porque cada control encuentra defectos distintos.</p>
</section>
<section id="ejemplo-resuelto-el-turno-20-en-cuatro-momentos" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-el-turno-20-en-cuatro-momentos">Ejemplo resuelto: el turno 20 en cuatro momentos</h3>
<p>Tomamos el defecto del Tema 1, la condición <code>numeroTurno &lt; CUPO</code>, que debería ser <code>&lt;=</code>. Supón que corregirlo cuando se detecta en la revisión del requisito cuesta 1 hora. Según Boehm y Basili, cuánto cuesta después de entregar depende del tipo de sistema.</p>
<ol type="1">
<li>Define el costo base. En revisión de requisitos, 1 hora.</li>
<li>Aplica el factor de un sistema pequeño y no crítico, 5. Después de entregar cuesta unas 5 horas.</li>
<li>Aplica el factor de un sistema grande y crítico, 100. Después de entregar cuesta unas 100 horas.</li>
<li>Decide cuál aplica a la clínica. Una app de turnos de una clínica pequeña se parece al primer caso. Una red hospitalaria con urgencias se parece más al segundo.</li>
</ol>
<p>Los factores son los publicados por Boehm y Basili, y las horas resultantes son un ejercicio, no una medición de la clínica.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Aplica los dos factores
</div>
</div>
<div class="callout-body-container callout-body">
<p>La clínica descubre al terminar el mes 12 defectos que habrían costado 1 hora cada uno en revisión de requisitos. Calcula el costo total en horas si todos se corrigen después de entregar, con el factor de 5 y con el de 100. Después escribe una frase que explique por qué ese resultado no prueba que invertir en revisión de requisitos siempre se pague.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Con factor 5: 12 defectos x 1 hora x 5 = 60 horas.</li>
<li>Con factor 100: 12 defectos x 1 hora x 100 = 1.200 horas.</li>
<li>Frente a esas cifras, revisar los 12 requisitos habría costado 12 horas.</li>
</ul>
<p>La frase de cierre puede decir que los factores son un rango publicado para ciertos sistemas y que el estudio de Menzies encontró proyectos donde los defectos tardíos no costaron más. Antes de decidir, la clínica debería medir cuántas horas le costó de verdad cada defecto en su historial.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-4.-ejemplo-resuelto-costo-de-la-calidad-de-la-app" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="parte-4.-ejemplo-resuelto-costo-de-la-calidad-de-la-app"><span class="header-section-number">7</span> Parte 4. Ejemplo resuelto: costo de la calidad de la app</h2>
<p>Con el modelo de cuatro costos puedes calcular qué gasta la clínica en calidad y si cambiar el reparto le conviene. Todas las cifras de esta parte son ilustrativas. Se inventaron para practicar el cálculo, y no vienen de ningún estudio ni de ninguna clínica real.</p>
<section id="datos-del-trimestre" class="level3">
<h3 class="anchored" data-anchor-id="datos-del-trimestre">Datos del trimestre</h3>
<p>Supón que el equipo de la app trabajó un trimestre de la versión 2.0 y que una hora de trabajo del equipo cuesta 60.000 pesos.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 33%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Rubro</th>
<th>Detalle</th>
<th style="text-align: center;">Horas</th>
<th style="text-align: right;">Costo en pesos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Prevención</td>
<td>Taller de requisitos (24 h), plantilla de revisión (16 h), capacitación (20 h)</td>
<td style="text-align: center;">60</td>
<td style="text-align: right;">3.600.000</td>
</tr>
<tr class="even">
<td>Evaluación</td>
<td>Revisión de código (80 h), mantenimiento de pruebas automáticas (60 h), piloto con pacientes (40 h)</td>
<td style="text-align: center;">180</td>
<td style="text-align: right;">10.800.000</td>
</tr>
<tr class="odd">
<td>Fallas internas</td>
<td>45 defectos hallados antes de entregar, 3 h cada uno</td>
<td style="text-align: center;">135</td>
<td style="text-align: right;">8.100.000</td>
</tr>
<tr class="even">
<td>Fallas externas</td>
<td>9 defectos en producción, 12 h de arreglo y 4 h de soporte cada uno</td>
<td style="text-align: center;">144</td>
<td style="text-align: right;">8.640.000</td>
</tr>
<tr class="odd">
<td>Fallas externas</td>
<td>27 citas perdidas (3 por defecto), 80.000 pesos de ingreso por cita</td>
<td style="text-align: center;"></td>
<td style="text-align: right;">2.160.000</td>
</tr>
</tbody>
</table>
</section>
<section id="paso-a-paso" class="level3">
<h3 class="anchored" data-anchor-id="paso-a-paso">Paso a paso</h3>
<ol type="1">
<li>Suma cada componente. Prevención 3.600.000. Evaluación 10.800.000. Fallas internas 8.100.000. Fallas externas 8.640.000 más 2.160.000, que da 10.800.000.</li>
<li>Suma el total. 3.600.000 + 10.800.000 + 8.100.000 + 10.800.000 = 33.300.000 pesos.</li>
<li>Separa conformidad y no conformidad. Conformidad es prevención más evaluación, 14.400.000, o 43,2 % del total. No conformidad es la suma de las dos fallas, 18.900.000, o 56,8 %.</li>
<li>Lee el resultado. La clínica gasta más en lo que le falló que en lo que hizo para que no fallara.</li>
</ol>
</section>
<section id="escenario-b-invertir-más-en-prevención" class="level3">
<h3 class="anchored" data-anchor-id="escenario-b-invertir-más-en-prevención">Escenario B: invertir más en prevención</h3>
<p>El equipo propone sumar 2.400.000 pesos (40 horas) de prevención, con talleres de requisitos más largos. Supón, como hipótesis, que esa inversión reduce los defectos que nacen, de modo que se hallan 40 internos en lugar de 45 y llegan 5 a producción en lugar de 9, con 15 citas perdidas en lugar de 27.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Componente</th>
<th style="text-align: right;">Escenario A</th>
<th style="text-align: right;">Escenario B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Prevención</td>
<td style="text-align: right;">3.600.000</td>
<td style="text-align: right;">6.000.000</td>
</tr>
<tr class="even">
<td>Evaluación</td>
<td style="text-align: right;">10.800.000</td>
<td style="text-align: right;">10.800.000</td>
</tr>
<tr class="odd">
<td>Fallas internas (40 x 3 h)</td>
<td style="text-align: right;">8.100.000</td>
<td style="text-align: right;">7.200.000</td>
</tr>
<tr class="even">
<td>Fallas externas (5 x 16 h y 15 citas)</td>
<td style="text-align: right;">10.800.000</td>
<td style="text-align: right;">6.000.000</td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">33.300.000</td>
<td style="text-align: right;">30.000.000</td>
</tr>
</tbody>
</table>
<div class="diagrama">
<svg viewbox="0 0 760 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Dos columnas apiladas: el escenario A suma 33.3 millones de pesos y el escenario B suma 30 millones; en B crece la prevención y se reducen las fallas externas" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Costo de la calidad por escenario (cifras ilustrativas, en millones de pesos)</text> <line x1="80" y1="258" x2="460" y2="258" stroke="#cfd8e3" stroke-width="1.4"></line> <g stroke-width="1"><rect x="120" y="236.4" width="110" height="21.6" fill="#fff3d6" stroke="#e6c46f"></rect><rect x="120" y="171.5" width="110" height="64.9" fill="#fff3d6" stroke="#e6c46f"></rect><rect x="120" y="122.9" width="110" height="48.6" fill="#fbeae5" stroke="#e0a595"></rect><rect x="120" y="58.0" width="110" height="64.9" fill="#fbeae5" stroke="#e0a595"></rect></g> <g stroke-width="1"><rect x="310" y="222.0" width="110" height="36.0" fill="#fff3d6" stroke="#e6c46f"></rect><rect x="310" y="157.1" width="110" height="64.9" fill="#fff3d6" stroke="#e6c46f"></rect><rect x="310" y="113.9" width="110" height="43.2" fill="#fbeae5" stroke="#e0a595"></rect><rect x="310" y="77.8" width="110" height="36.0" fill="#fbeae5" stroke="#e0a595"></rect></g> <g text-anchor="middle" font-size="11" fill="#12324f"><text x="175" y="251.2">Prev. 3,60</text><text x="175" y="207.9">Evaluación 10,80</text><text x="175" y="151.2">Internas 8,10</text><text x="175" y="94.4">Externas 10,80</text><text x="365" y="244.0">Prev. 6,00</text><text x="365" y="193.5">Evaluación 10,80</text><text x="365" y="139.5">Internas 7,20</text><text x="365" y="99.8">Externas 6,00</text></g> <g text-anchor="middle" font-size="12.5" font-weight="700" fill="#12324f"><text x="175" y="50.0">A: 33,30</text><text x="365" y="69.8">B: 30,00</text><text x="175" y="278">Escenario A</text><text x="365" y="278">Escenario B</text></g> <g fill="#f5f7fa" stroke="#cfd8e3"><rect x="500" y="70" width="230" height="150" rx="10"></rect></g> <g font-size="12" fill="#12324f"><text x="516" y="96" font-weight="700">Lectura</text><text x="516" y="120">Prevención sube 2,40.</text><text x="516" y="140">Las fallas bajan 5,70.</text><text x="516" y="160">El total baja 3,30.</text><text x="516" y="186" font-size="11" fill="#5b6876">Amarillo: conformidad.</text><text x="516" y="204" font-size="11" fill="#5b6876">Rosa: no conformidad.</text></g>
</svg>
</div>
<p>El resultado es una diferencia de 3.300.000 pesos a favor del escenario B (33.300.000 menos 30.000.000), porque las fallas bajan 5.700.000 y la prevención sube 2.400.000. Cuidado con la conclusión, porque todo depende de la hipótesis de que 40 horas más de prevención reducen los defectos de esa forma. Si no reducen nada, el escenario B cuesta 2.400.000 más. El cálculo no demuestra que prevenir siempre convenga. Muestra que para decidirlo necesitas contar tus propios defectos y tus propias horas.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. Mover dinero entre rubros
</div>
</div>
<div class="callout-body-container callout-body">
<p>Otro equipo tiene este trimestre: prevención 2.000.000, evaluación 9.000.000, fallas internas 6.000.000 y fallas externas 15.000.000 de pesos. Calcula el total y el porcentaje de no conformidad. Luego evalúa esta propuesta, que mueve 3.000.000 de evaluación a prevención y estima que las fallas externas bajan 30 % y las internas suben 10 %. Escribe qué cuidado tomarías antes de aprobarla.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Total actual: 2.000.000 + 9.000.000 + 6.000.000 + 15.000.000 = 32.000.000 pesos.</li>
<li>No conformidad: 6.000.000 + 15.000.000 = 21.000.000, o 65,6 % del total.</li>
<li>Propuesta: prevención 5.000.000, evaluación 6.000.000, fallas internas 6.600.000 (6.000.000 x 1,10) y fallas externas 10.500.000 (15.000.000 x 0,70). El total es 28.100.000.</li>
<li>Diferencia: 32.000.000 menos 28.100.000 da 3.900.000 de ahorro estimado.</li>
</ul>
<p>El cuidado es que ambos porcentajes son estimaciones del equipo. Antes de aprobarla conviene preguntar en qué datos se apoyan, y definir cómo se medirá, el trimestre siguiente, si las fallas externas bajaron de verdad. También conviene revisar que recortar evaluación no esconda defectos que luego aparezcan como fallas externas.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-5.-tres-casos-reales" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="parte-5.-tres-casos-reales"><span class="header-section-number">8</span> Parte 5. Tres casos reales</h2>
<p>Los tres casos de esta parte son los únicos del curso que se cuentan con detalle en este tema. Cada uno tiene una fuente primaria, es decir, el documento de quien investigó o sancionó el hecho. Para cada uno, antes de leer la causa, piensa qué control habrías puesto.</p>
<p>El Therac-25 se estudió en el Tema 1 y el Ariane 5 en el Tema 2. Aquí no se repiten.</p>
<section id="knight-capital-1-de-agosto-de-2012" class="level3">
<h3 class="anchored" data-anchor-id="knight-capital-1-de-agosto-de-2012">Knight Capital, 1 de agosto de 2012</h3>
<p>Knight Capital era una firma estadounidense que enviaba órdenes de compra y venta de acciones a la bolsa. Para participar en un programa nuevo de la Bolsa de Nueva York, el Retail Liquidity Program, actualizó su enrutador automático de órdenes, llamado SMARS.</p>
<p>Pregunta de análisis. Si una actualización llega a 7 de 8 servidores y al octavo no, ¿qué información tendría que existir para que alguien lo notara antes de abrir el mercado?</p>
<div class="diagrama">
<svg viewbox="0 0 760 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Ocho servidores de Knight Capital: siete con el código nuevo y uno con el código antiguo Power Peg; abajo, línea de tiempo del 27 de julio al 1 de agosto de 2012" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Knight Capital: siete servidores bien y uno con código antiguo</text> <g fill="#e4f2f1" stroke="#8fc9c5"><rect x="30" y="34" width="78" height="46" rx="8"></rect><rect x="114" y="34" width="78" height="46" rx="8"></rect><rect x="198" y="34" width="78" height="46" rx="8"></rect><rect x="282" y="34" width="78" height="46" rx="8"></rect><rect x="366" y="34" width="78" height="46" rx="8"></rect><rect x="450" y="34" width="78" height="46" rx="8"></rect><rect x="534" y="34" width="78" height="46" rx="8"></rect></g> <rect x="618" y="34" width="112" height="46" rx="8" fill="#fbeae5" stroke="#e0a595"></rect> <g text-anchor="middle" font-size="11" fill="#0e6f6c"><text x="69" y="62">código nuevo</text><text x="153" y="62">código nuevo</text><text x="237" y="62">código nuevo</text><text x="321" y="62">código nuevo</text><text x="405" y="62">código nuevo</text><text x="489" y="62">código nuevo</text><text x="573" y="62">código nuevo</text></g> <g text-anchor="middle" font-size="11" fill="#a23b25" font-weight="600"><text x="674" y="54">sin copiar:</text><text x="674" y="70">Power Peg</text></g> <text x="380" y="104" font-size="11.5" fill="#5b6876" text-anchor="middle">La bandera que activaba el código nuevo era la misma que activaba el antiguo</text> <line x1="40" y1="170" x2="720" y2="170" stroke="#8fb3d1" stroke-width="2"></line> <g fill="#0e6f6c"><circle cx="90" cy="170" r="5"></circle><circle cx="270" cy="170" r="5"></circle><circle cx="450" cy="170" r="5"></circle><circle cx="670" cy="170" r="5"></circle></g> <g text-anchor="middle" font-size="12" font-weight="600" fill="#12324f"><text x="90" y="148">27 jul</text><text x="270" y="148">1 ago, 8:01</text><text x="450" y="148">1 ago, 9:30</text><text x="670" y="148">45 minutos después</text></g> <g text-anchor="middle" font-size="11" fill="#5b6876"><text x="90" y="192">Empieza el despliegue</text><text x="90" y="206">por etapas</text><text x="270" y="192">97 correos automáticos</text><text x="270" y="206">dicen “Power Peg disabled”</text><text x="450" y="192">Abre el mercado</text><text x="670" y="192">Más de 4 millones de ejecuciones</text><text x="670" y="206">en 154 acciones</text></g> <rect x="40" y="232" width="680" height="40" rx="8" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="380" y="256" font-size="11.5" fill="#12324f" text-anchor="middle">Pérdida superior a 460 millones de dólares y sanción de 12 millones de la SEC en 2013</text>
</svg>
</div>
<p>Lo que dice la orden de la SEC del 16 de octubre de 2013 (Release 34-70694) es esto. El nuevo código reemplazaba un código viejo, llamado Power Peg, que Knight había dejado de usar en 2003 pero que seguía presente en el sistema. El nuevo código reutilizaba la bandera que antes activaba Power Peg. Desde el 27 de julio, un técnico fue desplegando el código nuevo servidor por servidor, y en uno de los ocho no lo copió. Nadie revisó el despliegue y no había un procedimiento escrito que exigiera una segunda revisión.</p>
<p>Antes de la apertura, un sistema interno envió 97 correos automáticos que mencionaban “Power Peg disabled”. Esos correos no estaban diseñados como alertas del sistema, y nadie los trató así. Al abrir el mercado, las órdenes que llegaron con la bandera reutilizada al octavo servidor activaron el código viejo. En unos 45 minutos, a partir de 212 órdenes pequeñas de clientes, el sistema produjo más de 4 millones de ejecuciones en 154 acciones, por más de 397 millones de acciones. Knight perdió más de 460 millones de dólares en las posiciones no deseadas, y la SEC le impuso una multa de 12 millones.</p>
<p>Hay un segundo error, en la respuesta al incidente. El personal desinstaló el código nuevo de los siete servidores correctos, y eso empeoró el problema, porque entonces esos servidores también activaron Power Peg.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Una cifra que se corrige
</div>
</div>
<div class="callout-body-container callout-body">
<p>Muchas fuentes hablan de 440 millones de dólares. La orden de la SEC dice que Knight perdió “más de 460 millones” y, en el párrafo 17, que realizó una pérdida de 460 millones. Esta guía usa la cifra de la fuente primaria.</p>
</div>
</div>
<p>Qué control faltó: revisión del despliegue por una segunda persona, eliminación del código muerto, pruebas del código que se reactiva, alertas reales en lugar de correos informativos, y un procedimiento de respuesta a incidentes. Ninguno es un algoritmo. Son controles de proceso, y por eso el caso encaja en esta guía sobre el costo de la calidad: un conjunto de controles baratos habría evitado una pérdida enorme.</p>
</section>
<section id="tsb-bank-abril-de-2018" class="level3">
<h3 class="anchored" data-anchor-id="tsb-bank-abril-de-2018">TSB Bank, abril de 2018</h3>
<p>TSB es un banco del Reino Unido. En 2018 migró los datos de sus clientes desde la plataforma de Lloyds, de la que recibía sus servicios de TI desde su separación en 2014, a una nueva plataforma de su casa matriz, el banco español Sabadell, llamada Proteo4UK.</p>
<p>Pregunta de análisis. Si un banco contrata a un proveedor que a su vez subcontrata a decenas de empresas, ¿quién responde ante el cliente y ante el regulador cuando algo falla?</p>
<p>La fuente primaria es el Aviso Final (<em>Final Notice</em>) de la FCA, el regulador de conducta financiera del Reino Unido, de diciembre de 2022, y el comunicado que lo acompañó. Estos son los hechos verificados:</p>
<ul>
<li>TSB contrató a SABIS Spain, filial de Sabadell, para diseñar, construir y probar la plataforma, migrar los datos y operarla después de la migración.</li>
<li>La migración principal ocurrió entre el 20 y el 22 de abril de 2018. Una parte importante de los 5,2 millones de clientes de TSB se vio afectada, y el banco no volvió a su operación normal hasta el 10 de diciembre de 2018.</li>
<li>Entre el 22 de abril de 2018 y el 7 de abril de 2019, TSB recibió 225.492 reclamos y pagó unos 32,7 millones de libras en compensaciones.</li>
<li>SABIS se apoyó en 85 terceros, que para TSB eran “cuartas partes”, y cuatro de ellos eran proveedores críticos.</li>
<li>Las multas sumaron 48.650.000 libras esterlinas, de las cuales 29.750.000 fueron de la FCA y 18.900.000 de la PRA (el regulador prudencial). Es la cifra después de un descuento de 30 % por resolver el caso. Sin él, habrían sido 69.500.000.</li>
</ul>
<div class="diagrama">
<svg viewbox="0 0 760 270" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="TSB contrata a SABIS Spain, filial de Sabadell, que se apoya en 85 terceros, de los cuales cuatro son críticos; la responsabilidad regulatoria permanece en TSB" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u1t3b" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">TSB 2018: la cadena de proveedores</text> <rect x="290" y="32" width="180" height="50" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="54" font-size="13" font-weight="700" fill="#0e6f6c" text-anchor="middle">TSB</text> <text x="380" y="72" font-size="11" fill="#3c7d7a" text-anchor="middle">responde ante el regulador</text> <path d="M380,82 L380,112" fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u1t3b)"></path> <rect x="250" y="112" width="260" height="50" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <text x="380" y="134" font-size="12.5" font-weight="700" fill="#12324f" text-anchor="middle">SABIS Spain (filial de Sabadell)</text> <text x="380" y="151" font-size="11" fill="#5b6876" text-anchor="middle">diseña, construye, prueba, migra y opera</text> <g fill="none" stroke="#8fb3d1" stroke-width="1.4" marker-end="url(#u1t3b)"><path d="M320,162 C280,184 220,196 170,208"></path><path d="M360,162 C350,184 340,196 330,208"></path><path d="M400,162 C410,184 420,196 430,208"></path><path d="M440,162 C480,184 540,196 590,208"></path></g> <g fill="#f5f7fa" stroke="#cfd8e3"><rect x="90" y="208" width="160" height="44" rx="8"></rect><rect x="270" y="208" width="120" height="44" rx="8"></rect><rect x="400" y="208" width="120" height="44" rx="8"></rect><rect x="530" y="208" width="160" height="44" rx="8"></rect></g> <g text-anchor="middle" font-size="11" fill="#12324f"><text x="170" y="228">tercero</text><text x="170" y="242" fill="#5b6876">(cuarta parte de TSB)</text><text x="330" y="234">tercero</text><text x="460" y="234">tercero</text><text x="610" y="228">hasta 85 en total</text><text x="610" y="242" fill="#5b6876">4 de ellos críticos</text></g>
</svg>
</div>
<p>Los reguladores concluyeron que las causas técnicas directas estaban en la configuración, la capacidad y el código. También encontraron fallas de gestión en la planificación, las pruebas, el riesgo y la subcontratación. Entre ellas, que las fases de prueba se corrieron en paralelo para cumplir la fecha, que las pruebas terminaron el día anterior a decidir la migración, y que se redujo el alcance de una prueba no funcional de configuración activo-activo en los centros de datos, sin que se evaluara el riesgo de no hacerla. El aviso sostiene que, de haberse hecho, probablemente se habría hallado un problema de configuración que dejó sin servicio la banca por internet y móvil.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Dos correcciones frente a lo que circula
</div>
</div>
<div class="callout-body-container callout-body">
<p>En la prensa circula la idea de “cerca de dos millones de clientes sin acceso durante cinco días”. Los documentos oficiales dicen que todas las sucursales y una parte importante de los 5,2 millones de clientes se vieron afectados, y que la normalidad volvió en diciembre. Tampoco aparece en el Aviso Final la afirmación, que se repite en la prensa, de que en 2020 TSB trasladó su operación a IBM, así que no la usamos. Quien operaba la plataforma era SABIS, filial de la casa matriz, no un tercero independiente lejano.</p>
</div>
</div>
<p>Qué control faltó: gestión del riesgo de subcontratación (saber quiénes eran las cuartas partes), pruebas no funcionales completas (carga, configuración) y una decisión de salida a producción con criterios de aceptación medibles. El mensaje para el curso es que certificar al proveedor directo no basta si no ves la cadena.</p>
</section>
<section id="crowdstrike-19-de-julio-de-2024" class="level3">
<h3 class="anchored" data-anchor-id="crowdstrike-19-de-julio-de-2024">CrowdStrike, 19 de julio de 2024</h3>
<p>CrowdStrike es una empresa de seguridad cuyo programa, el sensor Falcon, corre dentro del sistema operativo de millones de computadores. El 19 de julio de 2024 distribuyó una actualización de contenido que dejó sin arrancar a una gran cantidad de equipos Windows.</p>
<p>Pregunta de análisis. Si una actualización llega a todos los clientes al mismo tiempo, ¿qué mecanismo limitaría el daño de un defecto que las pruebas no vieron?</p>
<p>La fuente primaria es el análisis de causa raíz que CrowdStrike publicó el 6 de agosto de 2024, sobre el archivo de canal 291. Dice lo siguiente:</p>
<ul>
<li>Un tipo de plantilla definía 21 campos de entrada, pero el código que invocaba al intérprete de contenido proporcionaba solo 20 valores.</li>
<li>Esa diferencia pasó las pruebas anteriores, entre otras razones porque en ellas el campo 21 se comparaba con un comodín.</li>
<li>El 19 de julio se desplegaron dos instancias nuevas, una de las cuales usaba un criterio sin comodín en el campo 21. El intérprete leyó fuera de los límites de un arreglo.</li>
<li>El validador de contenido tenía un error de lógica, porque suponía que se proporcionarían 21 entradas, y por eso dejó pasar la instancia defectuosa.</li>
<li>Como mejoras, CrowdStrike anunció comprobaciones de límites en tiempo de ejecución, más pruebas, despliegue por anillos (de pocos equipos a muchos, con espera para observar) y control del cliente sobre cuándo recibe el contenido.</li>
</ul>
<p>Microsoft estimó que la actualización afectó a unos 8,5 millones de dispositivos Windows, menos del uno por ciento de todos, y señaló que el impacto fue mayor porque esos equipos ejecutan servicios críticos.</p>
<p>La causa es un defecto de calidad propio, sin ataque externo. Qué control faltó: validación del número de entradas al compilar, pruebas con casos sin comodín, y un despliegue gradual que habría detenido el daño en los primeros anillos.</p>
</section>
<section id="qué-tienen-en-común-los-tres-casos" class="level3">
<h3 class="anchored" data-anchor-id="qué-tienen-en-común-los-tres-casos">Qué tienen en común los tres casos</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Caso</th>
<th>Dónde estaba el defecto</th>
<th>Qué control faltó</th>
<th>Cómo se aplica shift-left</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Knight Capital</td>
<td>Un servidor sin actualizar y código muerto reactivado</td>
<td>Segunda revisión del despliegue, alertas, retiro de código muerto</td>
<td>Automatizar el despliegue y verificar la versión de cada servidor antes de abrir</td>
</tr>
<tr class="even">
<td>TSB</td>
<td>Configuración, capacidad y código, más una cadena de proveedores opaca</td>
<td>Pruebas no funcionales completas, control del riesgo de subcontratación</td>
<td>Definir criterios de salida medibles y exigir visibilidad de la cadena al contratar</td>
</tr>
<tr class="odd">
<td>CrowdStrike 2024</td>
<td>Desajuste de 21 contra 20 entradas y un validador que lo aceptó</td>
<td>Validación al compilar, pruebas sin comodín, despliegue gradual</td>
<td>Probar los datos de configuración como si fueran código y desplegar por anillos</td>
</tr>
</tbody>
</table>
<p>En los tres, la decisión de lanzar tuvo menos evidencia de la que parecía. En los tres falló el proceso de la última milla: el despliegue, la prueba de carga o la validación de una configuración. Y en los tres, el costo superó mucho al de los controles que faltaron.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 4. Dónde pondrías el control
</div>
</div>
<div class="callout-body-container callout-body">
<p>La clínica va a desplegar la versión 2.1 de su app en cuatro servidores. Propón tres controles de proceso, uno por cada caso de esta parte, que habrían evitado el equivalente de ese fallo. Escribe también qué evidencia guardarías para demostrar que el control se aplicó.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Equivalente a Knight: un script que, antes de abrir la agenda, compara la versión instalada en cada servidor con la versión esperada y bloquea la apertura si alguno difiere. Evidencia: el registro de esa verificación con fecha y versiones.</li>
<li>Equivalente a TSB: una lista de proveedores y subproveedores que tocan datos de pacientes, exigida en el contrato, y una prueba de carga con el volumen del día más lleno (por ejemplo, todas las citas de un lunes) antes de salir a producción. Evidencia: la lista firmada y el informe de la prueba de carga.</li>
<li>Equivalente a CrowdStrike: un despliegue por anillos, primero un servidor, luego dos y al final los cuatro, con un tiempo de observación entre anillos y un botón de reversa. Evidencia: el registro de cada anillo y la métrica de errores observada.</li>
</ul>
<p>Otras respuestas son válidas si el control es verificable y deja un registro.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-6.-estándares-y-contexto-colombiano" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="parte-6.-estándares-y-contexto-colombiano"><span class="header-section-number">9</span> Parte 6. Estándares y contexto colombiano</h2>
<section id="los-estándares-como-idioma-común" class="level3">
<h3 class="anchored" data-anchor-id="los-estándares-como-idioma-común">Los estándares como idioma común</h3>
<p>Cuando una clínica colombiana contrata a un proveedor en otro país, ninguna de las dos partes puede leer el código de la otra antes de firmar. Los estándares internacionales funcionan como un idioma común, porque las dos partes entienden lo mismo cuando alguien dice “cumplimos esta norma”.</p>
<p>La norma ISO 9000:2015 define la calidad como el grado en que un conjunto de características inherentes de un objeto cumple los requisitos. Esa definición sirve igual para un tornillo que para un sistema de software. La ISO 9001 fija los requisitos de un sistema de gestión de la calidad, y es la certificación de calidad más reconocida. Para software existe la guía ISO/IEC/IEEE 90003:2018, que explica cómo aplicar la ISO 9001:2015 al desarrollo y el mantenimiento de software. Esa guía no está pensada como criterio de certificación y no cambia los requisitos de la ISO 9001.</p>
</section>
<section id="vigente-e-histórico-la-iso-9001" class="level3">
<h3 class="anchored" data-anchor-id="vigente-e-histórico-la-iso-9001">Vigente e histórico: la ISO 9001</h3>
<p>La ISO 9001 vigente durante años fue la de 2015. Según la ficha de ISO, la sexta edición, ISO 9001:2026, se publicó el 16 de septiembre de 2026, con tres años de transición. Los organismos de certificación sitúan el fin de la transición hacia septiembre de 2029, pero esa fecha depende de cada organismo: confírmala con el tuyo antes de citarla en un documento formal.</p>
<p>Para el estudiante, lo importante es que una norma se revisa cada varios años y que un certificado siempre se refiere a una edición.</p>
</section>
<section id="qué-aporta-cada-estándar-en-este-curso" class="level3">
<h3 class="anchored" data-anchor-id="qué-aporta-cada-estándar-en-este-curso">Qué aporta cada estándar en este curso</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Estándar</th>
<th>Qué resuelve</th>
<th>Dónde se estudia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ISO 9001</td>
<td>Sistema de gestión de la calidad de una organización</td>
<td>Esta parte y la Unidad 3</td>
</tr>
<tr class="even">
<td>ISO/IEC/IEEE 90003:2018</td>
<td>Guía para aplicar la ISO 9001 al software</td>
<td>Esta parte</td>
</tr>
<tr class="odd">
<td>ISO/IEC 25010:2023</td>
<td>Modelo de calidad del producto, con nueve características</td>
<td>Tema 2 de esta unidad</td>
</tr>
<tr class="even">
<td>Modelo de madurez de procesos (CMMI)</td>
<td>Evaluar qué tan maduros son los procesos de una organización</td>
<td>Unidad 3</td>
</tr>
</tbody>
</table>
</section>
<section id="qué-certifica-una-certificación" class="level3">
<h3 class="anchored" data-anchor-id="qué-certifica-una-certificación">Qué certifica una certificación</h3>
<p>Una certificación ISO 9001 dice que el sistema de gestión de la calidad de una organización cumple la norma, según una auditoría de un tercero. No revisa el código ni garantiza productos sin defectos. El caso de Knight Capital, que tenía procesos y controles de cumplimiento, muestra que tener un sistema no impide un fallo en un punto sin control. Cuando alguien dice “está certificado”, pregunta qué norma, qué edición, qué alcance y quién lo certificó.</p>
</section>
<section id="colombia-icontec-onac-y-la-sic" class="level3">
<h3 class="anchored" data-anchor-id="colombia-icontec-onac-y-la-sic">Colombia: ICONTEC, ONAC y la SIC</h3>
<p>En Colombia hay tres entidades que conviene distinguir.</p>
<ul>
<li>ICONTEC (Instituto Colombiano de Normas Técnicas y Certificación) ejerce las funciones de organismo nacional de normalización y es el miembro colombiano de ISO. Las normas técnicas colombianas (NTC) adoptan normas internacionales, como la NTC-ISO 9001:2015.</li>
<li>ONAC (Organismo Nacional de Acreditación de Colombia) acredita la competencia de los organismos que certifican, es decir, vigila a quienes dan los certificados.</li>
<li>La Superintendencia de Industria y Comercio (SIC) es la autoridad de protección de datos personales, según la Ley 1581 de 2012.</li>
</ul>
<p>La cadena completa es: una norma (ISO), su adopción nacional (ICONTEC), un organismo certificador, y un acreditador que vigila al certificador (ONAC). Quien compra un certificado puede preguntar si el organismo está acreditado.</p>
</section>
</section>
<section id="parte-7.-equipos-distribuidos-y-trabajo-asíncrono" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="parte-7.-equipos-distribuidos-y-trabajo-asíncrono"><span class="header-section-number">10</span> Parte 7. Equipos distribuidos y trabajo asíncrono</h2>
<section id="por-qué-la-distancia-cuesta" class="level3">
<h3 class="anchored" data-anchor-id="por-qué-la-distancia-cuesta">Por qué la distancia cuesta</h3>
<p>Cuando el equipo de la clínica en Medellín trabaja con un proveedor en otro país, la calidad depende de que los dos equipos se coordinen. Herbsleb y Mockus (<em>IEEE Transactions on Software Engineering</em>, 2003) estudiaron datos de un proyecto industrial de gran tamaño y hallaron que las tareas distribuidas entre sitios tardaban cerca de dos veces y media más que tareas parecidas hechas en un solo lugar. Ese es un estudio de un caso, no una ley, pero apunta a algo que se repite en la práctica, y es que la coordinación entre sitios es un trabajo propio que hay que diseñar.</p>
</section>
<section id="cuánto-solapan-dos-horarios" class="level3">
<h3 class="anchored" data-anchor-id="cuánto-solapan-dos-horarios">Cuánto solapan dos horarios</h3>
<p>Colombia está en UTC-5 y no usa horario de verano. India está en UTC+5:30 y tampoco. Supón que el equipo de Medellín trabaja de 8:00 a 17:00 y el de India de 9:00 a 18:00, cada uno en su hora.</p>
<ol type="1">
<li>Convierte a UTC. Medellín 8:00 es 13:00 UTC y 17:00 es 22:00 UTC. India 9:00 es 3:30 UTC y 18:00 es 12:30 UTC.</li>
<li>Busca el cruce. India termina a las 12:30 UTC y Medellín empieza a las 13:00 UTC.</li>
<li>Concluye. No hay ni un minuto de trabajo simultáneo. Cada equipo trabaja mientras el otro duerme.</li>
</ol>
<div class="diagrama">
<svg viewbox="0 0 760 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Eje de 0 a 24 horas UTC: el horario de India, de 3:30 a 12:30, y el de Medellín, de 13:00 a 22:00, no se cruzan; con un ajuste, el cruce es de 4 horas y media" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Horario laboral en UTC: Medellín y un equipo en India</text> <line x1="60" y1="60" x2="700" y2="60" stroke="#cfd8e3" stroke-width="1.4"></line> <g font-size="10.5" fill="#5b6876" text-anchor="middle"><text x="60" y="52">0</text><text x="167" y="52">4</text><text x="273" y="52">8</text><text x="380" y="52">12</text><text x="487" y="52">16</text><text x="593" y="52">20</text><text x="700" y="52">24 UTC</text></g> <text x="60" y="92" font-size="11.5" font-weight="600" fill="#12324f">Sin ajuste</text> <rect x="153" y="100" width="240" height="26" rx="5" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="407" y="130" width="240" height="26" rx="5" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="273" y="118" font-size="11" fill="#12324f" text-anchor="middle">India 9:00 a 18:00 (3:30 a 12:30 UTC)</text> <text x="527" y="148" font-size="11" fill="#0e6f6c" text-anchor="middle">Medellín 8:00 a 17:00 (13:00 a 22:00 UTC)</text> <text x="60" y="190" font-size="11.5" font-weight="600" fill="#12324f">Con ajuste</text> <rect x="233" y="198" width="240" height="22" rx="5" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="407" y="224" width="240" height="22" rx="5" fill="#e4f2f1" stroke="#8fc9c5"></rect> <rect x="407" y="198" width="67" height="22" rx="5" fill="#fff3d6" stroke="#e6c46f"></rect> <text x="225" y="213" font-size="10.5" fill="#12324f" text-anchor="end">India 12:00 a 21:00 hora local</text> <text x="655" y="240" font-size="10.5" fill="#0e6f6c" text-anchor="start">Medellín</text> <text x="484" y="213" font-size="10.5" fill="#855400" text-anchor="start">cruce de 2 h 30</text>
</svg>
</div>
<p>La mitad de abajo del diagrama muestra un ajuste posible. El equipo de India desplaza su jornada de 12:00 a 21:00 hora local, que equivale a 6:30 a 15:30 UTC. Con eso el cruce con Medellín va de 13:00 a 15:30 UTC, es decir, 2 horas y 30 minutos, que en Medellín son de 8:00 a 10:30. Es poco, pero alcanza para una reunión de relevo diaria. El Reto 5 te pide hacer el mismo cálculo con otros números.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 5. Diseña el relevo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dos equipos, uno en Medellín (UTC-5) y otro en un país de UTC+8 (sin horario de verano), trabajan de 9:00 a 18:00 hora local cada uno. Calcula el cruce de horarios. Después propón tres prácticas para que un defecto reportado a la tarde en Medellín se resuelva sin esperar un día completo.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Medellín, 9:00 a 18:00 hora local, es de 14:00 a 23:00 UTC.</li>
<li>El otro país, 9:00 a 18:00 hora local con UTC+8, es de 1:00 a 10:00 UTC.</li>
<li>El segundo equipo termina a las 10:00 UTC y Medellín empieza a las 14:00 UTC. No hay cruce, y quedan 4 horas entre el fin de uno y el inicio del otro.</li>
<li>Práctica 1: una nota de relevo escrita al cerrar la jornada, con qué se hizo, qué falta, qué bloquea y dónde está el código. Quien recibe puede trabajar sin preguntar.</li>
<li>Práctica 2: cada reporte de defecto lleva pasos para reproducirlo, el resultado esperado y el obtenido, y una evidencia (captura, registro). Así no se pierde un ciclo de preguntas.</li>
<li>Práctica 3: definición compartida de “hecho”, con criterios de aceptación escritos, de modo que cada equipo sepa cuándo puede cerrar sin esperar al otro.</li>
<li>Práctica 4 (opcional): una ventana corta y fija de sincronía, aunque sea una hora desplazada, para decisiones que no se resuelven por escrito.</li>
</ul>
<p>Otras prácticas son válidas mientras reduzcan los ciclos de espera.</p>
</div>
</div>
</div>
</section>
<section id="comunicación-asíncrona-tres-hábitos-que-protegen-la-calidad" class="level3">
<h3 class="anchored" data-anchor-id="comunicación-asíncrona-tres-hábitos-que-protegen-la-calidad">Comunicación asíncrona: tres hábitos que protegen la calidad</h3>
<p>Cuando no hay cruce, la comunicación asíncrona (por escrito, sin esperar respuesta inmediata) es lo que sostiene el trabajo. Tres hábitos la hacen funcionar:</p>
<ul>
<li>Escribir decisiones, no solo conversarlas. Si una regla del turno 20 se decide en una llamada, queda en un documento o en el cambio de código.</li>
<li>Cambios pequeños y revisables. Ejemplo ilustrativo, no una medición: un cambio que el otro equipo puede revisar en 20 minutos avanza, y uno de 3.000 líneas espera un día.</li>
<li>Evidencia adjunta. Cada reporte y cada entrega llevan sus pruebas o capturas para que el otro lado no tenga que reproducir todo.</li>
</ul>
<p>Estas son prácticas de coordinación, y no sustituyen un estándar. Funcionan junto con él: el estándar dice qué debe cumplirse y el trabajo asíncrono bien hecho deja el registro de que se cumplió.</p>
</section>
</section>
<section id="parte-8.-cumplimiento-regulatorio-y-sbom" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="parte-8.-cumplimiento-regulatorio-y-sbom"><span class="header-section-number">11</span> Parte 8. Cumplimiento regulatorio y SBOM</h2>
<p>Un producto que cruza fronteras queda sujeto a las leyes de cada lugar donde se usa. Tres marcos sirven de ejemplo: uno de seguridad de productos en la Unión Europea, otro de inteligencia artificial, y uno colombiano de datos personales.</p>
<div class="diagrama">
<svg viewbox="0 0 760 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Línea de tiempo con fechas de la Ley de Ciberresiliencia de la UE y de la Ley de IA de la UE, de 2024 a 2028, con una marca de hoy el 3 de octubre de 2026" font-family="Segoe UI, Inter, system-ui, sans-serif">
<text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Fechas clave, según los textos vigentes a octubre de 2026</text> <line x1="50" y1="150" x2="720" y2="150" stroke="#8fb3d1" stroke-width="2"></line> <g font-size="10.5" fill="#5b6876" text-anchor="middle"><text x="70" y="168">2024</text><text x="220" y="168">2025</text><text x="400" y="168">2026</text><text x="560" y="168">2027</text><text x="690" y="168">2028</text></g> <line x1="437" y1="120" x2="437" y2="180" stroke="#0e6f6c" stroke-width="2"></line> <text x="437" y="196" font-size="11" font-weight="700" fill="#0e6f6c" text-anchor="middle">Hoy, 3 oct 2026</text> <g fill="#e4f2f1" stroke="#8fc9c5"><circle cx="75" cy="150" r="5"></circle><circle cx="347" cy="150" r="5"></circle><circle cx="445" cy="150" r="5"></circle><circle cx="592" cy="150" r="5"></circle></g> <g fill="#eef4fa" stroke="#c7d6e6"><circle cx="85" cy="150" r="5"></circle><circle cx="180" cy="150" r="5"></circle><circle cx="260" cy="150" r="5"></circle><circle cx="410" cy="150" r="5"></circle><circle cx="585" cy="150" r="5"></circle><circle cx="700" cy="150" r="5"></circle></g> <g font-size="10.5" fill="#12324f"><text x="30" y="132">CRA: en vigor</text><text x="30" y="118">10 dic 2024</text><text x="285" y="132" text-anchor="end">CRA: organismos</text><text x="285" y="118" text-anchor="end">evaluadores 11 jun 2026</text><text x="470" y="132">CRA: notificar</text><text x="470" y="118">vulnerabilidades 11 sep 2026</text><text x="610" y="132">CRA: obligaciones</text><text x="610" y="118">completas 11 dic 2027</text></g> <g font-size="10.5" fill="#12324f"><text x="95" y="214">IA: en vigor 1 ago 2024</text><text x="195" y="232">IA: prohibiciones 2 feb 2025</text><text x="270" y="250">IA: modelos generales 2 ago 2025</text><text x="420" y="268">IA: transparencia 2 ago 2026</text><text x="500" y="286">IA: alto riesgo 2 dic 2027</text><text x="715" y="214" text-anchor="end">IA: alto riesgo en productos 2 ago 2028</text></g> <text x="40" y="48" font-size="11" fill="#5b6876">Verde: Ley de Ciberresiliencia (CRA). Azul: Ley de IA.</text>
</svg>
</div>
<section id="ley-de-ciberresiliencia-de-la-ue-cra" class="level3">
<h3 class="anchored" data-anchor-id="ley-de-ciberresiliencia-de-la-ue-cra">Ley de Ciberresiliencia de la UE (CRA)</h3>
<p>El Reglamento (UE) 2024/2847, conocido como <em>Cyber Resilience Act</em>, entró en vigor el 10 de diciembre de 2024. Establece requisitos de ciberseguridad para los productos con elementos digitales que se comercializan en la Unión Europea, tanto el software como el hardware, y también las soluciones de procesamiento remoto de datos que esos productos necesitan para funcionar. Aplica a fabricantes, importadores y distribuidores, de modo que un fabricante de fuera de la UE queda cubierto si vende allí. Un servicio puro de software como servicio queda por fuera del CRA, pero se rige por otra norma europea, la directiva NIS2.</p>
<p>Las fechas, según el artículo 71 del reglamento, son tres. El capítulo sobre organismos de evaluación de la conformidad se aplica desde el 11 de junio de 2026. La obligación de notificar vulnerabilidades explotadas activamente e incidentes graves (artículo 14), con una alerta temprana en 24 horas, se aplica desde el 11 de septiembre de 2026, es decir, ya está vigente en octubre de 2026. El resto del reglamento, que incluye los requisitos de seguridad por diseño, la gestión de vulnerabilidades, la evaluación de conformidad y el marcado CE, se aplica desde el 11 de diciembre de 2027.</p>
<p>Los resúmenes jurídicos consultados citan sanciones de hasta 15 millones de euros o el 2,5 % de la facturación anual mundial por incumplir los requisitos esenciales, y el texto de ese artículo no está verificado en esta guía, así que trata la cifra como no verificada en la fuente primaria.</p>
</section>
<section id="ley-de-ia-de-la-ue" class="level3">
<h3 class="anchored" data-anchor-id="ley-de-ia-de-la-ue">Ley de IA de la UE</h3>
<p>El Reglamento (UE) 2024/1689 regula los sistemas de inteligencia artificial según su riesgo. Entró en vigor el 1 de agosto de 2024. Las prohibiciones y la obligación de alfabetización en IA se aplican desde el 2 de febrero de 2025, y las obligaciones de los modelos de propósito general desde el 2 de agosto de 2025. Las reglas de transparencia, como informar a las personas de que están hablando con un sistema de IA, se aplican desde el 2 de agosto de 2026.</p>
<p>Las obligaciones para sistemas de alto riesgo se iban a aplicar desde el 2 de agosto de 2026. Un reglamento llamado Ómnibus Digital sobre IA, acordado en mayo de 2026 y en vigor desde julio de 2026 según los análisis de bufetes consultados, las aplazó al 2 de diciembre de 2027 para los sistemas independientes y al 2 de agosto de 2028 para los incorporados en productos regulados. Verifica el texto oficial en EUR-Lex antes de citar números de artículo. Una segunda parte del Ómnibus, sobre datos y ciberseguridad, seguía en negociación cuando se escribió la guía.</p>
</section>
<section id="ley-1581-de-2012-de-colombia" class="level3">
<h3 class="anchored" data-anchor-id="ley-1581-de-2012-de-colombia">Ley 1581 de 2012 de Colombia</h3>
<p>La Ley Estatutaria 1581 de 2012 regula el tratamiento de datos personales en Colombia. Lo que debes conocer para una app de turnos es lo siguiente, y todo está en el texto de la ley:</p>
<ul>
<li>El artículo 5 define como datos sensibles los que afectan la intimidad o pueden generar discriminación, y nombra los datos relativos a la salud.</li>
<li>El artículo 6 prohíbe tratar datos sensibles salvo excepciones, entre ellas la autorización explícita del titular.</li>
<li>Los artículos 17 y 18 dan deberes al responsable (quien decide sobre los datos) y al encargado (quien los trata por cuenta del responsable), como conservar la autorización, informar la finalidad y proteger la información.</li>
<li>El artículo 26 prohíbe transferir datos personales a países que no proporcionen niveles adecuados de protección, con excepciones, como la autorización expresa e inequívoca del titular o el intercambio de datos médicos cuando lo exija el tratamiento por razones de salud.</li>
<li>El artículo 19 hace a la SIC la autoridad de protección de datos, y el artículo 23 le permite sancionar con multas de hasta 2.000 salarios mínimos mensuales legales vigentes, suspensión o cierre de operaciones de tratamiento.</li>
</ul>
<p>Para la clínica, esto significa que contratar a un proveedor en otro país que aloje los datos de los pacientes obliga a revisar el artículo 26, el contrato de encargo y la autorización de los titulares.</p>
</section>
<section id="sbom-la-lista-de-ingredientes-del-software" class="level3">
<h3 class="anchored" data-anchor-id="sbom-la-lista-de-ingredientes-del-software">SBOM: la lista de ingredientes del software</h3>
<p>Los marcos anteriores empujan a una práctica concreta, la <em>lista de materiales de software</em> (SBOM, por <em>software bill of materials</em>). Es un inventario legible por máquina de los componentes que contiene un producto, con su versión y su proveedor. Sirve para responder rápido a la pregunta “¿usamos el componente afectado por esta vulnerabilidad?”. El CRA exige que el fabricante identifique y documente los componentes del producto, incluso con una SBOM en un formato común y legible por máquina que cubra al menos las dependencias de primer nivel.</p>
<p>La NTIA de Estados Unidos fijó en 2021 siete datos mínimos para una SBOM: proveedor, nombre del componente, versión, otros identificadores únicos, relación de dependencia, autor de los datos de la SBOM y marca de tiempo. La CISA publicó en 2025 un borrador de actualización que amplía esa lista a nueve campos, y no verifiqué si ya es definitivo. Los dos formatos más usados son SPDX, que es la norma ISO/IEC 5962:2021, y CycloneDX, que es la norma ECMA-424.</p>
<p>Un fragmento ilustrativo de una SBOM en formato CycloneDX con un componente de la app de la clínica:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">{</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"bomFormat"</span><span class="fu">:</span> <span class="st">"CycloneDX"</span><span class="fu">,</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"specVersion"</span><span class="fu">:</span> <span class="st">"1.6"</span><span class="fu">,</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"version"</span><span class="fu">:</span> <span class="dv">1</span><span class="fu">,</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"metadata"</span><span class="fu">:</span> <span class="fu">{</span> <span class="dt">"timestamp"</span><span class="fu">:</span> <span class="st">"2026-10-03T12:00:00Z"</span> <span class="fu">},</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"components"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">{</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"library"</span><span class="fu">,</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"name"</span><span class="fu">:</span> <span class="st">"lodash"</span><span class="fu">,</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"version"</span><span class="fu">:</span> <span class="st">"4.17.21"</span><span class="fu">,</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"supplier"</span><span class="fu">:</span> <span class="fu">{</span> <span class="dt">"name"</span><span class="fu">:</span> <span class="st">"OpenJS Foundation"</span> <span class="fu">},</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"purl"</span><span class="fu">:</span> <span class="st">"pkg:npm/lodash@4.17.21"</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">}</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="ot">]</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">}</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 6. Qué marco aplica
</div>
</div>
<div class="callout-body-container callout-body">
<p>La Clínica Aurora quiere vender la licencia de su app a una red de clínicas en España. La app tiene un asistente virtual que responde preguntas de los pacientes, y guarda los datos en servidores de un proveedor en otro país. Indica qué marcos de esta parte se activan y por qué, y qué documento debería poder mostrar la clínica si un cliente europeo se lo pidiera.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>CRA: la clínica sería fabricante de un producto con elementos digitales comercializado en la UE, y su backend cuenta como procesamiento remoto de datos de ese producto. Debe poder demostrar seguridad por diseño, gestionar vulnerabilidades y, desde el 11 de septiembre de 2026, notificar las que se exploten activamente. Documento: la SBOM y el proceso de gestión de vulnerabilidades.</li>
<li>Ley de IA: el asistente es un sistema de IA que interactúa con personas, así que aplican las reglas de transparencia desde el 2 de agosto de 2026, que obligan a informar al paciente de que habla con una IA.</li>
<li>Ley 1581: sigue aplicando a los datos de pacientes colombianos. Los datos de salud son sensibles, y hospedar con un proveedor en otro país exige revisar el artículo 26.</li>
<li>A un cliente europeo también le serán exigibles las normas de protección de datos de la UE, que esta guía no desarrolla.</li>
</ul>
<p>El detalle de si un sistema concreto es de alto riesgo depende de su finalidad. Un asistente que solo responde preguntas administrativas es un caso distinto al de uno que prioriza pacientes por urgencia.</p>
</div>
</div>
</div>
</section>
</section>
<section id="errores-frecuentes" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="errores-frecuentes"><span class="header-section-number">12</span> Errores frecuentes</h2>
<ul>
<li>Citar una cifra de costo sin decir quién la calculó, de qué año y para qué país.</li>
<li>Presentar la curva de Boehm como una ley, sin decir que hay estudios donde no aparece.</li>
<li>Contar solo las horas de arreglar el defecto y olvidar soporte, ingresos perdidos y reputación.</li>
<li>Creer que una certificación ISO 9001 garantiza productos sin defectos, cuando certifica el sistema de gestión.</li>
<li>Suponer que certificar al proveedor directo cubre a todos sus subcontratistas.</li>
<li>Repetir datos de casos famosos de memoria. Los de Knight Capital y TSB circulan con errores que la fuente primaria corrige.</li>
<li>Pensar que un huso horario distinto solo es un detalle de agenda, cuando afecta los ciclos de pregunta y respuesta.</li>
<li>Dar por vigente una norma o ley sin revisar su edición y su fecha de aplicación.</li>
</ul>
</section>
<section id="autoevaluación" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="autoevaluación"><span class="header-section-number">13</span> Autoevaluación</h2>
<p>Responde sin mirar la guía. Marca tu opción y abre la clave para comprobarla. Es una práctica formativa y no tiene nota.</p>
<p><strong>1.</strong> Según el informe del CISQ de 2022, ¿qué afirmación es correcta?</p>
<p><label><input type="checkbox"> La mala calidad del software cuesta 2,41 billones de dólares al año en todo el mundo</label> <label><input type="checkbox"> Es una estimación para Estados Unidos, de al menos 2,41 billones de dólares en 2022, hecha por extrapolación</label> <label><input type="checkbox"> Es una medición exacta basada en los balances de las empresas</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. El informe estima un piso (“al menos”) para Estados Unidos y lo construye extrapolando fuentes públicas, sin que la mayoría de las organizaciones registre su propio costo de mala calidad.</p>
</div>
</div>
</div>
<p><strong>2.</strong> En el modelo de cuatro costos, ¿qué categoría incluye los talleres de requisitos?</p>
<p><label><input type="checkbox"> Prevención</label> <label><input type="checkbox"> Evaluación</label> <label><input type="checkbox"> Fallas internas</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Los talleres evitan que nazcan defectos. La evaluación busca defectos ya existentes, y las fallas internas son el costo de corregir los que se hallaron.</p>
</div>
</div>
</div>
<p><strong>3.</strong> Un equipo suma 10 horas de revisión de requisitos y 200 horas de pruebas. Después de entregar corrige 30 horas de fallas. ¿Cuántas horas de conformidad y cuántas de no conformidad hay, si todas las horas de falla son de no conformidad?</p>
<p><label><input type="checkbox"> 210 de conformidad y 30 de no conformidad</label> <label><input type="checkbox"> 10 de conformidad y 230 de no conformidad</label> <label><input type="checkbox"> 30 de conformidad y 210 de no conformidad</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. La revisión de requisitos (prevención) y las pruebas (evaluación) son conformidad, 10 más 200. Las 30 horas de falla son no conformidad.</p>
</div>
</div>
</div>
<p><strong>4.</strong> Boehm y Basili (2001) publican, para sistemas grandes y críticos, un factor de costo después de entregar de cerca de:</p>
<p><label><input type="checkbox"> 5</label> <label><input type="checkbox"> 10</label> <label><input type="checkbox"> 100</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 3. Para sistemas pequeños y no críticos dicen que el factor se parece más a 5.</p>
</div>
</div>
</div>
<p><strong>5.</strong> ¿Qué concluyen Menzies y colaboradores (2017) sobre los defectos tardíos, con datos de 171 proyectos?</p>
<p><label><input type="checkbox"> No encontraron el efecto de que los problemas tardíos sean más difíciles de resolver</label> <label><input type="checkbox"> Confirmaron que cuestan cien veces más</label> <label><input type="checkbox"> Mostraron que la prevención nunca se paga</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Eso no prueba que el efecto no exista en otros contextos, y por eso se recomienda medir el propio proyecto.</p>
</div>
</div>
</div>
<p><strong>6.</strong> En Knight Capital, ¿cuál fue la falla de despliegue?</p>
<p><label><input type="checkbox"> Un servidor de ocho no recibió el código nuevo y activó código antiguo con una bandera reutilizada</label> <label><input type="checkbox"> Un ataque informático externo</label> <label><input type="checkbox"> Un error de cálculo en el algoritmo nuevo</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1, según la orden de la SEC. La pérdida superó los 460 millones de dólares.</p>
</div>
</div>
</div>
<p><strong>7.</strong> ¿Qué mecanismo habría limitado el daño del defecto de CrowdStrike en 2024?</p>
<p><label><input type="checkbox"> Un despliegue por anillos con observación entre ellos</label> <label><input type="checkbox"> Más correos de aviso a los clientes</label> <label><input type="checkbox"> Cambiar el nombre del archivo de canal</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. CrowdStrike lo anunció como mejora, junto con validación de entradas y pruebas más completas.</p>
</div>
</div>
</div>
<p><strong>8.</strong> Un certificado ISO 9001 de un proveedor demuestra que:</p>
<p><label><input type="checkbox"> Su sistema de gestión de la calidad cumplió la norma en una auditoría de un tercero</label> <label><input type="checkbox"> Todo su software está libre de defectos</label> <label><input type="checkbox"> Sus subcontratistas también están certificados</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. El certificado cubre el sistema de gestión dentro de un alcance, y no el producto línea por línea ni la cadena de subcontratistas.</p>
</div>
</div>
</div>
<p><strong>9.</strong> Un equipo en Medellín (8:00 a 17:00 hora local) trabaja con otro en India (9:00 a 18:00 hora local). ¿Cuántas horas se cruzan?</p>
<p><label><input type="checkbox"> Ninguna</label> <label><input type="checkbox"> Cuatro</label> <label><input type="checkbox"> Nueve</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. Medellín es 13:00 a 22:00 UTC y la India es 3:30 a 12:30 UTC, sin cruce.</p>
</div>
</div>
</div>
<p><strong>10.</strong> Según la Ley 1581 de 2012, ¿cómo se clasifican los datos de salud?</p>
<p><label><input type="checkbox"> Datos públicos</label> <label><input type="checkbox"> Datos sensibles</label> <label><input type="checkbox"> Datos semiprivados</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 10
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. El artículo 5 los nombra como datos sensibles, y el artículo 6 prohíbe tratarlos salvo excepciones, como la autorización explícita.</p>
</div>
</div>
</div>
</section>
<section id="lo-que-te-llevas" class="level2" data-number="14">
<h2 data-number="14" class="anchored" data-anchor-id="lo-que-te-llevas"><span class="header-section-number">14</span> Lo que te llevas</h2>
<div class="checklist">
<p><strong>Al salir de este tema deberías poder explicar, sin mirar la guía</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Las cuatro razones por las que importa la calidad, con un ejemplo de la clínica para cada una</label></li>
<li><label><input type="checkbox">Qué mide y qué no mide la cifra de 2,41 billones del CISQ, y por qué se cita con cuidado</label></li>
<li><label><input type="checkbox">Los cuatro costos de la calidad y cómo se calcula el total de un producto</label></li>
<li><label><input type="checkbox">Qué dicen Boehm y Basili, qué responden Bossavit y Menzies, y qué es shift-left</label></li>
<li><label><input type="checkbox">Qué falló en Knight Capital, TSB y CrowdStrike, y qué control faltó en cada uno</label></li>
<li><label><input type="checkbox">Qué certifica una certificación y qué papel tienen ICONTEC, ONAC y la SIC</label></li>
<li><label><input type="checkbox">Cómo calcular el cruce de horarios entre dos países y qué prácticas reducen la espera</label></li>
<li><label><input type="checkbox">Qué exigen el CRA, la Ley de IA y la Ley 1581, y qué es una SBOM</label></li>
</ul>
</div>
</section>
<section id="glosario" class="level2" data-number="15">
<h2 data-number="15" class="anchored" data-anchor-id="glosario"><span class="header-section-number">15</span> Glosario</h2>
<ul>
<li><strong>Calidad.</strong> Grado en que un producto o servicio cumple sus requisitos y la necesidad de quien lo usa.</li>
<li><strong>Costo de la calidad.</strong> Suma de lo que se gasta para tener calidad (prevención y evaluación) y de lo que se gasta por no tenerla (fallas internas y externas).</li>
<li><strong>Prevención.</strong> Actividades que evitan que nazcan defectos, como talleres de requisitos o capacitación.</li>
<li><strong>Evaluación.</strong> Actividades que buscan defectos antes de entregar, como revisiones y pruebas.</li>
<li><strong>Falla interna.</strong> Costo de corregir un defecto hallado antes de entregar el producto.</li>
<li><strong>Falla externa.</strong> Costo de un defecto que llegó al usuario: arreglo, soporte, ingresos perdidos.</li>
<li><strong>Costo de conformidad.</strong> Prevención más evaluación.</li>
<li><strong>Costo de no conformidad.</strong> Fallas internas más fallas externas.</li>
<li><strong>Deuda técnica.</strong> Costo acumulado de arreglar soluciones deficientes que se dejaron en el software por rapidez.</li>
<li><strong>Curva de costo del defecto.</strong> Idea de que corregir un defecto cuesta más cuanto más tarde se detecta.</li>
<li><strong>Shift-left.</strong> Llevar las actividades de calidad a las fases tempranas del proyecto.</li>
<li><strong>Fuente primaria.</strong> Documento del investigador, regulador o fabricante que origina un dato, a diferencia de un resumen en prensa o en un blog.</li>
<li><strong>Extrapolación.</strong> Estimar un total a partir de una muestra o de pocos datos.</li>
<li><strong>Norma o estándar.</strong> Documento acordado que fija requisitos, reglas o directrices.</li>
<li><strong>Certificación.</strong> Declaración de un organismo independiente de que algo cumple una norma, tras evaluarlo.</li>
<li><strong>Acreditación.</strong> Reconocimiento de que un organismo es competente para certificar.</li>
<li><strong>ICONTEC.</strong> Organismo nacional de normalización de Colombia y miembro de ISO.</li>
<li><strong>ONAC.</strong> Organismo Nacional de Acreditación de Colombia.</li>
<li><strong>SIC.</strong> Superintendencia de Industria y Comercio, autoridad de protección de datos personales en Colombia.</li>
<li><strong>Outsourcing.</strong> Contratar a un tercero para construir o mantener parte de un producto.</li>
<li><strong>Cuarta parte.</strong> Proveedor del proveedor de una organización, que ella no contrató pero del que depende.</li>
<li><strong>Asíncrono.</strong> Comunicación que no exige respuesta inmediata, como un mensaje o una nota de relevo.</li>
<li><strong>UTC.</strong> Hora universal coordinada, la referencia para comparar husos horarios.</li>
<li><strong>CRA.</strong> <em>Cyber Resilience Act</em>, Reglamento (UE) 2024/2847, de ciberseguridad de productos con elementos digitales.</li>
<li><strong>Ley de IA.</strong> Reglamento (UE) 2024/1689, que regula los sistemas de inteligencia artificial según su riesgo.</li>
<li><strong>Dato sensible.</strong> Dato que afecta la intimidad o puede generar discriminación; la salud es uno.</li>
<li><strong>Responsable y encargado del tratamiento.</strong> El que decide sobre los datos y el que los trata por cuenta de aquel.</li>
<li><strong>SBOM.</strong> Lista de materiales de software: inventario legible por máquina de los componentes de un producto.</li>
<li><strong>SPDX y CycloneDX.</strong> Dos formatos de SBOM.</li>
<li><strong>Despliegue por anillos.</strong> Liberar un cambio a grupos crecientes de usuarios, con observación entre grupos.</li>
</ul>
</section>
<section id="bibliografía" class="level2" data-number="16">
<h2 data-number="16" class="anchored" data-anchor-id="bibliografía"><span class="header-section-number">16</span> Bibliografía</h2>
<p>Sobre costo y curva del defecto:</p>
<ul>
<li>Boehm, B. W. (1981). <em>Software Engineering Economics.</em> Prentice-Hall.</li>
<li>Boehm, B. y Basili, V. R. (2001). Software Defect Reduction Top 10 List. <em>IEEE Computer</em>, 34(1). <a href="https://umiacs.umd.edu/node/12156">Ficha</a>.</li>
<li>Menzies, T., Nichols, W., Shull, F. y Layman, L. (2017). Are Delayed Issues Harder to Resolve? Revisiting Cost-to-Fix of Defects throughout the Lifecycle. <em>Empirical Software Engineering</em>, 22(4). <a href="https://arxiv.org/abs/1609.04886">arXiv</a>.</li>
<li>Bossavit, L. (2013). <em>The Leprechauns of Software Engineering.</em> Leanpub. <a href="https://leanpub.com/leprechauns">Libro</a>.</li>
<li>RTI International y NIST (2002). <em>The Economic Impacts of Inadequate Infrastructure for Software Testing.</em> Planning Report 02-3. <a href="https://www.nist.gov/document/report02-3pdf">Informe</a>.</li>
<li>Krasner, H. (2022). <em>The Cost of Poor Software Quality in the US: A 2022 Report.</em> CISQ. <a href="https://www.it-cisq.org/wp-content/uploads/sites/6/2022/11/CPSQ-Report-Nov-22-2.pdf">Informe</a>.</li>
<li>Sommerville, I. (2016). <em>Software Engineering</em> (10.a ed.). Pearson.</li>
</ul>
<p>Casos reales:</p>
<ul>
<li>SEC (2013). <em>In the Matter of Knight Capital Americas LLC.</em> Release 34-70694, 16 de octubre de 2013. <a href="https://www.sec.gov/files/litigation/admin/2013/34-70694.pdf">Orden</a>.</li>
<li>FCA (2022). <em>Final Notice to TSB Bank plc.</em> <a href="https://www.fca.org.uk/publication/final-notices/tsb-bank-plc-2022.pdf">Aviso final</a>. Comunicado: <a href="https://www.fca.org.uk/news/press-releases/tsb-fined-48m-operational-resilience-failings">TSB fined 48.65m for operational resilience failings</a>.</li>
<li>CrowdStrike (6 de agosto de 2024). <em>Channel File 291 Incident, Root Cause Analysis.</em> <a href="https://www.crowdstrike.com/wp-content/uploads/2024/08/Channel-File-291-Incident-Root-Cause-Analysis-08.06.2024.pdf">Informe</a>.</li>
<li>Weston, D. (20 de julio de 2024). Helping our customers through the CrowdStrike outage. Blog de Microsoft. La cifra de 8,5 millones se consultó en la cobertura de <a href="https://techcrunch.com/2024/07/20/microsoft-says-8-5m-windows-devices-were-affected-by-crowdstrike-outage">TechCrunch</a>.</li>
</ul>
<p>Estándares y marco regulatorio:</p>
<ul>
<li>ISO 9000:2015. <em>Quality management systems, Fundamentals and vocabulary.</em> Según fuentes secundarias, la edición de 2026 la sustituye (ver Tema 1); confirma en iso.org.</li>
<li>NTIA (2021). <em>The Minimum Elements For a Software Bill of Materials (SBOM).</em> U.S. Department of Commerce.</li>
<li>ISO 9001:2015, y su sexta edición, ISO 9001:2026, publicada el 16 de septiembre de 2026 según la ficha de ISO.</li>
<li>ISO/IEC/IEEE 90003:2018. <em>Software engineering, Guidelines for the application of ISO 9001:2015 to computer software.</em> <a href="https://www.iso.org/standard/74348.html">Ficha</a>.</li>
<li>ISO/IEC 5962:2021. <em>SPDX.</em> <a href="https://www.iso.org/standard/81870.html">Ficha</a>. ECMA-424, <em>CycloneDX.</em> <a href="https://ecma-international.org/publications-and-standards/standards/ecma-424/">Ficha</a>.</li>
<li>Reglamento (UE) 2024/2847, <em>Cyber Resilience Act.</em> <a href="https://eur-lex.europa.eu/eli/reg/2024/2847/oj/eng">EUR-Lex</a>. <a href="https://digital-strategy.ec.europa.eu/en/policies/cyber-resilience-act">Página de la Comisión Europea</a>.</li>
<li>Reglamento (UE) 2024/1689, Ley de IA. <a href="https://eur-lex.europa.eu/eli/reg/2024/1689/oj/eng">EUR-Lex</a>. Sobre el aplazamiento, <a href="https://www.freshfields.com/en/our-thinking/blogs/technology-quotient/eu-ai-act-unpacked-34-the-final-digital-omnibus-on-ai-key-amendments-to-the-a-102nber">Freshfields</a> y <a href="https://www.gibsondunn.com/eu-ai-act-omnibus-agreement-postponed-high-risk-deadlines-and-other-key-changes/">Gibson Dunn</a>.</li>
<li>Congreso de Colombia (2012). <em>Ley Estatutaria 1581 de 2012.</em> <a href="https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=49981">Texto</a>.</li>
<li>CISA (2025). <em>2025 Minimum Elements for a Software Bill of Materials.</em> <a href="https://www.cisa.gov/resources-tools/resources/2025-minimum-elements-software-bill-materials-sbom">Página</a>.</li>
<li>ISO. <a href="https://www.iso.org/es/sobre/miembros">Miembros de ISO</a>. ONAC. <a href="https://onac.org.co">Sitio oficial</a>.</li>
<li>Herbsleb, J. D. y Mockus, A. (2003). An Empirical Study of Speed and Communication in Globally Distributed Software Development. <em>IEEE Transactions on Software Engineering</em>, 29(6), 481 a 494.</li>
</ul>
<div class="pie-doc">
<p>Calidad del software (CDS01). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>