<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Oscar Leonel Sánchez Conde">

<title>Tema 2. Validación de requisitos y verificación de requisitos – Clases María Cano 2026-02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../estilos/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-8713356167177fd77be9341a95314561.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-95bfa606010d176c52cfb6b551730f65.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-04/index.html">Unidad 4. Validación y verificación</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html">Tema 2. Validación y verificación de requisitos</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../../">Clases María Cano 2026-02</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación del curso</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 1. Calidad del software y estándares de calidad</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-01-que-es-calidad-quien-la-define/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es la calidad y quién la define</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-02-calidad-proceso-producto-iso-25010/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. Calidad de proceso y de producto: ISO/IEC 25010:2023</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-01/tema-03-importancia-costo-mundo-globalizado/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Importancia, costo y calidad en un mundo globalizado</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 2. Procesos de calidad del software. Modelos y métricas</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-01-sqa-relacion-ingenieria/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Qué es el SQA y su relación con la ingeniería de software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-02-calidad-ciclo-vida/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La calidad en cada fase del ciclo de vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-03-roles-habilidades/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Roles, responsabilidades y habilidades del personal de SQA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-04-actividades-sqa/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Actividades del SQA: revisiones, auditorías y gestión de configuración</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-05-modelos-metricas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Modelos y métricas de calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-02/tema-06-herramientas/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 6. Herramientas de SQA en la industria</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 3. Estándares de calidad aplicados al software</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-01-estandares-ieee/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Estándares IEEE para la calidad del software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-02-normas-iso/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 2. La familia ISO para software: SQuaRE, calidad de datos, gestión e IA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-03-usabilidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Marcos para evaluar la usabilidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-03/tema-04-madurez-spice-cmmi/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Madurez de procesos: SPICE y CMMI</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Unidad 4. Validación y verificación</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la unidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 1. Métodos, metodologías y estándares de verificación y validación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Tema 2. Validación y verificación de requisitos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-03-control-costo-calidad/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 3. Control de la calidad y costo de la calidad</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-04-nomenclatura-certificacion/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 4. Nomenclatura y certificación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../calidad-del-software/unidad-04/tema-05-factores-atam/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tema 5. Factores que determinan la calidad y el método ATAM</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta guía</h2>
   
  <ul>
  <li><a href="#objetivo-y-resultado-de-aprendizaje" id="toc-objetivo-y-resultado-de-aprendizaje" class="nav-link active" data-scroll-target="#objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</a></li>
  <li><a href="#ruta-de-estudio" id="toc-ruta-de-estudio" class="nav-link" data-scroll-target="#ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</a></li>
  <li><a href="#el-hilo-conductor-los-requisitos-de-la-app-de-turnos-de-la-clínica-aurora" id="toc-el-hilo-conductor-los-requisitos-de-la-app-de-turnos-de-la-clínica-aurora" class="nav-link" data-scroll-target="#el-hilo-conductor-los-requisitos-de-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: los requisitos de la app de turnos de la Clínica Aurora</a></li>
  <li><a href="#parte-1.-qué-es-un-requisito-y-qué-dice-la-isoiecieee-29148" id="toc-parte-1.-qué-es-un-requisito-y-qué-dice-la-isoiecieee-29148" class="nav-link" data-scroll-target="#parte-1.-qué-es-un-requisito-y-qué-dice-la-isoiecieee-29148"><span class="header-section-number">4</span> Parte 1. Qué es un requisito y qué dice la ISO/IEC/IEEE 29148</a>
  <ul class="collapse">
  <li><a href="#qué-es-un-requisito" id="toc-qué-es-un-requisito" class="nav-link" data-scroll-target="#qué-es-un-requisito">Qué es un requisito</a></li>
  <li><a href="#la-norma-isoiecieee-29148" id="toc-la-norma-isoiecieee-29148" class="nav-link" data-scroll-target="#la-norma-isoiecieee-29148">La norma ISO/IEC/IEEE 29148</a></li>
  <li><a href="#las-tres-capas-de-requisitos-que-reconoce-el-proceso" id="toc-las-tres-capas-de-requisitos-que-reconoce-el-proceso" class="nav-link" data-scroll-target="#las-tres-capas-de-requisitos-que-reconoce-el-proceso">Las tres capas de requisitos que reconoce el proceso</a></li>
  </ul></li>
  <li><a href="#parte-2.-cómo-es-un-buen-requisito" id="toc-parte-2.-cómo-es-un-buen-requisito" class="nav-link" data-scroll-target="#parte-2.-cómo-es-un-buen-requisito"><span class="header-section-number">5</span> Parte 2. Cómo es un buen requisito</a>
  <ul class="collapse">
  <li><a href="#características-de-un-requisito-individual" id="toc-características-de-un-requisito-individual" class="nav-link" data-scroll-target="#características-de-un-requisito-individual">Características de un requisito individual</a></li>
  <li><a href="#características-de-un-conjunto-de-requisitos" id="toc-características-de-un-conjunto-de-requisitos" class="nav-link" data-scroll-target="#características-de-un-conjunto-de-requisitos">Características de un conjunto de requisitos</a></li>
  <li><a href="#las-reglas-de-incose" id="toc-las-reglas-de-incose" class="nav-link" data-scroll-target="#las-reglas-de-incose">Las reglas de INCOSE</a></li>
  <li><a href="#la-plantilla-ears" id="toc-la-plantilla-ears" class="nav-link" data-scroll-target="#la-plantilla-ears">La plantilla EARS</a></li>
  <li><a href="#dos-palabras-que-cambian-el-requisito-debe-y-debería" id="toc-dos-palabras-que-cambian-el-requisito-debe-y-debería" class="nav-link" data-scroll-target="#dos-palabras-que-cambian-el-requisito-debe-y-debería">Dos palabras que cambian el requisito: debe y debería</a></li>
  </ul></li>
  <li><a href="#parte-3.-verificación-y-validación-de-requisitos" id="toc-parte-3.-verificación-y-validación-de-requisitos" class="nav-link" data-scroll-target="#parte-3.-verificación-y-validación-de-requisitos"><span class="header-section-number">6</span> Parte 3. Verificación y validación de requisitos</a>
  <ul class="collapse">
  <li><a href="#dos-preguntas-sobre-el-mismo-documento" id="toc-dos-preguntas-sobre-el-mismo-documento" class="nav-link" data-scroll-target="#dos-preguntas-sobre-el-mismo-documento">Dos preguntas sobre el mismo documento</a></li>
  <li><a href="#la-tabla-que-se-debe-tener-a-mano" id="toc-la-tabla-que-se-debe-tener-a-mano" class="nav-link" data-scroll-target="#la-tabla-que-se-debe-tener-a-mano">La tabla que se debe tener a mano</a></li>
  <li><a href="#verificar-tiene-tres-sentidos-que-se-confunden" id="toc-verificar-tiene-tres-sentidos-que-se-confunden" class="nav-link" data-scroll-target="#verificar-tiene-tres-sentidos-que-se-confunden">Verificar tiene tres sentidos que se confunden</a></li>
  <li><a href="#los-cuatro-métodos-con-que-se-verifica-un-requisito" id="toc-los-cuatro-métodos-con-que-se-verifica-un-requisito" class="nav-link" data-scroll-target="#los-cuatro-métodos-con-que-se-verifica-un-requisito">Los cuatro métodos con que se verifica un requisito</a></li>
  <li><a href="#cómo-se-valida-un-conjunto-de-requisitos" id="toc-cómo-se-valida-un-conjunto-de-requisitos" class="nav-link" data-scroll-target="#cómo-se-valida-un-conjunto-de-requisitos">Cómo se valida un conjunto de requisitos</a></li>
  </ul></li>
  <li><a href="#parte-4.-ejemplo-resuelto-seis-requisitos-mal-escritos-de-la-app-de-turnos" id="toc-parte-4.-ejemplo-resuelto-seis-requisitos-mal-escritos-de-la-app-de-turnos" class="nav-link" data-scroll-target="#parte-4.-ejemplo-resuelto-seis-requisitos-mal-escritos-de-la-app-de-turnos"><span class="header-section-number">7</span> Parte 4. Ejemplo resuelto: seis requisitos mal escritos de la app de turnos</a>
  <ul class="collapse">
  <li><a href="#paso-1.-los-seis-requisitos-de-partida" id="toc-paso-1.-los-seis-requisitos-de-partida" class="nav-link" data-scroll-target="#paso-1.-los-seis-requisitos-de-partida">Paso 1. Los seis requisitos de partida</a></li>
  <li><a href="#paso-2.-verificación-de-requisitos" id="toc-paso-2.-verificación-de-requisitos" class="nav-link" data-scroll-target="#paso-2.-verificación-de-requisitos">Paso 2. Verificación de requisitos</a></li>
  <li><a href="#paso-3.-reescritura" id="toc-paso-3.-reescritura" class="nav-link" data-scroll-target="#paso-3.-reescritura">Paso 3. Reescritura</a></li>
  <li><a href="#paso-4.-validación-con-los-interesados" id="toc-paso-4.-validación-con-los-interesados" class="nav-link" data-scroll-target="#paso-4.-validación-con-los-interesados">Paso 4. Validación con los interesados</a></li>
  </ul></li>
  <li><a href="#parte-5.-criterios-de-aceptación-con-bdd-y-gherkin" id="toc-parte-5.-criterios-de-aceptación-con-bdd-y-gherkin" class="nav-link" data-scroll-target="#parte-5.-criterios-de-aceptación-con-bdd-y-gherkin"><span class="header-section-number">8</span> Parte 5. Criterios de aceptación con BDD y Gherkin</a>
  <ul class="collapse">
  <li><a href="#qué-es-el-desarrollo-guiado-por-comportamiento" id="toc-qué-es-el-desarrollo-guiado-por-comportamiento" class="nav-link" data-scroll-target="#qué-es-el-desarrollo-guiado-por-comportamiento">Qué es el desarrollo guiado por comportamiento</a></li>
  <li><a href="#descubrir-el-mapa-de-ejemplos" id="toc-descubrir-el-mapa-de-ejemplos" class="nav-link" data-scroll-target="#descubrir-el-mapa-de-ejemplos">Descubrir: el mapa de ejemplos</a></li>
  <li><a href="#formular-gherkin" id="toc-formular-gherkin" class="nav-link" data-scroll-target="#formular-gherkin">Formular: Gherkin</a></li>
  <li><a href="#criterios-de-aceptación-bien-formados" id="toc-criterios-de-aceptación-bien-formados" class="nav-link" data-scroll-target="#criterios-de-aceptación-bien-formados">Criterios de aceptación bien formados</a></li>
  <li><a href="#cómo-el-bdd-une-las-dos-actividades" id="toc-cómo-el-bdd-une-las-dos-actividades" class="nav-link" data-scroll-target="#cómo-el-bdd-une-las-dos-actividades">Cómo el BDD une las dos actividades</a></li>
  </ul></li>
  <li><a href="#parte-6.-requisitos-no-funcionales-medibles" id="toc-parte-6.-requisitos-no-funcionales-medibles" class="nav-link" data-scroll-target="#parte-6.-requisitos-no-funcionales-medibles"><span class="header-section-number">9</span> Parte 6. Requisitos no funcionales medibles</a>
  <ul class="collapse">
  <li><a href="#por-qué-fallan-los-requisitos-de-calidad" id="toc-por-qué-fallan-los-requisitos-de-calidad" class="nav-link" data-scroll-target="#por-qué-fallan-los-requisitos-de-calidad">Por qué fallan los requisitos de calidad</a></li>
  <li><a href="#la-plantilla-de-seis-elementos" id="toc-la-plantilla-de-seis-elementos" class="nav-link" data-scroll-target="#la-plantilla-de-seis-elementos">La plantilla de seis elementos</a></li>
  <li><a href="#del-adjetivo-al-número-en-la-clínica" id="toc-del-adjetivo-al-número-en-la-clínica" class="nav-link" data-scroll-target="#del-adjetivo-al-número-en-la-clínica">Del adjetivo al número en la clínica</a></li>
  <li><a href="#cuánto-vale-una-cifra-de-disponibilidad" id="toc-cuánto-vale-una-cifra-de-disponibilidad" class="nav-link" data-scroll-target="#cuánto-vale-una-cifra-de-disponibilidad">Cuánto vale una cifra de disponibilidad</a></li>
  </ul></li>
  <li><a href="#parte-7.-la-matriz-de-trazabilidad-de-requisitos-rtm" id="toc-parte-7.-la-matriz-de-trazabilidad-de-requisitos-rtm" class="nav-link" data-scroll-target="#parte-7.-la-matriz-de-trazabilidad-de-requisitos-rtm"><span class="header-section-number">10</span> Parte 7. La matriz de trazabilidad de requisitos (RTM)</a>
  <ul class="collapse">
  <li><a href="#qué-es-y-para-qué-sirve" id="toc-qué-es-y-para-qué-sirve" class="nav-link" data-scroll-target="#qué-es-y-para-qué-sirve">Qué es y para qué sirve</a></li>
  <li><a href="#ejemplo-resuelto-la-rtm-de-los-once-requisitos" id="toc-ejemplo-resuelto-la-rtm-de-los-once-requisitos" class="nav-link" data-scroll-target="#ejemplo-resuelto-la-rtm-de-los-once-requisitos">Ejemplo resuelto: la RTM de los once requisitos</a></li>
  <li><a href="#cómo-se-lee-la-matriz" id="toc-cómo-se-lee-la-matriz" class="nav-link" data-scroll-target="#cómo-se-lee-la-matriz">Cómo se lee la matriz</a></li>
  <li><a href="#costos-y-buenas-prácticas" id="toc-costos-y-buenas-prácticas" class="nav-link" data-scroll-target="#costos-y-buenas-prácticas">Costos y buenas prácticas</a></li>
  </ul></li>
  <li><a href="#parte-8.-gestión-de-cambios-de-requisitos" id="toc-parte-8.-gestión-de-cambios-de-requisitos" class="nav-link" data-scroll-target="#parte-8.-gestión-de-cambios-de-requisitos"><span class="header-section-number">11</span> Parte 8. Gestión de cambios de requisitos</a>
  <ul class="collapse">
  <li><a href="#por-qué-cambian-los-requisitos" id="toc-por-qué-cambian-los-requisitos" class="nav-link" data-scroll-target="#por-qué-cambian-los-requisitos">Por qué cambian los requisitos</a></li>
  <li><a href="#el-proceso-de-seis-pasos" id="toc-el-proceso-de-seis-pasos" class="nav-link" data-scroll-target="#el-proceso-de-seis-pasos">El proceso de seis pasos</a></li>
  <li><a href="#ejemplo-resuelto-el-cupo-de-pediatría-sube-de-20-a-24" id="toc-ejemplo-resuelto-el-cupo-de-pediatría-sube-de-20-a-24" class="nav-link" data-scroll-target="#ejemplo-resuelto-el-cupo-de-pediatría-sube-de-20-a-24">Ejemplo resuelto: el cupo de Pediatría sube de 20 a 24</a></li>
  <li><a href="#la-volatilidad-como-indicador" id="toc-la-volatilidad-como-indicador" class="nav-link" data-scroll-target="#la-volatilidad-como-indicador">La volatilidad como indicador</a></li>
  </ul></li>
  <li><a href="#parte-9.-inteligencia-artificial-para-redactar-y-revisar-requisitos" id="toc-parte-9.-inteligencia-artificial-para-redactar-y-revisar-requisitos" class="nav-link" data-scroll-target="#parte-9.-inteligencia-artificial-para-redactar-y-revisar-requisitos"><span class="header-section-number">12</span> Parte 9. Inteligencia artificial para redactar y revisar requisitos</a>
  <ul class="collapse">
  <li><a href="#para-qué-sirve-y-para-qué-no" id="toc-para-qué-sirve-y-para-qué-no" class="nav-link" data-scroll-target="#para-qué-sirve-y-para-qué-no">Para qué sirve y para qué no</a></li>
  <li><a href="#los-riesgos" id="toc-los-riesgos" class="nav-link" data-scroll-target="#los-riesgos">Los riesgos</a></li>
  <li><a href="#las-reglas-de-uso-seguro" id="toc-las-reglas-de-uso-seguro" class="nav-link" data-scroll-target="#las-reglas-de-uso-seguro">Las reglas de uso seguro</a></li>
  <li><a href="#ejemplo-resuelto-filtrar-la-propuesta-de-una-herramienta-de-ia" id="toc-ejemplo-resuelto-filtrar-la-propuesta-de-una-herramienta-de-ia" class="nav-link" data-scroll-target="#ejemplo-resuelto-filtrar-la-propuesta-de-una-herramienta-de-ia">Ejemplo resuelto: filtrar la propuesta de una herramienta de IA</a></li>
  </ul></li>
  <li><a href="#errores-frecuentes" id="toc-errores-frecuentes" class="nav-link" data-scroll-target="#errores-frecuentes"><span class="header-section-number">13</span> Errores frecuentes</a></li>
  <li><a href="#lo-que-sigue" id="toc-lo-que-sigue" class="nav-link" data-scroll-target="#lo-que-sigue"><span class="header-section-number">14</span> Lo que sigue</a></li>
  <li><a href="#autoevaluación" id="toc-autoevaluación" class="nav-link" data-scroll-target="#autoevaluación"><span class="header-section-number">15</span> Autoevaluación</a></li>
  <li><a href="#lo-que-te-llevas" id="toc-lo-que-te-llevas" class="nav-link" data-scroll-target="#lo-que-te-llevas"><span class="header-section-number">16</span> Lo que te llevas</a></li>
  <li><a href="#glosario" id="toc-glosario" class="nav-link" data-scroll-target="#glosario"><span class="header-section-number">17</span> Glosario</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">18</span> Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-04/index.html">Unidad 4. Validación y verificación</a></li><li class="breadcrumb-item"><a href="../../../calidad-del-software/unidad-04/tema-02-validacion-verificacion-requisitos/index.html">Tema 2. Validación y verificación de requisitos</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Tema 2. Validación de requisitos y verificación de requisitos</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor/a</div>
    <div class="quarto-title-meta-contents">
             <p>Oscar Leonel Sánchez Conde </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">3 de octubre de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="ficha">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 89%">
</colgroup>
<tbody>
<tr class="odd">
<td>Unidad</td>
<td>Unidad 4. Validación y verificación</td>
</tr>
<tr class="even">
<td>Tema</td>
<td>Tema 2. Validación de requisitos y verificación de requisitos</td>
</tr>
</tbody>
</table>
</div>
<p><a href="../presentacion-interactiva.html" class="btn-curso">Presentación interactiva de la unidad</a></p>
<p>Tema anterior: <a href="../../../calidad-del-software/unidad-04/tema-01-metodos-estandares-vv/index.html">Tema 1. Métodos y estándares de verificación y validación</a>. Tema siguiente: <a href="../../../calidad-del-software/unidad-04/tema-03-control-costo-calidad/index.html">Tema 3. Control y costo de la calidad</a>.</p>
<section id="objetivo-y-resultado-de-aprendizaje" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="objetivo-y-resultado-de-aprendizaje"><span class="header-section-number">1</span> Objetivo y resultado de aprendizaje</h2>
<p>El resultado de aprendizaje de la Unidad 4 pide reconocer los diferentes usos de los procesos de validación de requerimientos y de verificación de requisitos. Este tema lo cubre de punta a punta. El Tema 1 separó verificar de validar sobre el producto terminado. Aquí esa separación se aplica antes de escribir una sola línea de código, cuando el producto todavía es un documento de requisitos.</p>
<p>Al terminar puedes:</p>
<ul>
<li>Explicar qué es un requisito y qué establece la norma ISO/IEC/IEEE 29148:2018 sobre los procesos y las características de los requisitos.</li>
<li>Distinguir la verificación de requisitos (¿están bien escritos?) de la validación de requisitos (¿son los que los interesados necesitan?), con el uso y el momento de cada una.</li>
<li>Detectar en un requisito la ambigüedad, la falta de verificabilidad, la falta de completitud, la mezcla de varias exigencias y la contradicción con otro requisito.</li>
<li>Reescribir un requisito vago como un requisito verificable, con plantillas como EARS y con reglas como las de INCOSE.</li>
<li>Redactar requisitos no funcionales medibles y criterios de aceptación en Gherkin.</li>
<li>Construir y leer una matriz de trazabilidad de requisitos (RTM), calcular su cobertura y usarla para analizar el impacto de un cambio.</li>
<li>Gestionar un cambio de requisitos con control de versiones y revalidación.</li>
<li>Usar la inteligencia artificial para redactar o revisar requisitos, con las reglas que evitan sus riesgos principales.</li>
</ul>
<p>Prerrequisitos: el Tema 1 de esta unidad (verificación y validación del producto) y los Temas 1 a 3 de la Unidad 1. Necesitas distinguir <em>requisito</em>, <em>defecto</em> y <em>falla</em>.</p>
</section>
<section id="ruta-de-estudio" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="ruta-de-estudio"><span class="header-section-number">2</span> Ruta de estudio</h2>
<p>Son unas 7 horas de trabajo independiente. Puedes partirlas en tres o cuatro sesiones. La presentación interactiva de la unidad usa los mismos conceptos y títulos de esta guía, así que sirve como repaso.</p>
<div class="calendario">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Parte</th>
<th>Qué haces</th>
<th>Tiempo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1. Qué es un requisito y qué dice la ISO/IEC/IEEE 29148</td>
<td>Lees los tipos de requisito y la vigencia de la norma</td>
<td>30 min</td>
</tr>
<tr class="even">
<td>2. Cómo es un buen requisito</td>
<td>Aprendes las características, las reglas de INCOSE y la plantilla EARS</td>
<td>50 min</td>
</tr>
<tr class="odd">
<td>3. Verificación y validación de requisitos</td>
<td>Distingues las dos actividades, sus métodos y sus momentos</td>
<td>45 min</td>
</tr>
<tr class="even">
<td>4. Ejemplo resuelto: seis requisitos mal escritos</td>
<td>Sigues los cuatro pasos completos sobre la app de la clínica y resuelves los Retos 1 y 2</td>
<td>80 min</td>
</tr>
<tr class="odd">
<td>5. Criterios de aceptación con BDD y Gherkin</td>
<td>Escribes escenarios con ejemplos y resuelves el Reto 3</td>
<td>45 min</td>
</tr>
<tr class="even">
<td>6. Requisitos no funcionales medibles</td>
<td>Conviertes atributos vagos en cifras verificables y resuelves el Reto 4</td>
<td>40 min</td>
</tr>
<tr class="odd">
<td>7. Matriz de trazabilidad (RTM)</td>
<td>Construyes la matriz del ejemplo, calculas su cobertura y resuelves el Reto 5</td>
<td>50 min</td>
</tr>
<tr class="even">
<td>8. Gestión de cambios de requisitos</td>
<td>Analizas el impacto de un cambio con la RTM y resuelves el Reto 6</td>
<td>40 min</td>
</tr>
<tr class="odd">
<td>9. Inteligencia artificial y requisitos</td>
<td>Aplicas las reglas de uso seguro y resuelves el Reto 7</td>
<td>35 min</td>
</tr>
<tr class="even">
<td>Cierre</td>
<td>Errores frecuentes, autoevaluación y glosario</td>
<td>40 min</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="el-hilo-conductor-los-requisitos-de-la-app-de-turnos-de-la-clínica-aurora" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="el-hilo-conductor-los-requisitos-de-la-app-de-turnos-de-la-clínica-aurora"><span class="header-section-number">3</span> El hilo conductor: los requisitos de la app de turnos de la Clínica Aurora</h2>
<p>El curso entero usa una app ficticia de turnos médicos. En este tema se vuelve al principio de su historia, cuando el equipo recoge lo que la app debe hacer. Los seis requisitos de partida salieron de notas de reuniones con recepción, pacientes y coordinación médica, y están mal escritos a propósito. Ninguna cifra de la clínica es real. Cada número propio se marca como ilustrativo.</p>
<p>El tema no cuenta un caso real obligatorio. Los casos reales de falla de la unidad están en el Tema 1 (verificación y validación del producto) y en el Tema 3 (control y costo de la calidad). Aquí el material es el proceso de trabajar con los requisitos y el ejemplo resuelto.</p>
</section>
<section id="parte-1.-qué-es-un-requisito-y-qué-dice-la-isoiecieee-29148" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="parte-1.-qué-es-un-requisito-y-qué-dice-la-isoiecieee-29148"><span class="header-section-number">4</span> Parte 1. Qué es un requisito y qué dice la ISO/IEC/IEEE 29148</h2>
<section id="qué-es-un-requisito" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-un-requisito">Qué es un requisito</h3>
<p>Un <em>requisito</em> es una declaración que identifica una capacidad, una característica o una restricción que el producto debe cumplir, y que se puede usar para decidir si el producto es aceptable. La frase importante es la última. Un requisito sirve cuando alguien puede decir, con evidencia, que se cumplió o que no se cumplió.</p>
<p>Los requisitos se agrupan en tres familias que conviene separar desde el principio.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Familia</th>
<th>Qué describe</th>
<th>Ejemplo en la clínica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Funcional</td>
<td>Lo que el sistema hace</td>
<td>“El sistema debe asignar el turno que el paciente confirme”</td>
</tr>
<tr class="even">
<td>No funcional (de calidad)</td>
<td>Cómo de bien lo hace: desempeño, seguridad, usabilidad, disponibilidad</td>
<td>“El sistema debe mostrar los turnos libres en 2 segundos o menos”</td>
</tr>
<tr class="odd">
<td>Restricción</td>
<td>Una condición impuesta que limita la solución</td>
<td>“Los datos personales del paciente se tratan conforme a la Ley 1581 de 2012”</td>
</tr>
</tbody>
</table>
<p>En la Unidad 1 viste que la calidad de un producto se descompone en características de la ISO/IEC 25010:2023. Los requisitos no funcionales son la forma de decir cuánto se exige de cada una. Esa norma se desarrolla en el Tema 2 de la Unidad 1, y aquí solo se usa como lista de atributos para completar requisitos.</p>
</section>
<section id="la-norma-isoiecieee-29148" class="level3">
<h3 class="anchored" data-anchor-id="la-norma-isoiecieee-29148">La norma ISO/IEC/IEEE 29148</h3>
<p>La norma que ordena el trabajo con requisitos es la ISO/IEC/IEEE 29148, <em>Systems and software engineering, Life cycle processes, Requirements engineering</em>. Su edición vigente es la segunda, de noviembre de 2018. Especifica los procesos que producen los requisitos de sistemas y de productos de software, incluidos los servicios, a lo largo del ciclo de vida. Da pautas para aplicar los procesos de requisitos de las normas ISO/IEC/IEEE 15288 y 12207 y define el contenido de los documentos que esos procesos producen.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Sobre la vigencia de la norma
</div>
</div>
<div class="callout-body-container callout-body">
<p>En la consulta de octubre de 2026 la ficha de la norma en el catálogo de BSI la lista como vigente y “en revisión”, y la ficha de ISO, según su resumen en buscador (la página de ISO bloqueó la lectura directa), indica una revisión confirmada en 2024. Eso significa que la edición de 2018 sigue en uso. No se verificó si hay una tercera edición en preparación. Antes de citar la edición en un documento, confírmala en iso.org.</p>
<p>La norma es de pago y no se leyó completa. Lo que esta guía dice sobre su contenido viene de su descripción oficial, de resúmenes de fuentes técnicas y de la guía de INCOSE, que la toma como base. Donde una afirmación depende de esas fuentes secundarias, el texto lo indica.</p>
</div>
</div>
<p>Según fuentes técnicas secundarias, la norma de 2018 sustituyó a tres estándares IEEE anteriores sobre requisitos, entre ellos el IEEE 830-1998, que durante años fue la referencia para escribir una especificación de requisitos de software. Esa es la razón por la que en libros y plantillas antiguos aún aparece el 830.</p>
</section>
<section id="las-tres-capas-de-requisitos-que-reconoce-el-proceso" class="level3">
<h3 class="anchored" data-anchor-id="las-tres-capas-de-requisitos-que-reconoce-el-proceso">Las tres capas de requisitos que reconoce el proceso</h3>
<p>La práctica que la norma organiza distingue de dónde viene un requisito. Esa distinción es la que hace posible validar y verificar después.</p>
<ol type="1">
<li>Necesidades de los interesados. Lo que quieren o necesitan las personas afectadas por el producto, dicho en su lenguaje.</li>
<li>Requisitos de los interesados. Las necesidades ya redactadas como exigencias para la solución, sin entrar en el diseño.</li>
<li>Requisitos del sistema o del software. Lo que el producto debe hacer y con qué calidad, redactado de forma verificable.</li>
</ol>
<p>Entre una capa y la siguiente hay trazabilidad (Parte 7). Cada requisito del software debe poder explicarse con una necesidad, y cada necesidad importante debe quedar cubierta por algún requisito.</p>
</section>
</section>
<section id="parte-2.-cómo-es-un-buen-requisito" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="parte-2.-cómo-es-un-buen-requisito"><span class="header-section-number">5</span> Parte 2. Cómo es un buen requisito</h2>
<section id="características-de-un-requisito-individual" class="level3">
<h3 class="anchored" data-anchor-id="características-de-un-requisito-individual">Características de un requisito individual</h3>
<p>Las fuentes secundarias que resumen la ISO/IEC/IEEE 29148 y la guía de INCOSE describen nueve características que debe tener cada requisito por separado. Las fuentes difieren en un nombre: una lista de INCOSE de 2016 trae “independiente de la implementación” donde otras traen “apropiado”. La tabla usa la segunda forma.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Característica</th>
<th>Pregunta que se hace sobre el requisito</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Necesario</td>
<td>¿Qué se pierde si se quita? Si nada, sobra</td>
</tr>
<tr class="even">
<td>Apropiado</td>
<td>¿Está en el nivel correcto de abstracción y para este producto?</td>
</tr>
<tr class="odd">
<td>No ambiguo</td>
<td>¿Admite una sola lectura, la misma para todos?</td>
</tr>
<tr class="even">
<td>Completo</td>
<td>¿Se entiende sin consultar otro texto? ¿Dice condiciones, valores y unidades?</td>
</tr>
<tr class="odd">
<td>Singular</td>
<td>¿Exige una sola cosa?</td>
</tr>
<tr class="even">
<td>Factible</td>
<td>¿Se puede lograr con el tiempo, el presupuesto y la tecnología disponibles?</td>
</tr>
<tr class="odd">
<td>Verificable</td>
<td>¿Existe un método con el que alguien comprobará que se cumple?</td>
</tr>
<tr class="even">
<td>Correcto</td>
<td>¿Describe bien la necesidad de la que sale?</td>
</tr>
<tr class="odd">
<td>Conforme</td>
<td>¿Sigue la plantilla y el estilo acordados en el proyecto?</td>
</tr>
</tbody>
</table>
</section>
<section id="características-de-un-conjunto-de-requisitos" class="level3">
<h3 class="anchored" data-anchor-id="características-de-un-conjunto-de-requisitos">Características de un conjunto de requisitos</h3>
<p>Un requisito puede estar bien escrito y aun así fallar junto a los demás. Por eso las mismas fuentes agregan características del conjunto.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Característica</th>
<th>Pregunta sobre el conjunto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Completo</td>
<td>¿Cubre todas las necesidades y todos los casos relevantes?</td>
</tr>
<tr class="even">
<td>Consistente</td>
<td>¿Ningún requisito contradice a otro ni usa un término con dos sentidos?</td>
</tr>
<tr class="odd">
<td>Factible</td>
<td>¿Se pueden cumplir todos a la vez, dentro de las restricciones?</td>
</tr>
<tr class="even">
<td>Comprensible</td>
<td>¿Los interesados lo entienden, en lo posible sin ayuda?</td>
</tr>
<tr class="odd">
<td>Validable</td>
<td>¿Se puede comprobar con los interesados que es el conjunto correcto?</td>
</tr>
</tbody>
</table>
<p>La última característica conecta con el tema: un conjunto “validable” es uno que se puede someter a la validación de requisitos de la Parte 3. La versión 4 de la guía de INCOSE agregó una característica más, la corrección del conjunto.</p>
</section>
<section id="las-reglas-de-incose" class="level3">
<h3 class="anchored" data-anchor-id="las-reglas-de-incose">Las reglas de INCOSE</h3>
<p>El <em>INCOSE Guide to Writing Requirements</em> (GtWR), versión 4, de julio de 2023, es la guía más usada para redactar requisitos en lenguaje natural. Según los resúmenes de INCOSE y de otras fuentes que la describen, esa versión define 42 reglas y 15 características de calidad. Cada regla responde a un defecto frecuente de redacción.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Lo que se pudo y no se pudo verificar sobre INCOSE
</div>
</div>
<div class="callout-body-container callout-body">
<p>El documento oficial de la versión 4 está en la tienda de INCOSE y su lectura directa devolvió acceso denegado en la consulta de octubre de 2026. El número de reglas, las características y los nombres de las reglas R1 a R9 citados abajo vienen de resúmenes y de índices publicados por INCOSE y otras fuentes que describen la guía. Los números exactos de las demás reglas no se citan. Quien necesite aplicarlas debe consultar el documento completo.</p>
</div>
</div>
<p>Las primeras reglas ya bastan para corregir la mayor parte de los requisitos malos de un proyecto de curso.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Regla</th>
<th>Qué pide</th>
<th>Cómo falla un requisito</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R1</td>
<td>Frase estructurada y completa</td>
<td>“Turnos rápidos” no es una frase</td>
</tr>
<tr class="even">
<td>R2</td>
<td>Voz activa</td>
<td>“Los recordatorios serán enviados” no dice quién los envía</td>
</tr>
<tr class="odd">
<td>R3</td>
<td>Sujeto y verbo apropiados</td>
<td>El sujeto debe ser el sistema o la entidad que cumple</td>
</tr>
<tr class="even">
<td>R4</td>
<td>Términos definidos</td>
<td>“Turno” y “cita” se usan con sentidos distintos</td>
</tr>
<tr class="odd">
<td>R5</td>
<td>Artículos definidos</td>
<td>“Un paciente” donde se quiso decir “el paciente”</td>
</tr>
<tr class="even">
<td>R6</td>
<td>Unidades apropiadas</td>
<td>“2” sin decir si son segundos o minutos</td>
</tr>
<tr class="odd">
<td>R7</td>
<td>Evitar términos vagos</td>
<td>“Rápido”, “fácil”, “adecuado”, “amigable”</td>
</tr>
<tr class="even">
<td>R8</td>
<td>Evitar cláusulas de escape</td>
<td>“Si es posible”, “cuando convenga”</td>
</tr>
<tr class="odd">
<td>R9</td>
<td>Evitar cláusulas abiertas</td>
<td>“Etcétera”, “y otros”, “incluyendo, pero sin limitarse a”</td>
</tr>
</tbody>
</table>
</section>
<section id="la-plantilla-ears" class="level3">
<h3 class="anchored" data-anchor-id="la-plantilla-ears">La plantilla EARS</h3>
<p>EARS (<em>Easy Approach to Requirements Syntax</em>) es una plantilla de redacción creada por Alistair Mavin y colegas en Rolls-Royce y presentada en la conferencia IEEE de ingeniería de requisitos de 2009. Fuerza una frase con una estructura fija que casi elimina la ambigüedad. Hay cinco patrones básicos que se combinan.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Patrón</th>
<th>Forma</th>
<th>Ejemplo en la clínica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ubicuo</td>
<td>El sistema debe respuesta</td>
<td>El sistema debe cerrar la sesión de un funcionario tras 10 minutos sin actividad</td>
</tr>
<tr class="even">
<td>Por evento</td>
<td>Cuando evento, el sistema debe respuesta</td>
<td>Cuando el paciente confirme un horario libre, el sistema debe asignarle el turno</td>
</tr>
<tr class="odd">
<td>Por estado</td>
<td>Mientras estado, el sistema debe respuesta</td>
<td>Mientras falten 12 horas o más para el turno, el sistema debe permitir cancelarlo</td>
</tr>
<tr class="even">
<td>Característica opcional</td>
<td>Donde característica, el sistema debe respuesta</td>
<td>Donde la sede tenga pantalla de turnos, el sistema debe mostrar el código del paciente</td>
</tr>
<tr class="odd">
<td>Comportamiento no deseado</td>
<td>Si condición, entonces el sistema debe respuesta</td>
<td>Si el paciente no tiene turno libre, entonces el sistema debe ofrecer la fecha libre más próxima</td>
</tr>
</tbody>
</table>
<p>El patrón por evento y el patrón por estado son los más útiles al empezar. Obligan a decir cuándo se activa el requisito, que es justo lo que suele faltar.</p>
</section>
<section id="dos-palabras-que-cambian-el-requisito-debe-y-debería" class="level3">
<h3 class="anchored" data-anchor-id="dos-palabras-que-cambian-el-requisito-debe-y-debería">Dos palabras que cambian el requisito: debe y debería</h3>
<p>Muchos equipos escriben “debe” para lo obligatorio y “debería” para lo deseable. El problema aparece cuando nadie lo acordó y los dos verbos se usan al azar. Un requisito con “debería” no se puede verificar como obligatorio, así que el proyecto debe fijar una convención por escrito. En esta guía “debe” marca lo obligatorio y lo deseable se anota aparte con su prioridad.</p>
</section>
</section>
<section id="parte-3.-verificación-y-validación-de-requisitos" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="parte-3.-verificación-y-validación-de-requisitos"><span class="header-section-number">6</span> Parte 3. Verificación y validación de requisitos</h2>
<section id="dos-preguntas-sobre-el-mismo-documento" class="level3">
<h3 class="anchored" data-anchor-id="dos-preguntas-sobre-el-mismo-documento">Dos preguntas sobre el mismo documento</h3>
<p>El Tema 1 explicó que verificar pregunta si se construyó bien el producto frente a su especificación, y que validar pregunta si se construyó el producto correcto frente al uso previsto. Aplicadas a los requisitos cambia el objeto del que se pregunta, que ahora es el documento de requisitos mismo.</p>
<p>La ISO 9000:2015 define los dos conceptos de forma general. La verificación es la confirmación, mediante evidencia objetiva, de que se cumplieron los requisitos especificados. La validación es la confirmación, mediante evidencia objetiva, de que se cumplieron los requisitos para un uso o aplicación específicos previstos. (Paráfrasis de la norma de pago, que no se leyó directamente; la edición vigente debe confirmarse en iso.org.)</p>
<div class="diagrama">
<svg viewbox="0 0 760 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Las necesidades de los interesados se redactan como requisitos. La validación de requisitos pregunta con los interesados si los requisitos expresan lo que se necesita. La verificación de requisitos pregunta si cada requisito y el conjunto están bien escritos según criterios de calidad. Después los requisitos sirven de referencia para verificar y validar el sistema, tema anterior" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t2a" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Dos controles sobre los requisitos antes de construir</text> <rect x="20" y="60" width="170" height="70" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="295" y="60" width="170" height="70" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="570" y="60" width="170" height="70" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <g text-anchor="middle" font-size="13" font-weight="700" fill="#12324f"><text x="105" y="90">Necesidades</text><text x="380" y="90">Requisitos escritos</text><text x="655" y="90">Sistema construido</text></g> <g text-anchor="middle" font-size="11" fill="#5b6876"><text x="105" y="108">dichas por los interesados</text><text x="380" y="108">el documento de la clínica</text><text x="655" y="108">se verifica contra ellos</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u4t2a)"><path d="M192,100 L292,100"></path><path d="M467,100 L567,100"></path><path d="M380,132 L380,196"></path></g> <g text-anchor="middle" font-size="11.5" font-weight="600" fill="#0e6f6c"><text x="242" y="82">Validación</text><text x="242" y="94">de requisitos</text></g> <g text-anchor="middle" font-size="11" fill="#5b6876"><text x="242" y="120">la responden</text><text x="242" y="132">las personas</text><text x="517" y="82">Tema 1</text><text x="517" y="94">de la unidad</text></g> <rect x="245" y="198" width="270" height="76" rx="12" fill="#e4f2f1" stroke="#8fc9c5"></rect> <text x="380" y="224" font-size="13" font-weight="700" fill="#0e6f6c" text-anchor="middle">Verificación de requisitos</text> <text x="380" y="243" font-size="11" fill="#3c7d7a" text-anchor="middle">¿Está bien escrito cada requisito?</text> <text x="380" y="259" font-size="11" fill="#3c7d7a" text-anchor="middle">¿El conjunto es consistente y completo?</text>
</svg>
</div>
</section>
<section id="la-tabla-que-se-debe-tener-a-mano" class="level3">
<h3 class="anchored" data-anchor-id="la-tabla-que-se-debe-tener-a-mano">La tabla que se debe tener a mano</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Verificación de requisitos</th>
<th>Validación de requisitos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pregunta</td>
<td>¿Los requisitos están bien escritos?</td>
<td>¿Son los requisitos que los interesados necesitan?</td>
</tr>
<tr class="even">
<td>Referencia</td>
<td>Características de calidad (29148, INCOSE) y el conjunto</td>
<td>La necesidad real de las personas</td>
</tr>
<tr class="odd">
<td>Quién decide</td>
<td>El equipo, con una lista de chequeo</td>
<td>Los interesados, con evidencia que ven</td>
</tr>
<tr class="even">
<td>Técnicas</td>
<td>Revisión por pares, lista de chequeo, análisis automático de calidad, análisis de consistencia</td>
<td>Revisión con interesados, prototipos, escenarios, criterios de aceptación, BDD</td>
</tr>
<tr class="odd">
<td>Detecta</td>
<td>Ambigüedad, falta de verificabilidad, mezcla de exigencias, contradicciones, vacíos</td>
<td>Requisitos que nadie necesita, requisitos que faltan, valores que no son los reales</td>
</tr>
<tr class="even">
<td>No detecta</td>
<td>Que un requisito perfectamente escrito sea el equivocado</td>
<td>Que un requisito acertado esté mal redactado</td>
</tr>
<tr class="odd">
<td>Cuándo</td>
<td>Cada vez que se redacta o cambia un requisito</td>
<td>En las revisiones con interesados y antes de cada línea base</td>
</tr>
</tbody>
</table>
</section>
<section id="verificar-tiene-tres-sentidos-que-se-confunden" class="level3">
<h3 class="anchored" data-anchor-id="verificar-tiene-tres-sentidos-que-se-confunden">Verificar tiene tres sentidos que se confunden</h3>
<p>La palabra “verificación” aparece en tres contextos distintos en este tema y conviene no mezclarlos.</p>
<ol type="1">
<li>Verificación de requisitos. Comprobar que los requisitos están bien escritos. Es una actividad sobre el documento y se hace antes de construir.</li>
<li>Verificabilidad de un requisito. Una característica del requisito, que indica que existe un método para comprobar su cumplimiento.</li>
<li>Verificación del sistema. Comprobar que el software construido cumple los requisitos. Es la verificación del Tema 1, y se hace después.</li>
</ol>
<p>Un requisito verificable es un requisito que el punto 3 podrá comprobar. Por eso el punto 1 revisa que lo sea, antes de que exista el sistema.</p>
</section>
<section id="los-cuatro-métodos-con-que-se-verifica-un-requisito" class="level3">
<h3 class="anchored" data-anchor-id="los-cuatro-métodos-con-que-se-verifica-un-requisito">Los cuatro métodos con que se verifica un requisito</h3>
<p>Cuando se dice que un requisito es verificable, se piensa en uno de cuatro métodos, que se anotan en la matriz de trazabilidad.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Método</th>
<th>En qué consiste</th>
<th>Ejemplo en la clínica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Inspección</td>
<td>Examinar el producto o su documentación</td>
<td>Revisar la configuración del cupo diario</td>
</tr>
<tr class="even">
<td>Demostración</td>
<td>Operar el sistema y observar su comportamiento</td>
<td>Cancelar un turno desde la app y ver el cupo liberado</td>
</tr>
<tr class="odd">
<td>Prueba</td>
<td>Ejecutar con datos controlados y medir</td>
<td>Prueba de carga con 300 usuarios y medición del tiempo</td>
</tr>
<tr class="even">
<td>Análisis</td>
<td>Razonar o calcular a partir de modelos o datos</td>
<td>Calcular que 30 consultas de 12 minutos caben en una jornada</td>
</tr>
</tbody>
</table>
</section>
<section id="cómo-se-valida-un-conjunto-de-requisitos" class="level3">
<h3 class="anchored" data-anchor-id="cómo-se-valida-un-conjunto-de-requisitos">Cómo se valida un conjunto de requisitos</h3>
<p>Sommerville (<em>Software Engineering</em>, 10.a ed., capítulo 4) describe la validación de requisitos como el proceso de comprobar que los requisitos definen el sistema que el cliente quiere. Propone revisar cinco cosas: validez, consistencia, completitud, realismo y verificabilidad. Y propone tres técnicas: revisiones de requisitos, prototipos y generación de casos de prueba.</p>
<p>La tercera técnica une las dos actividades. Escribir un caso de prueba para cada requisito obliga a que el requisito sea verificable, y si resulta difícil escribirlo, el requisito suele estar mal redactado. La Parte 5 la lleva a la práctica con BDD.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Validar requisitos no es lo mismo que validar el sistema
</div>
</div>
<div class="callout-body-container callout-body">
<p>La validación de requisitos ocurre antes de construir y comprueba el documento con los interesados. La validación del sistema, con pruebas de aceptación, ocurre al final y comprueba el producto. Las dos responden a la pregunta “¿es lo correcto?”, pero sobre objetos distintos y en momentos distintos. La primera es barata de corregir y la segunda no.</p>
</div>
</div>
</section>
</section>
<section id="parte-4.-ejemplo-resuelto-seis-requisitos-mal-escritos-de-la-app-de-turnos" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="parte-4.-ejemplo-resuelto-seis-requisitos-mal-escritos-de-la-app-de-turnos"><span class="header-section-number">7</span> Parte 4. Ejemplo resuelto: seis requisitos mal escritos de la app de turnos</h2>
<p>Este ejemplo recorre cuatro pasos sobre los mismos seis requisitos: leerlos, verificarlos, reescribirlos y validarlos. Todos los números son ilustrativos y se inventaron para practicar.</p>
<div class="diagrama">
<svg viewbox="0 0 760 250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cuatro pasos sobre los requisitos de la clínica: seis requisitos mal escritos, verificación que cumple 11 de 30 criterios, reescritura que produce 10 requisitos y validación que cambia 3 y agrega 1 para quedar en 11 requisitos" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t2b" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">De seis requisitos mal escritos a once requisitos validados</text> <rect x="10" y="40" width="160" height="80" rx="10" fill="#fbeae5" stroke="#e0a595"></rect> <rect x="205" y="40" width="160" height="80" rx="10" fill="#fdf3d6" stroke="#e6cf8f"></rect> <rect x="400" y="40" width="160" height="80" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="595" y="40" width="155" height="80" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g text-anchor="middle" font-size="13" font-weight="700" fill="#12324f"><text x="90" y="68">1. Los seis</text><text x="285" y="68">2. Verificar</text><text x="480" y="68">3. Reescribir</text><text x="672" y="68">4. Validar</text></g> <g text-anchor="middle" font-size="11" fill="#5b6876"><text x="90" y="88">requisitos de partida</text><text x="90" y="104">salen de las notas</text><text x="285" y="88">se aplican cinco</text><text x="285" y="104">criterios a cada uno</text><text x="480" y="88">se corrigen con EARS</text><text x="480" y="104">y reglas de INCOSE</text><text x="672" y="88">se revisan con los</text><text x="672" y="104">interesados</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u4t2b)"><path d="M172,80 L202,80"></path><path d="M367,80 L397,80"></path><path d="M562,80 L592,80"></path></g> <g text-anchor="middle" font-size="12" font-weight="600" fill="#12324f"><text x="90" y="160">6 requisitos</text><text x="285" y="160">11 de 30 criterios</text><text x="480" y="160">10 requisitos</text><text x="672" y="160">11 requisitos</text></g> <g text-anchor="middle" font-size="11" fill="#5b6876"><text x="90" y="178">escritos en lenguaje</text><text x="90" y="192">cotidiano</text><text x="285" y="178">cumplidos, 19 fallas</text><text x="285" y="192">halladas sin código</text><text x="480" y="178">uno por exigencia,</text><text x="480" y="192">con valores y método</text><text x="672" y="178">tres cambiaron y</text><text x="672" y="192">uno nuevo apareció</text></g> <line x1="40" y1="215" x2="720" y2="215" stroke="#cfd8e3" stroke-width="1.2" stroke-dasharray="5 5"></line> <text x="380" y="236" font-size="11" fill="#5b6876" text-anchor="middle">Los pasos 2 y 3 los hace el equipo. El paso 4 lo deciden las personas que usarán la app.</text>
</svg>
</div>
<section id="paso-1.-los-seis-requisitos-de-partida" class="level3">
<h3 class="anchored" data-anchor-id="paso-1.-los-seis-requisitos-de-partida">Paso 1. Los seis requisitos de partida</h3>
<p>Las notas de las reuniones se transcribieron tal cual en seis requisitos. Se numeran con el prefijo RO (requisito original).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Id</th>
<th>Texto original</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RO-1</td>
<td>El sistema debe ser rápido al buscar turnos.</td>
</tr>
<tr class="even">
<td>RO-2</td>
<td>La app debe asignar turnos, enviar recordatorios y permitir cancelar o reprogramar.</td>
</tr>
<tr class="odd">
<td>RO-3</td>
<td>La app debería asignar el turno más cercano, si es posible.</td>
</tr>
<tr class="even">
<td>RO-4</td>
<td>La app asigna hasta 20 turnos por día a cada especialidad.</td>
</tr>
<tr class="odd">
<td>RO-5</td>
<td>Medicina general debe atender 30 turnos por día.</td>
</tr>
<tr class="even">
<td>RO-6</td>
<td>La app debe ser fácil de usar para todos los pacientes.</td>
</tr>
</tbody>
</table>
</section>
<section id="paso-2.-verificación-de-requisitos" class="level3">
<h3 class="anchored" data-anchor-id="paso-2.-verificación-de-requisitos">Paso 2. Verificación de requisitos</h3>
<p>Se aplican cinco criterios a cada requisito: singular, no ambiguo, verificable, completo y consistente con el conjunto. La tabla marca con “Sí” lo que cumple y con “No” lo que falla, y la columna final dice por qué.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>Id</th>
<th style="text-align: center;">Singular</th>
<th style="text-align: center;">No ambiguo</th>
<th style="text-align: center;">Verificable</th>
<th style="text-align: center;">Completo</th>
<th style="text-align: center;">Consistente</th>
<th>Qué se encontró</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RO-1</td>
<td style="text-align: center;">Sí</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Sí</td>
<td>“Rápido” no tiene medida, ni condiciones de carga, ni punto de medición</td>
</tr>
<tr class="even">
<td>RO-2</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Sí</td>
<td>Cuatro exigencias en una frase. “Recordatorios” no dice cuándo ni por qué canal. No dice qué pasa si no hay turno al reprogramar</td>
</tr>
<tr class="odd">
<td>RO-3</td>
<td style="text-align: center;">Sí</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Sí</td>
<td>“Debería” y “si es posible” dejan el requisito sin obligación. “Más cercano” no dice a partir de cuándo</td>
</tr>
<tr class="even">
<td>RO-4</td>
<td style="text-align: center;">Sí</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Sí</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td>“Cada especialidad” no dice si es por sede o por profesional. No dice qué pasa en el turno 21. Choca con RO-5</td>
</tr>
<tr class="odd">
<td>RO-5</td>
<td style="text-align: center;">Sí</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Sí</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td>“Atender” y “asignar” no son lo mismo. No dice sede ni profesional. Para Medicina general dice 30 y RO-4 dice 20</td>
</tr>
<tr class="even">
<td>RO-6</td>
<td style="text-align: center;">Sí</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">Sí</td>
<td>“Fácil” y “todos” no se pueden medir. No dice quién es “todos”</td>
</tr>
</tbody>
</table>
<p>El conteo es el siguiente. Cada fila tiene cinco criterios, así que son 6 x 5 = 30 casillas. Cumplen 2 + 1 + 2 + 2 + 2 + 2 = 11, y fallan 30 - 11 = 19. El requisito RO-2 es el peor, con un solo criterio cumplido. Y todo esto se encontró leyendo texto, sin escribir ni ejecutar una línea de código.</p>
<p>Observa que RO-4 y RO-5 son verificables cada uno por separado, porque se pueden contar turnos. La falla aparece al ponerlos juntos. Es el caso típico de un defecto de conjunto, que solo se ve con el criterio de consistencia.</p>
</section>
<section id="paso-3.-reescritura" class="level3">
<h3 class="anchored" data-anchor-id="paso-3.-reescritura">Paso 3. Reescritura</h3>
<p>Cada requisito se reescribe con patrones EARS y con las reglas R1 a R9. Donde un número no se puede inventar, se propone un valor inicial que el paso 4 deberá validar. Se usa el prefijo RQ.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Id nuevo</th>
<th>Viene de</th>
<th>Requisito reescrito</th>
<th>Método</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RQ-01</td>
<td>RO-1</td>
<td>Cuando el paciente busque turnos de una especialidad, el sistema debe mostrar la lista de turnos libres en 2 segundos o menos en el percentil 95, con 200 usuarios simultáneos y 50.000 turnos registrados.</td>
<td>Prueba</td>
</tr>
<tr class="even">
<td>RQ-02</td>
<td>RO-2</td>
<td>Cuando el paciente confirme un horario libre, el sistema debe asignarle el turno y mostrarle un código de confirmación.</td>
<td>Prueba</td>
</tr>
<tr class="odd">
<td>RQ-03</td>
<td>RO-2</td>
<td>El sistema debe enviar al paciente un recordatorio por mensaje de texto 24 horas antes de la hora del turno.</td>
<td>Prueba</td>
</tr>
<tr class="even">
<td>RQ-04</td>
<td>RO-2</td>
<td>Mientras falten 12 horas o más para el turno, el sistema debe permitir al paciente cancelarlo y debe liberar el cupo.</td>
<td>Prueba</td>
</tr>
<tr class="odd">
<td>RQ-05</td>
<td>RO-2</td>
<td>Cuando el paciente reprograme un turno, el sistema debe asignar el turno nuevo antes de liberar el anterior, y si no hay turno nuevo debe conservar el original.</td>
<td>Prueba</td>
</tr>
<tr class="even">
<td>RQ-06</td>
<td>RO-3</td>
<td>Cuando el paciente solicite turno de una especialidad, el sistema debe ofrecer primero el turno libre con fecha y hora más próximas a partir del momento de la solicitud.</td>
<td>Prueba</td>
</tr>
<tr class="odd">
<td>RQ-08</td>
<td>RO-4</td>
<td>El sistema debe permitir configurar, por especialidad, el cupo diario de turnos por profesional.</td>
<td>Demostración</td>
</tr>
<tr class="even">
<td>RQ-09</td>
<td>RO-4 y RO-5</td>
<td>El valor inicial del cupo diario por profesional debe ser 30 en Medicina general y 20 en las demás especialidades.</td>
<td>Inspección</td>
</tr>
<tr class="odd">
<td>RQ-10</td>
<td>RO-4</td>
<td>Cuando un profesional alcance su cupo diario, el sistema debe mostrar ese día como no disponible para ese profesional.</td>
<td>Prueba</td>
</tr>
<tr class="even">
<td>RQ-11</td>
<td>RO-6</td>
<td>Un paciente que use la app por primera vez debe poder solicitar un turno en 3 minutos o menos, sin ayuda, en al menos 9 de 10 sesiones de prueba.</td>
<td>Prueba con usuarios</td>
</tr>
</tbody>
</table>
<p>La numeración salta de RQ-06 a RQ-08. El número RQ-07 queda reservado para un requisito que el paso 4 va a descubrir, y se reserva ahora para que la numeración final no cambie de un paso a otro.</p>
<p>Cuenta lo que pasó. De 6 requisitos se pasó a 10. RO-2 se partió en cuatro (RQ-02 a RQ-05), RO-4 y RO-5 se resolvieron en tres (RQ-08 a RQ-10) y los otros tres quedaron en uno cada uno. Que el número crezca no indica trabajo extra. Indica que las exigencias que estaban mezcladas ahora se ven.</p>
<p>Un detalle de RQ-09 merece lectura. Los dos valores, 30 y 20, ya no se contradicen porque el requisito declara que uno es la excepción del otro. Esa es la forma de resolver una inconsistencia que sí es real. El equipo no decide cuál de los dos valores es el correcto. Lo decide el paso siguiente, con quien conoce la clínica.</p>
</section>
<section id="paso-4.-validación-con-los-interesados" class="level3">
<h3 class="anchored" data-anchor-id="paso-4.-validación-con-los-interesados">Paso 4. Validación con los interesados</h3>
<p>El equipo llevó los diez requisitos a tres personas y a un prototipo. Cada una validó lo que conoce. Los hallazgos son ilustrativos.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Interesado</th>
<th>Cómo se validó</th>
<th>Hallazgo</th>
<th>Efecto sobre los requisitos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Recepción</td>
<td>Revisión del texto y del registro de llamadas de la clínica</td>
<td>A las 7:00, cuando se abre la agenda, intentan entrar unos 300 pacientes, no 200</td>
<td>RQ-01 pasa de 200 a 300 usuarios simultáneos</td>
</tr>
<tr class="even">
<td>Pacientes</td>
<td>Entrevista con el prototipo en papel</td>
<td>Un recordatorio 24 horas antes llega tarde para quien debe organizar transporte. Quieren uno a las 48 horas y otro a las 2 horas</td>
<td>RQ-03 cambia a dos recordatorios, uno a 48 horas y otro a 2 horas</td>
</tr>
<tr class="odd">
<td>Coordinación médica</td>
<td>Revisión del texto con el cuadro de consultas</td>
<td>El cupo de 30 de Medicina general sale de consultas de 12 minutos. El de 20 sale de consultas de 20 minutos</td>
<td>Se confirma RQ-09. Se verifica por análisis: 30 x 12 = 360 minutos y 20 x 20 = 400 minutos, ambos caben en una jornada de 8 horas</td>
</tr>
<tr class="even">
<td>Coordinación médica</td>
<td>Escenario: paciente crónico</td>
<td>Los pacientes crónicos quieren seguir con el mismo médico, aunque el turno sea más lejano</td>
<td>Aparece un requisito nuevo: RQ-07</td>
</tr>
<tr class="odd">
<td>Pacientes</td>
<td>Prueba del prototipo con 10 personas</td>
<td>Cuatro de los diez tenían más de 60 años y fueron los que más tardaron. “Todos los pacientes” ocultaba esta población</td>
<td>RQ-11 declara explícitamente que la muestra de prueba incluye personas de 18 a 80 años y al menos tres mayores de 60</td>
</tr>
</tbody>
</table>
<p>El requisito nuevo, escrito con la misma disciplina, queda así.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Id</th>
<th>Requisito</th>
<th>Método</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RQ-07</td>
<td>Cuando el paciente solicite turno de una especialidad y haya sido atendido por un profesional de ella en los últimos 6 meses, el sistema debe ofrecer primero los turnos libres de ese profesional.</td>
<td>Prueba</td>
</tr>
</tbody>
</table>
<p>Este hallazgo es el motivo de ser de la validación. Ninguna lista de chequeo sobre el texto de RO-3 habría descubierto que faltaba RQ-07, porque el texto no tenía nada mal escrito en ese aspecto. Hizo falta una persona que conoce a los pacientes crónicos. La verificación revisa lo que está escrito. La validación encuentra lo que falta o lo que está mal calibrado.</p>
<p>Después de la validación, tres requisitos cambian de redacción. Esta es su versión final, la que entra a la línea base.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Id</th>
<th>Requisito final</th>
<th>Qué cambió</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RQ-01</td>
<td>Cuando el paciente busque turnos de una especialidad, el sistema debe mostrar la lista de turnos libres en 2 segundos o menos en el percentil 95, con 300 usuarios simultáneos y 50.000 turnos registrados.</td>
<td>De 200 a 300 usuarios</td>
</tr>
<tr class="even">
<td>RQ-03</td>
<td>El sistema debe enviar al paciente un recordatorio por mensaje de texto 48 horas antes de la hora del turno y otro 2 horas antes.</td>
<td>De un aviso a las 24 horas a dos avisos</td>
</tr>
<tr class="odd">
<td>RQ-11</td>
<td>Un paciente que use la app por primera vez debe poder solicitar un turno en 3 minutos o menos, sin ayuda, en al menos 9 de 10 sesiones de prueba, con participantes de 18 a 80 años entre los que haya al menos tres mayores de 60.</td>
<td>Se define quién es “todos”</td>
</tr>
</tbody>
</table>
<p>El conjunto final tiene 11 requisitos. Tres cambiaron por la validación (RQ-01, RQ-03 y RQ-11), uno se agregó (RQ-07) y siete quedaron como estaban. Antes de congelar este conjunto como línea base conviene volver a pasar la verificación sobre los cambios, porque una corrección hecha para validar también puede introducir un defecto.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 1. Verifica y reescribe un requisito nuevo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un interesado agrega este requisito a la app: “La app debe guardar el historial de turnos de forma segura y por mucho tiempo.” Aplica los cinco criterios de la tabla del paso 2, indica cuántos cumple, y reescríbelo. Si para completarlo falta un dato que nadie puede inventar, señala cómo se maneja.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Singular: sí, aunque “segura” y “mucho tiempo” son dos atributos que conviene separar. No ambiguo: no, porque “segura” y “mucho tiempo” no se definen. Verificable: no. Completo: no, porque no dice quién guarda, qué se guarda ni por cuánto. Consistente: se asume que sí, porque ningún otro requisito del ejemplo lo contradice. Cumple 2 de 5.</p>
<p>Una reescritura posible separa en dos. Primero, “El sistema debe conservar el historial de turnos de cada paciente durante [plazo por definir] años desde el último turno.” Segundo, un requisito de seguridad medible, por ejemplo “El sistema debe exigir autenticación para consultar el historial de turnos y debe cerrar la sesión tras 10 minutos sin actividad.”</p>
<p>El plazo de conservación no se inventa. Lo fija la normativa que aplique a la clínica y la política de la institución. Se deja marcado entre corchetes como dato pendiente, con responsable, y el requisito no se congela hasta tenerlo. Un requisito con un dato pendiente es honesto. Uno con un número inventado es un riesgo.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 2. Detecta el defecto de conjunto
</div>
</div>
<div class="callout-body-container callout-body">
<p>Estos dos requisitos son individualmente claros: “El sistema debe enviar un recordatorio por mensaje de texto 48 horas antes del turno” y “El sistema debe enviar un único mensaje por paciente cada 72 horas, como máximo.” Escribe en qué caso se contradicen y cómo lo resolverías antes de consultar a nadie.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Se contradicen cuando un paciente tiene dos turnos con menos de 72 horas entre sí. El segundo recordatorio rompería el límite del segundo requisito, o el límite impediría el recordatorio exigido por el primero.</p>
<p>Antes de consultar a nadie, el equipo no debe elegir cuál requisito gana. Debe registrar el conflicto, describir el caso en que ocurre y llevarlo a quien tiene la autoridad para decidir. Las salidas razonables son declarar una prioridad entre los dos, o acotar el segundo requisito a mensajes que no sean recordatorios de turno. Esa decisión es de validación, no de redacción.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-5.-criterios-de-aceptación-con-bdd-y-gherkin" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="parte-5.-criterios-de-aceptación-con-bdd-y-gherkin"><span class="header-section-number">8</span> Parte 5. Criterios de aceptación con BDD y Gherkin</h2>
<section id="qué-es-el-desarrollo-guiado-por-comportamiento" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-el-desarrollo-guiado-por-comportamiento">Qué es el desarrollo guiado por comportamiento</h3>
<p>El desarrollo guiado por comportamiento (<em>Behavior-Driven Development</em>, BDD) lo describió Dan North en el artículo <em>Introducing BDD</em>, publicado en la revista Better Software en marzo de 2006. Propone expresar el comportamiento esperado con ejemplos concretos, en una plantilla de tres partes: dado un contexto inicial, cuando ocurre un evento, entonces se espera un resultado. Esos ejemplos son criterios de aceptación y a la vez pruebas posibles.</p>
<p>La documentación de Cucumber, la herramienta más difundida de BDD, resume el método en tres prácticas. El descubrimiento, que reúne a negocio, desarrollo y pruebas para conversar con ejemplos reales. La formulación, que escribe esos ejemplos en un formato que leen personas y máquinas. Y la automatización, que convierte cada ejemplo en una prueba. Para este tema interesan las dos primeras, porque son las que validan y verifican requisitos. La tercera es de pruebas de software.</p>
</section>
<section id="descubrir-el-mapa-de-ejemplos" class="level3">
<h3 class="anchored" data-anchor-id="descubrir-el-mapa-de-ejemplos">Descubrir: el mapa de ejemplos</h3>
<p>El mapa de ejemplos (<em>Example Mapping</em>), propuesto por Matt Wynne en diciembre de 2015, estructura una conversación de unos 25 minutos con tarjetas de cuatro colores.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Color</th>
<th>Contenido</th>
<th>Ejemplo con RQ-04 (cancelar un turno)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Amarillo</td>
<td>La historia o requisito que se discute</td>
<td>Cancelar un turno</td>
</tr>
<tr class="even">
<td>Azul</td>
<td>Reglas que lo restringen</td>
<td>Solo se puede cancelar con 12 horas o más de anticipación</td>
</tr>
<tr class="odd">
<td>Verde</td>
<td>Ejemplos concretos de cada regla</td>
<td>Turno el lunes a las 9:00. Cancelar el domingo a las 21:00 (12 h) sí. A las 21:01 (11 h 59 min) no</td>
</tr>
<tr class="even">
<td>Rojo</td>
<td>Preguntas o supuestos sin respuesta</td>
<td>¿Qué hace la app si el paciente cancela tarde por una emergencia?</td>
</tr>
</tbody>
</table>
<p>Cada tarjeta roja es un hueco que la verificación no habría encontrado, porque el texto del requisito no lo mencionaba. Cada regla azul sin tarjeta verde es una regla aún sin ejemplo y, por tanto, sin prueba.</p>
</section>
<section id="formular-gherkin" class="level3">
<h3 class="anchored" data-anchor-id="formular-gherkin">Formular: Gherkin</h3>
<p>Gherkin es el lenguaje de texto en que se escriben los ejemplos. Sus palabras clave, según la referencia oficial de Cucumber, son estas.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Palabra</th>
<th>Para qué sirve</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Feature (Característica)</td>
<td>Agrupa los escenarios de una funcionalidad</td>
</tr>
<tr class="even">
<td>Rule (Regla)</td>
<td>Agrupa los escenarios que ilustran una regla de negocio</td>
</tr>
<tr class="odd">
<td>Scenario o Example (Escenario o Ejemplo)</td>
<td>Un caso concreto</td>
</tr>
<tr class="even">
<td>Given (Dado)</td>
<td>El contexto inicial, el sistema en un estado conocido</td>
</tr>
<tr class="odd">
<td>When (Cuando)</td>
<td>El evento o la acción</td>
</tr>
<tr class="even">
<td>Then (Entonces)</td>
<td>El resultado esperado, que se podrá comprobar</td>
</tr>
<tr class="odd">
<td>And y But (Y y Pero)</td>
<td>Encadenan pasos del mismo tipo</td>
</tr>
<tr class="even">
<td>Background (Antecedentes)</td>
<td>Pasos comunes a todos los escenarios</td>
</tr>
<tr class="odd">
<td>Scenario Outline y Examples (Esquema del escenario y Ejemplos)</td>
<td>Una plantilla que se ejecuta con una tabla de datos</td>
</tr>
</tbody>
</table>
<p>Gherkin admite varios idiomas, y el español se activa con una primera línea de comentario. A continuación va la regla de cupo diario, RQ-10, con los valores del requisito RQ-09. Los ejemplos eligen los valores fronterizos, 19 y 20 en el caso general y 29 y 30 en Medicina general.</p>
<pre class="gherkin"><code># language: es
Característica: Cupo diario por profesional

  Regla: Un profesional no recibe más turnos que su cupo diario

    Esquema del escenario: Disponibilidad del día según los turnos asignados
      Dado un profesional de "&lt;especialidad&gt;" con &lt;asignados&gt; turnos asignados para el lunes
      Cuando el paciente busca turnos para el lunes
      Entonces el sistema muestra el lunes como "&lt;estado&gt;" para ese profesional

      Ejemplos:
        | especialidad     | asignados | estado        |
        | Pediatría        | 19        | disponible    |
        | Pediatría        | 20        | no disponible |
        | Medicina general | 29        | disponible    |
        | Medicina general | 30        | no disponible |</code></pre>
<p>Esos cuatro ejemplos reproducen el defecto que el Tema 1 de la Unidad 1 usó como ejemplo, el que aparece en el turno 20 por comparar con menor en lugar de menor o igual. Con el ejemplo del turno 20 escrito antes de programar, ese defecto no sobrevive a la primera ejecución.</p>
</section>
<section id="criterios-de-aceptación-bien-formados" class="level3">
<h3 class="anchored" data-anchor-id="criterios-de-aceptación-bien-formados">Criterios de aceptación bien formados</h3>
<p>Un criterio de aceptación sirve cuando cumple cuatro condiciones.</p>
<ul>
<li>Es concreto: usa valores, no adjetivos.</li>
<li>Es observable: dice qué se ve o se mide al final.</li>
<li>Es independiente: se puede comprobar sin ejecutar antes otro escenario.</li>
<li>Es breve: un escenario ilustra una sola regla.</li>
</ul>
<p>Si un escenario necesita diez pasos, probablemente mezcla varias reglas y el requisito del que sale no era singular.</p>
</section>
<section id="cómo-el-bdd-une-las-dos-actividades" class="level3">
<h3 class="anchored" data-anchor-id="cómo-el-bdd-une-las-dos-actividades">Cómo el BDD une las dos actividades</h3>
<p>Escribir un escenario es verificar, porque obliga a que el requisito tenga valores y resultados observables. Conversar el escenario con los interesados es validar, porque ellos reconocen o corrigen el ejemplo. La práctica llamada “los tres amigos”, en que negocio, desarrollo y pruebas revisan juntos el escenario antes de construir, junta las dos actividades en una sola sesión.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Un límite del BDD
</div>
</div>
<div class="callout-body-container callout-body">
<p>El BDD no sustituye una buena especificación. Una colección de escenarios dice cómo se comporta el sistema en los casos que alguien pensó, y no dice nada de los casos que nadie imaginó. Los criterios de aceptación completan los requisitos y no los reemplazan, sobre todo en los requisitos no funcionales, que a menudo se verifican con mediciones y no con escenarios.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 3. Escribe los escenarios de RQ-04
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para el requisito “Mientras falten 12 horas o más para el turno, el sistema debe permitir al paciente cancelarlo y debe liberar el cupo”, escribe en una tabla de ejemplos tres casos de frontera con la hora del turno y la hora de la cancelación: justo en el límite, un minuto antes del límite y bien dentro del permitido. Indica el resultado esperado de cada uno.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Se toma un turno fijo, el lunes a las 9:00.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Caso</th>
<th>Hora de la cancelación</th>
<th>Anticipación</th>
<th>Resultado esperado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Justo en el límite</td>
<td>Domingo 21:00</td>
<td>12 h 0 min</td>
<td>El sistema permite cancelar y libera el cupo</td>
</tr>
<tr class="even">
<td>Un minuto después del límite</td>
<td>Domingo 21:01</td>
<td>11 h 59 min</td>
<td>El sistema no permite cancelar</td>
</tr>
<tr class="odd">
<td>Bien dentro</td>
<td>Viernes 9:00</td>
<td>72 h</td>
<td>El sistema permite cancelar y libera el cupo</td>
</tr>
</tbody>
</table>
<p>El caso del límite exacto es el que decide si se programó “mayor o igual” o “mayor”, así que es el más valioso de los tres. Además, el escenario de las 21:01 hace aparecer una pregunta que el requisito no respondía: qué mensaje ve el paciente cuando no puede cancelar. Ese es un requisito nuevo por escribir.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-6.-requisitos-no-funcionales-medibles" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="parte-6.-requisitos-no-funcionales-medibles"><span class="header-section-number">9</span> Parte 6. Requisitos no funcionales medibles</h2>
<section id="por-qué-fallan-los-requisitos-de-calidad" class="level3">
<h3 class="anchored" data-anchor-id="por-qué-fallan-los-requisitos-de-calidad">Por qué fallan los requisitos de calidad</h3>
<p>Los requisitos funcionales suelen ser verificables de forma natural, porque describen un comportamiento que se observa. Los no funcionales fallan con más frecuencia porque se escriben con adjetivos: rápido, seguro, fácil, estable, escalable. Un adjetivo no se puede probar. Un número con sus condiciones, sí.</p>
</section>
<section id="la-plantilla-de-seis-elementos" class="level3">
<h3 class="anchored" data-anchor-id="la-plantilla-de-seis-elementos">La plantilla de seis elementos</h3>
<p>Un requisito no funcional medible dice seis cosas.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Elemento</th>
<th>Qué dice</th>
<th>En RQ-01</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Atributo</td>
<td>Qué característica de calidad se exige</td>
<td>Eficiencia de desempeño</td>
</tr>
<tr class="even">
<td>Métrica</td>
<td>Qué se mide</td>
<td>Tiempo de respuesta de la búsqueda</td>
</tr>
<tr class="odd">
<td>Valor objetivo</td>
<td>Cuánto se exige, con unidad</td>
<td>2 segundos o menos</td>
</tr>
<tr class="even">
<td>Estadístico</td>
<td>Sobre qué parte de las mediciones</td>
<td>En el percentil 95</td>
</tr>
<tr class="odd">
<td>Condiciones</td>
<td>Bajo qué carga o contexto</td>
<td>300 usuarios simultáneos, 50.000 turnos registrados</td>
</tr>
<tr class="even">
<td>Método</td>
<td>Cómo se comprobará</td>
<td>Prueba de carga en el ambiente de pruebas</td>
</tr>
</tbody>
</table>
<p>El estadístico importa. Un promedio de 1 segundo puede ocultar que uno de cada diez pacientes espera 8 segundos. El percentil 95 dice que el 95 % de las búsquedas debe estar dentro del valor. Y las condiciones evitan que el requisito se cumpla en el laboratorio y falle a las 7:00 de la mañana.</p>
</section>
<section id="del-adjetivo-al-número-en-la-clínica" class="level3">
<h3 class="anchored" data-anchor-id="del-adjetivo-al-número-en-la-clínica">Del adjetivo al número en la clínica</h3>
<p>La lista de atributos sale de la ISO/IEC 25010:2023, que se desarrolla en el Tema 2 de la Unidad 1. Aquí se usa solo como lista para no olvidar ninguno.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Atributo (ISO/IEC 25010:2023)</th>
<th>Requisito vago</th>
<th>Requisito medible</th>
<th>Método</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Eficiencia de desempeño</td>
<td>El sistema debe ser rápido</td>
<td>La búsqueda de turnos responde en 2 s o menos en el percentil 95 con 300 usuarios simultáneos</td>
<td>Prueba de carga</td>
</tr>
<tr class="even">
<td>Capacidad de interacción</td>
<td>La app debe ser fácil de usar</td>
<td>Un paciente nuevo solicita un turno en 3 min o menos, sin ayuda, en 9 de 10 sesiones de prueba</td>
<td>Prueba con usuarios</td>
</tr>
<tr class="odd">
<td>Fiabilidad</td>
<td>La app debe estar siempre disponible</td>
<td>La app está disponible el 99,5 % del tiempo de cada mes, medido en el punto de entrada, sin contar mantenimientos avisados con 48 h de anticipación</td>
<td>Monitoreo</td>
</tr>
<tr class="even">
<td>Seguridad informática</td>
<td>La app debe ser segura</td>
<td>El sistema cierra la sesión de un funcionario tras 10 min sin actividad</td>
<td>Prueba</td>
</tr>
<tr class="odd">
<td>Mantenibilidad</td>
<td>Debe ser fácil de modificar</td>
<td>Cambiar el cupo diario de una especialidad toma menos de 5 minutos y no exige cambiar código</td>
<td>Demostración</td>
</tr>
<tr class="even">
<td>Compatibilidad</td>
<td>Debe funcionar en cualquier teléfono</td>
<td>La app funciona en los sistemas y navegadores que usa al menos el 95 % de los pacientes según las estadísticas de la clínica</td>
<td>Prueba y análisis</td>
</tr>
</tbody>
</table>
</section>
<section id="cuánto-vale-una-cifra-de-disponibilidad" class="level3">
<h3 class="anchored" data-anchor-id="cuánto-vale-una-cifra-de-disponibilidad">Cuánto vale una cifra de disponibilidad</h3>
<p>La disponibilidad se expresa en porcentaje, y cada nueve extra reduce mucho el tiempo de caída permitido. Para un mes de 30 días, que tiene 30 x 24 = 720 horas, el cálculo es sencillo.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Disponibilidad</th>
<th>Caída permitida por mes</th>
<th>Cálculo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>99 %</td>
<td>7,2 horas</td>
<td>720 x 0,01</td>
</tr>
<tr class="even">
<td>99,5 %</td>
<td>3,6 horas, es decir 3 h 36 min</td>
<td>720 x 0,005</td>
</tr>
<tr class="odd">
<td>99,9 %</td>
<td>43,2 minutos</td>
<td>720 x 0,001 = 0,72 h x 60</td>
</tr>
<tr class="even">
<td>99,99 %</td>
<td>4,32 minutos</td>
<td>720 x 0,0001 = 0,072 h x 60</td>
</tr>
</tbody>
</table>
<p>Pedir 99,99 % para una app de turnos de una clínica pequeña seguramente cuesta mucho más de lo que vale. El número lo decide la validación con quien conoce el costo de una caída, y no un deseo del equipo. Esta guía no da un valor “correcto” de disponibilidad porque depende del contexto.</p>
<div class="diagrama">
<svg viewbox="0 0 760 230" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Un requisito no funcional vago se convierte en uno medible con tres pasos: elegir el atributo y la métrica, fijar el valor objetivo con el estadístico y las condiciones, y definir el método de verificación" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t2c" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">De un adjetivo a un requisito que se puede probar</text> <rect x="10" y="40" width="150" height="90" rx="10" fill="#fbeae5" stroke="#e0a595"></rect> <rect x="200" y="40" width="165" height="90" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="405" y="40" width="165" height="90" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="610" y="40" width="140" height="90" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g text-anchor="middle" font-size="12.5" font-weight="700" fill="#12324f"><text x="85" y="66">Adjetivo</text><text x="282" y="66">1. Qué se mide</text><text x="487" y="66">2. Cuánto y cuándo</text><text x="680" y="66">3. Cómo se prueba</text></g> <g text-anchor="middle" font-size="11" fill="#5b6876"><text x="85" y="88">“rápido”</text><text x="85" y="104">“fácil”</text><text x="282" y="88">atributo y métrica:</text><text x="282" y="104">tiempo de respuesta</text><text x="487" y="88">valor, estadístico y</text><text x="487" y="104">condiciones de carga</text><text x="680" y="88">prueba, medición</text><text x="680" y="104">o inspección</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u4t2c)"><path d="M162,85 L197,85"></path><path d="M367,85 L402,85"></path><path d="M572,85 L607,85"></path></g> <rect x="150" y="160" width="460" height="50" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <text x="380" y="182" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">Resultado: 2 s o menos en el percentil 95, con 300 usuarios,</text> <text x="380" y="199" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">medido con una prueba de carga</text>
</svg>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 4. Vuelve medible un requisito de disponibilidad
</div>
</div>
<div class="callout-body-container callout-body">
<p>La clínica pide: “La app debe estar siempre disponible.” Escribe una versión medible con un porcentaje mensual, calcula cuántas horas de caída permite en un mes de 30 días y di qué método comprobaría el requisito. Explica también por qué la palabra “siempre” es un problema.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Una versión medible es “La app debe estar disponible al menos el 99,5 % del tiempo de cada mes de calendario, medido en el punto de entrada de la app, sin contar los mantenimientos avisados con 48 horas de anticipación.”</p>
<p>Con 720 horas al mes, el 0,5 % restante es 720 x 0,005 = 3,6 horas, o 3 horas y 36 minutos de caída permitida. El método es el monitoreo continuo del punto de entrada, con un informe mensual.</p>
<p>“Siempre” es un problema porque exige cero caídas, algo que ningún sistema real puede garantizar ni verificar, ya que habría que observarlo durante un tiempo infinito. El porcentaje convierte un deseo en un umbral que se puede comprobar. El valor exacto, 99,5 %, es ilustrativo y debe fijarse con la clínica.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-7.-la-matriz-de-trazabilidad-de-requisitos-rtm" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="parte-7.-la-matriz-de-trazabilidad-de-requisitos-rtm"><span class="header-section-number">10</span> Parte 7. La matriz de trazabilidad de requisitos (RTM)</h2>
<section id="qué-es-y-para-qué-sirve" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-y-para-qué-sirve">Qué es y para qué sirve</h3>
<p>La <em>trazabilidad de requisitos</em> es, según la definición clásica de Gotel y Finkelstein (1994), la capacidad de describir y seguir la vida de un requisito en las dos direcciones, hacia adelante y hacia atrás. La <em>matriz de trazabilidad de requisitos</em> (RTM, <em>Requirements Traceability Matrix</em>) es la tabla que registra esos vínculos entre los requisitos y los demás elementos del proyecto.</p>
<ul>
<li>Hacia atrás: de un requisito a su origen. Responde “¿quién lo pidió y por qué?”.</li>
<li>Hacia adelante: de un requisito a su diseño, su código y sus pruebas. Responde “¿dónde se construyó y cómo se comprobó?”.</li>
</ul>
<p>Según una fuente secundaria que recoge el estado del arte, la trazabilidad es obligatoria en estándares de sistemas críticos como DO-178C (aviación), ISO 26262 (automoción) e IEC 61508 (seguridad funcional). En un proyecto sin esa obligación sigue sirviendo para cuatro usos.</p>
<ol type="1">
<li>Cobertura. Detecta requisitos sin prueba y sin diseño.</li>
<li>Impacto. Muestra qué se afecta si un requisito cambia.</li>
<li>Alcance. Detecta trabajo que ningún requisito pidió, el llamado <em>gold plating</em>, y pruebas huérfanas.</li>
<li>Evidencia. Demuestra a un cliente o auditor que cada exigencia se construyó y se comprobó.</li>
</ol>
<div class="diagrama">
<svg viewbox="0 0 760 270" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cadena de trazabilidad de un requisito de la clínica: la necesidad de la coordinación médica origina el requisito RQ-10, que se implementa en el componente de reglas de cupo y se comprueba con la prueba PR-03. Las flechas hacia adelante van de la necesidad a la prueba y las flechas hacia atrás van de la prueba a la necesidad" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t2d" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker><marker id="u4t2e" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#0e6f6c"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Trazabilidad de un requisito en las dos direcciones</text> <rect x="10" y="80" width="160" height="80" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="205" y="80" width="160" height="80" rx="10" fill="#eef4fa" stroke="#c7d6e6"></rect> <rect x="400" y="80" width="160" height="80" rx="10" fill="#f5f7fa" stroke="#cfd8e3"></rect> <rect x="595" y="80" width="155" height="80" rx="10" fill="#e4f2f1" stroke="#8fc9c5"></rect> <g text-anchor="middle" font-size="12.5" font-weight="700" fill="#12324f"><text x="90" y="106">Necesidad</text><text x="285" y="106">Requisito</text><text x="480" y="106">Diseño</text><text x="672" y="106">Prueba</text></g> <g text-anchor="middle" font-size="11" fill="#5b6876"><text x="90" y="126">Coordinación médica:</text><text x="90" y="142">cupo por profesional</text><text x="285" y="126">RQ-10: mostrar el día</text><text x="285" y="142">como no disponible</text><text x="480" y="126">Componente</text><text x="480" y="142">reglas de cupo</text><text x="672" y="126">PR-03: cuatro</text><text x="672" y="142">ejemplos de frontera</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u4t2d)"><path d="M172,110 L202,110"></path><path d="M367,110 L397,110"></path><path d="M562,110 L592,110"></path></g> <text x="380" y="62" font-size="11.5" font-weight="600" fill="#12324f" text-anchor="middle">Hacia adelante: de la necesidad a la evidencia</text> <g fill="none" stroke="#0e6f6c" stroke-width="1.8" marker-end="url(#u4t2e)"><path d="M672,170 C672,215 90,215 90,172"></path></g> <text x="380" y="235" font-size="11.5" font-weight="600" fill="#0e6f6c" text-anchor="middle">Hacia atrás: de la prueba a quién lo pidió</text>
</svg>
</div>
</section>
<section id="ejemplo-resuelto-la-rtm-de-los-once-requisitos" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-la-rtm-de-los-once-requisitos">Ejemplo resuelto: la RTM de los once requisitos</h3>
<p>Con los once requisitos del paso 4 se arma la matriz. Las fuentes son REC (recepción), PAC (pacientes), COO (coordinación médica) y GER (gerencia). Los componentes son el buscador, la agenda, las notificaciones, las reglas de cupo y la interfaz del paciente. Todo el contenido es ilustrativo.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Req</th>
<th>Fuente</th>
<th>Componente</th>
<th>Prueba</th>
<th>Método</th>
<th>Verificación</th>
<th>Validación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RQ-01</td>
<td>REC</td>
<td>Buscador</td>
<td>PC-01</td>
<td>Prueba</td>
<td>Pasó</td>
<td>Aprobado</td>
</tr>
<tr class="even">
<td>RQ-02</td>
<td>PAC</td>
<td>Agenda</td>
<td>PA-01 y PA-02</td>
<td>Prueba</td>
<td>Pasó</td>
<td>Aprobado</td>
</tr>
<tr class="odd">
<td>RQ-03</td>
<td>PAC</td>
<td>Notificaciones</td>
<td>PN-01</td>
<td>Prueba</td>
<td>Pendiente</td>
<td>Aprobado</td>
</tr>
<tr class="even">
<td>RQ-04</td>
<td>PAC</td>
<td>Agenda</td>
<td>PA-03</td>
<td>Prueba</td>
<td>Pasó</td>
<td>Aprobado</td>
</tr>
<tr class="odd">
<td>RQ-05</td>
<td>REC</td>
<td>Agenda</td>
<td>PA-04</td>
<td>Prueba</td>
<td>Pasó</td>
<td>Aprobado</td>
</tr>
<tr class="even">
<td>RQ-06</td>
<td>PAC</td>
<td>Buscador</td>
<td>PB-01</td>
<td>Prueba</td>
<td>Pasó</td>
<td>Aprobado</td>
</tr>
<tr class="odd">
<td>RQ-07</td>
<td>COO</td>
<td>Buscador</td>
<td>Sin prueba</td>
<td>Prueba</td>
<td>Sin ejecutar</td>
<td>Aprobado</td>
</tr>
<tr class="even">
<td>RQ-08</td>
<td>COO</td>
<td>Reglas de cupo</td>
<td>PR-01</td>
<td>Demostración</td>
<td>Pasó</td>
<td>Aprobado</td>
</tr>
<tr class="odd">
<td>RQ-09</td>
<td>COO</td>
<td>Reglas de cupo</td>
<td>PR-02</td>
<td>Inspección</td>
<td>Pasó</td>
<td>Aprobado</td>
</tr>
<tr class="even">
<td>RQ-10</td>
<td>COO</td>
<td>Reglas de cupo y buscador</td>
<td>PR-03</td>
<td>Prueba</td>
<td>Pasó</td>
<td>Aprobado</td>
</tr>
<tr class="odd">
<td>RQ-11</td>
<td>PAC</td>
<td>Interfaz del paciente</td>
<td>PU-01</td>
<td>Prueba con usuarios</td>
<td>Pendiente</td>
<td>Pendiente</td>
</tr>
</tbody>
</table>
<p>Además hay dos elementos que no aparecen en ninguna fila: la prueba PX-09, “el logotipo se muestra en la pantalla de inicio”, y el componente “módulo de encuestas”, que alguien construyó por iniciativa propia.</p>
</section>
<section id="cómo-se-lee-la-matriz" class="level3">
<h3 class="anchored" data-anchor-id="cómo-se-lee-la-matriz">Cómo se lee la matriz</h3>
<p>Se calculan cuatro indicadores contando filas.</p>
<ol type="1">
<li>Cobertura de pruebas. Los requisitos con al menos una prueba definida son 10 de 11 (todos menos RQ-07), es decir 10 / 11 = 90,9 %.</li>
<li>Verificación aprobada. Pasaron la verificación 8 de 11 (RQ-01, 02, 04, 05, 06, 08, 09 y 10), es decir 8 / 11 = 72,7 %.</li>
<li>Validación aprobada. Están aprobados 10 de 11 (todos menos RQ-11), es decir 10 / 11 = 90,9 %.</li>
<li>Elementos huérfanos. Una prueba (PX-09) y un componente (módulo de encuestas) que no responden a ningún requisito.</li>
</ol>
<p>Con eso se toman decisiones concretas. RQ-07 necesita una prueba, y el escenario de pacientes crónicos del paso 4 ya la describe. RQ-03 y RQ-11 tienen pruebas definidas pero sin ejecutar. PX-09 se elimina o se justifica con un requisito. Y el módulo de encuestas se detiene hasta que alguien lo respalde con una necesidad, porque es trabajo que nadie pidió y que hay que mantener.</p>
</section>
<section id="costos-y-buenas-prácticas" class="level3">
<h3 class="anchored" data-anchor-id="costos-y-buenas-prácticas">Costos y buenas prácticas</h3>
<p>Mantener una RTM cuesta trabajo, y una RTM desactualizada es peor que ninguna porque da una falsa seguridad. Estas prácticas la mantienen útil.</p>
<ul>
<li>Dar a cada requisito un identificador único que nunca se reutilice, aunque el requisito se elimine.</li>
<li>Registrar la fuente al crear el requisito, no después.</li>
<li>Actualizar la matriz en el mismo momento en que se cambia un requisito, una prueba o un componente.</li>
<li>Empezar con una hoja de cálculo en un proyecto pequeño, y pasar a una herramienta de gestión de requisitos cuando los vínculos sean tantos que no se puedan mantener a mano.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 5. Calcula la cobertura de esta matriz
</div>
</div>
<div class="callout-body-container callout-body">
<p>Un proyecto tiene seis requisitos (R1 a R6) y siete pruebas con estos vínculos: PT-1 y PT-2 prueban R1, PT-3 prueba R2, PT-4 prueba R4, PT-5 no tiene requisito, PT-6 prueba R5 y PT-7 prueba R6. Calcula la cobertura de pruebas, nombra el requisito sin prueba y la prueba huérfana, y di qué harías con cada uno.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Los requisitos con prueba son R1, R2, R4, R5 y R6, es decir 5 de 6. La cobertura es 5 / 6 = 83,3 %.</p>
<p>El requisito sin prueba es R3. Hay que definir su método de verificación y escribir la prueba, o decidir con quien lo pidió si el requisito sigue siendo necesario. La prueba huérfana es PT-5. O prueba algo que sí importa y falta el requisito que lo respalde, o es una prueba innecesaria que se elimina. En el primer caso, el hallazgo es un requisito que faltaba y que la matriz acaba de revelar.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-8.-gestión-de-cambios-de-requisitos" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="parte-8.-gestión-de-cambios-de-requisitos"><span class="header-section-number">11</span> Parte 8. Gestión de cambios de requisitos</h2>
<section id="por-qué-cambian-los-requisitos" class="level3">
<h3 class="anchored" data-anchor-id="por-qué-cambian-los-requisitos">Por qué cambian los requisitos</h3>
<p>Los requisitos cambian porque el negocio cambia, porque el equipo entiende mejor el problema con el tiempo y porque la validación descubre cosas. Un cambio no es una falla del proceso. Lo que sí es una falla es aceptarlo sin saber qué afecta, sin que nadie lo apruebe y sin que quede registrado.</p>
</section>
<section id="el-proceso-de-seis-pasos" class="level3">
<h3 class="anchored" data-anchor-id="el-proceso-de-seis-pasos">El proceso de seis pasos</h3>
<div class="diagrama">
<svg viewbox="0 0 760 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Seis pasos para gestionar un cambio de requisitos: registrar la solicitud, analizar el impacto con la matriz de trazabilidad, decidir con quien tiene autoridad, implementar el cambio, reverificar y revalidar lo afectado, y actualizar la matriz y la versión" font-family="Segoe UI, Inter, system-ui, sans-serif">
<defs><marker id="u4t2f" markerwidth="10" markerheight="10" refx="8" refy="3.2" orient="auto"><path d="M0,0 L8,3.2 L0,6.4 z" fill="#8fb3d1"></path></marker></defs> <text x="380" y="18" font-size="13.5" font-weight="700" fill="#12324f" text-anchor="middle">Cómo entra un cambio a la línea base</text> <g fill="#fdf3d6" stroke="#e6cf8f"><rect x="2" y="50" width="106" height="80" rx="10"></rect><rect x="133" y="50" width="106" height="80" rx="10"></rect><rect x="264" y="50" width="106" height="80" rx="10"></rect></g> <g fill="#e4f2f1" stroke="#8fc9c5"><rect x="390" y="50" width="106" height="80" rx="10"></rect><rect x="521" y="50" width="106" height="80" rx="10"></rect><rect x="652" y="50" width="106" height="80" rx="10"></rect></g> <g text-anchor="middle" font-size="12" font-weight="700" fill="#12324f"><text x="55" y="76">1. Registrar</text><text x="186" y="76">2. Analizar</text><text x="317" y="76">3. Decidir</text><text x="443" y="76">4. Hacer</text><text x="574" y="76">5. Comprobar</text><text x="705" y="76">6. Actualizar</text></g> <g text-anchor="middle" font-size="10.5" fill="#5b6876"><text x="55" y="96">solicitud con</text><text x="55" y="110">quién y por qué</text><text x="186" y="96">impacto con la</text><text x="186" y="110">matriz RTM</text><text x="317" y="96">quien tiene la</text><text x="317" y="110">autoridad</text><text x="443" y="96">cambia el texto</text><text x="443" y="110">y lo construido</text><text x="574" y="96">verificar y</text><text x="574" y="110">revalidar lo afectado</text><text x="705" y="96">matriz, versión</text><text x="705" y="110">y registro</text></g> <g fill="none" stroke="#8fb3d1" stroke-width="1.8" marker-end="url(#u4t2f)"><path d="M110,90 L131,90"></path><path d="M241,90 L262,90"></path><path d="M372,90 L388,90"></path><path d="M498,90 L519,90"></path><path d="M629,90 L650,90"></path></g> <text x="380" y="170" font-size="11.5" fill="#5b6876" text-anchor="middle">Los tres primeros pasos son decisiones, y los tres últimos son evidencia.</text>
</svg>
</div>
<ol type="1">
<li>Registrar la solicitud. Quién pide el cambio, qué cambia y por qué. Sin solicitud escrita no hay cambio.</li>
<li>Analizar el impacto. Usar la RTM para listar los requisitos, el diseño y las pruebas afectados.</li>
<li>Decidir. Una persona o un comité con autoridad acepta, rechaza o aplaza. En proyectos grandes se llama comité de control de cambios.</li>
<li>Implementar. Cambiar el texto del requisito y lo construido.</li>
<li>Comprobar. Volver a verificar y a validar solo lo afectado.</li>
<li>Actualizar. Matriz, versión de la línea base y registro de cambios.</li>
</ol>
<p>La <em>línea base</em> de requisitos es el conjunto aprobado en un momento dado. Todo cambio posterior se hace sobre ella y deja versión. La gestión de configuración, que se estudió entre las actividades de SQA en la Unidad 2, es la disciplina que mantiene esas versiones.</p>
</section>
<section id="ejemplo-resuelto-el-cupo-de-pediatría-sube-de-20-a-24" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-el-cupo-de-pediatría-sube-de-20-a-24">Ejemplo resuelto: el cupo de Pediatría sube de 20 a 24</h3>
<p>Gerencia (GER) pide que el cupo diario de Pediatría suba de 20 a 24 turnos por profesional, porque las consultas de Pediatría pasaron a durar 15 minutos. Se sigue el proceso.</p>
<ol type="1">
<li>Registrar. Solicitud CR-01. Origen: GER. Motivo: consultas de 15 minutos.</li>
<li>Analizar el impacto con la RTM. Se busca el requisito del cupo inicial, que es RQ-09. Hacia adelante: componente reglas de cupo, pruebas PR-02 (valores iniciales) y PR-03 (los ejemplos de frontera). Hacia atrás: la fuente de RQ-09 es COO, así que COO debe validar el cambio.</li>
<li>Verificar la viabilidad con un cálculo. Con 24 turnos de 15 minutos, 24 x 15 = 360 minutos, 6 horas, dentro de una jornada de 8 horas. El cambio es factible.</li>
<li>Decidir. COO acepta.</li>
<li>Implementar y comprobar. Como RQ-08 hizo configurable el cupo por especialidad, el cambio es de configuración y no de código. Se actualiza el texto de RQ-09 y los datos de PR-02. En PR-03, los ejemplos de Pediatría pasan de 19 y 20 a 23 y 24.</li>
<li>Actualizar. La línea base pasa de la versión 1.0 a la 1.1.</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Elemento</th>
<th>Cantidad</th>
<th>Detalle</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Requisitos que cambian de texto</td>
<td>1</td>
<td>RQ-09</td>
</tr>
<tr class="even">
<td>Requisitos con datos de prueba nuevos</td>
<td>1</td>
<td>RQ-10, por PR-03</td>
</tr>
<tr class="odd">
<td>Componentes afectados</td>
<td>1</td>
<td>Reglas de cupo</td>
</tr>
<tr class="even">
<td>Pruebas afectadas</td>
<td>2</td>
<td>PR-02 y PR-03</td>
</tr>
<tr class="odd">
<td>Requisitos sin cambio</td>
<td>9</td>
<td>Los demás</td>
</tr>
</tbody>
</table>
<p>Sin la RTM, el equipo habría tenido que adivinar el alcance y probablemente habría repasado los once requisitos. Con ella revisa dos pruebas. Y fíjate en el efecto de una decisión anterior: RQ-08, escrito para resolver la contradicción de RO-4 y RO-5, es la razón por la que este cambio no toca el código.</p>
<p>Un registro de cambios mínimo tiene estas columnas.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Versión</th>
<th>Cambio</th>
<th>Solicitud</th>
<th>Origen</th>
<th>Aprobó</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.0</td>
<td>Línea base inicial, once requisitos</td>
<td>Sin solicitud</td>
<td>Pasos 1 a 4</td>
<td>Equipo y COO</td>
</tr>
<tr class="even">
<td>1.1</td>
<td>RQ-09: el cupo de Pediatría pasa de 20 a 24</td>
<td>CR-01</td>
<td>GER</td>
<td>COO</td>
</tr>
</tbody>
</table>
</section>
<section id="la-volatilidad-como-indicador" class="level3">
<h3 class="anchored" data-anchor-id="la-volatilidad-como-indicador">La volatilidad como indicador</h3>
<p>La <em>volatilidad</em> de los requisitos es la proporción de ellos que cambia en un periodo. En el ejemplo, 1 de 11 requisitos cambió de texto, es decir 1 / 11 = 9,1 %. Un porcentaje alto y sostenido es una señal de que la elicitación y la validación fueron insuficientes. Aun así, no existe un valor “normal”: hay que medirlo en el propio proyecto y mirar la tendencia, como se hace con cualquier métrica.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 6. Analiza un cambio con la RTM
</div>
</div>
<div class="callout-body-container callout-body">
<p>Los pacientes piden que el primer recordatorio llegue 72 horas antes del turno, y no 48. Con la matriz de la Parte 7, indica qué requisito, componente, prueba y fuente se afectan, y quién debe validar. Revisa después si el cambio deja un vacío en otro caso, pensando en los turnos que se asignan con poca anticipación.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>El requisito afectado es RQ-03. El componente es notificaciones, la prueba es PN-01 y la fuente es PAC, así que son los pacientes quienes deben validar. Los otros diez requisitos no cambian de texto.</p>
<p>El vacío aparece con un turno que se asigna con menos de 72 horas de anticipación. Con la nueva regla, el primer recordatorio ya habría vencido y ese paciente solo recibiría el segundo, el de 2 horas antes. Hay que agregar o aclarar un requisito, por ejemplo que el sistema envíe el primer recordatorio en el momento de asignar un turno con menos de 72 horas de anticipación. Es un defecto de completitud que el cambio provocó. Por eso se vuelve a verificar lo afectado antes de congelar la nueva versión.</p>
</div>
</div>
</div>
</section>
</section>
<section id="parte-9.-inteligencia-artificial-para-redactar-y-revisar-requisitos" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="parte-9.-inteligencia-artificial-para-redactar-y-revisar-requisitos"><span class="header-section-number">12</span> Parte 9. Inteligencia artificial para redactar y revisar requisitos</h2>
<section id="para-qué-sirve-y-para-qué-no" class="level3">
<h3 class="anchored" data-anchor-id="para-qué-sirve-y-para-qué-no">Para qué sirve y para qué no</h3>
<p>Los modelos de lenguaje pueden ayudar a escribir y a revisar requisitos, porque trabajan con texto. Las tareas donde más ayudan son proponer una primera redacción a partir de notas, señalar términos vagos y cláusulas de escape, convertir un requisito a una plantilla EARS, sugerir escenarios Gherkin y detectar posibles contradicciones entre dos requisitos. Para cada una de esas tareas el criterio es el mismo: la salida es un borrador, y la verificación y la validación siguen siendo humanas.</p>
</section>
<section id="los-riesgos" class="level3">
<h3 class="anchored" data-anchor-id="los-riesgos">Los riesgos</h3>
<p>El perfil de IA generativa del NIST (NIST AI 600-1, julio de 2024) describe riesgos propios de estos sistemas. Tres de ellos pesan en el trabajo con requisitos.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Riesgo</th>
<th>Qué dice el NIST</th>
<th>Cómo aparece en los requisitos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Confabulación</td>
<td>El sistema genera y presenta con seguridad contenido falso o erróneo, y el riesgo crece cuando quien lo lee lo cree por el tono seguro</td>
<td>Un requisito inventado que parece razonable, o una cláusula de una norma que no existe</td>
</tr>
<tr class="even">
<td>Privacidad de datos</td>
<td>Los sistemas de IA generativa plantean riesgos de privacidad, y los modelos pueden filtrar, generar o inferir información sensible sobre personas</td>
<td>Pegar en un servicio externo notas con datos de pacientes o documentos confidenciales de la clínica, o recibir datos personales inferidos que nadie debería tener</td>
</tr>
<tr class="odd">
<td>Integridad de la información</td>
<td>La IA facilita producir y propagar contenido sin verificar</td>
<td>Un documento de requisitos largo y pulido, con vacíos que nadie notó porque se ve completo</td>
</tr>
</tbody>
</table>
<p>Hay un cuarto riesgo propio de este tema. Si la misma herramienta escribe el requisito y luego escribe sus pruebas a partir de ese texto, las dos salidas comparten la misma lectura equivocada, y una prueba que confirma un requisito mal entendido no encuentra nada. No es una cita de ninguna fuente. Es una consecuencia directa de que la verificación necesita una referencia independiente.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Lo que no se afirma en esta guía
</div>
</div>
<div class="callout-body-container callout-body">
<p>No se citan porcentajes de acierto de los modelos al redactar requisitos. En la consulta de octubre de 2026 no se pudo localizar y leer en fuente primaria un estudio que respalde una cifra concreta, y esos valores cambian con cada versión de los modelos. Quien quiera una cifra debe buscar el estudio, leer su método y mirar con qué modelo y con qué datos se midió.</p>
</div>
</div>
</section>
<section id="las-reglas-de-uso-seguro" class="level3">
<h3 class="anchored" data-anchor-id="las-reglas-de-uso-seguro">Las reglas de uso seguro</h3>
<ol type="1">
<li>La fuente manda. Todo requisito que proponga la IA necesita una fuente humana antes de entrar a la línea base: una persona, un documento o una norma que se pueda abrir. Sin fuente no hay trazabilidad hacia atrás y, por tanto, no hay requisito.</li>
<li>Se verifica con el mismo método. Un requisito generado pasa la misma tabla de cinco criterios del paso 2 que uno escrito por una persona.</li>
<li>Se validan con los interesados. El borrador no sustituye la conversación con quienes usarán la app.</li>
<li>Nada de datos sensibles. No se entregan a servicios externos datos personales de pacientes ni documentos confidenciales. Los datos de salud son sensibles según la Ley 1581 de 2012, como se vio en la Unidad 1. Se usan notas anonimizadas o datos inventados.</li>
<li>Las citas se comprueban. Toda norma, artículo o cifra que proponga la IA se abre en su fuente primaria antes de usarse. Si no se encuentra, no se usa.</li>
<li>Pruebas independientes. Las pruebas se derivan de los criterios de aceptación acordados con los interesados, y no del texto que la misma herramienta acaba de generar.</li>
<li>Se registra el uso. Anotar la herramienta, la versión y la fecha, y qué se aceptó y qué se rechazó, para poder revisarlo después.</li>
</ol>
</section>
<section id="ejemplo-resuelto-filtrar-la-propuesta-de-una-herramienta-de-ia" class="level3">
<h3 class="anchored" data-anchor-id="ejemplo-resuelto-filtrar-la-propuesta-de-una-herramienta-de-ia">Ejemplo resuelto: filtrar la propuesta de una herramienta de IA</h3>
<p>Esta salida se escribió para el ejercicio. No la generó ningún modelo real. Representa lo que una herramienta podría proponer a partir de la nota “los pacientes quieren cambiar su turno sin llamar a recepción”.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Propuesta</th>
<th>Se verifica</th>
<th>Fuente</th>
<th>Decisión</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P1. Cuando el paciente reprograme un turno, el sistema debe mostrarle los turnos libres de la misma especialidad.</td>
<td>Singular, verificable, completa</td>
<td>Nota de reunión con pacientes</td>
<td>Se acepta. Se une a RQ-05 como detalle</td>
</tr>
<tr class="even">
<td>P2. El sistema debe integrarse con WhatsApp Business para confirmar turnos.</td>
<td>Singular, pero sin valores</td>
<td>Ninguna: nadie lo pidió</td>
<td>Se rechaza. Sin fuente no entra. Si alguien lo pide, se registra como cambio</td>
</tr>
<tr class="odd">
<td>P3. El sistema debe permitir reprogramar un turno en cualquier momento.</td>
<td>Verificable</td>
<td>Nota de reunión</td>
<td>Se rechaza. Contradice RQ-04, que limita a 12 horas o más</td>
</tr>
<tr class="even">
<td>P4. El sistema debe ser intuitivo.</td>
<td>No: adjetivo</td>
<td>Ninguna</td>
<td>Se rechaza. Si el interesado quiere esto, se mide como RQ-11</td>
</tr>
<tr class="odd">
<td>P5. El sistema debe cumplir el artículo 15 de la Ley 1581 sobre reprogramaciones.</td>
<td>No se puede comprobar</td>
<td>Ninguna: la cita no existe</td>
<td>Se rechaza. Es una confabulación típica</td>
</tr>
</tbody>
</table>
<p>De cinco propuestas se aceptó una. Las otras cuatro se descartaron por tres causas distintas: sin fuente (P2 y P4), contradicción con el conjunto (P3) y cita falsa (P5). La IA ahorró el borrador de P1. La verificación y la validación humanas ahorraron cuatro defectos.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reto 7. Decide qué hacer con tres propuestas
</div>
</div>
<div class="callout-body-container callout-body">
<p>Una herramienta propone tres requisitos para la app. A: “El sistema debe enviar recordatorios.” B: “El sistema debe enviar el recordatorio por correo y por mensaje de texto, según lo que el paciente elija al registrarse, y debe registrar cuál canal se usó.” C: “El sistema debe cumplir la norma ISO 99999 de mensajería médica.” Aplica las reglas de uso seguro y decide qué haces con cada una.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Solución del Reto 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A no se verifica: no dice cuándo, a quién ni por qué canal. Se devuelve para reescribirla con la plantilla EARS, y de todos modos ya está cubierta por RQ-03.</p>
<p>B es más completa, pero mezcla dos exigencias, el envío según la elección del paciente y el registro del canal. Se parte en dos requisitos singulares. Antes de aceptarla se busca su fuente: si ningún interesado pidió elegir canal ni registrarlo, no entra a la línea base y se anota como propuesta.</p>
<p>C cita una norma cuyo número se inventó para el ejercicio. La regla 5 manda abrirla en su fuente primaria, y si no se encuentra se descarta. Un requisito que cite una norma inexistente no se puede verificar.</p>
</div>
</div>
</div>
</section>
</section>
<section id="errores-frecuentes" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="errores-frecuentes"><span class="header-section-number">13</span> Errores frecuentes</h2>
<ul>
<li>Confundir verificar con validar. Dar un documento por bueno porque está bien redactado, sin comprobar con los interesados que es lo que necesitan.</li>
<li>Escribir adjetivos como requisitos. “Rápido”, “fácil”, “seguro” y “robusto” no se pueden probar.</li>
<li>Mezclar varias exigencias en un requisito. Una frase con “y” y “o” suele esconder cuatro requisitos, como RO-2.</li>
<li>Resolver las contradicciones eligiendo un valor sin consultar. La inconsistencia es un hallazgo para el interesado, no una decisión del equipo.</li>
<li>Inventar un número para completar un requisito. Un dato pendiente se marca y se asigna a alguien.</li>
<li>Usar “debería” sin convención. Cuando nadie sabe si es obligatorio, nadie puede verificarlo.</li>
<li>Construir la RTM al final del proyecto, de memoria. Una matriz hecha tarde documenta lo que se supone que pasó, no lo que pasó.</li>
<li>Aceptar un cambio sin analizar su impacto. El costo del cambio rara vez está en el requisito que cambia, sino en lo que lo rodea.</li>
<li>Confiar en la salida de una IA porque suena segura. La seguridad del tono no es evidencia.</li>
<li>Medir el cumplimiento con el promedio. Un promedio esconde a los usuarios que sufren la cola de la distribución.</li>
</ul>
</section>
<section id="lo-que-sigue" class="level2" data-number="14">
<h2 data-number="14" class="anchored" data-anchor-id="lo-que-sigue"><span class="header-section-number">14</span> Lo que sigue</h2>
<p>El Tema 3 de esta unidad estudia los puntos de control y el costo de la calidad, donde los criterios de aceptación de este tema se convierten en la vara con que cada fase decide si el trabajo avanza. El Tema 5 estudia qué ocurre cuando dos requisitos no funcionales compiten, por ejemplo seguridad frente a usabilidad, y cómo se decide con el método ATAM.</p>
</section>
<section id="autoevaluación" class="level2" data-number="15">
<h2 data-number="15" class="anchored" data-anchor-id="autoevaluación"><span class="header-section-number">15</span> Autoevaluación</h2>
<p>Responde sin mirar la guía. Marca tu opción y abre la clave. Es una práctica formativa y no tiene nota.</p>
<p><strong>1.</strong> ¿Cuál de estas preguntas corresponde a la verificación de requisitos?</p>
<p><label><input type="checkbox"> ¿Los usuarios necesitan realmente esta función?</label> <label><input type="checkbox"> ¿El requisito está escrito de forma que admita una sola lectura y se pueda comprobar?</label> <label><input type="checkbox"> ¿El sistema construido cumple el requisito?</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. La primera es validación de requisitos. La tercera es verificación del sistema, que ocurre después de construir.</p>
</div>
</div>
</div>
<p><strong>2.</strong> Los requisitos RO-4 (“20 turnos por día a cada especialidad”) y RO-5 (“30 turnos por día en Medicina general”) son individualmente verificables. ¿Qué criterio falla al ponerlos juntos?</p>
<p><label><input type="checkbox"> Singular</label> <label><input type="checkbox"> Consistente</label> <label><input type="checkbox"> Factible</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Para Medicina general los dos requisitos dan valores distintos. Es un defecto de conjunto, que solo aparece al comparar requisitos.</p>
</div>
</div>
</div>
<p><strong>3.</strong> ¿Cuál es la edición vigente de la ISO/IEC/IEEE 29148 según la consulta de esta guía?</p>
<p><label><input type="checkbox"> La de 1998</label> <label><input type="checkbox"> La segunda edición, de noviembre de 2018</label> <label><input type="checkbox"> La de 2026, que ya la sustituyó</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Los catálogos consultados la listan como vigente y en revisión. No se verificó que exista una edición más nueva.</p>
</div>
</div>
</div>
<p><strong>4.</strong> ¿Cuál de estas es una cláusula de escape que vuelve un requisito inverificable?</p>
<p><label><input type="checkbox"> “Cuando el paciente confirme un horario libre”</label> <label><input type="checkbox"> “Si es posible”</label> <label><input type="checkbox"> “En 2 segundos o menos”</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Deja el cumplimiento a criterio de quien implementa. La regla R8 de INCOSE pide evitar estas cláusulas.</p>
</div>
</div>
</div>
<p><strong>5.</strong> Un requisito de desempeño dice “2 segundos o menos en el percentil 95”. ¿Qué significa el percentil 95?</p>
<p><label><input type="checkbox"> Que el promedio de las mediciones es 2 segundos</label> <label><input type="checkbox"> Que el 95 % de las mediciones debe estar dentro de 2 segundos</label> <label><input type="checkbox"> Que se hacen 95 mediciones</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. El percentil 95 protege a la cola de la distribución, que el promedio esconde.</p>
</div>
</div>
</div>
<p><strong>6.</strong> Con 30 días en el mes, una disponibilidad de 99,9 % permite una caída de:</p>
<p><label><input type="checkbox"> 43,2 minutos</label> <label><input type="checkbox"> 7,2 horas</label> <label><input type="checkbox"> 4,32 minutos</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 1. El mes tiene 720 horas, el 0,1 % es 0,72 horas y 0,72 x 60 = 43,2 minutos.</p>
</div>
</div>
</div>
<p><strong>7.</strong> En una matriz de trazabilidad, ¿qué indica una prueba que no está vinculada a ningún requisito?</p>
<p><label><input type="checkbox"> Que la prueba es la más importante</label> <label><input type="checkbox"> Una prueba huérfana: o falta un requisito que la respalde, o la prueba sobra</label> <label><input type="checkbox"> Que el requisito ya fue validado</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Una prueba huérfana es una señal de trabajo sin respaldo en una necesidad.</p>
</div>
</div>
</div>
<p><strong>8.</strong> En el cambio CR-01, ¿por qué se revisaron solo dos pruebas y no las de los once requisitos?</p>
<p><label><input type="checkbox"> Porque las otras no importan</label> <label><input type="checkbox"> Porque la matriz mostró que solo RQ-09 y RQ-10 se afectaban, y sus pruebas son PR-02 y PR-03</label> <label><input type="checkbox"> Porque el cambio fue pequeño</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. La trazabilidad hacia adelante permite acotar el alcance del cambio con evidencia.</p>
</div>
</div>
</div>
<p><strong>9.</strong> Una herramienta de IA propone el requisito “El sistema debe cumplir el artículo 15 de la Ley 1581”. ¿Qué se hace primero?</p>
<p><label><input type="checkbox"> Se acepta, porque suena legal</label> <label><input type="checkbox"> Se abre la ley en una fuente primaria y se comprueba que la cita existe y dice eso</label> <label><input type="checkbox"> Se le pide a la misma herramienta que lo confirme</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Pedirle a la misma herramienta que se confirme a sí misma no aporta una referencia independiente.</p>
</div>
</div>
</div>
<p><strong>10.</strong> ¿Qué hallazgo solo puede producir la validación de requisitos y no la verificación?</p>
<p><label><input type="checkbox"> Un requisito con una palabra vaga</label> <label><input type="checkbox"> Un requisito faltante, como el de continuidad con el mismo médico, que ninguna lista de chequeo sobre el texto podía detectar</label> <label><input type="checkbox"> Una frase con dos exigencias</label></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Clave de la pregunta 10
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>La opción 2. Lo que falta no se ve revisando lo que está escrito. Lo descubre quien conoce el uso real.</p>
</div>
</div>
</div>
</section>
<section id="lo-que-te-llevas" class="level2" data-number="16">
<h2 data-number="16" class="anchored" data-anchor-id="lo-que-te-llevas"><span class="header-section-number">16</span> Lo que te llevas</h2>
<div class="checklist">
<p><strong>Al salir de este tema deberías poder explicar, sin mirar la guía</strong></p>
<ul class="task-list">
<li><label><input type="checkbox">Qué establece la ISO/IEC/IEEE 29148:2018 y qué tan segura es su vigencia</label></li>
<li><label><input type="checkbox">Las características de un requisito individual y de un conjunto de requisitos</label></li>
<li><label><input type="checkbox">La diferencia entre verificación y validación de requisitos, con una pregunta y un ejemplo de cada una</label></li>
<li><label><input type="checkbox">Los tres sentidos de la palabra verificación y los cuatro métodos para verificar un requisito</label></li>
<li><label><input type="checkbox">Cómo se encuentran, se reescriben y se validan seis requisitos mal escritos</label></li>
<li><label><input type="checkbox">Qué es un criterio de aceptación en Gherkin y por qué el valor de frontera es el más valioso</label></li>
<li><label><input type="checkbox">La plantilla de seis elementos de un requisito no funcional medible</label></li>
<li><label><input type="checkbox">Cómo se arma una RTM, cómo se calcula su cobertura y cómo se usa para analizar un cambio</label></li>
<li><label><input type="checkbox">Los seis pasos para gestionar un cambio de requisitos</label></li>
<li><label><input type="checkbox">Siete reglas para usar la IA con requisitos sin perder la trazabilidad</label></li>
</ul>
</div>
</section>
<section id="glosario" class="level2" data-number="17">
<h2 data-number="17" class="anchored" data-anchor-id="glosario"><span class="header-section-number">17</span> Glosario</h2>
<ul>
<li><strong>Requisito.</strong> Declaración de una capacidad, característica o restricción que el producto debe cumplir y que sirve para decidir si es aceptable.</li>
<li><strong>Requisito funcional.</strong> Lo que el sistema hace.</li>
<li><strong>Requisito no funcional.</strong> Cómo de bien lo hace: desempeño, seguridad, usabilidad, disponibilidad y otros atributos.</li>
<li><strong>Restricción.</strong> Condición impuesta que limita la solución.</li>
<li><strong>ISO/IEC/IEEE 29148.</strong> Norma de ingeniería de requisitos. Su edición vigente es la de 2018.</li>
<li><strong>Verificación de requisitos.</strong> Comprobar que los requisitos están bien escritos, uno por uno y como conjunto.</li>
<li><strong>Validación de requisitos.</strong> Comprobar con los interesados que los requisitos expresan lo que se necesita.</li>
<li><strong>Verificabilidad.</strong> Característica de un requisito que indica que existe un método para comprobar su cumplimiento.</li>
<li><strong>Singular.</strong> Que exige una sola cosa.</li>
<li><strong>Ambigüedad.</strong> Posibilidad de leer un requisito de más de una manera.</li>
<li><strong>Completitud.</strong> Que un requisito, o un conjunto, dice todo lo necesario: condiciones, valores y casos.</li>
<li><strong>Consistencia.</strong> Que ningún requisito contradice a otro ni usa un término con dos sentidos.</li>
<li><strong>Cláusula de escape.</strong> Expresión como “si es posible” que deja el cumplimiento a criterio de quien implementa.</li>
<li><strong>GtWR.</strong> <em>Guide to Writing Requirements</em> de INCOSE, versión 4 de 2023, con 42 reglas.</li>
<li><strong>EARS.</strong> Plantilla de redacción de requisitos con cinco patrones: ubicuo, por evento, por estado, característica opcional y comportamiento no deseado.</li>
<li><strong>Inspección, demostración, prueba y análisis.</strong> Los cuatro métodos para verificar un requisito.</li>
<li><strong>BDD.</strong> Desarrollo guiado por comportamiento: se especifica con ejemplos concretos que luego se automatizan.</li>
<li><strong>Gherkin.</strong> Lenguaje de texto con las palabras Dado, Cuando y Entonces para escribir ejemplos.</li>
<li><strong>Criterio de aceptación.</strong> Condición concreta y observable que se debe cumplir para dar un requisito por satisfecho.</li>
<li><strong>Mapa de ejemplos.</strong> Técnica de conversación con tarjetas de cuatro colores para descubrir reglas, ejemplos y preguntas.</li>
<li><strong>Percentil 95.</strong> Valor bajo el cual queda el 95 % de las mediciones.</li>
<li><strong>Disponibilidad.</strong> Proporción del tiempo en que un servicio funciona.</li>
<li><strong>Trazabilidad.</strong> Capacidad de seguir la vida de un requisito hacia atrás, a su origen, y hacia adelante, a su diseño y sus pruebas.</li>
<li><strong>RTM.</strong> Matriz de trazabilidad de requisitos: tabla que registra los vínculos entre requisitos y otros elementos.</li>
<li><strong>Prueba huérfana.</strong> Prueba sin requisito que la respalde.</li>
<li><strong>Gold plating.</strong> Trabajo que ningún requisito pidió.</li>
<li><strong>Línea base.</strong> Conjunto de requisitos aprobado en un momento dado, sobre el que se hacen los cambios.</li>
<li><strong>Volatilidad de requisitos.</strong> Proporción de requisitos que cambia en un periodo.</li>
<li><strong>Confabulación.</strong> Fenómeno por el que un sistema de IA generativa produce y presenta con seguridad contenido falso.</li>
</ul>
</section>
<section id="bibliografía" class="level2" data-number="18">
<h2 data-number="18" class="anchored" data-anchor-id="bibliografía"><span class="header-section-number">18</span> Bibliografía</h2>
<p>Normas y guías de requisitos:</p>
<ul>
<li>ISO/IEC/IEEE 29148:2018. <em>Systems and software engineering, Life cycle processes, Requirements engineering</em> (2.a ed.). Norma de pago. <a href="https://www.iso.org/standard/72089.html">Ficha de ISO</a>. Estado consultado en el <a href="https://knowledge.bsigroup.com/products/systems-and-software-engineering-life-cycle-processes-requirements-engineering">catálogo de BSI</a>.</li>
<li>INCOSE (2023). <em>Guide to Writing Requirements</em>, versión 4, INCOSE-TP-2010-006-04. Documento de la tienda de INCOSE. <a href="https://www.incose.org/docs/default-source/working-groups/requirements-wg/guidetowritingrequirements/gtwr-v4-overview-081723.pdf">Presentación del grupo de trabajo</a>.</li>
<li>ISO 9000:2015. <em>Quality management systems, Fundamentals and vocabulary.</em> Paráfrasis de las definiciones de verificación y validación. Confirmar la edición vigente en iso.org.</li>
<li>Mavin, A., Wilkinson, P., Harwood, A. y Novak, M. (2009). Easy Approach to Requirements Syntax (EARS). <em>17th IEEE International Requirements Engineering Conference (RE’09)</em>. Descripción de las plantillas en <a href="https://en.wikipedia.org/wiki/Easy_Approach_to_Requirements_Syntax">Wikipedia</a>.</li>
<li>IEEE Computer Society (2024). <em>Guide to the Software Engineering Body of Knowledge (SWEBOK), versión 4.0</em>, con Software Requirements como área de conocimiento 1. <a href="https://www.computer.org/education/bodies-of-knowledge/software-engineering">Página oficial</a>.</li>
<li>Sommerville, I. (2016). <em>Software Engineering</em> (10.a ed.). Pearson. Capítulo 4, ingeniería de requisitos.</li>
</ul>
<p>BDD, Gherkin y trazabilidad:</p>
<ul>
<li>North, D. (marzo de 2006). Introducing BDD. <em>Better Software</em>. <a href="https://dannorth.net/introducing-bdd/">Artículo</a>.</li>
<li>Cucumber. <a href="https://cucumber.io/docs/gherkin/reference">Referencia de Gherkin</a> y <a href="https://cucumber.io/docs/bdd/">BDD según Cucumber</a>.</li>
<li>Wynne, M. (8 de diciembre de 2015). Introducing Example Mapping. <a href="https://cucumber.io/blog/bdd/example-mapping-introduction/">Blog de Cucumber</a>.</li>
<li>Gotel, O. y Finkelstein, A. (1994). An Analysis of the Requirements Traceability Problem. <em>Proceedings of the First International Conference on Requirements Engineering</em>. Definición consultada en la entrada de <a href="https://en.wikipedia.org/wiki/Requirements_traceability">requirements traceability en Wikipedia</a>, que recoge la lista de estándares que la exigen.</li>
</ul>
<p>Inteligencia artificial:</p>
<ul>
<li>NIST (julio de 2024). <em>Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile</em>, NIST AI 600-1. <a href="https://doi.org/10.6028/NIST.AI.600-1">Documento</a>.</li>
<li>Congreso de Colombia (2012). <em>Ley Estatutaria 1581 de 2012.</em> <a href="https://www.funcionpublica.gov.co/eva/gestornormativo/norma.php?i=49981">Texto</a>.</li>
</ul>
<p>Otras fuentes de apoyo consultadas: <a href="https://en.wikipedia.org/wiki/Requirement">Wikipedia, Requirement</a> y <a href="https://en.wikipedia.org/wiki/Software_requirements_specification">Wikipedia, Software requirements specification</a>, para las características de calidad de los requisitos.</p>
<div class="pie-doc">
<p>Calidad del software (CDS01). Fundación Universitaria María Cano. Facultad de Ingeniería. Semestre 2026-02.</p>
<p><strong>Transparencia.</strong> La redacción de esta guía contó con el apoyo de inteligencia artificial, usando el modelo Claude Sonnet 5 de Anthropic. Todo el contenido fue revisado y validado.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oscarleosanchez\.github\.io\/sitio-maria-cano-2026-02\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Oscar Leonel Sánchez Conde</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>